nfs:
  enabled: true
  pv:
    enabled: true
    # from https://docs.aws.amazon.com/efs/latest/ug/mounting-fs-nfs-mount-settings.html
jupyterhub:
  scheduling:
    userScheduler:
      enabled: true
  hub:
    config:
      JupyterHub:
        authenticator_class: github
