grafana_token: ENC[AES256_GCM,data:0UUAVco8fej9Mzjc7KqNKuycIju8erXsMYkRrTcAUsCugicHj0Q8yu/wU/0m8g==,iv:vFdANmJV/wCTz3aQPp8QUVr6k6wRkN5uMHNzukd97Ik=,tag:mCq/5dKIh37fARY44pfHWA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T10:31:59Z'
    enc: CiUA4OM7eM3cFpLARar7wSefGE14Qp8BwekhuymYnlSzCGTz/WBEEkkAPHlbmVkzqr0PDZhQ7UZ4YXeav0Yrf7DVS3VIahVoG/468y/Ptf80fsuxFjj4wlAlZQp3NZPBtZ9QUvP3EYnps0f6iAvpEdDT
  lastmodified: '2026-05-01T10:31:59Z'
  mac: ENC[AES256_GCM,data:ge3G6uESpXsUc8HtuxJpqlqLiQqDcAVNJlB2JJ4XeyH8YJJa4KIhRCxXZaSt0q7mDK3M0kYoh41/3Dklidb2Ukm/+L/I8Phm6uQwF9oWnHTkLKd9oHICw4r/BIJOd1l7jB2xqejQjp3FSsAs4Erv79TbIBqs9L7KDBAAc5kZqyI=,iv:FvqOjgOj3ebAXor1ZzyJIxwgMJbMFPHkLKw/Ojqz130=,tag:WTExOBz79GTsinnLY12gig==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
