jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:aQhzSawpQpcPXjdTkOzkO7YtZ8w=,iv:VsfCUsLARAxd8Y+QNreMenqPXbHnCBa44fPHvmXtdCs=,tag:tMNkRyHGf51aDNaF+nCg9A==,type:str]
        client_secret: ENC[AES256_GCM,data:y1bSl7YiYfa4cLrk4v7kjvIZQo0szYu4DpE4Vft61C8JeAx/ach6IA==,iv:Gzxt4GesymnMcCv6cwxwv7Mv9brUxPXbBnmsPaUpZvM=,tag:Lg43Xs8spVhxWq0G61vs7A==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:N9U5PaXa0zzR6goh43xqU4WvsAUO9pxfphRxtN3NjAPVtsRrOi8Z3KRLnZFGPAjyOtrI/8Xo3bUwZrEGrp1CvHaMyTTNBAmUxA5XJpEBN5wCf0K2Ufo=,iv:XOUBgdfDuvkTAZiU1iYwiHR1Dq17GQANzXa59fP2i6c=,tag:6iOE9HGsCgaHP5V2bcut9A==,type:str]
        stringData: ENC[AES256_GCM,data:04ElhwGu8DPianIgJHVeh3jYOoWoeIMKkGu+iXdVKTcTu48tedzt9+tSPQ7vwouSIzXe+8+3uHW4f+F9QrvsKQ2k4a0PedhebakUbEBbtO/XZk+e/ALli7Lt6pG69s0GoufvFO8iyClwHjLgouHz5UFBWOiBMsdCrPzHEx9iRrrb/pFeCnYrQeBbRQZJ3+qLsUGfAVL2U9eUKOxbmr7jZdCiLyPj/k7TD0E/NtodfT9PK7TQLxNe/ezSDxlTSk2b2B9D91P/XaOaQIcnlfsba23NVEDoU0i07pq/zEavA1Efa2UHKmWERa8+ED3bwK0TMrZz8STPQaAEeX06o02SS8ca8J3/rRxuOixaX5wwRXrLfqvqChRyMCHmdWeWis3dyeCKBJpCkittO9WJPCCOjZ4/S8tgtKk8Jkgp0zsIteyUfOeRgGEaxMPVv8PqLW3SaFeqr5gGBbNoVL9GMeCL5sGq/x5YaF02sFZfePYd26Y1cRd43iPAVs567pFyKGOQe80zXUFGe9Hi34NSnqXXzTy91RZg/TV5EDkh13ulfleXxh4yfRvJqLUZ1ZHJAySs4jeCxH/JDqubZ0ntxp95/93vWaPx9sZKCY0iVNxkxTKODRILevxfPz/BXrRpMPMskJFe/Y5XjB6BzhKvbQ==,iv:bsZXOdSJkwBheaHrIpHIfw8ANlPO/nb0Lo3SwKJWljk=,tag:3NL8sQZxjXP9rlVv+VvUNA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:16:08Z'
    enc: CiUA4OM7eF6Of+VbPLPekSNuSFHAv9+ymGGiGbprwQNnoJqgjgqOEkkAmy+ekisJweDV66CDG+KZPQehwj/5Rd01YQljwZV8lSPUeDxgWFAyabQeNjLaz4BNYgtbL0Pr4/la494ODfHS0ozdedAbrd6c
  lastmodified: '2026-07-29T19:16:08Z'
  mac: ENC[AES256_GCM,data:qlX2uyPGg1vj05pp0YbOjFh1uxL34N2PKbC9e5qLp83sm7AfiKvsJgT/5hHZRNHDAdewcKNXSyGLOWNH9NAr+uev+ruHE8q9yLxeX8hbxP00V0vA495PwKu5AEC/ZMx8BcYJh/T69IYUmcQsXFWZLw9/4IC5R/Vm1ZU/2FWhaP8=,iv:1nNa195/2g1JdEQx4mUGk6y6EdP+/91OXwSWcDi1w6E=,tag:HIk+muAOXnch4xMZ7Fbo+A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
