jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:AaZOcW1y1ylSpFxxvFMWyTwwmf5cW2amswSQyzKR7G64bhokmOhVJbVSp+1eDkK5awpT,iv:I0Z/ZZ/WsEInwQZ8vE9/6fAqyjgFj9jGqbhR1MmFc4U=,tag:owRRoPqWxSV0ePh99hEALA==,type:str]
        client_secret: ENC[AES256_GCM,data:UrPzgXcJX4ad71f+TImBJVsIJCnivhFR7EF2UKhPDcOm8ve0D78uNarxtj/4T1aC62N3+vvMhk71oefM1IwksKkR5EWI4iGbrV0uw65y2/18w01PvnU=,iv:6h7QrufCZxdyqvSuIFS+sZbUBpHWuM1qys9iO/FQ3wc=,tag:WZO0HO2DI1PqhrHPJcqZtQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-06-06T03:06:06Z'
    enc: CiUA4OM7eFHf2tsbsazBHjxmdH9+u1w2qtXLLYkKrezQ0j6IP135EkkAmy+eku8wBErkCgDm1bnri1mxIiglayfsE5H7J9cAh9i4VNEMK5gMN6VCECsevV9d6ZGl8Z+lIii/qeJJK9VLpVPTZ5otixXM
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-06-06T03:06:06Z'
  mac: ENC[AES256_GCM,data:7/pnMG7vf0YDyEey8SmLxklepHjkoC/un5UXte1ZFHGctA/kljfypm1pcu0LovYHBXIrbVCXLbqmS/8RKPWtVTofxE4iZo90qKFDwd7J/g+M/7IfRjjxwCFP790oPoS5KONnr7BMHX7DucXKnwgXEs/TcKHee/B7Jd8s1kuo6Ak=,iv:su1CoXtHuSyP0QCJDQVxYN2sQ1UVpiNHUfC555SQfzM=,tag:vgx7+PmUj3Cs18LiYJXDDA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
