basehub:
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:RDesaa0Wr6pnfklWU0BtoHaWw9g=,iv:C4bBjlkhdM7Xz87/QrEss6QP5ZRb+wPFArDLJCAZ+Ns=,tag:ivt931zOLG1xTsZ694WzKg==,type:str]
          client_secret: ENC[AES256_GCM,data:1IGyE4+VKCF6IiHHlCv4hhJLQphz2ax5oEUF4QXjSEQtZGzsU0s10Q==,iv://RLs5scN6NOL/XDmQAPkO+cTcDe2FLkWFS+Uj/+TJs=,tag:d0KTBJOdfdAcR+NFxjVUEA==,type:str]
sops:
  gcp_kms:
  - created_at: '2023-10-24T10:37:44Z'
    enc: CiUA4OM7eCQWEyht09mKKgbUxNyGoo+QsRZBAI6cVr2XWCEo/dCZEkkAq2nhVakyUtf6neyKXwWWxWPtq6iSLvuhHoswkNlxnuBBVxN1RSFeBEPy8b85Hj0FnSMBy0/tgqEwAbkp7wUz1MYTIbhdzqIo
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-10-08T11:44:11Z'
  mac: ENC[AES256_GCM,data:6HyK2YqEmgfHQ70xF2M17Q3LREKVnAq5iPth08tsbUD6cC8X4h8QP13oq6+gYI/pnSPFOMPIT/lNhXOjrodlnLFjKqMkTBj4ATF96i6+IiggQwi4A3B4F/qD/kbn9agPEZ4qwMLN5uA8KecOnbTV7RXV8gthw+lN5CQ9zkCCMPI=,iv:+S/I1fhr6iQW1RoZrEOuOJkhsU1irI0FiBftgP70cng=,tag:BXEDU7BQ1X38Qv7iuNYe9A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
