jupyterhub:
  imagePullSecret:
    create: ENC[AES256_GCM,data:6rfmKQ==,iv:ERoJRQQynEU4/VCfTHdWC2oaJL3pU9wNHC/JuxcVq5o=,tag:TCCZ9mI0xAQ48RUkTMXrsQ==,type:bool]
    registry: ENC[AES256_GCM,data:7T3zSbesqQ==,iv:x5zoEI7Pjh2z6A/Xmx/ksyfKsrI5Z1V44qdAxtrTahw=,tag:buoVsySSCw2kKFFUbAA7Ow==,type:str]
    username: ENC[AES256_GCM,data:aooMN5DbJlqw1+h6du1Sk0G5oAPJFo4IM+3nTzg//lT0WaG/HuseKQ==,iv:0iEt/pOZPH8KA3ovkKh99KMbu2mNqPkaBWEfUqPAAYs=,tag:sKhUCfwxM8wZ3UWV/PhneA==,type:str]
    password: ENC[AES256_GCM,data:jpqkrEr5DPpKPfyQTFNJ6KoiZ8ePo06HNE3FMFEz8dqEYLzpirFDVwIr2i6bFmFUxvU/zQvp9fb77kBpOJL7nQ==,iv:9JyAcmRWoNfDT9VyWFa+gLUt6U2MX/IGVmQtnKy2K9o=,tag:tqmiUzUJnkxRScaGF3kSIw==,type:str]
binderhub-service:
  buildPodsRegistryCredentials:
    password: ENC[AES256_GCM,data:3CRMM1Zu+wYjWuYyTxkd0AyQ9Pb7mgdoM1ziWdwg2M0oQYz5m8llAe4MVikkKq7bAeGfxw5RCQLuVqBW1ncy1Q==,iv:nAMggQJOHNeROO8BXISL/NAMgeJz8pWcwHNsQvArU6Y=,tag:qq5RRsdUQo3QSgVYqtpXTg==,type:str]
  config:
    DockerRegistry:
      password: ENC[AES256_GCM,data:WrhKnHFGqNBA7xhEaeID83/cU1MKNamZknvd8G2Nj9zOTYy94HESngeaqnQdckDQRck57OyJDvTudmQk+nr/tw==,iv:Qp3zZ2/gIIUPYPQ7iqGYe6mvMPIrkdaUXewDc7nYLXg=,tag:kc5fDMLeMQEq0IM+r7YxMg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2023-01-26T14:56:28Z'
    enc: CiUA4OM7eCKAfS822SeCDOvwyvK2He3x++XchB5U0Z2uRygrlE6PEkkA+0T9hQrtx2RjWzpuy8LDTafDdeFrNE1Ehco2aOXWi5EaMoT3PrOR9aaeynZo+a9RFNp3duwN37lnDIEBdrV0pxASZ+Ok1ct3
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-06-09T08:47:45Z'
  mac: ENC[AES256_GCM,data:2LBdfqICfPurkSh6RQ9yi/rsbyFABOJGUrHrD9g4B0zhk/RUrARp+T115woQC4677dSORNPdHvCN3WBoxM9GQxM1XSAVwopbooQR60L3JL8KJpnzPGKBTp+VGG22bZnWjqL3h9dyeqAudA3si1fAXQRVE7T3OeEyAqYijqGZHEc=,iv:Bpu+Go5ATqiq+1qMRRA0Qa9rPNpyThYcIsQr6hQ2d5o=,tag:YHhWxq66E4llVp4FN8ufjg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
