prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:ba1dirmDowV1fLDjq/W2FqqKmNK8MD7cVMil3Uo6PLxwAhpRDDIJ8bfO5l9gGFBMwojJZbtLhQaEb6EJg/nZCNXwd8wz/GoZpg1oa/AzuuPGQqfxXKiSjzS3y914FxbVqcQx97JB17lkPB07/c9G8Zn8wvzgtth7UsdfudGGQeLwN0kznrDVLPg8Hr5vVyCOir3f48z15lIDt/0I,iv:4Fx7/wRtJNhiBh1o87V/XVwH5Oh0YZxYr/uDbF6jSbw=,tag:twuK7UWRgukypZHw9nfsoA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:mli/lWm5vt7tGd3/1jc3sc0EebTN5LoomiA4YZyi7BKgFBbd4HDJMRn0KhflPF3+5R5VNA7n1Clx3NMViGXigQ==,iv:ccXXnffN2P0I5IDAWzZ6SuWIpXwRginxfIcoGm3u3uE=,tag:jnW78f2bs24pB4lUyEXF4w==,type:str]
    password: ENC[AES256_GCM,data:nPgbkjaYYiSqEWvMwYO+X4OO8wiILCCMKcRAp3y9YQAT7ZjMf1U+pM9Tbm0K1KXC87097z+kHL4714bW5SCoXw==,iv:FwZcXwOt5tFvNV6DpmLU9kRenq0uH1NbkZ1rXLXRjwI=,tag:Ng6olLlnWsoJy/kcl9nKOg==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:8Q==,iv:rS6yhYI7KtOjuaMlxsXkKiEwH7duUuKrEvO/QrljBfs=,tag:GjsR90vFkEMPsbmMqm7Jwg==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:xVmQ/HUKd+UakQ==,iv:iKnHHuph5Qo3Rv63sZUQZrgeGzQxjZIVbkRjLGe0AD4=,tag:HQtatIk2UdlJp7uW1CDb9A==,type:str]
        orgId: ENC[AES256_GCM,data:Mw==,iv:/uCoJTwDzc+3ttQsyqYHNBwUcwRrEL56rlm2x2lvUgo=,tag:yu283ywrb7ncgtgcx8mUiQ==,type:int]
        type: ENC[AES256_GCM,data:qI3rV3p0UOQoEg==,iv:cnU3U0yrkyPNqDvVzazjyePdzmDj8A5X0iWavDb9jEw=,tag:fXjHSo4tp62PGnpMzvAEXA==,type:str]
        url: ENC[AES256_GCM,data:fdDrD6J0I2PI1Iyyp+4VaDXvsZKKw4lIdV9sRXhAPMo=,iv:NRXVXPN2i08e4STgWfBFGPmV7B17XbBJgXsTvHivo9c=,tag:e/0JtRq1VkUuZb/LFQABKA==,type:str]
        access: ENC[AES256_GCM,data:KcacG2Y=,iv:BC2ehQgJIG61W3jamBkvoYbZlg26D20U/jOB619kgzs=,tag:CVQ8R3Sk+VPGhls3Yieqng==,type:str]
        isDefault: ENC[AES256_GCM,data:zQE7oZc=,iv:KknPB0HmjnxOVjsu1TrmqEqTMyzc6FA2zUa+YR4Epz4=,tag:r+3vs4XZMnVT9tJHtOY4bQ==,type:bool]
        editable: ENC[AES256_GCM,data:6iKGKe0=,iv:y7Aw+fAOhPsWezD1gcmAtzY2+PcnkOe2rs5QI60Tz1Y=,tag:PO7KK7zWcNpZajoIdPr5Dw==,type:bool]
        basicAuth: ENC[AES256_GCM,data:EfuGtA==,iv:ku71e/eBwEHOLF7L7Jk2quvB5DJCvguYzCxTLhNWcmE=,tag:1jqfHAMefBrQl/NPajhbkQ==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:mOMqmWCc5lyzjx+a82PjnihEhfBtd/bQqoUARehQWqaPXbOfRJ00qEWki/hfO+6jiapU+CBzqwCcUrZI6mQhyw==,iv:YNdcporH7rWs0m9GXyWrXcmaardBjuGXYRuW8BgXBok=,tag:jN4SWmNmNkjrXJVA8Md+0A==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:erifuLfTH6QMbx3EP8+VQ7StsEdLzm7fE4W9xlYdGnbW62KgqgkqmdiQSKiLzfHtCXNTENx5b+yMdeBWfoGY1w==,iv:9rVqVswEw49NO7KXXybEMTa0iwdYzdM8tJDYRPoU4so=,tag:FS2xtMGEJSy3+WCUkI4fhQ==,type:str]
      - name: ENC[AES256_GCM,data:aALauzG+8ccjRbWzQYRmYJt5f550pf/Bjl0RvVwdTg==,iv:KT9xTuaIDiewpa+7VbysimEWK+WjlvHyhQAn9GLFqUo=,tag:/FVHWSNfT/QlAV35OwXHYA==,type:str]
        type: ENC[AES256_GCM,data:OjufAWtzYLAaVDrDYHTvSe62fdUsqpVGscAJNznemA==,iv:BzXMPgpbZZ1eDqwk16mcn1bXoqL7rktffeAZDWAP/RM=,tag:Ve7IVmHR22t8k2b4Nef04Q==,type:str]
        isDefault: ENC[AES256_GCM,data:wuqPvhg=,iv:CeKR5ilLEwgyvP28s/2ckjTs6cBo5WLJDt3aoBJvTdg=,tag:emyt9sj4Ci0cb1aC6oqpzQ==,type:bool]
        editable: ENC[AES256_GCM,data:l13mGA==,iv:KcJkzmC0eN+VqdjPjVKAhyUiDTEeGEuVD0a9Wqb2XPM=,tag:XOWb+wTmbarguwvLrN7Mkw==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:9Cvvd6/WhFq843qOAA==,iv:2kJDIBA606PqED3UHxyTjAzilIu8te2Xe2+9V6w4aw4=,tag:Ieo/a+EJNIdMH60Cc8SpZQ==,type:str]
      value: ENC[AES256_GCM,data:rTb6heknP1ZAlI5MocphA8FBGLRN6Hcu6V4m2dtCSQ/JYiZKRYXsZUx4ZUr7zxkjlfKXU5Bc4+AKey+r5yussH9kmHihm1PqRhn4UtTFFQiMbVOv/BeKHujLHUX8oDzQWudZtdyvFv/tUbGBiHI8R4pVPv8Gwr4eNrFzk+uqkafOv3BfjHx+6eVK8QIfb8kLpaBSVJ9F3pFe8iB/XYhsKDkXpvzX+2Cf9wrpcG/a1PpBeg==,iv:F+Tswww2AC8lZbTVbw183M8p4wQI6NhwbKMcilULT5E=,tag:KatYq2wcTrEKUm/+hrNS5A==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:ahyAorFA2x8grAK1vabadERUDpY8Vfl9Kzp6AsPPs3IwRksBIcJLieFGd1/YDMbnq0GkSiKpt821iQNoqCNKWw==,iv:tesaOGgrb6jNjlhj0w5a9JviqbpgGT8yy6TmgIC8apM=,tag:tV24m/cinzDlZpIsNqrlFg==,type:str]
        password: ENC[AES256_GCM,data:bpbQ/RgjtIzQNiDL/kS5YwG6izeT2ayjqS4Nft1PzVjOdLalQKB9X7iglejCPtJu+Li5431O6yz1W/XkDjQCZA==,iv:JnHjRp1TpLfCA43eiTsW+JnXmzB82r+CQOgdoPBQhac=,tag:AzXHIxxj27G/zCL/QILl+g==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        hptZ5drzQA0LCXw7RMCMSBYt5KCPL1F45fUm72RGew3kDIIvkEJfIDvUGFFaBYe6: ENC[AES256_GCM,data:/Xh9U4Z7znGHCtQ5qkC39nBKLnQ1VexH5xu8k33KNTNURr4f/+immUfwscCW3q3P/NhRMkE4laO+cDow,iv:T9YztwN1dDZs2PTC4jmKDz+cq6dj7gFrpgmVS4OMEBM=,tag:W76iDZmImEsi7cpbAECGwA==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:HviYVQ==,iv:+vk9jrFPRkx89chjadbnb5qsZYwGagalqID0gNjWsAo=,tag:Zm/MqkKoKxCa9AD36W55nQ==,type:bool]
    username: ENC[AES256_GCM,data:jwcNJ4nFAX9xRduj7lRIPpex4WX6RqEsZSlbTs0jvg+VYDYZDoIiU86OJU++V0pyCXvmOVajT1RWErqqHDFwPA==,iv:Rj1GRanQu1jC8atHpYSnlmM5cP+u48HgIdPkHWlKZfw=,tag:13Z3agucR6zQykgOgzLcFw==,type:str]
    password: ENC[AES256_GCM,data:WnBFoJxdKL80mgAqpOEkGyNjeg0o5ZuBlyIYNiUijutlpcQmI21w+VTJ2YQZ0Bp1BfMvOBSL9QSA8ux/7md3Dw==,iv:exsH1fXeugP/RHyNS821JZm7B0Rqg8GEq4C/9k0taX4=,tag:5pXQMavfTV9Yu0XBy6euxw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:23Z'
    enc: CiUA4OM7eIfVexxs+8s1NB6ULfLkFPHJSnt2XfRh2Wk3wzKKqpEEEkkAPHlbmSYiR51xY1DYiSxnHRUXSTG7RvGL26HKdNl6+rQHzwCIHxufvzCFOJCc5izH5A/D8WpkbNjx/XtN6G/ewaDWwQ+dzHaz
  lastmodified: '2026-05-01T14:40:23Z'
  mac: ENC[AES256_GCM,data:4kVmdvEEZ0VLRSrhHbYhDCHQN6iASzuYPRirK132oyAKgVXfcxsGSOmtPDroByNZOAdg8QqDGxybBNxw2DkCOMnEQ7/6m8CTyhj+6YTjTIT8PA2Jm8d7N+ZNSJ8V1B6SCAaHgHf7vEdVb+t0iQ11bfj7KPwK2T8COFgn2h2rP44=,iv:dv63xCrfSNYW1meW5YUdZZAUQIZZ3ypYLse/Oxcgfx4=,tag:OXsr3swegjYkmtjLW6eIsg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
