jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:cCcFsREidFJE+8mNguzsiglaDNU=,iv:8/ONoisn8fresVPcztUejV5j1njBJe1TiyTPbzsl9ag=,tag:1zUsouNBoTdAAoVwZCrXNw==,type:str]
        client_secret: ENC[AES256_GCM,data:QVmzgFYEGKPgTrj6bCrumcQp5mZreLFrw6G+zITLOSJtydDY62zD/Q==,iv:nAdsoPGHyPhFzFPU4uxRAbQOm4fuZSD4IKtZYAHx3vU=,tag:jV9OsG1sy/OyOTUp7M9pvA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2023-01-05T15:13:06Z'
    enc: CiUA4OM7ePFTK8jhF1PvaNsOlsH2PwopRPJE7K+2pVikF/Brl4zPEkkA+0T9hUjgsZa2zAOVqZHOAjeg91553kP+YnHnIW2QPPnSha1dlGfrTcesxV5hsrbeqc3fxs7OnKow5KK3fr48Djf31CYGOgLY
  lastmodified: '2026-06-11T15:12:12Z'
  mac: ENC[AES256_GCM,data:p4Py5HQPrVHEe9P5n1jWvwA4fxa6mpOL/iSpxbJ4GMFIlqwLHe2+4Y/Wf9lDECl2xCWq3/euKKftzc0bEomc5IiuhYy0vd+aKQlSQnHPoNtoV54phbAeu/L5wx27GZpmgBYHXX6qxydGuTfM1fZYYSMxEbTk5UCdg76XOn+Ed/M=,iv:LQCo6dwubgoI1mvqoHL/10CkiLBjEpgjec7pc9exatU=,tag:2HvgDjDMBxSH0G8EhP+TVg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
