grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Cg==,iv:x+lP0d7vsUsk1Yjv8+cfQa3kM8597QY3jRzgxhLgeMM=,tag:HAgaD7e/CsV5EVhFcHyqHQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:+TKqgnwbUv8oDA==,iv:i9ylZdXyj+laH+hc17JJVRjdyNEv/ubDtriNooDJGvQ=,tag:ZfRxQqeeLBTHDMGOoOc5OA==,type:str]
        orgId: ENC[AES256_GCM,data:UQ==,iv:SbaQ9FR1v9pEBdujhfi6gngzz/b4ZUIz0R4XUz4sTSc=,tag:Wsr2QZlWt/VgCJz1XQHrSA==,type:int]
        type: ENC[AES256_GCM,data:/jaHUMFz6cQdEg==,iv:b7Z0N6yZ2pBuEgWpOvUle43rA6lChN7bjA4hv+MJmsU=,tag:kyXLuFLIOxomjEi8UDSNpA==,type:str]
        url: ENC[AES256_GCM,data:VxxP0A/CNFZ6PQrILqJepdM6uaCJH/vrl0LIOXgt0rg=,iv:oc0N8V65WeIuc2c73xb4MhvPRHL5f+3s2NXHi8eY7cQ=,tag:Xdichj1NrxNt++aNVwOVow==,type:str]
        access: ENC[AES256_GCM,data:3ldOaAw=,iv:Az0DYMO0tl1esgC1HYS+jIJwOSCfzh57BTg5xgT6quM=,tag:YwhVHZcRtJN7sC3UKloVmw==,type:str]
        isDefault: ENC[AES256_GCM,data:NB3fP3Q=,iv:5jOZVnmD2JeqFnoeo1CkjCNT/jn0dD/2POxfHN/Drqw=,tag:6naEcdGwsjyc+36Bz5t7Eg==,type:bool]
        editable: ENC[AES256_GCM,data:FmWjpkY=,iv:n/4Fn1dCGifu7714iLvWaaw00HhiMM5mLZ//LXMeTE8=,tag:91rxLyFlQKCAJn8Zdi2/bA==,type:bool]
        basicAuth: ENC[AES256_GCM,data:nL0YSA==,iv:XILVZV3rylOFg1hHAV/hyIZs3vSHmkJ2+LCyhp1tMn8=,tag:oU775/7TiuKfshpGmh3iSA==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:pP1kmWHOQ05Rd/TjVrIv3Zttrmgk3zhrHqxoF2fwqV40MCh6RHm9oCaTULVV8QbtuChlw1XJYIaC891dC2YuHw==,iv:WHjhJYWBNZp6Yc9gIDxQjyqcnhxaeMslS8l8OxEmf24=,tag:WlGkzN3vxLY4ftBeVoB1eg==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:EI0eNPUp+nzA8sO7OY3HrPJnNDTjeiJ1iScljlCxI3AeITuwnhrGyosk9k4uD4Of9cIOMj9TzQbhMQm6nP6Gng==,iv:FB/VDbj6RhghbJ8R+wgcWKxrO2xGhI2atvaWFORuI7s=,tag:qGI5Sz76KWt72+NzllK5HA==,type:str]
      - name: ENC[AES256_GCM,data:xEu45bvCDOULCrjZNK3FAmZ8p2qVGmKVyKlvKoq0qg==,iv:v3lWv7V2IlYadhPyC7Tiyw7XnjoRAS28T6JGbpYYHHA=,tag:dQjqqgJG51a36tagYqwRRA==,type:str]
        type: ENC[AES256_GCM,data:hvcG8x7/exhiMDhaCZcFHw5YV2KM2IWHJrLt8clUOQ==,iv:b43lug0fJNCzGNbgt9gsEBauY1cNcTsPcg8Y1OaV8dE=,tag:3LEBGg+P/AuADJ+4z/H6pw==,type:str]
        isDefault: ENC[AES256_GCM,data:c/uso5Y=,iv:s8dMCUuXaRMIkanzs9h8yjR+O+LIo+wykzUSZqjPoaA=,tag:Z5i5avvrNl2c7ia7qFeM0w==,type:bool]
        editable: ENC[AES256_GCM,data:CLvzeg==,iv:30HFm1W+5xe36YlGNgHBL6QoVKlKS+2hpVxV2VSMOUg=,tag:Uy2VQY1VxcwDrddTC1345A==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:OR/KgPruIeyO+JhpIg==,iv:/vEMlsE0Cw/vwANOifxFBWIMegd8n95cLvuxGd5hq5c=,tag:cUiS2jSbpfb/jngAa12YqQ==,type:str]
      value: ENC[AES256_GCM,data:hbD6wzLyhhQI+AVBV6NOYA+8BwqC+361I9tsvmocieTv5VNswxbj9amzUQP3uDw5o/XfUhy6IMr335+A0txYbmbet8CyAV4snl6NF7FDDntoHDHGbYXcl8mGb10Dq1ot+5QWMZmGlsqSh35O8kXvGhr4vPB/5etdvpqMVk9oMyDcxLCsSdH5QCgxsQNJ/F1PDFSNddBEqOKyhxn7xQdN7fskb0GsOneIwysM0qWoND+l9w==,iv:YcNsK2O1XZvpjkfdS60/m12HkxD8Mf5qeYMKwg9UdnA=,tag:H1F4+iiMT59R/51M5CqrZw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:AaymQL1M5NufBoJEC0PM6LT4ZsJVk7hplsqD07CA3CfT9nou2zsCsKYVvcQ2QZbpWzuUnC4BxmBH9tWRg9IIpQ==,iv:tVh2R++jOZfWOz/yHIVMQpdNgBwqy+NwlE6AKqZql5U=,tag:WO2rnVUt1lkCFVuuPYOIrg==,type:str]
        password: ENC[AES256_GCM,data:EQwfJUwdwhOBncYzHdF4FdsJpH00tVK2DqJD6Stf8DU5/ocNWDjIOOVqg9BLY9fOhtFmNVXJwcB2O0YzacM76w==,iv:XrlfyRyirv7vjzK2JdZbAa6kLChDGBygaF0+cayQQ0s=,tag:Eh1+nb1V8h+Iqc5Z+1FsTw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        hptZ5drzQA0LCXw7RMCMSBYt5KCPL1F45fUm72RGew3kDIIvkEJfIDvUGFFaBYe6: ENC[AES256_GCM,data:mZJPqAxA8e5obr+d5YapN8kj0DZdTFe6PqOiRYtPlePiAuvXNbIU8VZVtwHQu4BCvIS7BIBSwtqVhyu8,iv:wzgYkKnCwocotR0Tx6N7+uF7ozDh959XCljpNm++ou8=,tag:7A7ijwxsh2AO3r+EIbKmPQ==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:GroNhA==,iv:Px1BO0D95MDnFRaXTGzq+YLEz+nHV8jEoD7vAysBfNA=,tag:Ohs2rAVrJLWFfa2XVz6MYA==,type:bool]
    username: ENC[AES256_GCM,data:EJhzg9pxYAnYg6CGRE0z7lfIxH5E2MvpMHJlKjz6Dbm7AVkbOwIu/+O+Qsv9pNcO3JT+WuWMu+GJ9hmkWc99gA==,iv:j0ML/B8z0FLa2QLtta4Ap2YEQWIz/Vgpg1C8waAhG7A=,tag:6O3LQXupiyNFwyFgr1mTmw==,type:str]
    password: ENC[AES256_GCM,data:cu67VMUPb0fNshp3Lmbr9et1IA/EqYfXG8IBOlCArVoKftqQZK1m4t9e6vt2v/uKhoD6pczXKHDAghjcE3R3mw==,iv:Hu/UN1h7DGxgTUEMflePTT/6a1QmTn9OF3yePs2j8Kc=,tag:viZOOLk+zGQ/pwvgOcsPdg==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:9Ya7UHerwph3zXQR9grBQCoXo+EemXBRuUOGa5Zl/tL3/cpg0TXQaVXuFadxgF3Uyd++SCCewutK8gW5/0ytoQ==,iv:9mdrFI+xqhj0xoY9Q1ojBLLibvEP2vuqig7w0INDzK4=,tag:4cTq8x7nb9Jiho7uYG/Ijg==,type:str]
  password: ENC[AES256_GCM,data:zn3rVukJ02LyMvmYMifkT41FxMjSrCP5I/yLutWT1A2dWxNFGEpKL/rwbfMNqTeZMjC2z1FoIbyjtasrOkZvRg==,iv:0yY4LC+Q1RympT3pHSefnOfVxI5Mz3+HIejToYFtN98=,tag:8r6D5G4kdYVWjkYechxzdg==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:10:51Z'
    enc: CiUA4OM7eBLq/7Ft1Cs5yUKoegO0aABlh1RUE5G7ApkbiTOB5exAEkkAmy+ektx2iu1J/r47HJEtioU9RN5QmhS5oND+R1Kl1iuPX7x/zdkYO8yMhP7sjI2CP8MBH6ViJajHjcLkXFS1xdIn6+ciHEuV
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:10:52Z'
  mac: ENC[AES256_GCM,data:faaXko65aJnMCr5oI7A8t+hRGxL8LB547WTLBuoXM0vBicX0PNjixcaoAV6MjKMXVRiUwxz8AkUWAVNdoUpylevKCE53D3maz1wVVK8qCQq48Uplt1CPzL/qw7QBlrQ+koYlXLfESYU8HoPdrnxs6t7WTmq7zBGk6vqc0MLK3Bg=,iv:8RQpZYs7IF04Nevlw16vh/9aYpEH9+hA7Ml3NhuTfSU=,tag:nW9w3h664X+/42KVkBtiXQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
