jupyterhub:
  hub:
    services:
      jupyterbook-pub:
        api_token: ENC[AES256_GCM,data:06jVzCg6Zv6Xvd5lFR8IkSbBKiaD3GZGh4uqu8A=,iv:TlaJ1sWJnKgs4nWmkc9cvXzFXwk2VAOILl2mjN5n73M=,tag:xQ2QIb6aCVob5UxtUEM8rA==,type:str]
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:cCcFsREidFJE+8mNguzsiglaDNU=,iv:8/ONoisn8fresVPcztUejV5j1njBJe1TiyTPbzsl9ag=,tag:1zUsouNBoTdAAoVwZCrXNw==,type:str]
        client_secret: ENC[AES256_GCM,data:QVmzgFYEGKPgTrj6bCrumcQp5mZreLFrw6G+zITLOSJtydDY62zD/Q==,iv:nAdsoPGHyPhFzFPU4uxRAbQOm4fuZSD4IKtZYAHx3vU=,tag:jV9OsG1sy/OyOTUp7M9pvA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2023-01-05T15:13:06Z'
    enc: CiUA4OM7ePFTK8jhF1PvaNsOlsH2PwopRPJE7K+2pVikF/Brl4zPEkkA+0T9hUjgsZa2zAOVqZHOAjeg91553kP+YnHnIW2QPPnSha1dlGfrTcesxV5hsrbeqc3fxs7OnKow5KK3fr48Djf31CYGOgLY
  lastmodified: '2026-05-08T15:42:36Z'
  mac: ENC[AES256_GCM,data:0BYTIrtIw5paTmBqv2x1UGOuhlIO+OYGfnpORF3epIw79xa14d0Qm8a6J+4SmO9uk8dSWT7XY48SRcB9CMPGoYY7ljai4emorsOYhJ2w6gfyv3Lo5orz/EdKZnHbR6x7TpGa3kUb0r4+DpNjuUU/m3cnm1HgNJvKjjGlyuy9OdA=,iv:m8OKmdpVGZDwkL+3cPiSN8fV/ZmLbMNy4ZEHD7p3nLI=,tag:Hydfs39bQMJNBSaaLWTwHA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
