nfs:
  enabled: true
  pv:
    enabled: true
    serverIP: 10.100.169.190

jupyterhub-home-nfs:
  eks:
    volumeId: vol-007f600752daee49c
  quotaEnforcer:
    config:
      QuotaManager:
        hard_quota: 10 # in GiB
  nfsServer:
    extraGaneshaConfig: |
      QOS {
        enable_qos = true;
        enable_bw_control = true;
        enable_iops_control = true;
        # Assume the BW of the disk is Read + Write
        combined_rw_bw_control = true;
        # We only use Ganesha with one export, 
        # so only set this on client vs. per_export_per_client
        qos_type = "Per_Client";
        # 10000 (bytes?) per second
        max_client_combined_bw = 10000;
      }

jupyterhub:
  scheduling:
    userScheduler:
      enabled: true
  hub:
    config:
      JupyterHub:
        authenticator_class: github
  custom:
    2i2c:
      add_staff_user_ids_to_admin_users: true
      add_staff_user_ids_of_type: github
    homepage:
      templateVars:
        org:
          name: 2i2c AWS Staging
          url: https://2i2c.org
          logo_url: https://2i2c.org/media/logo.png
        designed_by:
          name: 2i2c
          url: https://2i2c.org
        operated_by:
          name: 2i2c
          url: https://2i2c.org
        funded_by:
          name: 2i2c
          url: https://2i2c.org
  singleuser:
    extraEnv:
      SCRATCH_BUCKET: s3://2i2c-aws-us-scratch-staging/$(JUPYTERHUB_USER)
