nfs:
  enabled: true
  pv:
    enabled: true
    serverIP: 10.100.169.190

jupyterhub-home-nfs:
  eks:
    volumeId: vol-007f600752daee49c
  quotaEnforcer:
    config:
      QuotaManager:
        hard_quota: 10 # in GiB
  nfsServer:
    qos:
      enabled: true
      bandwidth:
        enabled: true
        combined: 10485760

jupyterhub:
  scheduling:
    userScheduler:
      enabled: true
  hub:
    config:
      JupyterHub:
        authenticator_class: github
    image:
      name: quay.io/2i2c/jupyterhub-6
      tag: 0.0.1-0.dev.git.16862.h30ff76114
  custom:
    2i2c:
      add_staff_user_ids_to_admin_users: true
      add_staff_user_ids_of_type: github
    homepage:
      templateVars:
        org:
          name: 2i2c AWS Staging
          url: https://2i2c.org
          logo_url: https://2i2c.org/media/logo.png
        designed_by:
          name: 2i2c
          url: https://2i2c.org
        operated_by:
          name: 2i2c
          url: https://2i2c.org
        funded_by:
          name: 2i2c
          url: https://2i2c.org
  singleuser:
    extraEnv:
      SCRATCH_BUCKET: s3://2i2c-aws-us-scratch-staging/$(JUPYTERHUB_USER)
