name: Display deployment strategy
description: >-
  Adds a comment to pull requests that indicates the deployment strategy.

# inputs configuration reference:
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
#
inputs:
  github_token:
    description: GitHub token to create comments
    required: true
# runs (for composite actions) configuration reference:
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions
#
# Note that while this section looks almost like the steps of a job in a
# workflow, it is different!
#
runs:
  using: composite
  steps:
  - run: pipx run ${{ github.action_path }}/action.py
    shell: bash
    env:
      GITHUB_REPOSITORY: ${{ github.repository }}
      RUN_ID: ${{ github.event.workflow_run.id }}
      GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
