prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:gXrLyea9v/a3DTUzq/MVDzVeYjf3OCGVFVRZPPoKW5zA2MjuIpw1s/4QtVzXDtrtC7StvWEV+4U4MMKOv0Zz5SQZYj3sKCTF58YzxV3pKT74OMCyhQyEaR0S7gOAsrfmL3ZhiDCbwvBii9cDbahC6/l0AUsbOI0F6Cu4yD0CbaaGJreeMvfIMWQWeR9pDQoWwqg2u4/ibhrXkHk3,iv:MBpHoDumdZTam/rPy77mIa/yT3hHN6PMNdOI/95hx/o=,tag:wfUZsPTxmq9dJJ5kZEzISA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:KEm/ZoAaV03AioPqPyFLmbKBYyCLkmz8KIbNVGrTGSIT8iDdfWGwdV7t1nselXVG5v1eWgUUV13PPUFWyK3y5Q==,iv:kysdXA9kpZB/wONCnEwkmRHYUmE41sHSj3jq7Ib480o=,tag:RLzmsJ4Uw6fxNjinR/vMgQ==,type:str]
    password: ENC[AES256_GCM,data:O7K1xzXATH6V0zKia4WNbFQIKp5gl+Ccxsdc58E5VCSyFpCM7S9xOQKKK3ri1miZRQpQLVByDEXy9VAC64HwRw==,iv:KPGg6Q3HKVLFXhYxDc7k5caPDGQfQvdvzEqIpruJ4rI=,tag:FFQkg6LWTYJUCbd1SyNRvA==,type:str]
prometheus:
  configmapReload:
    reloadUrl: ENC[AES256_GCM,data:EF2yw3vpbhd8qCcE794Gax5kSmdOQGqBj3bfd11qUEpLBhntYhfauu/++jqm1v2fP3+1wSs32c+DU0nKdtQC/qD69aiK24Wyth7OpgxNpYu5ko7Zqs4a2lbQgCYUSexB7UMZWaUaQLh6TZ7fz6Ywekbh4X1Z+WiXdWpCCXqlFmXHmFwux+3gcHKk4Tvq4lAoLVV6Q9Uy1waXXjHHr4vj8A==,iv:RtHrwPTW5UsrF0+EX91ZdJPjHg5ky+4aO5nxYERpAV8=,tag:uFgu1po9qESx9sMRcwiR2Q==,type:str]
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:JfPCCOEsafvIw6QQow==,iv:obPJBW2qsuJfGWQRaXphY4CsdvHOgN6LF7/EdaQ1T34=,tag:f+YZE2Vubhb476aFfWvgwg==,type:str]
      value: ENC[AES256_GCM,data:xbVQKVnzInyrI/Rm2GQWhK02CSFh5NOOgmAgHi4MUzxpX4k54Hg9I4ZltYkMMTbO7tIGwa6MXfgQ4BEvKLNia9RPH2pY7R13AKTXm7HavmrffEwzeDPCvrsSkpiuY3fuesM/owJ0ukXBjCpDOCbWhPf4RO9eCzylu4KJTvgtSgQ1fMQj4WnwjTIu+bCzDzUzHWhqZ21TGNfEhhHqpTy3MoYHQm6GGKzYnyeI6KbWmddpeA==,iv:396+CTgW5WchwKTAEfL7krjSGG/nqhveKPjOYWhZsaU=,tag:mNdBQDZqiXP15kGIaj3/Dg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:KG/uHVTgG0Nbi19PI4FYyCNh8//zGmLAmVFfW4k6IBYxODHlouCRt+fr0LVspRg/xoDysiZAfzcKQ4Y/asGC6Q==,iv:EAr3k7XD5GRH2HRSH07KL9DzheARX7I0KYUIbqJ/o2k=,tag:9S1+bmqxA+/2Q18Dp7eOyA==,type:str]
        password: ENC[AES256_GCM,data:JnuivlJymOGxtWF38E4pUvzK41HdoBBMwPQ96Ll3bddGPyuHt6S81gNIA+jP5fKN/9Xz71sW6nPag1troL5zKw==,iv:FKmEx7X+EtTFPku90nkf38qLybmOv8ppJPLsU0pVE+E=,tag:dD58iTgYAzNsIO8gXOVQbQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        cD17A7Pe8kfJqUoXTDrD4aGhcplTA8YHEE1YnhBB0ZtUOnJqWPsL8Q4KrqjTHsZB: ENC[AES256_GCM,data:jIkgO0AJ1D27akbYsh9c7aInoT5OIwLyyaTc04dt1pxebckXdOVd+DHudAweUSOSGGJqAii95LnQmXir,iv:ef67DPMTFdUQtLg6JZemOK2GL3UM5i4dk+y8G4WN3vU=,tag:e0s4z5IJHfvDkL5SSCho7A==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:hQ==,iv:5lquLyLYOSSIzcB7geSZswgeDhv4V+8/rRiYD/krzAA=,tag:pQLOLpsbc+yIhCGZaLO/2A==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:7JfXKj2YQCSbRA==,iv:pTClvhuBiOuzj+26xkSiaRErsUr/9pj51tzGuGHdNQU=,tag:DBy0BBnuM0abnUr7Edovrg==,type:str]
        orgId: ENC[AES256_GCM,data:WQ==,iv:qHgU8si7Nu51bmwcsPrWFD4S3av4KocBjmHOS9CbHrE=,tag:JRGu67IlpUn5X95xy3MhFw==,type:int]
        type: ENC[AES256_GCM,data:AxfZ4hx2kE49Cw==,iv:I6ATTBNmFDlnAolq5IGBm6w6w0S2GFm/rLTI9vRrb1I=,tag:A7Q4PhpTZVW4vBICOXupbA==,type:str]
        url: ENC[AES256_GCM,data:YN5t8MEZn12DGYVsJICrOySQC0+vWz8cnPpPngBH5tI=,iv:oqfxeeVCjya0tn6o8XiiJyIHFdTIKMvfP3xn1LThN5c=,tag:dnwY508MmxhAaB8DMpoF/A==,type:str]
        access: ENC[AES256_GCM,data:qa1/qdE=,iv:GW7IHr7rz8QQ3n4BRPaZLleXgt8rRWoPzZyTtSxemPI=,tag:Hpok629kb7aNCkymGJDJeQ==,type:str]
        isDefault: ENC[AES256_GCM,data:FKcuVik=,iv:RqrniGpsXIRqytc92hKOQSquVngNTlkRc5lyE4WDpew=,tag:npdMG82eZNKDgHNuIK/BzQ==,type:bool]
        editable: ENC[AES256_GCM,data:o+fE6r8=,iv:IuGtKlsNk1/lIYpUDNGHxAX6aMzCLnh2xTunu5d4mBs=,tag:RvQ2ZAAOXEUq3ejYVlOcYQ==,type:bool]
        basicAuth: ENC[AES256_GCM,data:RgrNog==,iv:Te7AX/m94xsa9RlBCtqH9uoUso3xiauM+jjX/eBxsXk=,tag:6SaxM+/MyeF3bxJppoCGSQ==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:oeUnp2iA/WxeHz8k14Ny/vYZBq4qyaAg7JOB+e9Vjy4w1+hIFfR1MM8UIJAMoXB1+0JOAYSYC8wSWYYigmLrMA==,iv:329iSMl/IImMEbVfeupjuhX1dSXSzb3STR9dPDodlRw=,tag:InEQ6LXirgo1J0cVr0aVKg==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:fDvVCPY9q9VVjhy0YqrwYV6rbE+yrhbafVB2TyQeQTAKtaBV5PBFs5z0KnNDK522IfQlEPC6MgyWjNwftcyiAQ==,iv:8RWPbzSsNaco66dI7RzWGIkdux7gIBbYYzkJZMKqcRE=,tag:phxrt5Mvao+hSHozuuM1Kg==,type:str]
      - name: ENC[AES256_GCM,data:fKQA+9EJYn6t5fBwO416nTq3cXzaG/aF42G6ELQJPw==,iv:BpNKZhWIvBzdYFQDfW4ivpNPR4wI4czWPy0BPJEnt+A=,tag:MbYmrsqGIs/nekpKc4IrOA==,type:str]
        type: ENC[AES256_GCM,data:6YXpHzO3SX6/bFlIOu4Ncm33ufND1WWxp6F6OLvkPw==,iv:9zmW8OFkAJ88cVTZ/nXzp+F0ZTw+3Ug3KJLryYRx4RI=,tag:hj2EAvNc/U6j8WQ2RHjmsw==,type:str]
        isDefault: ENC[AES256_GCM,data:BAvJWpw=,iv:ZADzfWPg2OxdT3rf1/YxCodwkI+jiW/+qpLM7ALJMFc=,tag:zhZvb06H5EGHFfgnYhYi7g==,type:bool]
        editable: ENC[AES256_GCM,data:DRkpVg==,iv:PfYhRtU2/2v7WUaaSlXzSdA91fB1IHvbMjNTwATq0b4=,tag:Obi77LAFDcjRxw4/bQe5TA==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:D16PYQ==,iv:ai/CSkugcl6jIbutKVmHY4y0lDcxmTpnviIDMkPGT+I=,tag:QktJyLVTYr6qTBiIJ67ezQ==,type:bool]
    username: ENC[AES256_GCM,data:fMIJrw/WVvG6+4k8D7jht7FgwL1ZYfBanEUHmn3eyPIhFulUeGltB2Nuj2Z8gDJLjPZ6CekYl/9sP1YKvNjE9w==,iv:a6dF2Bf8WdvD7wOhx73WQ/P4r3hf+6tDaGKXBw0cy/c=,tag:4xQEOGQV8t9YK1b6BMROBg==,type:str]
    password: ENC[AES256_GCM,data:d0liNTmT0f1ETMOT72Wf1L0vVQPaRB8BMEacbyUtODVvSgMPCtI4mJ96Fsyrsu1mxCLg+ES/WW3aCoKfkX8Mdg==,iv:py6R44hIJfGXFBNXfPiulB2orNOXdot7ZC8SwGg/9R4=,tag:sTzV6Fe3zhO0pQ8Ekx6uWQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-08T09:19:06Z'
    enc: CiUA4OM7eNIs8YZ4OVTnHyeLqYSy6xhomswhVtyrZ+fH/6xGAjHcEkkAmy+ekqA9OElyAvgoSkqDX62JWbk8HYWepYBbyWruyflyXhujIMsPLTVrmSGoVYyEGRW2oe/qqV3ATqd13mQne0pxQscziXK7
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-05-08T09:19:07Z'
  mac: ENC[AES256_GCM,data:2uz5nZojfMmpIcG0kgmXmBg1iLcn/3oKt9sGJpLSEWDtFWyT6iHr97eeBjsW8yWwOnSOCI5uE6XWjGn4bQQ6cBNysbC86HaxvgNED+WxtONLrKG8A9l/B/vkzCb863hiRqLF9LbE1+XKQhLVj969+AdaPhf81cRa73EVu2Z9nVk=,iv:4+x+J8vgWSvD5TxKKLaXHB8LpbUZ6+cGfKI6E8bXDcw=,tag:I6cFIA6YbGKg2T2g4Um2WQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.0
