prometheusAuthSecret:
  username: ENC[AES256_GCM,data:NkhnEHfr1xL5vnDTijDmFOJCoHqw+AIgfWDi0ebAtTG81vXY8upqzsA3+Ih8oCFCBxNNsxlBFpPFjr1PQhV6xQ==,iv:8aau+CKuTWkVKrrQHLhKkW8JshBCfuUP/XdIfgfDPY0=,tag:y1iy2MeCm9h6drC/B/Co7g==,type:str]
  password: ENC[AES256_GCM,data:1FSUohXscb6NqL/qRir7xv8I4LWEVxP0k0yhdURuTO0S1fagLqPmytpuMK8zWDVNww5AyfEGZb3aRFckjxNxUA==,iv:UZJ24FQclNxmAgjgl7B+OWQJTE5cWT37FYC+nJYyHEQ=,tag:nRdH4t9vjmDoDTszvYdwTA==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:8S0+S/+xtSGiyopwrQ==,iv:CFzvzOekntABBnZ0b6x6JpEVBo0NmIleAd3X98RjhcI=,tag:LEVplUnfN3JSjw1/gF0LGA==,type:str]
      value: ENC[AES256_GCM,data:bgPhEHE98aGlMUO8DtCqrNk89xpuimxlfbYYf+wiPlqM3SNyfZ7nA5HvimBQ+dkKPDjANTT6YIR09+TUQ04YADv4mwi45vTBfSOePrl/GLjJ42cn4e2HcEz7QDKvNAc7dVxNXv7u7G4Hn/UEMwtY4mDkjIM0R9eAt+iSAatuhXWXA50dc/SwmVLyK2nvprOsn2LQMYlqwBMyW9YE+XrF190eTW7g2AHdMcXCgAtWLol1kQ==,iv:IvLH4QZHi1YjFfM9Cun2j0Ai2+ubr4za37+tQseZ4xU=,tag:WxE8uCAECLN71BKtoWy+wQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:sBvOi8Bt2yUWyIJTIOKUhA5yLRdPxfd8+cmiBoZn1r69KoxSKF/wVCrW6NT2N/sffhaEbXWBn7darhpYsPB0xg==,iv:sZdgKsXCOnDdtcOfxhdeqGgjTM/O2mbEZPWNriuCvMk=,tag:5jMLIUJ83+h4BkB/I20Tkw==,type:str]
        password: ENC[AES256_GCM,data:zdLAQRe4+56AChxwrSLT3Sbel6576Jll3sf2y/PevlarGWiaI/YKqDWplwrnitYYxDylvuN99CcwoAp2axwg5Q==,iv:CkxiLHfvZjUlbSLOlMC/W9jqZiOTAAVYm07u3MM+amI=,tag:lAEbJzvQ3QGiYlJlE4ge7Q==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        cD17A7Pe8kfJqUoXTDrD4aGhcplTA8YHEE1YnhBB0ZtUOnJqWPsL8Q4KrqjTHsZB: ENC[AES256_GCM,data:Bx8dX6fXRyt/fVQCy2yAzYyKvGwRHGXe6d2pt3xL5/6G1nwBhJZBaYkbIAjO9dhj4ihwQFmnxylEN2rs,iv:yA83dlD4XraIZnYQ0Tc14QhhKGZ0KgONRh16ACudk74=,tag:qRNB0SDLzt6sVqkpjPUjYQ==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:mQ==,iv:U+G0ssVG1+T5SzAku18SgTvLO7yDMoKVz9LukBvMf3Y=,tag:HbJaoQJgJoc2L+nKbkHUcQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:3sZo7wxAp9QNGQ==,iv:zyp3iAJTedqt3P+jKlvdBLFi+CJwoMRIYZt1+ob3kPw=,tag:L+sWkJKstHhI/Bcwtmicsw==,type:str]
        orgId: ENC[AES256_GCM,data:9A==,iv:ZyOEr4r+6PKYHfBvyV/V+fNS6WSCRW76UsNZbxgiJhc=,tag:YHFIr4xOriTjUGgwWKSAJw==,type:int]
        type: ENC[AES256_GCM,data:3/bTO5eTRKt7CA==,iv:+2DucR5enPCa9QY0m/E3/NKkvFobimCsx7UsXhspF0E=,tag:pLd56y73Xt86DUXuWBTh5A==,type:str]
        url: ENC[AES256_GCM,data:b1RwO/HrOx3RJrYK5MvVmURIJYkMqnAY9TrQPe/y/lE=,iv:Dp+FyW/0F4zbBfye6BglEg/NWB0tiwbbX1ipsSIDLwA=,tag:8TS60PbMhYkeq9290qAAXQ==,type:str]
        access: ENC[AES256_GCM,data:f3QbHrU=,iv:U3AoFYRcjb3ywyQjhitG1+Qg7VSWzvXibnQKToh9rUE=,tag:SBBueFqaAh0ODohfGrOmMA==,type:str]
        isDefault: ENC[AES256_GCM,data:TzqXayM=,iv:to5ZqfOHZ7gCINNGZjN+jb7JIvJD4ZNtPGJoB1W6p+k=,tag:yg7z4RvhyVqhztvHBzUpQw==,type:bool]
        editable: ENC[AES256_GCM,data:E5+1FHg=,iv:AonKqAKE6c7Tt+QALgFxRoO+Q3g4oCN87SmO/HvpTSY=,tag:XyDTawHGKCRi/m1bv+Cl7w==,type:bool]
        basicAuth: ENC[AES256_GCM,data:cXoaeA==,iv:ST0T6/fP+9MafVahcuzcbsXit65N/C6yF3ml+f0YISs=,tag:omH0CVJpM8Rr9CEurTgHmw==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:qA98N5+/sgrKJK4f9XkGPUNo/zVJrhQk42l0bhtF9HqRdoz9+MwBnmVnR3K2wXUvU4ZIKFWkRcE2Trv/+Gd70w==,iv:4JJA56Uuh12sreEUsPicr4sUCpBPy3ES2vyReYb8qE4=,tag:qgVN6Ic5bJe0mLSv3ZuyBQ==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:StoAWzVDuBjXICl3wYO9hgzsQ5YzVji6Svl8g6Crf4xuGtFXP7ngaEi8KnHwigjr2h4jcp6QOnfAffI4WNOkEw==,iv:DMpJ6PgRQD/apmsuDS10n6TSXg5F1ujdSjHXEGq8EHU=,tag:Lj57CDSqV2LFqYP2rE/g/w==,type:str]
      - name: ENC[AES256_GCM,data:6Y6AsNFQJ9Z9VEfdmW6kyVzMFKY3fYxobhMK5EKloQ==,iv:qMY4eqXdrRI9auqvi3Jw61r8DEePhY57osYh1qVy/fE=,tag:wHenGkT69KexCnDuzBdZjg==,type:str]
        type: ENC[AES256_GCM,data:FNu3j4oWwDOwjpX/Q450/FHIdLTZLqABDwQwZjJzUw==,iv:oZFtMnOnsfNgOO2KqugHN72zhkvEo1jx/OYQYkhkV0Q=,tag:chqXpj0rK9E/PORV19d2jA==,type:str]
        isDefault: ENC[AES256_GCM,data:Lx7TP0g=,iv:X65jewp04d/8dcoDSkhJFriSFIoT4AfmZZVrfg3NfL0=,tag:UxoFJ9I7jkUpFl+BtJrOCw==,type:bool]
        editable: ENC[AES256_GCM,data:Z+1wuw==,iv:I9uDNBilUGVrmxtkgWI4IreHQb4JR3lpgmYZkcqq3M8=,tag:MAzYAIDdpwmKiLWFysn2Xg==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:V2ajqg==,iv:nsaSOQoE9LSTslLKseV9T7s6r0W7rMzKOWWCVcoQzWA=,tag:JyJhwiGvF3KeXeolPEi79Q==,type:bool]
    username: ENC[AES256_GCM,data:H562JO++k6KWVbNZXCCRvG+VGXIirkY7UeMh0o9HgssLLWgmvU4lbcxG/eHJl/mdNHkgCu0dQjziOafs0zTxTA==,iv:E+FKjg9bGN30o4yXVyRWESt5HcFTAAHgDck8LUkHCXU=,tag:sFNR5d23G7Ekh2Mw0gSUoA==,type:str]
    password: ENC[AES256_GCM,data:GMNHggl22EbW3CcVOvRrNTCPbeeBViXK9EOavEnbdzlKg5EmP8V9zP5WFzbevc2PPamTlK812ojAdy9zoUwQ0w==,iv:3dBjvweIRBesJcPSGt9XsXqCb61XBY73cEXSE531Kag=,tag:ydtI272CGSXa0vuFpTb66Q==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:47Z'
    enc: CiUA4OM7eEj/me49yiFoWFsj9cFoD/5PYDQeUfOpndxxDnuLXEKNEkkAmy+ekhAxOxoY61lnJDCCdFVj0QTHHo3zFCStJFBpT4T9S0W3TIwD1Kex2DnLHovPvVu69ty9CKFbqM+w1nj7kFoTnnLQXpZa
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:11:47Z'
  mac: ENC[AES256_GCM,data:KSgbd5m9Pz8scszdEDPVIq6W7058HxKASF11TvCA733RcUE7AVr2641SKp2W1IDtjBjvf9ilbS3LAsha7fXLqeyJgl0BStjvz95Ilrn/XuTDdMqbO3zMxFW+06YIDbNXICE7/NqKZ6oWEKju45jbQMKkv/dbFmf/DKUHhZFnuu4=,iv:BAE0X8PJ2Md7NaBiOzMSjv7dGrNvSuKX/pRKzBk3yrw=,tag:n239iTG/iIKvIe52R7wg4A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
