prometheusAuthSecret:
  username: ENC[AES256_GCM,data:NkhnEHfr1xL5vnDTijDmFOJCoHqw+AIgfWDi0ebAtTG81vXY8upqzsA3+Ih8oCFCBxNNsxlBFpPFjr1PQhV6xQ==,iv:8aau+CKuTWkVKrrQHLhKkW8JshBCfuUP/XdIfgfDPY0=,tag:y1iy2MeCm9h6drC/B/Co7g==,type:str]
  password: ENC[AES256_GCM,data:1FSUohXscb6NqL/qRir7xv8I4LWEVxP0k0yhdURuTO0S1fagLqPmytpuMK8zWDVNww5AyfEGZb3aRFckjxNxUA==,iv:UZJ24FQclNxmAgjgl7B+OWQJTE5cWT37FYC+nJYyHEQ=,tag:nRdH4t9vjmDoDTszvYdwTA==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:8S0+S/+xtSGiyopwrQ==,iv:CFzvzOekntABBnZ0b6x6JpEVBo0NmIleAd3X98RjhcI=,tag:LEVplUnfN3JSjw1/gF0LGA==,type:str]
      value: ENC[AES256_GCM,data:bgPhEHE98aGlMUO8DtCqrNk89xpuimxlfbYYf+wiPlqM3SNyfZ7nA5HvimBQ+dkKPDjANTT6YIR09+TUQ04YADv4mwi45vTBfSOePrl/GLjJ42cn4e2HcEz7QDKvNAc7dVxNXv7u7G4Hn/UEMwtY4mDkjIM0R9eAt+iSAatuhXWXA50dc/SwmVLyK2nvprOsn2LQMYlqwBMyW9YE+XrF190eTW7g2AHdMcXCgAtWLol1kQ==,iv:IvLH4QZHi1YjFfM9Cun2j0Ai2+ubr4za37+tQseZ4xU=,tag:WxE8uCAECLN71BKtoWy+wQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        cD17A7Pe8kfJqUoXTDrD4aGhcplTA8YHEE1YnhBB0ZtUOnJqWPsL8Q4KrqjTHsZB: ENC[AES256_GCM,data:Bx8dX6fXRyt/fVQCy2yAzYyKvGwRHGXe6d2pt3xL5/6G1nwBhJZBaYkbIAjO9dhj4ihwQFmnxylEN2rs,iv:yA83dlD4XraIZnYQ0Tc14QhhKGZ0KgONRh16ACudk74=,tag:qRNB0SDLzt6sVqkpjPUjYQ==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:V2ajqg==,iv:nsaSOQoE9LSTslLKseV9T7s6r0W7rMzKOWWCVcoQzWA=,tag:JyJhwiGvF3KeXeolPEi79Q==,type:bool]
    username: ENC[AES256_GCM,data:H562JO++k6KWVbNZXCCRvG+VGXIirkY7UeMh0o9HgssLLWgmvU4lbcxG/eHJl/mdNHkgCu0dQjziOafs0zTxTA==,iv:E+FKjg9bGN30o4yXVyRWESt5HcFTAAHgDck8LUkHCXU=,tag:sFNR5d23G7Ekh2Mw0gSUoA==,type:str]
    password: ENC[AES256_GCM,data:GMNHggl22EbW3CcVOvRrNTCPbeeBViXK9EOavEnbdzlKg5EmP8V9zP5WFzbevc2PPamTlK812ojAdy9zoUwQ0w==,iv:3dBjvweIRBesJcPSGt9XsXqCb61XBY73cEXSE531Kag=,tag:ydtI272CGSXa0vuFpTb66Q==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:47Z'
    enc: CiUA4OM7eEj/me49yiFoWFsj9cFoD/5PYDQeUfOpndxxDnuLXEKNEkkAmy+ekhAxOxoY61lnJDCCdFVj0QTHHo3zFCStJFBpT4T9S0W3TIwD1Kex2DnLHovPvVu69ty9CKFbqM+w1nj7kFoTnnLQXpZa
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T09:00:26Z'
  mac: ENC[AES256_GCM,data:FUyg+SZPc2jCo1P79pWO//bYX6G4cohuwE9400y9jmrGZ+RfQWchiEdrNnPC3HRuxiu+K+UW6VMqpsAGD7TbFuMSVC0j5WvyOtWKH2sgTFJBTvnhKDSg8V1jdjW/1j8aVRQPdvSWkok04vY/TOPCkyFTnDEwcXnp5aiT+BZtE7c=,iv:6mfcwySODi0UGPRuBlGpL0dNCoLc/LgWpd++b4cHzZk=,tag:y4y8q/DBi4BgLaUIIApPDw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
