basehub:
  jupyterhub:
    custom:
      homepage:
        templateVars:
          # To login to earthscope staging, now use https://staging.geolab.earthscope.cloud/hub/oauth_login
          redirect_to: https://www.earthscope.org/data/geolab/
    debug:
      enabled: true
    hub:
      config:
        GenericOAuthenticator:
          token_url: https://login-dev.earthscope.org/oauth/token
          authorize_url: https://login-dev.earthscope.org/authorize
          userdata_url: https://login-dev.earthscope.org/userinfo
          logout_redirect_url: https://login-dev.earthscope.org/v2/logout?client_id=Kn6kSKtw9TqgrSrEmDS0rlBM7Sc69BkL
          extra_authorize_params:
            # This isn't an actual URL, just a string. Must not have a trailing slash
            audience: https://api.dev.earthscope.org

        # Metrics config
        UsageQuotaManager:
          scope_backup_strategy:
            empty:
              resource: memory
              limit:
                value: 25
                unit: GiB-hours
              window: 7
            intersection: max
          policy:
          - resource: memory
            limit:
              value: 500
              unit: GiB-hours
            window: 1
            scope:
              group:
              - geolab
          - resource: memory
            limit:
              value: 1000
              unit: GiB-hours
            window: 7
            scope:
              group:
              - geolab:dev
      extraFiles:
        usage_quotas_config:
          mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/jupyterhub_usage_quotas_config.py
          stringData: |
            import os
            c.UsageConfig.prometheus_url = "http://support-prometheus-server.support.svc.cluster.local"
            c.UsageConfig.hub_namespace = "staging"
            c.UsageQuotaManager.metrics_exporter_token = os.environ.get("METRICS_EXPORTER_TOKEN")
      loadRoles:
        user:
          scopes:
          - self
          - access:services!service=usage-quota
          - access:services!service=dask-gateway
        server:
          scopes:
          - self
          - access:services!service=dask-gateway
    singleuser:
      extraEnv:
        SCRATCH_BUCKET: s3://earthscope-scratch-staging/$(JUPYTERHUB_USER)
    proxy:
      chp:
        networkPolicy:
          egress:
          - to:
            - podSelector:
                matchLabels:
                  app.kubernetes.io/name: jupyterhub
                  app.kubernetes.io/component: hub
            ports:
            - port: 9000
  dask-gateway:
    gateway:
      auth:
        type: jupyterhub
        jupyterhub:
          jupyterhubServiceName: dask-gateway
  jupyterhub-home-nfs:
    eks:
      volumeId: vol-0eb31cae0bd3ee261
    quotaEnforcer:
      config:
        QuotaManager:
          hard_quota: 10 # in GiB

  nfs:
    pv:
      serverIP: 10.100.35.0
