jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:K/la3GCh89bJ2GQbPP3MKdCYnPM2Lp+3Lq+i0gtp7Ik6skhFK+pAt8csVkUQnzKHOLl2FuKBUq4gCEQZHVTarK5N96oKVprjOo1fmCpHB5cV1HQX1FHyOrO1lhiu5zjrcAp1lJucx2A6QUZU,iv:Qh7K71wI07kLhi4Rr38W3sf51jxpsKZ2Hh5r6KTM2Vc=,tag:ZSIeeip5iFMHeapqeV28cg==,type:str]
jupyterhub:
  hub:
    config:
      GenericOAuthenticator:
        client_id: ENC[AES256_GCM,data:hRQuAydniDTcgSe73vCt,iv:B7X5K70oPKwVUU0mNrEfiOXRVUf6Nb+yhFE74Qiu23c=,tag:jUHvMoa47paCEMvutzoMng==,type:str]
        client_secret: ENC[AES256_GCM,data:s19cYd7TckJe098+Lpu+lw==,iv:JolZqREunlBiPGPyaeHoKQVbtDbi+bZy+wzbgwaxBrs=,tag:xqNodPicP7/SKa8ZXWKKyw==,type:str]
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:Ai4NGs7Uogkd2rXT/kP7QsijymY=,iv:JlJnVFU9T5+9gR1bGQj+Q5pfFpK4b+TWgpeAcF/oYys=,tag:kMApKeHj48trURznIth6eQ==,type:str]
        client_secret: ENC[AES256_GCM,data:fbCKjYFVmgCNbJkiX7Edi6AYUxIU6uJHRhEIG96plLo0/33vcMFxPw==,iv:8Tws1ZS8M0zTXWYFJfmpFc1O6rcr7Bg+xp8CB9xox/8=,tag:rsy/CjgXHrpGWpamX2r33Q==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:d7A6gdYZajaza+3/X4MCQyVx9WGb80EyEZ6QG7H07c543EVgM9MVe6XItMWAYwHQrnlCyxdd1FPGZ7cwiSE05pLbgzJmolZF0A5mpnyc7bQXgg8JzEo=,iv:6GWG99d9rq3QxprcWNmUzk4vnJBuUdjOPvhqYVAKBRk=,tag:9yk8NIuCE2E4/BLabZlkXg==,type:str]
        stringData: ENC[AES256_GCM,data:GvEUQ024flmXdbbwpg7OQZ35n6lkwHZ4y343Qpz0fCi9c6ub7o9ln+LrqL2j4N4zeU2egWSazJxxjEDtkFwY7+nDuNENkKKMQQYpf/nwgJgFddJCAJPiacYpNGT8odxW1AxSdtPppMpij8hcSEqvpcQ4Y2Jgja3+uCea4umb9zVIts9kFJgPHQjgB2oDwtQdnnrm3oZGAyb6BHKpwK4hpPUgWpZHI3qmVdfSrX+4ISdCJxqvO3sUBf4fP90kIKgfu+I1tlOodwX3RR+HCif4f82ZHYHlMbyJenCVY4kMTiqvHmDWvIfF0d60GsDY+HlbSJO4dP14nDFscL5dyL7XL9jNV4C1XcDUFUmxlD0HFUCtTlxEkZPT/j29GOTGJAigeb2nCtVen1pXhv4JAzs=,iv:HpfxgKNTdjcTvMz4tgIwE3pVloJD5rVLCM7ss78T25o=,tag:j5n3e6aSlXHwLyy09ZJcYg==,type:str]
sops:
  gcp_kms:
    - created_at: "2026-06-26T08:53:26Z"
      enc: CiUA4OM7eMHoxJ45f44IDSbeC+03FfVVw3R0oYUF0Hf+d5q5oTSREkkAmy+ekpb0Ohuh76CLLl3CiOPIew9+YN+dzjfL2nutAzKiBVSPrRBXRdCMbX1RfwIeXoA+s+BPmEGH51/meugcVwfGlYkJsjbP
      resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: "2026-06-26T08:53:28Z"
  mac: ENC[AES256_GCM,data:2Zex50H1bJ8lbY6UaDBF5A/GmhoXcLIXYW6wo4XY3dghYPIQpEmYp1aRzZo/UZjKT+70CV5Fz3yR60RCRd27qaZhS9ZUpSSEHadc1t23gbCrKSFEotkRoJh60Uv2lNHOnnuYjMX+1PtpjBCN0j+/I7it2iBXg/Z8EzHEDm1Psyo=,iv:JDF/nSpD1VAodQKx5JUrg5y391fGBFDfH3axa+5+T50=,tag:wymX/2eCNzTbtcpym+XqbQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
