jupyterhub:
  hub:
    config:
      GenericOAuthenticator:
        client_id: ENC[AES256_GCM,data:tEY9ymOQlN8R0dLzulDS,iv:07H8f0KvyEFU65pmOPRLgndRxib1yjXXh7nOgn7FxEs=,tag:FMC2AZDKgYieORqMe0a0JA==,type:str]
        client_secret: ENC[AES256_GCM,data:xq26QWeWyUUCSFpsP2Do/g==,iv:w/S/MaHBSJXIHBfMK72DhzMjkmiJS2pDZFIO1Qv0H9I=,tag:ZwUcyJnshNNv74wROnz8bw==,type:str]
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:NUUPq8wuI6HyTK+FA/bLGeCxjKo=,iv:GnDWl9uSzu0om6/50ET04DrSl1KLHte0fJ0W0ItxCRA=,tag:/eAVGe372nwht7dcLO695A==,type:str]
        client_secret: ENC[AES256_GCM,data:leNNgb3xAg8cjoAYBBygSZz96jKU0SdzkiRGpO9QVyoC4ELvk03cMQ==,iv:zkntxObd5q+0rA/lBlOl+7eWG9BpELl8le9wuZNWr4o=,tag:7OOA8Y26uISweCUks/GBSg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:h1JGk7qfvi0PrUDyHNxm7jqxD2FPPB8lEZm+5AZxsAQkS4mAbUBK3jCk2JchhmDEo+VYKjNxGe3vtwPCKAMPXGN2vAwWMI0JBy0LQXOAigE5BH9iWL0=,iv:1YC5ckR43GQeEWxaiy87crgpWDhb9BT3jLOSjRlGK6w=,tag:BdiQWpVXObyf4hFlMKqTcg==,type:str]
        stringData: ENC[AES256_GCM,data:pXIYgCG6z8a3wzFQe9NWUZR3xEbZ5DFlR3AwKewo7etSWNV1jk05HG8r1Mq6uxzs98KYKl2KiQA7rXauYyhwsydaxllZJPWnaxEEtNV06gxLKSd/8ARql07ESxCs4hYP78Cb8FecFML2EduedvuXl3wdy883y6t9iEFSCwIpDdjxTmWxuOVWYGZvufjW677JcxQU6pdO2wexqoBD0cxDgjGAtuQHyIMGgC2txSV8g90QPH7qDIC0zyY+o4UNg8cHBqoCKzXmf9gOrLaNwhjql8i6NbLxWQrPv0g1LhKRJp/tXUQbLDjIbq5AsqEU0Ly06dixervIYIFj54eGg7ihcqtWFqS76L9iO50NVp/L2z+ocehR/DLYh3MFOJWEFZ6V6V9OBpFmyJPo8fcvSA==,iv:gGJhVulJ78xhHKZ7wmgVu6kDTRttlaCbFwHQZCf/Cxs=,tag:PC2IVhlw4rBu/ab0mVis8g==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-06-26T08:53:13Z'
    enc: CiUA4OM7eEbn+hfb+1QQ6Us0AMds0bP1F9bPVQFkyMNsg14NAGbNEkkAmy+ekquBsSij2yIz2FVucPle+W0HOJqLeJsUavZRwgQTjVbtUvGF71cqb80YaPLtSEiyU794VU24H4UWiSLvzTrBTd2r7oAq
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-06-26T08:53:15Z'
  mac: ENC[AES256_GCM,data:SPME8ECWVq0gvMGsDaA0hJiPNF8RJu+/hXRgMjCrxtisFa3PFPCI03g1Y41QbkgYE1aJ6cIKlolvCSTDoiCXgawvgh7C2Avp1YtiSLAXfoZ4wAVPvy0i1WfIBMdZY0wHABaIf4gjigJ1TJLA0iQAlank84aVTqo+/HZhX+ao9k8=,iv:HV69mh1WPSWR7pQWcIWLZgaTjsltKeT9mgQLYtQ1vr4=,tag:M54KxlpLwI5HvbOiiqXoPQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
