prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:CJ6l+tRXhZeHI38Aiw==,iv:OZKI+e9pqQ2spAZnUpengZgHmo9lm4ZUWQd7yATQB4Y=,tag:+3DOgKRaG2RbysWXAI/Ibg==,type:str]
      value: ENC[AES256_GCM,data:Knus+U22T/1tppDc8TyefbA9vtZ87UkxSWuPHCGZ6+Gx5skDyC2f66p9e7k55EH9dwKS7X8yTxjHQdmTy0RiZYsxshH3HcXRNQynIb4Y5ybH1QnlBD8D2YlQPn4r1Dop10GMTEREFzFSZSmDMcmilv7qajIc4h5AAxVRqOE+6X62otm/zpK5SnW8BQNDkvqRguqD504tbacFkU208ZlEh07a40U98uTAfGJpmsd6IaMBFA==,iv:HAQslw/DKJVBX44W5/UAePt+n9OPmpTt0vv78QitgAc=,tag:QJCGAmLmo9bKl/bdSYd/9A==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:06Gm0+tXZyHN5XY5wyb96SH9+Lecn6hLX/S1Nk8fUU88/TII2mwqM9u+4Zn0bOG9aCE4Fj/RZdAvHP4bDdat1w==,iv:M3QVrmFjId/CRnB2uuhbbI7EKXlhxe4cE297uv071TM=,tag:rvTfqS+gq+BLuSmeSxrXGw==,type:str]
        password: ENC[AES256_GCM,data:gxnRwViCYJQN0C9wCkpFh8zjFHMq6c7rGr2PLruttO89HmvqzmsNPjlsU/D7B2nwyP2XEFAJLXQSjr3cNsEOag==,iv:tN3VNXVozcK6TSoU+CDmoZVIdhG493ldQ/jgmkdi+lk=,tag:lql7JfQpsOiBh7Aa0/A62g==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        LHaB791vqQdCtiBB6jwx0KB4LA5zgeryfRV6ZEgqwEk3Kz7tv0aMjobp3G9ZYY2S: ENC[AES256_GCM,data:qWVm0hR498ljKtW8iveHxxQWHqRhUSGZtJLe/YlFBmm1VkBqDePnWQkGIj/4DbG0y1ezL0KtawT5RpeB,iv:uufMuwXnsRhsw6NZ9Dph+iYsVqRgdroZMu9LVvU1ZNs=,tag:M7Qu/A/SU+t1YjJdQSq5ZQ==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:WA==,iv:oTaTn1Bjgx0UY6X2HLZm7StwNCyFmxJjAN9I/GzkMs4=,tag:C7N8+AgqeXZ7Lgr2nBFDLQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:5A35hFGRhwlUAQ==,iv:IowJWDQH76o1W3jw7zN0cnHu6co97tmxxFis3oUhRUA=,tag:DW5ERxTXoFz/pnD0GzduRQ==,type:str]
        orgId: ENC[AES256_GCM,data:vA==,iv:1HWmB/T4GkH0nR5YQumI669LbxxjeT0mk1umSZTOAOg=,tag:xhItqMteZlvqU9lnxEEgVw==,type:int]
        type: ENC[AES256_GCM,data:mEy4H+q1j1TlxQ==,iv:6zTAh57DQb+ceUK1pbxCoNTXOFF4/AlJLJx3x13X+Es=,tag:nDuoYPIJ1It2IYoF6jKxDg==,type:str]
        url: ENC[AES256_GCM,data:Tv67IqRmUDAnfyVnDmvdh+gCy71LC6yUKsPR1qBtgp0=,iv:3ftAUpdhl9/SUMYQpGzbBtxkaVTPU07CvFGZeUy10m4=,tag:zao81/HSG53bYTmRXtGMGQ==,type:str]
        access: ENC[AES256_GCM,data:IEhTJAk=,iv:FBMA32lmVSwhl0AR+5BV4aLGlD4Hf1vtScvBWmsXU9A=,tag:Bj4t4U6CtzomGvY7mSuiqQ==,type:str]
        isDefault: ENC[AES256_GCM,data:01RC3OM=,iv:mHhrbHdSmrse7Pef+M/nSSvpm3TU+m9epnnY36aew28=,tag:SQoB8G/U5Cms8mDPvMTCyQ==,type:bool]
        editable: ENC[AES256_GCM,data:BF48kis=,iv:pLYe6UCotq81mL1ugs7IOm5ebAdb7mX8w46r9XNIh4M=,tag:3hLy8bBjmqJf1hkMaFvGJw==,type:bool]
        basicAuth: ENC[AES256_GCM,data:YRcGcg==,iv:UZreBwlxiszGo+5SsAJOInBMT4fKdnlhHa1zsXCaJSA=,tag:2xu5BnD2QcM4VgFXTfcKng==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:gfsMoHtiwZ3vkkPZ6PT3dHzQNv2asb2q9LvmBqlava51wpL6dPUPVFcJ6Po8S+juFjARVrD36htaCflW5xW+ug==,iv:9emqIw62sg6rrBp4Z8yFgnrkgHcZjDTcFQHhEjuIEqU=,tag:ZTHhRoG6tttLSiMgO2c3Rg==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:P0k7qwbiKn4GSyeNFp/U21+J2OhHnO1YR0FDdoWkI8LyqUOYfc4U2dJ9jyj/ZWSbat+2+iE8oQHpgQV3lEsbUQ==,iv:tchAl6GcktR5xppRvcrQl6K7BsNdr0zb7odS4LhOgYY=,tag:/VYr80MSHUoBxpdYK8nO7Q==,type:str]
      - name: ENC[AES256_GCM,data:RDKiKrMIOxYpMbNKv/h+kogq03GLHhVDKdN481NgnA==,iv:l4jfvYAH10XMlRziHPAPZb0bwWrwoLuDtBPJAVWL0kE=,tag:oIC9xjlpnV1hip2ySk8lqw==,type:str]
        type: ENC[AES256_GCM,data:i3LVRPNpu3XpnZZLFrGybo5UXrrUf8fEDQz94Xa2uQ==,iv:zzln0esUblJWkG+7zRoCNnbkpCKSp4vED9iGQNtDz+g=,tag:N6jkxuWuT7MHSrNrV/i+Tw==,type:str]
        isDefault: ENC[AES256_GCM,data:gDD07Gk=,iv:Bl3xu/YzoNGUnu9TBkJhZcSjI7uHMbWA4Oo3Fkxe/Ks=,tag:FQ4eGp2WDPsFcv/BSzGYqg==,type:bool]
        editable: ENC[AES256_GCM,data:rKRSzg==,iv:8fh+TUT80AWiOuarpsqLVY3a4q4kcjS6MMJgg4Z8N2c=,tag:p4zsDMQejkXoxzWYgmHR3g==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:5EP44A==,iv:7h8dQsyJ8MIXHekXgy0TMTuKboQjFyj9K/O2pmlFroQ=,tag:FEQfClS8augZFAdAVOMrtA==,type:bool]
    username: ENC[AES256_GCM,data:p9mgs87ZPkeX0t30CiOH6Vig37/+NdaVV4MVh5OKrCckmzxUVtd4eUEK++PZaJkOXQSS26IRvg1p/1E85mWmXw==,iv:9JRG2tL/oe1I4Bg4kp1juwTFbR/oA8FXMonHCok5ZCI=,tag:gZ8wTj9fdldV/Rc+yytC/g==,type:str]
    password: ENC[AES256_GCM,data:xHj49qQ6n88wyOKWwffCC/e0PLJkaFNzjTAXzU+Gw9+GAbUjsEO1y7a6IKM+g7zoGn51sAgn1I1Ev6pmJjNpTg==,iv:ZVy7CxV/Tqnu4FUKnNlHLeZDm9rmfb41ftYzEvykTTE=,tag:pH26hHrqCVwedzxaoUqrBg==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:DGNkS8+zMf67szrm4Usu5izaVOJ1SOfpAZr1E+6WCxNSlM77ygecKyak/ZuBTcAQHK7dWMyK/EuuHKtMgkeZyw==,iv:fDPwuYru4x+WVtfpsNgMd+jbgq6Rh6bhcYlMaQ591V8=,tag:iUqLqPkC0WOohAuvGjO1cw==,type:str]
  password: ENC[AES256_GCM,data:mDsAlCrwooSQqRZA+W+SESGBygyZQTpCORYg5gJ/h1XKv5qf0CjS5h+Mbv5JipRs5iDON0b8RB6MVsjCTPYTqw==,iv:BwD3bMA3wIycZuPea6Nz5lWrpkh2eW5dgv0Ry6wivZQ=,tag:jKetaU7rEMi6/wO6mR5lmg==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:30Z'
    enc: CiUA4OM7eOxEdXTaMo5hgd9CME5i9jg5DuqodReMGeJvGy0RlPlQEkkAmy+ekkeR+CncpBN/DNvFrm2bk+qHI23JjQBd9jvmTGVlO0OaeHZZkcFY2UYB0j0wI/9s8Jgoh+wDaG3XyxzgvOnVBBCkjfdw
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:11:30Z'
  mac: ENC[AES256_GCM,data:h+vcdQGBeA1tMUCH8wHdUcS0O8KY6YTqNWatoKddWbQaRNKPdwtDr3PNyXd5LRPFXX/dFa1fKX1hbMRNboKuJoCiWAl++yD39q7TT//cqDueso07Zbhnk46GAdWxvUqLlufydt/QnnoAVy7RADixcMXh6vugHpiUpHKpKiPlFOo=,iv:P+S/O7ivQRVSbCbwrRTyrp5SpEUoTv3ayM8GT49R934=,tag:sTYVQGe2HNJw1qg67yQnSg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
