prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:Q9j/d4KyNORaTyeh/Q==,iv:UI5Prvzu4vDLlSxtcIOvxc5UOgXoP4vgUhYDoZrQB6I=,tag:K02vL//q1gXoTeYyrRewVw==,type:str]
      value: ENC[AES256_GCM,data:lIOqGt7dcZL09k8v8CHdD333CaCm+ilDLFI8R6aJDTmaywvC1evLfyCbBQ45BzqZouOC2Zz0RzTB7Ij92Y+yXvM2Y1Sq8WBOqobSOD2Su5gNiqM65HzzSO1xioC54zuMbO0FStUgqNPCQPpXgIdFslRIQZKsT4SsZ3J7rdj3AZUcBI5Sv6Z4XOQ3N/MoDQaCdyJBaF6LPJwLKhLqc35ldIZrde3UUX+SpuumXxGXz1a3FA==,iv:rmXxsQyyfJUbkptNKKGG2Z1/J1fk73PVFYmtf2NEEH0=,tag:yYF+ILpY1Txa6YssAXGc5A==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        LHaB791vqQdCtiBB6jwx0KB4LA5zgeryfRV6ZEgqwEk3Kz7tv0aMjobp3G9ZYY2S: ENC[AES256_GCM,data:6KukcyWGtS/e9S4t0wRZv58GzFSDe9vGFnUAqu/kUnz/dhf4MiYhHywow2il5Yw3IqV7Qe8dsKqV0JTJ,iv:u9OfYJ/n1xtPlUSGyaMvEZJHEy3tHQShTzY5p8tcSeU=,tag:cxn0KlL7lZl6VP0bGs9+Gg==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:/cXDRw==,iv:iVGTwuHC/voaEoKyCpXWWgWXfOJkrhMZ0BMguj5vcpA=,tag:miAfmlxl3H8dcWlhkFY++g==,type:bool]
    username: ENC[AES256_GCM,data:PKy4ETic7b+Gwi3cAk3kh3gOzquXY/kXdkDxkXpkkL179Q6A8tZL+5TtgmWwn+okUpCRCsPSFUBMFxf1NpiKGg==,iv:0SxA8Vwm7fSKxFIpXCkZJKjv8H6WSUOSQb/Y/OS0WJ4=,tag:NBmeB2DtHR04TRra5GV27w==,type:str]
    password: ENC[AES256_GCM,data:Iw4LQuRtf1GAeOnzHYfvNkYR16VMtadtUVc4v+XeYZ2w1PtyliydbZ5az1shrhRIEDibsX06Zt0e1V6b9ZvIDw==,iv:kYMZGyhu5CyTnK3tyLL7Ly32+lPvBkzQHRYCkE8dryg=,tag:4U7BnlAPFDxL04RFgolTOA==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:cFkxEetmhHLVi0UPYiN2mNgQOBqHDHEY/zcMVlhtXwEt6dNjXvDsfEa05oSjx8vzT2eIkEcJUjuSRu8KS2XrmQ==,iv:DRsXH0hi6ZANbs0BUBcOFFN3WNWVC3ECAYiFgxVYyqU=,tag:G7erMkMr+u2odwHRlyR7KA==,type:str]
  password: ENC[AES256_GCM,data:NXOsrK3wYZOkXr/reRYyrHQN9/JZP17LYFwbXN1JrEktdkZ03IyEfeOzhM2VZ62Hi3ibFlNVsxxsWsgUH3xsWw==,iv:GlNC5Q2RyKHTy4Zsm2YlH1xE70SsoKb2E0VkmYA9DII=,tag:c7pwi5qHn7THWRaBfSRrZA==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:22:08Z'
    enc: CiUA4OM7eGUZf1FlLZjBAk4lmfsYOkY4aDxW7QF3aTJz5F008YeJEkkAmy+ekgOl7WJzj4cyOM7VskiEjxJXPUk3ZyED2mzju0IdgCv/QMw0WdKu7yZGAZ61rQeox8Jdzm2XZjE0vPz1SrefrpveR20b
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:22:09Z'
  mac: ENC[AES256_GCM,data:ol5exOmeIuMAV4q0za5b74U0NWLgLtESwvyl3DcycIG+FN5bjg9TJDERCFGOynmFHkFYA6cQIN03skgtHRUiEpIND9dm95ohmySjGQh1sBvo9/UZlekERJ1Ior4Y+6+aLU6Y6aWbEzUoCwfYeqWzYZMluKNraKc/U1Q2g9/eWNE=,iv:2EtP9r4p61OAZxY3VPm0lY3VXIrrHvjEQELT1n29VeU=,tag:+FLOeLUbTWRXmv5gJIdk5g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
