jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:K/la3GCh89bJ2GQbPP3MKdCYnPM2Lp+3Lq+i0gtp7Ik6skhFK+pAt8csVkUQnzKHOLl2FuKBUq4gCEQZHVTarK5N96oKVprjOo1fmCpHB5cV1HQX1FHyOrO1lhiu5zjrcAp1lJucx2A6QUZU,iv:Qh7K71wI07kLhi4Rr38W3sf51jxpsKZ2Hh5r6KTM2Vc=,tag:ZSIeeip5iFMHeapqeV28cg==,type:str]
jupyterhub:
  hub:
    config:
      GenericOAuthenticator:
        client_id: ENC[AES256_GCM,data:hRQuAydniDTcgSe73vCt,iv:B7X5K70oPKwVUU0mNrEfiOXRVUf6Nb+yhFE74Qiu23c=,tag:jUHvMoa47paCEMvutzoMng==,type:str]
        client_secret: ENC[AES256_GCM,data:s19cYd7TckJe098+Lpu+lw==,iv:JolZqREunlBiPGPyaeHoKQVbtDbi+bZy+wzbgwaxBrs=,tag:xqNodPicP7/SKa8ZXWKKyw==,type:str]
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:Ai4NGs7Uogkd2rXT/kP7QsijymY=,iv:JlJnVFU9T5+9gR1bGQj+Q5pfFpK4b+TWgpeAcF/oYys=,tag:kMApKeHj48trURznIth6eQ==,type:str]
        client_secret: ENC[AES256_GCM,data:fbCKjYFVmgCNbJkiX7Edi6AYUxIU6uJHRhEIG96plLo0/33vcMFxPw==,iv:8Tws1ZS8M0zTXWYFJfmpFc1O6rcr7Bg+xp8CB9xox/8=,tag:rsy/CjgXHrpGWpamX2r33Q==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:d7A6gdYZajaza+3/X4MCQyVx9WGb80EyEZ6QG7H07c543EVgM9MVe6XItMWAYwHQrnlCyxdd1FPGZ7cwiSE05pLbgzJmolZF0A5mpnyc7bQXgg8JzEo=,iv:6GWG99d9rq3QxprcWNmUzk4vnJBuUdjOPvhqYVAKBRk=,tag:9yk8NIuCE2E4/BLabZlkXg==,type:str]
        stringData: ENC[AES256_GCM,data:jqrbM8d0LpEMxBKlpiLiAjoRjbwAzCu9PNSJC6LIbX2HDxH93tqYPVGZN8ib53MFYydPwR4oNc8N3yKsj/MyZ3LZ2ShVKKQ7Toj9/jmc/KynKd5hKhwVABAOmzER5kKyBSysYE5Go1ol4L4yyzqm0bNfzvc3oLFoiMkIdvnzQnCjMeBiwJdchHdO97FMNcEOwYNjxIO13gVmtzr/WfmIE9D8SA6pwrq3fboAlEFts7HDhLLzNFDPQlPq/qsd/rLBb+1jW7vIWXESKD+/4JFHc/eEM/TOpJQ3xwYtVQjAi2yZmqMScJdr+Z8NtlJtEu+sS8TJ2bQ7wGNxhMiRnuscavgGF6hvYsFGxwNjQw9z1orAqO5nGGQnockUNO1B+98BUr20fVde6+Kp1Yw6xt1KdYXHk1475k+UDuUL/dhQ0SJDpoLQEOP7S6ed0CO7dfUI7MGiXRoxeCcY1AAg6bmlcbwEOqxZmjG8wowga1s9xri+kHkv/+5HmiPMcRijk4jq5KyqXwlpcvOKPLxuf88/VuOjT3IqxWX9rFUP5Brkiv/Myk8PPY+JXk4VDCVJEF12iczmC4UFxWNi8lx3b8zaptQxg1B7GV7Sfa1WpfS5CqHEIwxHKV5aOADM5QJ/UrK7cKKmareKnfE0op/Z7PsklZp0tOb4P67RFLf8XQ==,iv:sgjNcxauNcS5w9BK9aVTepNmANWL/jCdST9Uz5+Wz9o=,tag:T+9Y6GlMO9I4BO4NrIstVQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-06-26T08:53:26Z'
    enc: CiUA4OM7eMHoxJ45f44IDSbeC+03FfVVw3R0oYUF0Hf+d5q5oTSREkkAmy+ekpb0Ohuh76CLLl3CiOPIew9+YN+dzjfL2nutAzKiBVSPrRBXRdCMbX1RfwIeXoA+s+BPmEGH51/meugcVwfGlYkJsjbP
  lastmodified: '2026-07-30T19:22:39Z'
  mac: ENC[AES256_GCM,data:FINUSzhsVsPoqX9hYyLg0gHVRhUChJvOlfi1VMviNGGVrbIcIu2QrpcnM/k1s2WgseYBaQMSH9cCHTq3g/9iRwbbL05s3vqMTKvqhvwMwwCK/myzIOaK3NUOXOMpkNjYZo/Puts5FU4H2XMZ3b6ev8qzHzPOGJNpIWIhI5yAqLs=,iv:0YeKrfqIq5Xr4D4Gpm3PpWw7XDEssaEKbMfx0/hV9kQ=,tag:DL77xBi9aCl71RiXMtxZsg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
