prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:azSRgACBDrb4sQ8Esi0gsvK1suXZIsgPqYsoVU/rKGg0d4eP77OkNIxZmhqSzaQJ0hQ3T2tGw0RnmqydAdp53L6uVq+UgVbHIYmzDXXVRpDvLbziZQ0ioxAIF6egsmiRoYnCU1FF33zy+j3P0KC/Vpk6Po2pS5pUPUhZ2e/YwHlNa/QsjqUWeFIrVV19HunrGkPrCjbbpzZhImPp,iv:XWgMPw5TpUAMxcy5UB7dT129xSSPgpzI1ZtZstmW4NU=,tag:N/NwEdyV96efAtZtOIkMxw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:BB/vFH5jrJgOY6bGGcSm3Q0hqgYDdIFkwxLe+/larWFJwJAlECY+7igyiiTNHU+/FG+ak/nPMfGI2Z/qzipmrA==,iv:bye0V/ywL/iEKzFacVZy/6yTsVwk6iMM0zc4F/b9Ua8=,tag:CTomVM59qttxSfsgkYJdbQ==,type:str]
    password: ENC[AES256_GCM,data:+jOutHK9hZBFfdpLmIp1X1hUDxubDDZ1W3Wznee2CZRQKuYq2J4i7EeWbWOrFkopvhKcONx6pDdrNVEeitoIJw==,iv:zRcL5ZRoGl3G3vFRbKsvP7TrGsMwVHHSoZYAsgQh5G0=,tag:pYkvmul3whrFip9HTpyxqQ==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:3YXCJPqpuPIepVC4Pg==,iv:7dtfoUoRDtBqTtNE80q1LhYUmcd2zDpe7HRZxPGfodc=,tag:mmmzUoXEffQwW4WlHKZpDg==,type:str]
      value: ENC[AES256_GCM,data:idq1fNH3zHLayBYjwcMqqL/9T/eq9o1595uYK2jCwZOHLrzWg7xCJiEOT5ZG4CgPdXHPVdvx0G+T5ru2l0vEibw5mT4S49bMEQurcaczA2n7aCIA/xv22/UC9FZYG/x66YUALBUbOKrAcz+ko9CpyD4Y5vJgx6GFpe126UpoWmtmGpjmp9eQa5vzKXQBdE6C8pVxQ8nMlHh1E2SFzqYGj8SlCn8c7VWjvGXqnBiTnV9QTA==,iv:Ae2kGcSpi5eV8b39r+bw5FMe5LSDdxhk9HzSMISn77E=,tag:SLFKmbx/s1xHewrUqunEyQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:en3gY+YraNc0eOm9llvBlH7DT+eoJB7hVWdAIrmVVl0A2mCFS6JmJExCPpF2Q/XuQqP1QbIg4vZDLUSEoNNVTQ==,iv:S0Pc9VCHQuLFyMncd+NHQeAKsnIVKQx3DL8atRTT9+4=,tag:XeBk2C+B+IOX4KxMAqzUyw==,type:str]
        password: ENC[AES256_GCM,data:KfNuOWYzhmWbHyFTis9xH8y629wxZaIgiy53+kjjNsSNCIb7YdGzVoGCMOrJGZXZElzlI0pdtHreZmNflrYWdg==,iv:Y3WKi73l0qaf9677GMW41zzUy4Zk5of8fIUj9Qw0VQ4=,tag:hj/UEfxLQBMb1LtK5BEw4Q==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        LHaB791vqQdCtiBB6jwx0KB4LA5zgeryfRV6ZEgqwEk3Kz7tv0aMjobp3G9ZYY2S: ENC[AES256_GCM,data:7sR2RWo4wy2jodX1ObYTw8EetKDM7NSTOFYtXqcDpq76H47I8xkTOhl48RRi8N0B8Zj+sCrndAw5wAt2,iv:QC7qjgM/S+6M2AskCfUlXG1f//L9WHVxbeO0f60PTT4=,tag:s6LVuxWIwKfqQgjC2ODJQg==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:NA==,iv:NQqh/jQZH5OHCZjtAn/34d0llrCxiRjeb2fHR8G5S3Q=,tag:x0/jw4G+8LbWTdEJ5GAJmg==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:GHRN/r3esJdI4g==,iv:Tm9i2KRk2FkQvzYVzFb/4rGRv3wFhl9+eS9ptpY17Ro=,tag:sDsxdsXyxjc2M+wQPqcIeA==,type:str]
        orgId: ENC[AES256_GCM,data:SA==,iv:z7MStw23DercauURb3CpH2WG1ssaKU895IuOnT3xcc8=,tag:3b1eFx/daY09WkMKNbGBXQ==,type:int]
        type: ENC[AES256_GCM,data:3mhlzeqhvzrFGQ==,iv:ZxQvX4DYocif2eCJpdnolBfTzas1BjaiJzWqlYIRgaA=,tag:z2i5X5Hm2FT5jmqxNoiUTQ==,type:str]
        url: ENC[AES256_GCM,data:sz8DNIQ4iKtccbnHddDfCtWVxWnhU3poyADmf5WTJUI=,iv:wjZtMqCnb5Te8Zpo06TJQvOyTWKBHUsgo/jtaJBST4s=,tag:IDNr+bsQdCEgenEMMR0roQ==,type:str]
        access: ENC[AES256_GCM,data:XdE2g4A=,iv:iwYMBYeWKVEjXS6C0MOVkqhCY2M1hnHmURxCXy6uv+U=,tag:mqibdY3mzKsLI59hVgFcZQ==,type:str]
        isDefault: ENC[AES256_GCM,data:nxUqDSQ=,iv:kIg9bGDfJ6LTRqVg/3grSJj6dQkyTNZDs4B9jr1+NKo=,tag:zExy2RsfDA77na6EPkR/BA==,type:bool]
        editable: ENC[AES256_GCM,data:EjUc2v8=,iv:jDQgzpxJoXCVyms++D4R3XBDvdjasdrfwoOEwiABC3U=,tag:+6xw/C9pDd8El6LsgVSAvg==,type:bool]
        basicAuth: ENC[AES256_GCM,data:RPayYw==,iv:IzCuqV9vZ7qtDrq/Xiom+d1+jJ1QVh5kV939TEdsvc8=,tag:xxjskWkvJbZoq/JpzEHTcw==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:eho3aTkiLlADPaK0KmN7tNlQsyCvBHc90zEuyBFkRBR2xMUcFI6J7A/cHWy4QUWcT4RR9B2u9vOsJjpd246szQ==,iv:u7768tEOKEHKBsJYB4q4H/2+BAGb+ozfnUC9zi5AfDc=,tag:ShW32v9hu8+LDklvMgpBPg==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:K2c1lum3Ja5pZygCCtrg5cEiEqCn//BQnCl1iIbmvs7jPCmY/kWVt0cwJBgpxEtHPER59p/9kHmNXbz1lmZN2g==,iv:LVeecQbKikXAjNu+zDmt02iJet093x8XMsxW62REZRQ=,tag:2+TCRCZv0Ydr0QePNMpKeQ==,type:str]
      - name: ENC[AES256_GCM,data:Y+eEU0WRKp1isu7Dx45I0h8f+CxS/SHkcxKNBzaAZw==,iv:wC+0JwXs59y4QIwZdn4+6bS2OkQgD6B/YLfGgQ7+EUE=,tag:xZ+nnsOZjyKEVGekwbSjLQ==,type:str]
        type: ENC[AES256_GCM,data:rCo8ue/ABJoJVrcM0AjHwxTxOTNVdZIkX3AC1Vn5tA==,iv:iz5N58DVX4lsy67XbEU4fuCcSFKL6pAFEREl22XTEL8=,tag:Ok7BQZmuMIv7YJR1jvYqZg==,type:str]
        isDefault: ENC[AES256_GCM,data:sIfpNhY=,iv:wQjjQAiNSBQILisp5xUwPG9mK2zRAMUyIwNdubo6F8M=,tag:Mzv93QL5C3Mb2QAgmBJxiQ==,type:bool]
        editable: ENC[AES256_GCM,data:P2jLnA==,iv:qEoFz3CRQqfR1UsWUCplEMoLw8rGjdIM2Nfd2eC88eU=,tag:ADAX1G9SWHfsIyxb4+G9sQ==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:sX/o7Q==,iv:gnCCdfkFv+7T08xNC0hk9mjfJxI92w+8m6PTnyF3cy8=,tag:vmBvo69YphCqZeo4NFd/Kg==,type:bool]
    username: ENC[AES256_GCM,data:sOGN+jP811bGZKXq8QjQ9dLfxyIzyJbTaZTvMWjfSi1bW4WSND8CSYvHuZNptbr6Fx9PXkpuAsXZikClL9ZVRA==,iv:o+zWtvcaIw5Hd/tuvfMKwiR2a4Jpw5PIxUls7oSsq6I=,tag:41lakMAFx8sXHNw5QVGXLg==,type:str]
    password: ENC[AES256_GCM,data:WjdQm5ui0i+/Kalsk4ZkYXSVrjjE5OJDomIE8kZPjZS6MQH5jNyJwKZbZtcZaCvhIi1jTNe8xWIfiXrh10JbKw==,iv:BWquoFFcIYzpMVcAJuzGNq6o8tRz/F/Bi2myFcSL2HI=,tag:F7lO7jcVPgI8ZiZLv5o2cQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:50Z'
    enc: CiUA4OM7eO833NpsEHSrvcJrsZRpn7qY8IpjiHtq2DJZeMHgY8mSEkkAPHlbmSgtW5CF7gJYMvGnYi9PU7+8ltspNnh+sIorpFoj1ibHzEBzYADnB0V3LIqRSGV2ZzLFB9bMsPHGCuC/87p/ZJ3QBPqn
  lastmodified: '2026-05-01T14:40:50Z'
  mac: ENC[AES256_GCM,data:WphUgKZNRWseMwKIlYPcJsJZf8L/Vibr68a2GYTsRIBb9zlW3Hy7ad/mELv0lHbM3Z7KAg65y7k/hBcIyNTeMWbzFI3evLCrNMvCu94hpLQIeWstvDYhsRKgb4TFxfjIo8WwXtwwjZ/tXnyKVvIcW2f80k3WSR+us5/scNTKnRo=,iv:Plk6vQApdWZ7rSvkmU9QG1L8hHz59SQhiB3OoZrJdmA=,tag:dB4hZFoJ6q+92wkvBoF4lQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
