jupyterhub:
  hub:
    config:
      GenericOAuthenticator:
        client_id: ENC[AES256_GCM,data:q64domPOgPD2V7Y3ZV4u,iv:2Gnv1j3ZqkqI8eucDwShXQnm8KKohHS83hiHxfex4dQ=,tag:1ZUcsUGCphlsCG4fmj3rwQ==,type:str]
        client_secret: ENC[AES256_GCM,data:pXzeL70HiouSPPWOpnG29w==,iv:TA/YskgWihORj+U6hVw6fm/mfnMw4OE2hVwXeIFfZqk=,tag:RDKNgk2EtU3Z30UC8OOn3A==,type:str]
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:cPEcTPLvC7puTwUvPPtZQLsqQWQ=,iv:f6cFPYfEnXbwCW95pgxqz8OGG6SwiLhsyK3exNNiep8=,tag:k9pA9kSZyV4+t6WNLPO07A==,type:str]
        client_secret: ENC[AES256_GCM,data:ixcCe6t3OMOOnnvc9GdBjgy2F6RVs5cnLU5Gs3UVWDbvfYwBX+zM8g==,iv:9W7Nezf38nr5X7HeSx/9N3STD333WrqYzlja6PxVkP8=,tag:0IZ5LcCQd2Fswu4Zvxq/gQ==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:wTzo/gG7QnSQ52hRvRXV5ESbYPzUilMC4VTsAzv5dIpKyPa22WKhnvUMvqmm39wmYrSJNGuRczjm3KVyQ0xK1sr3HAzHRU6kfRGF3I36WsGk2awO0h8=,iv:0XOwuAN6kQHes+sBnfc7gswdI24ptgWCUY1gmj/TiKU=,tag:roStB+V+xIOjTaz18fPH5w==,type:str]
        stringData: ENC[AES256_GCM,data:ASoZbxNExIh5m26OruvvlzsH0qZ83OS02xjNF6mxzjjEwyueGvm3N3Gw31NAyhFClYG423TPPnwksSEbrj6pXjV1O1DmF6oav3RHrkw6FvFKbvLDQTs47m+Yfyi2mhUL9HUVAldv4HTF8QeOb+OxJxzl7GsbO6rXX8T2Sb3MKMB9jh7ptmupqMN/Im8CmA9KriadjaoKa6NWV7XY5vlewHJ/mJc96L4faoVcsYPu2ha464iZ6imzDHnVaZuo6qaIHGpRHWhD1hN3xZC5cYpLRKn3fGq0k8kJMJtcJY9GuSy7rn6eDvGAcEbMW1FXsermx+ryAV8NYQJrSIogd4M8KsXAvkilraqxfqzFFhdF/MGUhY5b9m4zQQy48Wnf7cRmsgO5dz0DqzqLUnPJMVGGpnyRt/M9b9nPjo83Hkp77gStyHlXOwmbiwYekHo83xk6/t2h/7dj0KcmEf3FaKZXQsRyPkSvsaitu4FNyG/H8OjwhDJzcUrocqjiTow2/TwMvMAmDQPGkEDTrbcX8vFPg0dcUbpPFF3NAIUvDGvlLBQwLQvu/MXrQUchtyjEawmQ/fK9O9d+UGtnaT/R25Zu7lG/WxCqtGa+0OtPblamLuudiXbztyT4bcUVGdrCwPrhV5iGLy7U8A0btx0VCRVYjp4hrWNH8npOH3jN,iv:UHevKLQKZMFp3G5bW4P88Hgp3mpBwKgnj+AXTQdlUHo=,tag:PRlEwrdcXfjI8F96tS5Qeg==,type:str]
sops:
  gcp_kms:
    - created_at: "2026-08-30T06:18:58Z"
      enc: CiUA4OM7eAI4z3NaE7YMFeUUJNelRwdgvZl14NKCEn9bE7pOlLjWEkkAsHDEl44W9DWv+M1vIp3txHLVtcRmfEKo0zKO2lN/RaVD9AE0iQ3tS+tJiCMHOplsBgXK9lWr6mXZQLBbDjZF9Vz3TfqspCiH
      resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: "2026-08-30T06:18:59Z"
  mac: ENC[AES256_GCM,data:4pyvzpR7VM9qK+0FfOSYk0OgifEPcFDWJhzBYs3zDkgsI7mvIVpKTPGoaPFktVchlGIITtd2jW1xZNzNlL/3+U7patagRVs9x+UiGKafHtLPJxf0gnUTkTkF7MDM/ZNqw/XxhRDAZttPuVzvIfFEJCxmqjWzhn8qxTP3HfiX0Hc=,iv:5r+wTX/gj7uX8o8QxWrAglhYKX1he/f5/YGwYOU2U9o=,tag:Sai9Bcfpdy03Y66AJN6hjQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.2
