# Read the Docs configuration file for myst
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# This file was created automatically with `jupyter book init --readthedocs`

# Required
version: 2

# Set the OS, Python version, and Node.js version
# Note: Python is included for executing code in notebooks or using Jupyter Book
build:
  os: ubuntu-22.04
  tools:
    python: '3.13'
    nodejs: '24'
  commands:
    # Install myst
  - pip install -r ./requirements.txt
    # Build the site
  - jupyter book build --html
    # Copy the output to Read the Docs expected location
  - mkdir -p $READTHEDOCS_OUTPUT/html/
  - cp -r _build/html/. "$READTHEDOCS_OUTPUT/html"
    # Clean up build artifacts
  - rm -rf _build
