prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:nToYluzzXn1KbSIMYJefnpHQi1CPJXIkLRGv6DCkKU2lwewp8nsZwtmrzKrNVgcOOs2W8CKXQYRT3xzydCwAP3jl5Il0A/g/pG15LDzQyWFcI8hzH/A38dUH30LMZowExuhzEbVw02BJ4X24EL/+UqvhKkJRrtU1qemKWVUNizuUU0bmMgybjPLOEbcXpQx6JwozHFpjOnjNl6ve,iv:LAbwZ1W/tX0ozqWScBZCHrxgez9EoMJfoxbRXErZNSg=,tag:05lDWpWAgFns1ysrn344NA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:tRRe8t0VqrHT1W9fp3bo2QIPutX+meDCfHZUh1o85h4cDrkI//TleSfK8/EWEFeCu9eydp07ajyAsppvx5jAPA==,iv:OKUjS3gFwo5uNXTrqeF/UWBdHVyYPsB2rq5N8hBEhqw=,tag:WhLTWw6pLjkJ2yiq83kQvA==,type:str]
    password: ENC[AES256_GCM,data:enzj8pbwBNF7IZz2Afz2KeQRni8tV6kTE/y05TalOTh/0vhqC4yGyRmkbYtyRgnxhblA1dHh76INsmKA4Cgu/g==,iv:qV73NlV8RXAkiZ55Znn2OIpWncW84F4nZUehvJcG9nc=,tag:dTZESvdmMqo1iq36VlcFVg==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:fkQs48f5PivMf3yYaA==,iv:h4IaFhBxVnX+Q7DfjbeENminIdeuU/GmptBYoMSDi7Q=,tag:n9KHk8Ef+TARv0RLJK1ynw==,type:str]
      value: ENC[AES256_GCM,data:h7NDVjwXJO/4EWmQbXWKFeecSaPgZUgFNqLCTbS686l97ww07j2QOcVkL4HxTvlYHmEl7kRqBpO2Rkak7YSWdbVLIUMK1JfnRnqmXjjJ2zbgKILJUTCNm6jA6pnzhLlGneR20POyS3MItM5IaGCJeJ+Um4h31N2GkHVeqaw3c0qDKpzuvWqsms+XnBPh0qCsRBu2ewa5kRyqSLjIb7A/mem5hSQyV4bXn8SBo4OSTHfn0A==,iv:wmj8ovg7Ez/l6H93en0QrUd4cxkAVH67JiLaIHD28io=,tag:Hm/s/sePyx65R1iEJWfQlQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:0nTrkOutZ4mJi3DKUcAY5QKz2Bd793wKabjYcHFV/823v07/Un2F3eVe+7fC6Y211ryPwXuZdgAwjDdc77214w==,iv:RUibzhP+pjfJJ2tlL8qrfM2KYvYQ+IRXlWaaZql21Uc=,tag:vLgmlG5QVNuiLTh5UIGzjQ==,type:str]
        password: ENC[AES256_GCM,data:oRudKJ/s8sH8vRGX97fpwaXF3o5LyFl7LgqETHAfJKyaoU5xC/FSUmJ5dYsx43egBdRVc1T8+66QO5y4nFJuyQ==,iv:16Ntp1f2orCAoxGJRMUprRBBzACH9tq7Be5kAgRCyj0=,tag:3NbJGhxAFyn/N2CPC8LH+w==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        haZKNVqTzKp0rZcfR2U65WeIWc9dJWmWkN1R4EyH1B6wzJTSG830chWOsFQdmgwZ: ENC[AES256_GCM,data:0QpI2j/AE781zFBNKrTg3g+1Dj0KYPQBJw+RsQb7aNIKYxIdj1zUeBKle30d6PMozAhMx5nT6PLhxEaI,iv:1zkhdjyjaYlO7SvxhNWElXnwXjPT4nQ7/riAGdk5H4o=,tag:f6x+rYdKkqh7Nw/eEIW9Xw==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Zw==,iv:h8TtUDQ5BCey5tSMc9mtr78zw9YQSuJfjmNY+wfOhKg=,tag:EUx2sQZk8vlAGW9PQpUMyw==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:XT3cmd5khazTLg==,iv:eU19zneuM21N1gFXRTezuHw3aFotYU+0mUZEmaZBRlw=,tag:qNKKwEGusW/3Tu1OIMlLiQ==,type:str]
        orgId: ENC[AES256_GCM,data:Jg==,iv:p8IuIdRIr1OZ0Bd7JLj5the2gfZQ9/Zq6iusYL/GSg4=,tag:fpvHRMAnhdWFCI5O3D+AQQ==,type:int]
        type: ENC[AES256_GCM,data:sGyu8bupZKFnuw==,iv:5UGRQinFttCdYe+Tsc6vn+kCk+sTiYkdhXEvPcvXV8g=,tag:mzfZkVAhB00u1srXEC23Mw==,type:str]
        url: ENC[AES256_GCM,data:gorVxpkfkSEzhrCtrqmxoXzJYWjyBbgEAtdr7BSSdmI=,iv:pESJF8//CH2PqRF1XGmoZ7R+icqHlI3lNfYsjtL5z9Q=,tag:xSJv9hRHxmmlDdovDkrJaw==,type:str]
        access: ENC[AES256_GCM,data:xZc7K0A=,iv:JzaQwzIhl2nhia7QZo7Ywuac6MtQcTks/LxsOMsVYg0=,tag:11GujjK5GeVQ/J0DpSfpkg==,type:str]
        isDefault: ENC[AES256_GCM,data:Pupr7oA=,iv:hY/kFyvbG2CbrMvVlXowwrjyf7+LRuavu1me/L5/Crc=,tag:9DAgptRgeFRyiF4SJLJDOg==,type:bool]
        editable: ENC[AES256_GCM,data:LYp5YPc=,iv:OZiQtWdiirFHHpg3OHiWwWXregVFhqj3uVQfl9dM/eo=,tag:iPqMHc0XSjAjQ0KpTJD2Vw==,type:bool]
        basicAuth: ENC[AES256_GCM,data:U94mvA==,iv:ZIJcDrriudqyExdyHusf+unQeyR4/E1UJxLWH0eN2S8=,tag:EV53kyEGJN2ApfSnQP7UQg==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:Xcbo4/xVoao1jrTdAnvqzHoVW3wSowKnnx0c0y5+epP5D3okZYU1BS5LAVFCVx32cJUgIcXrMLwOj2J6XRqCIQ==,iv:DxRfhtvkug0X2RI5qZpDAVn9xgrcCs5180RuSQdm8qI=,tag:4ZGB8x0O4FZLWEsqmMo3wg==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:B4uEE7BslInb1mRjCPOP6VKi8GeOCkej4h2O5tgUVsbLoQFY0Bs3IauoPyFDNTQKU+XL9bVYvnnkRTi+yE+pQA==,iv:F8F4yIhFIelYrIItwPR/2lA4lqWqmGKpHA9qlezOy0Q=,tag:xQAM6PbiSSAWhzY7qQUVgg==,type:str]
      - name: ENC[AES256_GCM,data:WRr6c6F6k+YekJYUyvcdfyYRE8Bi5SAobwM3xUf77A==,iv:oP+mNU0hZlXFXK3d5+yyxfY27v10aFBOALwA2G0fyKs=,tag:fpi+7r+8h5DNlwRvNwXBDQ==,type:str]
        type: ENC[AES256_GCM,data:COb9Bp8OlwZ51BvZXq2nwBg+xYqlH/NjN8ryxbCNDQ==,iv:jTZSnX50e0iJZ7gQvGZirNqfiMChuUDdOB1mKzP700A=,tag:P2fyGjBKBR5/mbh4x8lxpw==,type:str]
        isDefault: ENC[AES256_GCM,data:DrKEPhM=,iv:e/mHqegBfDMgCDS2bOE+Fbyu945VshvRP4KDVFTyfBk=,tag:41xWdlLmFBEtlEEQlywJkg==,type:bool]
        editable: ENC[AES256_GCM,data:1CUzvw==,iv:YsvGP+yBkPuxBmbuye1WQo2UVJx9pIoWXtIvPG0/liA=,tag:rfUWAXRCSHGVfhlOoN2CKA==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:JHPLRQ==,iv:6+kF8chpoPdD4i3OuR7lx7xKsvbLSNW679ssfWY465M=,tag:1hIK5xhJTtaR4ZXuAtLhGQ==,type:bool]
    username: ENC[AES256_GCM,data:PG5tZDf1UdinjjJ0q2L57H9e6i1VNYace4JQ4vXlOD3tTeh7aKvLvf3039ZhFTpiiVABpxX0DYL4OkVwnjCpSA==,iv:Gw7pmP/PyePbhlAI29dGnBIaSQ8EjxvMcqYCmy/WjZ4=,tag:x4W0Nzqh+IXXYLXlumcOiQ==,type:str]
    password: ENC[AES256_GCM,data:6cWQzGgSjyirqrW3dx3rgIPVDPatEhXACTp1Bm7EXw+tGOdZjzJP2H7nLkYI9XeK0Q2deOeXIf1ZsYDh0fnw5Q==,iv:Ekk+i4aoS222CfxgG0nK40wnY7ZSGeaVoSzzKjqDc7s=,tag:Q78fMScpSe/Kgh6Dq4TVLw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:56Z'
    enc: CiUA4OM7eGgEdq6HFKAIxXwpRaG8cu3eRp6u51F4jNGCv5rJaTpvEkkAPHlbmeQxsm5hZ3RC9wdpoVxHA5H0vNRNzKu4wh4LiW4zF1XqvRzgNxira8wTABVgQMFuT12OAipow8D9vQSzSzYc7L4kB3at
  lastmodified: '2026-05-01T14:40:56Z'
  mac: ENC[AES256_GCM,data:nJLiTejVWAH+Nx39FvqMTso2ti36P2zaVUgnKIQw893Smia2BQmGEmxv3dG4VjbxA42LdOVgHpGi5HoYebQzZ7DwkN6HxSK3C+CKpC8V4KgUt7Jdlo50Y505B2bhNb5XNFNwBDoUB87npWcqQrzw7s+i0x+OfOeGL8UiNdsemNE=,iv:uETWyZDa4kJhMkynK8SxpTr/nZmPjuEa16vuPu7iIjE=,tag:sphD3eQXUq6UIMukoG6i/g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
