prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:Ix2Y5nE1UTHZN4O2Mw==,iv:Sg54f8YXUFuo0K1foAW+lSo5/iFr4tw2mULQQzNwj1g=,tag:z7ldwoQFrP9H0Wks0DpX4g==,type:str]
      value: ENC[AES256_GCM,data:dKDUAA3odStIUrvkvhTuNTb76lzIpMheklMyaRwbJWEx86XiP3ZUfJafTKU3GmOnF0ejeLsLX8b9EZr48vNbUbrDgpsluwMNCXFjW/PtiRfPfHoKVeJtHbLmMr9RcNIgy/3uQE8HRb2slDg4hRhbkIDaqPfbEiMe+vGsyNFAnFlx2rtny1jGdiW8m0TK/+W5I+JdMuxRV6dpX9eUBK6FgqsMdvucgFnHbgqO2Uat4YpR5A==,iv:7HNqoRmYBNIf1luH3b6XkbsZjQNeYE4QZOkP0Y4Xhdg=,tag:ROAWrbIYyuOPsCfsK0J9Lw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:yH69oqM4MUV0SVvoipdG/89vijAMPSRRnNu6OMOZwCF8ib6T2CpMxIjF60K+vhTVzfWns02HSGnbyNJ9nQYi7Q==,iv:9iNzLOQFuAm6Z4MiC86KYLpOv1XfnQktlTrUCVUphOk=,tag:2+ShWi/OTC2YAiimKt69ZA==,type:str]
        password: ENC[AES256_GCM,data:XOOeGqwCa2Ux/XIR8Zo1Dz71mRVV+C6bOWaEPnTX5HoqsP197FY1EKZPnD0GqdTbC/iiPzV9Y6CSA3ec+qBiZA==,iv:e5lKBDo7CVSCL79o6vSm5S8/YdVMpbFySnt8Sw8HFvg=,tag:E9YbtuAts1WBQ7q00Bh1wg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        haZKNVqTzKp0rZcfR2U65WeIWc9dJWmWkN1R4EyH1B6wzJTSG830chWOsFQdmgwZ: ENC[AES256_GCM,data:5PZutjc8n0SLWyot+HkUW5hP1QUFl59xA+xAiyUDVenD1qmfofS7wHMbUPtw8tXpq3CNzJOuONdiGjE5,iv:YZaxxtepdpi418LIFsj5VKd0UZjPzjX40pCpzmnIWP0=,tag:lBdgITkg6KtxrUIQdnJiew==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:ng==,iv:ulttaH+BnO+vI+Hyep7cAVe9y+/DXoovcxb/pNMwQJA=,tag:1K9f7rnVa7QJUOWaalVCxA==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:NZegd10Gp4Unsg==,iv:VjIGmYG7TbODD7+RtXk6Lug/12+IDBtASQACReKLTG8=,tag:6J2Y0fYysIXUwpSVJm/d9w==,type:str]
        orgId: ENC[AES256_GCM,data:LA==,iv:UGn4rtzF3DO0qd0FwT5C32z31i2/BrePH4u5S0sgSbM=,tag:5LaR3UOry1V6VCTCl0Ouiw==,type:int]
        type: ENC[AES256_GCM,data:v4/mdRtKQEnnTw==,iv:RJ3d8oAkcMwH6QLnEa537BEeMqMEBd4I8OKJN2I143w=,tag:J5pLdKLSx8+L9hMMu9Mv0Q==,type:str]
        url: ENC[AES256_GCM,data:4D4QCt5XU/caQbqO6ZSEVPtUOCyX5uQtjCcDXD+mDXQ=,iv:zIlk4wPdFby9+l8IszmEqrRQc3LQstVIEEoJti+DlJ4=,tag:pXdqPZ7r0wzJEwzITX1qpg==,type:str]
        access: ENC[AES256_GCM,data:9NeAEMA=,iv:Jlut8S56x8afsWxqvk/htSzl+j37PwERuADSOgl9bmI=,tag:9Mzk33dVb0t0BZmtpX21SQ==,type:str]
        isDefault: ENC[AES256_GCM,data:PJOELfA=,iv:1qg5iwaco4XgI7X0Shx0Wik1FO5uU/jUdFG8akr8uSM=,tag:RAwmU6EhL1eMCCGL7sJm8A==,type:bool]
        editable: ENC[AES256_GCM,data:mN2epaY=,iv:/Us3NbHPitYGXma1zm2++oe56QbsozyUfIgXvFDaN2A=,tag:7oB7ebRfpoZvRPDZcON92w==,type:bool]
        basicAuth: ENC[AES256_GCM,data:BE3ggg==,iv:3gQ2PQkv6UOSNUHvrQTW5HkgaKtCoTzn4BZ0Y5zrPvM=,tag:6SBLBsqsPN9TiqqJDc3yww==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:YvA6jNWjiCP/z0u0Lwnj5zrYcUJWOWbTfIuxT3EpfQRuCxWXMRdPMw56Ko7fPWnALa3ppbSxnkHT9vogmySXTQ==,iv:czgxOMVwZU+hNSWydovHvmp6PcCfb3mNzQfcMC+Kioo=,tag:yG7h492m+tgIW3lXDTuxuA==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:9m1ToFpx+x2h6bj1TZuWwl2Z4dRBl8qyhlRkIZWQYE2RaAh0mlChVRNIFHQq6y8KinREygsdUHnVvF0UWXiIUA==,iv:DzCJNjUTwwmVL0dVHhqFuGnHiTIa95aRUl7UTVeguYs=,tag:ew39mBnwjK8eA3h04YCpww==,type:str]
      - name: ENC[AES256_GCM,data:UV0bA/gyCQySosXfnK0l24uJ/akC1/FtXnfoRI/9OA==,iv:XJLdS7Pcq4J9iRY5F9xBDxLkBtz4AjqlCf05+sTOYQ8=,tag:IhQic5TAPCtiKnYDVuWOyg==,type:str]
        type: ENC[AES256_GCM,data:A9hU1Nwy816nsxDfZuuqvTq7JYCyNTSHvaTLex9mEA==,iv:VXGZwYZ3Yu9xoT2nrKaiO+J7CJsdxL3KEJv4ZIbUhU8=,tag:DpBPqsvK9sX3NebDbz94FQ==,type:str]
        isDefault: ENC[AES256_GCM,data:x3uKsa8=,iv:Xrfsw10qrtOUzcLbS+lL8gE/VNnUMwQeNjFAqnYDs6I=,tag:5sen2YGZuRP+rNTS60UMOQ==,type:bool]
        editable: ENC[AES256_GCM,data:qN0uJQ==,iv:zjM6rY8qd4TdsdCWSqPmHjSDdFuAGpD/ubns4ZhKryQ=,tag:ktPL/jN9wM93wxDfIpaLKA==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:7iRAUQ==,iv:kaIGGMyS51T+MUsd1Y8sfQU4KPIYI2C6LvLI3ejOKoM=,tag:Vixt7ZV1BCzgVWW0iCQJMw==,type:bool]
    username: ENC[AES256_GCM,data:yfSipSx76vNUc96GZVZ2yiPt7SCI/owE9AaAEXgeiF7lI5lO1Ur2tb84RJuXaagggoNg7aw/jmY8W71T1FTz0A==,iv:wrEcxICasRCTD0LPnuIon/bQ9XXecYoY+hNMBxfqirU=,tag:8TtH0QSKSHqleK2xiMQO5g==,type:str]
    password: ENC[AES256_GCM,data:VrDYuwH10QJacufh0iLD2lodMHynr6CPIpqGBReMjAJHtDBS2vuDdpkIYJwHe+Gp6QnF7F7j0JEXZZKyhDVgXQ==,iv:3lvhhI5iXXaz2Q3vqiAI8V8wtDdNfVQhCdZYpJsznIs=,tag:NN5tC31w5yGHqUkhTx6iBA==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:Rfg0t6BRCY47/YVqqJOz49Gjtgk+sWJpea5pTqVkzgmiB2tWWt1509J7M7jUnfQ5Dc9w0TaZQq4LRPeU0YDv+w==,iv:akkDYLH+gW9UIvqav1h5PZEJ10GI77JQ23dh5rmyIHM=,tag:xWNlsOQPuD2vkP3eYxAN2g==,type:str]
  password: ENC[AES256_GCM,data:kemjFozFrjNoiwu00pJRvM5x1rzDeU9M8pvV50Bx1z2+qqhyUOPSOlr3G+V7xtL2pAMI6MCxOUt664hGcYGdvA==,iv:Q51Ad4YI1Ub6mmaX9ftNYu9TqFtnP9VJ2sbDzhZAdXU=,tag:IPCaNCzuqBqEoYHOYOMbwQ==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:38Z'
    enc: CiUA4OM7eCW5BAmnZPHhISCTE7UOLOScplkGU0UOmsF7ZcX/sQH1EkkAmy+ekgUKx8YqmpDzmZL5WucHFtOdNVkfo0hjU7gGmQ9Htg5RFFlOfm4v4rqXK59E0866xsSRKrOo+OeqrAZoxHzaF7XFk/Zp
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:11:39Z'
  mac: ENC[AES256_GCM,data:kGORJsjaEciNd0uZ+RVxYHmKGCiPioYZFDE1BlstZ51DtzlY1oEghIIC2QbZ3S5OcokOf2Dc129Dd9KHnwn/Uf/DNeiu70QTgMva4i8/rOCrjnb99aDacpjBkxlG38eTKiRBFmUMFVQ2++dv98vdibCMg8+RIF25y3FvRMldChc=,iv:p3CXxPcNm8aXxem2kQSXk2+mkwKMjFl6DlDrMmpWyDQ=,tag:JnK30YDr6FNukyCCsK4EfA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
