jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:zjQglxanrpZ8XfAPV999vi03TTg=,iv:tf9EkOjiXBgxfG5qVwaMdfwmBV+f1/nAmXdUN/6i4Fw=,tag:yyQjDWdHr8GAqcdPY3yvGA==,type:str]
        client_secret: ENC[AES256_GCM,data:v7lV88SzKlz0nwmfAhIWMT8TeEehxwbMTvq/sQ3vUJ+5slR+eW+cTg==,iv:XV70r4fK0VzX5CKwrJny6NkoAu+hlPjNVJwszkqu+Ls=,tag:jzNfiL6XHznoM5OWRFBqIw==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:sYm5/zonisWZDrMrIISlPLw7GwsAdM8R4uJsZuDpMQd0nBpwIm5x3QDgpZiFFi3UNSa785QYsbJSHvxioXu3dF4MI8ZVQlFXSn1vaIZZFdga+nJV79s=,iv:0Wb/wnvQEDjkHKiDdJNMLOQ1qSd3Bw8lpR45/SN5hAo=,tag:zRWcJqD/caV+KHO4JvJOxg==,type:str]
        stringData: ENC[AES256_GCM,data:fEVqUBN97FmQS3CW4q42sKzEVdQpxuAKc6pDVwWNWOnjuEginvRoFiDfxaul0CzNsSTSHBIY+G7IiyPETRHcLNFMCaxjd2Bi7mCvWyfTriB3Syu1pBiPxD4/q1mQSg5bLixKCqFxc9xwT/wNJy+8qTrgbarqKLyvUQelwwUz5ZAGuLLDpnCIjaK1p8bv9GXKLkPGNZNM/IRql6VbsQ0oEmNlA6J12MqcoqF5syV+v3bPGQ4sDUqMz7Z6c/z6fL0GvDBnxotW16wJx8x7iQt1V6i7nh7D9Ha0HxAyDIfEZa6SEEqdKIhIuoSC75+0w+lm8KXv+645DQtkApF1XYR1qn403vsA/2MttA7XEOI00KK5jhdbnowDO4lNsUdDD6xEzVb4uUDc0IP9tAJd27LDnDoWk9zbb86uvwtFcgYk3Aq6wTJ5ct7bNJMWpSl+Ek3OUF2GTTVmEihJvMM5XOW5irasvGTR814yN7dVQZLGaLgBBAf0zWztjNBPiwynI1zroW5OqM4utuwi9aIUrk65SUzAH9mfb4npKNKZLTgaj5AUiBhB2YNqgnDOqSfc7zXIJZjZRGd5P1a3E8E70uUrDlqRgNcMlQ7THttoenjxAvOtN/nOJ8QcKGN7zoQYCYF4ewenupkVLEIBUl44Uw==,iv:agJYLbxwobBBZXQo1e+wfwl5JMJekQmrY8eYLzediEQ=,tag:UR4bVJUu7EgD29m5OLfScw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:20:23Z'
    enc: CiUA4OM7eIZwLdcRIaUDUaVp6EvTVMtzFVygQ9ZQXVXZCmesUHWJEkkAmy+ekrvWVqYidaqdsH1yFA+9gZ7mNDgl8icvkXUiB4Vm/f9hlcnEbpRJzIctl9wJAUg6nKuYFKqCaabB8qAgS5icrZPMUIhq
  lastmodified: '2026-07-29T19:20:23Z'
  mac: ENC[AES256_GCM,data:wPXgWooj/5K4Hnr5Xky/F7T6YGHz3yWYKf0pOFGF/J9w6GVSdnJoJyE2gyiBHSN/4azYZJqMUWOLHsVOrCYggQEQQCL4W1Zo51HJ/546j65L3sKFhb2GjmvbXMTzBUdgwt7rFmk2+hF87yVzEmsphqSu07TlcyVyfci2hcwBaWw=,iv:LLxdgtA67evbfHmD5ySA0PbrtCvue0ta/4vwmhLGAm0=,tag:2jrpmtxU4NCAvEhDaybKYQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
