jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:uPKdVfcQutYQYWEr+Wn26YxEJW0/CA8oDWCrW3+VRDRE7aTqEsYMLLSocJGOxe4GG4Op,iv:t9iFeZxirMf934UbRZEoviBiH8cyQhVFmpOXg3PPzgY=,tag:dldEdgk/YWj4tUAAztqQAw==,type:str]
        client_secret: ENC[AES256_GCM,data:4HCo9PtHE3LVvFgkHKNRTRkxHypV/5mFhOwgfpJqDZXFjKiUOes8rIU2HAi4bwHdEZVttGxiUmEkb1G+tYRWBJpg2GU/s0IMVtvimlqvLGdiiwwCQZ4=,iv:z/FHnzR2VfLv94kYT7JbVmz0g/z2wN3chs8W/hFiZgY=,tag:wIvR2B42eQ7x8VrRnRHRVA==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:P80cQdW89+aNbGbr8ueLafCBpg8s/dmFI8k6p2ADeg30n3sJl/66LaUm97f7kNiZ6zzoSCQeKHACO1de+kKdiA9tQtNUsOV+Vf9YCIVhkGxvuT+lRjc=,iv:CWs0J5zmq4ehn1IFsLKrQK4juHl4H/20zJ8g9jfv5xU=,tag:VsrltdKDRWY4iI9iSNJZpg==,type:str]
        stringData: ENC[AES256_GCM,data:COOCGYa0PJm38yi6UJt8wYYWWEU90w7rJr1tY5YV+balDMe+8Vpy5LctgO+t1reSmxfVm7bWtY5aZ3W6o3E0HBefHDEEkIR+Y4+RNo0tz2c/iM7I5GtY+guNaBme5cslVqX8ac2nHsj/WUcAihdXboPyBcI0FiG0T52t0E1n9ntBIV2EedTYU3yszx1dmt+xPgr9LlZ59PnHeHt3OLXVjDGV0joL26B3NITDAkMA/cSP/Dug3T7M1vDJvPRznrxdcggj0wlG3E4MIBYZYdJpK4fFPbVPy5+SpXlOe87KQmebpuInBJrqjVgWCdxXgTceewjyqSqA0i8dSHHOKukQ+7zGtSglW8fCogd0tLNBeAinxnstfLpGfsnYZsbF5NO+16b9amnNbEZdGvzFxx4z9dE1+Epdd9pPwZ6rAJ6+i0gzfIWSOFBAiHa8wSirXMd4H6SaPEsXNf+nqRAWEpOX2nzRnuUw7UqNoq2k/FIQXo1MfvyBcCgwVVnvUPumfBtxT3gSmCwv7QT663eJ7Rxe/8HRyhFrpkgKPEZQ2ULe9L05O0+mZtKxqJK/Ssy3UvV8IMKIXZUhu3IRxn4B9BMWU6+z8foEmbYewrdzop/AMsbTztX+27iD4A2inb/dcnqxh2SKa0faLCBNlylmCw==,iv:/1Tn1O9Z5dwTFyyfJIMB7bE9/J5uzdu24QiXOqn4X7E=,tag:J+PrjrbAL1/16I5XYo4wkg==,type:str]
jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:Y3W+keRUabLACtLZgi1YxufW2sH/WwcOdbv2my+fWk92Ae5J28QEbhojmpVAJVQfnSrWHjNf,iv:9g6t9RSSHWszt8ZU247HiHn7eqDlU08EN8A/9K31ib8=,tag:7xLtMlNdzVLtp0gdwxC5cg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:16:39Z'
    enc: CiUA4OM7eIloKfz7svo4i5k+PNBUUn9l61mMuk3vUbp2Vov1f98HEkkAmy+ekg3Hrg5p+iiuuvlvVptS3m4y+0onvBqkQcC1vbwuEVkprZToRxykiCCmKJhLIkJPkgdKb7RE65RntGUAixkRYsGfqCR7
  lastmodified: '2026-07-29T19:16:40Z'
  mac: ENC[AES256_GCM,data:fdHG3EvOk3dhoSj63dAVBPZNs+xMURZHRAIAcZ9kvCiEOVM5FGL9UAWsPs8r+Mf/kAYLZ3P5kl1zc/NatsdJPH/ZvWrt30CEk79CMSC7N/I8DjVSNfDQ1FWd3VFTiUmwM58gpUOMe5pZ4YEFeWgF7tUFl23NGh5QtaqoaXnnv0c=,iv:M66qJ//NXs0J1tLLnh2ebS6RJ6KYmFs20jhvTuO7kIU=,tag:OpXuJIFn6cU7E625r6z9ng==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
