grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:PA==,iv:e01sGsEEtPuT8i/u0D8ee8UFj1tx6cjFxXHBj2i5RsM=,tag:a6d65DDPjIYcgVfrDHCYLw==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:0lBy3tHqPFZtlw==,iv:7IokgZecjQa3VWnki3Rn7OcGFKMh/W5yMEmWBqvEH7M=,tag:CtDV60ekNe5khRWafjjZ0A==,type:str]
        orgId: ENC[AES256_GCM,data:Rg==,iv:Rww23eXCzAHQPxAcJRkl8WooW3lYPE55o1UsWrShXUY=,tag:D2SQgjKzKmrgJyFvuJIz6w==,type:int]
        type: ENC[AES256_GCM,data:irAAMV91aWygIg==,iv:OXWiZgCKA2HqZrXPChz2V7nWPGONe3pnl6RHGfSxQmU=,tag:KJCreR+yf5o3x44yCdI7oA==,type:str]
        url: ENC[AES256_GCM,data:PlF9FV5nqyCivrOmWm9tBSxGzZT6HkowhmIKccSzyQs=,iv:A4S4XGHoOcvvvHmGQnhbOYJx4N7iqYzd+BBjqwXHlYE=,tag:pPXJmxlJWHigN4KmRjptQg==,type:str]
        access: ENC[AES256_GCM,data:uwynzt8=,iv:SEQpBQoav2Oj0DQx75OJa1Vt0CQQQzkS9nkOe0QLmmQ=,tag:PhwG1jh/LSZNDOL2ztfwow==,type:str]
        isDefault: ENC[AES256_GCM,data:QScQuLw=,iv:k7Dh71awJ+hDW5W6Wf9NxxDxSAEaabv8Gn0pZdL8qpE=,tag:Tyvnv/peypeVrhGIgyK8bw==,type:bool]
        editable: ENC[AES256_GCM,data:UxoZ+AM=,iv:rA09/E0oJaqTDqdIJveoZZAoUm4F1fIqYPJXlaBwYis=,tag:qPWzrQBmHG7k4YRzRJQuTQ==,type:bool]
        basicAuth: ENC[AES256_GCM,data:rOWc0w==,iv:SZ6TKBV1rRuFJBPKPyzn4b74XXvzYDJ1N67zaxmGIJE=,tag:Lmx30MQshS6lCpFEpOg1Dw==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:vkfnOkQHbjdl5+grsPGI0aSMi1nGFqqKl743bKx5IVAZR3CD5E6y/MDPGixmq7iYj+csMPRS2YGK0a5xyGMMNA==,iv:2a5atjDmxvYGBjb843SRWwgqghZyVK/2SO2RZeoKWl8=,tag:XVkfRIG38IPnHtk+5NicUQ==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:lMd1bz0LUGFmw3AXvWb8fb1ijL1eXPB1NarxcKdv2sI6U81XlK7VsuT4+1+0Hc46Ry9LQlIRXei8ZftxTsUUZQ==,iv:gTL8SpgNZCgIsgiPLvFrKxXjT+CxMDI1FQYYQOdBjcQ=,tag:G+U/A6VxoGb4ZJDiJibV/A==,type:str]
      - name: ENC[AES256_GCM,data:GUGryw93QeJDEzIqr58+byhPVDsQn8kuz1TAgQmscg==,iv:HFiwXanMA1LloBHHYl93Kkv78RTR8xDVqIFjMQRztvE=,tag:KZqOeiRw2DaPDu7lAhdVdw==,type:str]
        type: ENC[AES256_GCM,data:owj/Lku2ha1gJP4v4vNvw3qOImUVY9adD49/kjGzMw==,iv:J8N50vxYJqT/OQovjTwCgmfMsfymbi8jw+xQMvD1YKo=,tag:vnQkE2gttwG614gULNSomA==,type:str]
        isDefault: ENC[AES256_GCM,data:AGiOlMM=,iv:wvrF7HPZuBCQrMjZM1XY5AwfIOAtCYi2lgbKCZuxFvo=,tag:+Qtxfob3ST8YOBD+MvaEQg==,type:bool]
        editable: ENC[AES256_GCM,data:C1Hs4A==,iv:a58z1tPLvcjdRIbIT4gwkRo8OEkcAAkhxqo1jz8fYd0=,tag:INLZOfd2xdXTD7qjbsoofA==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:mnF5qyiiESzhEtIG4A==,iv:7VDr3Vb+11GTrmpltgbNGWHp0J/dc+HD541LRNFRAUE=,tag:FzBd0rswIpfZaxxGWIfi7A==,type:str]
      value: ENC[AES256_GCM,data:lZVhfCu02DM8/tMnyRRpM0ukdOm8KFBONAaQ7H+gPJJhwmbfthPswJxMdn77HsD0GIaIu052zM0BKeaM9HtmwLSjTTmSxOS7ItW8Y0Li/npFnnjEnUp11UC1rZNml4KMLM1isq0mZRRrlWwEg50QY6V0w5G1XrTZ9BcsgP/eIy15IJGqGVc4ENGF+GletozDS05X9p5q4A0ar8jwk2azCFr8lUBvPQwcbfY4/idZOFyhBQ==,iv:EHxMWZl8P4jYS7JkYWzmu87efjW6gTCYkcZLm9jU3ys=,tag:/vDb09wlKEYkAyIaaaGDVw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:bQ/2hPNaXhcXV6r4AY5+c7fotR9Wot9zFb+SBlH1vIhUgEYs7TK89JweTMOrHza17iMuLWB32gK5twRAVjteLQ==,iv:x7ssPAO1dI0K0wf8D4L1GsjZA0bvMtegBSuiCHN/09o=,tag:sJXvltXMDBZ6uRBGcDtXjQ==,type:str]
        password: ENC[AES256_GCM,data:lFmgzUXJu8mpznLrMAq2r0LvMYkp3dBs19NQ+DI+yln/cMoHJJk/8+Q5pnTIC6Qn8qpQMwo+KuFX/MdcWVfdmA==,iv:39VvDXyYknw8G5rrLoL5zs7fCuax1Ly9WswVxF0kbvU=,tag:S28gYQCbmVtRNnJVlPux7w==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        toshiphuuVah0rahMae5bahD6Pee0teiPh1ohlie8elool6shookaishahShohCi: ENC[AES256_GCM,data:RhhNRwZ7QRgW/ogXnupM3V8I9ahAkh7cylmiiV/oHLJSFlAMrtyqqBVJgJuwMYveFBMrM8m+nVJPBq0A,iv:pC1iKlgqcvKGT0a5cK7+rVyGGOH8tpj6RdPW5JkwQ+s=,tag:m6RLYy9eKC+cgsvyFuPjYA==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:6zFHRw==,iv:1zJwLr9yz+h5XbJU58HWrm8PnhF+MzYe4o4S2cWmDuA=,tag:e54Y0RK0xjFJBCylW37Ocg==,type:bool]
    username: ENC[AES256_GCM,data:HNuhQXG6pKlq/+hiWLcXD+9h6NYSevp6eS9bztX7b8reS/1AoqDY5kThWJYCK/bs2YNuWB+VJ2/UFvtAbhL7ig==,iv:KGw90pQ3jPYmB/jLLJ6PMb0h6Qum3ezCpmanpxbuN90=,tag:LlQPs7AC+EsKhKI5L8G6QQ==,type:str]
    password: ENC[AES256_GCM,data:B9GjzOMA80B5kxirc+67ZsKkCkRT/RJ3LxmumPCQGOgvCppw/XEcFUz16pX7DfiGvzKN1AZrQsA1Ekbw3QpFQg==,iv:582dRR0LiJsGPHo35llB/BM7w3i0sLSqm9Mkm5WNalA=,tag:R30LbeuqFV4xOeuvOBmJnQ==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:x038dB0lIn1gHdQqOknpXbvvjyHKug69QevCt3RAA6SNWg5sQ3i7P5K/RszP7XNmm/n9siworYJAqz1qjckPAA==,iv:wxhhlmcsa/HvOCTD5JV9ft+FR5lSYADtcN+tAom7yjQ=,tag:5Dydyy5geJtfxWZI568TPA==,type:str]
  password: ENC[AES256_GCM,data:6IZuB8yhO4JEsbHbtFyrS2Zhzfgfkz4gJSYzDuU8Q5TZy8xUWhlj2MPXpyWI1o/nsMJKrwrgj8Iq2q35vXybjw==,iv:0vFeFgenKYgaPncs1Dy1JfnhpXxPQDwwJbjfURiyTAs=,tag:xyDCU87/KzKy3ExFxhsjuA==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:09Z'
    enc: CiUA4OM7eKgXXvLmHlk/hwxBSdEG67b6o6m1h3yTj1OEvBwYHtnuEkkAmy+eklxDOVp0jmuiymxvaVj4K4XkfUz1ehtfg0QRr3fB+nMrxT99r2EGYgGrFMZWztiy0hazOuUgLRfhgzMbD1ARlepuQIk5
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:11:09Z'
  mac: ENC[AES256_GCM,data:D/cGvhYFdp1S+VFCZ8gddTRYWFNQUWgzntWI4pdNSzlsML/gnersp0owYtdSTOuhdWH454FWf/wvGUp/FPuHCywl6wrSPHrL4qCoazxcoGLHUgjILjt9ypc5gxOUK6UK5gqxdU2F+F7CTfBQlLJ6Ckma4EotBVBJtiWcfy6qgq0=,iv:ZAKXMf/j8XOQQrptWPfXLgjOLSXVgB4HKsnDiWJ8zcQ=,tag:VDYCbRU9mA6T7UnLpoZauw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
