prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:mnF5qyiiESzhEtIG4A==,iv:7VDr3Vb+11GTrmpltgbNGWHp0J/dc+HD541LRNFRAUE=,tag:FzBd0rswIpfZaxxGWIfi7A==,type:str]
      value: ENC[AES256_GCM,data:lZVhfCu02DM8/tMnyRRpM0ukdOm8KFBONAaQ7H+gPJJhwmbfthPswJxMdn77HsD0GIaIu052zM0BKeaM9HtmwLSjTTmSxOS7ItW8Y0Li/npFnnjEnUp11UC1rZNml4KMLM1isq0mZRRrlWwEg50QY6V0w5G1XrTZ9BcsgP/eIy15IJGqGVc4ENGF+GletozDS05X9p5q4A0ar8jwk2azCFr8lUBvPQwcbfY4/idZOFyhBQ==,iv:EHxMWZl8P4jYS7JkYWzmu87efjW6gTCYkcZLm9jU3ys=,tag:/vDb09wlKEYkAyIaaaGDVw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        toshiphuuVah0rahMae5bahD6Pee0teiPh1ohlie8elool6shookaishahShohCi: ENC[AES256_GCM,data:RhhNRwZ7QRgW/ogXnupM3V8I9ahAkh7cylmiiV/oHLJSFlAMrtyqqBVJgJuwMYveFBMrM8m+nVJPBq0A,iv:pC1iKlgqcvKGT0a5cK7+rVyGGOH8tpj6RdPW5JkwQ+s=,tag:m6RLYy9eKC+cgsvyFuPjYA==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:6zFHRw==,iv:1zJwLr9yz+h5XbJU58HWrm8PnhF+MzYe4o4S2cWmDuA=,tag:e54Y0RK0xjFJBCylW37Ocg==,type:bool]
    username: ENC[AES256_GCM,data:HNuhQXG6pKlq/+hiWLcXD+9h6NYSevp6eS9bztX7b8reS/1AoqDY5kThWJYCK/bs2YNuWB+VJ2/UFvtAbhL7ig==,iv:KGw90pQ3jPYmB/jLLJ6PMb0h6Qum3ezCpmanpxbuN90=,tag:LlQPs7AC+EsKhKI5L8G6QQ==,type:str]
    password: ENC[AES256_GCM,data:B9GjzOMA80B5kxirc+67ZsKkCkRT/RJ3LxmumPCQGOgvCppw/XEcFUz16pX7DfiGvzKN1AZrQsA1Ekbw3QpFQg==,iv:582dRR0LiJsGPHo35llB/BM7w3i0sLSqm9Mkm5WNalA=,tag:R30LbeuqFV4xOeuvOBmJnQ==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:x038dB0lIn1gHdQqOknpXbvvjyHKug69QevCt3RAA6SNWg5sQ3i7P5K/RszP7XNmm/n9siworYJAqz1qjckPAA==,iv:wxhhlmcsa/HvOCTD5JV9ft+FR5lSYADtcN+tAom7yjQ=,tag:5Dydyy5geJtfxWZI568TPA==,type:str]
  password: ENC[AES256_GCM,data:6IZuB8yhO4JEsbHbtFyrS2Zhzfgfkz4gJSYzDuU8Q5TZy8xUWhlj2MPXpyWI1o/nsMJKrwrgj8Iq2q35vXybjw==,iv:0vFeFgenKYgaPncs1Dy1JfnhpXxPQDwwJbjfURiyTAs=,tag:xyDCU87/KzKy3ExFxhsjuA==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:09Z'
    enc: CiUA4OM7eKgXXvLmHlk/hwxBSdEG67b6o6m1h3yTj1OEvBwYHtnuEkkAmy+eklxDOVp0jmuiymxvaVj4K4XkfUz1ehtfg0QRr3fB+nMrxT99r2EGYgGrFMZWztiy0hazOuUgLRfhgzMbD1ARlepuQIk5
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T13:01:14Z'
  mac: ENC[AES256_GCM,data:Yrgpq7E7IbzdWbq/+DPs12mUuceKv1potYKioYAVnZm6UG6CcwNhrRXqK68YBPPT0FaWj2p0ur4GFTZ3ePsJ5wZpF6WfuzGoNRlSsBHGahhTvlAkPr5aknof75F4L06XFKgXLdUkkCzqrWhDihcJM9Y35ms+3GrxVMdVUaj7OsU=,iv:nEd8Z9oXkSliB4Incq1ZqhMXsTiKa5Q8CxpaVrroSms=,tag:pvatk326vnpzPWkANRrAOg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
