jupyterhub:
  scheduling:
    userPlaceholder:
      # Keep at least half of a spare node around
      replicas: 0
      resources:
        requests:
          memory: 16Gi
  custom:
    2i2c:
      add_staff_user_ids_to_admin_users: true
      add_staff_user_ids_of_type: google
    homepage:
      templateVars:
        org:
          name: 2i2c Staging
          url: https://2i2c.org
          logo_url: https://2i2c.org/media/logo.png
        designed_by:
          name: 2i2c
          url: https://2i2c.org
        operated_by:
          name: 2i2c
          url: https://2i2c.org
        funded_by:
          name: 2i2c
          url: https://2i2c.org
  hub:
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        allowed_idps:
          http://google.com/accounts/o8/id:
            default: true
            username_derivation:
              username_claim: email
jupyterhub-home-nfs:
  gke:
    volumeId: projects/two-eye-two-see/zones/us-central1-b/disks/hub-nfs-homedirs-staging
  quotaEnforcer:
    config:
      QuotaManager:
        hard_quota: 5 # in GiB
userServiceAccount:
  annotations: {}
