kind: ConfigMap
apiVersion: v1
metadata:
  name: usage-quotas-config
  labels:
    app: jupyterhub
data:
  jupyterhub_usage_quotas_config.py: |
    import os
    c.UsageQuotaManager.metrics_exporter_token = os.environ.get('JUPYTERHUB_USAGE_QUOTAS_METRICS_TOKEN')
    {{- range $name, $value := .Values.jupyterhub.hub.config.UsageViewer }}
    {{- if ne $value nil }}
    c.UsageViewer.{{ $name }} = {{ include "python.literal" $value }}
    {{- end }}
    {{- end }}