prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:TBmlPuS61VkcygG7wA==,iv:3BJvxX6C3wxgmyadzgSkKicWwTB31Fy1LWwQsHAgcM8=,tag:DYQ3f7qW/igbl4qlchTgsQ==,type:str]
      value: ENC[AES256_GCM,data:Fby59nfIS7LoZogYXgk9dIp3bwtt8nO0a83++fnmpEUbVUh2HDn73Duh8ybc2LhY+bnvX/2Ihn9wjoUIAY7W/lVZGZFR1YKFGtJ5oSQGk5aYb1pl5q3a9/K8cvh+jFf0A4RY4lBhCOzex5i+/ILusXO79YLwG84U52XLbslyB6QijUYgGZmCp/aVtL4rbX5OEbYRPo1V/HHEnzy+pvxZlaOT226F84V1sm3aRdo3/GvWsw==,iv:mr8fylsbFEjiCnHOYUdYEyOCar8V5wkUhojvcUlk2PY=,tag:kQSQ8MOvnPcvNL9QNelZbw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        fXVdxJmr0ZKsp6urCavA8lDFtB4fPjxhO9V1frHwenDLtMYmaIdY49ahNk9jLPiI: ENC[AES256_GCM,data:NSpd2cR1El5Pr7QC6P6CbsDc3PexWEoqs+JS8K0lhMt5g+1SHialEOPyKhjLhRuBfY+UO3qpepFq7vdS,iv:hwTCKI+p8DPVkkasshNFrNPgtiDmk3wIjevmk8LjpqM=,tag:L6jNH9ApTNNldZpqR9iWKQ==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:B6ZBow==,iv:Cnx8ihZT6wgz+bZvsS+WIGxlTEeINd7kMT6qPenH5Vo=,tag:ECF3cYhNUH7dPqvmc/j72g==,type:bool]
    username: ENC[AES256_GCM,data:XLNVN2U1J73zAI0YkKVisE24dpNCj5TwLqYo+SW2fN+BkPNmDbZv6GfwS5RWFwlDvZ+wEsQGOm4XasjoNOjcOw==,iv:2G7zKDBx7VMnWjNPP5+L1jLTS/stdN6i7YbGUT1TXu8=,tag:qzJVDEXZoDbL9sDYlxQmQw==,type:str]
    password: ENC[AES256_GCM,data:cqTeiija/QhR59pIIg6Ktcayw7uoXCFjJyPxosn/ktESWkS6BGPBx56lJEODNws6kFXy5kFfSZX8xDU6KUsdSw==,iv:xbLyOSsQ90S5ErmtiT1hWb9ZT1WK4baBbPtgpy3aR4E=,tag:rioJ+M4v1WiGuJBhYHaVdQ==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:atoOx5CifVgpvdOZCXkwc8OoseXVTOWEODs5XHctgc5DLvpvxLPTAKUtjEMCGHHINTL/vnGxqv3RX3oH3LaZCg==,iv:2JxE9jmeqRmUQyyKgKDLAGCTQ/N69qc+WBq/QWqIKe4=,tag:+0oKdgu57ygM9tPRRSV0eA==,type:str]
  password: ENC[AES256_GCM,data:p+P4UslcQ7S9C8K29Xr2TX/fZlGMb7uBgckW5E3h/ce9NpMFZynUhzMXAvVvd5ISP9h9cV2LTrk4I3oFsxkKWA==,iv:lcX3YSSKCfxq0V7jYyU3lxix7A285OrIiydC+puo/Mg=,tag:z/ICaL+TxqBFk66JhUtdXA==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:21:50Z'
    enc: CiUA4OM7eA+bcDVzA/A6oe21s95fSo00dUveuDD8gHWLKWlmdxLNEkkAmy+eklKcu9rClqbd0r47LLpiPyQKMpQVjoAI3nj2W3x22P5ggDbJtD++fkaT/xLWRmwuvKCceBDuRDGBCRC6pp0qB2tWF6cs
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:21:51Z'
  mac: ENC[AES256_GCM,data:oPSCgRLeM7aDjYgwB0L5QKmfVWaOa9n+hAyxpEBTwpxIhQefrd3ToChafpK5uuO2vKA3pjvMwzqoy2LHdddsPxVqRj/mdA+EciwsPws+CLWiu9bsROA4QNE9FNtEL6DJ0LMDzVvKrEedCGSKqeDcjLt2YVuyj9CrU9S8KOvOURk=,iv:eVoef0ydqxRbLRPHqVimcH/cZsTRFYnR/z/ykDKp3ak=,tag:XNMWB+2GewbdZ+F9NuIJfg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
