grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:gw==,iv:ASeGaO7XsY8U15pJfXH/IEGH/g4p6P4Pnq2RvoPxZBU=,tag:UmOj73OScr2rjyFFiD34KQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:0neFbaRaUlvBrQ==,iv:lLji+pecshPwUTz+a+9U+VLW5aSty9cch4w8Qheuv10=,tag:lNdO3JHEYAqwWUzorRMejg==,type:str]
        orgId: ENC[AES256_GCM,data:sg==,iv:r37U5adwUmNCfqHyRELazP0/P/s3rflaDURfGvps1WA=,tag:ILdQKFqNyDi6WKmmOarQcw==,type:int]
        type: ENC[AES256_GCM,data:d98K5P3F1peaDw==,iv:xw7BlMfbq2J/AJOEflCDC7ucOyc5jjolcFEi5ewucH4=,tag:IS2DRTzlSHKNVaHLT5ht+Q==,type:str]
        url: ENC[AES256_GCM,data:zizGRxIUMyLyEPoRxvgpRNlK04k0WBT1HnZCocTM6gA=,iv:xyjvv5jOaZXMO/slLDEGvEcgrTYSu4CIJG9UA1lnQ0E=,tag:xqBt6GJurZORIpz8kTtToA==,type:str]
        access: ENC[AES256_GCM,data:s1ZX6a4=,iv:A+6tVlfmSDdwVLghUm1I5igkrOSGwIFK93zmRAZqXns=,tag:4dPHyishFnjGE5VelRo2gA==,type:str]
        isDefault: ENC[AES256_GCM,data:rlE/Mio=,iv:f/IqYAYzVZBv6gmO63teEkmSWCmHEYQHY/EI12emVdY=,tag:72m8u+dug3gjf7V+6Q6PDA==,type:bool]
        editable: ENC[AES256_GCM,data:a7bmLxk=,iv:/2BTI1kL3ujPV1off4xUm5Hp1ggvWx0VkzwULpjvnO8=,tag:x8tFSvkCCluEhjybS5d1+Q==,type:bool]
        basicAuth: ENC[AES256_GCM,data:QrNtXg==,iv:EwhQQXv3ODA4oUqM8Z/i87hjERT6hyyKmTXg7z0IPeI=,tag:yCve9XNHj0H2BXw83/k0lA==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:8UERIHt//ADNTcW1AdfxTKCRN5QJUD+l45Yesni1UrBDucUPaqvVG7aWGetBiFYhw+hQ3Tppd4admoSnOa5HVQ==,iv:0RleE63PuM/YFjIF2ePslg59Ka3ye+fpnjjOvXS+kHQ=,tag:awreImG2vQISzUjPhQOfvQ==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:IzuzlEXuyIaK/HHF5ubV6Mf5JwZzYPzrp2jz1BzBrVTOsxAy6AeLMvK2yy1rhp6uHhMNjEMdw7EF/CNcJfpo8A==,iv:6uWmfawdAaSc6cVA3I+8DE4YJ9wYZ8WZyTrs0FcA2Ik=,tag:7wzLyI3D2Y4F37vNQ9etfA==,type:str]
      - name: ENC[AES256_GCM,data:AN9Cz4szOIpVfvYIqYF4+Y5ZhgfuybLZfe3RweSPFw==,iv:wJTUk3q+Ny88YlK0EO+FmihKPdWaO7+k248eGUc/jYE=,tag:uWchoyr9TY47lXc5KD0ZIw==,type:str]
        type: ENC[AES256_GCM,data:edfyXumTLtj+NSVZtKf43BAqrZDW6WTO3R97d6etKA==,iv:U3SMwI8fmruqEPR+/P3wJQxvRHzNiLxpyjariiOsCys=,tag:AO+zCsq5cC5BHJSGtiiFbw==,type:str]
        isDefault: ENC[AES256_GCM,data:4puVEvQ=,iv:2imBP12Yt124XxCN5vFq4+kN8ApegqaxfiUk1Vu8wDQ=,tag:zpoaOMPcYWC9DkVSxkYkQw==,type:bool]
        editable: ENC[AES256_GCM,data:ORylCA==,iv:gi74desJ/b4WyjF6oUnUzQIdVfJlcBXq1DUgdMbnBc4=,tag:dvV164RDhoODHzNhoSl+Sw==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data://+jrjRCjQrn61NlTA==,iv:dbf+/Nx99XlNLrYt6/edqaFTjOukXMQLH0i4DvT3TDc=,tag:GbS3paLmH+nWzsxlTUjObg==,type:str]
      value: ENC[AES256_GCM,data:be3C7oI60ZTA0WElKmVZCp26h2MUwk1b2520Ffnj3nV+xOq5bB1jWwy25Q2NBdyLByqbQB3tGhaHG0XrMunpT9fuHP4CFyIvVocCBVCLWh/CkYNWf0pAVyi4QAhVeUkwW/u/8tlIvV7JPiqpsJvg6Ayov1B4jEkPx2zpIngVAMX41ucaLUBUrDzYV4dbYIe7QT2dRTR6z8a+WXKp0UoVolrK9inpIfqht464TkOrXI5ZIw==,iv:hrhXmuz7wYmatGZRodNQJNhhyfpd/c7YI6rjF/jb89I=,tag:ordngMH2rbrxu1Lnyhe1JQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:F1u99Z7HJqthuH4ONYzkgevU+wQokphQEk8GEvFs4OXq2fOo1yp3lWNPrCmDDlDNR0aEJpWMUnUf1PxFEXb65g==,iv:ryQwRmkbyOKlHi6EireOnCABZxawaCbVF9N1w78RtYE=,tag:rBvbXLkIwWILhQQTf3oeQw==,type:str]
        password: ENC[AES256_GCM,data:zK1M4RxvCLpS+rEExTgFwfcN7RTfbKGTxBiewF9MAiUr9B8CvbrcQifCDo1pSYZ8L4XfhqsDekTsHgTsvFcgvg==,iv:ZFYJ1fzgdYrjPhpBpDBjB6Jol14PJjkXbGwq9HoxEMU=,tag:Nr98TNnPEUJXLRoxeOVF5w==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        fXVdxJmr0ZKsp6urCavA8lDFtB4fPjxhO9V1frHwenDLtMYmaIdY49ahNk9jLPiI: ENC[AES256_GCM,data:0JaneerM97OutNT/CVQIEhwwRGt8RDq6tZbmQy1W1r7b297SuDxpy0sY2WD1ONlOhE6h43muC+awmEee,iv:7mHAfweHC6Hw6ITO0M9QcDWVUZSK6KBF+JBD6GeInzY=,tag:s/Fia5a/keHEsZsQ3Z2VCw==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:434UvA==,iv:P6aRlu6NRWQq4bxYtaljLArzpPBgz1VbbYbDhedfmPo=,tag:X3nKxltx3tMIzCIB2fwHkQ==,type:bool]
    username: ENC[AES256_GCM,data:nuFAAooV9Mq/8X7ecA+1cGj3nGyewordQLGHDOnKYORd9Xa4YdR78R1YYG/qUEZoYyHEdPM2flkNgi/ukrPwfQ==,iv:6JwnxXIY1ZeN3E1Av2nRpkpqG0HMFNBw4EotP6T0xfM=,tag:HaBya6Af7n7oQmWICTt5og==,type:str]
    password: ENC[AES256_GCM,data:AeXZ/L9g0ueN/wmvooPi7QNQxkg9WCDyQuil7k/6NVdMUUGCP1Jf/ne+v0oDqncdlon1z6Ns1DKvRle6Zk7hgQ==,iv:XXeeRy6GDblqBux0tfmAVpZUiCxhFMj6bdpW+PLm0h0=,tag:ii8HK05Cw7rHHPiWdkInpg==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:ZOq+ffEZRVHAfSkSD2YvfDAr+R6TwVJR3JcyRu3QnERAgmnb35+NHamwAahy5wB1u/+qouQq3mqlkSD1u7n8OQ==,iv:4tgFPBTRCGUL8UKW85JFSuu0MnyMT6Zql0MmgKatCHw=,tag:mqreJQCAZfv5MPlu12a8sg==,type:str]
  password: ENC[AES256_GCM,data:mCHME5bsF/vi0znMerqD0XBN+siYzIJ2aMMIWWVldtmehaZbarLkUErFdhaUThJeCaeW7dKmURnnuLFul7wKag==,iv:rjtyKZxCBqmgoUOtq9NftTuGHKgLzdM4xdaBnQ4rQ7U=,tag:Hzg9qqgF+6uPEQpoozeA1A==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:11Z'
    enc: CiUA4OM7eHKU2R5Z0OEouBSWnAL4tRVEe/jScaoycjcNA8ibJX4mEkkAmy+ekhsNZUD6cBRDLJ99mYlWjR/lIdr5iKCBJ+e4dHzNI2bn/2oP7GSYPoF6D69PRtl5MkOOTmvLTpdPP8sFBhSGWcwir1Et
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:11:12Z'
  mac: ENC[AES256_GCM,data:uhTBsMhDcNAFjB5FsMlIaDUsDFsKNOiJAVf27C+lIBP8ZmWRRgwexlo1x0jHvmFMLK2Dxg7BYke/s8ZMyjsJrrsqxh0yCv4C35NYUyjagG0Au6Qvj44iDzBwEmoi+o4AtuFrvZxroPmSgjYlXSZuHNhYa8NzXbeNcJM7WLuXbTc=,iv:r/nNFl97ryk1SgLcoGpwqJTFuXOqozSh3OmSdDSUG88=,tag:ygIfFqBgfptgh+Fk2xEc5A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
