jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:jLElSYuOETeIC7S/mzYT9QyG/TQ=,iv:kteBNKHReA6Imn8IpmIe6Us7C4xk1daUK+/XvpRXAG0=,tag:gQBKe8+DzrnF1OVwnGI/Dg==,type:str]
        client_secret: ENC[AES256_GCM,data:yzUUwe7Jk5mQRCwDj1/yuE2/ERGm9Gp3Vq7Co7YXZ99Vd3XzjskG3w==,iv:ffQnRj+HgdJiebSuWy/SQvR/UGDNsryMX0Pw/Krx7Hk=,tag:8F8u00Bg7VTeTHPxts7PRQ==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:glampq8hu9XQCrM0bM3AL3PVGvhC1UuNYFb288THl+KUBWOleJtudyxdqPz2VSMeH6Q0xE4L1Z9rHoVz/zvqt+yddlL3mRLmsUvTaDaRkCDBonGsyes=,iv:hi/DkGXf12uTKgR3JQZQDN3fkAhZQ7hXpUuTmk0WufA=,tag:RIRExVMGWm/Ze/vOfw51Ig==,type:str]
        stringData: ENC[AES256_GCM,data:TsQSRVkgpTOeYDTFXaXjix4ALT+CJ2NsQ2BiFOdbRa7BildBmbhCxOaZhD5DdWtcPCqe88CybTvRHb4rNY6PgkREXZ2vhub6IuZuC1zWcGpMXXYwN/FDxi0r2MkJd4va/HRmJHhszhjufIpGE3yyLOWI6bAV/vNbaNcfcaFoshpf3lnsGY5sUW1P96uDv8OX5U6b47IqYpOC8qDYgVzIKEeI4hxldJnK8Dp+CzMzBjJsxOzR84qkeraGfdnl1NAl51DJAKltF/GSsJsgcBrJ0fIYnc+UgFuOF87HNzqb6tVmgbdH8bdxN/Q+x4Pn2LHJvd2JQzSkNeVw6gTxjHqvENBcjYw14AL+mh/SjQ4zC+kBh8WMGAR3ewMNFC4qDQrHMNnRiP5nB3aYM5II33H3zHT/MZ8CsoNkGhuI9nN/oz6X16EBgvf91IRcdy1c1JVTaQi/odIB8TQ/oidRY5mGLOg8qtjIrrOthMjFek58XZs7UadK+7UOnSIxNUC4LFdKeQlEzudOyHPUC/Y2Hs72LHlWfxY9E/Aypz8ZsgQO1e+I3HikB3QUPP9jn+n5TIL6Qv/6Kp7mAua7hunpwtOmVtpF4AjG5433GRtjhVWp5aYlqT98zaXWa0LhdampBSBkRnKi1qJmNhESQ+T0/A==,iv:Bp4rMngL56a+gcpNULz6E7DZGnf/q1zeZQmxCzscQWY=,tag:Z88r99xAcbFXHj+iPkDp8w==,type:str]
jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:P31S5yvcjTlLsCVwur19/QxV0IWkFEV6e58cSgeZ5EZh4PzHCKnCbGkSCEEJpRqtnhrWavs5,iv:yMuj5l0lqXLY9ynlp7x3eYW1dEsEKw7Govrhktk/5Qo=,tag:6mnkzhWl8XQ1k7HUZvmf2w==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:16:27Z'
    enc: CiUA4OM7eNbnaivWS+PdeaFjr/jFRpOjvaAiau8OMcs7qBYTJjhtEkkAmy+eklZfGhK9qP+sxUfiIbS1tNS6vCGaP3ZanP5/sPciUFJTuEoO/Vp/5E+jvAb5dXJhw5E+kvFzf9iZjHXCGoypj03G4A2A
  lastmodified: '2026-07-29T19:16:27Z'
  mac: ENC[AES256_GCM,data:raAdOjvnc6yRf5QcFk2Y+2wu2qAUGZ2HXoUAWSEPh5PI/JtFURDvViVpwMS6vqraFbzouGJLrigCmpMbh0oiAa2Xa/xzZJFbrcn0chV2y3ZT03EbZkECv8ta7RjN8LlTw3DsC8A7T3tIIAzDuLjBNj9v9paRNzdozGXx5a3G1E0=,iv:tl+AuxUrFeMOl+8hZlee8Mpb8/bYvCTKO5Vkk6/nez8=,tag:hc8c+Iigj8lqXk2DweRHAw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
