jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:KYX76vJIxB6ZA/6BvBSm/p3UoeQ=,iv:lhyP8NGQ5JFgCDVOGWAZtJmH5EYKeDQEzBQbKwqyLYk=,tag:7oBvsREmHpr7WsTnOvdW6g==,type:str]
        client_secret: ENC[AES256_GCM,data:wNzVLRg5quXVYSAaklt5Swk7HbkWe3HdtILfzj5xjSc3GwJjFWklyA==,iv:dkDSPyjBHDOXhT+mVdSFETzS/ptijdBgipst5nnoc3Y=,tag:bkvGUKgYNuRdkM34PlzJlQ==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:fcVKJakvAFtGeHP8jinulwFYdV31iozpa1ANG7FHRlp2ZXl4k94ezUcw2RKr6n72gfFCJhVHqNf1dlGaKAesM1/sFr1AZmuBUXhQZhqVh7+5keJ6yA4=,iv:j9okn36ieUA+5vdwZNR1BXyu5UiZEwaZjzqW25Hke18=,tag:q5QoXPG4rfuDBW8Wn4YFNg==,type:str]
        stringData: ENC[AES256_GCM,data:ZCKwmvQ2C9KX+9pAKmWgdRIhAgKYJ+xHTN4mvzgV0YN6An4wICS+WfIyvxx7rMWg0dqS/qSd/VQeqsSDrBq0aLp+JLxZNE5ZHeL1GJ4rCyxISNuy3bNb70jrJl2+Rdp6UItZDj+2Wym5ydR5OVJ5AfYn829t0k4+hwb8yTxSMpihZohvi+8oZyQrsdBCd4/a/DA08tg0GsR0K1YORIdriszH/VzXWDnOuTA6wmzFmVcZWLT026dePutpEa58vX74CJc5GYSwGtoFjRLswcuSVNL9g5/jBGE/YRpmfaTs18zzYq0s6rp/KKsNvTlNu+3MavAgBUaqlUTZpSr47myOiWMc4vDJoP3ig1e1TRjwrEELiOvK2me1Qsa6JOCfIoFRT8vzV3uBSmvlWbH7y5V/ThiEgAp3tfKNigq0aHW0ciZB8aZ4/9kECRnK/8w5sqlpGHtLZbckNK2CQj7GTh7944PL6/bnTQ6IrFBYy6tQPBy5q5z8TZ2oQPJXTnkij4nsPrhHwGHM40ZO1P4YEtvEA7vG9EMHGcfm1JUUKm2WTDZGomWwMlQB/vhJwr2wE3b7nOTNU70/GnqCmN75ARDCyt4hQgx6RobSvaR5GeV8tkuzq4Llmk1EX/IHmNTCmd+7eVdPTcWS5b1aFyorpA==,iv:ve0KFfqy3KGOZy1Vo1U7LL2CrPkDe/UsVCnZ8bFByJw=,tag:3crTsTsrs5kjXBVUURxdVQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:16:25Z'
    enc: CiUA4OM7eEKt1dIbAcoAF2GsKpfzVbAd1TQF1r/FsXSxnepVTCKdEkkAmy+ekl89QjFFGrQlOd+RY+uz/tqp0zWOfMpBgl6LTRVZFCgR1smNZC3TgCVxmRONPzZRj6uTUDHCti6NYtf0ukKR9+ZuGjdR
  lastmodified: '2026-07-29T19:16:25Z'
  mac: ENC[AES256_GCM,data:SLEwqB21hKUeKnfmx3dMfosMK5/fLHupdh4lmw+bbiyXDxs+OJ2K/Ui2F6RHKqAwMJOYmvYVNo9IZyIrSgHX2ud+BK4DaXylBwm/NMPHz4Nj114xqZGQau9bC41ANl1qyhcorYz/Vy1BmBPwA+XyhLTaGz5kM7P8FaszebDILoU=,iv:OR+kcp+wmOSFHKd3BIOdRLUgptH8z0LqNWcVI/gMGG8=,tag:rZK/omFKBSMSjgYwGLftgA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
