prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:WeBVx4oqKmM4RyU5Cw==,iv:oq/wPPeRGYea95s88Ltjaa7MrJPkLPsLvouX0816Keo=,tag:TivU0ICHtoU6+a5eKbBg6g==,type:str]
      value: ENC[AES256_GCM,data:FpgmQs0jBzvNfTOaqhE/XjfF2kGQwi1nriAD9VsVJQRIfFBmo64e05vbsfv06qlOreqUrQfpjWXUoNvlW6lWpZ4YfMRJc8U2a54nlsodbb7Z6M3yF+KhoMqlZdtHN3zM6bOxRhhlRCt4LKRoMKIBx+M8nHKn5RC7LJNSE1rBOgGGlKVIOuwyF8yG1aQu4AaK8Ic9PtrFUey9b+1IxEHZcVEO2EcTBcc6pwHMTYgqdwSIIg==,iv:1ici/jQm2+ndQbHAkqvobbie7Z46oXsSN2sNsJ5DxoU=,tag:5S2vwl1LNRhJKHIzg4kcuA==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:u6L+EH1icta+/sg4KNOIr/zHE7GTnlKCnwBTfdy/RFTq5uBwvZKP8NHRQ15UDJCiAmJfnbY66k8toD197xUzjg==,iv:8jNp7pOrK/zTrPayLZe5MyLClClopguROk0A+2M/ZyI=,tag:EQk7AhxgE0wT8yTJbzqsEw==,type:str]
        password: ENC[AES256_GCM,data:8RS1N4mkVNflE1IunqOvdtLNt8RL7JLilJg7YUtvbH/9PXE5xqLCauoZwzMLRgtAiXj/XoHrcUlN3lUdVopCzg==,iv:bBB7IN5QuTLcgyA7M1BQ4b2XUCqOODrUyu4HieXcf/s=,tag:O8ElabpLbwuc9OMtQaLruA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        Mo212kziLwQFZyjyGPGj76j9OEzgjXmVoAOZNQ7ckVOJy0ujANhbICirTTpWNBk5: ENC[AES256_GCM,data:fya/9TWc/4ci8KyuDkEyB93qBFH/pMAA557Hhnl+GuJRvjyxx3YdRHZSm4LDYK7O1TLcbjT1pISD2gr7,iv:k9l5586yTy6D+blw8qSyIJXoHukr8qjr2WrrN+NdRXA=,tag:IGT5AGnYuGbX0vI7FWILsg==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Qw==,iv:tNnGcaHGZO+7FwUTTaZofbcZZ+Pg2/KqBXEAfl5NHPk=,tag:NFUuwqMX6dPrj1CyiwQfyQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:4SdXOZPvSBVG5g==,iv:xTqRV8jfgRaYccx58vjRJUj1CghdAxtuT4S3Ygi/plg=,tag:XrUQnN0hQ1hNoj2LqjdRbw==,type:str]
        orgId: ENC[AES256_GCM,data:Jw==,iv:ZSwpaHq72lNVQbnFox7BTMgtYgUQX+n+Hk9gt8qxKkE=,tag:+ZQw5a/2DdWNlDOzVJYrpQ==,type:int]
        type: ENC[AES256_GCM,data:NCU2BRC/mJuedg==,iv:MLLXDKtbVQuq2d25X/ZYiFsXv1NHxiURMvh2mQQQPsU=,tag:BHDj9+ExAaIN8T0vlJkA3Q==,type:str]
        url: ENC[AES256_GCM,data:wMoa4x4cj1ZtTyNBZv/iqAnsGq2UNHoBpQO5QwV4rfQ=,iv:H26lNYLSKg0pctEWS14lT5lRLPqHBnFlnllWmXpQnWc=,tag:WY8oI7qL23SHwYms1GmDmA==,type:str]
        access: ENC[AES256_GCM,data:g6Mjmoo=,iv:kw8h5JU+TCup5NlKsUjWhLqnGdGv0iDTUBs2mLmZDJE=,tag:LjgmMfnIW5BxKNPsvrn8hw==,type:str]
        isDefault: ENC[AES256_GCM,data:pUJ/bmk=,iv:GMFvu0vPvqW55BlE5iLwl3a9+PRhfrODXmy6J89aN7s=,tag:Qrkpj3G47Qy1VUG4vmxNRQ==,type:bool]
        editable: ENC[AES256_GCM,data:BDv9Fs0=,iv:/h1tbUEyniuL/LP9+5qE/soLw9dGoUK/ccWCnsqqfmk=,tag:6OwhXtFG+q5y2Rt+uN18Cg==,type:bool]
        basicAuth: ENC[AES256_GCM,data:DiR4eQ==,iv:sjBevWWJH0HAcurcgXhUGxGub6YENo6um05B5cpX/Nc=,tag:7CpM55Aq1lcjZ9jU2ZLHcQ==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:cQeJRBJ24DRz4pe75DW/1ITuVlAD0bTDvB8f+dZEn8/HKMXnTPEBQJooBF1Pi1Z+JGemJA7VAkW6KM5IROXpXQ==,iv:9+nG0FmkrAcOlUfOmHtO6ZsRo+5Jxi7D1qstFX3Xk2E=,tag:+DamEwxnCPAQAE7XRA6QEQ==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:p0G0xqgxT+dtXIT3akKI8uWtmQ2B1GPJqX7lx2hThMvVHlniV13QRZkXAQyB+MAbx0hByIpMUUd923a0BfU74w==,iv:K7jE2Yg1Nkpy7YJ5rczntDTCbFzFR22sOerWz+zYslQ=,tag:2sMnBrcGSuquwV9Hp5TqLQ==,type:str]
      - name: ENC[AES256_GCM,data:44cL10+gJHgmsbnShgo/ptSJPlp1ZxyucwwE7GhzMw==,iv:ATVMgWRNr1Bv110/KRSqPXwSML2iHzARyhY+ML4jDAg=,tag:pJZNaXnaruOFXLQmPS1qfQ==,type:str]
        type: ENC[AES256_GCM,data:tRln2MTR+Miqw2SEUS8dntwB2FG8Y9fHnwFXzaDi0g==,iv:ZuXWbXkbIJShVsjETvno2u8ORyWF9qkI0Wb6jQv6e4U=,tag:5bo67J4vQtT6N+BcBnQgOw==,type:str]
        isDefault: ENC[AES256_GCM,data:VeF636c=,iv:yYU3Me6m6kH0N0daxWj64pwD4jyOH9LMviD9vNt0M8o=,tag:5KNAnrC1ysAE4aMS1WbL1Q==,type:bool]
        editable: ENC[AES256_GCM,data:IBRc+A==,iv:Oy3Rys9AMhJdg2WtcpUbJdeQDECQt+KcVvyu8rfqt00=,tag:ygpRZnn0OuZcb3njEK1meQ==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:S89G3Q==,iv:JekTzOfEW9UD/hg4xAeuB/HxO/HL2kb/HbsnMMmYAo8=,tag:md3xHDOnYKQO9QLrlL8iaA==,type:bool]
    username: ENC[AES256_GCM,data:pXKfkMGPQV7uJsV+Hrs3B6dqG5sfxkCGqesysRzfCmguU4EoaFcbFqW4vvHDe3yvMQiB8k/4i4Z77pztActxLA==,iv:HnMux6/qFB6TMQPzE01RZA3CWDml9bkI5/mMRN1I2fs=,tag:ZCd7XDjNArmVfuuWVQPX1A==,type:str]
    password: ENC[AES256_GCM,data:8Mxh8xIxENx+l5dDvUWiPElhcsVjTD4Sql8E0MdVCKT8o2Y0ko5RvokDrpkg8cw8rX2Nbn2AC736SS6ooL0N1Q==,iv:YXaOScvv+46kguwH2p30HiUXeTcbC4GyX1r0OaRYLwo=,tag:yG8aHyyKdMvzV25COPT2WA==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:D7vaMjwpQ31Bp+9Cqr5uA0x+MF7/ZJdIqQekjLHkuOf1XdDxfS+2LpxCE0UzNWkE+6PUN8AnfKxGXgvTfCdI2A==,iv:CpYEVkl/FARcz/4EX5fiA0SC6dOuAhMQrZSy73hZcX0=,tag:2zP1/5Bee5pOx323vNfTog==,type:str]
  password: ENC[AES256_GCM,data:EcInwIhcwOUZyw1M91pjc5ksBAb5GZcJJJypNBXUCu+u7HfcnLWcVv+1IIQdlEiMxKMY2O0tfJvX9vFMqV8X+w==,iv:5U+mY0NPlKFB5nQKQrXt9HGr+8EPGLGBQNJCE7jf4XA=,tag:Xh7jMvICDdg0eQFRLb5asQ==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:10:59Z'
    enc: CiUA4OM7eMXoNllCbgO8DDXFrpDwj7aaSnOFq5mSPNzhNFvTWa5VEkkAmy+ekj7/cakuY40FXUWhp3erVOOI9+wJzrVwmfnZsz/NZAPg2WJoiENIxLN7carCxTz8oo7toZRSkH7jQjzQalrD/L8B2iKX
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:10:59Z'
  mac: ENC[AES256_GCM,data:pnYn22dZS/xZF+VR3ME40vcPAiY7DGt2WVBBO5BYVt9xuhIka9VTHycpsjlbkLf6/1VzsYkgniTlo0hiK/8IKGCgczeGpE697wfo3tf/OFsa+zm922t/1w11VBWyTT5QP/I7TPvEcWVMitgfJHrgvgRXD3Y/8FwfQ32oJ1eWQvo=,iv:6+IJfN7Q5BZTYdUwEuHzkekx3S3H5hHUpIY1Mlw5E/E=,tag:zPCcgu6qyO6x034NiqB/Vg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
