prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:2bF2vr/l/SX0azHizg==,iv:xn6Ih0oXoiQ5Rz/4F3a5h8fyRvMDsKFPwi9fXOZfnwM=,tag:AkDnd2YZcNRqvjiG+HVmzw==,type:str]
      value: ENC[AES256_GCM,data:KQeALY3nN7swrasyV837H6YfZvZEFL5R48nsOhlHIJu1G2Z2TF8wEIt6OODglnu9pj6SFxisSVVUCZza88zATjUfMEgj4h9uZ5Cty9wofryhCic3p88pyxo9qqpdhcWsgsKXZmVVwcM25NJTUepV2RnRIX+Be/Ib1lgSQRjB1MsJv9+7RpOLiJyWGH+6exWxfyldTjlGSzP33S4dZkdsNDmxdZsRBm2rJkw+7Vb8RMxCsQ==,iv:GWr9EAJzNOZqjSiSDVbUFazWV2bWNfvgu/VbyhE1YcQ=,tag:I5MUCu4v+sG3tyMhfjrXEQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        Mo212kziLwQFZyjyGPGj76j9OEzgjXmVoAOZNQ7ckVOJy0ujANhbICirTTpWNBk5: ENC[AES256_GCM,data:NRzy889mI7+87S5mPXwr2z2J/vcq/2Ue8EZ4QM1jwGTIftoKBwNolcQUbAnhmXotQdv3VX8aU7MIFaEW,iv:ZCO/Tg9NKBWLfcy4g7eSSDzc8EZnF9L7/5QR7+nNljY=,tag:TkSsr2F6u0Es2KFo1FJ6kQ==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:WGzbjw==,iv:uzOr2jy07IFDZR/pQbcLXpb08bfFXXLYbU/uoXASFPE=,tag:iRcpOkZRvVaSE2rGf07hHg==,type:bool]
    username: ENC[AES256_GCM,data:xf3rbcKw1Fcjnw8baWqOSSMKg1xY/FamBs2OLHz9jaMfZJY+S6J7X+D8Ng+j6p6HAko9nafnyQlcxFxKdN98BA==,iv:5b0qQkBiYJy1yoPiMEjkDKM5QqJN2uQlaRUp+pnlARk=,tag:2o+NoRexbsjjxAenpx1Yhw==,type:str]
    password: ENC[AES256_GCM,data:MhlQisfvmqZBBb7KVfvVIYLNOvGcm30aBkwp/IdC2NcDVzxvXGTeGefZjw9s0gY/1gd9/GdIOITVkzQh8sY/FA==,iv:/JUZbbkAkxa8+fK9gyIKfCCc2ZAtG6h72jb8joU5XHM=,tag:GsRxVEwnmrbxbsJvuDxahw==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:2Awgoxb5gvDxkSQMvHQ8GPjk3hm+9hNHqRX5zfNI6Xkf9aTtDBd3PdOMECbbvq459o4pVIKJ9XKkjXQUi0oa7g==,iv:MLQKrUy2k/Eaz/wIuIvgvEEUysEYvbrfsjWgZuXJobs=,tag:A2hDl3N7PCvZTd3gmqkFWQ==,type:str]
  password: ENC[AES256_GCM,data:Go7F+e/USQu/8AIM6hi4DHr68fBL80Xh4r6VudVI8Afu1u5ZHnquJsj+Z/tchCbRJWs7XNiZCnAq+qikvDJuVQ==,iv:AHYSVjejxJ5MTkNlvw/7nA0OHZ53NqjJ4KVEasjIb5I=,tag:GRZoCNPdzU5WZhfJ7FE1tQ==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:21:38Z'
    enc: CiUA4OM7eNVvRmmbdgT+MpsHkt/Bol+hUa8Qh+CU1p8OXodNyxfPEkkAmy+eku9y59FSlPOvUAfzVB77JP6GFhIFhNAZ4OHuup6VAidkqsT+3OHdi6jfEXpFfDfrDiEgMvujSaHsXzMMR2WBX18/eEDk
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:21:38Z'
  mac: ENC[AES256_GCM,data:El6uWRpAiWt12sqjpsLBfLRq4Vz/e3eAluRFKeFYWlKSzHbuLb8ZbmhKmrWtccLQiGrgcNROHbqrKGTj4RKxAaNgrgRsNa92tQtG+Z7wb3IO/1uT3rg8tV9sM+5PI101nQXCTXTLOQ+2NSk6nhPKcgN2YVff7IvhCiiBcf1uVxM=,iv:2LIZU4zpXDnb7Y3pMeyz88onTxDKXeBp7oj7nETAobQ=,tag:VfxwZ9xVU+iYfYRhXpijaw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
