prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:8hqyjVHx2Ou7eEBCHO+QObyWgNR3/9WLUs3DXL7+nxRn4jD4c0Gzk/NcfNhKRKc5rOa0hjNQfLaCOmV4wXdrror+WdHy+9IWixPdTdB136xUqG5zJWBohjHdWkn9olb6kvcVWt4DVgPLtHICCkhpIiYiz18J5GsP5GrOfTkxeaxidt39mC97pGCaljrf/TNGdhwOZVSoyLlun8ji,iv:nvL/K0wE82F4EsDwAa/pKQKGoLuwQ0PsI24hsrlAafE=,tag:x+w6PL3LkxNm6On1XLv9pQ==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:DfWIuvRIgIGmPZUhL3AkE7A8GvqKzdCFSTHSl2wOwP29uC1Lol3Nn8qtUh5B2Pv4bk2kdygOWhfV6edPkkJYGg==,iv:h3VQXUokkmbGc1h8cjWUBQGNoBBSR+fmVb9ivftll50=,tag:zqAdX7H5gDotezUGUWSO+g==,type:str]
    password: ENC[AES256_GCM,data:GD1YhqMhaH3hzdGUbBXJYKgyNpxdk/O2Cg46O0j87she0rDm6I4q2omJ/R90S82E6Q0VnllMZ1N6g7i1ZHR/1w==,iv:BzUpJQ1cjnl97P8BS+0/Ew9SKmsXHCswHEBbJfNiKrc=,tag:JQWuMS150r8DzwPtjI5H8g==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:5+MVj7P45+7VjCBiKQ==,iv:H+pCOhJVRO0CVh5TToyyns27igEgql0iBuLyX8SHqTc=,tag:uZzwPij1z948CjQCleGgUQ==,type:str]
      value: ENC[AES256_GCM,data:QGGyRBMeZRfqC3PTV56Ubled81lmv+I1/cOXBw3jV8vjT8/rwO4QE/GXHp1TQ2ZsnIcklCiMe29Dw7whXs1DanDq+g+FCk8jB9mFQbFGvn+mLvtYrDZfDkjHllvWuKMg9vM6npqlYlUH3FxkM03hnWykC9f9rxGkB+7ceJ4lpGaJ2zRr+BX66KIcWfVfgjlSXRa6RxmYbLu2PG9dks13i7XATDDqvo+rr3osEY/M7HGEMQ==,iv:OG1M4xuFlp2FAzQ46M7C9dpM2zTbIFwKluwYUggvhq0=,tag:PEfGF9sJXtgHHTwxRES0Rw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:pcmTc+7PdsPYC3sUHDsH0YWl8i48m6V52ni7yzZzNh8B9b4wAe8UjeEw5VJp/s7sgulOeSfE/bNiPIFi9FxiqQ==,iv:Us3OO55N+gc4AI4Dfq0hNKz+VcP8NfgTNaA4tXqHcbA=,tag:69x2Srf+tb+vVw1mQqn6VA==,type:str]
        password: ENC[AES256_GCM,data:2wKFgODbSxMV4KFW5QR2bsTmzC3ut80gbEEqua8LCSKJZlIJ4iuaJ9CkINZ3ioH4kPJnrmN2Qh6AMFoJbME3xg==,iv:nFkpPfosFNZYpf7ZgLg1kITy29OzESFv3Cy+IEThfH4=,tag:0fRWGuXCkn2hXuA40u7vrw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        Mo212kziLwQFZyjyGPGj76j9OEzgjXmVoAOZNQ7ckVOJy0ujANhbICirTTpWNBk5: ENC[AES256_GCM,data:j+5TgM55N89ZbOUQ1VIC3im9AaphGfR8k0RWiJ4INpoQ89CeaYDSF0SAsnrxlABvBqe5u2TBkdHjnJBB,iv:o8JoJGrJKy1/yb/isqTq4PCQvNuQXW/Jzf/tOOHa6GA=,tag:hS2yVeKF110WpotENkqH6g==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:6g==,iv:fJvLgDruMYN4i5HaSGWtQn7LEBJ5yTNnW5J22bYUhQg=,tag:sdSTipPI72oEVIz0inL7zw==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:JYDU83z2rSGkWQ==,iv:xLAcp9K/xbnXTDZdCIa3aYKzWEo+ZgiLvKR7KmEjr9U=,tag:94Lp8uEjPyGPu4bE1YMZJA==,type:str]
        orgId: ENC[AES256_GCM,data:EA==,iv:pjJH5JA7/TtZspeQ68YZi+/UP4MvdgUBTflLMNeYdSA=,tag:waeth0Z/jW6mjcV16yuvWA==,type:int]
        type: ENC[AES256_GCM,data:SAjvJirVywC2Kg==,iv:y0RZKqVqX4OHSN4oHocGxwzCTGWCgf77ajrOCysqrwk=,tag:/F59HJ3ObyAWIPxDcJTBQQ==,type:str]
        url: ENC[AES256_GCM,data:zve3Hyo9Pv0N56NTl3UpHLis4WosIpO5L52nWZhz3UI=,iv:tUlrHuTY6i/upf/9YgJReH6Sk9MFeKBvu/2bxgJwsRM=,tag:foS32i4V5Yw7CtIO8WRf9Q==,type:str]
        access: ENC[AES256_GCM,data:B/EkoU0=,iv:xz1Odv+82wmXy6baMtCCmSRfZS7Ibj3N3VKuTqClw3c=,tag:exvqRryRCdD0M3TGGOyXhg==,type:str]
        isDefault: ENC[AES256_GCM,data:mTIswhs=,iv:5mW9jK6OTDYNzXhNkf/njAMqroQV3Y/RD4reuFHfodU=,tag:FKJInHPdgIOrKlLg64nSUg==,type:bool]
        editable: ENC[AES256_GCM,data:kkH82Fk=,iv:Ky3IyYW+VAfw+JXtq9QPvV4IKoWkEchuuIdBIi+HHn4=,tag:CTdHeR25sUgoJekfuQ5/zw==,type:bool]
        basicAuth: ENC[AES256_GCM,data:dfssaw==,iv:IEtRUU72coGHfNAP52sOO6IC8ntHCj/HKekfZBvaAZA=,tag:qqWjZ0oCiWJu3R+3Tf6aQg==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:wYd4Z7RgFiaW+waP9FSXG/0Vaz4SN+dBKjNYP19BT2Fx0OQpDR1hIIySxizTUqYg2ChFpZ7Hahm9b6Khg9ZdnA==,iv:xfXWG8YcD3jfZiIqP7KJdavI4LTch+E0SjbHe4BtlUY=,tag:AwYOMBaIuJHPcORe0yLGrQ==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:N2KnWuUqL3Nb80RlcXPhcAJnMMdMB6dB92bh72EWNc9gllyrkNrCtm6htq/Ltjxj+tZuyHqrl1J7yL5PrKKKxQ==,iv:xlEYHUPDNkUt1ne5+vzQll0sA31qriNLUEUZbENXrNA=,tag:TcGyEkp4UnoE4Kj8v2s7Sw==,type:str]
      - name: ENC[AES256_GCM,data:I1k1neQe2fZkCwFADKNDlC9QleYmlZpzqE9TJuUoMA==,iv:hiooNhaR7ViUrKr92afVvdiwub3IhgZNyQC1pk96DJw=,tag:CY8F7yop5L1FORtEoI4bAQ==,type:str]
        type: ENC[AES256_GCM,data:MRySEQgN82iHDT6UV5l5KaCYZM7EUVIZUIC86OSjrg==,iv:TUFjyQxfymAjVcMw4Cdh4eIrR4LpUX0qmTcoWsfacfU=,tag:YqlPZQspar+WPFF0z6nj9g==,type:str]
        isDefault: ENC[AES256_GCM,data:Yjm1+Z4=,iv:QtkVF9M4/WLxa8bPwfYNPMTlf5hWmx8ranukkXODWLM=,tag:nERVggkSDL0lx+p6scyW0g==,type:bool]
        editable: ENC[AES256_GCM,data:4aimEQ==,iv:JIa5w1ILNAt0/UbpbybfaouEA670aGxtj3R7HiDEuCA=,tag:+IetTLUGLvfm9oF8StmIyQ==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:MSWQJQ==,iv:DLk+vOdaodnpwL8CbX7zM6Qqe6c65WKJQrd8sR3pv9o=,tag:9kV6Wrlpntihclcfscl5aw==,type:bool]
    username: ENC[AES256_GCM,data:yk2cCRUhnhZ6+Q5pgL6zxEc6oZ7TeiD37sVF4s7ZGRgqw0/3O+lrBNgKL8P5HVyRSEL4p0p9jStujTc+Qiwvyg==,iv:iqd+SQcyfWMB5XlbF3beZYi5w9K3IHTr9SMsdHuBpVk=,tag:Ot7psVSl2ZhfwR5p/5P9gw==,type:str]
    password: ENC[AES256_GCM,data:ZzAWhqfBoujz5n1sDDNXhzYiq0Whhd7uvoAdV4RvgDEWNrZc9Iv4cTOWjHRu85fkimYIkFuVpp3dPXdA23kNTg==,iv:3Whx1WEl/URccGX9gBdxHU9wyfXH6injuGWMplVyIYA=,tag:aro/L+93fCqIP6pzZKkzfQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:29Z'
    enc: CiUA4OM7eCuAwxRtbOIpiab59KjSNl46xN8ikbyLPPAfNOViEkteEkkAPHlbmXLNyzZO/gkXiOjY/KC4tfSx11xiqz5zDgOnqF2D1FIP/pvPPJv2CftW6jAwBdOEIWAf2fFMWT9xyc3DJmdIRe5IRTvr
  lastmodified: '2026-05-01T14:40:29Z'
  mac: ENC[AES256_GCM,data:2JB3recJe/xkh086ozPpePCCr2cT5+RNUfsSwjiAgqZktGXubIwNWHxAUt7hNksWK+rICK2sVPt/U8utc/cgOclp4663+kiZnq7bVTXTC9BwfQ7viAgOE7elD34Q2emCeYguwNCK3hmBqheR5m7Xj8D4sAOq4CddrcP1Sc8qrRs=,iv:DrwhLnuqaJtZ63v7C6a0wVv1wpW76kQMNWPwUKwQ/9A=,tag:F96WDTRcI87eEDALEOT59Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
