jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:Wvd5WtgU3aYoUxidK8394Fra4kI=,iv:mMHWqYM8Hwy/oSAvIQjZ/bVQFdy9vf44OCZZJQEqww8=,tag:4P6Wl2DwBUGT8oHCu0PWLg==,type:str]
        client_secret: ENC[AES256_GCM,data:lDEkP07rBmqTYaCazTI2A5jthDHBZscqSkyyfFJeAx2jklHEaIzkug==,iv:bOuOoZ1f3he3D3oNTVJm6aQXQ9JOlGSBWK01AOJA1gU=,tag:p4fXoeea8+m65QIb4YzxBw==,type:str]
sops:
  gcp_kms:
  - created_at: '2024-05-27T20:11:52Z'
    enc: CiUA4OM7eMToeLf5fQgnKvrZXGKFZcOPUlmXBirxzPu2FTmAqdkxEkkAWX/fcVFQzEb04SBjy+ByZyCOayfihNs7RoK/TtYGIs/TDVkYj6/ubVzrkxIHif8Ff0T28PhhhdWWNLzKer3K6nEuOC4M/fjV
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-10-08T11:49:48Z'
  mac: ENC[AES256_GCM,data:Y+HleJybdhu7arxqvMX3fKKx/rTMAPXvykt05drd5ejl1mvXMQMebW5Hz4AEXK/uLxbbILtvplZIQjiWZJSihsQXrhoR6MAM1Jf5ojRe4jz0lpC3xzenOH/GcL5eeQQhMFycRnFC9+I7YyBQUaM7yX3hGl9V7q8TAExtX69PqIE=,iv:XltRe2OBx3Oft4+CHSHDKpuCl9BrKI/VqmjKXD6lKGs=,tag:RhFOhHGwPWQh/JfCUllYbg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
