nfs:
  pv:
    serverIP: 10.100.18.124
jupyterhub-home-nfs:
  eks:
    volumeId: vol-0cdc25a68ca0303ce
  quotaEnforcer:
    config:
      QuotaManager:
        hard_quota: 2 # in GiB
jupyterhub:
  custom:
    homepage:
      templateVars:
        org:
          name: ProjectPythia
