nfs:
  pv:
    serverIP: 10.100.18.124
jupyterhub-home-nfs:
  eks:
    volumeId: vol-0cdc25a68ca0303ce
  quotaEnforcer:
    config:
      QuotaManager:
        hard_quota: 2 # in GiB
jupyterhub:
  custom:
    homepage:
      templateVars:
        org:
          name: ProjectPythia

  singleuser:
    extraFiles:
      02-menus:
        mountPath: /srv/conda/envs/notebook/share/jupyter/lab/settings/overrides.json

        data:
          '@jupyterlab/mainmenu-extension:plugin':
            menus:
            - id: jp-mainmenu-help
              rank: 1001
              items:
              - command: help:open
                rank: 1001
                args:
                  url: https://github.com/settings/connections/applications/Ov23liWxGyeDz5ETgPF3
                  text: Revoke GitHub Token
                  newBrowserTab: true
binderhub-service:
  config:
    RateLimiter:
      limit: 3600
