nfs:
  pv:
    serverIP: 10.100.17.202
jupyterhub-home-nfs:
  eks:
    volumeId: vol-039e18f9304722450


jupyterhub:
  custom:
    homepage:
      templateVars:
        org:
          name: projectpythia staging
  singleuser:
    nodeSelector:
      2i2c/hub-name: staging
