prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:XDgBYKcw/TLCWU7tRmXrtcpJjw+tA7Me37hu/TSwWhD+EnqpHOfQk/mUwWUFTCRHCjhboTKELFN5n0bVEoJkQF4WoysX0QFPrC32mgmbVLVbVgBqIfM/7DKOyq0tHv478yu3qjK7CvCwYgsFmZEUfk04SfPXlfeBQQGxH/Xd7tRI5E7WIltEk6UlbZ4VPrVHbfLxnztElRUfethC,iv:1ejj3/JVacH4D5ub3yNewTf6ib9ySw1EmW+O+mYKVxE=,tag:ldinKunEKk99sdarBtJ3wg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:a9X6YK0JdvXpdfAqtra4nDLzga881R+vdqID6CEu57b/VnoogWgbxnpsQWCEPEmAQafdsszZsjY6TSnjQtSzXQ==,iv:hXolVHs1mhy8wvFScMFX/8g/Fqjal+QANcqiY5Ag9NM=,tag:ZNg2t++dIXwv9YB7K0vzOw==,type:str]
    password: ENC[AES256_GCM,data:oKc9gP91Z8PwMrZKE3mXZMSqtLm8WAOrW34WpuaIBHY98MLdCLfc8luMwHR2ZQUmO7wyKFkKRnFfGEXrU8pUdg==,iv:WHlq14Gg7lknGu4us99R5AHqKovhz1gGsXdCin7ptZg=,tag:UXuL19RSbg48h6L5MMGs7w==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:NA==,iv:dks9omgwby1SJ7+egubqEqwL2dGZtjAUJt34kOsmWHs=,tag:bQTBrJW8MrcyWtoOTTQEYQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:aW1ezbdOyjdiOQ==,iv:ascbhqyHiHa58lKFNma/bWQfB+tMtFJHZc2CMIkPJOo=,tag:uLOSvMlOvjv8q6TbKrdQLg==,type:str]
        orgId: ENC[AES256_GCM,data:8w==,iv:+HeElnkiX6i6Cz+G9RCLKEYI45CgNUgslXfFbKqhvqs=,tag:aW2wCvlefig9kU+WD9OtsQ==,type:int]
        type: ENC[AES256_GCM,data:6Kei0+hbAm1QtA==,iv:/f23FTSMSRAbP/q/IrZD/hV56RVMfaHI+tGkx5ItO6k=,tag:VcXdM85cOekaGwMOcLIqyw==,type:str]
        url: ENC[AES256_GCM,data:jh47IfrfZsq5ts4fmiLfHgngmQczyqjgULhEou8GPFU=,iv:be7uQZponLozD+toyZLCvNyBJdnqZUrnTgYRcx3nmN0=,tag:A3I+9CIRLiVm+Jfh41ZZaw==,type:str]
        access: ENC[AES256_GCM,data:LL33CS8=,iv:w74aIMlienXAQdGR5DgI7T9W2u4Qm7CpKazbhliw+Wo=,tag:Q12Eiix2tZ73tv6incZePw==,type:str]
        isDefault: ENC[AES256_GCM,data:BXSUiOw=,iv:qknJPonThzUGKRfm2/gki8tf2yTN3Vne/8nK1TG6v8E=,tag:ERS4USK0BaNepKGdcirQCw==,type:bool]
        editable: ENC[AES256_GCM,data:xIhUpQw=,iv:61bKIB4H4uY0YV2KnMxJgEB/G/wsj7oZinYxc4OgrnM=,tag:9fTDojZmvJNdpCtGlUvWog==,type:bool]
        basicAuth: ENC[AES256_GCM,data:nfWwow==,iv:c4bAPcf5XhJmaZO/WySa0pu41OFf/kUPcrB6ia7VjQg=,tag:2C5hZZLt+WKhQv69jCXT7g==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:V1X3Oi4suASYZ+Ul6nbxZuAQlE8zGW0NyhqnObKSlzO5+E4SYBSGlAyMs3jhvgQTdaENU/QxusFmTCPKKVFKEg==,iv:DWswlP9NDkmVYsdQ3pPbKKi+k2y3FTqdtKZOagsEKRQ=,tag:p0iMzBdvvZxuC/28kB9QHw==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:liS3r+t0uqHiu8XT4REzREOddmGZ0sz49TaCkRuA0vYplwdBNsay3kFqx0vud8DmQXGrEyX9T5LFMQGa7EzGzQ==,iv:zdyUZwomMixiT9xC0a0GnCFxrdogYvQDLMCofVtsqlg=,tag:cVIpPRLYVT1cddK+UwDBlA==,type:str]
      - name: ENC[AES256_GCM,data:kkQf5PoESTXaCw519s86MIF7o67B1Df7KmZVp6msGQ==,iv:/ukDTtjZQDEcbCo/hmPuM0FoAsZn5mHchu1dXJNOpC0=,tag:HFEq2nlNPIMXRweY0wK+2w==,type:str]
        type: ENC[AES256_GCM,data:s0829FiJE1XxtBqksOO4VvFmUcvlSMcgLzh7WsvZQg==,iv:etGS3AUHPz9buk6xoRzDL641oLhc0jB37UFvbxLBMck=,tag:YTL2IZWDKXNmqqnTa0VAXQ==,type:str]
        isDefault: ENC[AES256_GCM,data:H4uJ2Co=,iv:GEdZwMIrb3Y/adt6RXMDZr1FH2XRoUyd9f3nkLs95N8=,tag:+0xKdpH+2eqQ1iiVjWGAow==,type:bool]
        editable: ENC[AES256_GCM,data:F8mHsw==,iv:joIEqZuvHGYBUisN1XYe0r00u/lUR28KI5QX5zVVKHI=,tag:LNksyj6Yjr5XpUriCpZ32g==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:kV2WCph/cDTjawlOmw==,iv:YAotJakCV0fnVRkVvULk/ROMqtoUiBP7Kf+6DUu3kuE=,tag:kH2Zq/ylO3M3/DLX5aofww==,type:str]
      value: ENC[AES256_GCM,data:m6fG6z667EQ1lGYxzeVaBFa+z93qCsg3mwiRCoxfY8UB581H2SaP+FtE6ggV2HKtr3zIYTznWd+BAU5LSxHRXuulX0WPyM40eST1iMlS/aTmJM6ZklP3Ge3h3icFIebGSFtYinGxgw3dKVHGkeiD2vzN32dC9IM5qOYCbIcmBvejAgwcXKI8IBpJA7wH9NW93Qcn15SbrOtDGsVJGB2NB5ThXQoBQpYQ1JZWnN/RU/EmXQ==,iv:J425TdOTAD9/LEnjC67TYxiK2RzLbral2OacOMe4QeE=,tag:3HSQfJogRZTaEc9np5Uj6w==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:wjoTnVuKWVauDdFNKANa04QMdOcaQzzt882NicX39D8voNiesaKWVKOl22HJJQSEvg5gPGEQk9q7v33tuubWdw==,iv:vMur9UkXjrEuTAtXjpcvBjW+CP7Whlmppb2bRD5ixtY=,tag:NCTDPgU2tkjBp0PLRWRo1w==,type:str]
        password: ENC[AES256_GCM,data:0f5wxse8W+Ar0aZJvPeafMm7qZ2cd4DskvdZf4gS26k877oyL6e9w4wYWWrucrMvF+d8FxG+9HFshxOIPIawVg==,iv:KbXlZYjxQsYFiniOmDqamOY/3ydRmGPoNtB5ZaUj8zE=,tag:urgQA5dL3Cvag8T/jmqoBg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        weegoh1uewojiJ1ei6ahxooh7iz8Paegaivohsh9tai7uu0che8wo9aiPiZ0BiMi: ENC[AES256_GCM,data:c1aM5oosb+wpp2rKNOBLJ73RUtLIHfUPbwcaptuCQqiG/ONxbPbVYRb7hylJzH0bnq7jVjj0rypSvDoH,iv:vXTCKF9vjJrb9YJ14B4/T8ezUoVm6OKiaoeeIxeZFA8=,tag:/i0dm9UV4Fi46x7qobl34A==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:D63kTQ==,iv:41t9aRLLGLKV+4NEJJE+7gPin4QbsLQw4fvIVXgl/fA=,tag:o73tVA+ZyUVrW4HgW4To5w==,type:bool]
    username: ENC[AES256_GCM,data:ZKZFZLfG+gc/XGNFLxoq8kDAUXij5JzPLF6XQLgC/bXYhbrcZUf/2Y9a2+voLSRRlD4zHlH2IVJIQyC+eCAf5A==,iv:nZQNlBCDj7bLaSNHGnM8wArh8IzQJYs5zZrnrAkc7W8=,tag:KFjK4R3kV+5lcctcK0DSYg==,type:str]
    password: ENC[AES256_GCM,data:J42EoLROd+lxiAagF0j8iCbI7rLMXjzvpGOlO/bbw5LsFT1aBXdy4i+Vo5KE5ne1GLWmz+2X335FL57IfsFrng==,iv:MPpWq62yZbHgRrkFTyioh4S+ObxNF44bz8Rbk/sAoYY=,tag:qB3FdtBcXzWywRS1iH2ZBA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:21Z'
    enc: CiUA4OM7eF9/mCTA3zal8g62eDy+ceyh/svXdE/LFbffd3xCqHQBEkkAPHlbmUicJ52e0/mJQHHwZfYZ7XRwwMfi83l8W8VfgKOU46xsQhnUuZ7rqup6JM/y6S5yvya8CGKOdiu4MCpTXD9k38cLYp+3
  lastmodified: '2026-05-01T14:40:22Z'
  mac: ENC[AES256_GCM,data:BbAxlpxTWgIBGgE//8K20M7XzkFWIEZ3uvm+QesxBh0ydv4DJ/bXQuNKWJDFkDPKZRtTLauX2SH6qWD1f/g5p/OCOpqNl+olr0ct+Gdj5OCipoE0czEppf1VaLei3RI7P0NQUo4bI347wg1nHEUcuVoneGpagIz43nVMXYN53Cs=,iv:Pr3V5IUdxp/elZvIGV+J6xoRPDS1IECO4NNS0oeyhaU=,tag:4YVAO8CKbeSCW5+xS5W7tQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
