basehub:
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:6xbZHfFn2Xd252ggJOoSnY8/dM0kiafiJ0Ofpoe68AzmHPDOhJP2Qsbh63i+I6IQ9Q3geizo,iv:jp/RKaxnXn1KM5jF9MSVVcB/d5NYJg70kHLP62Ndnhc=,tag:IaGIv1lOlVuJvpSNLvX2og==,type:str]
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:dFGSC5So/gWCHfLAeWtvmVxa7b0=,iv:h7r8TFunhVjads3c030zSLjQ6k0gsncK96sXodfmEAw=,tag:+t8oSESCHWLUGT6SZntx1g==,type:str]
          client_secret: ENC[AES256_GCM,data:m8hTA/FMg3CTOwdjgaiXdlqt6E/1S27xhAo/lsK0XZE7eb6eSZkUMA==,iv:94sc3XX9l/8SLB2Gttt8oJhMbZFFIxPRtuQpWWIGY3U=,tag:2go+BQLLx01bOYi2QBFq/A==,type:str]
      extraFiles:
        usage_quota_config_secret:
          mountPath: ENC[AES256_GCM,data:4fLfkCmuAFkRIFSnTrMwy+3YDZ19kK+P2vZpXpT6WWQYvVzWhVDZQRyuiRPYu7M71TBFmMBke2gMdN3ZtiXMtlmBAmQTra/3NcAV/T2s2jy9tV4ivrM=,iv:EzFOP6czYp62YTfLDRtXjWfp2k96mcWXQGFwHrMZlRY=,tag:YnauzTNtkiuNA7rL1XhTgQ==,type:str]
          stringData: ENC[AES256_GCM,data:YR8XOLKiHKj0L/hC1XByuHc2bmtdeudD4ZzVub3wa7rlTJ516eTeT6k34L/H+fBs5u3VcTllg1QNIg7N7eH1SfJ3STrx9RElJvH344OlvB1ARi0tl8PHl0/1Ivz6E756KTjYXHa6+QAZsEX/c76Y3OYr1DpFsNcMvEyMt2Y9IjwkwOd/o6o+U11gEC+yFxfjrPipoF/M1dIVZy2GHA/UupVUtSm7R7jBXZw3EUgt4nUiSGJdLxkQz8bEWON2DF21hAOn6KqXiwD/r0NlecuYIzVU3mibHCmHFl+t8RyVIFtYIIdyFNXtKZwCPWY2DQieH6x4ceQx2ppncBRjnlOsXzvKxTN/BvWFCoP47am/PJtquFlQYKN5LKSV+V9uSVPsP8Toj7r4xvCi5lnjQSQ=,iv:6DkWEubMksRg4QI6DI9RtxZ3kTosQ/rWnRglhGlbZP0=,tag:Zg2wKkviJHjcCqMa6p2bVQ==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-06-22T11:23:15Z'
    enc: CiUA4OM7eMHYuDnjdRvo5zftvVGkKClOCkQPy1/mUK9IR+MIcQO3EkkAmy+eku9MNxbneqWyKX98kRq/u1sCK6E8CRUQju6POTsUG35zwf8BBvBWQCsHqtnQqNsgxvBKf1JV+DCgwZzOkx4+hlKGObGQ
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-06-22T11:23:15Z'
  mac: ENC[AES256_GCM,data:mF4c2fZimbLD9AecrJAlQKYboRZ8NAZkvGuQGYZv9TnxQLc/sBQ1sJ0UAmiKo1bPByYzM8yBWSKiEbGvcQ6J1mCngo4DiRkvrL6TvxK2ErwxFT4+hZnDvY4TjGvpQZz/p+1CjYLgXaDobY4KXz3i0UUhKKcVAeMXYOrMDgDqD98=,iv:s/qL2VjixOU5bPvDFa3enDIOhKByr62ntVIh6j9SKO0=,tag:8RB7+7Klk6ix44tZHc9r+w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
