basehub:
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:5ryNbR6td9Bj2xugqZ4C0qyWcpA=,iv:GTzFnd1m+n8NFJjwg9PdYnAQEKn4mLXg/VHfeGuC3xc=,tag:afKZe9odPh6BK8BCdtApVw==,type:str]
          client_secret: ENC[AES256_GCM,data:ML+9bI4MC6WRFF/LYrpwfUvd2DfjUg0gxM8BxGH/sYzIukvlL1Xpmw==,iv:w0eC2uNseOZKZiLBZq1VG8YDKGlBqafAi/oceKqPU5g=,tag:8pd6uQPBJS5wyoQljBSwbw==,type:str]
      extraFiles:
        usage_quota_config_secret:
          mountPath: ENC[AES256_GCM,data:YoIUATRviF07/y0VaDl7TzRWGYMlh3AUvNmXNoDpml/TynJOyXDG1t8khp8epMJMWE1fRbpta+oJdvrRcDOYPB5PpFKSiDO761/KMUN7/wASv/2zPl4=,iv:t3r964LB/HCotuugWrTpKe9THwS9IapuoD/Ynl6HMbY=,tag:hDyu3bF81rMj1ckyTGfzJQ==,type:str]
          stringData: ENC[AES256_GCM,data:fjaVdrqHQqAfiVKrycEoYWE7w8dIwhjU/QamPp+8rVafeGNb5n0JaFecQnsJPJcq/8E5PpRyt6XO9BfaYNXS51P9dioxLZ2bsozHbPu+fGiJsxiGGSakneMGbCeYVuh5oS5Wor2eEncmCbd76LJr0ur1cT/tomx3rI3mZR3TmpouIwORGabapqanBqhJ6oK1EZQHpZ1ZkwVQXnB1hNXwXSpQS+mknDo4s7Xnh5GJaolFkUubjp4ZqHeurpmEjeXNmzl7QPRqRmvzkKwF3QOiG1C0ne95wPC0IR2UOnI9OihykSCvZS0dMf8Kma+BzWwdBJBx+E4UcQEjtZXDdl5+LIvEH2xGamvhW/3608y15fjYIOR7nmvYPND8OhYzCmfmdkrHqwLk2V0eyF/j0gS32C/0HhOKPrTDtu+0jzDCBp/fJyfSG+H3xWt3lgBVnxE/BhjIQElOl5h466W/tGTsj/x1Hk2zGdjZkjy78BT9MkIICiriRtdvpSuyMQYIvwS+JgFgTHE+lYeUnwZy0IGjopeXCTWHASW//4biOdxsfvsk177rAgqY0xx8+PYZDdKPJKHd0IZ5Wy7jULiajg6Esrl58yQvkBhdTjNcNpQZzwLZDD4/JSqyiBrDaWYBvoGRwEVporH116Mx1Eu4hk+yT5XM3QIMS6uH7laSBA==,iv:ZUDqOzZVvKJQ/KFbkpDZ+f4oVAeMtsjx5LEYIxi7mLY=,tag:OWHqU2FcB/irWPt52qas8g==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-06-22T07:22:38Z'
    enc: CiUA4OM7eMIE2Kj/Xafz9xX6V+QfXn4znDyNQSZlMNX2YwzBPVJ0EkkAmy+eks6T9T9NRkR6/z+HEweYXKcJzkRmaTNm9EWIDGsSZISDuBUExHRzQUSbYetzkcaDmfF/eNBuao/eHL5rbGzn8Hf5ldDR
  lastmodified: '2026-07-31T08:39:56Z'
  mac: ENC[AES256_GCM,data:PEBNWE16f4MTgcltaXFoKIEPKcepTWgn/tbx5s1zpk/xzBnIpk7VMT+k1eAzNiR1VvNsCs4d1DjsUevwwvuW450+wH+w8DstiAcsL3ui6ljsf2qbA9o+Js7bXspbAn43DsAaVeUXanagLpA/v/nNY/Y1/KrHNzOODJYTqpUpTVA=,iv:HpIhNVhkwm1Te52xDYBhHeaFc7AWbhp0bwgburCxd0c=,tag:72bnbw/mnH7thOjH5q36zg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
