prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:msZYM6bTlp4EsU68OQ==,iv:RYYsGwCcfgn54yl7yLPlmJNj0vktyYF9C6NVC3izJM0=,tag:pU9nf8QzPtXvsJayXZs2Xg==,type:str]
      value: ENC[AES256_GCM,data:JFSPsaKWqJ5LxPk53MZlMqOVZfuQzg1to8O0OCyd+BxJMn4RKIP6SXV0niLTjDQu7aR01nVJHOyRGbFHiVO72OE0cOfpdtH/pkCSo4YtigUgNXPH23qi1Yf3PSGp9bx8p9y6OocywxEOxM7ovEhSU0aEf19171Hpolpu6kBXT0zmAvJeyd0FE5CHVIic+0lLdGtSO5V5NzlxlLeCizpCieG5KUbyGh73IpFjf7UHUiK4wg==,iv:FH6rPSUBQqshtvtKL9D5gmp97OqNmHwHCxP6xhO6N0Q=,tag:uIYcoI+AbhWt5ZNOIOVsJA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        weegoh1uewojiJ1ei6ahxooh7iz8Paegaivohsh9tai7uu0che8wo9aiPiZ0BiMi: ENC[AES256_GCM,data:d80ACQYzTEPxsVWWOdBFVRNB0ZHfs4lWxMvnnIhX4lRgQBOnhh49f7jULhbF3TGLHqQc/1o3P90bRmCK,iv:m/4a9rPWMKWTqXmhHBZNnjzNaGxDOsDy8dmxb/0WCqs=,tag:cXfSkMLRcP08bbn44uNsZw==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:LCrMPQ==,iv:5XEmQR9XEBiDSHm+4TocwBGA7Jb0OHhcwPZHoBhk8XA=,tag:+IefMjvJvCbHprPdAi1rmw==,type:bool]
    username: ENC[AES256_GCM,data:1ThZTszK+hIxGXl4mfGsfUh/FDcDzU4AzE6MayT4gIPym2ZoyLJI6Owwmq4mKkZM2a9fovQTF3QAZ7IKn6Nq7g==,iv:YyiXlNBv1IB9XDAF7J/xqkUtr7086CR5lkCVbOcMg6Y=,tag:5/AORgEtMugPRd3PZyK5eA==,type:str]
    password: ENC[AES256_GCM,data:UyOlmU+d3tspQP+NiJHvdQbTMuBZfOkbdlDXVms6sxQLpOAWu9OGZqo5qfqDucxY/uJMR9C53bQYQjSofroE5A==,iv:i154L6noKBdgbP38OJN8phmiLqucIJXNMbJVioxeqKA=,tag:wpRTWm/QMHAVPBXUwuqcpw==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:L5GlnlzU8NQLGmnc5JcWgtublQDi3/03qgArXpOELHMTm1GP2vrTeXTuepQiuBmmyc5CNY3kiDhJlyN6PwiRwQ==,iv:gbOcsOQMGLTJIGccryFaTAZDz9sVfAET5g6GjBVama4=,tag:nem5JfO79P17RFXGQH1/+w==,type:str]
  password: ENC[AES256_GCM,data:ajpuZJKSlBJCszShoDOI6NQgALb0/NpvKX8V5Vfno2cCIjIggR3GXXsZE+drElY8RVNT8oeCh+2/tDFK0npd6Q==,iv:u77XUcBBkrX9poUppjiwbLVGrwMBYEjHxBeST+EZ8Pw=,tag:IPLGyPcVbxDnp2E891BbzQ==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:21:28Z'
    enc: CiUA4OM7eMoe2OaeQcxQ5O7wt9RqOvL0rQ0w3wwGdylBZz3AGPctEkkAmy+ekv+m62ZBbPVaV8TE5B5m/9lNFyaxMpBZGADMtalWDvYtQa8D6JATyTGHBCCn+SHRYnU1kLq8KXNiYPoD9iDRVr0UCOvV
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:21:28Z'
  mac: ENC[AES256_GCM,data:OMaqa5PtU4ZqqO8NebgaQ7e4xeqYstwQTwNqiLDWSDLxwOG7Rk3DjNIEOIzTklMLf8SkaFU2Q39S57Ol0EeKUGJs2G3Tlcbs8VXW1Iyq6IjfGIxS1cCgrCdw0kJM7SNVateC5evXy3EGfP4ADTgyx6mqYNQ+8slI/YAtbqTGTUc=,iv:yHrfnt99bDrGcq7CWbFr0Sdqe4Go//c/jMF8hGidA/k=,tag:ivpBZ1MpLg4dRio04rDKZQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
