basehub:
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:iIlu6TfLfJ7pJrJgM7UVCZ9MTnI=,iv:ZfgJC01tZA1MZIUyhalml3o9/3QKPf4Tvck3a1RAEk8=,tag:oO7A8J5fUDOz41TAwoSvmw==,type:str]
          client_secret: ENC[AES256_GCM,data:4Apo68TTM4RNimsB0T9ejFil2+jSmkhBKGPlMFr3pPYWf37Spltbag==,iv:P8sYQNxV42H0C9Pudy+SE8q4tZ0aLGx5uZ8dx8Zq4IU=,tag:HWXx9NtLoFtrDW3MS8w10g==,type:str]
      extraFiles:
        usage_quota_config_secret:
          mountPath: ENC[AES256_GCM,data:g0nb/aOO1nTsawbwOcXt0M4mMwe+PEuZhDiyI//pPHAZtmPb2k/L/tymC2IGUllha0NRFfFRiRsBh6FsuFTh0VA8WgV/IB9szYDClHrRv9Lkl6a9Bi4=,iv:iAjtxOx4riNNVuxlAndEOL3oA+Khgs1QJnZMdM7WqNQ=,tag:tjCxE953D/ubnh/akX06jQ==,type:str]
          stringData: ENC[AES256_GCM,data:sha6hZxtcwn21R62oEEdKodkZ5H9gD5bQRuu/R7PNH2Wz77zaK/hEVbGfVynBBUfb4q9HL1YqOxbaS0OECDUIZ2h7YgXi5Fc+whcOmpx+/ZQPX3Hse18aLUTmte0CFcVZX5avUom1bYK1C8HxJVhI4ah5UxxaVqaiSU9/B2aOh/OzCC1faUAhpkHbIPHmHesdG+vFJMBhA4h/fRd+YlxupSbXzetk4EZrmvllHoQ/pchsTQZAvevdFEDoBbKQdNuhf0zFjZ3rVQiuhyGXXo6qiN/jCB+XHaGWRp7QRKMnAnK1BqnWgxeyT8x5HOgBGVThufbkyMvLtHt6pEnBhIJXPag88FZab+rWq2f5vQcxrIKmuuBZwF2CQeDWbClMf4Bq1BhYukrS2sq4t2hTumQ+384KHlWr1dEhHfdBUES2fzCH6gj0VST6t4GNY8bLnL36bpOmrSqk8XEyJs3V9U/vPu4fVmmHiZb40C7FY6H3oO9ljmyQrdgwomNIKI6EQnKmj58iYCPlsH0i7bK/NYyulXvNlNGHpvCpBDi9KQDlu1kjdTlrV3jIq8s0XdDhc82dMfAcCMM0oNdA/+M/BlCIDNCunhrCIL/1/ygn/HCmzgyYITuitNjjGbX6ZjDLHKyh+Kr1/bmlAB9IrWyvw==,iv:sCWelSpHrNGPYun0x7JwyKd1r5PXUXxYWy8zF7dmzrk=,tag:Slz2iuB7t4AoG5OcUseHeQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:16:04Z'
    enc: CiUA4OM7eBLygpy/hxi7Jljk5jd8fyhYcCL8pJIdTN6dMgZMmanFEkkAmy+ekisRqxeJKYpyc2CmmXlwgFVMD29cHPtmBy9tcwa6RuBNx15gmUcL3RZBafpf0O9DzBQinrqJEhFmLD5LwtzfNBKUBius
  lastmodified: '2026-07-29T19:16:04Z'
  mac: ENC[AES256_GCM,data:46qIxMZzuUGcRp9w97y0yX4y9JPfBQ4Q2A2GOrvf8rrxe6hxq2nAoq02ADZR5vGhL9QFzMPD9OVVZ3ZlNeusuQCJkAlwJFiYzhF+mz9Ysw3ZWRdJKPL/A+IUBHIK0sju0hxB7jdy8B1WTCaSgvOZQFXwfj6j9axVt6lETQ+hz3I=,iv:4RUCxk4R1hDBp1dHtKHWJvF2Kr5dxbLq3Yu7Q11ignQ=,tag:s4InDr2BGVk+D+LuFhqD8Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
