grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:lw==,iv:zz/wXe3QDeMOSp4wNR3k7BSqdMsdga/NZ/4Nax7qtcw=,tag:S3UAS28NjjWaeKr3B3ce5Q==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:YIf8u5KbERt0Jg==,iv:D9t+BbJavz9S1mtoRhXp0pn+CtHYmEIZrlDQDFKMUq4=,tag:zpksj1nlCdQdUDKuLee0Aw==,type:str]
        orgId: ENC[AES256_GCM,data:Ng==,iv:vA3RFBEhpYGbYAsp1+2NbKYYtXIeRmFpnh1/TJHnz1k=,tag:7Fl4/7rF+JBIJojdnj8fHA==,type:int]
        type: ENC[AES256_GCM,data:29dh6cHE5SetOg==,iv:eI0VwyO0WfyBS7934M//+6C/JqqHX5ox6t6C9RVVaEg=,tag:pFBtHtRvOkbIRzAS7YaKCg==,type:str]
        url: ENC[AES256_GCM,data:FnHTJpKd34N0lSIUts5i+ucjDtPmRJWaQsMiX2apZWc=,iv:PiMoU5k3XHyV7jkLlCQwr0ztuduIoXXOLhojq/QhvnM=,tag:AWRMP9JBrUseUFljL1zBTg==,type:str]
        access: ENC[AES256_GCM,data:1BXhRTk=,iv:B92skTqiOKCeFZdNw7PsQou/TWBYLQv1d9kG5v5ykpk=,tag:dQzKpfDTBUJGNkGHyI0wFw==,type:str]
        isDefault: ENC[AES256_GCM,data:DaAlLG0=,iv:bQ9la+Quy843burxvdZ7+Eq/72ePP9xqsySVU1fKYyw=,tag:rcuKOgc55IKKoVdplLA4BQ==,type:bool]
        editable: ENC[AES256_GCM,data:JlpUAus=,iv:lZrD/IIFI1RsDgWOzmXSqgRUXhOjnr4MHjDbaxtQfWQ=,tag:GPjxQS3wgqhN57BMu8STLg==,type:bool]
        basicAuth: ENC[AES256_GCM,data:doTlVg==,iv:bCw8PDwDKy3MwLdJNWuINcy7pkuDG0E5ut0vUtW5MxQ=,tag:t0uH61Ry/XkNniuslep3eQ==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:iDIgCrz2AE55tNfNZm7zOgAkqjY1Z3u21KB0N2L6JjM30cpTqVud+ex1ZcsHi9O67mw9NZ8MCfQE3WzlLmj3Jw==,iv:JFUb+FqdnWFdZ6Nlld5kVBq0JDnfKsjHHfqmeE6g6Dw=,tag:UiJRr8eCOutSjvNswSZWhQ==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:DBLUozMlw60YQqTpWd+TenrPiuZ3RxyRvzp1LfokUlTGmBCbVM92CZr1eyYacJl3oZF2doFJU6pqfVhof62ZUA==,iv:Gb4CDRrjgRC7jvMFAsxTejoxn3JVRuOxez64YBzhgd0=,tag:tOrhVUSsKrj0ghfX7dz/Qg==,type:str]
      - name: ENC[AES256_GCM,data:guMu+O+d6tpiybb7M8gT/rpoVlcKKK5o3+2tZI3XbA==,iv:GBCtkkRakDqhZFMH2SI9c75CR0WEUMcvsfd3hvjrnhQ=,tag:I6K51rqgDadbcFv4Yt4Fow==,type:str]
        type: ENC[AES256_GCM,data:HsAuGtm2jhYNHFy65frpNcXdMKXSYPBrtd5lRNOa/w==,iv:sZ1lgYyXr7Dkzz3E/fpyFGEA5IHjsvVzJqJfLZQ08hM=,tag:RlMYQec9BoIjdsevG1jKTQ==,type:str]
        isDefault: ENC[AES256_GCM,data:n2+qEH8=,iv:ds2WndMPNk5CQaBsomJOyFpJgWwxP6xXf9WVtDbN13Y=,tag:JOQNO3WkhUNr58+49Ed+FQ==,type:bool]
        editable: ENC[AES256_GCM,data:BRoW/Q==,iv:Ty0JFdnLyIteO50pU5lgM2jJgDEvOzI457uENy+kk9g=,tag:ep1qiLUcIrVezTgrlpRvzw==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:gCCaWwXuC15G45OVNQ==,iv:16kFUd+qkvnSPqALb2x04ccA/ftkHSGg+iJrIc3EZ/Y=,tag:+70tBUQqNEn+upBnb8gFUg==,type:str]
      value: ENC[AES256_GCM,data:U14HcdFSjXa+8aScHAeKIgnFEN01GmAotVOesdYPmxXwfhNFoI0T3HIfcq1w6KaEtEYKgLpGYMsKj8ARD1FDDCS024nfn7pSAxFLUL8bGxPDy+6Jd3xC5hHseXL/bXkmKOhHn9wJMtVuYKNOW6N10+CMIPcVfrJK55EmE+mwklRqxIiT9/Iu52LMn5hohQywdXbtp9SZwaxQfbrerWf9zR2mFrGWy4qhInCZA3kBtAJvdg==,iv:Pr7V3RNLN+2VWr0J1zv9V3+hTlOYUGgjpfkrzEMYWhQ=,tag:zmjs65U4/5IR5vmv7d869Q==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:KDelnXn4k+yy8TWDS0cb/WuIXiQOPXy6xAmUUbB96yxjy9bpBUKKmF5W7BFOA3BvKGxWkUzlsBmxCbXol30QzA==,iv:R6rpdSgzk1XgAM4NUbBLmbkn+4aLNtu0v70XS2fbFEs=,tag:J4gdWk37B5NLRzMSBtI9ew==,type:str]
        password: ENC[AES256_GCM,data:aEH6jwY41eipaKMPQTmsGQGr4pSQDctd/BZvZgD3Givc0CZy1GWZSL6tHOFCFvQ21yREQW5Ivas01eluDvm4PA==,iv:l5AThYXN/SPli2dDD76V5S+zGexLBbxFsk2eE6CHSZE=,tag:EczWyubllKa5Y3EHqcqDgw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        weegoh1uewojiJ1ei6ahxooh7iz8Paegaivohsh9tai7uu0che8wo9aiPiZ0BiMi: ENC[AES256_GCM,data:huKS7dyzErBtfrh2b2B+dVTo1KH6F2ybIbIpamMkN5sEIUy4qGBbT7i3DOkGebY6gZZhOJkXkQxgSsP1,iv:un8nv1dmIiDHfmOdJOyF1wIJxq4rE3XsHzjMR0mhVoY=,tag:k4JaaqTaTQh/6Wr8qxWl8A==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:fLGzzQ==,iv:GeLiIeM9kDpK1Lq39oOw07AsPxtIAkfc5qY7YqUpHlM=,tag:JU8Yof5u829VV0GPceVb4Q==,type:bool]
    username: ENC[AES256_GCM,data:vexjFk2t86kXRJY0wYh/IsY982aIAqAst/7OxLI9AvrA7jIyAgDe7aUmN9zjl0riFyGP7ujRLZYY8MPwZT0b1A==,iv:L1XS1aFxZW7FKwq2XnM/ktY4z3dMlURL0zhjaCVcFGQ=,tag:hBQwhotJKS7sTMaVj5005Q==,type:str]
    password: ENC[AES256_GCM,data:C95rOZKmOc0esh69L4UToyFNOD5e5yzBo9lUuuYLI2/su4I9cnfXJHC3pGKOBhIlRtc3Peb3JJ5Urr2d6PNIig==,iv:0FkkctvK9A+Gdr/AfKHcXprFj8ZDVoGlPl5tHdcS7lI=,tag:pcHxi6M8EzTs1KEGA5AYHA==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:v3m7F0Re0WnlxZO6wQRlRTdjNpKonD12U1c6Rb7kRoHfh1ME9/xMIV+hWdCkXzls7w+j/q3My4Rxi4Uoy71qGA==,iv:YP9hSV+kyY0zsCVk3MW+ZS9BMd5dNQvToIVDKDxe1WI=,tag:PyrZoDfZXR/aBmRGu2gwUQ==,type:str]
  password: ENC[AES256_GCM,data:KYvSnUEYpmzjcphOirY2pFIeqXV4FESui7Xlv5FQnS/wU10iMHnossyWnj/gXE8Q4EY74sgpeXYIoX/hVfF+QA==,iv:SvqR28Cgp33hshll6+aWdOY45USwydndMcmcmUrHueY=,tag:Yjsq2D/en5p0KrqKCDCGDg==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:10:49Z'
    enc: CiUA4OM7eFB/bYIT4UPBhG7Oolp61Z9NcH1P5lg+36kaEFA5ydoPEkkAmy+ekpG6lJ+odWVH0x6geKCY+TPlvMd+rbDSh9OI6kl3YrC9enp/PBuR5Echk9WLOjsemOsX32+280+Fp75PRNccBGO6hAvm
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:10:49Z'
  mac: ENC[AES256_GCM,data:RiolhRPZKCrf8zUVD4NN4HU4pzyHBaNXQdgn6R4gsxdcaQu9SAvl5ySc92J2WXMSYzjj0hZFfAZEo7045Qu4EhmPHxo81aSaeIc16MA9VE3n/sXyoBfN4KKTpV5EPwHzOcbX/OYNh/m/MU8HreCRthjtWCreVYaXNJTfVLLRJEA=,iv:aheLIQ+tWWOthQ5TOgYpWgKzhUl6zfd8Ipg9OVkBVJU=,tag:+LwyBISAUXFyH8fpdm56hg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
