basehub:
  jupyterhub:
    custom:
      homepage:
        gitRepoBranch: bootstrap5-nasa-ghg-prod
        # FIXME: use this repository again, once the changes in the bootstrap5-nasa-ghg-staging branch of 2i2c-org/default-hub-homepage have been ported to it
        # gitRepoUrl: "https://github.com/US-GHG-Center/ghgc-hub-homepage"
    hub:
      image:
        # Temporary image with jupyterhub-fancy-profiles 0.6.0
        tag: 0.0.1-0.dev.git.15540.hbaaa997ce

  binderhub-service:
    config:
      BinderHub:
        image_prefix: quay.io/imagebuilding-non-gcp-hubs/nasa-ghg-prod-

  jupyterhub-home-nfs:
    eks:
      volumeId: vol-050b22932c5cf210e
    quotaEnforcer:
      config:
        QuotaManager:
          hard_quota: 50 # in GiB
  nfs:
    pv:
      serverIP: 10.100.172.188
