basehub:
  userServiceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::597746869805:role/nasa-ghg-hub-staging
  dask-gateway:
    gateway:
      backend:
        scheduler:
          extraPodConfig:
            nodeSelector:
              2i2c/hub-name: staging
        worker:
          extraPodConfig:
            nodeSelector:
              2i2c/hub-name: staging

  jupyterhub:
    custom:
      homepage:
        gitRepoBranch: staging
        gitRepoUrl: https://github.com/US-GHG-Center/ghgc-hub-homepage
    hub:
      image:
        name: quay.io/2i2c/jupyterhub-usage-quotas
        tag: 1389e6181c78ec61e9c3c5e430e8840758d0854c
      config:
        GitHubOAuthenticator:
          oauth_callback_url: https://staging.ghg.2i2c.cloud/hub/oauth_callback
      extraConfig:
        11-usage-quotas-viewer: |
          from jupyterhub_usage_quotas import setup_usage_quotas
          setup_usage_quotas(c)
      services:
        usage-quota:
          url: http://hub:9000
          display: false
          oauth_no_confirm: true
          command:
          - python
          - -m
          - jupyterhub_usage_quotas.services.usage_viewer
          - --port=9000
          - --public-hub-url=https://staging.ghg.2i2c.cloud
          - --prometheus-url=http://support-prometheus-server.support.svc.cluster.local
          - --hub-namespace=staging
          - --UsageConfig.config_file=/usr/local/etc/jupyterhub/usage_quota_config.py
      loadRoles:
        usage-quota-service:
          scopes:
          - read:users
          services:
          - usage-quota
        user:
          scopes:
          - self
          - access:services!service=usage-quota
      service:
        extraPorts:
        - port: 9000
          targetPort: 9000
          name: usage-quota
      networkPolicy:
        ingress:
        - ports:
          - port: 9000
          from:
          # Allow traffic from the hub pod itself for Jupyterhub's internal healthchecks
          # for hub managed services.
          - podSelector:
              matchLabels:
                app.kubernetes.io/component: hub
                app.kubernetes.io/name: jupyterhub
          # Allow traffic from the proxy api pod
          - podSelector:
              matchLabels:
                hub.jupyter.org/network-access-hub: 'true'
        - ports:
          - port: 8081
          from:
          # Allow traffic from the hub pod itself for oauth calls from the usage-quota service to the hub api.
          - podSelector:
              matchLabels:
                app.kubernetes.io/component: hub
                app.kubernetes.io/name: jupyterhub
    singleuser:
      nodeSelector:
        2i2c/hub-name: staging
    proxy:
      chp:
        networkPolicy:
          egress:
          - to:
            - podSelector:
                matchLabels:
                  app.kubernetes.io/name: jupyterhub
                  app.kubernetes.io/component: hub
            ports:
            - port: 9000

  binderhub-service:
    dockerApi:
      nodeSelector:
        2i2c/hub-name: staging
    config:
      KubernetesBuildExecutor:
        node_selector:
          2i2c/hub-name: staging
      BinderHub:
        image_prefix: quay.io/imagebuilding-non-gcp-hubs/nasa-ghg-staging-

  jupyterhub-home-nfs:
    eks:
      volumeId: vol-01889854859d8768d

  nfs:
    pv:
      serverIP: 10.100.155.30
