nfs:
  enabled: true
  shareCreator:
    enabled: false
  pv:
    enabled: true
jupyterhub:
  singleuser:
    cpu:
      # Each node has about 4 CPUs total, and if we limit users to no more than
      # 2, no single user can take down a full node by themselves. We have to
      # set the guarantee to *something*, otherwise it is set to be equal
      # to the limit! We don't explicitly set a guarantee, because there is
      # a guarantee of 0.05 set in basehub/values.yaml
      limit: 2
    image:
      name: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/base-user-image
      tag: be91a6cddfb6
jupyterhub-home-nfs:
  quotaEnforcer:
    resources:
      requests:
        cpu: 0.001
        memory: 32Mi
      limits:
        cpu: 0.2
        memory: 256Mi
    config:
      QuotaManager:
        hard_quota: 5 # in GiB
  nfsServer:
    resources:
      requests:
        cpu: 0.02
        memory: 512M
      limits:
        cpu: 0.1
        memory: 1.5G
  nodeExporter:
    resources:
      requests:
        cpu: 0.001
      limits:
        cpu: 0.1
  autoResizer:
    resources:
      requests:
        cpu: 0.001
