jupyterhub:
  ingress:
    hosts: [cra.cloudbank.2i2c.cloud]
    tls:
    - hosts: [cra.cloudbank.2i2c.cloud]
      secretName: https-auto-tls
  singleuser:
    defaultUrl: /lab
    memory:
      guarantee: 512M
      limit: 1G
  custom:
    2i2c:
      add_staff_user_ids_to_admin_users: false
    homepage:
      templateVars:
        designed_by:
          name: 2i2c
          url: https://2i2c.org
        funded_by:
          name: CloudBank
          url: http://cloudbank.org/
        operated_by:
          name: CloudBank
          url: http://cloudbank.org/
        org:
          logo_url: https://s8968.pcdn.co/wp-content/uploads/2015/05/logo.png
          name: Computing Research Association
          url: https://cra.org/
  hub:
    config:
      JupyterHub:
        admin_access: true
        authenticator_class: shared-password
      Authenticator:
        manage_groups: false
        allow_all: true
        admin_users:
        - sean.smorris@berkeley.edu
        - ericvd@berkeley.edu
jupyterhub-home-nfs:
  gke:
    volumeId: projects/cb-1003-1696/zones/us-central1-b/disks/hub-nfs-homedirs-cra
nfs:
  pv:
    serverIP: storage-quota-home-nfs.cra.svc.cluster.local
