jupyterhub:
  custom:
    2i2c:
      add_staff_user_ids_to_admin_users: true
      add_staff_user_ids_of_type: google
    homepage:
      templateVars:
        org:
          name: East Los Angeles College
          logo_url: https://www.elac.edu/sites/elac.edu/files/elac-logo.svg
          url: https://www.elac.edu/
        designed_by:
          name: 2i2c
          url: https://2i2c.org
        operated_by:
          name: CloudBank
          url: http://cloudbank.org/
        funded_by:
          name: CloudBank
          url: http://cloudbank.org/
  hub:
    config:
      JupyterHub:
        authenticator_class: github
      GitHubOAuthenticator:
        allowed_organizations:
        - East-Los-Angeles-College-Data-Science
        scope:
        - read:org
      Authenticator:
        admin_users:
        - sean-morris
        - regis-smith
jupyterhub-home-nfs:
  gke:
    volumeId: projects/cb-1003-1696/zones/us-central1-b/disks/hub-nfs-homedirs-elac
