jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:X1c3e8U2j0ks9DZsyqro5GDZs2Qb8bzYo6ibl2YdxQ8CcyhqBYHAyrn4qvV+i2O7rD80,iv:A50rxYJYSDUu3oG48oL6Tu6rNTGfOVCG8A5aeyqxyxI=,tag:eoTHzE9S+QX+JjEOAbVJfg==,type:str]
                client_secret: ENC[AES256_GCM,data:jiAWjiLpGc4CMXS1BSYuOuzcXGBeoeVsYvzS2C/Gdhs43gD6Kr88N/5AYlHSghhPmOYUkC9wMsyKqq9UoAgNu68IqQE65sxd+FnXrlXNtI49qLmh4L4=,iv:CAmY8NhZdPiorMzBD9+tlLLPnkFmHdtweWHWZCcNt8Y=,tag:vOgIwLWK1l5Gb78YrzwD/Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-07-27T20:02:09Z"
          enc: CiUA4OM7eLpkvyqqfmzmea5+qZ+7BjQuqIXxoNeDJLSEPbgJKbucEkkAmy+ekjjnb5JhbjsUJq+ayL3P75QYwsXIcEv0TFz+KTkGG3RMIWqsiS4HWWOQYQfwQqTvwK3VVJfT52nqPyjfukxQetb0I9fP
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-27T20:02:10Z"
    mac: ENC[AES256_GCM,data:qOnBaLa4Iy0G8IRQjitC3q4/j6gQe0DLy3hSXUs8KZCaUpP1x24rOv/jb2+lnVZSeJY1IjcFLOKWrg+OKVCJdsmA7f97FGWZRzlpPVF354q5wdqlbhRd9liJ23dY3rG2DobYic+VHi9h8Q1ZYjn5IDCRBKarrekAjrf2orU3wcY=,iv:ejyNBQxihfn7SRl28AiNWr6plY5LpFQ6qqVaY2n0mK8=,tag:JKOP7yRNkgok8FJfPLi/lw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
