jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:GB2HcmaI1D66pzJvZFzRYoyH5DY6wbMTXAcL0cETL0k2oewuYGg1UY2AQzX7UEf5Bz2j,iv:IXxwB+fBS9hvoxqK7xjMOTmNZ315ylwz+6yZZByGogk=,tag:dPgQkcsqFm2If6M4+WBlQA==,type:str]
                client_secret: ENC[AES256_GCM,data:/332RFfxLaM6wRClejfjASi25Qmpu0zoYgIpgaoYWoGG6p7xC2p+gv7mxqYDmg+x3AM9zp5C9d3OzvUirASSx/CiucT1kWG/KZDtkIwTZ59JlIg3zyA=,iv:CNjME/Dmx5ztHt9TxcBq4oNEPlv5obz+je6FLrypa/0=,tag:csYmgdtcKZO8K9XMf6yhaQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-06-15T18:03:48Z"
          enc: CiUA4OM7eM3pep0T6HV6A8Knx6ICdvUEalDf/R7mNMRdfOm48EN8EkkAmy+ekk2yFamAe/WHutYfgogg84G552SV+LfR40u32tG95lTRrJkpHUoJJ2hDgoQeKDh88I2rJxVCqt1EY1L66t7sigNpgajc
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-15T18:03:48Z"
    mac: ENC[AES256_GCM,data:ra9RzBkze8SaHJ9yTnLXjnaw1aS1s98uV+ncdxm+0aVCwrT2Dfd0GWDgwniCh0mW9blDNwmvROSva5Bl7UjDsV/nzRECIqpKL0XIUPlW6AWxZ9Rv4bGZlp1Fn/20gQ+cuT5B9/QAwSCZqRoZeYNmVASjFvs+kAPtRFDw90t8t4Y=,iv:GbFcWY/LCEbje828DK62S0MQD+QoLQO66nhB6Z2sYfQ=,tag:wDeOoc7nfCQqPqvYNZbiRw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
