jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:nU7lbDcNeiymLwzliKG/g5QfoyoSR75O405PTs5CeGz4+ZjKgJ6AB5X8p6EU3OY5Yb3O,iv:NW8UykzRT9zCuSQTfP+XFpdC0OZA1Q+xxcrneArLP78=,tag:MdhFPqFLV/agQbOKSsGNeA==,type:str]
        client_secret: ENC[AES256_GCM,data:r/URspyeUojwsnDXncEjnV6uZJENEAV8YHOMZYK8jjr5FRIwLRqwXfDy9Io8aE16u5RiadqIsVHPc+9ZmeYfWCKpCb5bXvjkZNZawcNyN7pY0+vf61g=,iv:lJ6tbWOZ9ph3Xe7WwFPKuo+G4RTNH5jVMeQh9QoBN/s=,tag:n0w9J/kkFSK3OPQD/+7pKw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-09-07T17:49:40Z'
    enc: CiUA4OM7eKzD88Ih8UJ3+sKVzd2eGMDR04MeqEpuOF9u1mq3GktHEkkAsHDEl8F7tDCEyxPquX0ppN31+H9jsS+5x2i13Pjxg6gd6GU3js7j8NlyqNIYOJlMyDrHRXxxleo6/Go+25H2y/fLWqJVd499
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-09-07T17:49:41Z'
  mac: ENC[AES256_GCM,data:kVgyJJuK5465sihLiKK1YEFxRLvN6tsu0S3bSMsvVbP3wKd/TQm/Ayz6KBhrv6xBUENy9Y9WhQZ5K6PA+PS4QFrKrTJrADKAj9KN7PJ5xXUdh3LS4jhS7ZWdooIMPTJb++a137xwkNMPLkcs8fA0oWMaKS17wjw/xkVy9kGBtZM=,iv:S0vFz1PTBhqw9c99Y6o06yt+lbaoqRIq4RyZNH4f9sc=,tag:blrihGoSxH77Wc2LPoIcNQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
