jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:6MO1Sk9SDf4uOeJi5jV32KINQ+vOoaMKwXVFoKaK1lU4JJD6VEAG1rb7KS9LZKt1bZc=,iv:Onus+stce9Gf1ZuurlBrHL+1y4IAt8MaAHl+nUJmEyQ=,tag:8GpNMUXxy0HHgqWyLil+eg==,type:str]
        client_secret: ENC[AES256_GCM,data:rEzR+u2LDm1mrNYTp4/8Q0AJsTNbb1YKSquTjVeTVdtx6/EZBRG9YkeY7Yxuxh+jKoMb6qRG7F7OVCOayCThGCwhiZBBARjDDLsrCHlSHE3kHc4PKJ4=,iv:H9veSSCiH7s4JcZi2WpEEYWqTBKiLFgkAbyNxRIs5rg=,tag:aWd8eKZAU/qeTtthyywaEA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-06-30T16:50:29Z'
    enc: CiUA4OM7eCkG3hQAcU859tH+u+4lhhm+oR3J8wDiNIy07oEo6+BYEkkAmy+ekvczY9rm1WdrTuWABwwb0bQDQaTjvSwmvQrFUPiy70rgkSGVNi7EosDER4Re7dpT4Hio6jD2NBgzdJdMPzpkgRDqFUIJ
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-06-30T16:50:30Z'
  mac: ENC[AES256_GCM,data:DKF7DYDp8Ow4zevpZvl4IAWFfvrK+lgXE1zl0RBKw20uEmDmsz+U7C0X80O1rFYqoZpsY09XK+F8b7K3SBWg5SsmbTZBC9te/7ZG5DNZlH46JRhwHDs3lF2t9iOQs/Opp2q0Nnb3r2HF2hm6I3NYAdwqytUpKET4YP8NWO2/mb0=,iv:noTOWdKYYRjhqanDYYHHJ3Zn6NdpFInhZVmtpS2xyfE=,tag:ZEs1A+xUMiZ0mXhX+Q+RyA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
