jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:wT1nB+rpJY43+w2rhXfHfsgdM20DFbzk14FJwDwUsAhZzNbz/JAkwHf3x2KL7faDFVo=,iv:BWpeVl8f63CdHKX4enNGfkIuACvO/CcE8IhpI/pIyF0=,tag:qbI9qXP53FHdgi3TcIGJvA==,type:str]
                client_secret: ENC[AES256_GCM,data:08wG3402lWSrkqaDxGs4sQj9H/TOzvjRHjUjJUEpkizGsndMgPle0mT/C2fcMEi3EzmVmEfSbGTXh4qPTFXjIlg1NP6Msm8BHoiZiCN+F0KZHeejiGU=,iv:EoWbAgL8TdyZy4rnYAqrKvPEDDyXIMfQeweLaQV1vVc=,tag:LE50xIt28oIBEfcTO9eKwA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-09-18T01:36:49Z"
          enc: CiUA4OM7eArNblPpxNqE4+A2VJSIsyDG4thLii0nbEsQXIZcsjnxEkkAsHDEl4pUYj/e+an5QiUxeiRIze8J/N3LvSS40fs+hB7nwMJ5wLpP3KF0lQ8bb9Nq6vz3kwWiyWFCIHn7NP7qNksPPH4mUaxG
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-09-18T01:36:50Z"
    mac: ENC[AES256_GCM,data:EBDqsDUin/IzoFH0NjzhsCm4zboDq3w75MgSiFZtELFrjfE1hZPsx7/ZyxKNljLfAIaQMOcLRwO0tAVsReGYoahGc2fxecH55VkwyrC45HZwMNW9vLrpJyHNdvCvxRTLpSsiYfFhUitje7gCSK/K/3vqa5e9siXZgJBGf9bFkqg=,iv:IuCyHf1OjUSftc7e9BnQEBOq8yeEISQiVjvUsEbaa0s=,tag:hY2YF6Iy7V6dAfvTNR4i0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
