jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:nxo4bnle3kju4YDM5+p7ElsZIzs=,iv:IyCKAd4QTFRS/TcHKPeZvp70KTWwn5ieWDlSccBTQkw=,tag:dejfg5GCW9tD388V3OrbCw==,type:str]
        client_secret: ENC[AES256_GCM,data:GUa7k1PR6uKVSsMscp0l9+/ISsdW3UfzriM6kUv610hXdktdLHBuUw==,iv:ZUHGiz7pFVpIzS37so2i8FGK5FMed0DKxRhyB8umI6o=,tag:HMrxftkjlogMM7k2g0+6bQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:42Z'
    enc: CiUA4OM7eJRdDaAc1MgglTe5QJiaMdML5d0y/b7HAM9hDnh1wVb4EkkAsHDEl2BVokCjid/1yGo2NuTJGyYfyYyIpHIHkSv5h9N1PuhUO9ZFIMH5ySCZlJkKiXljHAStWZVYZEVzD2R5YIYY1QmAliIt
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:43Z'
  mac: ENC[AES256_GCM,data:mT9QLTtdMSaFraLYw5OqlJKquokzGgIE4QQuH0Gkhne0f/biocmTxJh0IruyLNE+rbo76sCypWyis3XvGODab4sbdlSDsiTyVcBlE3TodOC2XkqgN+p+3xSRxTO/sedzNPjhP+1aNYkwAiUvA+q7yBeb38n/rlCM3xb1CLp0svM=,iv:A7/kksBNzHerBjPgin3P30gu2apgRh2w5B5Nm3r3c6c=,tag:YkUCLACZKB3qpw79isbfxA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
