jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:IHg1dw21nxEXje55y9AVksxh1SrgRd6AOE+MJR+zbcx8Al80SA6fjGBPFhjdTtnV15vj,iv:IOJbsocTvr1U6bvy/4VNscN+O9rR42bbEKu7Vt8iKvI=,tag:Pk4BeXcPQPd3d8ApcVwa3w==,type:str]
        client_secret: ENC[AES256_GCM,data:5MkZVGf8XJhfibAU7M5WsqpedYxaXJrxVTiFSPlKQRoJtqdKTdq++dJDcExStfEitLm1ikFBnpKCvpwX0ZrsRJhtHmi26NyGtSkcjDUY2fZADiR6Bck=,iv:XgAH0XeWHRRWZwIVRu1gvfpOi165Ol+KeY729LGNfio=,tag:tp1JhoQXLfQtPfkC2e8LnQ==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:gXb1BHxMAJh0e0VJ0zDn7SFC1AyfGxRhLEyUDDIj9+1Eti+a75FdnYWBln3LAfojVCV2VXj83n95i9MsgsNR1Q==,iv:LZpZjhWSKG+hXw0jB2uTeUO4njF22gDdckellprxZZs=,tag:RfmTIiSGVQ9Gkr4q7RYUPQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:18:10Z'
    enc: CiUA4OM7eG+2R5HtF2xN8w//5rwHfYXYYEh88coURKRyCCw3AHzUEkkAsHDElwjXj6q4NXVEv6j1oWFQ11ECfHu8f2vJxn81GeDRYhM7g21ZO4DT6CTXvgXrGD+xBux479h+TcYAE4eFdsuWeXyriIcJ
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:18:10Z'
  mac: ENC[AES256_GCM,data:h/bpa3rm+T5jnmEHBen/O5prRY42b4kXNYsmqQIwNMBvhw8CfWRCh3H2vIUafmjIPRY2swTFJ0dyCv4Rr6inypZLtXYw3vwICa/NIhQzTENZHIrvCZiyQmO/noqhI34YUgJ94qRFuxLbxWKE2Hx4hw1eBLSya86oWzlPnStk/Xc=,iv:UKHyW7sUCQDaBS8MmGgZWNii+aVdPW+eGqF8nyyXZq0=,tag:v1VBXaDDodh2lXTXMVRzsg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
