jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:InSDJA3uMqhF41036jOfZ/6EznsJSiTMIZtTOVzYpb/3vOmTMF57ckc5mrsmiLuF2HE3,iv:mHwAwjHtza0naRjqru4MoRMiSfgKWRt06JEfCoRxWIc=,tag:cPVHWyxQSaIz7PFF+sv5eg==,type:str]
        client_secret: ENC[AES256_GCM,data:HZG8i2vwlvfYbvQh9ZP9CYPH9qedr/gQ47MTITYSDZ55UvnTR8HWKccAq0VDJty14hAE8UqFdhUJFyKBLYMmLR3aKjqf21B963YaazlHH2VHUbnUYiw=,iv:oXL+U81v2b23zY/TJoOnDbFyfD1f4rJM5GiEZ3hp6Eg=,tag:s2ejyElRRIMZ1IOxKBudig==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:PQaZTs0TY/kh0vHCVavG8CuQ+/8W/hnnnLhrGrFhUR56GpvNzHe+hBGRnSrzwas1re1aTwfJCNssjymVHkUGXucfG/gJHwFUwM1PwaosKRiQ8s/L57k=,iv:wUbonfv9kwv8qowZCMUIHS4r2bw8PQuUbCxF6+zHMsY=,tag:l7FqjvEo4JrA/xT9nGrfvQ==,type:str]
        stringData: ENC[AES256_GCM,data:8zvQ8w8NK8kwY7HXbIu//A7VBmtTTsRbPdnUIgWRS3+8HNJ63CC2ROwZ30jp71PrkbmL5MICZqPXSKTdHIGEyhjUQNXi9P4MA1WX0UD1lUIMiw4xO4Uka4/NPqlCD/sCYids4Ui9WMUE7+9TGJJeZsiqPwHBaoridxvA3DWKoN4bAk57nP6ZsCM/PVnG9bvw4X8t1sdUbmbWDf9tABFR5MECYIZFnRqZ+ef4peLksUNheQLXeOWSddKCRHbm6E8QAMSMK3D5Ss/XxayYOmDZnMzUai6tdSwlb8tbe2UrrwrD/Glm4Kaz9jVX0M1eyGQRiey87uOxtdw2JmuZE0hXpAlasEEidWOAz+LWRbyuGhUcqYaBEJwQeeGkrC12HTXxC/oRJbqyD8UH2nQs6Bp17IY2+xIrjCzDvEhLwpeKXun5beIm6VV8FBl2MxW55jKs04rncrzROcDeBYx6QR+17v8TEdD4ohIqfg1dj9nhgByPeWo/5i73vtCDjoSdY4wQ3r9kH9+5dmLjudRrcK74phS5D9cRuLyp/5OMP8Jf0yYltRFDpOsCX2dGKGV0vS+sjUAU26slx6ua7ss8Gt+aW6C0Pe9w+wgF7drN4tmkAIIOFjREYlIzkKhpvib0AjBOILxpgq1aLebBAhDd9Q==,iv:f/kk7oIJumQ1fNXEhyKaO/S5qKXsJCKeKJsjfsclS9I=,tag:acmaRQMK78LsWjKp0Wu84g==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:17:27Z'
    enc: CiUA4OM7eOFOdM7ssjV29x1LOfWR2wlWKQrysx2f9/yVtFMU+0aVEkkAmy+ekjWFuHj684I1r0oNyvhVQ1Gg1EuESmuMRAGD/6V65WBc7Mj10DJAD81RV5m5/KBCpjbtQblwSNemcaaURvqIvC3ehyok
  lastmodified: '2026-07-29T19:17:27Z'
  mac: ENC[AES256_GCM,data:ufQq9QSEtlzRk8/3riZWphUGyCvvw4S7j3Qvjhq8kYxghhSoTWlyQavdo6iY8eDoN4LUlBLVJX3j4xglOpUOhBr980WcBbRaoJvdVZWywvfkAuSa5uziHz1iGx08s/jrjIvtlaPVAledK0gHJqEKvIi4DLFipvVAOiuzaRM2EXA=,iv:/p0YHFpknXV94tcrrV2rFi0gKYb2D6F4ssUnZDdpgd4=,tag:cgecGSGmvF6arHm4JUY0Hg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
