jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:8x38WwmLThE2HaBhZQ2zFA3tplitiLdCbswwAsY5/FzeFOBnc1ozDLIiu0NL9KIv4EpV,iv:HXhxRINWDfbXgHjOxBCs8Nv3Iz4mkyQIphlI6Jzz0BM=,tag:e+VAg00tDYk0E3+6uECkYA==,type:str]
        client_secret: ENC[AES256_GCM,data:JVcXNEGw2pT4iPQi7amAXZnelMkx+ywzL2z2Si7mej8h6shrd1Kjtok07S6vKV9bv+Fl7qyOfkz5rgholU10INVjWm7dGIbcZnBlEX1SDuHoABLfR88=,iv:kQxtlmMV/lgx4nP95nvuCKJ2J3vu/XaG9FNUK86ZzwE=,tag:uQERrf1Gx7q+NrvYcccX2Q==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:LpQ3i43Ay2VWv1KojWNFA8MXc1HIzIKEbic8J2GsJD/iX86rrHqtShHp5tTV1rcLrHgsMecLOTJzVj0Sz8Sgtw==,iv:0WwyPeTzIvbWm5nPRc48QRXgjeq9fPaFam33vACgeII=,tag:eO3RLSJEr3B/z33TAAsk2Q==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:18:59Z'
    enc: CiUA4OM7eIhwlqvvPlegEoGq2Tun6E8PZaKpJebr6Vy9XHYttCz/EkgAsHDElxt8rlu0S7XkXF/LGof7ooLfDnnuBZKjVe9IMlIqYN6r9n1w0EOAsoqD5Q/l8Xn4696/cNiu8FPP3WX6Q8Oi2t/f2F8=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:19:00Z'
  mac: ENC[AES256_GCM,data:s6HHwmA4VRFS1XGmN7jWDeDU3Q+Hq/M3Zy6JQMaS6mlcYogj0xYv0Ln70WCRTJ98GAUKjScyBljt91ka2LHFCKMbGxdi0/MTph4MaICUmV4pWVnfhUKttMW+mbgiV4BicbAlzM2k8MSrMkHpv2LORv64JyG/NednqIYcpildTsQ=,iv:eg7RmhXsLm9CxMDZcHhPZ1p0GVFdqPx7ZevRebxYAMw=,tag:ya8hL+qw1Lq6g88G5AYHKw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
