jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:rkY+Opo9QLJq2gj2p9dhsn4r7/FBTFGt1gPcIefyiQu0qWtP6aO9St+4n3Ey9t5G4aO+,iv:Z3OnIzHyF91pQgfyyJfkUW0uCFk4a+Kc1GbeWDId55Y=,tag:XUjUBWuc6B5OdPBoe9bT3A==,type:str]
                client_secret: ENC[AES256_GCM,data:weX/1JsHDKaSvlg6ommLvd2fcjwlnAgowsYntyJdvYUHxaSD8c+DiUTQaz87Dfz5TkIAyRUi2Uvg8Dl++sqwoxzZ5kGGMVch4i7/bZSwshxKg7TKns8=,iv:eALuG1GmryGhFBL37UsAHXwXvJ8pEaCageT3ElwdQqo=,tag:wJv/Q/w82MypJNvjxtzXhg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:54Z"
          enc: CiUA4OM7eHw5BMsHE5IeGTNO+m4283r4ll5BHTrzPP41VvNCMDvoEkkAsHDEl3CDp2xtE8eVVm0XhtzomhuKqtK8ka4TGkJpHH8b6g/ltnp5huwc4fMu1IeQxklEcqc2MBWumQvNWJadFv65B8avcBAh
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:55Z"
    mac: ENC[AES256_GCM,data:2+dgbRCdRuw11s3H4c+dxzPTP3czzhZurqNwbg0dvSATIRkntclEl5tI7nOgrVMojBtjwUhObFvOh7bg8il9BvkPSOYIhbrBBWJGean+z/ajQG8vEPvcoCFUs4rJWNp8siFSgPTLDdMD71I6KeLG07jffGiAlQllKMcCyEHYfdQ=,iv:0H7zucSsodnAgiQArstPbvhBiKXGhjbacVMQ7/1OtDY=,tag:R8+5sew0Fc69kU6dL1fzBw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
