jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:sy0naB5tkNbHp7EYrE8TrUkfPBznaleTt42kqO8Zo4TcM8w41Iy+HgEXvUJQTq19Ddv3,iv:7b7osASYKPHAvI9/jtcOeMURhhcWiMq/2SKAQu3nIYU=,tag:YZnFwolWEhEdbqBv9uwiEA==,type:str]
        client_secret: ENC[AES256_GCM,data:KOI60I6PVbrNrXyBl0rAKqVwd/3U04MQHY9sz+ALw7RTZyYPj6s+9sE2iy+CeyUcGS9794Nl4uaifjxNUDp9k52vgo5wJONej0monSpVsi72WWbTve4=,iv:yTZhTme26WL4T5MR+n/4n/zESHMpcgpJ2B33FL9P+OI=,tag:taSaeWlORA5iPZ5buW0wow==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:47Z'
    enc: CiUA4OM7eER9mC8zuYHF1NkgYkDQAxP20l8BHt/snwMgHGhfTHxREkkAsHDEl097UohjXqyMbqwcjFybyCU+SHvdpqv/qQ7OzcdR3F+t6seS/RfImzo7Fw7hGsRCsAzg+pTEV+mge+DcluUQJAqvwGuR
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:48Z'
  mac: ENC[AES256_GCM,data:3fgCuMWIaNliV6okv2W5PWDvRnBErzda4hwxMsCilpSHmr2KigcBbJpFy64DIO39k7NHu3X6Lx0pXhZJNRuornS43n3yJM/J6ADG75aH8RrTWZrB4OjnVYi+ns5gie8wbf4PotH28XMf9EuhcOvNDa++/PpgXquXFdUnv/VzCws=,iv:1wRKWxssedrcyfuqx1ANAcV965boAwo2UUyz1M/wM3Q=,tag:Nn40kQxc8QibxB1YiKnb+A==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
