jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:x6YCGOXMctDfl0Efx5cnG0telZ7yFbepBVOoxoXr4ZBtw95iB0wZBazWOnVj9bRX1ToB,iv:wQvXHgmj6c0Y9SRMpxWsHoPIILGGY1ITBwGCDAEe7yw=,tag:c861OCdrBR5qdWzlZbMVaQ==,type:str]
        client_secret: ENC[AES256_GCM,data:6qUFMJQ1kRPwqEf/x15NiUzDBxLv2y2HRFSRW5eHRIziX9RjkTM4o4sVVUfrzQeo6Ih0n++bRLD6XGo86aafBXXVLB+bTRHpUQ/H26oBHqwsM4W1d28=,iv:v6rAAguNltOfTQ71bc+w7IMYivq+fU+uAILV+jGwQMQ=,tag:gwtDRmr3QTmPOJ5UEm8E3A==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:23Z'
    enc: CiUA4OM7eFBdbsbqqq+sgxGSmltyuFmSuzPF+cIWeej9vMwizSrlEkkAsHDEl/SmA9myAm7BxkurTIGahk12WQMdmMb0ijAIaHeA1dTYnC09EgJNORsEj7iNJjKyyd6e2DSJm3RCNWhyiHo5cDuqZ+4c
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:24Z'
  mac: ENC[AES256_GCM,data:B8OPXcohCSgypHINW1EUOugtOuqGKhPKTmqpw+BYRTUaLb6UZOdhCkPfJLfnUpZlGtXvk7Nn4g5hWiD4So5RfQqytfTysEf7dFGUhIGrjFKaqBwja7UNozSPeL3DDHnblViDRPD3LJg/BLuAU5oA7dI4fn9xffoKKVkFukIjkRM=,iv:UMrSfYCc/sExmzlWBJBAT87bwVT7n9YF/Dn4ukESnH4=,tag:YbIWjvU0ovukbzgYr36wRA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
