jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:luLLU715iQOZbDW5IcyTApGZdfX0TxY9D9e3KLyGlnmA1LPKwlxRMC8PRyYD3erJ8TM=,iv:Juyef/rF62xP1C9baP83wIAxlRBbKEnmQ2pjISScu2A=,tag:tthAJxOkqjUjE/Fa7IGVkQ==,type:str]
                client_secret: ENC[AES256_GCM,data:LS5epeUhJJMeF0YpZYKoHCa/dZPS8EFp1zvvfF312tPDhM0JkW6TqT+rZmipzOIC3ms8DNVM/EM2gFlqxVz37FVsKi1B5JGJJeKmndnSwtQskcKr7U8=,iv:7OGhzAYoOn6WTpIUdxedB6g23oGSIQRmuew9WIcVyno=,tag:8NCz6JI+N/6pZf/f2BjB/A==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:Zi1wc4kAd9W+i60y4WIP+IBE6Ce0xHEF86VwGR2fB0f1NrDGsL+ZnzuCnSOCYXRBVGcjSwn23ZXwOax41RqPvw==,iv:+1d25/2zwJVYf3mGu+fTqAWh0vZTy9on6cfEA9/vExM=,tag:kkG0nNHiKGSiAmFVpGp6Uw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:17:25Z"
          enc: CiUA4OM7eOlE+/9+P2G3zcYv09K2aKi1lLsB1sxrvjFAfKPcizkiEkkAsHDElzVisQhrno9vqt2vx/GbUpxMTL2AUt3htLdTQd9+UNsenkgExV3y21OhpeiRmYJhqT5AkTD0Sz+o7It/3hVr2vVFah2e
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:17:26Z"
    mac: ENC[AES256_GCM,data:Hs+xKgNESgP9OhLuYrEOMpy/JwqQdRM1Rgwn82vlrb3nuQkk7ycKZjf/UL6HCqfQRGpTzuN/jJQxdslUHRDM/UTrJd6ozfGBinMno9K6kA8LCMu5EV4nvXPs2JrXD03PnHOC+a3syjol6NA7d8AdiPQ6gXXUuyE6vXX3kurCBPU=,iv:iyNJyW4gKGqryhyoVtZwrPhopJxzRTke6szuVYg8Tng=,tag:bgZfzewXQtjbn/SsUg7FsQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
