jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:P5HDmPlSlRVzsHLjJtGMtjxnh1gpDvtEMgB4WcLSaK1CMz7lF8dBAwZ/z7kWHXZNCYzF,iv:n7onaBeeb6qon2uDcTp7AAD2zB2vu0UUfuEOgv1pnjQ=,tag:P5mtqbQE7z2qif9OZRYp2w==,type:str]
                client_secret: ENC[AES256_GCM,data:Eo1kBifP23dP/rwcTOsYEWqYZz2lCTvRnffu/t/Mm/uL5RSJuhaaCdEbsSkYTbXCOyNo/FYlhXdRepY2tUEASoDb1OFKF4Dz/JCySstlzi4NX4yXAr0=,iv:XlDNc6jvCNFNhvurxDuXVX58tAFhRbB9s4LY7EIwHAU=,tag:2nbGRG7dXqIT/4tPP9DuGA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-11T16:55:56Z"
          enc: CiUA4OM7eDGhoB0ZxX769vAczL2DrMLe5oz516o8eKVkx2JbrQ26EkkAsHDEl5HIItWxWOcK7DP9u6C2oT1bFhoRS9zR766RD3fTaIAZW/buMzexbtgBQIBRAT86zIXZESSpfr9O/FS9DbVCwxirJFKG
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-11T16:55:57Z"
    mac: ENC[AES256_GCM,data:QN8ABX1J5afhV19ZxDncKzMTPRK9hUpOu9/vaJK2GdwmTcAbTOR6yUd2jdTtgZyeuv57pKT2xX2r62/GmoSG+VHAAoTWDQHBjsqcexvsciWNbryP5V2ek8zfWxLnq0wlKs99a201Ltg1YNHLrxEu7af8NkV4jYF5Ns9fAjggDJA=,iv:OSQdXPKdQ5VoMaSsugwv6d01Z7izJOqUrkhKvdv3q5E=,tag:2zOKT/RHs3dFbUhyb0avfQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
