jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:Z/g2bOCP1dRnce3YZesfHJC7GC5es0ylW5t0LAHWPvx0MiCq6OeYOCeenR4MJFcl4rsR,iv:v1nfJc+qQ/b1jtoa7JM+pc5J6Nb87omn6BwrV9kmevQ=,tag:VFT5yuxrmBBZZH3jojLxRA==,type:str]
        client_secret: ENC[AES256_GCM,data:sZgmzUb5pLPTLrG+ch+JduStxdhhCy49ZojscbKMqTLZXyw+7oFKbgC568AB5AyWhAPCeEMpnp1za8KA7m2hiHJF4H+uYdopJoJ/WvtIUr6yyNJ8pmI=,iv:WSqcqf+oUlrDmuTe0tBlYC4C1z1EqfECsaIxCYX8urU=,tag:WQIvYw+njxI7Q4W2kFiohA==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:vD/0EzOqAho7kv1WdLh0oqdvMfbBAMYSkHwBHj0dUcZIvCVvTuwSimYLGS1NFmBsYMBxrJYOrjybkZDlzHINIw==,iv:ayTuXx0FkuWSAzEqh8gGWQwfg1Djbf/hgf5Vj9r58Xk=,tag:rHA9hhSD02HKFPrDgDkOgw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:17:49Z'
    enc: CiUA4OM7eIj7H2ihD1gn/2QRGg9iPJyjo9m1JVRLbzJtysjl0ZzeEkkAsHDEl89I2Z9qo65Jda3qEaixjZPEssGYnQVMyBM1i658Lw2fKPtCGNeCCKxwen0fHHSM0VTclJhUdUNj4fwmaXyZ5j65uz6J
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:17:49Z'
  mac: ENC[AES256_GCM,data:W7i52mlmJLd4U3hAdtHXvkZ3mH1tlwnkWiR54U5NsoiaA9IEN1f/PJHDDzujDJzdpGZwQ9dGjeyc20yP4Q7Ox9RjN5BrW8aeS3/NBVguPL9RsbMBkD/bWyOssc5FZ74uW2ojuUL+94BumkmDCKcbeq0t7YSzLKr83hou1aShkPs=,iv:KB0D/LhO4YxsMBZdWMbllaJACujm73HpVsYu/RMYxz0=,tag:3m5xC8FqlWJ6bTxIwXEoeA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
