jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:kNpJaH7Vr5OCPyEb2bgC+zfkxvs=,iv:yqm/SIV8FU33xpLbAd+E+emP2eg9qPeQHobN7a+cwQs=,tag:FLbTldqiyP9LbF7n5SFmbw==,type:str]
        client_secret: ENC[AES256_GCM,data:tQ24Wt0y6hOeCztatJMY/N4cPpOwUor54K32NYUhRioQ1QElt/I00g==,iv:WoQVYe7oUWOoDEM/4g6RdlBxblSokgvVnHS5n9FeJng=,tag:TI1o1JbOKVha85KxPYORkA==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:ADzxldZkOtDlOOSsxgMVDYqZR72gqTvdb5ZerOfUuO+1MgDLlCv5Q5sxuhukHAHPQoDXIpip0Ioh11jPpU9BOM1IG0mj+KFXa8zSsIsy2VTiH8gudmo=,iv:2IcTEOx2thHA2kx/6Wj3JznZaesIDdiWEUokFKYl1/8=,tag:zhUXreH5DmpNqn1eO8d2dQ==,type:str]
        stringData: ENC[AES256_GCM,data:Phjis9/dGY44cKjg+NKAgVw4XPo3eRJuKvfYwlKi7MiWEXj65Mk27guXoUtzrfMCKoDPG6k+gbumiOw9f++PMn3wWj+oLLvpg1LjUkikI3R4ATlsi8yOjte+A8K6YF915pUtVHIzhd7l9RvIphZF8y5aVcsGtVsm+y1qsQAVjtr/2xosdBkHVHe3XTmRZq9KXn6pRSRL/69/n5aOXkixQy9pw9om2d62odDyEcftBnoFmETNOEckRrvrY+HdJywVOAfrTS3lMc4fQPUX1cFwKYe35cGX/YW9PxYONEit1Hwm0nJcHse4+5UsjHG4u6+LVTnwy43VkrtM46AtueWnoUP6pp0qPB+inpFr7m+1LegCIjM/V05rfmRqhX31mGrN2w5ciau/p52kFBSdUEIwMo9tJ9++Av4lje6K0g1TXadGkB9VMplH9OmJKP4yLNJH5bIOT0AilKNNGrE45bBy7+mFdcFwx/kHjF2Fa9/B6pXf4qBxLXZFhJHnZlQZgG/2tFeEECvmhG2MBSc5+FfcTQwhQZcCCXbssfvPQa0234nkVQFG42zQ9oQ/JgqwAQh0tarMwFT3frwk2Bh55WNHWj5Pm2L3wQ+NqMw5czUgWB5lB+8OjfwPCoI834OGjh+vwMtf2yXWAhf3jtbB1g==,iv:M4hgovt7yLnQJh7zqpq+ZGoZQHRlwhyTPwJ1IgX9eTw=,tag:fjOHb0PtF8xXdoB0wjznmA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:42Z'
    enc: CiUA4OM7eNfrLDbCFF3FWFhMY7yOKJeq7q8U5aN6wAFmf1HD7ZcbEkkAmy+ekt32VPchZ4wRNSVobrZNzpUTmINWtc6YzIUmvebNRRDyXpG77TKnMJwIrK7GtSD/g7zhQ9qneNvv1XIC2HNkWvkXTosX
  lastmodified: '2026-07-29T19:18:42Z'
  mac: ENC[AES256_GCM,data:jMQNqBjEEXy2MbOdnl2zBysjxCtkWb+xe9vijdcutFAlfwp5PuIvIP5ZRNJNE7488iX8xPX9ptqSpkrXJTrakIr7kID0iBn7q2Hkoce0Z2mF4lkRMdyZyf/QI0A+B59l+cPmXUvmrkxV/n5xesqJZsYK+OlL+9IxzuYsEz3IGsI=,iv:1bbmIlxMUMgkgY+dmOAXLsrIs1YRhw//9sjT+7eOFzs=,tag:kkAibtqcWk/uk4TKe5LFKw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
