jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:V+hl0Aq8jYxqsSgw6ItrRnmJfjFogNdbxihDxtdUDPU4iZq4YKdO38sjbvL9kVO8NRQ4,iv:kAUbopgk/177mxYOEkark4x+s2y3MnRQJGrnq1vVrIM=,tag:y13USz3gQxUj4urlNzg13A==,type:str]
                client_secret: ENC[AES256_GCM,data:yI6GlDg2H34SCsxc4ZIheH+biB44GRzJdlyLpDc5V36DvG1c7IgmZoEPKbQTpfKBW+he/o9oyB1P9zoYb3VwrFRjUhfaRnjlmUwfjDKmerqraNvEWlk=,iv:JsY86njGrtgP1Yp5rUJ4CojPahmzKiwBR7cJNntFhhk=,tag:u542SMvZlRHecNVolUt7sw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:02Z"
          enc: CiUA4OM7eKRV+++JiFMXIUi74ClUE5P4YCAJ5F5+NEmZFOnMc3+8EkkAsHDElxbHmRcWopaYTsLN7NFn7hCuzNf5tevC3ZXyLcFFBXjd4RXvfiiqzJvTxq+CbcmWrxhn8DMnjjhN7HtiFvMWtNpzb8Ds
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:03Z"
    mac: ENC[AES256_GCM,data:t7ucyMPHWbS+cE1KWgaFqaWdY0IlH2X8BLtWB7DmIoPfS0G0LKfujbSZqHGkINRv0FuGZVUFsvrWdSdrIagmIdf6OdUV4xCzr1dMBLG4MQYV89YQn1Xhl7XmnnRXl/zsbFfIWiq/x1qK+DATrVKv7AAKqQklkq9mSo2CgHNH208=,iv:FFE+2/NEze80QgFU47sT1if28BF0i917eVcvlkXj9hY=,tag:g4WQtg3a89meKJZHaHly0A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
