jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:x+T0Du4fN9iysEhDguMSkWZkOUAhoBRW/ecI+rS8Lw2eA/CD2wZBENpyV4gia59fR6p0,iv:bKalokqhZX3ow1no4krl0mb8RER6/lGKRsJ3psndB30=,tag:T49n/rJk5UzhJFFHzBXjcQ==,type:str]
                client_secret: ENC[AES256_GCM,data:15Vc+7pb5wzGeWPY+pmI371Ua/gjbeGHNrqhhtP1XOcEUDDZYPkYr9hyGhyy/Ubgulle9kg1pz8lDrSzG3sax+jlNCvRh77FtRHdoWdeIToqPgyIN7w=,iv:JasLaULcaIDq4GmYn7kmxenMTaYdWed9UODGKbeFMpw=,tag:UJOACcfLoQykG+a5+A7xRQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:07Z"
          enc: CiUA4OM7eHWUXkQM3lNwlbGI4pbqMqtwtrxabP6SjHmqChA4iU2REkkAsHDEl0qdh0E1TILsutxqIhgulzwzfaZQJ8ptFCUJzTO36Iah9ntOIJnh7jRq5nJYRT9pjPeFWqjMb2Zcyvl7riOFOb7AGH/V
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:08Z"
    mac: ENC[AES256_GCM,data:K0+Tgpg3rh4WNwqh1oXlyiF5vvJwsI4M1qPOH4r791d0Mqr2wKB0PFp/cjx+26vjzgHDNimjxEgKqbrKAvxma3x9hEX+9z3ec/J4aKbcb+YiNkmvLhLJFRVnxAFQ7oaccojF7KffFebC/PIC+Tb2b9kCLZftuYkCBO3QVs9zapw=,iv:Bs2RFxBXXWhxCLelB7SJ4oKOjz7RjzKJxJ59DUwtkgY=,tag:i1NUYM9g4Mre/BPLHWaI2A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
