jupyterhub:
  hub:
    config:
      GoogleOAuthenticator:
        client_id: ENC[AES256_GCM,data:bB+b23gMl7uwVY7YREvusdVYrC7kaAfdjR0/cTE46vD25iXBOPx5NAmbvrS3wncs5itVbntsECEFyjPffI3xMOk5D1XFgVV7,iv:60ZVvds+0mFIkbhUsGduyAwLoDBWwMViT6sN+zQ8fCs=,tag:YINpr1GyrwPt/EUJSgfuzg==,type:str]
        client_secret: ENC[AES256_GCM,data:zfCFdQ8DbAVzIgweyvnPK9nUxuyDWkNbKPX+x7ijEApOPwo=,iv:RYwhBrU6Wspu9nFoFIWZzgYMkWETRznaAJbRK0bVnp0=,tag:b8l91F8ByLMKtofB6y1mmg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:a1kjxvsvq85CO6JVFKZ9gTrdh9wqzyWCd4sjkHlWPjHGBmFDHiRMnk8K1IQXI2Xe8tKCRQGbhnunGbl/PBpf1FQixyO6oL2733+cNnqOn4CMpenNCmY=,iv:T5IxAHGV6cl9nnROf+HyInX+axuwU7g1X3MkeW2I21c=,tag:c/7Mt3qZGeWx/n/MpujTdQ==,type:str]
        stringData: ENC[AES256_GCM,data:dvE2WQ5gkkfIB8JG4o4DkpCOMFrw4eNvEkOuTWXjdTDQD1s7yEyjSVu40JKFNm+sjA8SXdECRKTLL2BcLmx17DeRbG82zOd6erYWhAdYR13EkwINk/2Hf6W/d3EsaDrNkxDepjvO6HrWi+7dIkPvqWXHi7+2nFfxNcetksDjyuAc13xcLmsr9qiJ4iumzvCWo/S+yeQgGkx0kWXWFNo+Qry7U/1pDJkKDaSgLpvDcIgVac43zcFinJFv77EKKizCFO6fXyga3vZjHR1IGbhZ+s8OBT4OrwP4Vtfass1z9D8dCEk0wgOMWYPsFpnCC9NrdiPX77XJ3Icl7F3SUDe1VnITdZotPpTsFpNTRzSnvCVjbajGjMMA5wceEm9fdEh+bC/Ofao8UMyAAEabW6l4AvFH+04+TCvKUYMzia4h+9VxTB7NRxCtnGogG85YGu47YeP3L8dLa7kcRZ6BsGe8KZSxiUs1RN3Acw+TZlpqQrxYPTmY7oAFvXBKKDaNNRQCh/8/B9FSReR6QRB96HSr1kzlNesC8475n6FAFKML2UJvL+lRFtTJgeZx4l4vAKWrlc5F7az6HIZyCfStHmYGzXC3VntcoCr2PGJT0qJvXh6QVTNh0PU3IFkRLRzKztn6OLfctE5o5+XIP8qstQ==,iv:7bAAf1HaCg99qTvjut/b/YxDQbRF+e9IAQehXT0H290=,tag:RPDz1JQRDan22DDy8xXPNA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:18Z'
    enc: CiUA4OM7eHIXOawWwtDx9ty93VX6OwUXDPBSJQn3Rfi0o7MVTSD6EkkAmy+eku94eGhDWwzaovTFsXOuvJyMj5dThEsmGURx8gaDqJv8DHhHLJUMETFNJP7byAiBbtOgGKmzJ/YF3YbCF1G9X90Bv1E0
  lastmodified: '2026-07-29T19:18:18Z'
  mac: ENC[AES256_GCM,data:nd99/V2JV34MDTQW1nKbLDczMqpJgqu0mD9TdKche/iJPvYxMTFx8G/D9WZ58dbSgDu6quUeTjUEx2iLzyODkxZg1DqpRX3GyHER9OMM9NKQDWAggT7AWULe9Y04EYr2KILPAuzOUo/bofUmyVUt5QTSzS7xQ6KdGzTKKF0eUlI=,iv:0Ii3Zh+ddZzFhZ9y/LyROeNvd4LLksOoYW5cFUiQaJA=,tag:QAxTOpmAjfamESFaehDq1Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
