jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:ezZ11GgTnXUdv9deqVhpSYqfZWgjUd1rgT7RVcx8mA57373f2sPR4z0pD4FGloZPdR7n,iv:DnijhJY8nkBx9ia0r3JGBhmzafh+UT5m/wptN57bGWc=,tag:39TV6hawr1t5jLixrRZVeg==,type:str]
                client_secret: ENC[AES256_GCM,data:y5qPciaSTVtp51mufN9iQgNEzKoWR0xiQD92J2q4KVAfv7xoaRFd/AaKBKQE79vwKmJUFBTYQv12wT51L58LUNzit+UAmT+GJ1p/l3dr4BbLiUOK/AM=,iv:AUvoPCGzEKrWW/UdpaWkcWM3Ie0cmhjCWoEi7NzLEw0=,tag:us7QbNbxK6umbb21xDCcBQ==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:OYDB5fY1HVmcBhglOk4EifCNpvHzzvJUcQkcfQUPcJtFU9fAQP0svYiaaP51XieRvi9S5YJ9ljFtzUsEm9NDvQ==,iv:gKFXYCcULp3sl8IdlHrpw635wdVnvMKFE3qPxq/dAOk=,tag:mgYwdPUgbE8+QOnYFJpdfA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:18:06Z"
          enc: CiUA4OM7eM7/VJqRlbuijVFVS44cWk0hpF0nAAik6MlSp3wk8GQjEkkAsHDEl1HQqVT+MnZTJCQXqYpN0EAFW9l8wpBWj9pruKekeOCpBad8V/JBq3Bx/uJPO++I7/eMxRATFC/FIugIXadqbBah3iyD
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:18:06Z"
    mac: ENC[AES256_GCM,data:soQ865xzfOoEglRWZIXsgFfdFN0kMxMek58ixlanHfuyB5wVNjMeFZbb0ijaazHyxiTZ3kmLI96bxZuS+Mp27UO8UFok1STsWYd1OlsZ5YupAYk7ld48Edf2ZPFdIpcbr0sRZObbp2gxz+OAKLQwtCcGHXxBBQJgOlrcLOVbTjw=,iv:9KteaIbatqL7cUFy6n+ChBVWj9vwYjxqS1tmITFLauY=,tag:Ofga89UInuc8hs7+bWRxqg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
