jupyterhub:
    hub:
        config:
            GitHubOAuthenticator:
                client_id: ENC[AES256_GCM,data:4whIJFbIwXYD0v/tVezGAmyoqLw=,iv:K13b23pwVxNA98gd0APHcFq8J0NpxzhoxYGpQOeiEW8=,tag:Lvom+N0gnnkmi2jxQeLjSw==,type:str]
                client_secret: ENC[AES256_GCM,data:PdxqQcWqDdhlsfBLlK5Wdcw7y+oKFMx8bCagLJ703jvhQ8UlpNpRqQ==,iv:vUT6bMugZ4P7VlOkgbDnqzDSgVxN3K0DhFxQ3T2UrdE=,tag:FBqvo3zlSof+XytXE4V6bg==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:X9H2SLl6fNb+6RY4Sahqn9SVu4oPg9t73HH4dIPiY+k2rIjOYyugFDHlLJum74gvsTdrFCm3h75wGkVsdTZRvA==,iv:YZUsmRLeZa6HexuUF/RpMA4oIjQ84/6O6aQeb0L1Zas=,tag:Eu8JGnwSiZB781I6sd9ZRA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:17:31Z"
          enc: CiUA4OM7eJhfhq+98FcSWbt2NYk/rzY+y5/fO+vhYkmh60QQz0b7EkkAsHDEl4IJfEfsknpBfkyqSB12VVsrslCPGzVglSonoP24NsrLZvhLzcwYW9XSwEWxa1o0H3Vh0wwZxZwSR884C56kG2qyTuro
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:17:31Z"
    mac: ENC[AES256_GCM,data:SntRNd0QP6Phd5+Wg5sEgOXOQHtoznR6oW4+7wAZ5KZHEDrjkjTTUQ06Y97D3JvFqvugE6oR20PMcwDHmFC5vwdgiskDXPEd21cfckYMOvvgaKx3gsMGUcqvvJcAL8Y5dZs59xsFOflruLLNAiHr0Wj0UwB0Mvh1hCgOh5P9eEE=,iv:qCc6K/GHIw+2ZjLUYwcp4jmI/Nn350V7my2+cEcaDx4=,tag:MA82+gC+rb30J4AQHoQzLQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
