jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:EGmwHP+fk79RNRhVw1BcvATG7k65sg6dYq3T5VCtnKD79I6PxRH/FjsujMg67cH5iCsz,iv:VhOYem8mb4lD+QoDupRn7SaS8DxhO0sz30/GJXZ2bKQ=,tag:VnPnJopCkBnckn6DDGUBcw==,type:str]
        client_secret: ENC[AES256_GCM,data:hfboaCVHA8S96L/mu2X2R/LBTHqapOYwnzsy7vFGoLaqTMkH+9yEVlWdO03mx0GpTG7OCBDpvVydssa6NvWhLvsH7mem2bSSew+GpDRBcAvfzXbBRQk=,iv:/TPrEfKBtjkWP6TEZ6W7qp7MOwunpiNGrWYJ04sWju0=,tag:gQ53vGoCYo8YTuHCzwtiwQ==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:7mMz1UcYTtX3UI6BHrjsVrV8Vta0hmkvol9DGjlOdmduE+RjYr990pHfVKXc10tXE/nGfJaG22V6CE5kXykYoA==,iv:mmPmNfnQhjM6M8r8vVL1peEL+iwUSdLWteYHV6fRqcs=,tag:UeJiiOE+SknY2gR3qIWEdQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:19:00Z'
    enc: CiUA4OM7eKvYI74Yg1Xcmns7c2VwWMZ70+dUtEXXuTOjTruRAmidEkkAsHDEl410yPSTSDPGzvEwBFrwycMnjTjr/IN5jGaX762YR1bTQ4PNvEdka+8+sE1k+XgJN2th+hZmTsGsfFKc+ivAwQIfAu/V
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:19:01Z'
  mac: ENC[AES256_GCM,data:HrDvJpwa3AVn/sPT2xch2uXxLbgfWnfUzkYd2bq/YjMP0CZgM7oP2Mcuy3lPPwAhqd7YsmAeYDT4Rrp5RU0YvFd6EVuL9siW2IwH+8kiCgI+g/cnaKvx418wcUzrry+9H7NzkmMGYOGmdjkJmOw6zoxGp1EGQZ01PAuKj7oxqBY=,iv:8hR7HYTDsRDsY6R77B8jxFJs8meqbF9KSKMxKNQiG0I=,tag:PMSUss+y9pkqANBpQNbhjw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
