jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:49TgnWig6iHZ5k2goyVzNmXIgnezwccRJF0+cG8YtudeRghu5GJfzuTGUcLX16bsMuT4,iv:nraISvo7AYp//eAVo5eSdPnpCI2Hx9XR4KyOkodyiBI=,tag:bAU1UXe5v0GA3UPZorRoRw==,type:str]
        client_secret: ENC[AES256_GCM,data:e/gnAYGzJjuTnNmCbzzzEnNM/osVYEhft4paMnTQRojUOyZnE9QRuuU/TgIxk5B3luGQCzVnmUeLsvX38Bhkvgs5SvdohlR6jaOw+Y88zvm/Kk2ed48=,iv:gkHehWfPwXcyAbob+yIOvw9ePc/4l3ZFB2Diuu1rPZg=,tag:TQn4vycanN0T7UsFKjpjZA==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:X7qd7ix3eHvsepZOHD8QRkmiYgjiQKv2xHrnEUmfDGKs6PksTwxVPYKRwzMgU2VAWN1a4sduOqogKfGRIDIEYBiZnvXKtvRA93yOS272aH+AH9Mq8iw=,iv:rqb42DpGoqMLSU9/fI4z+RvrBUmBnsxpkxibqrOJhK4=,tag:j60/oi7pFN0E3BDyh6dKmA==,type:str]
        stringData: ENC[AES256_GCM,data:nMFJrdHer7LHt+Fg/nQQ9MDg+6UZ7OIrNHhl8jHmrlVJJvuqoP1BTbvyGGvYC8KEcE83v2LKREMLfKnkRQRM3pV2LAQFHfFZPV/bAmlM+7RhlHwZT7NWVvgfo4ZcL4qOWqFZ3yT2bySe/JTzG6Dw/mfU+HrJIn2VOpHfsVF29rNn8Yn0aSY/NnQWm7e8zL+K5zbOUrYpZfieuFvO3xuOEuBnVYEoyueDZxKOSTDzSrquU2zuaMntX5bP02g5IelxU5CpJfFDT4RRmXyHWMlPpUIFzhfWaskHmuPe3t6USLotKkokpYfGVXUpe3pjrWqSRCVhSBVgX6OOWwwuOjBjvj4UqHAGF98E8AVw/4a4zWtCkGTHae+SwxtPqSrbARM7+jrQFJ04wJmP9AiRMGer5vZWdmgvQlaL+ngD035LWt33Xscctfbx6c8IATMVJQexjJoWoirafmCgMMc25fHSp3dXdSpvw3+LSIets7IDereG26wQotvX84Env5S4GKidd8D3dc+JNuti/D4vNr30esttSAOR1+cUH+RsIDTImjnDkrttHrvfv+CDmnxQAHFcm9xxjtQS1lWRhXwTmBt3c1FtEEYCiYkflpAj0aqTCFsq+3BTLinW9IvdcMuiFb9cltxUaUXG+CeCsVD5ig==,iv:JMzbeK6zmbNw3v7wnaEumg4va8Mb+q75h6r17BDrHVw=,tag:AoP1tWxjLY72AszzehoqeA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:09Z'
    enc: CiUA4OM7eO7q0yzUGF2ZI9an2P7sWgJyG8YRzCD8mWF+ULyUFJe+EkkAmy+ekuBuoKCFWvOMyRGVxOUvgYieKMui7AyPK76e6PmHvUQuR3UjoNSPbDAcHTXLk2xEZDC3+5+hvfsweoegZDZmT+1C5i23
  lastmodified: '2026-07-29T19:18:09Z'
  mac: ENC[AES256_GCM,data:RC21641TShanmmxXNn8VDX/nLdzizN8C+tTmD7T2pnQ1EKwG6zj8c0+1btRd1Cl0VwQZxa70mni4d5ONTruKHBkAVO2b9i/rmdhcGtZWCV/Nf7nm062KoXbinSqLE23w5Mug0RTn7SS4eAU5ImEkM5NLtIgP7HU6nBDyLw4WW7o=,iv:fh+1vhSzy0G6vK11O10IjFdRzLXebOsuFcpI7QjOGa0=,tag:zC8zMkeIkuVTLu1uBUaK0Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
