jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:Wj2Tb85ana8icGRSlpo0Cfm2zJeIy+Sj+A68P5Msk/XPjfxjX/Wkv8ehzph7YJUOZ1et,iv:tHG4naWnvshEmEykpicgz87fvlwnKY4fdJrdvcCOK8A=,tag:QEKnNR4PjEZ7Tf1invK+fA==,type:str]
        client_secret: ENC[AES256_GCM,data:b6T/YCYW3jdYKaO6zfRwaBCnkAzghFGsKhTUKw0s2HH8fRJ+M4CPRUw7wAxaFO5aUYPpkt+44p3uesODC1fD3DL/PKkCnrqQUbNwIWAWxeupukeK/Ck=,iv:eTXvTPt5qLwGAshUI5G/JmRvyoQj/VpPcVKVrUiBivM=,tag:bZI/rMn3+t0llNad0SwHbw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-11T16:55:43Z'
    enc: CiUA4OM7eOq7PgaRqO1i7y7XAbMgN/rOmmkmMH5TYT1W4wJCGhMbEkkAsHDEl+f+J1Y5AxyaeQrstq1nOeefVGUscYyYEifKK8kD2dEzoGBzDhemeinYhbmgntsQ8kDVF9w0YewDk+f5+bO4EmnGQAcD
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-11T16:55:44Z'
  mac: ENC[AES256_GCM,data:kZHXU37j57fW24HaAZs7qAxd/TBmfmbvPF8k9ZfPw8rCoqemzRuI1TNCJjvF6cY9Qxt8Dd2mbCsU3Y0jIKisN+3cEX/Q2qEJV6wmrvt6jbzHiHnvM1O7wzjh1llbe+6mYWZq3qip6m4vQI4xH/dAsE0/G9UCXTKMN92Q1pLI+dg=,iv:3lsHBrYQlLigqVnbwdM359bsPC+f5XPcbplEY9jkh3E=,tag:zES4AunFGIHTNRwim7H0lA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
