jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:C2r7LYIE8fblp0vOV5ZlDz/ysiEINM7z1QKx+Jj49CVPd7TG9YIHzKp5Rk3BH8ENcRoA,iv:xG45BpMTeZ1DXZB4vEqmxvQTBDhFPys1LkpNH2hR5iY=,tag:Jcf/s2pB34pMf4oy2FTSSQ==,type:str]
        client_secret: ENC[AES256_GCM,data:BY1yCEog2HrtD+zbSZ3mTe+jbqqwpb1EbLd/Qy1cH5yVkULiol75u3Jv1JIdmj4ZCtATOfOT+K4jNAIu29AyNldRAvh3hOatin3xot7MH2ig4AExOz0=,iv:les6bGmgd/9ct+3fLEDRkDMNR6XkT2o726TdF844H3c=,tag:PzfQBMAc1Pf2wTYxjtuPHw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:13Z'
    enc: CiUA4OM7eGNa+lkSuno3avSTve5KrDGK4tuuQcUx7YtaB1AdZbRkEkkAsHDEl31gQMqxfSkagqPaJ60O3wvES9Nq+q8K5zyWQ5+5b9XhvueA4w8+TA23elmFfZnAsl72JkaglYCywziANQmq6d7X8jJ+
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:14Z'
  mac: ENC[AES256_GCM,data:xn2sXEIrQtR6Rjz9oGK/EkkYmOWhEGfVUfi40SmM1raTitYzYlRapz/z3H3nhRGYPfBGGxi4fqtMxZU2UHzp02MVCwUKaXMW5K3SxOFjuwu/idu2vdf290oppz6mNibu61bC7pIebQH6HHG8sbGyr5zBlERUw66cZGqX5wjKUy0=,iv:nGLyvZAI4pWYetroqwwMsPGOVy/82bpyifqEGLlzSwY=,tag:mWLHY/w3lu4kN8WbIyOyMw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
