jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:kWm44BAomNiNewycBpYUEmFmsJtQ7WfyfCNOpr9+xVXWEQHDPRIfFKvl+rXbuuPf0nmxJWgPpGFm+tjDlCj01R/n4LREwwBD,iv:X10NlrX9XHLV6YPv15UOu2bU8oyXqcoIfDUV+1Wr5Bk=,tag:e42b1v1CAXoSW6aoXszNhQ==,type:str]
                client_secret: ENC[AES256_GCM,data:qguoZvRp2bJfAEHygQMr4zkyDkGd0EqLXMhhGHJgbZ/zEMU=,iv:2i3i3W4NTkcLBuZAojblHj8xON+pARDtEfncVgYUAXs=,tag:N0bhKTwcuU2nv/74zU48lA==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:TcxWqyrn/Mh54Xwn4W9HdDA0CYLs7CHuz6IX9DEZoWSQBNe5a8h8NuVv8c39HaT/tmZNwT1hbJGSQYlKEn26pQ==,iv:vBR9k8R7jk5RU4HkHU1FFbz/9sga65xyVgNAQhDK9Jo=,tag:h35yEVK4URajv9Lpcx0/Vw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:17:32Z"
          enc: CiUA4OM7ePfc1d5/jOHGUaX4cgwJEAwmPHDOPwsq99r91u/PXMc3EkkAsHDEl/aWXhxRohUieKN9EBt2wgagB8zTN1HpIg3Tx2xDbrfcNn7/na+hHLRFetTtff+1rs/3TyVEPiOgQNzz/H/rdC4M7nM+
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:17:33Z"
    mac: ENC[AES256_GCM,data:pXT0n3qnV3PZYHc2YFXDc7vOVfSLpBS83edSjhXAse0ZiMv4wcvGYxsZZ2BmycEyz9rpiK6B5Ziy5WUuKHIpeYi1mFN+XcH79IYOtA7ruMZANwFRZD+lBK+PSwbo8KU+ohXAcrxyVws4Ua9IyhxXAioNvVy+1kSeS8L87NvqMfk=,iv:ij8ujtYdygY2+P6cVUwg0xPviieWmbISo2iqHXkH1h8=,tag:qjV9C3avJArcFMQbSQHbsg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
