jupyterhub:
    hub:
        config:
            GitHubOAuthenticator:
                client_id: ENC[AES256_GCM,data:KU26MIShloqcEVngNVC2dLIFNjs=,iv:FlzjjwANaS1cy6mgSTrnR4dj/+QbSQVNiEjhXbFpHAQ=,tag:BUchiVv7n7p9yLffyymIog==,type:str]
                client_secret: ENC[AES256_GCM,data:W2VBMRTos+LXKy2TJHJGWZMgkoQhxkRjPCfy+weGd1uJAhbGUoDb2Q==,iv:e0zlV4ok9pMMpWr/J5GPX9AUbZg/2CzX/7mna7HDcwk=,tag:wqvNbPtvI9r8CfsbMAQRKA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:26Z"
          enc: CiUA4OM7eBrz1OLsM3yLo+PHPd0f7yaMg+P/VeLlLctx9VxCYuTpEkkAsHDEl7vhCFEylHbiI77zxQEYl5JWGeDHudB2w2JeDVx7fyZWMM2nXjGKyaQUfqFxhWQUimDPe3JbbHTck7MVAfLIhYkNUmce
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:27Z"
    mac: ENC[AES256_GCM,data:TV5qu6PBqZq84RpbCY335kkkaQIBIRjD1zEybyDwJQpFnyNTxn5dzz631CEpIP35Y10imUWGvDsS6v4zPc7c5cVtSTDHqw6C3XpdvQGji33p4Ebwkv4rcjvqtey83OPbmOVoQmB5afAh+ujnigFWiiHIpD4pcF9uswgxjNpxGGY=,iv:RkRZNUKUErypj/RiURFmUnfnFzjzFS2bOB6DrmvTkrI=,tag:fztF7U2briPsa2PLrGWhpw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
