jupyterhub:
    hub:
        config:
            GitHubOAuthenticator:
                client_id: ENC[AES256_GCM,data:XCkz+Am1MGBM1XSNc/gJv3v/zfo=,iv:hm1TvoboaoL3aOuoZlAtLYR3nZLKdiPUblHdF1fQqcY=,tag:MbS1raG6qPusjJXtJlbQAQ==,type:str]
                client_secret: ENC[AES256_GCM,data:tu0cabKd/GCIa/MXJoGpg27PUoXZzGaK3N3RCVKZM33NaLzACBqVRg==,iv:BTGcTW0jMb3zZNUBz1ivfBoXLXnkMVe3hciPadzkt3U=,tag:styTSXi221cL/8cmeXWCtw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:45Z"
          enc: CiUA4OM7ePoyMdP1+6xWzNNnU7aWFfn7QrmgiIRcvZ3pXaUQkwEZEkkAsHDEl2zIeF5nkOAD4WC2Z1Cir9fd/9Biwt641ua1LsC671+J0zC8uaJozDbC4Eb0WjE3nc/fvOG7xHfWoS9imQyTK8OkbW99
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:46Z"
    mac: ENC[AES256_GCM,data:aDF8OlUgHx4grSIn5X7iwNSrrhYKtqgpyNo9cVuQ8Q4L6fZucDUQZfCRpMMLM3RMQQhq7zFavV1Zb27+M3XBirGlzkAgzbx8hAK3MBnR+KBKf7uCl05BYmVEkUS/rNuPZqObsQohVSVxJctdpsBe5vxuhvza5wUNtLbBW5XoGbM=,iv:3Cu32rjIGCSxtP7Q9tXHj261nBMHLfJhtcO+ddxyIaM=,tag:JtlgcdI/ooRqloHT0qN+/Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
