jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:26heKJUbRu6YsS2j8cW2e8zRhiH43Y6eAFIDx7/bcm73tj8j0vhJR2neGWKhHr0lrW43,iv:+YX2idaI5pae5guVpcdgnY4+3z7LXAWVxdYpm4GT46o=,tag:ocPnDn6OSyAYkpM/HkkjRQ==,type:str]
                client_secret: ENC[AES256_GCM,data:SohlyLkPu+iYynAlhtTIA9Gk2K9H2b7ELFBOL1iyKOhlkJywIcI6N4jhk6JgeRp4Sxrn9d9z19kjygYLDE6lT+Tw8lu4fttgMZ8YE0TwsZp4xG4L4hk=,iv:6bCo029YmNydGeZFBetUzEJngmDOp1zCNkIGapBBQpk=,tag:NdMqmqha8pp+dr7Gu4Smrw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-12T00:29:37Z"
          enc: CiUA4OM7eGH60nyXL7hsnjGvobidW+A1CvHfmSD4pNGG9w6v2cFeEkgAsHDEl9kO+rSRmqwN/dthT9YRSTwAPBYENy4+nzM0JKyf2B4CdZfmkmWfNtIu0SexggU2wkgFPfB4MBms8AJ2EOtfn6aY10Q=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-12T00:29:38Z"
    mac: ENC[AES256_GCM,data:BI3IrtXo/rQAVcEZjI9/QpwQOhyXkZr87rdAmkTAj4doD8BQepGvHj7jaz+/mUc9QQ4XjiyckYPjiv9PPQal7NZcxUztik8J3exq6jAuLvqB6rZE5RWrqsm85WBf0Rw783GMwy0+pwGH1tpb/zGSS0/QLbCoEINTd6dFfHi+Sj0=,iv:HyU0/FogSBTL0bVMsm1z61Th2e9LanvBPN3K1YpibbU=,tag:wyfCCt4bSv6c+mnajDZx9g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
