jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:Lvdmp760TXBHl+h7diKN2X9NKxDhRCCEG6a6pxfYgwx2F3kx6y84oj/b0KjMoyGHjKKR,iv:H4GrpfCDudBXNCh5K7X5KkxYo2VSeTh7e1Swc06L1Jc=,tag:DkhnQkZTjcaRBKJMELfk4g==,type:str]
        client_secret: ENC[AES256_GCM,data:NaqzvavgtgZ3+02WVdwxHHEqv2gfzA/duB67r5BvK5e6GOuEYOfew0KWVbaJpuAu/VnHbKAzThii4QzukDt1mwtVYyBniMW8bC2Lx2juVi/QhKm7SOQ=,iv:t0LgIyUubY43VYzMecifqqiz9NRNBMOdEZcyeZ/TiG4=,tag:Vxs+dyDtaxrbWi31siCn5g==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:04Z'
    enc: CiUA4OM7ePGzfrhKo4L8Pc7Eb1lo5kZv9aMGjrpjdpSOZ2J1MY+dEkkAsHDElycu+M8iFkCVE2OiT/3iSuqc/1R+C64DfJtgnp6i22VlPyzwUxC5MxqsxiLV/vZNvXdis+0Tv5l4UIsK1VPhzRVWNHSV
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:05Z'
  mac: ENC[AES256_GCM,data:3rY0fO6sB5FPIGEwbdjOeZ91bxessJCYzQZwH078vyjr88+uB9gxZClVhhp5+FiozL6WYpT4fnJd+aonVC2HvXOoGucdvoO2rrBiK7K6+Nn9w/nMX7aiRp2HHKhJmnADdXErQV6PaD1SIuKeN7QgKgOIFF/XZwtRlj3VtLBNcBQ=,iv:xWBAPAAksl2ii0/N6c+uxO+6LX7usEiASqkmdo55EEs=,tag:PYMfydIETuqCDuXWPhlbWQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
