jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:HGE0EbZJgiXaT53S+oycU/VP8gGV8KL6pfdEfhSYG/vyq3Y5PVd7K+o5ml6SkYYo6kMf,iv:EFo8oncqQuwqZ/bthG+WGedxr4OxrfQWiobxs2vw7F8=,tag:3Y94TKMeAbq92kz3FDMFMQ==,type:str]
        client_secret: ENC[AES256_GCM,data:a3vpJUW2Gaqjs4OSDXGoIQTvDAbciVHlaDTSGCsJTi60XpL/SdET8NXAPbdHfCPeaZ3NxkLL4l+7jpZ+ZSfOhI6girykn9UNPYQEJE369Aa8tapDxvo=,iv:yXxQ5HyBdLyNEXUo6rMjDfab3TOhuJkHjd5s8ZSHdqU=,tag:xZ7pF9QmR8CwDyirdG5Pdg==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:RzMKiyQwxbF7HfL/5jNtq8m2qNgcB87yeodoTThG3J9Kn8V5k+kfEVjpwWWHbU00287Q3W9vafcBTgsOYaaQ6g==,iv:qmaiMYheOYaXAqJ0fw8/ZPGM+wn9ougug7kAKRxL4/8=,tag:c45IA/S80qWiX1PiMLl2tQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T14:51:29Z'
    enc: CiUA4OM7eOD8FNag7mSopSTkF5HB94CKSAjnMbXc6s3ft/MY1+UGEkkAsHDEl4vWmAMewThFU+Qn5uceR+w/VYrz8PnPpl+2zMDMUEEzjoJRf4rO2YCJHdX+Xy4n6gJ8rYIVXhAx3t4sSI6V/jP5YxWF
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T14:51:29Z'
  mac: ENC[AES256_GCM,data:RioUBwtojUgLZ9J0UNDw3MlWwWd1Dq4uH7+s14qM+QOO1MEsyJ8cYA2+/k/vuFN+L2bDAHdQGZliKVV6Lt0QI4br7ne2/ynNNdEBBNmWBjD+DcGUpyOeIAxjb4b+Y0NyJvuvvZj4bgwxFPFSPqMzEJZPx/TAJiIQS1WKfkLNwlo=,iv:uwCzk/lM/CJR7I4Z/j+0GNTckxLXUptjQXlsGApiYuE=,tag:eNS4FBKSwruHz773ZY/IUQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
