jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:L53GbGwpFLpD30eaQe9qpWwTiJvGW2zvqcPiQV9rn7WQrQvw8z9w,iv:msn1EPtoO/707zs7H1by7tX2gldGaQroYgyS8GXCK+c=,tag:q0bLM7h8OXMe5rtvjLj9TQ==,type:str]
        client_secret: ENC[AES256_GCM,data:dnr7Dvp5Njeq14q2TlpAZ4wq6pRu+nNkn+y/xEO9yz4xZ1kXpfW3lg==,iv:ksh5rxFpZqdrlRo19YLKZmLloGMTkSasTQfnk1fjxlc=,tag:xynBnHiN1ApHKI21sSpikA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-06-25T19:38:45Z'
    enc: CiUA4OM7eK2++YWtxCfhT9nSqk/p9lSqW8bs0JSTmR1yjNBFzQx0EkkAmy+ekp7LCDErNc/iVJle1hXewolGXxtx9fZT7leIArfrMgKQfgVj58v/j+m0GuNdzES5Tsh/4VNbCPzXHqTJqI9kUjPVTYUo
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-06-25T19:38:46Z'
  mac: ENC[AES256_GCM,data:kNsGitzDBIhLYd5hKhWXPDiwNTvNejIjgdVwMGXsY296RP65Klrev6F2YGber/RXHLLm96RCtk6cXZa0o1SRpxq26bvUmSQDf5vEbNar1o7aj5yfjMyCqNYrGJ+im9L4ek/MNYQr3s6Q84G6L56CL/aA9GrKQwk2HKDWkwBjCpU=,iv:5IhS5oQHpOlSnbodpvRmm0yb4+s/4gOyLk/cUF+VkZo=,tag:cpvtmIgl6W7VLeC9McY6ww==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
