jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:iUqmnygsZoEYuBqbRe+tJ0UbF4dkr6l+qzITU0lujgSygUEF1ZUD/MvmDP1PcWgz5iyb,iv:tNB5m1gPeWf+LxyR/5U5KD18pjFjmkWZ+/Xt+FDIehQ=,tag:2aBDce117CMssNGcbvAKTw==,type:str]
        client_secret: ENC[AES256_GCM,data:Ba0A7/U8NzoofrEE8DoA6JPapAp9/mdsHXkaCofAirIjUAg/4afSKygaZbrsA1Pf0XN5pslC/kQhIWxO+et8aMd5ddo3BMp2JtoPAx/mWgpFaCrg4cs=,iv:5vFw0ba1xrRtUK7wIDsGbT2u8Gj5gW5hdrAjwsLHi7I=,tag:X6HNu0MgV6vLf/+KIyLDtA==,type:str]
sops:
  gcp_kms:
    - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
      created_at: "2026-08-25T16:23:45Z"
      enc: CiUA4OM7eOwrvJXF6RIzWYDONfUhNdgHMR+CiW0aIqhzDTrLL+sWEkkAsHDEl90Roqigz8dLXVCWNqytKeoY6kL220GBaLxPw9qHQiIIbbSiY3i91i2yjZxkXq2CNSz2pQBsfAwqkw09/IWteCsmEIPT
  lastmodified: "2026-08-25T16:23:46Z"
  mac: ENC[AES256_GCM,data:th+lFAK8jEMsPmvpZN9dPfiB2pz6O75SHFUaelmodtNnNEUeSqCS5Q3GeeTvfxYysSiDlRLROpr/ZSuO/+B0yjN+06fW4exqspj496GSCRuxGIZtuJXLibG7fU7QJx50WtTjz20TTjmi47zpL+ULD2ynUHNnjaz2cyE+1vHGKVA=,iv:j88zuei+dlR4/nrz+cfhF7Qfsu1dJFMYIdBQQGfUWV8=,tag:sY2XOpgDATgBpfRX+JMShA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
