jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:9KtQnLEy7SJBbhF9vsXbE5CTFZVd7pkB6w85jDv4wakuOYgMUskctGXtO+pLO8OALQoK,iv:rhDRCAghhA+6L19smwJmM90oVEYZ1RXoZrXx7Ce5BIQ=,tag:2Q2V6vArgSrpUZOn7ZtmYA==,type:str]
        client_secret: ENC[AES256_GCM,data:Otbnog1GTbxv30zO9xPl7XuzRNY4DnOCTjx/arg2J+EojnEDpniXP6GFv68tYfIW+VpzFo8qLM4wY1d8mMR07Mqa9figyEMS8NGwu2LuI2ap2DPb5SQ=,iv:euHD2pwOhQkLdGXuxbYfm4ubGLBQB9ivFMJ0TtDlYQA=,tag:wLAL5PJcNm8ABbz64AO6fw==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:u8lX+JQlFeyGaiImM1D2owRnsnJDNgwE8Nq8BqxUF5uymhcrMhy7OaYpmQhVPkyU5DEgK657TZMw3TxuxeXke9TCbuj5L6F14sjh7fVYY+tdlALnPGg=,iv:/XDugZLoBptT1OCSs+nC0DkdiInaNdSmZFb2DXwAH50=,tag:YQmJwWnEQO8Ibd+MDliSXg==,type:str]
        stringData: ENC[AES256_GCM,data:3v9uTdN8/hH6hJejGqmDELzr5jm6oR/+tOaOOf+2Dt5fI2rrL4U1SgknubFEl1bz5pm1BoLVKguPNLMJ5WTKF07eWOH0CwvhasrTHictemGFToMdEazHF3Zim05gGTctuOxGvgSHP0r7HOZ8W+i0QSMHc8AhowCV3dbijjqMEVTGrPPqh/877eM+oDlLJNUnuGTwmoGAYVDK9/nBl8O+8V/d4qNrQMPXEiEguErx9NmGKTsztuSzhVoKIUaei9FC02clVP1TRgw1xFbo+cVanqJ5xAZTPCm/PgEvOsJDiXZddt4b+kNx2GuZ3n3KLLWtPh29BdHyFZQJS4gFS3ds3bCKsIUlK/0rO8XwDynQypsZ5hoKaDMRvZyPyiw8JQw77+NFr5GQUt875xrvCMfyt6RMuuUJFL1SkofAi3lITRGDuItpU9XqhSK+j5JLnPdYUuRE3sKHJNGfInGt0X6WxhkEfWb+YafPRGBXW2u7j9X86cziyyzSpFpnd//0GS/rsb0X7llUyX5bw0vPBwXMbOf9Q3CXrPFrlWNqXg+CaA3F8979LJYBt6aerJYSe56DibmmVDuZ8Gq8LQpXGVUUA1atgBCe4saw/OCoTfe+HUvXT7KN3H2ucIl7CPYDP0IkRhs2f9aTSMXISJf4lw==,iv:ZM11AA/UAQ3TpoCgO48/65DDHa48EqLC2gn54r709VQ=,tag:Gdb2hud5jLrytYm9E0hxtw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:17:29Z'
    enc: CiUA4OM7eLHPA9fix8CTjzPuSPJcOTzBffm6aqVnoAag6sYLlcR7EkkAmy+ekvHop4/n3vx3tt9ZSI4H9rV0h7+Sl5oC7zEolWWiXIhDdQCHt/PwK8tQFi9QonAkeEN1sFeUU6yW6Wc1GPeNWn1hYMin
  lastmodified: '2026-07-29T19:17:30Z'
  mac: ENC[AES256_GCM,data:4CPSDw0ghAoQ0MJ6qD5NdI/V1KA/8xp5mtI4B91GVcyqnnUpq93IBIwawmoGwubWU6YZSKsCDp6y8jicmph9BBeZa7EvIm+BgQGSRvdCp6l/Iw7u2wMpYu/43uqMEoFLfxhUR76F3T65BBlzFAkhVEzWKeZaBL6XUHjiWVtuyUs=,iv:YamI5jApvGN0Al2Q/0GAIfrG1xbipLwiXCHAcajvSzw=,tag:0xqAIduTMAEye24sc3jjWQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
