jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:J16VmKgoe1LWoMIyaW2Jaq5hBvhsFcrNcZCdXeekPVg8dJ1joL6ADZZusYUXP7JOLzGN,iv:ZBrI+iN76t+tUcEuwE+DhMD3hCFAKI/ZzrGzMIEdKpU=,tag:LaGDQF9dqEx5FkeKe+WkUA==,type:str]
        client_secret: ENC[AES256_GCM,data:kJCUjbsbc08/Jsdh4uuh4+Bg9uW9JyqFrQv2FpuHSzU4Gu10/x5B9qdq6OYFiRB0TCfF0wvrFZuUOwTUaFB07dv5q01WE2++4t5icCyhjLlLpEQvY38=,iv:bCPD8tal6HzTA+lGyy60/HlzGQPHLiqKFW+RScvqiK4=,tag:WIFbPBRrGVC5oBZg6Td7qw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:34Z'
    enc: CiUA4OM7eLcgtjlLznRqmgIc0GNEYizMFcXKkoq1BaIRc0CQ9XqSEkkAsHDEl5Oy/V7Q7oVSaa+BBj168PNiDvrbAiUx0YD2cCVIbcsN24oQmKmdjnT55iWJKgOf5yGs5O+GYCpawVgWw9jqpRb1wRSN
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:35Z'
  mac: ENC[AES256_GCM,data:z1sxLTnfvhAAlCvgh5o4eY7/K+gVZGo/XpYFMFjBFvvc3Dca+G4lPyqF8V+FEwLIBI1swsoOtsnr7q1RzyUpQOpToVN6G3ld1MC3g83Feu2RtQ75ckp1ZR9IGn/M2RijO7ih3ndp8fGhmwNIAY/jYz8GxRUOf7wkdQjwqLeQoOs=,iv:PwfMoulLy/kTO5DN3JU0Om+q4pESegaeDolYGJxVjXQ=,tag:cxzj9FUm2ODrmRjHXJGNpA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
