jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:n0xBP8o6v4WrsOV+1dsU9ha+Qj+as0heHDOFPC59lcQg/jadesCQ6L60nvD1q7sIj7Pw,iv:udbSozeuUAZH1+1jFrp8GUnFxWezDZ4N8saT7t/P68o=,tag:lqZoFJJL4zQp2uCk7u+isw==,type:str]
        client_secret: ENC[AES256_GCM,data:EgfOcyRfkB6e5LXQpJeHAMGFJhzTt5TXYrDKXzh85FM5uBUFs4/6hjT1VPF5fBwStvXvepNmcqMNOlturRXFYmtpnp+NPQLbhVaHE7yfMjUTAOG2OmE=,iv:QwhXnDkNWpWuxqNL6r6XxdeaipYt1D/JGajulEZyxtU=,tag:DJOGYVOO93FPHubH8Mx/mg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:b66s2N7p1HDghkJOP/AgdS04Hh9IeoR13IdN71yKDZWilqlPNKbLmz5/Y+Tsx7mIFj9UKTDypxi4pD/0upd2HZzdJ+4X8mIiuQZT7/rEzd17iunG4dI=,iv:Rq9gPBgatz7ADd2RNwXfqkvi7VLrE6NtaVm/X9FX164=,tag:tMOcXV5Ko+scN7hQLcTwEQ==,type:str]
        stringData: ENC[AES256_GCM,data:qFyK9+L/kiEYEYCAVHPMjoB6SjIbtJ7DqvnSF8RQYVI+iK83aVq7+c/ErMudxrCDZoMdFGbxAxmAO6kx0Y0Bao8wfabRmJl9obJqyQM5JaLnJ4Oxl3Olduc1uKBRp0cMXyQHZkFn5pKwwwLGgJxqmqJdY3R1oxWT+PFvAFDzVz4bGiX30bs9rAjOdeRo04gXPWAood1MbDh8Ghy6hJGnlXGLIPPQhHCkazePWT84RcunRE96SA+Seg479plBUinBmap77obqqIHyRCQG0A98KB5e0OJK/opVqQtmJFM/f8AuBw1WQBxr9Y8zbiQzx7OjJ0Kmt4GenwfmGf5OmhqpFdw9Zh+NpjNswGYX5RZhgnXRsZbbZ61CKQqJVFiGpmUPfOXy4inNgBvC7PPDrffa+usuQSb67hJyxbioKLfM0UFcd8bNQTpXFQFRYihvA+aXe+V0h+9tdQ/h2A7tkcWcwQPLZhIixIECi1ZZ7818MQdRCYhsFTVX2AYroYbrRQ+TR4FUM6UZ4H/MIn4PCUWF8PLh3jYJSc4kR47icSvBn/HJJdOyVNrBeGRWJ6K9qTDRDZeiDIH/ZuZW5Lyk7Mj4Plhcn14jmZrJNGS1ybA6nvCTJ0KLtutL5J1deTUg2mpdQeq3di/oPPjY4/OW1w==,iv:lMWleDZTXgiHBTUnxNX9aICpNjwadW3oP8qfp8xvupo=,tag:qjsnhx4g0JJP1UwwvS1N2g==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:37Z'
    enc: CiUA4OM7eCPjjSiuKP+CzfPy6ejA9PTbQjJQJA76EQWf15KWlJcdEkkAmy+ekpjRkgvJcpmfx7IzUd4vJt5euAg2FO9xj9w3Ida5vGqBi01vyJbvmQ/u/9nwgoysJUSKxN9gLuxQErPqmvDf+Y+VmOaN
  lastmodified: '2026-07-29T19:19:37Z'
  mac: ENC[AES256_GCM,data:7rq3qLHy//noD67CRDmqJ/z10ZDxnaHh7wFu00BjYkel2c1H9PYksIpFkg+jxdCFtumdj1DZYo7e13o6OX7RvMuZSd6a9bsP6u9jnv080oGSswOhf44ZttDeUJBIZ+S1QrgMMEtPBEEgibE+fBPVpMpDVu6PCxhwjc9xIN/TAsA=,iv:DdN0tb9jJhDe9b2tta2xxnXphKAwFH+l8Yj8u06No6o=,tag:kybyHV0nI7Xayb6KN0ZuQg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
