jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:4tw3RU5vCOSQ+JtUCskq2gqzPWroA0D4fASxS3H7oLT5y305KUN/qMmxqRWSgz0cIgU0,iv:xzrHr4vChmtg5K4yTzHnkV+xp8KETHHkEPiXTV++6Jg=,tag:OWzHYSAiF/GfV6eeClb+ag==,type:str]
        client_secret: ENC[AES256_GCM,data:4oRElAnarPYdC7Jht1n+Cttn+cpNAIgzXbSyPRKzvltbAfGzc3KzvhmvVg7L/vdQbF4C4uaejWAKX6fL2Zo/grCdhDPbDBkO8UscZ9VImDPIvYXUpY0=,iv:Zjop2SZgJrgh1o206I6eGZspDv1rmdxvv/w7m1YwBBY=,tag:Rp6oviDYbWIRnmIxmRi8Sg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:EcVG+t3y1swm9H+tZP+WGQoX4BUyPENC9Aw+lwrhZYm1d+CUPRzm0RNO+svdCiVjvB4YAUmvMRmGAm3LcmYFMVbNlKlkOWX/FwrM89p2YD9WPp099iQ=,iv:6BrDW9wzyidCnOJoQQvdGz8TU9GNvj88IKeFppncl7I=,tag:x+eOnKMhlK9BFFCrYtTjYA==,type:str]
        stringData: ENC[AES256_GCM,data:mTC/xsL60fmK3aO7xCUUWXZ7nZM5h1ms0eGyBgFdanlLS6J2ujS2eX6Z0h87vIvQmFuAxEeduPiQEsU0gInVojMm6vLXU+5UFhYPoJlkItyJ2aFrXHSF9eQSCFasf60IcaYa7eYBLFN/cesEYLqrgONWyk1ir4pGh3poWcfAlcLY/xsYL8fKAednGLZK3Ud8u76s3GdTS33U/H8X6/vfbi+B3fb1glIKEkmps15cWWXiVXWn91uI3u3IaJ1CsUzdfuj6yprpipVNH/uDMp9Je8gxfRImB9PpxM0XkoVnVU3ifxzmOAAXLyAHwkdnXjSQwoXrzp/siy9y0fyDxk29lun8qbAPKUs2rydo4FXeEqC/3Mk7HEcSC5JJJkC8QnKcCIV4sIz8jKOl1RBmfSLF5JtADCfwp+tkGFJcJFc7EOIChiP4Mbe7Kq3w//3AnD6qSq2DhPHok0RLOAU+XjoOzMIdWUmLeRdFNldNaaKrXOrz6E/NVz6OeteUGozZdfRq0jstKyb4et68Y8ZQB47L0YnkCApvfHo6nN2aqUj4W7hCoKwWcOJbS9OvWTgEjxhx8iqxM6erxPUmJir1kilLJVzPbBJR7/3kuR6NxqbCxVLEApQuPisQvOKKiOVKFkWWtjGLTNG8IcJ0Yo/8Cg==,iv:nKAhWqogwoH50hUKU5LhBcsNNNgTF6ANooaalzydnbg=,tag:607oDQOb2Z5PO8dU6RLDuA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:20:03Z'
    enc: CiUA4OM7eLSJeZ5pv+JtldMdjM63lZsxgRH1JKGHV2a0ldrJBz3VEkkAmy+ekvpalxemTG24Gth0oIz6RFA8LwOOjYQ3COZ5UCi48WgdUxX2Qd2ZMckJjVcjhwqGSi2AQ45vPYds0zo3im/5IzejvGFO
  lastmodified: '2026-07-29T19:20:03Z'
  mac: ENC[AES256_GCM,data:83O8SxS4IrJFToL1ypWDPlxsAojE9OEj1ISBXfcrT2FIQY18jfftPL0IBhlEepgFFlEkbZR/1zVV5MEGZ62WS5hwR5YDoiNMKkgGWi/+wLcbzU5sVboMjziOx8RDPjWQvaNreyFHEaeQJGhqfflbF9Hu/jQr2EoVCOvvamhSbOQ=,iv:zllwESwlQ65q4KOn8Scfu6JQGdTiEGn+kc+fC8MYp4k=,tag:qM+qkT06bxNjjpIhDuG4ag==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
