jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:HnODjKDXVVXEX/4Th3AhgE4ZArlM8HAlilCxPy+qwa9WLZOSXCCUfxwvWX4PQLS9+C/t,iv:hSuqfK10vGB6smZcvnSC2FxfElR1hqYHrH7ExMIWHo8=,tag:zChPiwrm1j0x1WRgkBydxQ==,type:str]
                client_secret: ENC[AES256_GCM,data:35pRCgFpn7/vqI+pxXVR1Y6f0iZwo8Jpu9FGwJBYj41FoopAFtCJDWXVXGNOzKgyETeF1vqSqgt8GU13xLsFLmGBum/pdR2tw92WpLo1uzK4qNqNS+s=,iv:vwfTPB/hspHbhb+oVtUWogjhvZY0Xy2NFiOT5eSVg2A=,tag:59HdqhotGA1p5/8jP9e32w==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:50Z"
          enc: CiUA4OM7eHmfQwlHkwQINRjdfa6UcAZ7xiHYCactOSEU4MVEHl7NEkkAsHDEl3PGeXpod2WpdZDvUbN+9jvf8695xetIrpZ1dOzI2zsWVkYjBrBmKZh0HEqS14rWM1vEhIpk4IB6DPXuHLx5jgeP+5vj
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:51Z"
    mac: ENC[AES256_GCM,data:nljwiP5zDYZo0SyAy/0xM1Wy84W3X8KiSAnrvaTxfJw2eJUMnAToywr/oCWChZS8M7eky9sAssLRAJI0d2VjCTlbJS/M19I+1H9hEpy52hQ/zXuZLk/PDJDpGv95XBfj7VgO0I92P/JJmsLmb6rhLclt6PSwwElo75OyW4S+nzU=,iv:aya8ZVNXa+hFxUFgNzIX3p4OUpW6Js8ketLl72a8+Nk=,tag:hWmSjh4oAIpirmem4nYCpQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
