jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:/L1TggyYhqxl5lmGbuYXlsoVX99Hg16Wq1lycDLlpomflbh4z8QN9OjObLt3PMsKgatd,iv:m/o2dK4R10K5huW4noK86xjhEur33FOqBWTczDKT0uQ=,tag:qCJSISEhkQDJa6PR5Io0rg==,type:str]
        client_secret: ENC[AES256_GCM,data:Ujo0AJwsTtSZA60KVCLCmJrJC2xKSeJ53ffCP6NTq+XKY4PDvC4eJOZ3q0cchvKULEZ9KXLEtsgj5F/yILUTjKjiZFe82YW7Yp8MHZWBTeFa0Tc659c=,iv:08OlUIA7E21NVb+NLwgVedrUqxEOa0JnPVZQyz913L8=,tag:qch8ZntqTMC2yaXSs38fhA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:48:01Z'
    enc: CiUA4OM7eJXr0Xi/eqxERblyCBpFvdkEOSKbthqywb1Mf+bOGMh5EkkAsHDEl0VjFaGmmVNarrbO+DkWeskqRBcEyNP4UOnTSgu/tnwP/lAWIrw1uyfInTlKwc0q/4B2BMsXFu8Cy64wvpYySLvBDmbC
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:48:02Z'
  mac: ENC[AES256_GCM,data:dMrq64tprarU1KGuMNOKQodUb7HxAS9IO7WdWTi1TeR3/9g20rmkfZA4PtRZq1v3+1w/2XW82MJuSiUb18taWEYyGo+beuTaghZILkpXnSPNpwJ0zEaqKPLsQAE4atLVwzJAAuYo2+LNNRlEmrVoJ3ESrAOWa3r+N92EKAzaJMY=,iv:hqm9hOhDj4/zRbV6BzFN/kruDGy/6Mx9puFgLbOHgV4=,tag:C1uNSb7xxTHgDMPQRYSCIQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
