jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:XhgRpS1zniXUYiDMh/oNE/kqbw/ywq4hgET7fM77U0lHE+N55J2QjTVPBTFddtX/BOzP,iv:PgTS5590vxH4540UQuwJQC0hP485mhjDx7fkcT2B0qM=,tag:sEVMtmqdippUqtgfv5UelQ==,type:str]
        client_secret: ENC[AES256_GCM,data:IpkuhkYukE1PlFsvUZ5d32ffLedZHSMXRX+aoN33upnqEkY1jUvIs4qngXJfoeo/uRiRaCMLm2hhsfyOwBqOmaVanxIgcya9NtfJizkFx/AbWBAAQpM=,iv:0ZTANqNPIT3vOiCVsenxM7+HU0VUNO7sD/I4djYxHME=,tag:U1MTILxAQ1beuiPcHnCjAg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:17Z'
    enc: CiUA4OM7eNLj9xOBLHnWwSW90V0FrzWuvgidUDuH5b5tcrkL8w+iEkkAsHDEl9DfbW3EIaqovN+QpF+nv1VKX7T1NiZpJZnDwGosFA7uBRKilEJHRrjL2iIsAJbftdPgQrqA5VWs4lbhP1ItvTWw7a1V
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:18Z'
  mac: ENC[AES256_GCM,data:jJpKgSFRsJV43ubk0P5gPmm0GJrhpp68ppXQQPM887oy/XrpPlQYUX78e7kte3bfa/mgNsudF/RN0Nvpbg4kBBH+7/faV6Ad+1sqWg+cLsrVu3UNEy2becF1NHRJRQObMkxLuMoU4/CQHAVmE9QLOXG0/gQaPR+DpKDGC5/RHEs=,iv:k9iPggxUcPZ8Zsk0lfqDkdBpbZoown6af5FdqA5StQ4=,tag:SshXdOGcZr4Qng+2gzALXA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
