jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:A7+v8bPJ3cQHnBeiOIBMCp0MAtWyBJddN/42yvrjNKEDOwYbw4dk/MtJbHDijiKTx+M=,iv:Ekn9vYQOxeHyyexe2xA9iNdA0/AfLxxfu8uh0vRlYUU=,tag:lJGwF9ouJ85Kjuf+McYbzw==,type:str]
                client_secret: ENC[AES256_GCM,data:VV4+hsVcqVD30Oiawa9C6zaPP4ThkpD/6jj5jFoMcTCfzNzzkpgvQkQjWKS/bXsf7qn89iccNIL7MDDBLfVLkoyi02HTlIJiwpxQQni+10BYKSGuPLw=,iv:ouqR7zd0YCUunkFzz67VXk7fnA0kBpPfVMGN9J1hoy4=,tag:loo1SpvbrRe+nF6iE6XJHQ==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:Whe2eJIJsozWaU0HqX5ZJpxc2aSEGc4+fksT+GfjGVbJh56KOsG72smOlEbYVuzhiE8p8P/srMvNUxo5dF+mLg==,iv:u6NripgDleYXyLV/Dgrpr6zYXlY02wiCEN8JMJZ1hog=,tag:dbWwknJb8tR5iW6dGK41pw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:18:53Z"
          enc: CiUA4OM7eIzOvfPyvN7RfjxbB5ySrueAW/5tPRheor/vLSM0hd6KEkkAsHDElxlL7Y93VhJkGYyWynA63SGjKOJrh7RuDiEJedipdmHbG/pCjLzYrKgZNkgF7jV+eHVLCDJPXWa3cQYswyHg80eQmtxH
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:18:54Z"
    mac: ENC[AES256_GCM,data:XY+r40jEytoewGaPGqeKDClr40/REd4Ztko3QDtDzWh+K4V+wmdBgFYeTUjVPYcKZhPUL1jSn2e/krEfX8xywwIBGo9UWc1BtpKzCwZXLzjM/iJRpVwobUW+wpudsjp7KqzQmdMCNIobbL+sw++bFEJyh/Inztg8TxwzFxubhG0=,iv:MoGt8XQmZDAeDjww9Zdq8ZFFit/GhXYi9dUN1zQ2P+w=,tag:p9LEsUfWb0ZhPVaxIW92YQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
