jupyterhub:
  hub:
    config:
      GoogleOAuthenticator:
        client_id: ENC[AES256_GCM,data:D44NJLZB+HEmAGEtHoZqJUXJltdZ1PzEbCCSl7jsXaBVaX0ZOm5oSk5pF6Vkj/NHbqDKX36WWweqq0f7WnqJJNTL1nMXrkL+,iv:M80nyNuw20LpHiuQDZAZUBpsvT+HbZmlVg6x4BkY6Ww=,tag:Mauw/B74bDA4cHvK/lMV9Q==,type:str]
        client_secret: ENC[AES256_GCM,data:xTAN6YRa+VdS5E/QcnCGILszNYxEgvrUK+J8GW4fWrdCsdg=,iv:ObRIktxGoD2q7AjdkJrE1p+6I/E9LX3mCQSdn3JcGMU=,tag:Xu/KQk9xoQSg4G6m5huSDQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-01T23:41:23Z'
    enc: CiUA4OM7eAQBxazbeCKoIJ5WJ6Pw0CINWNQJkGU6036x7mJluLt/EkkAmy+eksmarxQ/GXv4oATr+bKB+AxslWe8OX98Y56EwSTFw73oWhrFftg9yjLh5W0ojdj1WPWmKyMklvJICOQ2nOlndOM+/YVu
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-07-01T23:41:24Z'
  mac: ENC[AES256_GCM,data:v7CAJYgaVcEKRdnv6BZ7/t/w9lfdQUU6lgIGDMt0LePNOnOI09pZc7lIUVgnh5n0Q6eizS4Ty4yRsi+wOAxlZU69MafJHFFfqz0Ld71alZdFE0iRy+A/ZF/ywltk1cBj56eJQ/1mN1PWWj/hl5w0J3Oy2CV0R9tByjS7OkT0fH0=,iv:vGYGGFt1JAKJWsuQKcDwAcC20DzOopU8Rv8unObYThA=,tag:Xdjc7vK9imifLAhSL7UN+Q==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
