jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:zqNAshVqnENqckBRLXXeNHw0wduvYNQwkBJx0av0ww1nrxVwlJwVTXEdBV4GHrIn6gNc,iv:l/17+hvR5kNJQCkz9c2f9HHsJ29/XZMUkpnDL8DJq6Y=,tag:d7xHUEVbWR2kLn2IkK/J+g==,type:str]
                client_secret: ENC[AES256_GCM,data:1EYOqdMMs1iVne8AeCIIs+kBePI6bj81I+M1wVBa5CRehLRvFtd2FtfUxJfBDVZJae9Ci0un2G/PBPF32so1fvAcqpuaONoU0ojzeA7m3zWbVasfJL8=,iv:TFjQH1xTkVohrsNORhyTQ4LAVVvXxPUj7LanHv/jdWA=,tag:yA9DuzO5m2bweuayqwLecg==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:KS0phCX9m++sRoD/orMTPfyCMbOkUtuV5rsHfh/q1r8h/wQQ/uyK2cLwQThJqyAtmc7n8OyBQhcyDAInweJVoA==,iv:kx8VHzoqc3th1OOPrN/710jUna76/BKMs8ovVC+BBjg=,tag:+W+0LWFZ7dkP9tB5pDvdUw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:18:13Z"
          enc: CiUA4OM7eDyPGe5DUJRqI4ZL1piDrAE61mf+n+S80N4A/QyHVhaLEkkAsHDEl8uW4LjyxKcxXr2ErpgcB5iQzz0UKxzW+76Tm8CRTwLNPDB6Bj81fUVSju07D7EV7+tbjGKWC6G1LE0Gk7pkV+bhqCIN
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:18:13Z"
    mac: ENC[AES256_GCM,data:3Y5ZbMZZST0QCLr4kI+IFlFxeGWI1W97/1KwLYnHzDzHPcA8A0I84EUnTEKXdViMzHST6tcAaBuPFt8QDT1BtvVCf8v94o0d8XNsYFRArv9aJD1yLCKgNNNxTAtuGtkRsVCSoir4k/vjZA+nGqotUogFuIOHJcL1IkGq+fqy/Ng=,iv:F0eyjdJ+RtuOTR6QMvCHYoIVhgNj0dD8ua/mt7/82FE=,tag:dRvs4KEPyb2tnTne/ho+Ag==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
