jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:pPsNGcgm9/+3u+Rv3cI6O9sM119Y0rPsnl3t2ZiMvjep54Nu/WGUjeGQ/uiokMzvgK0/,iv:IyNR+e21dhGZWcVKF7rVm4hwSPaHGO4zDvn1nswwnfU=,tag:/5JhF2AJZD7LGp75UCHApA==,type:str]
                client_secret: ENC[AES256_GCM,data:HpYhJGTLYWGExgNL9WBbL6aspjKbZba8jbL4kRtGPeuDiVGzP7FDL6SOn6LrCK3S+xBTKmPnGZ84z6cvHdtIud6ceU8XntS0NCaTc7Q2hGRJ84A+T4s=,iv:TUfE7SCXLqmPUFfbk9oks6DqeZrVggumt0nryZSllgQ=,tag:j1CtlqjZiT6p76addpIRVw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:51Z"
          enc: CiUA4OM7eJ/+CVerKOjOX+HcsgxdTQXLpKM+pWqz/kZWTR3YmCSfEkkAsHDEl87itiq16t67A7BshTFHFAuvwoyhzMksxtfvlof10ccUCIklZGrMUoFNaJnaZuXC0cqArh+jphYcQq2UdoF6flOd2m5a
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:52Z"
    mac: ENC[AES256_GCM,data:JWVmOH17aynJ/TCnA38YHemdqvsRTh1gBlID2pfgcIyUKBZ4XJ6z2ltvGQNF6XJjaTrItiI38b/PvlLWWVg3oAAwM2GndhgOblmg35WB3eMH/de5JZjBtJOTa8jLEF8sgQUIw0vAHiPZb9eBmMwliXXdS+x0lmfhnuU5Sb3yJu4=,iv:9vyqxCARAM4/CIYwSWqHjA3mi6tEYfjrIgJ8EghmaJ4=,tag:yGqG7MtsBULimQdE8ACJcg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
