jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:qfRqT0QBXhPTV8G5DJKmEdFIXx1FqSX3RBrtPIq7sqxhwikLONJjsUo5MafD/Ci3KiU7,iv:HOqvBOVK7qfc3wTim7PVQqZ97sbHnhBJuiAE4QuAi88=,tag:+ILN845VeYJbMcH5YHk52w==,type:str]
                client_secret: ENC[AES256_GCM,data:ZxhpqWwYC8zZtUHDJw1+A7L5nxUgVIeEtzJ3f+eof4sFSCUJC8A7jo6k5Xhvu/5MrTWHVzlvcY2wQtUhUetjyOshsRzm2qIxw70ezSsLgu/trfUssPQ=,iv:4pquLCRFlMR/Ztm+U26u/JEZNtotFgzbmSEg9FzUkH0=,tag:cSh3NM5agtNiLvgANTbQ6w==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-06-23T23:08:48Z"
          enc: CiUA4OM7eNVTynEzOBxUh8CfCTkKFGrFsNMMRJtFGyA9GX+enDtQEkkAmy+ektAvk96JqGmGYx5fvhK6tbVlUf4qB4QXDPsjc0sBLCarUqCOAydQYlYX3VkwVTJ0ibsHZFop6+Grl9PY2fID8HqSLFR3
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-23T23:08:49Z"
    mac: ENC[AES256_GCM,data:c3wiwg6/3H0B8M72DPIBchbgm/QkiqeRHadcqnJkgsIuyQf/PrK9KmBbMFYndNdNWT20rgU9nDyFkzWjm3ghUWAQFTznPDtCqGm8R0fVyRCcoWjwA5i9HMI6sD/TTEFlvDTVaPDsXX+2++7aJ2rwqT3ksDeEaDxzOzN3zn0a1Gs=,iv:rvRL3DRXTy1DhT/qOuuVuhpaejOUbk5Bk0r72TL1t30=,tag:cKmO9Cbx5Hc4AU93Wm/AnA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
