jupyterhub:
  hub:
    config:
      GoogleOAuthenticator:
        client_id: ENC[AES256_GCM,data:lCfwXVKQzEMOJewW+j1RfBeFyjzOnwh/Kk7ny51GxAW55jvBJCYF4yXa0Qjj3VLWGzcKbjpNgrgCiPHEzQMgFBfXXBauA9Zq,iv:83h3Eyn6cU7JN3lOqSXVF86W9MLCBFwOn4wXIFY1YYA=,tag:aslUt/MB8OPY7o3/hT23CQ==,type:str]
        client_secret: ENC[AES256_GCM,data:unFfHsvkVWrSvy59x24bfDeXKNcMTb1E1ViUnDSb6umGd5k=,iv:Fw9cU65h2oX9PHrfgPpaCQiPfARRBakI34WpZS+sGNk=,tag:DvGsQMceTSm9oUDZRcqXBA==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:JizJNyJimMIAlPDwK0dIhGVM6fvwjzDaqsUS5MDxijrIO5A8DyxsoIMeYFZy9BmJcxvuuqrG5dxmfB01ijnF5eKzQxaYu3QT0up1JZnUGYOsFVlr4ig=,iv:o7jZ8W2ICxJH4NKf4cnCA5fqRcizXGa6ZizwyYFQaz8=,tag:MPYi+uMwG/61fjVlQNZ3QA==,type:str]
        stringData: ENC[AES256_GCM,data:O2OvwHuykaBZe/dSrhpuU22pfi3wd6VoVv/wjud/M4e8eXmdjgXsYQ2BygGtw1bywihZ+PUL/B4tcYgh/JqkqHmR6z2NYKdbLf5k7nDsEuNy5cFVT6K0BRm/rTNEaLIv0WoVtzoZ4aNbA1f5aLf9DbVR9B9efz8thbtpm5ZNdfyLS489y7rNNExgRb39Ia1Ea4Ps04qX40tGp2yWDL7gI8N2FOIBxx/6Eikgs/ZqhUhHdJ1IzcaZ9kOFandqVof0DplRZbYS0HIarH39Kmbhke5se5KMbUHeE8euKjU1YsjuslCNjkHKGxnX8U1tWYCap1bg9g6BlmqI3uJRgq7vfBfgiZQEWt2nPwpPImynEIoLgZF2aD9otqDTSOovtLj79C9hF+ZcanUe6r/8xmOvXcbQkl2T9lr05m/TrdqUeZai3SWl67AfO3CiNLV9Zv7fbJM85G8TQM8eZG7L3y2cMyO/LjUMYYKRl7UJK1kidbXCiUQn8TcaZY1iRJzLAEjqVktYk6GwvGo5JSdGbj6LC8pOO5SSbp8q7f54+MB1pUf09TKqQ3hTXS73Q+Ak5vGC/nEzJLsnLaM0XFFT5YPYce/90aEO3O8O4QNULIBp8wgVkZXneHvFRwtAXNpqCQluT3WduYQzt6rup6MZHQ==,iv:u4eDtEqq9GgmUMfGKBUX8XHJT7AFLywTN3ShucxrVPA=,tag:8j4p/BadnHq43qIMPkpN8Q==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:17:38Z'
    enc: CiUA4OM7ePGCW+9pi12ULz7DbcnZY4uJ/Febpbj8A4SYPdg2t+ZXEkkAmy+eknRjGmAlAIdkAfs1nLVWKlC/S6Ri/PbC+VMvIKE7TpkUO92vvcA9cbTAacyYBULxlVKzJNBjT4JM1DTfjigKN5A3S5C2
  lastmodified: '2026-07-29T19:17:38Z'
  mac: ENC[AES256_GCM,data:yZInK1dzD055lmq7CMaBjmtp8HQwSXIx1nYRhJm5ZDBqnZrsgCS8ZJkzjEMtTkwSwdQwFF0TodbfFqmlTAHQtAsydeE82g9pBAqLdC1c4kuuKs1qIUxZAHSsThrRelqMkNnLJGqM3bHM+/FE5gAvZ9hqSRjA7fJ6+67WkXx5h+g=,iv:mcQUf3g5PeVnf7i6BuREvprj2P67r465p9pu1yVlQz4=,tag:ZaPtWgzSCm3WwpGeUI5U3w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
