jupyterhub:
  hub:
    config:
      GoogleOAuthenticator:
        client_id: ENC[AES256_GCM,data:5osv9o+FRWWZnU0i7QD10dZxZTaCWpC6tG3tLB5nsfwcGMPcOuTFlnd97DwwJ4CuGV2JF++cssscSU6WwflA42CBe5V0ZCQA,iv:5QKTjs8PgRpU8N/JMlxvmujDCFuw5WGBAO+J3g3mFL0=,tag:QBKiREL1o2gf2tL6127IKw==,type:str]
        client_secret: ENC[AES256_GCM,data:mmQBJBl/s+jnOrLdvWCW2gb/H6YBUiZuOJwgpG+xPNcoZ2k=,iv:yykQHH8o3Fl42IFub3U71WQ1ejyl+HzPj6PvN7GumKw=,tag:savDYcNmEvbnCGUHtK2sEQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:03Z'
    enc: CiUA4OM7eA99ux86F5DjkRduG4+tiy/54rpj3QvSAklt7YtmK4m6EkkAsHDEl7ateX0kEOKhhrmFFvuFiJQSG99I5z40VVGf2bag9nm44GzRsAZcDA2ABTe22ewx4bKW1MS6x1s9XedlYAAwydaWoOmt
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:04Z'
  mac: ENC[AES256_GCM,data:j3VH3eh4bYcotuxoLv3xyj/rQb7XXwE8cz7NHodQmcyr7nv2QomrLuOH8bErN9TlL43hmnUtUUINMUr0R9G/AvFlRyV8myWqjctMHWOTulVQ1bnKosFCLS17j3wUUnMhrv+WSTIdob5MumU98RuNHOn2Hh6b+azMPpaYVDRmVzQ=,iv:pKloOMbhcUXq7zV5IKcr+iAcvmOWUotMUpGGme1XKCs=,tag:NOTtYb3UWR/DQTDir3gMyQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
