jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:h4/bo55w6PF1raT+7ruTrYei71WlD9DcEtm1nRgPsM0zUeNqlaAA1PQQZh+w/HbwLZxO,iv:udl4+NwPCacBVkuSYZDVYf3pWuK/sT4f4H5mthBV6E0=,tag:mqsWYWRxGXmWKLrBiU0nhQ==,type:str]
                client_secret: ENC[AES256_GCM,data:MI8mFaWtmM4rSHAaF0+Pd760bN+zyR1P/MoUabxOPaVTTZKKMQt+u6LujczFD+RlrGwmLuFLNZ3yIBrmeqCLKFnTEzarfuQP4yFB7EHVTHB4bWsY6+w=,iv:+i8DtwK9OoHco8UphU9pzXRe0X6IaIKc6OK0nA/cCnQ=,tag:6wGktfIvULiPNRypV1pqTA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-07-01T15:56:25Z"
          enc: CiUA4OM7eFLExmZwt3tiXLutmu6pm6LmieaY+UJClsaPpLiifvTXEkkAmy+ektx7CzEsqvzhyLkXdv//xu9Sk9nPwrPtRVmxMtTLeUZODbEFTQrTGVKXD4KD7pvhnMtPKovwQb1HaNtDsSm75sEFRHse
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-01T15:56:26Z"
    mac: ENC[AES256_GCM,data:gSBjIgiaLDmr+WGxuTlcVjfw1sfwU0KrdjIO2KhVklZ/KbD+azPBSNqdKfe+Y0l+OwDgVLwFm48ivj1ZPoY86e/cR5SnB0GOEObpLUTjPz5SwE9JEAwgaoNJonSvDisoOmDZe74N0RnqxiUN7+nQdxVoP/F8nvUX5Eo6bsqlx+I=,iv:FDDcugMvK8NhQoBjX95v+u0cepQvCqddOWXxFBYWzBY=,tag:4bwm/c9IBx08+K+7cFM8Ng==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
