jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:ZlxbWQS5SNsFNZdJ6y772H4ABpMw7r4Zxf/TH9jWF3t1I9671cZQXE4h3auDQ6PydnaEkWfLDmsNHOn4C3aQVp2WmjafmiyM,iv:W9bPj5SVpKpnxTepbSlJ+X6hphv9IF/aOfsQkS1hbr4=,tag:qeubyL6U5tg/O3TDeNJ6xQ==,type:str]
                client_secret: ENC[AES256_GCM,data:iz9sTzQcMKeqDeQVNcI4IQ1HF6z9omYHzgATVEaJlJITeq4=,iv:OCP/S8NQ/LNaeY0sfGfz6pjcVCM9S9JOqt8qCeux7eo=,tag:q1F+ud6XXmQX59+HZj2oJQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-07-01T23:41:21Z"
          enc: CiUA4OM7eMvUNBRrXSVMDDXTC1d7t3xexfIFZxNJ3Pt2uk3h5mnwEkkAmy+eklDdHdKH67W7mndprso1Lo4ukEdD1LFkUF6gFcHptA3zJkfsZ6ZkZvhvg5rOmbm9Z4pdrSQvfQYBuVJx0p7FFSFhxqUH
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-01T23:41:22Z"
    mac: ENC[AES256_GCM,data:Qc2OOcu9xtFQde53gz4bGpw54ZCV6lzMDIuxAn25cxlKbiB36pqICbngYc+BO6FlcSrUiyozHpgfXpB3f+bCK82Bf17Wku4c6CG+QMZftwdjYgoZcbCONQxtzmRAm9A77R8slMa627y8UBn1CQNLpxdbmRNHEgqxbL/n3WaskHQ=,iv:9AyAR5G8PwAl9zi46yxzyPZuSmLuG015GG+Bmj9FYsc=,tag:A/Rqg0RKxzIIDnKRW8tRoA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
