jupyterhub:
  hub:
    config:
      GoogleOAuthenticator:
        client_id: ENC[AES256_GCM,data:QR9PQrxnZCoQN+CapSNPzY48zylyUD+MSrxm5KRMDjL0RMRCv2cAl/LfSgO3KOUMuNVVJFp1QcverPgYYhM9aVexX0TngGKB,iv:57PxoVGIyMCRDoDscn3DYc01faxyAi+2U+FgnkSamhs=,tag:dGUehUK97ov8c7oapTR1qA==,type:str]
        client_secret: ENC[AES256_GCM,data:GYJFZQEkaib0Lz4VZpbdI2HCXIeWy6xqiqw8NcCqZ+zBUuE=,iv:dwSTHN7J2vUKL9q/NbriGzhlU6Y/ogaj2NDXcBqNBtc=,tag:0Rs/UYpxPM6YQQWkGDSvhg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:xLajpFmutHDm3deD4CJ5V8MVrm/DWpQwlr1EkUJT8IoiZdD8Gy99QWg0Q4/qL0Xr+H1IvZEI3X19C+BL5YtVpGBoedmRJrz7xM97ZmifKO38p14RkqY=,iv:T+6WkQs2PDe3SpAVchSuGUTRYcdA4Hyte3UEORHunfE=,tag:H5L8RtT297PU3hijk6Bx2A==,type:str]
        stringData: ENC[AES256_GCM,data:UyNJ3CWmu80Ugi+02/4VgIMfH6tlC9W79/iep8LgxQtDMbFWjaUmnOJzb2rf+F2EbmNOF1XmjXKHmGjIUJcyUHCdf+nr/zWSBfiACWPXg6ytxoSdmiCt/7srJHMj1H+a90UF9yjJs1vefxHkIa9uNSbD2xv8Dze51eHuFVUUM7dvYladO0/TzVN8bLJpfe04ruZUmQDyEMJm/R59sxPq0LoISknwIGbzPSlPQUxQzdCQyah+wSlH7CgK7qILazF1uF7IpUj36LjMmNzJTuab/Ckz/1C/6BUsKrVEniFgS8A1H4YepQspUQRhvv0IeGPjDnAejWnUUrUNm5sBHHSalaf6mzpTs2h270PS0hczrG5IFWV+tqu0Je6G2NcbHAQm3As29hNQr8TZTmc7iR4GzGoN5ggWSkngkohSbdppWrVJ+zKgxUiFvqkpRmEHvs03L+B66KODojT7OiQjK10+R0IYHC3p510d3oYoqkQAzPSOQTusmxB3DCMqol6QW6cvd1TcnKuvacKtcTwHf17znHhHteSb1OFYL9h/d5sEtYogEh9HXU7C60LEMc175Dn5n6lZBVrjJkPNYjgRrhclraMy1mwf5SC3jFMLUch8dbxw6hqo5dgKcEbfj9FIbeRPNfjdc7gWuryGKpxRHQ==,iv:HIlIDZVvIQBNIp6EvyD8rA0mkwBXtaXsDdRe1fu3aGU=,tag:SyGaiwfx6k9/qfXoX9KRSQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:17:54Z'
    enc: CiUA4OM7eNvtebn6tI1widVGikqPvqdrgOifkj/wSrZfQrXuubZTEkkAmy+eksj73CFP7JcZ4g3K7csQbdR7w7AcgebOQnyv15c2rcH2sr6YLTMdJtFJGtI0u0S75vBvATs76798PtoqnqsWmL3M28RF
  lastmodified: '2026-07-29T19:17:54Z'
  mac: ENC[AES256_GCM,data:khVHGh73IojNKKPcz8e9YBEdEtopm8mo/4y2JQOBl3skPrOMjdm+NZ9rNqNk00Thc0E0geaPe9oE0fP+pbPkXAa6r1QxfTRo3U8cmtsZPuAsrs/N8OnjQipKnGsnh+9jXoGaR0CbAOIP/dlr7oAZO6o6eNFlHvh6Mi5Dc40x540=,iv:MP8JlMhwlkWv3jwLpzEy8/mPOWzGg11OGuyq/csAplQ=,tag:6m6tJ1lu4k0u1K7LvkPJGA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
