jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:et0ffu7u1f/4qRhb5qVOPiqFWyXeFXF/cOdMzUTx8AqCa9wc86fP5sPxBGUHgIB8gly4,iv:r4dtHhSj1rrcttvVDYY0rVFkWfdCazpuSu7eANzKYSs=,tag:ZfudtyA/gA+zXHmIZbtVOA==,type:str]
        client_secret: ENC[AES256_GCM,data:maFkO7K60TqD7uk2Fzql+5fGwnWi3ssSq/mSu8eNvPTViTPS6uefm9peyu5LE7LxGQf0L51llXo9+imWx78jtx9vlSGFO9mwFicd7BM+6q5MWyvalOM=,iv:dBi+a9jmjsapBvjL+LUJ+vW3wKYVDe6e65Cst5eJ4xI=,tag:aWPX8LFnKCcAdjCA2QWOJg==,type:str]
      SharedPasswordAuthenticator:
        user_password: ENC[AES256_GCM,data:OwvaI4E4et/Ng3sf1g==,iv:B2znxg1eu3jGfpHkupaLR6O1hKshs0kyNgLzF85V/Co=,tag:phBi6dSwpxQxKo2GlWf3XQ==,type:str]
        admin_password: ENC[AES256_GCM,data:BVF0OXP3xthLWaDLigud5bw03P3i3NWEJ9EstHInV/D85CbICiF4ng==,iv:ZS8gUeT7gy3lRQN42jvUPTZnFzp1fS4bYO7d2J+7qxg=,tag:P2GyCsHSFokbluCdbA8sfQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-09-17T01:40:24Z'
    enc: CiUA4OM7eIS9DiTpIEfErE4pCYQdAHaJn48pgAYpEPPs6ZIS9C9PEkkAsHDEl8T3u1vXpOxEPnpOKWdXsTcda1AZQJ2s/Yd1y6YUzb5LUbJK8zlfq/eiCLfbRAtY2VyAtxqzBhLD0OYy0h4ERjkyBc5v
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-09-17T01:40:25Z'
  mac: ENC[AES256_GCM,data:hslqzhCzebL4rak7NkeEKrq4zr8jsF36eTbDHEXeNPMIgerEph74I12IdT27iFEtT0aNJDGSR3OpMy9um2qcj5XaG8+nwwFw3YH7nnXzzJCpRjTKOBCgstEptbmOhU52Qpzxi5lDeCEbF/EQZF3+7CIE3DyBRz9WSnFEx+h3QM8=,iv:Uh5ZAnGnmcz9PDymJeEPeGgBQXQgi6GUt/kz2Ui7AyM=,tag:kOM505Dull1sm0FZL2QDHg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
