jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:N2xZ6aswCJLIzwVMzEziRGibBCWkVE/cK2pmhsyYu82nRbsoGCMTiSYtteXvfPnei538,iv:5wWV9BmbCABhUdaqinR/GeHn3gcgic0/8cVovgsxMxA=,tag:6z7Jhahh57+bMtDh9aiJww==,type:str]
                client_secret: ENC[AES256_GCM,data:0TiK53Q3uVzOX1a1BgHD007b4usYObRls/EXR98p9gQQ7ENW8wdqNTyPpW32KvqzNeOUeJkeTn9wACL9MO2Y7t/sGY7mLTDsoIbjC/Eu+M5sbOlQldw=,iv:gZkGqRbeRyHUg9AdcQvUbHoYUrKVvj3fJhHiMxYE7GM=,tag:y2YN5V/NsdCACfSG7WfUMw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-06-24T18:46:27Z"
          enc: CiUA4OM7eFuvwDBDyk8/eshteevR0Nk7tEvKEnvhOjhamK1u37z9EkgAmy+ekknpJaPKBuTBR9XYEzt9f/lEvmY8TiE4IizC84FZu3/ADebl3EkbNmzdAmlE/pKA7P2O5UG0xF4M0vc2en8S3Ic+4XI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-24T18:46:28Z"
    mac: ENC[AES256_GCM,data:23U3o0wexMVts3FHSi8ZvTKO1AIg+Die09bOzRcLQRCocDRMNF+NhWiV2zA2wMh/neFh/RMQJckk2c5xBuIEjsfnUD0/NpqIbr7g9XDSH4ZJIUKm3nfIXxfgJSGE1JPCT/8a/F0HpIwaiakbL4ZOziRSV+TA2NfGP+9/jZTQypE=,iv:XipyCUIMGXwKFK4e2ONtMGgryJy1dreL2GVND+MSLJE=,tag:JrqqQP98QO06+cIDXJO9zA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
