jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:vjcekGfNc6Cxvp+h6hbspaTRozQfFhozPzyDdGzM5s1ggn89Am7UawutCzlFwEvApYMc,iv:6a8DGqpJk3xf7guQ+4DR6ANY0CknPwjZrt7iHwcYC1Y=,tag:7zPW9V/iGU1z414/GC3upQ==,type:str]
        client_secret: ENC[AES256_GCM,data:rA/RtwuaZPX79szrAe+nnyEyn2NCWu82Sw5GFiHa4kWy3YQmqY/5Ffp6E+GolICgpms7FNXO7JZUdtM4dd22MlgKk1y7grk2cxUx/fObq29FK7jHeDg=,iv:AamW0PefL08d3djLs3o4Bq7BKs+jlshjIk5Bd97cz+U=,tag:+uF8C4oyhfVHqLopUa2+Wg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:l1tRHzNQw7J5QR2kThFD0g2emomhCTiyIm9FAIX+Bzb0q1sHuwE1nYgi/Roc0N/MIa9ZCNnQxyLg732MLMZywTVqN0zFYB90ERo73L2hhgci9kVqvXs=,iv:R8LFAiYLB9u6tYUGWl3B+yFbP95v2V7y/U6x7u8n0S0=,tag:oB6ixjaBAAgK3UJ6fz/h9g==,type:str]
        stringData: ENC[AES256_GCM,data:646ibj8a9iAFXq97iYJD2K1amRKpZ4eltiTJbEs379O/Sh5pTk2E8PR05eO1b86JnLscYHz8paGHNkaPG+x2xkNAcjhe3Ll+yVp0ZKv6XRTltK44F+Pa6+lOTdvrJdOfOBWxgPsQJyzuMyDmFX24kxfk6ObjY04+mtqlSTunAoz4MUBWli3u+y89yE1elTnjR1qvzBMRDdIiIRaTu0CH9+A37V5NN279WMzDaalK+6nuBlrvBxN0OYNrSbQQLEs/IwWNQHEgjwTPFmAgsiZdTTc0dzi222nHFv8BScOkl25Gid67jGuxwNIzERgAoXU+E3ZvlA42F46Fs8BlTPp/z6bHxIpm2FTaBf0V3m28yJL8wmpRarTePR5SbiN1ylqbuIX8YLTAnnN37m9hSrYj13TkJD4rsRM7hO6iTMq9ZaZs2nVWaV/v/xRizI1dBp7u3QIwJA6K7fW1lE+8wAhgSW9STNU9p3YIKxob1OV9p6I3P9AYwfuHydHkm7uAFsieObm84i86N9PGOFB4vFMvF1PYqQiffj8BkrJZq+Gd+xSNUnJyIEgK6wS5ymAkVRrtJmHnmAZICrBp2D4Y7SYFrzTvamzM9EeKNBauPw+puJ2lJ7ozzLconTXAPRCP6SFOcv8W0b0zmzUzXU/xRg==,iv:P09IxzyOH9ofrKh2qJNOYx8kJTZm3fHr0yaNPfzyQzs=,tag:d2YG+RUPApgCO5NnA15Dlg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:14Z'
    enc: CiUA4OM7eNEiKYOjLWZdW8FlccjBfHGJO5crAe82y6JfDqkMkM/QEkkAmy+ekmwgF4xgUsdwDZrrc0qDWPfxfuvMOSdrY0ZaNOJ04hhhe67EAwNbPnO7lCX/G0H6D7iplvrVu7fZ11RyabCnE+quWwhN
  lastmodified: '2026-07-29T19:18:14Z'
  mac: ENC[AES256_GCM,data:2ofFFkUOQ3MoQKqvcLU3nA5XFSLuyMB54nXbJbhzdZpYo5H6ONqDcd9pamijPVVMg3BDWhYxynHew1hln1WcmCy0RSer7itouusXCvfrOtnFFCn3HK2EOO9uHZHAHfK8RLhrkpevXBhwSyD9XnHdYbmu9NYG45QOv5ocJvYoEPM=,iv:UyhAxzGAd8cYg8/wpF0k2/6q8ZZD6fHOZPCzjxITNu4=,tag:VZ4i/Ng+Rdwjj5olYkrXng==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
