jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:dWOclPlluTM4A3T0zrVpENGi5K+Z5oRv+1bFPe2BU8Ts9K9D3Dufn0ZOjwNZfhDXcry6,iv:MsPS284BmE+fPsgVJjrjkdrBHHZPuFguFcFA18x7eq4=,tag:tK4nEn9aBiKsyTc8wOpacA==,type:str]
        client_secret: ENC[AES256_GCM,data:luWOP43saLTh6/lkcwhRBWbaItGREXox9yR1Yzpo5MGX/AG8kKuIE0qs+5AZ1CWDZysET6zG3cZYwhySC8njtpU7QjJzPWPSlyWp8ywQOHHOMEIgFrA=,iv:JLr3TXrZXJ2YlSNvv0Fxu8t+2cvUtwts6KQuT6TlH/Q=,tag:3bQ3b4QOa9f8MMYxPuiEyA==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:P7c4OqMbiOLsQyq7vKNwwAn3zrGQy6rM/1YlNLL2HCtwFW+TRbq9tQIbTlzMTRuEraY7dG43P4FkR34L54q4/g==,iv:FszfDdB67+iZi7ENbSaGQqfHmkQvCIK8afWDf5qrjtA=,tag:lIHd7ei9T6Y1u+ZfeiIsiw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:18:08Z'
    enc: CiUA4OM7eMtxCpETP7BRkj1li+7VLJ0XZFxJdMqlYLANU7o2Atk2EkkAsHDEl4wVyA7hvfQhIwKnfnX1O2XF6fy+22ahAJud0pNKFAW+L1tzg3Ha7mBb95IpVUyvyvzDBbzBcPMW956ao5YS5nMxm8ih
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:18:09Z'
  mac: ENC[AES256_GCM,data:mRo101wRIXO3kmSGeIelWuR5jbRbkPLACYMUSoU4CwLJl7FJspvVg8pZHnFjefY53rB+mBvMW0eKvTwg3pbfA/rwhEQgYXbz9BqTqNZag4NjFabGSuSi5nzZWIsNtxcz8muqtP90TLtxHcqu5J6aGYT/g7rSAbJuBZfzSL8KkoI=,iv:yWo7VUcrWRPNnYM5i5qcuOz8gd9lkSWhIQeVrqQ5uFo=,tag:0p3zuZv1NE6ih4scGLfhZg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
