jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:BoqlewWqyXidRDggXGAXua3NpPfm6gIHWTZnoPHAsEAoNqYovp5h/hD7GNrz+xkZGGhT,iv:ixXjXiEWEKWPfIv30GcOuswSGmY0Zvt8ch3i9Ryh7hg=,tag:nDhAP1phU59iN9fDwZNwug==,type:str]
                client_secret: ENC[AES256_GCM,data:2SRkddHuVq4XQgmxZQ8NbITB7BjgZX7Nh5NKkCA+Te0j68DLEz4O7MKWC2Ha54E/2TUv/fxxYmNDYH70nDxfNL52U58lu9Z1rlIzumsPworx7GsFxxA=,iv:4twK+9rISysxD/xeOg4ChK0iXib1PbgAB3nxK+XdEmg=,tag:g3L5TVHZJ4KA2i7qgoKZlw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-06-24T18:46:23Z"
          enc: CiUA4OM7eHF75kvRz5yqhTJrZkN6C1MGE83LG9G+dInJFg2D1xsMEkkAmy+eknS14esJyaTDDc/s0nwRt2lkVWhGWvMF2Si0TccySeGRsZ5pNmLrFkvi8tWVWG0Tfiu2p4mV6f3hKW67y4nicNvg0KtX
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-24T18:46:23Z"
    mac: ENC[AES256_GCM,data:KqQlqRzHhX3Ll7H9GyHxGsJh9FsBCFB8u5f1VQS7Jnvv2Y5bv8a9ft9Ek33+TrLL5zu8XXJK1WT7W48iAGB94VBKzazpUlrg+nrxWwrsCJXE35esQgNYwRJOY9CopT1XgeiEyf1Q3nV1i/48CC2nYlTTt6oNpJYSAhU1t50ixkY=,iv:WGaeRE9bPkMXPy3u++AqWwUMdtod4CzRAqHnOb3O8IA=,tag:nbGoouYjw1hZfs6EXbFlqw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
