jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:cf7wF/K/lya6xLn/l34vrUQBi3UTbEtvj8em0DRcF+Ap1/XdNWTqHwctINPuJtpEIOOT,iv:NQs7D0PAIQvfMUT1/lYY9a3aLjiokIT99lvCsPnUC3I=,tag:SL7laZCuaCvanvcYrp88DQ==,type:str]
        client_secret: ENC[AES256_GCM,data:qKYHdlBqjA0D5GLPcu61w81xu6KzOtBiDRXisc0ei10LaH3GrlrBB/aEqztv9Fuqcr6+MnjfmbL2Pbu/ZdNin8EFNO2RjDaSqYKiiZaP2q8I2/WETjw=,iv:Pbcpr8OrIktsm02zLSndWUAljYbuXZr5pUaZPNoyTDk=,tag:Y9mSOwlR7+KbZPoBO7fxPA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:58Z'
    enc: CiUA4OM7eKLLZgHxZSFhHu4hLUv16j3hPXwx1DltZji0Z21hDuoKEkkAsHDEl2XcSFvUJMqVBpzAcmxxZoe4rxFVF5p183YX1fWxKHPAtRmgcqipfUV8w8ZOzwhZQ5oK3p0XUcjIqbDLwzwClVF8M9fZ
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:59Z'
  mac: ENC[AES256_GCM,data:5c2WjagO/8iPSdIQ3/ASth+m3AHIdCda85T6s1WcHwx7HefLPhhnodZU4DEvgl8gYPdvJmTf1y1pip8KPNpvENo4HQRZcXADvvkCF4JyToKSRL1yVqfN2yHwvDqs/tczVaYqn19WdSGv9te01aMrWY2SXuzkeyvgIxkBD7RUnEc=,iv:ca6EmzwdDApi2o/EHHSqjV75lM/8TXYgc4ZZ0uuEFyg=,tag:AyL2g8eH4DFezQwi2UWv7Q==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
