jupyterhub:
    hub:
        config:
            GitHubOAuthenticator:
                client_id: ENC[AES256_GCM,data:hp6X8S3frTZvK/mqlHUsqgDFdwM=,iv:tVCsjMT8WimioJJv029C/pLZpIfplJBZzPQzRkR2vgk=,tag:KkNScmrEcC4ytQ/r7kpkmA==,type:str]
                client_secret: ENC[AES256_GCM,data:rLkC5YJuT4zJgN3KcgNt55zxqZlBjD7eCGzP2kv04XqLuV9Q5z2R/g==,iv:7CMiRiAmy9yXxDayruKq2EOsL7IXRNx5b5Nr2FYSO5Q=,tag:dHQ1jVljs30ZtPEZs+vpaQ==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:/es4b7dNPY7k5UKGPpUcTCd7aGteDdjbkn7sEh9stQjZIj6u/HI3l5j66hStRsXroP8ng2F+tidag3SpNaeeyw==,iv:P9qLHTMu8gjJJTZYQnvp1iRmwXTgSLxD/+ytOaaJvRk=,tag:eEHNvGW75pBre4tQog2lBw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:18:38Z"
          enc: CiUA4OM7eDYeweS6U10JwwAf/iSEK1VxMeaSHujrjojlMFIt+tpQEkkAsHDEl43Fq5wGZPNIgdHc3M9JES3jkM3oOVNbgjlk3UHljaFThjmoKXt0KQowpO+u+x3+WBMcn7rmPu9hd1v/8g0XBFzc0/Vf
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:18:39Z"
    mac: ENC[AES256_GCM,data:WaLt4xEHU5FuAn5+mEAZUK6PJUppUh2p5BOZulw/3NlTm9cMP+pi5LqSoN03uV0VH0bOo6GbhU2ZR0Fao0nmE8+SWa6Lw0P9AmufNsq3H+Hl5wg0ItHJRp0i/Qah79R+jnMeaFnY592PeYOhLCCoH4ep5QlXLDkBu7wEIKYRFXs=,iv:KI+zwo4/qzBl9hMcWLgrtx+LtVdNP1K2B9TXtMSTGG4=,tag:A9ogMJPUtL8iedIsV473HA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
