jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:cBhRhImRtVM5fTexsC/Fhi2F9VW+BbCpCTf5oZNibC9zO7KknPvHGi27e1KTu01cCs0d,iv:knXtQds9zsUhiFGAVLtiQaqK7tHSF4U7rZthZqqA/Y8=,tag:zqPNEQZmcQq4OK8cFGzGKg==,type:str]
                client_secret: ENC[AES256_GCM,data:VzC+lWGTVgJZ2UomGXu8hDIQdctsAUfUSaMZW2POYtOr54gHYqtIWwZ09auNUQ22eG1jZerbtXixHvcu9CwPhjbfn8yCSDm6KCcaEXFiw9eUAGUifJ0=,iv:n49nN1YmGZWP15W2O1v2KKuM5GUsJNtSB7z/sv+S3Wo=,tag:KtTMYpWAJPJsruuKCU6Mrw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:25Z"
          enc: CiUA4OM7eBb1FrUFhJ4YfUCYREfdgWdP13MpEXY692q7BhMe+R5NEkkAsHDEl6jc8zTzAMmOxZr1ywwv1ADfM8IVG2gJSdyFzdmCOeNw/ouoBkUQniY87KwCODOixo2VdzgT2IP/bqmQOk9w8nPoKVkh
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:26Z"
    mac: ENC[AES256_GCM,data:TjT5L7gVE86WOUeR5vJNBtDh6NcotGzZQm3hSDmrBZl+yRnOalDHmwF74YPC2nfaKkrn4jbnr+xgbkETon70uPzBDuzbOcVr1XtD2D2fSKFwnBn06npsnJ3q4wb+JZQ3X2jpu5rph8vc6labSR4iUX5fFwzbwmN24Qoc/h63+3Y=,iv:7walj7FnnFbn7ub3Yy2gg3CWrX0JKGnbuufByxv7Ers=,tag:mclf+hntsbV47FARvdUlcQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
