jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:GyR1ASjvwmFp6ryiOFhHPn0a3Ck=,iv:rjsL7FUPiFh4PSYeFBneVecJzGfHjDexgXehdSk9Fg8=,tag:pwwxZs2tnRN/f+Hg/4ezSw==,type:str]
        client_secret: ENC[AES256_GCM,data:GlzWbH3knNfVRFScf/u1mLH0y74GOZmfIBqay5HzdVDXb1YMELmd0A==,iv:8s52PHIEXCOcFzOoCnwS6USmjB9wUD5EqJ2euN9SV6Y=,tag:t04WiafiCSdRTSoDiMsb2A==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:f4vo0MuvlVd990NJSd3sKnlk8ZUYX+419xZnSSFcStw/UrQYreRUEhSmjhyECo/otef54F8f6H1HusScU6mxIvY3iOF2eeYryolabn39W1Fmt+koJQI=,iv:9nNXHrqAyvz8//v69jaGU5cBOZepJEKT4rhyUZQUAr4=,tag:h62cjZI0nXaUnDYfQ0goUA==,type:str]
        stringData: ENC[AES256_GCM,data:aeEJNYcM7BCnI7ccsc6ywvm2xhUUhxmYw3BbtYbTu0njuIF9PEvUmk1YOlb8xr3LbUPdL05Ohl5mO5V5oH0CFumejrjhLHcpWTle5w3H6fQgG3dD++bdPKYPZ1bkCCjlJ44euKRfONvvPOyjleu7GCrPee82pUoajbm3vJY+k/GdSY7Ad/52BKfMjkaUBGqMasWq/DsF5LZ9ADssS7zmuLKAF3+0m8XpXWlqQ+MpYyk3yH7WGWqZLmSiJ2w7AtX9qrD2a4+wUwiRuYMEWNuAnOE8dBkGCNXGKdMxz47yjVkZ2DMtAzciTxedoYat9rX6bJrGPZ2huGHzs0uBShI0JURVugS9tlPFIDnnlTl7KekL4HxoWPxKA3dL2j5BsaSrMoew8pYaW1rJpnd0RETtfBho6puj5bzCjE/eQeKv0Qgpvse94clce2J3rYGflb3rDjIAPTqGurx2PyglWWspDhKlqlDmY833RF039Gjg4Ip4uodXgqM7UGM7naSc8WbO5AbkabFKYPG5du3Vgl/fYmnomWzYQKBWAHTKBuCUY+qFUm/FvdSJ6VniOQy0DPURk7951Bo4HWBCgmgN/RU0EMkhhNtJFRJnlRzZkHpq/6HCLC+x4491Mu1pgX7CbyCSQFTnG2DQGC+wyckYSA==,iv:rPSKT752a6lunW+cc0Cy2WZGgEgiWCUxdFm9J5reWp4=,tag:PzJ1ZAjAA0ksQJMSB3Il4w==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:53Z'
    enc: CiUA4OM7eFwAtK8hnXK3ShBK/+ekTU1oRE5AnWcIYoIwR+ampp6kEkkAmy+ekibr6lE34CnYRxYO5fB9BcLlqK3+RrVSBrSJOlMJzRbn/2BiVaurvD4aoF6Qfd5I6PZ4E3PZMgfOjIebC87XE40FAR4x
  lastmodified: '2026-07-29T19:18:53Z'
  mac: ENC[AES256_GCM,data:kDLNXzGWwHfD9gc+aZl2B7Eemra70FDay3/tCc5z9YmDM51sm9KfENKJRnFfnR4AlV8NGzBvRlFapinbKbXr6kAtn/45v0HdRUPmQnxt1piQMEUx+g5QO4Bisy7HEGZ1wLHF3M7gbBPMPxl4ssQOKWXht4mYFPo+rjAmOWlOeb4=,iv:Nmy1s+Pl99eem8FJoA5ipEWa0+lD8qEjYLxAVXB/dSc=,tag:Jpmbb4cSix5PkwSthvK0Vw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
