jupyterhub:
    hub:
        config:
            GitHubOAuthenticator:
                client_id: ENC[AES256_GCM,data:t70J7dsoER6d6/NJ+3nNWc9TfEM=,iv:wsrO3u8VNliHjJoziRKFkqU4x0INXsaiNi6SinG1u2E=,tag:BfcV8P7Sdq9AZnyi8a8Qcw==,type:str]
                client_secret: ENC[AES256_GCM,data:zpq2D1wt51/pFrLuTw9AMpXIDeTiS6fSVvj8NMLC/+DrY0MavFKH6Q==,iv:DJo+KrmezZqDA/SoJFi/J+OCYoLlP7HIp91/jTCwBKQ=,tag:u7VKDw77uU1njxPReYotGQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-06-26T04:08:24Z"
          enc: CiUA4OM7eJY/PXpE3FZSbyxbL4rBcchOxFt83iUtDuIs+LoDwEOWEkkAmy+ekpzL67QGSxLUzPc8I6Qx2JT01MRtXGOn28c9EdM9ptnWnbn2n1JMjGdQkig0rFYM2ZAwyaIZkUoefqDmeClsUwbqW5oH
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-26T04:08:29Z"
    mac: ENC[AES256_GCM,data:8bhHEhMj1NwdKZAEMRsBGh4QxZ8GzJeJM6UgscJX+KUoXU5hAeNFyYQ581Rn13/khkOYsG/H+0mRD1r51xLhhUwAcDXZhR29ZMd126bxG2f+NhHVw9j6Cj13++UIT/INWubX9k0OKyfM7ru+89Jj5NOExm1G0HIxG0pR7UA06II=,iv:b7uGcgLfsxdVX8cxn/35RvDsK6uddjzKQDbBKOJK+t0=,tag:k5im/yzjVaXV+eJ/tBE5XQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
