jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:Z/3GROt6tAdKUbhzdtBcEr2kFJW7WvGl1SPVz0ELnz1dnsKq920ZllZZ6QNSEgXIG2Sz,iv:TwwAQuReP0CpMFRzjgscxyqsoCecyzFz5inj+B+OOK8=,tag:esPYPD0YiOScAt2Ei1JUQA==,type:str]
        client_secret: ENC[AES256_GCM,data:qkAptuwUE1kF80v55V2Rfs7vxbLjQyNMDt36PmFnVlWW+YR+yo1cGgJORTIfNuap8/7Wze0nUPSb5Bj+HwqQigrhePN3uN/wO3bjv2zjUKUr0LWsddU=,iv:BNpZ28XtleYycME/h/WA0i2U1SNk2TuiFtCypp/hFwM=,tag:3fwmmleSmMQd78dN+/WKzg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-16T19:57:56Z'
    enc: CiUA4OM7eOtl8XC3LysEDRMXpyzTk94S8Idv+p1kgABsQH+sLU4oEkkAmy+ekq/ljjk/0V2Azm67RT2GxA/z5+KRoCXtuaMSZa3NLlPvTERsQnHOF77BL1dWeZlLBPzfPoE6RtbrIqIvp/ofH8vgQOuj
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-07-16T19:57:57Z'
  mac: ENC[AES256_GCM,data:uPT2o5ge+4ILXsKCjDfbH9dnQssMqUALAZInPa8F1YewdAc4QzO+IzLranLL7or8bn0MdTyDFkrGTbpW9JPreF6B8kqsUMs7wAnX0ZLN2TmYMUHZcDrt3NpHht96QYygfTuj6gDU2FE6xs+Zf0poYWalQvgxaJJAu2vLUlz2vdk=,iv:QKejFAbB09KtocZYeGqF17O73FcxGWzB7kzJVxo68XM=,tag:z0nvcuERyfwpKe7bmfCJFg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
