jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:d/Acpa67vAJyej/BKIshVyK5JSZ+WtxDpKE7v14NouYZ91+7kAKHsXreuJN7lbgOttg2,iv:vwnOvDxYGSJGbQtsYwrbFr01yr4kh2sdIXZR96Gg1Qs=,tag:n0sF5iRSuQgkQXDlHS6JXA==,type:str]
        client_secret: ENC[AES256_GCM,data:HxY3zFr6UlvsuhUl8CAhwD0+tcs12BbrCPmAvCTAqSLvMx8grAuL1pb0kaaRRCHfay43faZnvxJtdsFlaya1OnfYhAWUjIxRPpRq+8falLOTijaZm5Q=,iv:ZNsOIiUAelkTKl3AzkLAWaHipsKvrFWcdsP2Hjcz8sE=,tag:arTxM8A6E7onmWik8+WLSA==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:UPtIT2uXZiqivS47sOelT1F1LWy+vbxTZg3abOBOi1ww9hMdBLww1ey/qIv3A26nwFdoOEnNTPzGw8idAinTK5Uvid2WPMnc1UtEfcTHOYcoZzkAXe0=,iv:hqh1MtIWTm4SR41ahic6ZlIilVeWqBxxkC1JgDlNwsc=,tag:mM24+cctCdplWQakmN122Q==,type:str]
        stringData: ENC[AES256_GCM,data:FJOXwTMqlonuPU72bN1q4E2GOzO7gM4OXvOGBU/tn8uP5saqEL3/QANQPQ6X4ekkHvE25K+KjoS1LntAOMBIG51g8HQsoLoAUDKuiV31KDv7J2xxLx+BtoOFs2Zq8KNsPw4jM2kAxpswB46VX5Vnhq1msMQLjIoeAYG1RtGxZzMBB5N4H5KmNBrvy4Nloo9Kt4DUxRCBL7vtdF9x2H70aM7HJODb5LedVjFYK/BPdQBgMKFgBLBy6WvLHPmUlRw6GHtyGMQf8PGBFpVxid6j5dXJXzO7bAoA9chb+7h1oQyqxqLDGX+4F5qWYB5dm9OptyO79CJf38Oppjbqap0PWyhGRke1MiwfgCEO2aesOrr49vHa6LBCLACBo9h8oR7J9qYQDfLGVjOSwJ5l/khKuC4E4+0Q1vvCIbi/MRz5y9sqkhqhynSLXyZc3gpi8G8APIMNSB2uItrqa0KlgKFsAstuDbeBGIkAduHjXIIwiKjSU01sHslsXzi40duXTNeF2ZqBN28mlKzoWZkKuvnJqwn50IbTR7yjpYaVRnGMbUlf/0bLjUYPKBo9Skq0xexdmE7RQAq/7ejOGOTE0GIYTIDv/krqDq2CL+GLJOvrhpMdh+irFg0q3ko+dJnNSYnqgqL0WO6QswxLQZ3RxA==,iv:BekmtAZ/fFmGKMBVA7MHQcba3v5norB259haWupNRHo=,tag:OjAZKuBE/q8SiUfzccL44w==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:31Z'
    enc: CiUA4OM7eOpUB7zlTGwehbnaTnckWmpBuJjAypngQHJNgK4OC2lwEkkAmy+ekhdsWfxBj1HNz4v/zDVOLWFx+UQAltTe4HmFQkxc2FV/uqhv0fF23LWYU/cqnmX3dp9PerVONygvOvoKuCzQ18SqQ78c
  lastmodified: '2026-07-29T19:18:31Z'
  mac: ENC[AES256_GCM,data:3JzWYL7IE0uARcpY5ayQrlP6kSN0onyIn+fZydAYAbJHML14R3JTFybZkChTcHq2CbhzxFHYuBThDhE+mM6GatGV8d1lVyE93kTPAVNP0292bPukCa4ocCkQyZCunppNtK8dEeJOhDkVL45QwZRz9m4HSNq7qcg4RSHhvu6xCa4=,iv:jksBQQUQ+KNBTo1Cu6TqLlaUTYnPkMuAw8bZO04DpXY=,tag:OOrlEfMMFsVOI+qouVDUWA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
