jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:ij4QBSA5n088eyfKAW4lAMVmqW14QLgTjPvob3PfkNMrSC/jNc0u5YoNnDQm1Kt2ToM7,iv:3ioVV4ooGSy80tjiUgqJv1kz7CBoGN7vvNy4gLq9hZg=,tag:lrihdbMziO33D8G30lBIAg==,type:str]
                client_secret: ENC[AES256_GCM,data:vR0V6qHS5sbQIRf7d5dYePxb4CbIv8vhS0Y9fbVC4FIsWqditUt4b7dvLDykkNpGCmcAqaOO26vSRr9cCp0mBxf0XRW9YwsO+345ThUWYerfQsZ6r/Y=,iv:Q9XDofN1dBGg+JXc0+OsfkcDrFUoVzXa3dHTgipfa00=,tag:Q8Pofha5QQ5kz4SDgOJleg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T01:32:20Z"
          enc: CiUA4OM7eLkFnyAFbzCDljZxOqRBju/badnaO8uP/xIjAKih390jEkkAsHDEl4sZy8lflt1R/J1LiRcTU2ZSaJ9/Hkt2tROpEpCFboX5zCZxhNJMrMch3+S2wwCgSu9FKxq3crFNwB28a+vziCRNV1tw
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T01:32:20Z"
    mac: ENC[AES256_GCM,data:RzXJbq5isafrdAD8IbbO5nIR540cXjhqkpVbYQZLGh6jZGUYmrEFrSTq0S+/YcTY5kN8HSl2vbgyFUrNdMe7YcMKamaSLaGoyVNuukMf4BmwXBEmLnsrpJymBL+h84lJ4pzQ/eoS1W3pINPk6DMKb4hyG6q5iVtniVre9ymxPCE=,iv:9d2bW4+TIZin7zcABW3xYEsST7jeYPmBqD7qabdfTq4=,tag:xjOFcN2H/yhzwQ7QywLprQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
