jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:mGeTJBoFenh/T7sGZTUdKmvS8tkacXQ+dUHNAZRy4EV555EBeWSrFSkcFLNIKqPyer/R,iv:7+a+G5JNTVSSzsCTm3oRu+oL9k+LgL/JYPpmP/nEyFs=,tag:8Vr0b1Abcx5AVRyZKa3zzg==,type:str]
                client_secret: ENC[AES256_GCM,data:k4i6wecGIu03+/vFiyEm0/c7whHgEh2UVdNfAHWfcvC+lQyRknJCuw5hEPbp16OD5Tn7A3H1viYfpB/966hZEXiRTa3GWbyM+xWWQDNo5Q+dp6lnoEQ=,iv:IbDSgWnI65BuzlWHPUQIoTDognKU4KypM+91FNFURFU=,tag:BuamC0Z16bK/MfMMo9nlLA==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:TVr5kvbYVVJJ+hN/TATGOGiAEza5ze4UIbn4nImZXy+ibOeBW4/GHlwtG6ZqdB16HbOuZOS0Dy0kZB2xPqmZjw==,iv:zaPqGlB8KQP7ii3w42Rc+ujKrYad6C9BlxTqKFiV0PE=,tag:jxGeQ9Z37KwjuGEhaS1Gwg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:18:46Z"
          enc: CiUA4OM7eN29qypZ+ou44JLZJabE+ReSw0TSjz8Hi/Y+OcH3pTa3EkkAsHDEl4hnITVIFiHkiJLY0Ee66rZZe2ZzI13WH2cTSBM60zmqUGJVpDKceWknQU9ickhLhS+XykSHchor9TdRboY++xJCB31Y
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:18:47Z"
    mac: ENC[AES256_GCM,data:pOpWW2sRSYi9zXaPEFi8gItxz9j0RjR15e0dL909bNoShImr3xsWQU1KyXzSZ3XRbG0uXzbfBM3g7Is1vj6d281dN0ub90blkwLIopL8pXxFT3nVfZVz8k7U6Wsze6mB1y+ZUErAtVjbWNIwPhQPf707Lk0ahRFQMSfa6i32rzI=,iv:zOB5IrDaWP3hL0zuVGZOmhisKJzQb4t8IHGPsTS3yBg=,tag:GpNvfxhs3yOtVBg/PBkFYw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
