jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:GmqRcns9bZ/JL/m3Zp9YYiuwots=,iv:l/5vndgZXV6dRSWfdx8nv8DKfMX9xmxjOz1/uI0pjhw=,tag:Me7L0nvVbE7zjHJMBM67pg==,type:str]
        client_secret: ENC[AES256_GCM,data:DGDvDmgxlsR0y9QZhF2V+OAdMzswzj+zpleNAwFcUqMOqeSQc9nFiQ==,iv:1sAYi6WPCfpDvOF+RmtK6eVYPsQ6PyICzKehenhtM38=,tag:tCB8IrgctpEMqGHzBEpkpg==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:Ha728WdBElHEl5225gbwGtNCkm9m+zF3OPqe4TrvTFS8btSdjnZn/DXZj3P0G0dgteh5sahsGHfc4FD9/0ULog==,iv:9b+9/e4xlnNXH5HP9HtWPx6ue38jLHYB3J1u89fT0s8=,tag:5hQNtQXOwun/1aafKOUkfw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:18:18Z'
    enc: CiUA4OM7eHTmESJRbnZEuL+BFHsVAZ+5uGyxrss2nEBT8YU+KxX1EkkAsHDElwzyR4toPbvxnfJdh0TRSxrdzHZuF6o6hIlM2rVATZ/+pLLGUuw/GpAI6TRIsCUe3RdTtpnOxhYhM0NGTm0LyClqEdD8
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:18:19Z'
  mac: ENC[AES256_GCM,data:9AiOVMX7dS1K3YE1F3uD77NQoBctpGRufU2b/HOaztdb98TZW/w6iPiu/Zbp6G0ylgc1uXGhdxEfkYLmvDNFMJdPZcn2/M57k41rUZ0wYRgQL6OZGuecn4VsUtn2aJIcLHWFVaEXTwD+1OlLku0tPsKVtCu2cUiV6gkDhhBOlwY=,iv:eghktLIWKUE2Ub6Cx3giagj1prP8f7YXTOJE/LJLD5o=,tag:Jtkb6Bnt/ys8ZNEjFM2w7Q==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
