jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:uhE3g61CQ8Pv3uUdhPHwvDb/sHDQapKTcRBhi/z11o0c5t9F/waB8bBJp1tifpQjwKXVPhr6N3ZYXxlP900z3K7FKA2ydEjw,iv:lIkI3DvNiAsRgWcAD8T1KgfPiucS7J7WhJSXTTKDfz4=,tag:q/p14r9RIAEWEtRLH2HEvg==,type:str]
                client_secret: ENC[AES256_GCM,data:URPin0rdm1R01ZzdVd6NszfpmWkyMvrClJVuUYKQ1s7U1BI=,iv:gP4BEOr9ic1rgiUvFQyP+Ylerho0Nap6DCxUApOxP+Y=,tag:5Tr5rLDpTrKcwX/+ebf3Tw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-07-01T23:41:31Z"
          enc: CiUA4OM7eDwT/EPOKHKosEJYZzoxszX9JrayWqJVHnhBt+JCbkDFEkkAmy+ektP0vAycLkUj5vYHbIzMua6uYdM/jQZ/PkAwcSV2S8RqY0l3H3fE/ZKYpdbjU1ocxUWgbSSZUFwcjAuMXbe2BLc365lN
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-01T23:41:32Z"
    mac: ENC[AES256_GCM,data:WA0I0FVnUfzDj6F7NBslZlsjylsFEB63qmUH7V2QVaI4aQC6exczFrGg/KMusrtQ16wIKnKFO20kRcUF+p2sQZGl1F08571zwBdrL60uSfkEfs1LZQJvU113uvAyWDBUriB2y2oLn3Sd1bIzDR5fbX8WRuhBeh8Z/QfTLKSEfwM=,iv:UOuz1ehLQH3LHFhPFpa8khFvo2fsOJTst7I8MWgzsHQ=,tag:QkvccqBgs0V4xa2B8TeYfg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
