jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:EGhGiDj4tGai,iv:uu137Rq0/+L6dDYvTy4Vys8CxyBLokZpnDGR0aSuS7k=,tag:nP2cHDEIeArlblJGKCTv5g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-03-06T02:41:03Z"
          enc: CiUA4OM7eHueMFj2VGe9uMtqS8PU/PHi2m3Q6OzaY5tDA/rYLPUFEkkAPHlbmW4FBQ8icz35leKa/ZMgSr/XxYWyYHGRny44sWNdfBOhwhdNeNV++I2k22+7u2AS6A2Mm/DRy/UnciHI2DviqoCBjJEX
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-06T02:41:03Z"
    mac: ENC[AES256_GCM,data:a/QU5sYfOeLeTgYspb+t61e0VuHUsf6GGJOUIFgza1vHM2Pouh2SmtNzaekzFtfUkguCcCwMfqJbWrq5ahxow3ePLoODoYRmXiCfZasxwM3ncgVZPnCF+gOhJdDNDZ4uehzJ8epepXZgBknqKNTACgMdXdr80Vu73py/uyMfrNQ=,iv:/SuiVKhC5hyGRC+u1GR7h2QthjgFS/cJ51zYv8zaHEs=,tag:dQubS+JljwgQS/d+nmMw6w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
