jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:EHEIixj2R28lV76tM3bTwDd+GjluQnPnjwSjgt7kBSGP5Oh4B7sQNlaUa70x4qFog602,iv:XO+IoMTVRqNnBv18vc4+FugkXiNdak7YBqldPU66vMU=,tag:QchZdZc/nQC2DXSNf4vJ0g==,type:str]
        client_secret: ENC[AES256_GCM,data:mEDUglzGMC9ZBp0FyU701osiTvHGNjOygxakSpZJgjgUaLwihpvXED0qPGWBpTM/8QZ3SXAwENZryMt/7R3VG1Ng2L43x56BeaisQvHo2q8ZZB1gxxo=,iv:nbhhdGbI0J+CYn2GQEvCtdgMUFSJ1VLC0yam0MnPUWU=,tag:mH7Jzu10U70qhba2kkyzXQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-15T22:35:36Z'
    enc: CiUA4OM7eCjGu4fjzmERDeGUkrpfPevE1OZ5MumlCmPQT0s83aE0EkkAsHDElxfT8PEt88KWC7SOanpHC/AXU/FAktJiZNLsHb1SNB+X2iWnEO2PS+wnpL3OjyQkiC/ebVvi6nhjJ2Djt1lOZ+uXL5Fy
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-15T22:35:37Z'
  mac: ENC[AES256_GCM,data:dmFHXSAWkde5nAg0PnDVACgz2O75A4eWtdzaN5guoZOWSLMpVJeJ2vMfPTN4rjsbWWqxPsJ0edpZP7Hu3WCtoGVnKFrMHIIjtfurV7yPJwFjl2bkwrf3nlEmdYAU2ucCLKwlHBrdY0nneOSTD/4F+fa7Y01xp4q7T5mQxB71n4c=,iv:ngA90vbKB2AjS9jDePOEtzBpBBp77iQ2CiYsAoMHpSc=,tag:+CbWJfR9MOMx/6q1aIwhBg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
