jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:R6dzxCkh/K4tDo/DG07DhhOF0O6cORLzWiNjFn+sE0/FH/IOipa9JqvC7ju5mL6SC5hA,iv:Vn83r0s4QNKexewGnZa+9MyIqy6xGG58PXp7R7bSBXU=,tag:E3n9lN0N1DvoK1cCPuDEYw==,type:str]
        client_secret: ENC[AES256_GCM,data:ulNvpL/CaZgQXA6VX25sQTqDBcxwvtnBxKNqjf8L/ssnzTosufVzN3PA7YEk23i5cBtejbAwjJ2YKwN96RDpMeHr+7ar2hOdEhw2Q/bJzPRTvGymTto=,iv:VMc7laMXWLVrCGLX3TPu4ZjKDbzR7u0F1j/BBM7egDA=,tag:RdbNRf1CWnJeT6GGjmg/gQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:14Z'
    enc: CiUA4OM7eIDpEdx7UHoB7SW6NbIRBLFx4t9Vgvhv0/Ff/+7WSFMqEkkAsHDEl9gRxoe5cn4Adq7/Ord+chQm6XDLTbKkO3Hb9RcxBW0wMZlFlI2cjbD41sELvacWgvSxBhVTNNBfo6ZXMmOaN5JHfOt3
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:15Z'
  mac: ENC[AES256_GCM,data:FmM5nGUTgbXPh62OLgsX7rsCjMODMv0krx+C6jnQoIG17AdTiBtNpq2qSHrcYSVVJfW43V5CJivqA2tHgyPVSWqfSdQ1AmhGJY2saDBvJUx7u7JvNjn8uXn4AVRqKCDjEph4gScsVzjl0EcVuUJb7JztV5JMKzUqblPZtQJoGnw=,iv:m+mSZ1LHCOan9cquwFwJ7mCJ7g8sjRJMCTVGHcezhOw=,tag:aLGaDxqgNDc3utVD8pxZcA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
