jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:zU70EtlZqOhxCQd+pIvHrvoyKn3ASFwNX701XKr26deLDYVvz2eWZhc4PURjm6sTsG89,iv:YHzw9SBUGwTJT84HAX0PrPYPEzeD7dsy8S6lx4obCyQ=,tag:sGjoTtMhebNFsyk6E7n05g==,type:str]
                client_secret: ENC[AES256_GCM,data:6Z4bneeYPbbi0qs19lk1bdV35Iam/enyDizYPXh2qdO+MrsvjEXaAmEBV6e3ClOBsNUrskRiPqERIqf5CJiPGVaCtnzaTw5cKGeF3KvyHk31kZmjf08=,iv:/dx7FDGyzIj9z6J1ofrnI+cA6OEgYE9SCY//oLZGWN8=,tag:PfqLDAOOIRSGwfYZZfIiIw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:1/zN9fplYWz9TvGi9+MEroag53ykkIVeUQ2ac2/muwRj2Rnzef6e5KnAk/6fR0atZBtf6mqWsJJ0LXXF8GB8Fg==,iv:UxVoAPOpYxOIe4XHuMOK1xcOTxebVYnQGmzU2ssy588=,tag:gNWDKSeI65ad29Lg+AoqBg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:17:33Z"
          enc: CiUA4OM7eByNyqv3gy3zQ19uKurfD9rD4dc9IkrD+z0v0w50hRr9EkkAsHDEl9EqxSX6CkZHrGUlMxD59PGAD8D+MqlQlPVSHyAJwJRDPRxWRCHbr1/9bNIi1tgFeDl7Oq04uDaPdIt3U43IMDmn0btR
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:17:34Z"
    mac: ENC[AES256_GCM,data:FIU2o1k0SIJLwWqwpKW4M0V/dact/6mxBVyjS5en2guChNmFbPT2k7JP4oFlfvGWxhPs1IXLqBhjf9sljh1oPGnitKIH+dKWP1PCUyqE0qs8nWImbxTJkwrCmfqG4u48Q1KZ5HseKE8v2d/oG1aQGM1LnivAJ7tuvOq658ixrvk=,iv:Ev4GNLAQnYAsZG3YD69g+r7Kdi+TM/gMXknen3nEsUU=,tag:LbknRdg5WTatIyiIg073Tw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
