jupyterhub:
  hub:
    config:
      GoogleOAuthenticator:
        client_id: ENC[AES256_GCM,data:Kv1uuv1Ca1ryR6Zx+2FyNAeV8/PgqptHUOE6WBlPos12QgBWYljRVqY8yA4yVQ4Lh65grwrt69vGXbDFkHCgRaxbdNZ1H426,iv:swXkO5KVv/pfsMTl56Jtq0/RNc6WjNaUDfS46zPHnlA=,tag:ABVRxTxbagXT2bI//GJvyg==,type:str]
        client_secret: ENC[AES256_GCM,data:D5Qb18jqISDwSxo2OHOrtGxw8rDdZ2ARA4XwjO1mNODihNU=,iv:itGHCFTGjMcPacKvV9iQpkvuZNPXQFlMz+AI6iZPcE8=,tag:B7Gm/SYEOqUWdL9V82sL/A==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:+s6YZZqvlRX3sD38ZACqY2v+jNTUaiRQIW+RqvE5AD/UlJo1ESuY/noWz7sSi3K97cQzGdl6n2bGPyp0aoxnXQc6n3rM+mBqStqIifUDtsvccW+iu4s=,iv:r6pa3N2jn6RCwC/9ebNy5zTDj2ExtrSbtixT9jS0GVs=,tag:fagC5MzSiwRw7qOVJI84ZQ==,type:str]
        stringData: ENC[AES256_GCM,data:Y33hn/ywjZfuU5ff2Xcp6vaRR4rbwi6MTzFj88pjCCMCwBHziM+yJbnKcogDp/LwfXIY7ma6H3/xnHXtJrPSqEhi81nzCRqDnQfzmcATaD50p0uv+V8x+umPB5DLDe7hVsAEGlfA0y0CKPQ5v6r4rCat+wi7o22K62gdmyMWqiFLX/pCGp/ooXMmWMhlcRbwTD3ld/1SeoRMR8h9ZS15+psf043ou1phAQwDocS+iPE3dTafIyyveozMhdJJO0yELKy1dFngyTR8P+qFIKpwKk+DMxKqmouU3Fr1yw/AoQdzYnhfpjD7Z32WTQf3pxU2/ItQaNmdmDsHWvN8gjbq7jurF9Z4ycVZvCY3gWKeh9ZPQdrP7hCJyxE7npNOcaFer6QbyGBz3iNqiWEieyGyOYiuINx4hL8y1Kukqc0TowGsT5rldx4va0sqgrUxF9wCoiLt29bTaEIPogfPgb5nUGPthxLL2TCtcuTPKtqQVJIuuB1bsh8mhaXZ6nGFXiHszk4KmjPtGC/+K/jUps5xT9Q/svvFB/JRE+TrSRxXItYXabxrJoAxA3M3+2gNoV9TBQ2PgMJJWJP9yNVN9/iTcxX4ZD2DOzfNrMmA5gU8yHRi769GuSPM6lr9f4hOB3ms9SlQ7nJg0V+27Oqfig==,iv:wEpEQl+PHNMuZAyeOQZ/dpEyuSNbGEGYeXh1a1bir8c=,tag:KKdiHfS9PzUKBG7RInJIJA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:44Z'
    enc: CiUA4OM7eHbNKhEP0rfS30ZHZnQH9kmky43HwhTR84fYZ6r95y2oEkkAmy+eknhuWmZiesC3ipE4wcmyd1qaSwzfxm5Khukd97RlaF9WXS2o7IZNBWsWW9Zz3S/4qnLu6BuInnP145IeWU8RaOgAgS0C
  lastmodified: '2026-07-29T19:19:44Z'
  mac: ENC[AES256_GCM,data:F/YdQpZeSNWwayZuKJzIyLLTV4uAqD063OTIwR7LYLwvkw4Aqufb/0QeN4UFZ7Yj85lY7kzAJRuC/BC2B+MfxZTvakZwRvQMwMPDspvJK4LY51X/0y3ha3zSxs0sX0aLX69n8wZ/Qe9YeaAGN7cGwNrPmETaKzhLOAWgH8TRESw=,iv:cyAZyFvK/nZoy2SfmC+kPC1lP03VZW+9RgUzf8UfG1o=,tag:kR1++Z1+NWNSxV+7zELX9A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
