jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:1fdhObjo86UlXh8SvbXgr1jZtBBAHrNqGUdONyqc8Ww0WUEsJlMLZtEQ18JCdWKTPF4E,iv:kL/myLQi9w/E6XDWB6EusZl8SuhcImpowLJUGAeOGXI=,tag:iw6LZS2CIiitRwtjHE/UHA==,type:str]
        client_secret: ENC[AES256_GCM,data:slMkIa5kq75KV1fRf3xKeG9794F9NUVKOS8bZPtPT52qYHcztUKNJJ8O9VxNvgHbYSu3lPtzbi8UHSxz51MGxbdi2uY3LFK/KUMmsz9/6ns57E9F65M=,iv:hUkM+Wn3TAGlmVYeCLPAPhCek/Wuuu6mZGPzOBrI0UI=,tag:R5cv1SZEuTxF4/N3z8G4lQ==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:4RrEc3hw7fPT43kRPBA/6AczUWYMDp7A9J4g4jFtPPjepVoblSBgJkU0sBOxmQwZrvAt974FEpn4A0V0Ke6Wdoei1EK7TH+Vh3vG/SdM6soe5m7Nd2k=,iv:eSe5o3C6YhfnsKyrWTds3B//dBkLtld091lm8SJi9KU=,tag:ACFqmsOmQCVwBe1JLXqYPg==,type:str]
        stringData: ENC[AES256_GCM,data:3L+zxFV0owO8HUTbmndwQtdDmVvX61JPIyzPx6eUzlLj2Am21KnAheLa37R8z7tL+EiST0mA7DF4XPfobkdH41rFg6vUuYuXAUW8booqQCf/elCYY1zyJ5gBALwrmrjrtuc1xZIP2zz/rZeT1xuTds2b4rzfi476UBBLpr5djvKRdFW89xcpsHoMINOwch4OoGAtyhJPs6MVRV54k005Cufv7wFPInc2GYz2WcJ0HIMff4aJE/6xFIIy5pAD0e1TrJvnVl+CCl9TL/AEKpuEbfIknPxmebSlI/CoFHC5c7hLjqDctvmGLwSCyYhrb3zS2kp/wrvuTuIpWnzTAtm3/H9qPKvFVREc1f7Fd+FPyvb24medF56YIxMIJPH0tjQwZ9veENnUO27QJJxfLpPmb+7P9hHkqtM07zstQKl+H40ZFZmThp03h6ze2UO8sCCjsYGuLdiV11y0wR4z8JtQSItKrIqcqJBk4mBVGHmoHfvUFKh5ppmMIYBuEG3cSMmmW6AWSs3fNVr4Kuq0RlgezLF1VrpKfPxMrXHFH/VXQ9iYwegeTTXLV918Lb9QwP/Zo/LZEi5NaVaeIlkVAhEqM5CLFcR6CJl0X9MFA8DmNdtL6EVRz5GMPBW+tbbMIKuAm4dSf238dDYFbdmszw==,iv:pIXLbTTe/+KtNmrXru8KLt2ZOm33trf9PA8n4FkNFtM=,tag:K6kmbWZTg/l1DWNzP3K/Hg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:20:08Z'
    enc: CiUA4OM7eCOb/huoUx/UC1ihHary6E6/+f1YrlOw3tVyh0RveGB3EkgAmy+ekgtRfhFBNYUigVdCA1uQLN3BpF4cAh7S7XVPDj6SkLg1jRYaxfhsT8jhIal3t6d3kaeYPQyE0qVP94g08BEHudOKbp4=
  lastmodified: '2026-07-29T19:20:08Z'
  mac: ENC[AES256_GCM,data:rszaQIDDReWKWN1Y31upSNBqHtxi09NdaIMh6K/+T5MEzhXau4YjPaVC0NIU1byfOaNg3eC5vnDfJEHwrQiWmPngcObmJBgw9GL4/dhf8TTeG70BE7t8tYxnJN/XjJnhnifA72EYGHe0lB/+v9OGGzbXQdCVYsg8FyG4kToSZVk=,iv:RXJzqjf61QyqtrbA2Xx4NThbVh7OuFUs8r7YaXemjzw=,tag:sfEYaY6aCedJZqsEcP4Gpg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
