jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:WexvvU+qnoErCoazCmaoFAL8Dne8VqN0n69urKGje0nKRQrFsRpZI8jcH0gJmblUsFSg,iv:PmQdNjDIPQKPPKxNj1d69J6JeeO+dX1X86iGsmx02y8=,tag:i5lTz8xHBy0U8fEa3Fk+ew==,type:str]
        client_secret: ENC[AES256_GCM,data:pEkG2Jl0xGlGM+17rrtOgCf7vZb91pLJ1ik8YerFCifSOoT3uoh8eNAFdvscHqwWRQK+7s1axDSjxap0PJt8qVRcb7wsmMWjnh1QwS+9t6OZwMWK7oo=,iv:rEXDViqoy/uVYt5I6lU3q/4Jz/zPi/P6qsrhU5GDzBo=,tag:++VKAHKHhsfAacTf2ulNhw==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:upVi2kOBFPWA6uUs79lIPFLbKqGDduijFvT2jTd9Q9lEal29bnJdy1XrR0oGmPHe/aDkG/tx/WiIwHTXkDbhPxIbPAMPy7PV4h6JIx0Lp1mTJMoccL4=,iv:psawcpQfiIsp/Yfe8s3CSfCWb2+bQKu3rVHRVrBkOsw=,tag:PUCEKykXxOhkMpek7kwxvw==,type:str]
        stringData: ENC[AES256_GCM,data:LfXd8qvT7a5sv82NTPcq1tLesKAcYEI629nUi8e0TaZ63ag3M7jzsVhKHrGnoQCNAjwshXWCJvfYl19DkIgA0VApJnbLMiB5GNBaSLRWs+iGGHujHHmd1d5kttvOwm5CB9Bqs0oZsfmnVLm3YXdgJkVWm5cHb7mhtKnBls3z8k8wHyEBb6CgtBnF/aUamFBprDo+WbblDlec3OTIV+DtoWuRJQy+mNp08gkMbYoN4rxOjy9jQLTRg8uIH108HDstbkKAluvWtXIa19Y8FKTazaIhLgER3MsFsigokOhZiROo4JwgRcJEbCB2vr0D7vayJPEYt3hNDeiaUCyzK5xO4VAkfO2/A0Ltm1nvK4zHBXWsvQY3jXuPl2ipZG0vk/KfgDIvayQE+85IcBH6eb05HUCJM/UNd47oS6X0R//bD4EzrelwykomakNIT5oQ2MUjnOKsr2fnltzQqASr+6GPTZcCdsVEQZzGCvZuDyc7ODFB54pajReqeNHHO6xX0kgSXDJWpw0O6G8jSded+eQM6LyKFls1JPrRcJwLKGzsIBbUFGKPXBz0Y5BYMg4jBlh+zf+qMzQBxfdj2nKiebICRv1u4WEwBXxmrMYTF/P0JDU0mtpZJT8Q3QoxVbk5qBKJYh1ThhUWuPC2IvEENg==,iv:8swVh3vV7GxevdsfrTfFqHjab4v5Ok5LBDkkSm23qbI=,tag:EIvEo5TtL2sBz/pFetshtg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:17:49Z'
    enc: CiUA4OM7eGZQ7MNdjtDu6oWz1T9j5dQC5JGUmMbCJNIiko4Rt2pNEkkAmy+eknNX7IBSih1pqUQWVKXM5PulrM7dgqsHXxEaSz+TqijedEMZCRwvC7JAqgy2VS5dijOy6uFRENdA6s/EDF8iOq/Xz0jK
  lastmodified: '2026-07-29T19:17:49Z'
  mac: ENC[AES256_GCM,data:GQ/FohHeXtNN99HYU46n4WklGr8O9E0Shx197F6DvZ6Z/LMv1b4ELtFGQj/Kcer8xDhYQa3QpYv+5sMtOsRBSb6OJ4vYDapnszTjrsN+nFiG1+vwPXuBV53mWNCuQNLLuWYI9EynuNd7J8VMGN00oAeQIcjTx9BjUnZVfvCz15E=,iv:DwDfawSzmOrz+qpTpBa+Acdaj6sr26qAGAepwOhP7RI=,tag:4gX2+c1Z4WlbOn2z3g0ANg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
