jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:9Fljlogxtk64p1zKRwIf1qRSd9oR1KVZuxQSdiAvf3Gfn082ifZJBZuxXNbpV9rZnNEO,iv:y7Mzrn96PJpnjheeoG7NZGT6CzdcaSVXAC99uelw2Eg=,tag:JYg+IfnLXSZ07rZayPzHJQ==,type:str]
        client_secret: ENC[AES256_GCM,data:/bQbmXLjeCECGdIU28Kli3lsvUiUUgnsZTeMkvWWap8m8T9Xt4Xl6uA/QEbRmfDc5dX8v4Qrgzb7AzAQtqTHKYM6EexZPh6mYdnLN0lOFnLlLnudSWU=,iv:+EE4A9Ex+6RozUUdBleK/jK+Mx3tSoRv25iERCTFROQ=,tag:EK3CDWgWlDynIsBWhnujvA==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:Gtr20hcnEiXr2Yeb5+AQ+kX7qDLeP5eEacydjobZV0NtjEgCY46ZWKYdGSNr2VwtxIF3UlpV3se9pSJFNFc6LexFDa2S+/BMUuboGT1I2npzdSBp77Y=,iv:HEE68N754QeunQyHUUmrc9J68k/fW7i8t/k3PUhtcxo=,tag:Qqe95fM7pVm+DNKrxfQWaQ==,type:str]
        stringData: ENC[AES256_GCM,data:F62CEhlSNtS8VHePqhhdipG/DdlY+KL7QT/TdC/tm+UjXWt7KYmOZmZ/0jdZ13A92fFEriHodWhkr7kZDOm3z8GfXwAsxURpsVHYymLx0WIqiIvJLJFgzeoPO5LNeKIW/DmzDRImsSoB5/PV7t5dyS0jGz+ZKTlhsTdYIOPBPkemOe+OZd0m3ap8HV/7rvAh3R4sjlta++xDsUWHNTeSCfAlDLocYEVruJpS/09V7OhgEzDsn/4s+AWoW0YY+ZACDYbBQ9C4yoSsGDyFOMzJTxACGdxVSJlOczsTwY1Hzwd8Sa4q+0dHn5F4g3wNFfgPeY1UKSUzY1H1Efrom7FgsYbewatIeeI3NyB6PEHDmRC7Sttblo5+BpFuVUVl3oa5Bf7CZJNDUUCl3wB9VWBs07zNjGVgApJZ9FxrXXLXA5s6fZ8u1XCSPXyjE98qIVAz2NrDzEWc9Y3QS+TDYIDdNueJPSz+ZragDMfxicJClyD1sHnkCTxQVRl1fwjOhfq1jAa6Eo9zhPXcklVw01ala8VzIaoPiCW8mqgxEb/6J39NMQJxU1UMhRJe10xKta3MLlhs54hZ6PZydsO0NYV5szEEX8iPK9ThLe+3bnNX3NVVWwxLuk4KJ/3syd1eHhymEm8GAxyMxVm8StV5ZA==,iv:itUjEef3Vq95rKm/tIgN3sA3DxMCUVjmEILkIPnWrts=,tag:IPgwAfF+qgn+Gd4DRybx9A==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:17:18Z'
    enc: CiUA4OM7eM0uhLfdie4pSMjIkq4IVFhCXz9E/9hZu61UWrKEvmFKEkkAmy+ekjVrI087kgmqqoUAdVGILu12s+b+g5ktykiJHxelisHStkP4pIzX/Vht/81b3zy+sQgnJQp2KFUL5juTrDMb5ZreflJD
  lastmodified: '2026-07-29T19:17:18Z'
  mac: ENC[AES256_GCM,data:TPzgAwukhcJrCLc3myMhvPpsmdYYHQF6E6vuNrIi2LovFz64aGcyjefpaBH8tWdYo95QjETGQaA/yyQrVjP+YZ1gixaReLJX4/aslRqj+s3CbYmTUa18FTxrgrNMF+2VdUGLImbR82RBAiDU8buA2EnVtZDBDnFKYIPgSZST560=,iv:VPFJUq39MGgO/1tuLGS1AQ1GjnzlhwurKcR+7yvQn8o=,tag:WdGRy3JZprZns4rZQR3t+Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
