jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:2NhKGaVDfi+yBLq9mMfmhc7L1QmShVAR96V+X0eGYCHq16/xwCtBqrYEGSp7kRGzZ0i5,iv:wGJQ8cDFb1YB3wAGLGl4ZnLdnkeM2AfMUU5PPYQZ/ik=,tag:CvHyBDv1N7g5FCRuQSOBbA==,type:str]
                client_secret: ENC[AES256_GCM,data:hf0lwR/5D6XYnVfBBUcMfVmFmYfuUVDzYShCFGTaIfP0yyXkTgypXm4ROUMTSOgJNsfHVqnqApBvRfjx7PCO5AUv831VVlTgDDwY9mhMStTGfAncYbc=,iv:910aArm5Vv8s6rZ1Xf0/Gzul3EnsmnXqUABpEBglt9c=,tag:tzqtYVdKT7RijuRvKhPa3g==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:EgqHhm7r/UYtpkyR+ncfgYE8ehftibrhCA1ozLkeKq2t6Dyu0BJA5Zmsig7WXM80dB4dm+lODTikhovnkBNPuw==,iv:yUCCJteFgqwsKa8Y6LbtrdGuqaX7RcVb2ztoroEBFpM=,tag:IsvCdrImd5e5G7lzn9ME2Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:18:23Z"
          enc: CiUA4OM7eOpZqmTkwTeFwVLypxBEN2PL09tvXDaXU9zXdMJmVcU3EkkAsHDEl0EQWeF+wM4eGeKELW3wxtyjpT6/mt+4/IAS339zx2aIldSQ64gTam2K4pATILesIPWmrM/EHK3NkLCs/P90+weviY8J
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:18:24Z"
    mac: ENC[AES256_GCM,data:nzAehb6ugLL43UbQn7sKKbbhLky0COIDLDI++4PcDsZlRS1BVpwi+1y2WQQsvcqGJh1gTISe0Bn2OQJ+fdcxgzkQzhBMrGF7MlwON3yFJkd6cw3YQyYDExl0DD0E9+F+JLJQJbcmMOJ28JaOjlqDj/DJh9xyAfxldkyZqdIPqXk=,iv:03pjRyukDzQ5dnbPDVeM3P+wkoGu4rkyUpAxDf4tjt8=,tag:N22nCP+T3CPgQxCPAhI6Mw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
