jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:0LwDG8DJ2fLtn4cXYMso4RWrbU/9JZjHUGzBBjXIJDmdZ4c7+oaAxWbnT7PYcG53W550,iv:k8cc2ZXwv/qsYbL6ZV9/k3ajW6Cm71JeziM3qK8V/Lk=,tag:xej5Ys14Y2YMec/aMrxqDQ==,type:str]
        client_secret: ENC[AES256_GCM,data:00CCZUOAtB8FjGi1uXhcF0D/Z3MzqGPfqReq0mxn+rIZMSN+bO/84O2TVU7O0TnqLXLKmq1AVJRoexouSLOmBMi0dH0TJPLM1XAn58UCEZzQwVjnukY=,iv:QW0e+UnHMMLkFjFbLnMd4XQCcA5Jj2GbLoKk8gLN15U=,tag:vV0vh8X4XheHRopWWSApDg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:qa7VymWNstJ1okH2jJgGViPvKyebAivyOGDiCAETdbvED3Z+jRaTQr4LCZCGypCJK3w6wGMd360948WRaVuwImCsvjkZ2OQSG8TVLj52k88eViJjRb4=,iv:kLkRJw+NG+i2Dq/J1pbqT4G8furUgYrpoNacUtENZ3I=,tag:rHrR76Ot/nKUHlGRDcQ0bA==,type:str]
        stringData: ENC[AES256_GCM,data:DFIb9r8KDgT3fwoi9SJs94R26uiToOztLToQ5C7G/BAZlfpDKo6KjMB+q7TrxBlcuhdTxKRkwFjaq1TRMUMQ+e0YFRjZVH9KNhbH2uDz8zs7vK5Vv/VCpVZJGAW/h8yenHn2QoD69LEK5y7cNbmJ1vp3wUvN/MLJ/yNP5y1mx/ahpoWkx9fYNBoomdiyPW9soSXAXqPS0kndwIS/D7eSfgNygFkjNapTDZKll/AHcX2f9mXEAw95qsEEQWm0Po3fDtLrObzQFl0JX3MfiE5BVIUsHDctkedjI+q/Cd6jf4Pg6QWK0ZROrVbE5Qr8bBFIxnbSXLKaSml2F1JQ/6w1xFZ8afGdZL+FpqRVPHfxJNnt3ip13RiPkV5dd8GuZY5CpB8AvyOhCvhKsT7XFdf9RH8MBGRgsnQfUHGqjnBmVupLkiNVfjq8p37NcR9nhQIlnQ6TcI3oznUQXBk32TGZt8RAV5UFcJgpJ4nS9QcYxwxrnxYDNUGEzX9xxt590ny2DhFqw892IS/njA4Z3X8dpwBMflNBbnGkxkT4wjyUUn1Y4E19C4HdFl4jz8zKK4iOY3vQ197K6PNdtelohNDrSDdoBPQ8/NOgir9iuIa+SXCBlUKI33rAVuTTzTrr5BVjf2hMY6fblepeuxwwDg==,iv:QiCtM2q9410lsLfCa2ysoNwZpX5DFX/KYQdJzqFAX6k=,tag:g2faCuWpdMnk03dS0MWWcA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:58Z'
    enc: CiUA4OM7eD3iDh08o6b1AP5XeZ6DUlz/6UVOgLLV3BD0i3uedSL8EkkAmy+ekrlv63/TxbQTmHCYqbGa8ivejmuFY0Eo25jCP8oQS1fAXU0gq3uzjBxT121SS/Vr+0v8EcYTVCBp1VTaIuKgCiREM1CC
  lastmodified: '2026-07-29T19:18:58Z'
  mac: ENC[AES256_GCM,data:aEFZyhzk4+fCaxtNI6N6t0GC8ljUb3gXmmpExFbn2eQMaNIcDOX4VsvBVAb7iyoSRuA3TuHvgHidXzfVsM34WRWEH7XJpgVxtKiKFwvklgV4mwQ3HRyEJHZVExsF6Mwbf8A8plYgDd74GXMJvz4KLEtzToRhba/mZ5z8kXv5SzI=,iv:v5pmSks61gLEx4m17UaEpNF3q7rsD5x/E6Y6b4Ectic=,tag:G6rXeyKjawFUL/OD1Vub6Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
