jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:Ub2sRHKFht8iPCD8SjYfJx9UiRJlVY3J5wRwjPTLu5ec8aXtWO2nY7MzGQZagUlJ2hp0,iv:LgIx6LATIR2TttdW4Ch2RSrNnHlcjKY1tsaQMD7HOAw=,tag:+jXrrdNy+cMy30bJVEgoJQ==,type:str]
        client_secret: ENC[AES256_GCM,data:O9p7ElFKXuEBm/JSy6oWYgz733bkmg7K0upIrOGVL1ZnUcclJ5YkPXFxsm72MxWuetD4VVk61j13FYriOESkOmwmUKJQL5b76xYcBMyTaGlMiWhvEDk=,iv:FbhxGzFqhPxgHdvrCLB7+myLzHd75H+dYxWJG1k3JeU=,tag:Op11Hh+2yp4SbNRgn6SPdw==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:jmxP8cgFL1jY1mIR4JofjCW94BSLwqbNwptOwlDEnLIp03hg6QGI8T1h4/6S4Goiuun5ZsSCPLzVeQu6rNM2/Zl0MKHaOq+7dcyGzvE0pD1h7CpIvKE=,iv:T6+WbicIyBceshMEKBvNMRkNTgbe7iBp3Aneyw+tx6k=,tag:km3meElBnueFW053gC6kjA==,type:str]
        stringData: ENC[AES256_GCM,data:ISSisdfeVuEBa2/KYLrRhpD+xiGRq/xulVhwSVkL2hNZgOMoxW+ui6KtgkGVSALkIoUZYiHfdzHbV3mdRc+vLBXArKI86Qxy3NSH/EWTLj8vJZN1ZPnwlrCOQSor8FXOPr4lHgGvZM1zy/LwfOQ3dq1/GTePBLafR49fb5cWMQ5BvhZ0qy1BAYXRjGHcyRgJuP6bn7m3mxkBUHuP+GMUEQ7mFPQxN6w2wcZFNfIg+yBUXyEKbxmj4r1VB4ZxH+S7rYEnDAxoZ9qmNMQB5a8I2bnIKl/ZbYSw3E/aErs2rjxhMrvWjopC94dVGlRII2qepvQ/WjutQ5EIYR45AzwGtdxxZKFw2WMVewtHbiRHHMLhTcFqargrgoRdD68T64K1MPmVBgMa7SUrh0bIGW7S7LRilI1lA9iOm/95yIOowLITD33DYreOk/VS+b08qZ9TsMmyeoU/OiiaXWRRfXVOGfKDGLq3fMmGbgH2nWVybGbO7arWfHkTxQsZsNJ8Mfp45afmFZ5MmlQf5+rLZmG4SBdSZdq/pI9jRARaxixil4DfdaLDRCAfiIzoXWZVtXBRgy6qBDO8K3JaLQ2tnKSl45RGca6dPz9Fn3WeJWo8RReeMCjbAIz83HemkXrRqkZ0JFUAz88JTUUXniHbuA==,iv:PlhhMuMkhQ8SKuuKWjTcecCL6GB+C5ETLg5dTcOVNzE=,tag:/5S/ieZ65Q4/k6UEe62uXw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:59Z'
    enc: CiUA4OM7eJsw3V5JGpcw7fmzbqzTeZrjjnr5ECO+GtYcu58QNOXREkkAmy+eknzJS6X9NGwny1zNruD1f5L2sy6MdjDi4Z7Vro92YnGzdrHTlWRE3B0l3UieE3ivmXQJlNlpGl6aTFUE5iBXFDNcKWbt
  lastmodified: '2026-07-29T19:19:59Z'
  mac: ENC[AES256_GCM,data:0o1l20zIzEW9QJR+QIATra/rarNqDXPam6ehXHj2XP/Ea69VtNdHCJisBaMnKmOmh1kuvB7lt/p+sUuql9XRlKkPKf4Fcu9MKcPV92M4o204VG1112FlznOiUc5iGPT5w2OIk4+ksUPjafMpUN7t/gx5S3g/mJhfn8hzyUDwBMM=,iv:Ev/A6B8sUX9vp/EkooQz+1o8z4zXjK2tr9WhRtag8W4=,tag:ZLh1jaquSbTvUT5wqItANw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
