jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:SwkAypL0IKSLdU4/qLvGlk9B46BkOAni4bGtZN1qJCQSMa5bkMENLetVgI3k1HUgmczc,iv:AeFlELIP2wDUeY2GB9UkS+9KNg8QWYzEJBC5+oSaijM=,tag:mwqruAuf4yCqV0iWCFdylw==,type:str]
                client_secret: ENC[AES256_GCM,data:On7QpddGFHyDK2h0kpqU4FSUkJIw6qdkZtSYX5qDLxCRA1UcMMfuGCvbKJkAHxvynpRvpYGhzIY27qpj5lOjQagVLi4zTKuS2vy5CxRk0sDfhjzeDpM=,iv:3iICDy1aGlpyQoMbUSmZiUbNNUNUMcCUel/Kgt0Uja0=,tag:yotEuDkKhiPhhK0fTulRGQ==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:sv9A6XUD+GDLEJlXsO1LZFpGG7DjMTmoISBVRge2LK43ugw03P+5glTzRMSGSoiE/sMmSRcJrBkocXx2k8GGZA==,iv:1zPZTyBqOaw2WaaIG/pbC+VdY6MLC7wJI6JOb8wbC48=,tag:O7SDNIkn8oWfV+ItyvOFZg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:18:00Z"
          enc: CiUA4OM7eA7Sr0rTc1qt4Mlp+cZB0vgrBs/PE43/BXEXwr5sW1UFEkkAsHDElwFkov5/o+QFyorq2N1I+t2xTh8aIVTJwOABM4kfcm2D9nqbhpq8UgfgbGfgcUtsMjutjUVs/ql8SCVWwDFzkHukzwt5
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:18:01Z"
    mac: ENC[AES256_GCM,data:gEFUTFUwEaN/C1CIT4w5gNkjXS9ciG/OOu1Y98nheCTbYz0t9ntNnGelzSXhEq9V/oJ/t0fBFD3bKXUwO+vzxURDWfP3W9aLsPwoV++FGcmlpnLkJNaDacDqoXGlcNktn1bYaEZNmIXsgb3tpTO6pMntWPqlvUAH3ys72BrZS28=,iv:5GONDc6iXqfeDmfjLflgNZAqr1ySYeY+XxZP6f+Up3E=,tag:SGSNi62ftXC5eBRoGYcYMw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
