jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:rBHbQj16AzVOKnEWuUikoxPNclW6wd6zx8nio+jkmOpACdkd5O8MfgHTr80skbWxisYX,iv:MtWCkhI5N/Tml08cMdcUqAL5f4i3sbkmjXAGdGIrBzw=,tag:UpVTzUSwoDfIsHy19LcTeg==,type:str]
        client_secret: ENC[AES256_GCM,data:Tjwutm7ymlveFFnowBgmsxOKkfYhD0UZlRb069ahflqSkZTQ4zQDvYRoewAkSSF+3BPSUWoma8iGOl8LEapmKxqFfhrWdpkLOp11INJv4368YyY22iE=,iv:+kB/hdkPPXEHp1U6Kph4+h0BlawvMjgXroIh48TBiwY=,tag:x26A8C6rLyeqvWzTdBsiSg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:L/wL5CX2fE77oelb2Kq+IeFTmaAyW8jkt6qS0b5tK+mS7f801TjejqD+ObIefA+LHGgFyJvyd38Cjfvfmjc4rcXI5CCRGicUNmu2tJ4x9C/lrxNitPo=,iv:xVd35V3RILrVtwAoWNtSApo7payPPKOU+WOI8ieb4GA=,tag:FWhunmB2yuCl/AjF2eV7bQ==,type:str]
        stringData: ENC[AES256_GCM,data:adALmEyr8vUFHDuwpuj4nxCMnL7Eaic/DopMXaA8PDUAlSQ0ELW1JDXVWgzIzJ+055bGDuKhakGaYh2tQeztTxsKMzcZ071ffWDi/R5GFeXGB6Uvc2gSEOh9ifUQAjFKtNdaq15cse21e1w0O+5t9uHjdDdSSda6YJuRZhYHUmfedw6GSt8pk157EX+G2d0tWkK737lqF0FWL1yGu+6xGbDWV8f4t6LfZMkA1TEHwfZZSQ3jTxHo1t8mkynf0R6BUa/znBDopk0J9PZNBo7v2bhLftiiQhxH+Cniz/imjRUl/r3nto+Sp36bpxSUnMtxEKYuKQ3qo3I81Iw5f6s4DMbht1f63zEwroo3LOKWbwDGOYtbpIdDH78Ithg6WlXv+e8fD0k2weceLwCYtG8HQiV+ORGVXMi9AOlchEg6OhEFnagEbL7HbbYz+6hcbSE5SFpy54nnF8EIUMcgZD+H29VVIv+0VOwUEw1mCo5rHsyTDkiCPYyKhZscwdIjmrfrdcteGFg3OjD/mZXHrt8KlQ052NEdoKdNSsN0YugEa0eBDJqhlBtz7/igcU/d6vqAaYWc/I1dbNL7C5PIHmOYXcP8zRD7f/VaAAb6OtMjZmDEoZgXVuFtP6i+dr346GGcqqociV/MdSZa4zRCzQ==,iv:d08sfvmpWHKMMOvZB/HTgfQHKFUkfYkRgbR2D89TMbU=,tag:gWQpu5qNzXtb/6jKOcj9kQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:15Z'
    enc: CiUA4OM7eHsrmY3T1Jha0NzRxUMrFX+HJsGB71Fchn+OynkLkS5FEkgAmy+ekpQk3bKbCeihFpiyZbSM1P75Ap3vX6SQVl7ysOMZYhiFiLui5Qm23Tk549FIxa7taJu8s2LGsirLvvniXcezPHODjFs=
  lastmodified: '2026-07-29T19:19:16Z'
  mac: ENC[AES256_GCM,data:9QUJ2uL7RH1w51DzL7hD0cH5eP+sHr6CTmDL9CDpCvCCSJJbsNV6hGkPxF4Sk4L0QKmNPQ+qoPzJR8XL97cnlwnWH5xa6TmswkkTSYTjWPxpJWKjXw95Nf3RZiy9R0+oUt6qO8tkWbKuaYAaVaO8X19eeCPxAuXdErNRpkAwPas=,iv:HTZsx1rNenGBDTJAOrCOkaJcX6TpDYp1GQOPsS0K1dg=,tag:UR/2aojga394MLHLffIesA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
