jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:ZfxoMlIkNE8TMFGzF/nS6iINgvJImhDfAgKEPRzu2lIbRoLx7o8EhbGS2DNEyueEItwA,iv:8dZS6fCy/SI/ciPGXYb7ZQr7PDul6LzcUoPi/QwFq8o=,tag:TLML5PomKZeS2ZQoNxFK3A==,type:str]
        client_secret: ENC[AES256_GCM,data:N77C1sEMVII9AEDlD4zOiFQHWPp+kFPGuZRktA+WTjWUxM+iGS8SdFIP5RUs8Mhqg+VQYAdxgHEbk1VfkAR2w6USn+9TO0mhU2iP+O5TUwPtMFaBlh8=,iv:FNr52oTmQCsKco86dIPHDRnM2Y191Yp9J0sZ7Z59b2Q=,tag:9PzKgnm5KxKt0nUly+cDwQ==,type:str]
      SharedPasswordAuthenticator:
        user_password: ENC[AES256_GCM,data:qBMO7mnxO10JbOt63mnE,iv:9QrSyDsBvYbs57D17Ng16cQfIPC+bR6B4gWq6WTA1H8=,tag:xW+0A4br8ZHuTFImE1Z8ow==,type:str]
        admin_password: ENC[AES256_GCM,data:4Rl40F5t1nDvvQ6YenQ65ofBeotqeNVoEVxXWUgPP01tAn+hc2So,iv:EjhMX8+fVNsfX6AGIJo0wPuLybJvfaearUXfoEWPT6k=,tag:Aqsxjkad0fknMzxqkb5GPQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:00Z'
    enc: CiUA4OM7eIMVfy7qL5WZv66iPtqeoVE57gdjJNdT70ZTiLFXPGPjEkkAsHDEl6HcPNpPqQ1B7+7wZyVTkKetaiMSWSrjEnSk2TmtqyR9MVfIvOoLLGt9We6r15P6mjYhXtH+PAvsg5pdiUHtVvicpSOk
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:01Z'
  mac: ENC[AES256_GCM,data:Y7FZfxSnCJ+hK1GeR2C0Ttd8RgcTQ1Ya3fHzSh7T4aZmPB8Fvb2HL+AJpEz+5tpBYagenwl1b6bowKcpk382tQw6CSyyrCXDyr9MSp12xpWTqx3jfI2tGiNImRFxSTVaLzqFQhQezpCU6Ys/CojTTajq3JdaRS1DqyDpUO7u4zU=,iv:w4S9eVKRMQGXtlc6M5lFZaXthAtGIYEE27935u6Br/I=,tag:tpBv4FJuErPcHNpffrJYsg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
