jupyterhub:
  hub:
    config:
      GoogleOAuthenticator:
        client_id: ENC[AES256_GCM,data:B6xo39UjWQ07Q/U8AeZzl3I+a5kflfDyNmmNkqAvbxUgIuBwWWokVNmySvOEKlWhCl5nWtw3W6/kQ0V2kUC5+7TzMXn1SNYx,iv:Rnk62ZEyGMl/hq9RLZ9gWcNyJKneQBneImCvMVtwNog=,tag:PeDuRYwFxiG78qULRAu9SQ==,type:str]
        client_secret: ENC[AES256_GCM,data:lEsSs3o9g/Kt7MUG4FOmshbTNvz7bur/xfVq8byV3ugvyPE=,iv:DdxldYl7vQ15Z1jGPSElIVz2BsvyILqIfKbs0Szay98=,tag:OaB3V4LVJHWYIL5OPUqSzw==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:U31Cr20Ecpt9EByTkosIDZaCgIoJo5G3k91QXVbDw5nVa5gbXDLiRrojlRuDMeUxnQHM/MPohCtdRukv4gyMrQ==,iv:VE2DhybIQMIBjLUIJaDbGN+rN0L1uHQkftiQ7a7BUUY=,tag:hgIiAwN+7ma5KBuuOv8mzA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:17:42Z'
    enc: CiUA4OM7eIAwZzZTAplJp3r8iRcte/iUSLAdBTn87jaBP8PU6kuXEkkAsHDEl3UIO87ZsiIudOS95LSeijiVcxf5Q1nZb8Q5QBjxiuPg+RqzWGIEeQUgyUaxBw5nPuFENYlCgS5sIgOxdp12YgzSPpAU
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:17:42Z'
  mac: ENC[AES256_GCM,data:VcK2eF9EWP1LGeUWZC7kYaEtDlC3gTV3jTZYwgkKyb4F/36yuTkQB0cjJo0IS7umBhzmoW3HPypyVTY+9Lbcm3EmaPPw1zLCbwY0ltyg6Uu04aHQqbAY12P4G+uZZ4fzOLwbw8IIyvMs6EaQbFRkKUG+rwfR4RxMXpV9/bfFT9w=,iv:jv1plH2x/XUBfVsaljGWhnVirCqvK4Wx2E5NqEhYcRY=,tag:t43sIkaccT62EODPMPRnig==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
