jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:PfGT2xa6w2QuAyZbxOWOElaHJ8AhB4mim+0Bdb1X4v/jt0OVECkllmKtT9+fZEbkd6y2,iv:N2CD4guOZj3BNTNfCgmZPTjjcL4070oQMgMvPKrg0+E=,tag:ZnfV/yP+jtqLJclSgmGROA==,type:str]
                client_secret: ENC[AES256_GCM,data:2evkI3wkx2HeU0ttRJUnA6nd1xhX4UEAzHolgj1DakK47mQtqswqJLzBhe/9KbVz45exlUejIMM/Dd8zwcPU7AMk8PCV7Pl6CdgZO++rLHA+i3U+Uwk=,iv:i1XbRFUNeOCch1YnlmXK9IajBxyOu/qTpZNkDfdH30s=,tag:Df7gxdj3d8LCFf7Ujpq5eA==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:0aT8S8FEwXvWcfB3/9h0d1aimtwzTLpCI5OKtV7gqVe6vwBuODYmY3saFIW8NnOlgjbDrgN1nlUYaVk1dyn0og==,iv:4Rka3Y9fnMS8hJYK8wUsxUPTthvlxIwHF8a9yWajXos=,tag:iGiNtq4ZByy7zEvtG2O25g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T14:51:31Z"
          enc: CiUA4OM7eLPnqoIeuJIL8xVbp8sNQuTWARjWV2RPvs2Me+9/kgwDEkkAsHDEl7Lu9hQlsdJOeWWdQCCOeCoDJWAyvUqYX9KtaB7/sy/7302YYNBX6J/z3qfnf7sNyn//FxVbMkfrCqI61EMHyKh6DItd
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T14:51:32Z"
    mac: ENC[AES256_GCM,data:zkzHHz6DAslpjUtieyVh800a4hmo+nQEoIBKP1Sm5nI7OlbwkocObKDVzEvJGoH3Xt9odHfuDdWHBTAukeDyCViG41MY6plHuuXUEe5h4+QpYdMD9syc0PsNi+QvSQN7bUGs94R4xhtvyis3MTZ7Np9mjuD5esBulrURedtBWvg=,iv:/jpRkZnL9e8jwsqwnFRkUK4I6VIke9EUQCEHg9ESPUU=,tag:kky4K7YJj68ZZF/+0/uZXA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
