jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:B+MQDUOZo1wBoW7UoSVPFey/+/5c5E++XxcW9qnMyaPVHXiDG/ogcbq8uYaGWOLSYzG0,iv:HujjOrFgBpUHf65XDH2ZzT9Soqp2gGr2Kx61M/IlTo4=,tag:pze9pq2sB9wJvwTQ6wfXXw==,type:str]
        client_secret: ENC[AES256_GCM,data:qCcwffTUM1bx4lIBwiRtUHCUJ84UZeRA3RbyM54eMdxGi+Dx3GhA/un18qBsYKWNtSDL9gBIwqAiFJzCU8jLMAck/Co1eROdUp+HAytzzNVNcWLla90=,iv:eQBCqTvQiG1HqfuVdE/mQW6v5yt+yyJH1lxPT7PVbIM=,tag:t/1gookvGoVtJ9L5GsWUFA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-20T03:59:05Z'
    enc: CiUA4OM7eB4nebciOrRtQ2yTIn4Kev2pssK7iHe0shjLyY8k7yYbEkkAsHDEl1phhXY9xEdhPB1/rK+VtLMVx3oHqHLm0jZggpIfkoODt38rJipkTm6sr+qf7Twp0HqOATfdYIBayzyNS8StnpR0iMiT
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-20T03:59:06Z'
  mac: ENC[AES256_GCM,data:Z5/ngRiynlQ6Q67PgK79Iy7GaAH1INxw3E/fi5zOw8wWtbo7aAEanVZR3Rd7WwTeKryZXVN7v9Jd2oMPxJb3EoEv3F0F0OhW17jDkW7FCJIbxD5eFf0059cbGEeHme0G1E9Q46Ef4iXK0rHaWQSnq0KDxAqztJbX9CbQ/T9I9y4=,iv:MLilOZklquXRYjBrzR7HHm3/5DJ6/rrmliA7kJx9wsE=,tag:KvRiWnwsoeRF1L7c+muTPQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
