jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:/Y78kPlAK+EJm/g699uAYkGiQnjxSxIFCnCYYJCwaYDjJDUhPnF4LJSVSR5CKrHJeIMv,iv:srN0t19lZroSVARQ6UpKqTJztMB7HeyXAiOEWQtFXwM=,tag:xLuIXqXzQCK7q/Q5Q7gz/Q==,type:str]
        client_secret: ENC[AES256_GCM,data:9fMitWvBWfwaC8VAwEvAigDuO4RUOMM1REJonnjS2a4NWnJoO/yTcEzev1ksijs2sd+p/OQdL4AL+DQ40BZszDir7wDuOyO8vo5nROveo7lrnu15IBM=,iv:HfQNCkvJUPjwcIJmxPCy+xyBfgutxLhYXK3Py5dzyEk=,tag:BpkP7lmKz9q8+DBb69E9lg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-09-29T00:43:47Z'
    enc: CiUA4OM7eN5/USaSUEEp7RrjMfRAsx3llAx4PuSkrY48TlcKlhdvEkkAsHDEl0y97B5UQHl7e+jGuBAOsduCAzoBMzsIbK2WIFQlNgMFNX9lIoFojbupCvncxjfC2VtIF4+xndOqaJZOcFZtqny7a7up
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-09-29T00:43:48Z'
  mac: ENC[AES256_GCM,data:taNQXtIxtkFRwpT4Nxf8WvefYIKHrW2aSzEWcBw2D/0KkE/ViDxvzxt2NKlA64Dm0w+pSXdutWhEFOTikLXMNNfKEucdBSrljdvFlB9f+ZQN0/4buaIq9WFelY/+2MA1yFyCJ3iNn2X2ZnXms8+NkaBqXakm9OIAKl8x5shbuqg=,iv:in0oISD2OYg/r+6Kgy9TGjUZzEpp+jw/cjQ/seR2I54=,tag:tWmSLaDOvw3QuisByyogtA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
