jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:3FbQvmHmQiZJSvi022Yz5YILSA+N+39M/H9ns458oQQskuo60KgYs7rVapsJRIIOPGrI,iv:DqlBgLKLomdxmkqEWEVe46A5ldvKbH7tqFDYcE6RSXI=,tag:Kn+ldhDSgQIjqqhzmZJygA==,type:str]
                client_secret: ENC[AES256_GCM,data:3iKy9G3DqmksGq6aCgKiem5NUa/0BOO1s5Ch8lUt7yTWXBL5rGsxqc2LmQloSAALZYKQkzBW7+zqrUd/GbPi+Y9Juu7aLZLYVs8fDevFd9v1vL2X4IA=,iv:ojjF4KwlGeBS2JKTKzrqKZKuJQYzegLEyzg4j91shGA=,tag:3WnTBJb/v23olJu34qcfOA==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:fgI49haQi3W5qPimnQFHXuHtJpA5krZcy4dCyot6jxNfHu8yMH9osydR6DMcMmDmgsMbXcIoxHzAGpXMfkA5TA==,iv:6QN6V6UIyyixqHc0j8tYP/PFtmJ5L6PHdTafSz+lB+c=,tag:D7DR/BzK7aOdXUpA6OwKxw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:18:19Z"
          enc: CiUA4OM7eG8k0Liwz1BBeyP5PpJ0wRnsDc+UsuDEqXj40uZQKnmAEkkAsHDEl+A0wRp0/2ihUFivJgcDjpg2YqZ+D7veHNnSrM13FRiyEgwsGtPYeQ+kf6AY+eAvO8z5YyxIYUn028JtYELmOS0JS2bX
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:18:20Z"
    mac: ENC[AES256_GCM,data:TwqO9UxZNBjto5uyUSFJP6LxpDrjAyQYeSFLgGqc0/FGllm8kk5XGhlR/SNfKeSoVR2Y1TxIHcowP2qBYb3jLHDSK6pC3gMJvLDpQkH1sXGDPOx9zMF3cGfPww6KVAc3uHP1tmLKRzdUYyrwuNi8A10zUomWTGMDERfJSyvF6Vw=,iv:rPL1FOkOF49a15aCsuiha/vF1Zoi/a3RQVvzJj2KooE=,tag:UBTYnSw8GkivA2JVO5ez0A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
