jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:WUWxdW2wGPJR2+Tl9Qg8IyawR5zdeGJ7XcWY5DLeCRxvI9Yvzt6XjUrvOP4RmrQR5kYT,iv:QBJA3WWG/49qB0ApssoO0W9dTADBiJmN27vxV8vb+rQ=,tag:XPyTnLY1bFkEcbD6plQ8sg==,type:str]
        client_secret: ENC[AES256_GCM,data:MA9J57li4NpBNXANTn3VKjbjhM5hsMrYRwV5VNqBg2dGvq2pHVU+5rD4IaAebmdXoZJ1PpMEmXMiq4C2Gs9US1PJhw7ZwP3UaVG1uokzd112i9UvWZ8=,iv:vwplI7iA+d4SfQcDi0MlTIaSxjOFOPg2FJLNpDsMLKw=,tag:iUpw4z9o4H4r6PThAuFmOw==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:1gKdMqA2wAfyOHuQEGdpSFIsETK/1aknczOIkryvwxBF0P4dMM2FZ4L9GKvN5eBwUzJZ+rU1c5tVy+bxydQWfpH/EjujSBIrFyQHI38j9PMPhBUWL18=,iv:DywKOXPnQPiTFSC9HCosomMB7hpzFv9nAmcRT9IhlTo=,tag:zkWSAqmm5TyGTS5zOdXzLw==,type:str]
        stringData: ENC[AES256_GCM,data:tvz8vIkopil14Gy4k6JIoKJCSBdOzlEgs/DOFBChrI2VdTJ8h4oVhe9lMLkVp8o03Z3US8OW7TvfJ9wU8kVwiakF3adbioHDx+GGhFRYnBhueKlaMygcNykTrrXr6H0Pq2WvUJyuTKsHXOtwzmKDyUrVW+WFeANP2gLZt2xsT4sWz8TNQKtucBCQ6aDqP8hav5+HE2p2FCxFmCVhIy1vefJ6ud52+NgsrPewmsxi6+ZjBMnS17rQDZraDsyREs9cKO5ejT5XiWykmSTEm1y5BVBia+FHw1lXe4jgZYrsklnC13iXp3P8VtESaoAJX6+ljz06lsDzNo7iCCCAaSiuix8c0xp8tUGutdJIFhPdCGwf/yaYqHD5Fg2UL+imCWW/rMsL0PGXu1kYaSY/neXfWPEDeZK5dNk5ABnmYRR/D7mYDc1Q6lPPH9gmzQZXGG3aFl8ELDO3yOy5QOnQMIJvSRkKHlvIKgfmThgVste678IB15wJf7ivCCUmRu0JQSAfUrA7T5dpytRMv+k7gEs4twg878wihKrS1V7QAnTPNAhnZkt+qRtTfiQaDhBqcY9Es/MWewB1JrqwQFXZ+kp+xKKMswo193a0WcMCT81lSExDY0A7O5W9XH7C2Rq/snszRBE09PWC+BVCa6gzFA==,iv:0b413y+Kt+UvznvF4ecmkxIWgATRI5oojqoG2Jsv1A8=,tag:EVQVLlsz4Ce6UZ4kF8w+mg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:41Z'
    enc: CiUA4OM7eKYLloUDTAOLHTY8GEf7nOHXHefbmoJphLw+8nkAhAM8EkkAmy+eknNrWnUOIwX74RXPrP852Jodyp4NwpjDDYAGZogr5ZOO4KMHw4XfCMWRt8oTs1GauoDuoUMme/a8hAH3ytrf0IvKF7mY
  lastmodified: '2026-07-29T19:19:42Z'
  mac: ENC[AES256_GCM,data:Rm65zmBGXIWEkjjK6O75BICtNYEmZbggEmEGdaGPEandisPHzVRoCx/RaVnbJ/8aNxaPYhXxUI+fJ3vic2B3zTOkAVbnIaFFfO2GInhesJ3r83hvOjoEetSeodFru2LTWI+KrNNeLQSzKtXBc0PcW3z86p5LZ2aHfH7bHVMU3tA=,iv:dPxFhy/q384nmF42uaNzmc1Slp/KNILOdSyqya0Ftlc=,tag:oNbcjKOLT9vkHnyq5kI4BA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
