jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:rMdIcMsnbqO8x2AbKyIuJI1IvgAV8GoIN0CoiZHCisMCpFrMnjBiyxMbDUZqo7tpGc0=,iv:R8QQSRkVzJ+v0zL60uvI0hL3MNnM0Qb5FIbBmbky8dY=,tag:J7x7mS8UBogBE53JrIc2qg==,type:str]
        client_secret: ENC[AES256_GCM,data:Ui5ivJ68tu9e3QCUhoIUd2LxiUE+a0OhB07Diy6euzJsRxFuGllr8XFjOe4lxQX5fhPSl1a5iawkiB0uRBTc/YhkEfggFxmfphr3uPXc71FINwkD2oA=,iv:Xy2JML/oyeF11QUGEZAvcwHKVS0vx+3eogYuaGZZbVY=,tag:8wc2/gK6XKbme3O5IraA+w==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-13T21:15:44Z'
    enc: CiUA4OM7eOtLiNXb3mPx4Ql3fUh2XHCVuupUpnCyae/Kp58IqxkvEkkAmy+eknRExZTJN2jalATsAI5juRRC+BvB5dNIjfbVQramPSQsAnhsSSByqNX8uKL4xhvsbmLkrJ+YplhoRepnX9s5SxpXCQs2
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-07-13T21:15:45Z'
  mac: ENC[AES256_GCM,data:FpYSmF0g8c3MZ2Qn9Uf9opJ+QF+b2szz2P8lYFANEVlXpbjafrHB7UVDdSeOq0ufKQxpWNzQxu8vPYTRCnRuOpKNx+Jn1LtpIj3097ILfsO6OD0EieK1ZwxlBKLzF81nGf5d591xJCLknhl66bbXS9D8TyP0BWuLrC8WnfsJ4/Y=,iv:fPp5sLJNnr0EAHLadeHv93qO59XFDs1Jt7URwkrzq7k=,tag:7IGkPCGzDYpvA9y9gvKlvQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
