jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:flm30/3wN0hUjsqBpXHItzngEtL8W6NppS4S9b/ONmUdbQlgwt2fghlK4b2UkbvJ5ibc,iv:xTOZZt+4nT0y/08hUQP7x9L31Au8axdPjJPCUoqYpeI=,tag:RdU9JS6dMrcDga51c+WRqg==,type:str]
        client_secret: ENC[AES256_GCM,data:ibmvV0l2hBDVqFHqDNVudeetDAg6nW4/XwOi4g0LqJ81E114lSbkI3vP3uwSdIrH8gMqnlX3RWkQ6dfA1skI4nfaikfw/fYpAYC62RByoL3bnwhF/WE=,iv:l9CosgjFgDKey77yWQTjnlE0mT+FtPkq4ol/Pw1+0qA=,tag:JCSKDGGyGf7yqcBZ3QaY7g==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:52jG3DYOCE7kRCb0E/tuc6EGk/e5ywjiyReaLw24byRusQK4dQ7UjC68BSGLUQBgi2e1prsUfdW+evaOl7H6ndXJSNYAXuQlb0c257/641zDmKItTU0=,iv:c8l9m3xCHsU6hdsqIk8Gew8JH6NH22Wp18SQqbVtVbk=,tag:6X7qAEXslRNH44lkxFKwNA==,type:str]
        stringData: ENC[AES256_GCM,data:8XjtSTkLf8iGOrFEFy3fopHDDZXElvwnyOa1MTvUxRwJRS0vK6NOoJ8Fiw6ZnUqp58eRxAUmvjracNIjAG8BVlI64UzkHMwzzxo+UP2VgIp3x2ya+5QMvTHeZRVKDXlsETqxmzBCxhAmCBxShakvhMHApt8CB0D+DlmIh8RPKCNSQBK1LqjhQWxbtvij4wyctreAQMOXIdo4cE/YPWcKbMPYt+QdpsjPE6O0LADFFt9BBwJc9PVxZTaOhpySFD6i3/iao8tkg/g6E9fmCtuQKXQTyBZSv+Wzr7N14TY0PiRjeyipuQY/ozJbUijaA+CCV1zoKQazKHIxG9LbtU6hFMR3g62LFUcYQgymQ7Q3qT10A4Oxed/5sD0qTUVTh/MxHR/efATU8FFWshvbsAWCRnpNPcFVu/u9Mxcil7QiVJ0dAX/piaz72Pjq/BI4ublwc8Nm56EPpgonqINRxV3hhNdHYqDtrXvsGcrT6GszKI1XbZ451SFeHbVbyK+AWunoTiQsjeH3EJ5e3c2j0n7SDtwW4VzLY3Vv4ol5fkaRpFmrUbzWyOZ4AsAYV5zXKtNbCpshe5uIRjDis7iab98g/b7/kyQzQo9hpNPTyDJGPfW93RXRXsqHzR11ftQlNBIL+Wtz1/XrAUKeR659gg==,iv:/taBUOullr6FsH19C6nE6PcVU4PugoqW+G7ZlJRhU8c=,tag:jqn2mAJNY6Zh96eTqVS/+w==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:20:01Z'
    enc: CiUA4OM7eIRuRpi3MN5/415zK/Gm3f/5I/inNr4Qz5JpjGNQG0VEEkkAmy+ekvVswXj36x9KhFjsa3R8O1TYA3rL00HWJbL4IhCiIqNADvXct0o82mbrccsQRc15MfUvyXAEt1RwdOcKQoYPZ2NbBhwP
  lastmodified: '2026-07-29T19:20:01Z'
  mac: ENC[AES256_GCM,data:ZlS8id4U7w4vRu//Phlw6Npl2mAVpKu5uClUUXdtBpcUpBisSDDkMJe4whpwLKQw3yDAu0D7kqUI80aL9ek1NV7cEZfheowAfUGq9BOe1f/DtZQzUrUc8TZb5eMorzOh2wiLKlM+A0SuCon5WH9w5WRiV/ruurw9hP3bpvb+vWk=,iv:jM1Nl2EVSUkW5uY6SkQdqok2sJdphuDJL7kHXk8DszA=,tag:uE6KD0ECLIbvSbIoLFSARQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
