jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:xe7oK9MqHxZOoyidKWnsdgioN2/k9TzE+jeum5TtDgPRjWnXtVUEEN4Mmq5wKpGlxSO8,iv:anTmMyJzmdANL21AG28jKSDqqkA21bYv1g5wKtQrgdQ=,tag:MOCFKJyTFgidRP5vasfsDw==,type:str]
        client_secret: ENC[AES256_GCM,data:3mmXY0bJOwVSyjWwFOrlLwyk6MlR/ePWjK34qRLITw/x/ihs1gEne20wmTDlmjINoyRmTeABoeiF+ru0WhDowL2SAUyw9drj3cg2i1q9uiSG6QiYEBo=,iv:szYGaMriqyQzf/YVG7Am8PSF7/uQSoTIemxX/U2q7Fo=,tag:Jn/rrewbqv7rPob68J9OEg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:txFvv5ccyM9PW0UgKBVGAzr9mCDV1H+JqVR8tuy18sZ0cSAbpB0NMEo2HQtDJ3W2HHZyk7C/Jv2qIquUOwgu6l3LRqCDhU51oP1FOmdXPSknvwN9NEs=,iv:dEd6tzfPePWR638kVuWt2tr2vd0l4E7BH2GYR3QKqqg=,tag:k1+V9BXIm33sfd20Gcj/qA==,type:str]
        stringData: ENC[AES256_GCM,data:9elZ0vy/k4DaVsXfEAnEHr0OlC2pH1HUbl5R8haaQh4A0rfLcJYnWzRyUR30sbI7q2leEfv8MgSBWHNqTmDy7s9l0yFLe8eO3EeT8xeY2g+QzWqV/5q3+WUKo102tgSTdOBiY9VWSpGKei8YlKn2JNkPBXYTFaSqgkCT7R9H8sZjqEpMECvKzJ9UafeRhoZvWenVw9fug14ufdeFl/+X50mzoZJc23Bk9XJbXN+QuiW65/ip4ZTJRhOzpWxlvoo+UmMpwI43981IS3DGBI8qXLWCf6K8TAmrQKu5MTMrjNvtBJ7LxoOxw/0by56aKMjzKQ7Ovte+2S1ufJ64VliekILFB8/ysRM6Q00VUh3YVdZcW3UhnV734/9V9tKFFMTSuAphVjZOpHfhfxyKn/gdhKr+n50HyzSs7UdlC3dQsPUYlQHnUOjM295pjeLCee8hVcTa6P9HhbjW97SwKzhwo/ZCljjdtPm9+KNRb3APGsTPi6Qbaz+9rUzpEutzm16ZMazjUk/zm2fy5kDfSHwV6nuOjhUqyiWNgFN1Yye3khqj0ajObisWea+pg4iTRLTlMc2vZ9ToRe5mU9ABfvPmCZA+b1C8vsYoNMZcWbg0bp1i4EaoJYWU08LBwJlUm4U/wCsX66KEJsC1iVg+zw==,iv:TZlbsrvlEHWtStqR7oDQ0AiY4hxYOYPABMPnxILtAPc=,tag:EPZS0HSJKhJnSqjoqm0BQg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:20:12Z'
    enc: CiUA4OM7ePyNvE5dFH0kUvT4lCKJKb3OTG9l3s6ucEedTgf7lIZdEkkAmy+ekjtZZ/HiX1Qd6qzxrgEVLyasEUcQQtezaxNOmddg+/6MyNvH/leCUfzXeTT+iwJuQxxfVBbOgIqUlEqexG9MT4FOP9/K
  lastmodified: '2026-07-29T19:20:12Z'
  mac: ENC[AES256_GCM,data:Ro+FBs2i7EHVloBVu7QAvpb0d1L3u8nD2uKpL6mCGmNjar1JiCSghqWDvV6lqbrMLgZVeRK7xpfy2IBbh9DhbUA0LaM981qCUarG3hTKlFFq5RrNDXPzUmHb+kbnD0ayrbBY+o1Oq+r7d1kT+ypqAO+9kPhSpg4nhBUECMOGOgY=,iv:VS9C+xcu2HzChnvHntgOjb7Vb4LngKNWnkNRHc1AnuU=,tag:mXky22j7Pg/FipIIxrNaQA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
