jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:8qBPuqc8PeCG1cVCEyNrmia40b/50Wi9w9ki7bof9TQeiOGEvnpFoOfdzK4RjN601ZWz,iv:1vdpDJ/UOvVpzkidOzVX+Ku3pRimdkyEpTp5gMo/ZRc=,tag:3KtP1lC0OvVC1zuuwKgh1A==,type:str]
        client_secret: ENC[AES256_GCM,data:zMbqg7LKut8odg7tSon+VZEvLeTbWlpy8ff2q6RQ8Sm3gz25FPrj652oU6L0uZ9+IEHEwgRzeQHCLuXsMrrWKsnxAks0jg9T4qOj/N4VtfZiF31AZlU=,iv:36nxYbriycumIXMTfO5p2Yg2ElHnuMl3EDdTJQN4FAM=,tag:nZ8P+8V/5w/df8AB4oz5uw==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:S8lUSi3pSbCrANOeEPBRSezQ8Q67PnNR4k2n8R8oNwiFfh+necJvY5wD9B2L8wPwm5XZHttPDAY+8FBKJFE89A==,iv:0SIKQHNADVHESKeOtg+d3lhv6DCo0iY0Jpg9tzhn35k=,tag:T3PrhfF2lzPsM2RSv+4TTA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:17:53Z'
    enc: CiUA4OM7eCJkkYBDrucHjlumLrvbGOJS03rFbbs82Vh1dHcgPmgQEkkAsHDEl/T/R9UFU9qnPXg0RDurFq+CO8Lj1MsnauqGaZzrIkOiTZ/eGphb5wy5a+Nno2c/O2Yes8mj2bT0nL8mq0LxUZOxVgXM
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:17:54Z'
  mac: ENC[AES256_GCM,data:Y58QsRceRvaHHlhb3xLyMmYu0DD40AyiwS88KHFRdIHSVI6sY6cZB4XXCOjLDHw4KhVbNWKOclCMHHMPvisCX/k7KAtGW65oy88cNbrjrpEqrTFqk/1Schz8jkJRBPi+oqIX47YwNkqg/DFXt5xtnnpYSri2lSxXFb9hxX6HbYc=,iv:5tAXeDP7RVMkLmdujvw6fUqssymScuAVLusUjAyZsEY=,tag:Zi9a3ipELRGicXsu0jn2cw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
