jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:xuBIA55HrKY3ILcQ3JsdqiXs13eNKOl7DmognBqhj+bdC3FzZs8SSe8z9QqWBH+PFHLn,iv:dxh+FiekGPTuNm+pbtvq+OZ5aNwabHq8TFmAlSX4iHs=,tag:aEBBYEaxtxseXIUrsnSXnA==,type:str]
        client_secret: ENC[AES256_GCM,data:APNm//KYkbzxPVe+SKWRhwzXGzngxgM2xcLrXlG+DfJXRJi+0y300XUG6qzp/JIba/aj8ua85OMs+GzGrXxXhEq+AlmsLJd+eZfSXB99SxdiwtqmATI=,iv:A5sdtT5y4T0eAbS/yOoRF75eJGxWzjXTnO9NGP5bcjo=,tag:izIGwXWy8/YL8RFaoEniTw==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:ceupo0QhMlecKzd6aIifWIgxMCXHjPLJlkwh5R584mWUlr92GLnlCKPClE1fY8Ef14QikghdUlgtOklf2660ZA==,iv:zGyzNeO+29XaHYnUB5D9+9yshwmma0ap5XM/vZHgX7Q=,tag:tekNpAF+xLuJNke+/39kjQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:17:22Z'
    enc: CiUA4OM7eOVQKoadPFJpcU0wAnWvCJ/xhDyES8E1RXA8CBSSxVxvEkkAsHDEl6AVI1XeFRJVv0YlfhIs0rXgEEmc7WYOMY0ipKbA5geXr6j4Izcs/nQFZEtItYq7DOWa9YCxZReKoiyCf1yZ264IlqWt
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:17:23Z'
  mac: ENC[AES256_GCM,data:RAsRaoUt5i9NAl3i/KnnlgD+2jwROwZs9IgrNgAGCaeOqNa49JEO3t5WEjXcxUM7ZPJHn6p3XjOJzB8Yy5WkjSVlokUwUZYNflGkBIs+bSGw6cCQwPtBtbJ/g4qnVXInrAwZTbb53KO8prY3rBZZiUKAmpNTHbGWVZTfpTFFsow=,iv:28nPTHkmcfBIyvU2iftKuKStl3MygjObBLfU67abftY=,tag:VRqS+Y2BUsWfV1f/ys+qaQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
