jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:maH04xLVIiTjudxpzrENG7ZR0eQ=,iv:VKu0kd3T9mpJ08kqpRc6ssnrH69nvT9JQuBHL8TrWu4=,tag:G24JVnstMVniGNswqk/98A==,type:str]
        client_secret: ENC[AES256_GCM,data:D13UJtxFhkKhT/AxKIELr5kSKGi9/GFXzK5gZoAPQrOgGgy/uQr+Rw==,iv:w3xMP1NDu1jnXktt8gSksV5cn3ykuM7YRpBkENqa75Y=,tag:gO5v3hkeZOjP100dylqRGQ==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:PDur8StW6RIv32YHqC9IOQ7Shei9LZB99V3SGDgdavFijzx32wIbjbZjZbx87NrnywQVKPYErG43uQYm1a9WZA==,iv:yeDKKNdpYTjT3M29AshbADlRTd6Z6fIT/PpqZo9nhNM=,tag:tgWNO8VCqiNzD3dY2D4peQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T02:30:41Z'
    enc: CiUA4OM7eKVHsY7unL/ttuRHeeVOtmLgfiKuzOrnq0HSCLnkOHDREkkAsHDEl5Ab+ctakohekhpJUVV2LuebUUowqLldbU1+RwI5iiFirkX9fM5/BP51fZjoHvb526LZSx7fV0neTZ23FXxDzKCoo+Ea
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T02:30:42Z'
  mac: ENC[AES256_GCM,data:IbK5fAS6YblrwCYxcEo0bmrVV8bjhrwjwFvu0iVynK981jpzPICOTqjj4+9DlakX6KBBeGSoNm8YgyhYZbMzDPVpWoo1hU/mMZK+bqDAaKFoIBgtsDmW+6FKYkMsoEQKXD0QlBKckSvCvHtFKGy5X4tmVI7DH3gBI35yiCRoRRw=,iv:kG1xYPRIhmvRqUmvx4uoeabGo5gcighNbGMJGNLJNF8=,tag:kGre2rxaJGuYV0ir8egl0A==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
