jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:XltZ6g3U4AFttRwMLcX8SK4UAS+fcrKxajANobmijD4pvYK++PF5JGzJuRAMfty+fr2w,iv:QZuC8RKdJUzTW/wzGBN1jbjQRxw0C1/DfXKBjQcT4Zc=,tag:N38GBdQPd0WOfj4ssjjzzg==,type:str]
        client_secret: ENC[AES256_GCM,data:qzZxP+vx5NXFtSB1NXL47ONBLnWq01qZB77XOBoeQ1hZg1KXnkBHkvGbqf59g2KWum7Osdoz4E+Q2QoHYwxB0PMFyB6Dy1RtVWXyxu9ptJse9QdlZfA=,iv:ITzZ3CgArOl9BoTsRBO0MznkOjMPZ20tZ+kNx2MkCqM=,tag:TRlQAuxzb+ApbUoXCow2Ww==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:LB0eayq81MES/j/YlEpNRZEiRQDiy7BHRfutkHwQPzY/t/FZrq9MblLc/iVWLSAgt5TABhELEAHa3OuWr3mY2w==,iv:hKldZgBFcr/WKUxVkASTNyGDPvDf8AUPItwkM76ImGk=,tag:XToza34CDGj325X0KaF07Q==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:18:14Z'
    enc: CiUA4OM7eEuOJFM4qNrCLa+2Um227onpaQV91tM8HuPgtbahNiXfEkkAsHDElzve3R3PWNn+pZtfM6Cfnb9LVtnAZZ2V/t1kZBSRU1s0M4dsBfvwAKzy0WhJw/0ggy5e7WTGo2qDOhTVMJcNhBKirIQW
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:18:15Z'
  mac: ENC[AES256_GCM,data:g2nO2ABof/BPmZ+hGxRVc0XTlM4aBtz+seML4eBDX+gYTPYUAO+bsQb1l8HRPdKGwAGI+rfcZ4WtPm7+bOQMwuEVgbitD838eCSTysm4+wl9DRncit7AT/xK4mvw+5BPijXbhaRpP1/+RDKPkyVCPhdF3Qnv0wbH0J9RVuSehYQ=,iv:etc7/bnlJs7uQTsITVvzdUcWz4WVVquAMdmFiAVqQCU=,tag:wHhePe2g/W4zC/uIyG8GCg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
