jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:EyXpSg4UnQ38Q5r8zFfEBxBzrp563/qmwJecWESRzusZroeorNrN9dctEPNoGxad33EshFjaCPWlkTQ6aqwm4ie+RHiBNYtL,iv:aTLsWjQZ7Qss02uACrUdhnNGipUcnX1QrjDikdGqKW0=,tag:SxKS72TKgnVyhyef1A/XAw==,type:str]
                client_secret: ENC[AES256_GCM,data:DXoIIA48MiC6o2ggwQ06YPa3pT0jy+WinjOVPueDyzIJp5A=,iv:U1vZmHdeMm5jdBYXtWDRtSYqzhQRhKb31lkrJ5cVpow=,tag:qxYuoJgNftpPzAYS0+q7Zg==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:IIGzVXoVtMFBXfx/4gq50WHwD6NMgCmwXV39/Hlw3BxOhy6a2BWTMh2mjLOLmx5U++YWXy/JwTX7s/LT5qE5XQ==,iv:L976HnVLVVl8OvJ4qYATprgAezOjJHlialpbDtYGwOI=,tag:X05PI7idiGG9XXyWQtQHXQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:18:31Z"
          enc: CiUA4OM7eATMjyzXYglWkORiCG8+mSgeF9i/iBV6+Ir/drpwVdQZEkkAsHDElzSSjOvbJj0NyRPj0JN/TlTuZGsmt2TmSsM9bhxm3IqursnxPn+0oOBLtbmzWLG+zw9IhbXp6w+HjK9RnP4VfzaCLXSl
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:18:32Z"
    mac: ENC[AES256_GCM,data:jJF6YGXIo9BkieKVznVVGo27hTbW3WXaXAoR8iGEXVDfyctGlcN6gtEHqy1SAtNqiVvq1pqyYSB+bjwyD3Ey1GT/4rWrQRaslnDBnLkxFyh7I+VdxDk+HJGp5VS7HtsgtgbM1PNhFt+Klv2+jnJApE3jwjhiniZhEAAomfnskJg=,iv:AVaAfXZt4OOV4/wb58Adp9o/YNrMN22s/BKDLDtINKU=,tag:WCH2w8nQAv0o6biO5e+59Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
