jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:WLPJXyjLfoqMrWOAJWmQdQP2wQPOZYh9NtUPmuI5qLeJJz0lZBremWMfNxuR9M9dVQSx,iv:FgKfit1oIBeJMOjisSMynhmlQKk64lUjiqOihoIbYis=,tag:Z+sB6jCiy5lU+D6zoSKhVg==,type:str]
        client_secret: ENC[AES256_GCM,data:9YqN42ubAKKNPBmG7eQNHh6SrtH1P79UThvNZk2HWSaz9G3qEazKgBfk74qDrBemZ2Xk0KZcR+cBJYbuv/OEWjXOV7T957bo1keJ2zicddXaHTbpquU=,iv:zYCSol9WeMSTpyi1WU8/rsP2dJKXGp7NoPI6M5k59/g=,tag:Z6RFBkHSiGxTUFci8grovg==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:+tXqEKjNU/r+0dcVdx7pHot4f5bzfd0knEfQOUyh8IYb3PKmQSC1eN04Et2DBxiLib5i5AZkxhe9ynSAmh/X6A==,iv:B0OToV5vIwdjuyn5PvA1UqRlLNoWk8Q+EA54CtTy3tg=,tag:PE4oXMeGK+hZF0LQ5gR2gw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:18:26Z'
    enc: CiUA4OM7eBD2hbipWzb9rLdngM70s+eFvLIytSdgX0TYbf40GOiAEkkAsHDEl16KrZdGSsJdIvLfo5IMM4N5XcO6sWUwXEVDfDHQXpPTfwQkB5K2j4vUt//IOXyMZouVD/wg7Hp7KoORD7e9r6ItIvTM
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:18:27Z'
  mac: ENC[AES256_GCM,data:mSVM8WsrfRFPpSO5kJbQjdhTWDFk5Vma1PdHnj/Vs5N001ItQb5T2kP+3QRiUrvM23F9hxu2uNgHhT1q14yvQjOFpC/fUTPd4TIhAsSDbtiKNfu8uIiCFLxUXapiCEd8UIrvPvLavMC1TbuXZD0oUcpPUPJqYaz7NJrguX1zVAc=,iv:TY/XsIwAfZ1s2AzgHQGo7UZ5Yx3L3KJam02WMc8xVJc=,tag:dz+22SoDRZugnlkzYW2j/Q==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
