jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:XeRMpHnPqVM/ygTabo3ieXbVwnZ0mOFd7txQ8y4EZd2cPYwUNyBwYkXJA7pFnv/XawZ4,iv:F10po56HD72uWOCWsIbkH/7yidI2+m7/h4pSu/b6MWE=,tag:rY8Uxy4qsCtDnLOz9k1U0g==,type:str]
        client_secret: ENC[AES256_GCM,data:2YdjUtqIxRDlM76qN6h7Jl+hWLEyKcmujSqiZuaxNQU4hfF6cukFf8sevfBT2JSrp4HK2Nj8FxQ9gfXEWQDTwvzCw0vedxxtlKIiWQYyPCbGRNsa/wA=,iv:yLt2diXMuzcAhiOnd1CRmQUDD2bQ8GjZiP5Fgd57giI=,tag:HTSTBrca5Bav5xZ5XJegxg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:54Z'
    enc: CiUA4OM7eBB7n6iXte9sxhs7Lyl3hVXeCMJ0pUJxu1MawEPwC7UYEkkAsHDEl1g6A+qwgEkHqmY41BK/AMC7AA5TJxPFtGrixjTAJ2NVg31VyjFRdCP4fri/s/y1tNZeBkWD4J7gnsY+K4TI/98F5Prv
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:54Z'
  mac: ENC[AES256_GCM,data:9bp5fC4/BsHf85LiGDVwM6kjNJTui2tHH6DTQP3XzXFHVGYZsGzL/mbQWGHWjEiGwSvpuWpTyE8gxrXkR5QGtfdTYqksPHWzaxP1v6b6haFn46Y31shn+MbY8EFuSpSDzH8t9VLoYWQsVDV7hLcClNX0yYG8sqXkfAajJw5UEG4=,iv:NLWCh5qvsjLHnbeN7JkpOu/n+B8e08N1DZy3adO94iU=,tag:A7QgwPKe7FCy6tjYDmLnBQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
