jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:H/yUVc6D+dg9/LOj92q5EwsT6Plnqhc8obFmOFDzYLaWSw7SGyeIMujL3uORTNBoSUdE,iv:PGbOXdKworCoOX2IaIJ6NN7b0YCKvxV7BiezziIS64E=,tag:GmovsxWnCEmut7u7JuUqUw==,type:str]
        client_secret: ENC[AES256_GCM,data:fCgYLE8gP42lfqt4VqplPSOEU5j/0SfQlon1Qm18jz7Mz2lu+XOSUUe4zLcw5NSuImgiU5HRKC0nvl0CM7QnwMIn8YH3LyxkxJqAQFnw9MVKZ4E5/ZA=,iv:FNAPB9nNn2QH2DU/6s7whnHL31KZfbkaWu1PSlL+Vko=,tag:cHP882EmNgEvcsHr7zzp0Q==,type:str]
sops:
  gcp_kms:
    - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
      created_at: "2026-05-14T21:32:04Z"
      enc: CiUA4OM7eKqAumTjdheZZ2nVILNajas0yuEgkFP6Bu4bq5xCk3zMEkkAmy+ekgZe3toP7HNQHuZB9qGuTDBc/3XzLZvQF8W56GlN1/bhtBkItoN4E69Wl6afMbTsK42jP14NtdEkxtOfYyxRVo2+spbe
  lastmodified: "2026-05-14T21:32:05Z"
  mac: ENC[AES256_GCM,data:ywEppDFZbKhX71kQDOoc6O90sTu8hvgDnSAQPiDjkTJVmd+JwMPFx8p/54XgFbFWjSK7Cin6Izg6+68Zigq4Tbga58pJg/wra/pUPEe+PtPwZat/CXWhtxY/NRBy8bKgkGSPWajX+CpAcwC4EMLH+HAre8XAcArqlaYMmYTdxdk=,iv:o3eka3x2tNyJJGA5hJu3Bb9Ac6vKhxRP7EoQR9bfmnE=,tag:rxFGtmjt5fZyA9mSqPPdYA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
