jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:JRlpDZVfuSx7i8yvMlE+QOYqgHg=,iv:Ucr9vZ2rMp/VA6DioaJJ1x6lyTmI43CK5YhZhjLErfQ=,tag:OW9yr/xEdJRdzPxR1EG8aA==,type:str]
        client_secret: ENC[AES256_GCM,data:B80P80imPEAKAONwIWs/bo5TnaR392gdjfgnafIm6wAVNhoWjzzV+A==,iv:3i/XITTWTQB1had5a8A6sBN6yP3CSygxdWPKJQ/YoW8=,tag:xesRUCapzqmAMJZW9zRjvA==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:yFCohmMQglo99XDmGwXXkk68i7pkxQUPKBw/hqX5/RqWVO8CFlh1GDjJcNA9ZdKo0s1SfJQHCTGydKn3fOzSaGutm1lHoaCsiXWr4urWWBnC9xwlU9w=,iv:xuB/EAZ5xe+IdqDeH5e2SQ+r55Km+rZKkGBQVuPCmUg=,tag:i03F0pwbAP5ewjzyyx+9lg==,type:str]
        stringData: ENC[AES256_GCM,data:lh6WEKPBqnue/Bn6jyA+J84TeAw8+W7A8fytlic8MpET1ggK1YoLMcb2nnD486m7Dzx0XW5FlS0CyzzgCJCNwHp66Fd7nz8G5O4Sh0BF2pGKcpNCNUl2tApsCBvaS9LVQCRhEkDY9UE5oYX7i8xftiGvq2G3Vb/kMBhPDRyE3L3umLr/3Zpx3xJzLxoPehPh8AV305TQGZW+0jml5Y63nkZB62lOXgUh0m8nhvyG+VkfoTyrmiuC2X6vd0TbODRZQNdWdyGfTb6S5FRoGECZn5cgtaFaNtFfe7wvWgUtycRrRjsEZz15VmXZtEiLyhOyTSXxzfWHmlDFKiG4DQlwTzCFTt6pH142Y648xwt69WWkkfM+9rk1hRUuuFGQmqsqVndBIXjthAmmr7fcXlGePrzaOx4ERirm++3JEUemAhnP0g+XClJ2uusHzGsQWyPRXKcNiqN7SbinBQ3OWIgpK4gzzbkWoPTA0q1yrn9b8eDFg2a7GM99XZayhIkghNa9bVXDGBDngeqtx7q7XypXj+GrPLZTRNW8R9xjQtJYam1CUE41u9HP0LC3ur/O4XbSQQbAuTL9Lm5FoB+jPYkor7azOQhVJYvZrPmpWfiCh41Gv65MkFrP8vI60SnNw0+ogzu6b4Erq1PZwE/YzQ==,iv:SqPzbHgRdV3TvoFFbBdZcwyV2Bj4SSciZ8xODVAEs2g=,tag:rRxz/xpwe6Zo91zwc8OWDw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:20Z'
    enc: CiUA4OM7eIZzNwFiUQtTuz1nZWJjGGVQvHm88T+KX54ej1kKEGZ3EkkAmy+ekpL+0kp4KDIcltsaWGofvDH9TOuDzlhw9+dSUQkah/5LMylk2q2v+j7YJLYUAF/E0maDuO72D45WHvEsRRtLD8Unch6N
  lastmodified: '2026-07-29T19:18:20Z'
  mac: ENC[AES256_GCM,data:iAFNVqQ8VxqBbEkegglgsJmKmdJEjLxdJadD68zeAIVz66cd0ALzp3hiNMqnFkkTInb7PYad8Gk5aLrztkdh77KzaVoU/iGyU50pj5TxaBF866M093cvl6ZCE1Dt9mt/JTactuMUYmAb58CJCDGDtrxK4HUOTQp/G+qPyHBtGL0=,iv:6JwXHT9USTolv+EcthoRTmgTAvlavSd4/h2v0FCoqDc=,tag:W41DQ3tnJrnHdSPXqe37jw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
