jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:4EqQWkQtaNdEioUWeYhkPeS+A1CSfULg0pZp/fn5IQOS/ul628Hyk/81+Ax8Bp9N4HC7,iv:Dqo86dNLbej02yEecygcY/OYawScqhYUMqm/c7q3TB4=,tag:WKPR7whfNcx2v4ElXR/qYw==,type:str]
                client_secret: ENC[AES256_GCM,data:ct7WlBMrwJyH3RlroU0UNqB0OYEFn4a9aMy6JdWYjlUTQpYPHqkCnRh2BdPdYQ9ldqaepCyw/G0QjTmHmDpKPlaOQw4pZmx9gZDjclJ/1D870QU4iVc=,iv:/sPFhb1E2iP7OGSFyZWX1dSxu2zB/ZWBCxcBSMBESEs=,tag:FfWGVYUSxWuUusUKLim8YA==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:kHacoZSqllmdQufhjFaGv1JMWK/GgoBI7/kTQy1P0vCs9i2aw3iDGNwm8p3T6m8Mtl3VtQOwp1ZgReMmG1kTaw==,iv:Q28McNOYfHGrqQsSnIsBdrIEFksAzRjcFRApJafLWsM=,tag:dEh7To9nXQfNUI/56qPRlg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:18:39Z"
          enc: CiUA4OM7eIQ9f1BEtJH0P8LOB3ZrW+9vB7xP/0+3puDHu5/CRZQYEkkAsHDEl/YV9w6MB92MrrPsXIrdsFRkH0LHWo0mWLZth8Abw/bY8MD/LJQiQT1uHCHe+mZ0uE5VuwL1STW8X2M5C8WoI3vqn4WK
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:18:40Z"
    mac: ENC[AES256_GCM,data:eA8VWGUwuFG5KHuBvxfMFrQFqJwu1mXUf7YxtO4xxTK+kMEGBbESW74/Ok/Tl+DvpViEFemSQcPbHt8wRnCnkRnxravxSpPwk7rng/gtbU0p85Oa4bMAQsINEnvg40NgUfedLyKjdrHxHk7/krH19qRD9VEVEEDPWTYWUqpXo2I=,iv:Munv1LWtGMg1v1JAFHyHDLqsWQFmeC2rru34M3FHQuw=,tag:MqVgxCqGOa3ZWFmF+YU5Ug==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
