jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:DNs8L5KPNP4d4Twtcg7x2zdlsyq5VTMUBlwHD8+w3ZQ4tA3z2V9VCY+jH9YGZyP5lQSr,iv:+C8VREvWFoHyvM+Lavlj2QtCDYXHG9i+UKpbhBi94ME=,tag:B0/LuZRyKmWe++TSdlp/4g==,type:str]
        client_secret: ENC[AES256_GCM,data:jnd3mzq35AWAAzQ8ut9gL0c1CR77pZs3NOkY7abIzaJemakm9qE7/BOZA/fedOjOSrNPm5PWhfpOnjSTM/zHes8uflUa4fCssA99UXl7HCSJZGY0Y/U=,iv:S10pOBJqwuzGO1II25TWonFasrtyYb1MGIoOuuD9iaU=,tag:XY5L6ZvgQ8CdvopF5SEhUg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:59Z'
    enc: CiUA4OM7eHcOUpR/QUfN31jHhQff4fAHLc62zN2cHPHtnshMx184EkkAsHDEl5OB7rgGnjCzW3ahrVH+Q33G4dq5NYqzGlOa4iJ93yK6cqii1v8amEFbjcEG/CVXhcgL09Tkcw845uZLBLjk1Bx7XOsK
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:59Z'
  mac: ENC[AES256_GCM,data:b1dtprgvilvbCKyTZ07PJMhLRLoRO14Vd1Eh7APnMSgX2U4WZs4TIlk+LZOotgKewZbw3zxLLePpZt9dideoHvb3bS/YjCSHA8n3iode/ChtFoeaagOZ1J6DmQbjLhjPcPidTqNeHcAix++m4MSEZ2u0mC5zqiBqGL0Z7DNvisU=,iv:+OfSMyOYB7okcNVAfvtwFOrRAOvoIqJk7D5MjUp3htw=,tag:ggc8VMF4uEFBIJX2tHFGLQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
