jupyterhub:
  hub:
    config:
      GoogleOAuthenticator:
        client_id: ENC[AES256_GCM,data:m/b+9e7+cI+/ZbRYDNQQkMZPVD+pvcVSbxXSQxBFEATmxSHNz7RAq0sIIZ/NQIVUeE96A1ZnaKtoOYg8ne44dFLyiL4Yb8Rz,iv:49zM2nhHRMJsB7AYC225fUeTmFRLPDsCePVFoDFGPPM=,tag:wqYy2SqRTcgaXhBxqfl+OQ==,type:str]
        client_secret: ENC[AES256_GCM,data:5DDW++Lpb8RZ0Ydm4YvNWBtFmzGos1CljYqEpeNGACoXmzE=,iv:+jE5p4tZq3L2hYnq3Yg89Ka3TvpQukI4bkDqcACkr3Y=,tag:NoQ9UsIb1liE19BWxEhJEw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-01T23:28:32Z'
    enc: CiUA4OM7eFAfLQXL6b08LClOkJqXvvbKUk4Z9rpN/E+SuFIzsa5nEkgAmy+ekpTqeI3WN+IZfkiE5L0Lmke6pKXQqcbBwLeS46fnEaaTpXZ5jX/mQoLARnwDMqp2VPvK2m7VpL6TccPpM+5CnoTAGwk=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-07-01T23:28:32Z'
  mac: ENC[AES256_GCM,data:rg59bupeMd5OEUo/hCDWkUJYnK2v3VpbWTv5QBmcWwJfTS51C/bMCQFetECwC2pwdl5dDZiKe/IYTx8p9ZJfZpAhWq3BiFWAC750kMrWDLe7zYIECvSUFagBhh7QByEMsbZ0TyqeNoTrniv5mhUuspA3HGqrEQO/m1GaLi8Jths=,iv:83iwbUliwH3ttGc1Ux7vy+ZBt1R6KzhHjGWtHCgpAGA=,tag:OuJg5cSrV3wCkfXlyRlCEg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
