jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:CSJSQppuqVwsBomTNTbHN3wJDlk8TRwfPHiT6YhSF91txipS9U6oA7cetEIV1htp8Gd3,iv:wwrGGU8HAodP/LVFIZRjWDb7lPAmv23jRyjmWbCJBcc=,tag:WGalIkbInqI50Evmik2zpw==,type:str]
        client_secret: ENC[AES256_GCM,data:rLbOGTZljmFwjdblJYN3ip3fHYK54UPKq2gM+FlIucHEv1R30fTFpgAKFXMPxDGspV7Hd0KXjhq9SiPKe30q+UJjqpDzJKDxzMpsX9AJWs0BgrjEbi8=,iv:G86ua6jLaoKlFGuy13XqbWKhpcMq1Jf3LIEE3dGmez0=,tag:JTTuvnm8JnOp3hiZd8jWLQ==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:4EnuvZumnx3lbvJjQms7/KAx7q5GW1r95uvG8Ifs8o0usCrPeZayhdtOAiu5IJsHmBJDii1w1wXQ6untklzZW17nWW0gZI56hXcyZ9dbqtJZemmMdFg=,iv:STuZrGv2rZZfDuvV5m/IGTiAycf8gpjxeo/UMnl8nFQ=,tag:+OXN0tjneHCEDgreJzLp+w==,type:str]
        stringData: ENC[AES256_GCM,data:wg3y4uyfbJckFUoUdtOXweU5dcTdzQ7OCbXEVAPUHFAq5oWzVCp59gtyYXS6gL4twK4u25lDaKuTF4NEbraazix50usWsfC/A22u5JUVazQoFbqX4DQfPHrqwFov8YsptJYhAVL+T3b7LpW5h2Y/c+Gc9RG1MdqfivMD/BZOHRH9ktHA0Bw5A+f44U0THuKPvdJ2imWH5pkRzKYivxEC68EeuvcqYTB/4AZcU9o2qnyCfE3Fw7xu4Z0JM0nN3tzEupJzwgXda8RXHuH8SLApe/V4D0xR6GtXkXHjampQvSdP3jxI2LR6IFzX/m8ryMyuMtUwmFnTRRQTV8RC6+jbhlYTx2QVVzIjI1n7ne5Ks1vZjwMu0SiW+Yq+iK1xmBD+qJkXOJ0nPZ3CziZ7BU2HrLTJf9KTwCSjQNc1z5rBpvEDNDvvu4VxrtzmXN7JB48PpVMxxnPh/WdL2S2FmAQ1bPu6JsyWrPJt+ASK26jLUe37rfnjDwuw9tkAdjE564nGuL+IWNy797ist9a4KgNeSvxf5qAavhW4j1OJlZvcHp8zpGmxrL4Q6PrAUXDoxALpuHYF4fPKY/G5bS5bYY1C3559FF87sChuesh6ri5GlhNc0vcetiAAwOaad2g6I8IuDIPRkS4yfksfVF2Paw==,iv:ssVRbbphNpi1n+sEds6YCe0CBEKRmO+QreI4RgzOT+c=,tag:iYu0I1o0OkTEgl1e1HBa2g==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:04Z'
    enc: CiUA4OM7ePzitJk8wFVLlRyLQ+WPpVcukRZVgrQnWFQqcbF68BOYEkkAmy+eklhcTvnO+yLDu5tqjv29FuVceJsoWNbJ4qisL865ozTOOY2FGedqpVaPNePOLGu6P5WADkbLX/vVFY3VBOZtmSzgByDw
  lastmodified: '2026-07-29T19:19:04Z'
  mac: ENC[AES256_GCM,data:ev4psXe6GqKdQJaZYyMePE7uzBpIxKlpmEOBpMRDsHs2VnqVEpCCiFtSNrjuquoGHJpec6ePg12/RYXPLhH/sXEeYQup5ye/TCrV6CDOgDEGszrLTnw7CMj0pCDVlrKqSmio/P743U4WhCs7jD01TZkhKDXlYCw7Y1MiULeHiRg=,iv:emJ+YDVAYBJhk5jGijuhEL4ZFmS5bms6DgT+5j2ondk=,tag:LUBMosYRIcnp/W6Gs41nOw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
