jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:DXWtEu0b0bRQXYdfh7R85jcijoPrbUgVVxHvMqVxZn+ZxvXKQkD1LzREfpFfvw38jjMf,iv:GBxceg71Nc2ASLuGPXTUMqno7dwIzZ3vX5XxJOYr1JI=,tag:Ob2izZgXrAz9oc9xDBbx3A==,type:str]
        client_secret: ENC[AES256_GCM,data:ixHzCODIxCVO8iGb4m4PSL1ToSZHdAm/ZTWb7dF33uR3f1DRAcuMrBzA7saqEuXMWikWu5i2E4lzGzHMVL2R5eYAo8ExryjjctUvaWCuOi3kyrjTzn8=,iv:fVWxgIEDNLHOFdmlXl/waHJMpwca0Pq2txhx0qwYBoc=,tag:AqVwaFC5YjQ5jgKIWkRLJw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-06-24T18:23:25Z'
    enc: CiUA4OM7eBEZMZ7V6Xa4RiiA9petxY30B9NnwzuleZlIueZr46IPEkkAmy+ekkW+SpbrLstX6GCKSm1gZGHYTwGuHTQQisqPjOTqjysskhkPT5+WHTHf6DD1xmX+cUGmsB1z/d6ufpqv++1GRMxF7aql
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-06-24T18:23:26Z'
  mac: ENC[AES256_GCM,data:X58OIDFvkY1vSEsD1h5Bzm+iU10vKFkFjUN2SYH/PjgbUSf0I3AgVqwYkS6qiHIYRsxQ4oJGrOGKWR/v9c06Rio9ODCDQwmyGsIJpahgGgL6jGCPesz/O48dl2y1hXPw9dk5FJcL2yXYrLF0xusXGv8QSQcCzys6TfItxBunaU8=,iv:dJmaz73m2nkMV+FxNeJGZjkRFcYaIhwb7kxDXUozzs4=,tag:tuKVeOEeTr2WaZqr73pZUQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
