jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:Zqz1r4vSheue4PHi56bHJIynmqYy9lDJF3i2q8lhrKYdLEiUtuImdl8/EbSvY3ISyBMv,iv:CjmTluVeQLCFUBemSg2+GfWp8UtHtHUUsDTFNAiAIXk=,tag:JRVffSnGhSNB3VsCfxpLXA==,type:str]
        client_secret: ENC[AES256_GCM,data:WvT85EGmRu1qgczNaHWMTm3kdiwRhyH58DxHIfKrRjwhUKJfeuQCpHvunjTQ2EQu+u9fyF9aTNYBkD+oadmkZODNgXolYp3v/jrOBv0nTjX46XuLF8U=,iv:gt2vbU8GjJrVIxXbFFVknORDDHCCi70ow42q43hOb6U=,tag:xvjHXv5E1l/bHJkUve3u/w==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:52Z'
    enc: CiUA4OM7eE4Xp9LaIjjKcAIQnrg6nKjK0zPAchSPK158pFvox9PIEkkAsHDElwQche/MvMBK9EnkQwv73giOcIFYUV0pV2RPTXPcsfx2XRCaREsPWoxsFQVKfFFYIbcHecuaXZU+uvl2AFv4hrkHum9b
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:53Z'
  mac: ENC[AES256_GCM,data:m7kGJKhl6YXBICaHn1QBxyveRS5iJFEP112K1DqLVAReZVHbEt6qFD4jjwJoMP9DDbYICTm8uvnZ+Zi5eUec1PiQt0/nQTKyyg8+7llQSqklzIMHKx1BXFc7onkpGmm6g31JLhhNr1etvv4gLkwnBw837HgxWQRQRliPJdOnuzg=,iv:oJU3tcrQcINmeYA8KYHF02PkfIjDmXAMbWMh3SAiLDE=,tag:XjqyIflZxJgZGqeD2i3cQQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
