jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:W4BIBvyiotfPlbvWUd69pb1J53x2Paw5dV0ORQKvOpKl6WyINrFkLkaFU6dp6rvDEJox,iv:GSZ8y24BSI+MHM7AQd0cao+/gOVGs6DASmOs5LaoosA=,tag:1zlmEcFwC3y1ipIiOvf2wA==,type:str]
                client_secret: ENC[AES256_GCM,data:o+N+g2nqr60BgaJUH/vAhI2D2bXlJsg8NkwqkZyFWuN2MMrH2FpSMe6q6mjnuSpC/Sn8ta84+bzmjdGEfqLY9/yiacfXOPwlNoUK6L2J94fnlFoVGKg=,iv:yNJoXZEJfToMruesESgwp2sDAZnPSqEN84+y46seJZ0=,tag:8rVgZ4taDy2nldEr1MQv2Q==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:nI3xZpQsaGTqu7j9usZ8+zctIsoM23dC/uVoQXByfVx6dkhZeRbQNEdP5aa73rH93vhVfGIUTKaTpblDxrSzIA==,iv:kAod55p5bSbsZaglaQCBzWNlsjCkIZzP598bmo4dqN4=,tag:gjbK/cgZ56/HZ2NzJmqouQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:18:58Z"
          enc: CiUA4OM7eNa2xV0O51tMwASDpix9mRj6ZFog91jHjqCN+P3P6mpREkkAsHDEl4rdmR24Jx4SY8pYqTC/Zwn9rCwINdIDkTegFZ88DKJFHy6ZYiuE5kTuew61xa21JpaqdkCMnLK6t9k6OvfslJpjScIt
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:18:58Z"
    mac: ENC[AES256_GCM,data:u5FL4QmyFZTQA7WVFVhcy1oGwas37owekIFgD8hDkOD2s8A1MYOOr0x8dVBZJpfIIDOChTE5vFXWIUEXCMUeqDmVJcvwCnBY1MISzBSTR820gtDu2BHEd1cENMK7/Hoi8C0w0Z3q3iZ/dKDfSk7hfrVTomj95eXnRJ+UxTGhuPE=,iv:ecaxTzE9bSA3s9prMUgrX2Y5UOILHPR2ouBrzNlHOos=,tag:sqejsUVoxOnU4NpioHDJJQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
