jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:cPgvckVgHczybDgRXksaHxG9JUq0V4E8qPa2Mb/7cfNr3ZtK5ppobnTDFckyPnFsELsi,iv:11HJR1TUA8uo0I9lFvaHEQuhV3va42zsNcI/ys8jcR0=,tag:G+JAXZnQuvhDGOYEz3lMtg==,type:str]
        client_secret: ENC[AES256_GCM,data:2PDIp9OeU3S5dZiF0OXs88B9deYdQOPIOKf1zYYXqNCoKPHhtxX1yejkqcsr4ElOk4r92eB0OzA68HG/QRGU4A1eOZyKcB3VXDMmlySiJ9+xu2iSf5s=,iv:Qlo2Pp9r08mcFD7hHZ5c6OHJm3GV1DGL5ZM7wTFwYdc=,tag:i5QH69FgnY5+2PdCjJH5vg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:ucMNorLibF7qjvKImsQgt70xNrS0T6zYSPi1S0b0yzd+OFmgMpMmkWleCWVfcqtAPUeqSH60DWbCFBhI+rDXTvJcyvOKEIkIWZORFT8ecQ/S0f5lPR8=,iv:0oDxIgK4PPzuCC0N2J0yqF1ZDvsKdJJWmIj3QxsigY4=,tag:YoXa6NIbj5MyVy/wuXxaTA==,type:str]
        stringData: ENC[AES256_GCM,data:23RD3RbAPyFSUJMGJW7tXhF8oOtSaQUVW1mhtmg+EqynFxrjAYl/4Q5R+vRJxflegfcTlebL2m4Ntm+vQskKnIOX7hA9GyKzGUbNDU8WwZfJDb/b6kEzECcD1lzRiGMmxdl3ufY2n046NE+2IxXa31vWp2o2jB/EvbTGfTYQZOysKX95Fq1ISM/5yy0wg7VHYxLGFd8qoBwXeWic8AFvee7Tc7MvUqPieYOzxluZbE47eY6tz036WjvlIRIk5B78iFpFejTnrP2Kog5IAoNLUp/U3/fVzCGpC5Qm9jO+nYGI86Ees/LrAjnbU/ZaA9CQLvDt8rLGbvmXYtAhReIrs3ZxDd3yR57kTqN5braX7CppdC9n2WAfiAkRV1nd8CBCOT97VwDMUVqGZn8jVZSZPActq0yQ/XXV5GRhQyANEKm9kCdW8oKbGI5A/oMObVrIeXhuCIzElVh/v4YRvFXiFshDRU77WsWqAlPomDNSgysc5Y6PWBTAbfldk03a+tQ4rIoNbz/eR12xPn8+2d57DhsoGmLqYzjoUe9KhzCF7Moi3hTMf44oDjruUop5KG4s0XrrqEYDNtEipj/iHSgVt7Bv7OGpMvKFTU/P6w58ZwvtG9yL6Qcp3iG9FPmvwX5wWghPVg65tVvUgm+sAQ==,iv:Cqvqn4MmR/k7ANFrWZcSuT8HSOlR0kkOXoCeHRvqTwc=,tag:L13hzYMUO59vOdGc1H6qVw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:20:14Z'
    enc: CiUA4OM7eFvUY7hdyV42CBXAun2dQSU4KcgaaXNoHK40tSyddRMaEkkAmy+ekpLPQuuyehli57UhwWzdvOT67rjoMKKB9Hne38HnhDJCuyZES0BlUbSngcxuaSi9aAGUY3cVuDZHtE4YZ1Ynlf+9UqiD
  lastmodified: '2026-07-29T19:20:14Z'
  mac: ENC[AES256_GCM,data:WrSGnmKq/SrH1X9pOfG4PTC0Ldms/fhQtMlY1s2TPspopZ6Or3TToVeT/RQQiEilPKxMe/lpMO73fiNatU9vneCAsV26141WD4+/UsS8JvhCoeaB9CqcTpZhFMzYOh6CkcDsN0eENc4jSyFb3gvh8m3WEg438EZoUcbNRuWysGU=,iv:4jqBEWewlQXZ4c6xYTbfisfwx/A6cVeYG0MC8fcs3eY=,tag:nhXOAoME3kfr8EQmhyBwDQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
