jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:DsquBJz0LTTUMw+EzyiFhIxuFbTiQQXFpvx13bNZLaXB6x41LOCFffvGkx6pkrKzTeM/,iv:nsdqGOHE5HG7nso3VIB68oCW3ZmGh9UTlnzl14pODGM=,tag:yOnWCvIVhoyNF0il+vdkzQ==,type:str]
        client_secret: ENC[AES256_GCM,data:mZdWQY95c0OcHk3tctxdZjBFeDSrHfD9tfzQ02OPlY3N+lWYIoYhoG+MOwbPkQRtlRBdD0mdtYkhWlM9Py+0zEDQosLF9L20+klJPOZlORcuFcaM/wY=,iv:OF0Qkbcfu1Y2a1NEcF/9BD8jfA/qMIWdBkoomWpACbk=,tag:8E03vPUI/3CeSWmGJIFNtg==,type:str]
      SharedPasswordAuthenticator:
        user_password: ENC[AES256_GCM,data:johyEGKtpbRmpsXWrKAK,iv:YaMn8M2vQVvtuHQSNTlsDstXUBZJen1Pd6jixix9TNc=,tag:cDs0U1/pSJpETWaV+FxcEg==,type:str]
        admin_password: ENC[AES256_GCM,data:nckFMzwUGu9KKxTQoB7SUWVIOQOieSK1vpTQcPHooxDx6w5ks+L0,iv:f/4L8NtfM/bCiDdoTu4QlnQJk6eQaQ9Fv2InEIUAJjc=,tag:zL55+sp8zWtg1ZSN4c7zGw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-22T23:10:32Z'
    enc: CiUA4OM7eNqa2iHtm2v32pQDIte9fwqdvMQYbonNCdywO6bAf0vyEkkAmy+ekk/41YXCqnSvCchVkECGrMzjzPwDP8bckv1RkugXHhb3Aiut8HuV8O/V+fp/6FHXXGg81UmR4Zyqn4BSVpoR2vzK/1CD
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-07-22T23:10:33Z'
  mac: ENC[AES256_GCM,data:LPv5e4ubDVeNftrM3T8xqieuYYWzf2EwENoAJ4xBzxzjhVEEeDIyoKW/e75usWIRfLRPlnC1PhRBBMFe+8RpZqlrUhAHwXmBEP2rs555GkRGQFsotthegpnyHCX14YD/qocjgrFHowamYky5Ab3+niCTWmHxqNJsz9ZzE6WS/H0=,iv:E3G3msB+zXQ7bqzYlX7KTV3qj31l2Wc12m5tCXsEboE=,tag:cHN5GrBnAO1Bsi6QuCtG4Q==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
