jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:z7UpPOzZhtNd4IwJhB+35imEFuj7LikXdUJJeqRYwox/pHGGQk+L1r5ElW77gZaUrQ9+,iv:EmCrFXtJ34mQRZGlEUjD7wFACpPHcdZ0lG5M9UosVHg=,tag:rAMM5u69DRLszg0uQ/R/kQ==,type:str]
                client_secret: ENC[AES256_GCM,data:9sE5fN+6t4j76Pw3qqLdEa2Z/zJnnru5stQ6z4MmuwV+xvTmkhH0SR8g/wNvrUTxvWHXwqUfEmgaUm0q+7tIE1Y5d66fPqcfnp6kqaah035zkIf4rOI=,iv:SSYuo+QAgjcyp1q7ViE0TjMA5LxKAiuL8/pRsA+4y3A=,tag:1j0JKCkAicbL/t0XblMXcQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:03Z"
          enc: CiUA4OM7eCLdBNgzoomdOtxZr/0U7PfqfGFIeWdWurrhBOLlg0PZEkkAsHDEl7DiA5+Rlr6neWBo2Vx418m5lcs0hFxTkBNBgqu15hIuxOfB9z3hVaqLt+bKgDNhRIw3V0F71bKqw89AGswboojVIfJA
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:03Z"
    mac: ENC[AES256_GCM,data:QOHG5B5Q6z9YdENsWSIutrOGALGjoG/t4DiVQuXQDR5hg1DWIK46mGslyTTWDC2B3Jvgw2aO2WaOLnmaaht3AolxZb14Y6g7PbOq0xAkA+pF3sF60rXEaIf9+/I605zfJQaBldWLLGWEV+0HTzagyzh2GcvWtuKLjhc0s+mqbgI=,iv:tbi+kAC4bynvWjJ3SbDRebTlmy9706sUHsftn88v+WM=,tag:dPZfUy+QF3u4aOWNBszdnQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
