jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:PF0TzcB3e26FcL5cH7pqxPYZS+M=,iv:kefaWpHhOKtmxVI+1LNOMEPmFQPj6ch5mg36gmbgovQ=,tag:1fMy/F2hyHtauYXysh5Uuw==,type:str]
        client_secret: ENC[AES256_GCM,data:O/AsE+NbJPZdRkmWCHreinCbJHK6RpKBob67JaAd2IJbg02+IyneoQ==,iv:5xgrLl0Bpe9lMIzIZuM8yK77pMKLCVQinqiW4rsIdXQ=,tag:44USq517ARZ7o/OPQCR1jw==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:CVmGqPiSaFgEf6Qj9uT3Rg9++aiJ+4Yy5xHmdg3GAVY3cSRX7p2Dd9zOEa7QECuHnUVsGURuH4bnjTAxoM9MM2YO3x6lGihiyGUBpxUuAOvli+lXUh0=,iv:W9Iq15O4qc+jQqVm2jUd9954L2azepLJ4RiTaV1aciI=,tag:I7kAJrLgOUyutf5MOfAvYQ==,type:str]
        stringData: ENC[AES256_GCM,data:uZMjhOTlMC7eMt/jaUnt16UM6nXXcYRe2CXZb4v20KJiLCpoP9CS+j+7dPyowQdOqrlpNkpl4X9qhgMKpNdKC1CmxKz7ZbsPbz7xo2DfK96nkXvBPZV4BQgC5d8ujWYMJCaLisFJU9BkHCTB22q6zV5wLia2LIukSTnBmgRPT1EqNnGVS80l9S+d2FAG+ynChhT90/WpguUKSmGcEbJWx7cWQdmNpGU2wVnOauYEMayhn/yXtOSFEuX5mc/ORF4pqZc4pKB6HQf6SL+QK4vnmtc+i/+bFOrMtvd4Y/7+E7YuXQOZ+gZHEX9jcD1nMsCOc3m3f8dt6vIHrdxXC4SQOTGjm3yfX1JA61KgL4pr4aYbgXxY+oeYJcB2cvGK1CAV9JRBUm2674ityr99c3ez9w6xvqZGRa2ZY8SFFXri8st8pzypEvAS1ib+t8MKpb34S0+7c5sWyqosyMiymeBNwkpUt76O4wlkWbnLIYxjXBgNEdoUPm1u3aa8GzlthdEvLqxIPXczdlpKCBO4YjR+bBhbb87DxLCNxw2OAssed8ygQADpC4cQw4LaSA3FzPo2hSvj7eLDyZ6g84Eh+dLVtyn1PAIRNVSu2Xf+3gNauVSwDx5kLcmwY3P/fYjIR/NysjMaV/tz10XcDS0DbQ==,iv:jQnzYfJHAteoqro/AjzhJkOHB85BLQXeVQvXVwFWO3M=,tag:1/5YFenZjYjIC1LfcLOWpg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:57Z'
    enc: CiUA4OM7eASzq/BeRA/pF0PQ1WFbZbsVCXAfMG6sNA+gbiNagvYUEkgAmy+eklJxqSwgpQN6PZaM7S/ODVomqFRMmP69fKRz4sI119eE9+LRXbURkJ+4g/hvHsDnMiQHUUxrRCVjlRhn2J6alfri92w=
  lastmodified: '2026-07-29T19:19:57Z'
  mac: ENC[AES256_GCM,data:4eNPEUcuKGZCkjr1dEijADMKsKcW1oU5SVFoG3GhqxDh708oQj4Fu063AR5+QV9ptvyVc5SlpZA6AG8u3MRRO5L0CejbnmaclMp12XjLspICh0EQdSdhRBPUE8F1RiUwIBumaBSUUo/YiWSFHygIFaqWuS9fa5F6yksHBVkOGmo=,iv:C44SHLaNU8lazLfIzcPraqM2Rf3l+TTAPxZoxGQhGnA=,tag:UYsPA7UfJGA3SKxRJm5wAw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
