jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:B8LngfTNAVNFrhD0n/XPtm05ItodIv0cPrl6DL1hYV3y+eVPUm/Jf9heBFr5fiGnF93t,iv:l/MEFJ3tI7O1hxO0PvPosX9DgSO3istDZJ9z+dTSvVI=,tag:HxmpVzqxktQf6VEfkrz8IQ==,type:str]
                client_secret: ENC[AES256_GCM,data:KhHsC787V2ABmQQnMdE5CwHUsSdZ8Dr8/sFzx8Fi8uPAJgOE0WIiQFzz0JzUV14IqNsvRwZDB8Yd9Q/GhjlPX3wtT/H5VJdbwFOBakSf59hWRc7A9RY=,iv:aaxhAQB2pTUZQLwaR9DKr6pcgxyPHFp2mP1sDRaun0U=,tag:UGKWqXjKBpg1G2kNmYA9nA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:38Z"
          enc: CiUA4OM7eGmGnNCNVBexxp388ukBE6hW6yQqwbUX/W8NfhM2jKs3EkkAsHDEl/7w40oQb8YZb7lJ732rdobtWE2Fi6nlVgUaMcHw6uPGEbTs9iSBkJiCK8bUOBuxRAtaSAgoRwv3ZEGfU8s9uaHmLUbC
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:39Z"
    mac: ENC[AES256_GCM,data:1w1EFISo0ove2Vyq2DrnLQfoVm/dQ281jolORIA8SqeCUyhQ5t6J1hFmKEx+IJmKcKAIkDGler1mjkZ05ngNuIsSlFXgwwPKyBF5tKl117WzSRyhLkiHnfQwhfC+3Mk6UBlxdbWS5lBaIVJx6H+aUbP9ka94Dbxtjf7+DTez8T4=,iv:n3Gks5kkgX6DXDjo3RULQTtp+OFmh7X+y9ZQtpZac+0=,tag:4ayl6mIOeAMfighLdFG5qw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
