jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:cpH8yY9Tfu8LuHjVXBc5Sz9vwc1d135AhyN0AHYcW6Enh1a7dQyKjHY4bdNjFtUFhqXh,iv:5XWG34lmpWwBcsd6BZJyW1u8XOzhiXz1rTEud3dhWZo=,tag:FVszIhJb4/LNhpiZO4hFmg==,type:str]
        client_secret: ENC[AES256_GCM,data:9/hdVXKkFs9wxi9sgS4M3B3yVGWgjdGW74BIXEgzE8trO3+kJkaUSizQoh+jjn9M9z6YCieJxqQOqsaMf4enQYVpWjpi/rr8Mq0PS9e5QIWMlHN1H5o=,iv:WRqy97dEsCO7n6j9ON6dPi+wao8eVZ0m1abNdrPs8yY=,tag:D5v+KfMfQnrlg1lXO+V9mQ==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:xKcklpgZTDXnnQNMitMLh9EXzbeGrYvEOXofKis3TeqI8goNzOsbkY+MVcJKVIWpVjlnsBRGGWFTYUI9fMFN0BkB2VHzOJAjGailEjfVOSg2WPA5k1Y=,iv:TtwVKm451PCu2FTz6iqPTZTDNePCfasSusXWJYHIgXo=,tag:+k+XTPb21qlMnxyQg92GMw==,type:str]
        stringData: ENC[AES256_GCM,data:6zyf2WQQbSYAQlsXsJDCBZTje3rcSRG6xbiihN5jfYzpEtDdkt9hX3Q4TjaDtYGoJF1ieBBatUxskYGyckDA1MPXiseq8dnAnCNDpuyKJsLbO1O+jKu39PUBzVfEGUlpywLcigpfgl6YSRvvv+T143NjtwnkewQ5lfuTfy/rI0MfHXhVaHfpgo4/9+tvpXmt3AQMsXrhVqY694uo1R3leH8KETnlQHTPZngPXcAyVe9uRTsI4tiEV37xVAelfhyySvg29ybSJIqkYuwjCRtFnXiV+A+zkFGiORfKGLv6VdqLxUUleFiaofRarEyGTU13s3qCnP+pz0p8ykPM3fxIkMiEZzA7BcBUyFpfiumI8/i3sX+/ON/96neuIOkpsG1Nh62BkP31Y/5wsODNbg9FLBR2dlOy59yOlmBPinogXhE8xakD74PvcxMA+CJpQ47oSFfGohBKUR52Aqu6wgKT57citkJXVYo34dpvZ+DQL2yiyJCC0W+7DTyilgkwQsa0B8yi+snDwwdt1o6T1Yu0e43h0YHPQd/o+AS2qYBs8+Rff0VLEDzjrJWh/+PFRV98jXFhw5xzw0dqnvzf73Rqt+rcd9yxXIjwcJc7sKD9gVHTp1N3u/0qbR7N5BZSvMBmv/kAjnjGyJQY6J4xXA==,iv:5QtVXWoN/8OUp5Hz7wHBnBTHiTbZT+SbN5Qb6UcyK24=,tag:CsPW3h8Fzk+I49o+3FWmpQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:11Z'
    enc: CiUA4OM7eJP58qNbJj/nOaKQhKAVRbq5M2HI32WHLCt/tyK+hueuEkkAmy+eknn7hP11528kXPQAo0HiuL/cCkKlQ/RrVF9aeDGtk+Pd7PwVakhd2IP4Y6/qwtJ9QjJ1ZJ7n7HrxSB7iSch05C/EAoLg
  lastmodified: '2026-07-29T19:18:12Z'
  mac: ENC[AES256_GCM,data:pdeChpWuNOH7BE6kkFMItiWD13X+ny+FyZyeelkQ+PAbY3oWzE6mxG98B2CXpnHfvV/AFi23GuAkhEJuGAHg6ilNTOxgACsSN7kZe4OaK9UB8z5Sb2dech1EldtXAnnP28ocU0V6h6RSs8EPtvkzrd8GllxaluCItlpa9I5SRuw=,iv:HsVKinvDtdcgA5i9OWmQZsBASQnJ4A3kUq3tAfrS8FM=,tag:LdIlOPuwfeFz+QhQsN79Dw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
