jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:ux14q3uMc2NRx4DXYRYLylN5dH9Msmx2TD3L0mMEOG+ehsLFrLkTbxMUcZIfT325bY1l,iv:9ucZ4bTK8Env0BxSfhOSMdC+zm55KQIfl8PWDMQEtHI=,tag:wnanL2SpB88OvTq4nnSKtQ==,type:str]
                client_secret: ENC[AES256_GCM,data:Kbhqqwy4ciie4Q5EGCpuXIDgLpeXG/YuYJFvuQFhoNNkzQHO5f43RhPbs8pu1+YrFI4JVIyDzas4ALY28HKmvXeZf5WLBnvg9YzKHZhOBUqQP6Ztg2k=,iv:ObGbMfjJ2YXGWsQo/a6g5Zh+kzoHv7DmfXW8LhvFXX4=,tag:FcbN0H9OA9Fzpv1RQGPi8g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:06Z"
          enc: CiUA4OM7eIMX9igjCMd4YlvPJulifxQBnOf4jze+oMCPIihOF8sKEkkAsHDEl0ZfU+vTO4K5dVQh75pochJAn9hWd3YGwQZdr1Bs8qxX66XkrtDuAyCrDQghv4Yr86t0pG6pO5lTJynUMo79ydwX1+C3
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:07Z"
    mac: ENC[AES256_GCM,data:OuTO8bi+BK+Ia9uhoxCLDkI+KNG2sftpZ787l68LoW9DIMHlWW3rHJ+cvcnC5+F90PJTsrZtlYhg7EXZAw6I+mhJmoAgWCRpK/265+xLHx0CEd+jkgihDbFo43ecxjLI13zr+UXDfCWlB1J0DFuWA/jXYB3ly0TilRWLXi6d8cM=,iv:LGRcRou4UhFMFy2cWy96p1QW+G13Nm0G56BvHrhLQ9U=,tag:sgdwPV0GVTeizgAJnQBggA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
