jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:BPZsxo6Xj+OqjHVEiVthcVqYT1brKIlW6wypKeDINKYK2zmLoyCYFu7h3siN8Gw4aoLc,iv:Bb+tzAtZUc1WXaHmksaWl+TTqvwTKpJj4VUpjv4wIfE=,tag:hv/GJhWVKbP+XUrJ4vS1jQ==,type:str]
        client_secret: ENC[AES256_GCM,data:LTRIWsX71RGMXOpcaifERfULqn65D6VlGyOYihEtijkWpw94X6OmdFIWT8Lxr8oDYf8J9vJsxmiMQYcG/xE6cpWtrkFLwo7s0DUiGxBaHYCIsKhKZ2s=,iv:8Q6yatsVa3BR3YPLZrH8PzCsB2LIozaUk7V+6p1S09U=,tag:MzKoiSYdBm5y6Mm8BYlzUQ==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:SZXYhetSSzvykl9+9MZy9ZAJ9+Ib6TPWvcfdxNnlzj/81AnJ3izUbFxLLdu5Nnna20U9gBCvHeu5/1F770yQDQ==,iv:4Kc29ooNSKf66ukT0IKdcjSHkKV3w3Aevj2uyv2zWUw=,tag:jnY5ykEgGvP/f/ZC7FK2Ag==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:17:24Z'
    enc: CiUA4OM7eGrw3f2EzpNxTCmJBalOq/EPSp8Pe5cjJE+90+UsP4VpEkkAsHDEl4WCRvYWi0vMT9rYz1BfGfJoArbcaU2LdCgLOBBixakel5n37vTl9+YASq2PpAEnw7WzgFXjmEM5IHD8oJ94oPBGdUDR
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:17:24Z'
  mac: ENC[AES256_GCM,data:QrGWT1xzfoqB6bgOOEvzBtahsrackjQhE+MWpOtbEJM6gaLufK7HyFe5O2rCLC56feac8/IEI6ew3X8aevAyJ3pfZ5P1KCKegmTiSe6MKeUgQOCyvOKVxnBsWz17GknXYtyPG4viDOrlep6LMvh0tMRbsrqcBsx5V1e1Ej6XN6g=,iv:3U0XdsFK4mjgFojDNYXu9uGWDZJG9hpMLdvsunzPy/8=,tag:LPcNrRcMtPgKZToOoLaeyg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
