jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:7cLPCPHnM2ex8faT1P+sZsBl7RyhcPu9ou47Et4DXoZXUNTbKfSV5epbMDFz9oIb0fhB,iv:MQS92JVJzhmhWJhmoHo7Wekf3JAcZa/kBIMS56eQLGI=,tag:Eu1JIrzOtDZH+ce8AuWQ7w==,type:str]
        client_secret: ENC[AES256_GCM,data:9FQ/7NbHmUCECVpFVCSZ6JkMlYSJnD1tcggrN4z7IZtNhrZN32iGh1b/RL4fzBhCy8M8/9P6MHmnkGN6VMC/662ds7yukkn3hdr7lyinC/pbdt4rMSM=,iv:Uw8MCust2N7uNlbuqMWJTSjaCIEb24XeDDrstlWSVRM=,tag:9jGiwn3aH+1GzLg/p0nAFA==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:C+kYlj1DvmztTcp34p+gsXr0SdlzHMbyIlr0V4bpZMOeeydGPAtdZzyBw3EixGeb969U1zJNBvtBM0VHBTCle+IKjRDN7CpdQ97lNRFeoQ5BD9KYDds=,iv:CSNA4kyATakrrA2K5ReND5arDKbV9zpm4Jfr8UvlXl4=,tag:+pB0S3ck8zvmq+3oJnIcPw==,type:str]
        stringData: ENC[AES256_GCM,data:d7ylqJAIT5NF4cYnrTST7p1j6cXIcGMtJrUykoP4acrLjzTvGZ08vN3ik/H5n6SLcIkrezdC9q5j61Y8Bt50Z6YHzmOKKf3CNd4ASUPLy1OwZccd880RyzXZplWkn40bvhR0GJobQ9gRT8xaXS4GMMHE+Va2XSI/NSOd/dN1TIPrcsw9vimUZC26K2AO6fkrDqJVZD+/49Vp5o0qHYf2yWpaZMDMP5zz7czkb3oCowzF9aN+cYNXoQbN2LUw77OaRUsmfoiTMPXRZakr1S6Qo7k2gkzLsPi90X+c62bDlibBUZLstSyFn53OTPb1vtoFKhofSO37lXMjkb3z2b7EXSjJqORbcwI89khXfYt2qGf/xo+z0T7bQ0i52aGkxPVSV7H2WecbwHhG5/NtpRK5LwrKryaNWc3gcesVLAey5w1hvloN5iy/swiLtf9QQArwew6VTCew3CYUPZgzGVMMfZecCbjLo3i8cVwjHzPC1fV3RbokBpXX7L5CweOmmczT4qefiP307YzG5lbr+Q1PnwTVSUdypK2mXwlQ6q+i/CQESZJPOkj5DFN4ASFxn6PXuuiemEi4SIhtOYfkFG/hsDpteakwcjdDn6isWLdaVg7Otf9dahdVd0Shn6fOuyCuKSYkDIL+jnoFwVvA/Q==,iv:qKjzna50ZDq9mIZd8bV3B/S5x5x6W8ir6XUleJ1/VY4=,tag:KUnjC8fKrLI1b2zoWnigAw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:33Z'
    enc: CiUA4OM7eInaQX4rhIkwZjNOupJUVo0GIR8m5mOwuiPVBQrRXXb+EkkAmy+ekhmb2bAqRhikLoV6Azhcmn5VFTrpAwEiYJSAc6dFQ7ldlzzi7Xl2AA8X7BG6PG6kL+erKjoKvtZTWZW78pHa3fr1sUXv
  lastmodified: '2026-07-29T19:18:34Z'
  mac: ENC[AES256_GCM,data:AgdVUk0ThfrYp008M1b8xBvUU7wwv0WkKnNy047Me6TOlVe3zC3uHIpkzGoXFnL0LTd8QQyjAFzSpqz4Fq98+xTZyMOLRxByvXDDgHJzcROjOfKHxc9DGdJmIBcjW8nHcISA8X1UzqFj5K8wICLAVzQYKR52htWdmI4G5c2NoJ8=,iv:WDjRW13MkZt35DOlMN2pCQHcglKkcE1uTDuf6Tv35ss=,tag:ZHeLmjwRt7Ss13OKq+G1ZA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
