jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:72PMX8RtcMxe9J1CgfKDDDtv/6nkxmfc2mKhiioybQQ20pEj5j23OkmBkAxPEoeHg9PU,iv:D6T8URsRVEJglAEkBbL6Gk1kPFd0F6M+dJeHfFBW0Nc=,tag:1DwRoaWRJ8xAayDHSG/Qiw==,type:str]
        client_secret: ENC[AES256_GCM,data:nMH99aRUkzbV3TL9a1jXVqVS6IDuSLuDNnk/yiEhvumN1v2yOBP6VoZzbdOPHP7Rmh+R4jKGdujIYxUQtXp2w3SH4ddpA/d214dW03fHH2HSq0aN724=,iv:pJPseefzvsIEuO8YTY8KQHTyHxrgQ56F24pv/yWFqRw=,tag:PVAnL1QBbAL6c+zuIUqQDQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:12Z'
    enc: CiUA4OM7eHzigQwnO/wNixiPYWyp3NE88p40G+78D8IWSE51VgG8EkkAsHDElyd/ZZEAsGfZo9zB0mIZDL9IjzV9CcZWQ/HvxB2/Wu28UdxcUwk91+hbIog38OUMnHtsdnXX3xfz06YhjwEB7/rdGiuk
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:12Z'
  mac: ENC[AES256_GCM,data:0Ji6OBh9tQE/Mkfy6UUVWIbRzyPDcbNDlDPPtpQCVf2DWVsS0+D5Q9snJlxO881QbFuze0KsOCcFokFleKeI/U6wTlttManHsQEtM4JlAhu2pvKL7dAaCHBvp/ZlcpyQxMLI/vjVFqj33U5TAfycnygTHiDPnt/NUPaBovwlRS8=,iv:oq0x7V1BC2CE6ikTFe+iVHLLLRhfqPcwoaIaQ5m9+VE=,tag:GdnD3q7G9Ts9M3iN4NGmBQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
