jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:pUIiG8nL/oiha30zSLyfj2+ryhGEpI01Snp7AqR4N6UvMLfH+mxFMMquJIJ+e1W9Ncbn,iv:QXcxMYAkziSyBrYKkTA/K9Y5iBbtpQbIsFDdZkLmfRo=,tag:WBxmFjzRT0sbbSYuQpvj4w==,type:str]
        client_secret: ENC[AES256_GCM,data:SmcyKtHbJbV16NdF6c8eD2V/pzflA/GVJmXxnmLHNGmD3lnV1ABJgsW9RsDj7jfkqjxyoxHUuBqfRpsqHCp97+aP1MmX/eWlC1UyXC55nSZf5wmzV+0=,iv:FLXmIaF3Grgkem/zArlE5c2gBS1gLWm7e1bYDFSG8cM=,tag:0pYBO7Xrf4meYVlza1xawQ==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:Wlt3gOJuOPZG/vZ2nqJADa3o6HwiR7uoBqdhKzUpUtzUgc1gYli2WuGYWB9m7ZWrYiCPpRMO9vL3MJ+u5xHuNQ==,iv:my19r4GXMv6gySgXG1ZBLdW1vDbbQqFQiXJ1t0MWK7E=,tag:dB/4PSY9fr++CiG1x5dVgA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:17:47Z'
    enc: CiUA4OM7eLwk5nd6kVXwyT/tMh5pSKaVj0W63bwYJFdMG+snakDPEkkAsHDEl//xBYqi96I7KdbkFtp1z6x6j57+jsiJYCiDr0+T5hCMr+VqCoNR4rW1aEREaxwm4oC5fvsfu1M0+H8dfb8NtO1ixOVJ
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:17:48Z'
  mac: ENC[AES256_GCM,data:WQOKUhLn+bmKm0PfTSisaaLFCF1WLvS6X7RI6w3ijF4cFbaJkuJgbBZpgMpGTebBljWlEBAAEn6QON9AtbKse3XymciF4ns0oyCcsItQ6v6ryBhKFnl6n8vPxnpDBpHm57P6G02qROrtj4QRTCdS/R/74tJKRaE/yjkVYilXPRw=,iv:S0RxWEHh0wO2XuKnNqvSSLfYkhnb8jArSCSO3LBvojw=,tag:JVZ5WRF4AUCl88/wkZsBgg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
