jupyterhub:
  hub:
    config:
      GoogleOAuthenticator:
        client_id: ENC[AES256_GCM,data:dHVTjGbftS7Xt34+ILKmZVGqMbhHF+iIGNG60ubSO//jUWcTaLJdW/wbUhwSjSj+sd1P+MEcDUtHtVQ49q6Xhd2EA6759djy,iv:X7ZA0e7d/D4zOtOPN+ctXMTNWaPO2TE6/WX6N44u88A=,tag:CQbyQCRCzPll84EKSP7BUg==,type:str]
        client_secret: ENC[AES256_GCM,data:TjgGsP48d1tE7Zhe5aAIuv5NINStBQDbGYskUxTpPRMS1Yk=,iv:uYSSNbV1DssCtBWagXsmSGTyDf7mi0ldUSlyiJ7Rxrw=,tag:FQmQ7paMGJ4EbQH/7m28kg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-01T23:41:30Z'
    enc: CiUA4OM7ePiJb5i7l0kgvpOcasOyZlTrNTsHRRAenhNc1dYqOPQqEkkAmy+eki3yN8hocqANW9iLnz+RcXuAr4zy/MOTpNJ97qEpdKNwKEniklgl+SeGzf9Iu4cxNb0ngsBva2Gi+tcsyIagbRdeZTny
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-07-01T23:41:30Z'
  mac: ENC[AES256_GCM,data:YlICAUf1ACTh1Yqnd22YPDegMee/D1UKqibR6oX7mraFOFX+lC5k1GK4yVH5WBx+WCBwZqTzsrdr/KPca68IqJDUg7QKtF1rkU4gc/nBILyuBgOF6o8TfLlMl4NPT4K779yu5wH7+d4zqgRj+3xzHtCxWDVW21HpeMUmJ1nBKfs=,iv:XLgD1t/h4x7kX7OaggL804/2YkJWdi70ZwORkOxmM6I=,tag:+FS3t1mlM3M2Rd/DMUnUYQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
