jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:ul9Vy5KPd52qCKPC+ZANy9PGIKD8Z2jmCeJBIsTvwtDA6VCUeTEPLmVOQIozb6l20AXu,iv:K6mvB2KWC3gELjtS8vuSNiV4q0R3ucl0/imqKgNbnVw=,tag:SJvfeks6xJG2diwzUS4o8A==,type:str]
        client_secret: ENC[AES256_GCM,data:7XbGcnNKYU4aD2e+7VHjpmevqVNnPl9ZAFNuE+MhxhUyPT5KzSKN+Q+/41/13bdZTxLAbl210en0OeHgwsvCB5h13zDqsCafR3isvYkl9vMH+fYwlo8=,iv:f+NGu4WpkM9w4Wjq7HB2PUYMZFgLOYh9Tike6pdJqlA=,tag:ofmbV7y4qsuC5mkYHS7Zzg==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:9McU0sYPgnXiNA9nK1jBQfGf4efoj5xBKD+bTZSYSlsq2jpy9LZalktG5leglDftvGZee4YOyXeKveJ9JhZadQ==,iv:Jd8w71cSyIPWWD2JB/kDquIHCKQFu4A5oUVb8keI2ak=,tag:qTYZjpfOe5O9sFyjXdV1bw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:17:54Z'
    enc: CiUA4OM7eG1dWhlahj6+bRLymYpAkbombm+YaRi9icyypI0K5US2EkkAsHDEl/ayTNv129+3miV3TYDUJXbvJ2HYMRuJy5dZGLqOkYt73ADvEqQqmwRqTz8t8VfRfRUe7S7WvupICh3kPuyxrRT4jfXa
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:17:55Z'
  mac: ENC[AES256_GCM,data:q5fPG76alczM1P6OHMLA6QQWoqMB2zMwhwVucHKnPNUpXRTxRyRnsSlesbzb3NshoQmkYw7/bPPxJoMC71f/yF0kPUgh1V+hQONDhb9OxpjvwTvXNHTRk38S2X10J5juyutApGhIhr9bxmik4EZ9uuh8ovpJlFxnqgjLRET3GPc=,iv:rwxE/pHPgORbQSAaaHN4pqHmhCgsoQ5Ii51TFhyFpU4=,tag:WfYHgfZmRylF7IucodNAAg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
