jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:1afng23UaWQ1ZOKrX9qP0SJgsv7WkBzjT/C4FI6AoeqhS8dLLdBI2Hr396QNcwC/kvRa,iv:s7th+LakrrRPVusImCxpibkwdcHTjegv2XbEOBZxHTE=,tag:6m65dRivlrR7cv7wNR09hA==,type:str]
        client_secret: ENC[AES256_GCM,data:+MzTAqspo6WTd0ZK/1Tw8RN+csrKGeiyfZ4OO63p1ELE0HR0qhB2RrBy+rvSiFD41JF465/cB44hcL13WACpMJ4Az0rY6HgcFBVEDqmBKlCqpakpris=,iv:LHfMfyzaEHSwxDV3lqkwAN8736dabm3RydZdz0rpFRg=,tag:A+c6Rd9so8E0g4wi3y1b4g==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-09-16T01:29:38Z'
    enc: CiUA4OM7eM8bIgjPO2u+V0h3g/SifctNgN9nlzw/y3ZY0CY7/I0FEkkAsHDElxfmsrX7z874OiFWCdr0Z7aWXaKMq+aLGjBzOkZb/EHIGyF+jAq5pFVD9m9o7cqMxStegk0d1koHRanbz1HRrmZdN6Mv
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-09-16T01:29:39Z'
  mac: ENC[AES256_GCM,data:knaUVQJPzOz2gAWxAXp6vjlx3lUWk09DIyVbLi0/SYDdxcwy/ll5h5qTr89DUnK85iygxEU9ZqGg1nwWPMI8ED7LOJmU4UmhDkKNJbg/rGkStLSMgP+m7dH9Y+7Dcfn4uHieQlMehBEf+1nPTj5w5v1MCnfRvhiZS9H2bjqlC8c=,iv:qN0jZ0fETiX0Q32qpGdbcV9OTdKwX0C8Xecpd1mnPLQ=,tag:xeaLIkjhl9urwcy0/FNXjg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
