jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:lJ5QhZRz6wuMAZlxNUnS+o1x3ViT3/w1C7ZrodDklHDxetf20cBHddE5FY0YAUCV+UwfW9Ei+VHTvOQ1RSLbYukbUbQeDySO,iv:xMrtYJCmyzWvrqtup/0fuS+OibxytgtAC+ArWQNhrKo=,tag:zmkuuCWaa61rN632a8Ws8g==,type:str]
                client_secret: ENC[AES256_GCM,data:71mHeqCT0NKbkh5tVb1nGQPLyfbX69hrsPipjO3IHR4a6yU=,iv:edD+NpSY7O49xX5czPVmtC4XmUutdpeluB3s1NsgOAM=,tag:/Sd2ndFr/NSADHRvZJgZRA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:48:03Z"
          enc: CiUA4OM7eD/3kjCUzYMzvLqBNMOz2QIP5a5WgeVczZfB+rACCIo6EkkAsHDEl3uOhfI0hgvsFt3kCEGpZMqVxdS2BVORvzYbdQ82PmqBn0t5nK8SMJFSW/d1UVcZTVmJuxyAcd3O4aQduVU0vW2YnupP
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:48:04Z"
    mac: ENC[AES256_GCM,data:egG8Oe90rrU41MRUPTcuWVTZ6tsoadZjT1hnSVvdtTN5f3nTXxeAzlUpYERuzyG7fVikRqCrlJQ4/hHIClAB0eU/lxSzhRHo5WGGVLjcCrqPmehpc7syBHBisnFzHN/PX1MEVktfbOhcG/TyaJQFtHtgXXep1+bg2BRwq1/Dq6k=,iv:JkZNUE942euF/ocNfgCEY0VkXzzueHMWIS9G9KVgvDg=,tag:hSA0/iUUDPnQR3YSnvqN3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
