jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:/zL2q48Bo7bqVrhkMwNBEl+nkgVeZmSJrLqhLX6GWQzsQIXLeyocntvFBMfbQ7GHpuRY,iv:Tfmbl2IJHwnydT6xR1uspzi5Nvs7K6xl8KVlezoRm+U=,tag:KH8I1NpHY+SMiAGvVLheMQ==,type:str]
        client_secret: ENC[AES256_GCM,data:6dpfzg+hNETmvCFLPAdcJkUjnywi2ijtkA2RysKpYCENVjWmZphiAGvlVowqfSfEWWMuF2KXJL/33IG/S0nbD1HizUisLkeZSNOqM/16Uxe+3rmI1eU=,iv:4B1btkdRdFlO3eHGBdCjBuB73K6n3+GI+l90pQbhSq4=,tag:Wna0QFwN+xSxW9gY56vIBA==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:1r2aMvXlvxNWscGcIx1u5tTQXu/IQOHCDMKPnt85IfjN1cDxF8XkcNULu0cMZ+NtVjLipdTRIq7KXtkOb02T3gdapSybmM5DEZ5ODpQw+6mUtQQUXTk=,iv:R5oS4P4r8F3yFhTSCZj2b6mWiOKFLlsMSAoVtMi47gA=,tag:LNZkcKz/CA/BEkquj6T5jA==,type:str]
        stringData: ENC[AES256_GCM,data:wmrjTjVr+Gf0sUGWCpDuB+mt5aXYZK2uz+VwfuODTB5yP1bFGuSb3+BRXmm8zBRVog8Mf9p2fddwft4TDwLFE8xkqBBjNN13s1Cg1xSgiOpVxA37g1OyA5vTfztQeKwEVNnAZAoSlW6Y/5DShSr8tmoXB9KcltP6kvf4TtBcvE++T3gproYsResanefL8oB0ExFDxmwkhvq56kwEBvFILJaUV20ZTPxwcFIeYz2mIGEEc9ec4xTRpiHr3bA8ijN+eA5smDwew1qI/iAULq/CVekKZSgs2SRawCXr/NgZVlTcynhN3gSw7WK2LrtvON2qzRkX8JugYdQ0l6CthEQ3as/R5+UgeeFKmupKCwpI3Lc7QgEspEcl/xIUuYt3n7ig4f9P16oDD6GWEjvTcKQL9gqX9H/jbsCIS//P4aJnReX14WxM7T+5ij8dO8lzRqoUraYXf94LkXaKt0pPVAI9j68tQ83/xylj2nucRl1jUGEVPFphCyyw1H1t4CctXW4hAfxPi7CGlzKrMKetBuS3d6Dtmu7IsRoeVszppn7zJiXtyUNeokgJjlPceQid37Ah5AtRgXNbzRAs4iMu2OJmzvdpKbPYeSnvGr6E3Zv70HyhpPGTmVH2jybPixos81eDHZ7YVSRsGzUdO6Vv1Q==,iv:YJhv8Ur+Xy7r5BADSnfNpxbGXxKGxrEAjA00MulHVT4=,tag:PksfgMoWaTnYYzthB32gIA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:51Z'
    enc: CiUA4OM7eA19GLh1CQhuPEPO2twyCnCRE9R75PMO7PDO/KBtfF47EkkAmy+ekh5nfrwHkOa9Oq5tXeg5wyxqbEHz8ZlhdeXBQt5BITyDQYY+JtsVdK0wnNwsCCutFDJ99Z22I638OVZII7E4hgkV/R47
  lastmodified: '2026-07-29T19:18:51Z'
  mac: ENC[AES256_GCM,data:pbqHrUB5eY7XKCjlpcZhZ8+me9gn6on6CyHhiA04AC8G+fFX/3/4XKQUYDKe74HhmM0MzKSd4lo22x39N4ARQZ+1Tds1dx8oQMXMnPn4HW6yJWi55nQNbbkArlXeNyOKPfF6LY7X7vptJu12SVhFkOEp0jrInD4As6Rt/gNY8No=,iv:PO5eHG8DQ36lEk3/319VHO8SWA5aRe+KRJHxJaKFyp0=,tag:v6R9hKdjd6evi6TCb0v5aA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
