jupyterhub:
    hub:
        config:
            GitHubOAuthenticator:
                client_id: ENC[AES256_GCM,data:rf7QasznnJgIof0JU7EGrZ6twc4=,iv:TIJNJV5BgMMJIaO/2+8ETsQr1xOn3KzgTm16CrTprLE=,tag:cTZkWzmJ6J1i9syAFfBUoQ==,type:str]
                client_secret: ENC[AES256_GCM,data:9bn2J4ITybD14vEWur6R2cpEQJ4bIM42jJ66EqtIhlKBeZ0RSXc4PQ==,iv:krKji2sqdhnav5TKYXNqqqYphn8vWSwgV2F5KqoN54g=,tag:YIXyAQ+j+PzKiHoLE2d4Zg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:29Z"
          enc: CiUA4OM7eFVvRqPkoEV7i5sVdGh5ikesGtLr8yzA3zNQ3qjL1BwAEkkAsHDEl8LKqwJWRLHJz2As78rUZfBR+koriR8mYzICzM7TG6x/lHPo1FirzADpAxHpN6ILgPVk0/H+kvPqhcOji7dHqWdKO71a
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:30Z"
    mac: ENC[AES256_GCM,data:R2VCEkuWrlWKUZhpt12K6JgiqwER9zHq2lP5UuiIPgpk0o8T7oIfMZ09x2HVcfG/022Zmjgo8zHG//XRo+xGsxENk5PoYCuielu71s3KyAUbrfLFBbx3JCrrFh00ifi980oGRGIZAVqu/B4+DrkKVdyqlzaduLAOb/wfL5eZ2GM=,iv:YbmnicAMqXKO/n5gSZ/+3JE6zbHVCYv/PxzY7ubMEqY=,tag:v/zymo8eM+UxFon4cYgJXQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
