jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:2lo+7WEx3DBrsXKnP6S7zm/yhxRwWDE/VXCDZjvKEOPTHaij5xTe+v+eDtRdVy7KRqH7,iv:Y8AVHteuP3YYz0o2KHU33APd7wgdpyz60InPCw33gmg=,tag:FmURivgICf7bjnVW005BYg==,type:str]
        client_secret: ENC[AES256_GCM,data:5d5yUOeBQo0bRGpUfdu0QZEGSalXvmUl4vX09ju9VXcILUYzQIy3AgUhjoz1H1hhZuGWLwCFmbNK+lw91K3hDvsT9Zp7KzzJQ/gm1aPdozRDiFos2bo=,iv:l4WTohQEr+nGx42DxCp4xL3AREJgN/TcCuj1lvspawo=,tag:UdArZX40kaJi+9UvLVD8jg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-16T19:34:12Z'
    enc: CiUA4OM7eOXqrrcfSaqwpHMYJciy+bNdN+ccKKdKiFEBUFg6HgOGEkkAsHDElyKNxDW6ZE/5cvw3S9lLlVM4B4b6GeAU7KwJWZTtB2V7VVHqPFGFYkib8EQriWQ8HFBP+z76RazLjd4uGI+GPTgBKCrd
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-16T19:34:12Z'
  mac: ENC[AES256_GCM,data:H8VatOqm9nxq1VgA9onogyqLurXWDqgrhyoz8NE7yt8RIL9+Idtzoh8xdyocQ8vjSlCeOBg/W+6dE/Vh7+S7VuxIk1d7XliyYv7FOeIvRNEYamfcMV8MBiJ3OOvzAfFQjpWgSP9WXhUt4wIHTYKwdVRidEV9pTUVmJ4yXTzmbOQ=,iv:0CvoksfLNJVxPq/nEE9wj5h1CSo6rCq8tFCISXDxv8c=,tag:7tgl2lTljVklA46r7qkc+A==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
