jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:txVFDvnzEDNhbBub4Ue3HjNmycp689GNZYYLpSUJM1doOX6VAkhtCn4nUl1MaEUhO2Ae,iv:XWCMAZ5keXq5TiOWQFciG03aDtVaTGmMVm1QtuaWqJ0=,tag:0TlijWpocm7LY+znWSd6pg==,type:str]
        client_secret: ENC[AES256_GCM,data:6LoO+AHDC3VKhcneBib+e1GFUd7jvVwFk0SCriVPZa17GvFd45c5sgDYz2ad2/PV7wGL3sXfFzDX2UFW17e358TaQ7NV9uTIWU5yoyxk8WWsFsohy7M=,iv:l/SpaG2I3ogKZPPCDVdMqjIt5/s87G6jVYaMh4hEHrs=,tag:mi4XbgU4BMGvYKBvLYPMKA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:27Z'
    enc: CiUA4OM7eBWnot84loXchsK/7vxQz77j8taxP6+28jb0NSsM0VtIEkkAsHDEl9VSl/BefLfpN/HiT1LHRxiddsKBW+7zmUyn9SSpQkT/9S/h+Bd9qNUuWUqExlwluYJgzX18x8Nal1roiXAzB+8itala
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:27Z'
  mac: ENC[AES256_GCM,data:rn1HGedZ30hvzeFZtWmnKcwEuKRWXaL0OD6/XFxfhV2tn5vPcao1YHKBqwXwCd9+WTCE59aPqzAdSImhQCI9ifgi6bdawzbmM75SU0BdQYtHTAT3kE1CidspSYfihpy7Dy5kWliFQL7VpnxospVfWVw7v+Ai6148uBk7QKMaVac=,iv:b1s2GKqfZTpd5HVjEyR98qm3gQMicMZD0ps3twWkoN4=,tag:NWRsxR6Pdi992GteZ9lHNg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
