jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:CDAraHmyHnE+FWmEwpHR2zsxJ5Xtr7isBlpxke0ED2gGjRTZmXIsP5DOZj/cLw+vPaU=,iv:gmc7faAqtINt+eA69posNwSxgndnQ8A9wC/0Wh9oNMo=,tag:Dx98wSwdkxTb5+NGAoct7g==,type:str]
        client_secret: ENC[AES256_GCM,data:Sx0NxxJTnOW6BISrsBtsJyOjss75vol243XrMMG/1vC2WsuNuhbZuQKbL7mYDe+rXB/JSG30JVIfKlFtwi3Dc6bQu+Ut6lmVpJHg9LWOOAEUBSyiqDg=,iv:WER5P8j1gw4z6ekSNARxg9AIOd+qLwsfHH07QTsVl00=,tag:v2iRTNUgpOAVmVSlSdfWwg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:WMGASficbzafZUJ/hz1dJAtbhXLPwhRl+UsmmsDZ9uWdmouDfzQyfEyNehmyDBnpSNdzKD4ctcGowPMKyoUfYxZBIb/i3oa3Cxvbnkiv8+9qbrXHfx4=,iv:0xeoGm1h236JwfZ1P6kekACmVk5Dex6dYCUTTFtxomc=,tag:kWWT5bbzgOsgUltMBAPrRw==,type:str]
        stringData: ENC[AES256_GCM,data:JwCs/pujhidOgPPOcF8Pe9IHilT63x9SFHtZlxCUjV+lIAOkTUwW0fgfw/+UOiyLpws7YNpZ0LtlL3uOkbbMLv7f46Nt9CFZJbkS7fczLfAOgb7iAJb5afxO+6PwMi+yFcHZ1yBhQQBbf0k0f5Ij4k0UzeR5fuRBuMPfADjniZd2uir+sPrer4gTA8qe5ZzgawDNpPgiRf/kh7HCYZQte74u43FuedXH4CIHyHtA72fGBY3G8TImF1seNDEzlzahTKlzVabE4Bm2W9k+oyEwmss7UloiTBhL19BM7Z7/uHkFqo3hrftN+wQlT4W5krFVwV8yokvTZtnz6fT/pYNU9Wi6n8/NAnrMDg1Ke1Q7+wkXJbY6B/6M7o3VNHRJ+7Jt9FFTs4GhOpGZE01tiegjYb/49vYDPrCeAl4sI87mrEyO8ShZc4XXDIBw2XKg+0dn0ke2qv7F/fm0mf0UlRnkPLrxnwL4pWvfXNzhK/8Rco7kT3Xt7xOW+BOTnqd2X76HQjoeEt5u++LsGqEQBI+DX/M8PR8BghSI/e1q0tUaNFJ5e25HDGMDqbSGd4T0UnXaIiPv99ZUXPuWvOg5rz42D5BH/Hioo1nGBB5WP188AN7fXAyQ07NIaah0tW0uZqg46hZ3mW0qDyHpQJYAtg==,iv:viv2iaxcdzAokyqx0sTobBMIXlqzTLa8ItG2N2PiQPY=,tag:hgJQGRuW5XfOg2xYQLJK/g==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:50Z'
    enc: CiUA4OM7eLDt/RyP+kssBYMWe90vcpvzUQHMjBKwFnoaesXj6iVhEkkAmy+ekjPcX+6UgFv3aS6m/dUF0L8BpnkolduGNlVQw/QtpN/YWLn3AuggbnZIK+fWdgR+71yFM6yifg7ufq5Iw1Qt5ZqOzZVY
  lastmodified: '2026-07-29T19:19:51Z'
  mac: ENC[AES256_GCM,data:acEgWB5MnLILgrTJ0LuJYSH5s0dZUJedrzioy1uUX7pmvpiQl/Se8fr9Q864om0CreaW3BECG6UvlBprAJCt+kvihNVQ//V+n44Mo5InrqpwWqmh9X5Re/7DXmaJoN+zrmGcqK4xoDKHnh2Tx7R0mOsf7EdTCwK5IcM3LUmAmdc=,iv:4O+oXKB7V4FD94YIB+ppxLK4BU5iY5bJyR27XCUAhSA=,tag:dsTXlTZgd+IDA4be8LHxEw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
