jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:WlapQZVUMLVocvwhGuArIyGoWOT3tP/h7NGCQkXmgEDvaYefrRZ69VdHbEVh3sXrKHyG,iv:KB97Q4+8HOwYqVkNHHThV90C7Ep3ZFTIVe289hdit4Q=,tag:7UwqpLVj88qO/4tUYMkUzA==,type:str]
        client_secret: ENC[AES256_GCM,data:B4EwWorTQLlmQBHtbICj56XON7al7Q7ecEp3IQ2WgzHIAPOwnJgsube2tPPBdR/4/USJPI6d0R9ZMFSmDzpIxab+93J4cgY6DxzKt0nsSI34XfqN/bk=,iv:VOd0QjDhPOi2yENZ+Q4Cwsl6/bODJepZY58sE1O6NRw=,tag:Iqo5TA242iCmRntryP8C8A==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:pSjepfuX58X53I50FKgVzpFYyQnzPkaKWF6IcC25WiER23RZWpHoj8vmzNYwN0aV9cbmEiehL1MS+qtGFIWAeA==,iv:ssF3i7GpsGl3+Lu/wIHn4I2UCjhOwmr/LjoRcBVTgfE=,tag:fHznF1JZmBdnmoIFCvahRQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T14:51:28Z'
    enc: CiUA4OM7eAal2oK15MSk5+31TYjopgZkMDPsZrcWi9p3XbRYDVDzEkkAsHDEl1a48UAud7zPGPoCHQfyvAZT2Zo47AfgxP4It9GHgewqfH0VD7k5WHD8dyKT1ycdljboj0BecIDmR77Ch0cP/yu/XWmv
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T14:51:29Z'
  mac: ENC[AES256_GCM,data:Sr5aZ5VuSFXwyelgBXBuKelf2/g7m+pr1YKkZmt5ZpDy9x9DdWROzoKxHq5DFizWPVVuMXgF7wIVRoGGk3GzBsdjs88bNzJaVs/Fxhx0ONJ1QIHHtQKhyHBtvPeqlW6q6+vMD0mwX3G+kMUvDPSak8PL5jUbfHo29JrXlq6XXIU=,iv:mf0/Vq4hMgGSKXhBG6olMyArlfbTwgfHb+a6Z/VafQk=,tag:vklrdB+5aoLnUTvnulQ4cw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
