jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:SgLSqCH7/GF3tlhjwsWrIx5RTFBN8xzRe7/onO47m8BT5KEh1OOBZ0Jw99QV3ZiiFyL9,iv:Qcmi/GCgP8Yv4Y4HHVEhMliFK5thrbU0SjHszscqosY=,tag:tcGxwuPN1CjyDtjo4/A62g==,type:str]
                client_secret: ENC[AES256_GCM,data:FLkGHlcndgpXo3e5EdAgVs4rwAtoOcti2WU2WzRWI7l4AuXRgvth8YrOUq6z6PGTU7nvPGjz0nNZTeRAcBwYRrCDSTAvLA9JIy0ARShJBfWuTHOifh0=,iv:5pdMHmJAxVL9TuoV7k5gFibk0/EPzHFwdyIyLopydkg=,tag:7A/p/Tf9W6udYBSRVsdfww==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-06-23T23:59:58Z"
          enc: CiUA4OM7eKX3n2qG4Kbr5Dj76rx00QDBgdISOsoA9vtEOymE5Po+EkkAmy+ekvZsls29bqv3+DsFWn81cCHLCDQ4sAAv+lRWSAW+J74RXLXVONaV0b3fei65owaJSRs235mHEFFwAVShkvJoeB6zRuO1
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-23T23:59:58Z"
    mac: ENC[AES256_GCM,data:7YZZlLAwns3nM2c25QR0fD1yxF9m7VLvYwjfJPnZNq+YiLtIMUnx/GwHe8BoR0aUWEb0JxKXiLQHtowbmDfOJ3EYqTFRRhae/avGIno4ht186JkM4F3ZiaIEPU/VY1PabJKs+VxdHFGucQhbgbO7Uzu19d4gpyYoBzqk0LE9uck=,iv:dJmjRl+SShEiinhdPcr6E0I2nxzF2a43DLdkViKoZnk=,tag:tdWGsJU+KoHvKhtvjEIvrA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
