jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:whQT4DzgCUbk20Zlcv2625OdHEiVSnrt6eLS5r+uvyE0gLUCG1jeNUy15BhZQ0J9OL0O,iv:OAE1GAzzRvJjTEziv241wJnB4CTYXwoqOBWdaapVJRk=,tag:95O4NGM8zcbiu0gwkwh6ug==,type:str]
        client_secret: ENC[AES256_GCM,data:JYylhi1o4GxqL+NZxC+LzU2ptuemuGl76tcG5BNp4KeIkDPDRHB4OyFeA6r0XBecs8crml3LxICx292JMXl6nunyqeAAT9h0wj8ig/dLOYPblOsksIQ=,iv:ldeg7WTPsikvRefJgyUlBWnyoUy1JxTQFgc4TaOEysI=,tag:lXQct+LFO6/qMiwxTjiIpw==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:roPDAZwNrM1BCVBRlU9hFgfL+gkx8SyHq+wpYTF0XwdIUCOA45xNvCiLGRBG5IyLYBTO/xLu0LpwuHNo8DTZgA==,iv:JrU6Fu+FdEpTSOxKGF+iZ73fQM6669eQhhOYW9crMlw=,tag:bSYr0XT0E+MV+nHS6zZiIQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:18:17Z'
    enc: CiUA4OM7eBvaevwtgRuxR9Gsd0L0JoCjpDeZoTuN6+lptYTj2KV3EkkAsHDEl/Ty6XRwa00z/ad3xyec4D3ePIz4IU+h8UW7P9rgxn6ki0cuNSmVNEz3YgXvfBo8ehM6M5+mtcg61OCvb0Chy3aYdR4i
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:18:17Z'
  mac: ENC[AES256_GCM,data:Gur8UPEkHG17NMdOdCBAFC0T5PWc2Jbm/4HL5UYuNA79jBtMvOZH0kUkUVDNad7U44oRRdBJaD12hT5LE5seEEGGQC9La1W+pDuOXmJnS0qvMdZ89so9zLxypENNN31BncvoS9ZJrkmef+q3lCpTFyASDk3iCR22ACC5tTHbFcE=,iv:n1oCXkurDRGRHkt6Inn8/8WIYd4zeI8+pUaIiKODFXA=,tag:W4JHoXPLJyStFz81dCFOrA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
