jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:AadoI+Opb/eKeKc8JEAD3t9vuWf2wu3V2Fr66FoFu0/mw1Q1YOJ1H7sxcoGAS1qKCbHm,iv:ekAmAQFK6wElKFeABTJoovBwJZ0r+Mb6Mj1I5wOE888=,tag:T1kJesPGv/EO/YFyv5QSuA==,type:str]
        client_secret: ENC[AES256_GCM,data:fo4GyOwhO8Zg6I6aE36Q8cBLbuTvQkmRtkhYaTL20a83ZNE9uLAv6YFKJpEG/46X8MiDF9rL8gX1C0TkQk6e9IQaHru2kCMHd7d6mIsqrjI90/ARuvM=,iv:lPVxDkq+LIvaL2BI2zza65rXeECkNzGO/UncgWLfDr8=,tag:ceIYYFObsqYSDVXxYN5GDw==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:QpJrhsbKEm4+JO62am7ltfHWG3m3c30IvVfwUkxysjbdHOmBVL+6L8pJTZBI0IL0ORglmJd2KQXyoVDuNXlECC87D7H66X8Ghuokd0fzn1gw4yB8Q+0=,iv:qQ46iaNgZ3RbF4fTqtQnxVnPBJNmaKuNyctJkYlB04s=,tag:u6c4erByjQCaUcnqs/bJlg==,type:str]
        stringData: ENC[AES256_GCM,data:ZxSMI7SSph3Hsi4SDPdq51yRKTfnN/6ki5TaAUVAYk0WyaWv0oTZF10JqotT9yZfcRBGBoeaOCAfEy3RGvrCSr/As+r+w3EaWXJqYpq6NyMZTV/aJh/mKkmgd8MBKHeuX3sMcDXVS6+HdMVfiJu3jPAEbDvtsnorVgQbJklNN7Df1ij07hgn3DfIIv67EJbrx12JwgpCPGVncVrle7GmIzuMHcQ8D2FhxFZ8iFA3Rg/Eq9H2ZKefZlsGsV4rPknOQ+lUqtMp2BOWb2P2xYgahmkpBgivyWer4QWZDTMRYktFOanYSg6ZvBwZALvyaZmdrUAyKPoL63QlaB5cDdErUJDNYKmGvnTI+Bd+Y+nHQ4Wu154FHQogbsNtqS583QhAbnR2mMwHiZxIGYAWa1/4IzDBhWUsqUHUFOaWc1lYXYe982wFLO2XuebGSRnbcQgI89X7A/k26hrZi5YMkFvH7FRsKuIGyrEFPWo/tlDyIZw0EBX8M9niP/A/8itzd0JpZmtkxjn2Y+lufh00dbir9y2xUnJGDSvomwqBC1tLYdFvQkBNC9szqi3pq6iPPRpUULQG0siT+ci8juqbbRkshRDU/QzlaF6Q5Urk/87MEYC5ZHfbfEP5QLxPfMXWK03irwA1m05M4PAkViWGNQ==,iv:gwIJ5s64GUj7O0u+O3hOseJOAMuUXDAJLHt6B7pCYmQ=,tag:8unChB2Gbs5SM7C06bCrNQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:17:25Z'
    enc: CiUA4OM7eFayhbCBdvATJ7UvjPn1qrC9O36XGErMFyihJAsyGNqYEkkAmy+eksJRCP684JfE/477MqMVyPM+kwLtcGAgdZikG4lfXD2BjGKOxeoGxEEYyz91zITj39a0G9dBpeYx9j2ck3Hi1VmxG64h
  lastmodified: '2026-07-29T19:17:25Z'
  mac: ENC[AES256_GCM,data:vBQa0ZTavitl7guuaYUfiYz1V3KMsPLve/VlLdWSflIcl73QUqE2qD9GSXOuFiNBd3cdYdY0QtGDLDTYK0IPGuqSIlIpWqQVsCQKF68lq0ABxEzMNp562d7VZ4iVEjs64WQzQwoLwin1887pizCtJ0ODyHoMmFv0FmBWWlpaaDM=,iv:J8mVbcVZ9t/ItMB2/oqeV/tFhYDMud9MRf6svZAHsg8=,tag:ALBSNnMJyVoMwT1nNbg9Tg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
