jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:qWf2OOhfozs2A2Cd313hYpVQJh4Xz3w7pK2R+/pDUB/lxzAaaHJNHuJmden06G5FLHsA,iv:M/ZQUOvuQM3F6QpMGG7ZvjJTDjze2Ovd2zyA8Q7qLaw=,tag:hUpzCSFFck5MPRnXJurSCA==,type:str]
        client_secret: ENC[AES256_GCM,data:yLCVyklWOMCrk/LGv9NLZhgHvGeZkYNljxD9Wdc0K30i7lOxNxoTOF7eiR5pViv3DOnXYhQLyTJ6kdt7gurZrh0Cg0m8DO9hedOBVHfzYbNVlSQysO8=,iv:/MZZQWeNJsU62uEIbfb/QmKB3Q5aS6TGC10aq7ARmIQ=,tag:Umab/A+UFoS619ASxkzG0Q==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-11T16:56:05Z'
    enc: CiUA4OM7eNAYtvTqx0N787o/B6ETwQn8hZSLTTL7wxmkZkLZVuHTEkkAsHDElwNFx+jsKX315U/TLKb3ZKb3YNm0MMR40MV2kkoubmItQRfpXrnnZKaBhSriqjFvk3WBol0aSBD1WD/JI48jGTEVAYL5
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-11T16:56:05Z'
  mac: ENC[AES256_GCM,data:xHsXmYJVBu9Z1Ujc9dTuAr6Wa1U5HdneT1NSLJRK6sRbFDN8nqpK9QkAsTWalPW4oqgvpij2M4m8k9d2sH0JIm9wqN3KVzqF8PPzELOHfMMFfV9Txki8bgg+lrgj3FHaWO/wWm2aP8+Qtt8IFfkjZTFLyuFn/8jJM3Pg3Ucts0I=,iv:BxwtnZpRNLS5qiCRvu8abJRzgAOe5dsQfEel8cUZW3Y=,tag:RoOVPJ4Q6D4bSUXcocC4PQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
