jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:8m68XcREIr5TQplOYLwVFTTnTjjxRPCC1QWr9QOTP7dqJqapA6G8ESCCYCQLi4BlF4Zbw4+LVMxb8z1CeCk8qTA6Tp1ZyzvY,iv:aapD5slBDWjPlk+/v8F1F2/EWVWKrlP06rkaYGr3RIM=,tag:/3MjJKOXWWVdaFis907mKg==,type:str]
                client_secret: ENC[AES256_GCM,data:crAYa7G/QRm+kXujM4y576svwPijXDzfK91qRjk81u/QXJE=,iv:Luxn+ngxpD/S2RfiD5vIdJsnH3+FFSYxtA7GKyG9F/U=,tag:qIT5v4mY6uZj1gbsJpjVbw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:NTrYSn/Zib25Ojq2hyM4qXtTSN9w0vMnq8I44vWRpilbfzFamZaVQaQrVIlifvC7xSUUpNKBscvSxKaupu00wg==,iv:0OBfe6CzKvJUaNhPSUy+cESVQ8QOeUpHn6QCdsKfGGs=,tag:P0uVBRh7gRwIhwvUCmUNTQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:18:11Z"
          enc: CiUA4OM7eObrrVtjqEQpSeYV+ivilZ/1YYb8xgTSYp/LXY9CrUQXEkkAsHDElz53dsURuvpTtmKR7X+waT6k58zuJwMk2qQK57u9K4H7KjKU4T1Hr4CZvHplFSnywkTAo0siUMW4dHBM7/kTiO0jD5dg
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:18:12Z"
    mac: ENC[AES256_GCM,data:FlpdqvmWEMyR1rL0s6hnmGp8CErjPaP8vzyTbqf0qmHXx9UMo25YwQJVybi57ZVByaF2N3qCVTUQ68SOkLV/VdzbLOiFh8lItHVFfMXY5861hW8J0IeQVZvx+A9krNKynoQu84Em8HDbBew/4GQvTfiSMThLOQdMqyb/DhPId8U=,iv:Ghf2E5dp+1EnFpmorjWtQaUJ7rcKxBRw2SfOpldQk9k=,tag:cQXnGMwjJ6W9U+HHOmWrvw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
