jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:7vyhwZxABBuSKfwSDSr/D/YqnP6H3Cz3C9hfGiNrjBOMuAP8FvqiS9LKIs+MYq2hgouMTOgqjti+WLf1Rinzsa5Cr7s/cbgl,iv:y8xnMnQhcphFTcFJn7Zljsc6+pBsOv8Ii1nM/CmeOg8=,tag:inx4Omo4NR2VDKyqIRA7bA==,type:str]
                client_secret: ENC[AES256_GCM,data:YCbAq8iMedjp0F7w8wog5kXyyr1zbyDanUofQ7GK9KfWwzA=,iv:ScsyEL+0Kl0M68pAohVuLXuW61W1fbqDTKJPI3pxJ1A=,tag:uKjMOGRJrIND+BCge1O97Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-07-01T23:41:35Z"
          enc: CiUA4OM7eJtRtUpwKknYVY6dEvzfajwRYiz2LIfsQQZZ8MOOH2/kEkkAmy+ekrbRm53qm+S22bI/x/xmcWj0G05reUF89ntlACZviJcmiST5abmFxN5Dn7MX0KdLOeoAJxExoYQsqktHfXvcPyrH1RQo
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-01T23:41:35Z"
    mac: ENC[AES256_GCM,data:9GDPziWzp/OYqlLb2oUTWoc6XZPKQIVNuKd+M4Oe1ysV81YcYs2ONMn4+WCN24n/y9mcn7MtRAUDuzPcRjH9fT6yS5mTRdOA5iKx50Q5ziG55jajG+wpNboEXDh9i02MIahCCbley/0SPcW8iVFxeRQoh21RF1YeeTFGgjg+grI=,iv:3YomWrmIDLL+TqWb6tk4lm0t9Mka2xEYmxGq6pcr8mA=,tag:qsbH8vYMIghhmfUEAD+01w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
