jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:7LAxkVWd6oKOBBFS0ct6BN2+RpUlGSVI9mecLYYNjPlYmUs59Va9lhlqHVlvw5UVdvOd,iv:jBEqsUCyeas390Yp4so9sjR+RUgYK6ZsqEW0yjOpIJ0=,tag:P2Py1xkfJXdnixKWP93scg==,type:str]
        client_secret: ENC[AES256_GCM,data:0ompBstsOH17Y1PgxmbyOacKjqC5IA17673NHW/72qINj4N8dETvmI865AGzBgoqMJwdwMySikULV4qklQUbe44af6A2PfAGywCUWHXejPtmkW3Dexk=,iv:nCDVtngfdMx+A+tJktC9C2h1JtIjnwHKa/U790xBioc=,tag:uSq+RetDaeODgogVb5yh8Q==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:15rT6FJdh4K4p0C+3wrdQMGyMIrVek4d1AkiVz4aeb8U0oArlvQV2FbqWv2BNBVkeYRbZijsgtzAzeFvfumb4Ebzhr2Tb3qqpysN5/YcgJ5KCw6kk3g=,iv:RBEvcaadSmjMpcrrPVcgE3oQIqphRBW/uoB5UaM+gO0=,tag:t7RoS5n/b6w0uyNn/dpvPw==,type:str]
        stringData: ENC[AES256_GCM,data:zzjtjIiSCWDR7FakfZxs0P0+4wdzGjvdv+3931EwQ+XUjYtaHofU4nxR8yv8xVGvdL1ejkcbnB/Ya+Y9eOJ4qOYRgu5VGd1uNQas5a83DqpJ+lamFzkIqjWc2WPrrvXiH/zQo/H3cllwGkXwle1vkO1jeHOZ1G+CTFdtQ6I38/eEtf25K5vnjL1cbzt1HxguFAboVdaN6NHPJc8+jxQuHsx3R3M5cY7bcdC8JirXmgXruHsTVlGU81ygAgvmu/fPF+mpTaz9TMzCZd9QTeAWPOrE0rIWGrm6xCvmzCbNgQc1TDEp4yMHb+CYCRYaxZjepqfENqSEOVoXG52Re13cC4KLvpOOfzKREaWxK7sLyVYgplRvi6ptQDytmWbBLgfqv0NUtFFbNVf0IZmugQt1Y072w4mDFpwPSNtpPdAsSWh1e6RxRFmhWZtRR4NTCT+1mm3JoAQqSxJZWgjxJeF1aGEqQOHbZCWelA2C5Hk55lenSYugrGumjO0RykO0Ub5s1ZWzTsWNJfKePW1Cn3Z9wXUA8WLZp+k6OkVTUNXv7MoUpx54O/315K/qZh4NyjakBj3CoxzKx3AANz+ckPt5uuhktqX6LNv7eTKrmyY18EJQosYBFb472OgPKZ5Ih4RHS0Sy+Wy6dGP+LQfu7g==,iv:XhcIrERLb3hb6zqGVNOmxRTK7bPCZ8yAA38JhxwU928=,tag:5KV1mUflFVJGqBxpGc1opw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:55Z'
    enc: CiUA4OM7eBdc+Xbn1chNg7ahJtBSVmzDwMi17D6edNzu7de0O101EkkAmy+ekjvTTACxgOWMm+rmYbZ90eIsWqIKo4JZtBVObw4M0/tEzvrKUpnEywB4MKPwWJQXg4y4iGITOUuomQI+KpvMzYWT9ZCw
  lastmodified: '2026-07-29T19:18:56Z'
  mac: ENC[AES256_GCM,data:XeMCcNJSOQG7bIDSFqXSEtnnKL0NL0AuSdyoOmko/XCJ1F/dNrpPw+Mtn9sveP6D6E2Ka4GUP77EEYwKAu6NTFJKw7kNvjqRmZ4egkEVzvyxs7beBF2VPeBYPDRrxJ5a4ToY6XxyBM29xnKaPID7TvsRh/hW9jacH0Liy9WoP6A=,iv:tBCq6LySwJINVsO7yxKvnSuGyuL0kCCxZD4WAiOD2Kk=,tag:vGKC6mUg36UWqb+JhX3jfg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
