jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:mZgmaqzEvZCL2r6czI6bx5SzdSk=,iv:j8Ibe26gvhhb1lQnhAWazu19bSIRzSVTGc+2t8tisxk=,tag:+zYBqfI/ap3CJ3gZLYY9uA==,type:str]
        client_secret: ENC[AES256_GCM,data:v9Xuqe8fl5jkH5It602QcZ88Wf3+FgtgiswndMyIApilc/AQIw/CgA==,iv:NDAI1TFgw88lNltpS4hORB2lq7lZEV0J8j2ISs8rMuQ=,tag:IH3FTJ9GmcsXHiyroUkCNQ==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:IPY7+TcnQgnFtFJaYnjEyQ1KMrWkHOIDNv2RbhAAN+HlyOv83rvOJis2QzuHlRYZpmmG1Y6LfSJffafi2ZW7lMDUr8RRbklBQdTLjjgCxqk2pfzZq1I=,iv:nu239QMTmGAH5KrpEYxkZNDH3MUAFFkEDXhJ03KMOXw=,tag:VzuMPUkiT6QALxtQgIGULA==,type:str]
        stringData: ENC[AES256_GCM,data:OenjVohAuh4vW9J9iQxYC3iomNwFovBip5F6s7tSmHA3SXK32bE5MPSVpx1XidRv1nsp3UCBpzc96wmRKLIKN4ii8g+x/bF6elKubLf/52LELkteqTq67v1CrWtrNGuPtN7RQeS2kLXF2icIEyDB7xVdFe3CdToFY9r9XR3PpObzQYda8COlQPXYF54gTi3HVv6TkgT2oGw6kt3Z/9aobMRu5AU+Fw/sPoPr10LltAigjl0Pz0zR0RyMBQNH7oIQJ7BQIQw7vKvIfSk6LvPGVlLLieqqldDv8kuHcubuOUZbcbXeKSUcqfMY6e7xnF9AA9nFUrl0cYLTOexwnFrXkKGWjqUeJuYSSlO9nwiu09/aOl7trXz7tTMZNTHqgrJkOYAXVlMubu2TiUY3SZlaZ9HIITmtWx4fE+ewsSVnl4jL+r6hiFQEWS0MwZudqiW/wee/Z0RyfFbP7qD+CecRjr42zMirbuvc5Iti+NQl3US5sySPIPLj3EjYerPKd3oy/qbfes0eloxviuaLS6nvjX1tghSIAgjcJltJcmcsEMxuPSlXRNcfSQhWEykjCj0wxB6PR934symSSpMh0ejFj4ns6evZQfjHnKk03u8qdHRuFoAB8An41cSVe8aRlOK5osbVSUJshYWSSXyn3g==,iv:Al9WSeszpDb6A6i6i7dDo3+W5wf4itXK2Fv6sRun1q0=,tag:JRAhKaRHOohht83fzMxaKg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:00Z'
    enc: CiUA4OM7eHXc4sg7yHIKaqMJreGi9xqj9P9/wi4qvLJz+yRjcN2PEkkAmy+ekte9SdsNeavvSFmf4wsFfgNjtgisoiFlCMxz/uhcyJ4el3P4ML+2njQDjnXiBFloOboAh8NJJO9rOQIKcUSKCS6qJH+T
  lastmodified: '2026-07-29T19:18:01Z'
  mac: ENC[AES256_GCM,data:Cm5hx3VdN1gdnRafdEutxqNCu3+z1uibnD0BJAZxKjGEWFOOeFniHLKsIluVkLl3GdtbqPmo2KiMCxW8+4EnBHI5rvg6eOFiOyCUA46FEVLCpr08NfJQ7+S5HkixkgveaNr7Ius9sXzLSoztes4Xmu/h4dTHVOf7VEYRYUQvNHw=,iv:AnBEeVDBl4EuR309YJ0+gZZOwK92FDXLn++x83NdEFE=,tag:CWXmhVDIdIrvsyNxla2Nbw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
