jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:gouQ9V42Yq0H8bLAq98lNRqLvtTzpEahHVoZPcv2k/kOw5H1dujBcLnlGQFq5to5m1K/,iv:E07BPnghdwXvHqZ8j2PdxZ3gOWl4bCODqIt5/mn7RfE=,tag:Dt3kCrWskq6KvszqhB6UWw==,type:str]
        client_secret: ENC[AES256_GCM,data:KQmwTTY+8w4dE6hXabs6YwyHhhD0rLLGnv8ecVAO7yyh/EURHLVdboVbyKZRZlwx1MBS795vc45sVLaF4hEOVgsCwnpfQctB3LbNja65rgtVbmCNJbc=,iv:upHKqOHqp8qP94CPPg8n5AtRuggeuwpuwGKMR5V7mI4=,tag:GNPx+AtpkeSFYmBXpNVsIg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:4AmMTK2+W/72xahk8lpJHYKgYrt0x23Gp/M6Ycs27ica3zUQ4PPjzvno5LU88N51gLLudIjwrlDXH5N7iY5zSW2TU9aGK5lBBt6ytE2qGOey73K3dCA=,iv:yYfkdi/QPiNHC/zx6kJBFopROZz5FvLt+cx+5sRGxZc=,tag:FBrjI3lEw4tyh5r15T44LQ==,type:str]
        stringData: ENC[AES256_GCM,data:7gIRWsaqf/Hsjxo/nR2U4hlfuKpReKeTycprvQpWwJHB2zjoxbULHpOyWJdJeltJHKtapSC3aCYzENWoq+q6ixeiIYF2gtSODM89vc64CXkEngL1GLZ/+bYt6M6KLWwd3Uhxszr6ov5E/tax4jn0tCxYzgBNct8NfhlWEJvlFt1NanWv5VzQOAdcMUrxk+DOFVI4uMgCJ/m4MbFM4o9RNBx9zq6ihuj6rg5OXqUN2qnL94Xb6uOY/KGdaVWsEa95F82jjSHNl2bOAY17FguecX+HXywOCFbIHMlMaIN08eKkK1l0DH2bqxEUBXtFssDzgdnJzcGOUEc7QFiJPkg04JbIitXg6L2Y3no/TbWv+Xxnig5CLkCMCxiyCGwuPObzWpGbncq9ihA91KfsOxLaNJeDpnhEckUdMuxv6SjlS/zRrMeV7lqlqg+1HqxHlgY780C/RmPwa+YSIUiMp0w9sPGAkmFTp+xVqMPgakyWEAgAl1GlAgTvJqxkoaqsE3Qo++Y+nLf+ABO/ntZxVzOXCPBj9bBrSiCsbLn8Thf5ZcG6MVNxLiw7QD1TPxLULQVeHSYXKu2e9hqYEib/Lr0MtfvRutslOp9QfvQWjoNw63mLQ2PyVOmnYLVNBUG0QmvY8+1ewBaQXBYUehF2/w==,iv:FQYtQrklC6Ivsdvpdqn+WXzwapeI9GIPXdkxlyeFtGY=,tag:TG2tQxPacY9+tEPVag6iJg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:17:40Z'
    enc: CiUA4OM7eGdyBrq50T+copHeQWfZOpaBotQ1rRFtpnSO+/5/hrrcEkkAmy+ekssgfEwVbn9Vj9Al2/H3BApAeQHp3f/LPXR8/wdPvdq9OBhMrelvuOsG4+auAsAfLajj+HciBGb0LjgmvuMivVaOZA+y
  lastmodified: '2026-07-29T19:17:41Z'
  mac: ENC[AES256_GCM,data:YkM+kuPb2bXAW04RB1nAJowyvAdVqKzjTVL14vE5fJbHxPmEJiOlLA2t4D56362M/voXm8VF7R6Ee1wfXoqxMlw6o+FVhbk5pNesxdnQMv1JVTBtyO90azNIakodP1zvFhDyIb5qL/0ZJ+89257rxSblDYYwqU+2XNn13ptIup0=,iv:RQGBSeJAC4VY26I3yOYTI0/eRN4aiM4adcVKK92fBdU=,tag:QoYAS2JpyKr3eWplsBmhPw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
