jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:w03J/GJJP/6kN5/UfpD0QlpH+LnoD6WVPUrOQMyoVIJf3YMuDpdOCh6wasOYrEkiPuT1,iv:/LMdCjz8K4c/Tf2f20ENesSp8P0Jv9eFTja2a5IlmtE=,tag:53BC2s0KHxLxI0leBQnjnQ==,type:str]
        client_secret: ENC[AES256_GCM,data:OqyJcIr4tHwX/AmJZMr1a2OgBFvaDDmIf4bDC8kTzA2RPD5m4kfH3k6ACiNuLD7hXnQluscQfoOHdeIkxtlNqRlsJCAchNmLSdXsLW37fvXcDRbq7S0=,iv:MaLxxXGPHjcG/W+eWOBB6tR0rKygqf7fWTkIF18I3/o=,tag:6pB/HatozJcEfuZNxId9Bw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:48:00Z'
    enc: CiUA4OM7eNfyCcsfoeQfcA85SAdKncd6bnJKvJh9AJJhxMNfrul0EkcAsHDEl3g4noFahkF7ABFHjoY3BY5DZSNx8nhB93Pwero7p2DN/yfbIbaaymPYxY4hVD3yJWVNZ9LK266rKJ+t3CmWd1cxLg==
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:48:01Z'
  mac: ENC[AES256_GCM,data:Xc4041c3Tm/c/w+RO9z+8elbUuOwCpnl2KY8Q4o9eBiLqi/kNBnGakKuoYGvl3Ypf5AoTAR9H7sjHSgunuqXBklxVe5kPHLsOyj1+jFn61VI1c5Q5jvua6J6Z72jpCV4sVk3j5JbVpafvRLwukNb4pBgAZU6Y2iN+gsImRxshMo=,iv:NT45/+BS06h+s7KXOaP6LJJIVQ5u7T1J7GsPIuauGUs=,tag:a0rW4hV39ijbHaSmQNy/MA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
