jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:uVy7oBu0r7122lUKt9VeiARYfqxQduU18PnIfTVfOhnUw5MlY6FA8nK2EsbqUXZlcRLm,iv:3svjZJn4HrQcxWMXIqeCFtHKyt3jRCmkpKnFiK0nMzY=,tag:Doil/pZRWzGFcH01DBFg9g==,type:str]
        client_secret: ENC[AES256_GCM,data:B3B/KXbOkxKGau/34nZiU6tPUS5oCU6nmQxiR7MLPy+xJAY0nBMDHmTe5B6sBbvZeV344gVgEruAF8JaRfebXfWAB0w4SkOTYLKfBa7OZSvOo+jG/3M=,iv:OBv3tByVwgkyYscAg40pm/e3xJUkXKt9z4ah15EbUE8=,tag:KFF4Z4VxIHyd+tsuQKxg3Q==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:Mdfc4ZSAjCETF9E6zqM3da0XARaWU39iDIgbqaITNqrYTKJbnQ8jE+6SE3YTND+iu+O/AsqbDiV/cAn1FGQcJ9tPIXmjL4g4c3j2yd847qoxDzfTvZY=,iv:v2OxwDsgaSs4vtqQ6j1VdGR4fVo4yH5PfRP4Z/rE0i4=,tag:t6BBZC7HJm1eSMFL6kDr6g==,type:str]
        stringData: ENC[AES256_GCM,data:7tFnhI0WpdjJaAGSZ/dfN/ut1WrnFThRN843e3DcSlAD/8cXZKRWIbnDWhbvYTmRJMzNPQlgUkDg8msnoeLNiNCzQCFMqjxUIwaCj8Qs4Gup39cwyDd/0AnErKqKHenRsqrX7FcQvYl+uWSF78KSFIU1KppBdmUx6IGyLRqazm60w567IxbsCCnb8iJpGkH/lklAHN521loMbrcf/xNbCTFndZyHGpQinnYAbRMf6D6IGjeGp+Z5QCFSozCyix3Hd1ZgaxGrybjckLgbd651zDZrWtQPqiIslSp8fu6M+mIgaUbXyl6pQ86NUefDP/4w2FW7d02+DneWL4uS6x7hMvwkf3cziswwrY73RjmYBocga9a9cUTM3STp0IT528THPwMho4W0ULjGMSAi06evNAyfc2qZMMCLO+VxuuRxR5FG2bYb2bIoMjKNdd9VU4NBj4x6lQJ4mZIIg8WtKcz752NE1nhyKE0UnxunYp3d1QxLPEtIXq/z43UobeWe5gLzt/AT/r/U4d2+U3EnqxL2AZumeUtQOWalkhzQLzfzkW+slBSdKNd7b9pOTf09CgNixtFKwDxK8PT1rBDlDSUQ/vGYvZ85jIJNpBaeZKHVDAnDGi39RaxaUdWNohO5man0YMxN+6arB80km85UcA==,iv:+m7yfrPiTo6z0rg/Vk9LBX1Qxq7AEJ/BTUQ+8B2dYKw=,tag:g8r3qJGhRW4ChnFYOW+NqA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:05Z'
    enc: CiUA4OM7ePIKcwUjIcNy7ayj1w3wfKjQMoD9UypZGWYqVVKPActLEkkAmy+eko6vPVBQFl9IDhH4VkNOGVzFcgmt2cOAfkSbQYemWydcFEwdb/GKM3M/ukmdDxzvMQ9bBUTiqlQBrA68IkgmLTBga8DU
  lastmodified: '2026-07-29T19:18:05Z'
  mac: ENC[AES256_GCM,data:PXKpjQH9IIQzQR3pALQF5bczEEpcuM4gXzWyGPUHyxgZSALhEJkdFaA8S5VLhRHxbrFuE66JkQTK4VP12MSqJKjDeZ0PxJY/vg9QY1CGpEq3krMtI09dYh6AXLo8Q4hG0ef3uWlL2xNUrFlOGaTrBMdoYX4DqPoElGk+Ine8IWI=,iv:gt1EFoa9xad7G/9e6EXyHKvNQT9Q5qnFvPCWY+NpogU=,tag:6QMHESmmPhs2IIxdAzBq8w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
