jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:KDeAh7hBfoyXVVmNNPvjkdCWhEQ=,iv:Usz9mzWt8zjZK8ROZUIw4vH5zqAXdK7ISZch9zZSHJ8=,tag:wlUQoSfDGNiiqyE4cZBw9g==,type:str]
        client_secret: ENC[AES256_GCM,data:ZaIrAk7YJ5dy5Sxtb1uS8xMWet33zz+lXYYLLEiJcLDsUgkikoi+WQ==,iv:V3gShP+3Sd/XBye+s7iWr4p8TXlpmEYYYwMSuYGd/ws=,tag:++KFqDQxrUrG2U3vsyVF/A==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:qkWycC0N8j8boPNlrPfqJriTm7Y5Pyzsh48On4Gi0OW9qWM6HOs5Vqb9X2mevWv3En6tmrVyMHiGGeHwQm+aXu/VrNF1z5PdDm+JI6IiOOHgi7bwHKU=,iv:Nq8ZjWZFJCgaSogXZIK8JuEWvCxKFlwHmiuQ9zTKebc=,tag:Hh2DC2P1pXZKgnvUlMqbdQ==,type:str]
        stringData: ENC[AES256_GCM,data:N7eNvm2tfjfphXuijPpKN9UzP5uUPNwo+FDlERSL+QDQpEiM06yf1UDSlNggZWA3gIN4Z0uuOtTZ6M95SQDu+xae+b29yE6Qm7tXiVlVSD4YM93rTVOmSdR8uuJPr78gvMMKTMxAhgFpjYQlaAP7jPq5vN9aDGALYR0B7/SQqKhy0pLt74Udznj33htsqpf61e/a7zZP9iVINJQlCV571snU3Eb1cSE31G4XQnPkD9MEwa+PKTKU4KL8Tk1idAdrgWhegO7SVOE3g08Cm60k84XlB9Aadk3lZx+VIlbUGGsx5hPxmycPid1941LHRtcwUnj8y7gxWoXwp0Pmu9MsxTejaXLRNDqxuivdj91yopKpomm87Q8hXdg6Ez+pVhB2w714rg9WAFXDFxHVJ0a3qSZLoL1lpoM9B0a+lOvi3kxaPjRgxpbp9iwsx7cmj12fN7r5n0qK70/VtdpKo5rIbjGZQgHBizEIMt41ipUp05Kkk43RODXY7rA7N6mwQ+U+JoM7RidgKe/vaCUn5q1uiKDzBqEdD0n38IsFls1nW/CZkjsN6m0D0c3con0bU+dsN1ovgMM8m2whZn4p5obFwAyR+QKk1BpQkJNRLl5EutSflo+qireKKlG2E1GXumDMiJRakYFYrBLQGp/KRQ==,iv:LfGBlmnKTJLxXjL93oNY40UeDwtG8eFUn46G05MoZbc=,tag:+7HS4YPHUxEV5HfS9ecBNA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:20:19Z'
    enc: CiUA4OM7eFFF1MEzbBSlyUzlrpqqF57bTJppavIzAKBrHudYdKMkEkkAmy+ekjZsBbJEWlH1/U10Uue7lAUj+jLyuN6P+miLRm4tPcwGh9DtqbDhQQY5+Gl9hm6LK9RtVvFZdVfFxtCt3G8Ebka2v3Gx
  lastmodified: '2026-07-29T19:20:19Z'
  mac: ENC[AES256_GCM,data:j1jnrSK+GNAFOm353BPQ+qA0bMOC3YFS8EMj4OHzpWCSkRH59+csxbl0oAPRIBPQAnDf19gvB9qnS+HtdhS+icY603eX6qWPj+5SdBn7rAxfAxTrgFXxnz+0wbK1GQr5VVtE6WC9FMT/oPgB7H/G5RH2vGTM0zJ9p3H8xjoaHmY=,iv:oK72s8jpS3zX5bTcwnw9aJdAgHRGeiUpr3M9BE/pYUs=,tag:kvUjx4nlNRLDj1Y45g+hrA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
