jupyterhub:
  hub:
    config:
      GoogleOAuthenticator:
        client_id: ENC[AES256_GCM,data:eG9tz4EwvoMHzndo6JaRxUNCeVeXWPDhfwlG3y9H6eK9yDczSw9ywVl8Eh7v2roDgktBxLwiFnEKeK/ycl5kJaLRNPKcZv8P,iv:7ACWQD2v3Sq+3YcVin7JUudgJriZCJs3k4aizqjDoWo=,tag:X9TWxqL85oMe0B0C4e3ZWA==,type:str]
        client_secret: ENC[AES256_GCM,data:zsaSghkkQ+o0F2U0HBudLdJEEJhGITJ4Rqi87nko5bQzlz8=,iv:+tcKPWvJCXrvtz0oszg2WoRnVa1jQdVLTPc80Digibg=,tag:PgyWHr0xEohsotCp9G3c2w==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T22:18:27Z'
    enc: CiUA4OM7eAJb9OwnFnnMxrovIEEtD95LZJw0pFrxJwxisBSJyRcvEkkAmy+ekqBUxGR1wxyX/mqmTJfuokumj2hhw9ThOs+bBVrSWD8GW3D/ZNh9LJ27Ca5eHfDQAjYHc/o1AOisRncDf6T4g6iLEDqz
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-07-29T22:18:27Z'
  mac: ENC[AES256_GCM,data:Khk37VOhB5jJnvGNJWL8qdC8EzvNxfGSj1IaDFVD1q86NutVsHgivoB2nnkXa75D8zfobbt0SKWbBvA4kXW8Tf2hBL4cOQuMKmlU4Qvv68kzBIpMBLanfXbXunFWBkiUxqXT5fAVEpgg2mieahtg8RROPH62F2ktBYIZq9etQZY=,iv:LE+N+CObTZYIFTdgZkQdbksxXitCN+ueZ3COmwNW7jw=,tag:dz/oblPPsG1bmEjskcJdjg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
