jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:CFRqEnCKHoBj+wEEooOlUftjeoH9oHO9yl5JnsaCEz2gcWptbhJfcd4vnCnT6T6xhhPU,iv:z7wqdwHLhjk3NnpCNUbwEjwtgEo8bj2MHhpgqHT0qwo=,tag:8F2lj7vAsTiGengMvA83xQ==,type:str]
                client_secret: ENC[AES256_GCM,data:uZa45XAgLdnYwOrwz/XTKdnhq05nEuiPBxSQCezGVufMpHnDV7fv1FemFgUJ5zkZ3/cU+jcQxrhED4al4PLsq5kfTRibgZfnxWEVCiOJXgOwKAAKkZM=,iv:6JK5JIZqjp07fCJhLbqsUllPBdc+evpuPzNrjcMh5xY=,tag:HhsfOBhz54IvmvJf8NBpdA==,type:str]
            SharedPasswordAuthenticator:
                user_password: ENC[AES256_GCM,data:9lJrfmcsHsbhfDloxDfa,iv:heApW1qYq8VPOHz4mUD+5Rb5JReszeWf3TDkQQexhqM=,tag:sn9hEGCP26q39A8diiO4kw==,type:str]
                admin_password: ENC[AES256_GCM,data:QXw34Z5Lxp/JG7M0yT0rnBO3tAlrAqn8QQ5qoxYdksLt9RYwqsi+mqKTiiHce+l4,iv:OxUaMTXupHqBXe7gmgOXub+VV+huAWrnk3Mxj7rQ6Uk=,tag:rB1Ue+hkbpmV0B+S1L400A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-06-26T19:31:41Z"
          enc: CiUA4OM7eE+4PZaNWiOjo+YMp+gznqwoJvVZzF4F92s38aw4gOfrEkkAmy+ekqTQZrAE//DkHJDtDEAgRZSuDjtqvY7YuXWqiwFTs/zTBPTUZEL9RwZSr6OUU3w+vYNm1LZMA3+dBId0QuI0j2KqajjF
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-26T19:31:41Z"
    mac: ENC[AES256_GCM,data:ntLqUWT5T9qJlcHusEl+JnNBbZSUlnnzH1VUP7dRTuX0Ka9q4w1EisLIzjLm+0bpMCU1ojn2xQ4eHhrM81OLNHf6Uyoqp6hLena+AJZDZR9ATEevZF/Wl1bnwxl9LSy6UBqjeebsLJbMQ5D6g7mPLqjp2xjQCE7GTKwLUNUIfNc=,iv:IrT5yS1UPXMvhKnFYxsMSjV/XDqRFbRwIoEglPcDRqI=,tag:IpVq6SLk1q0cy2KmQKFTNw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
