jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:yd/WmF5OaMfcKL6SEr2J24U8H1aaq7rUguncgFEExHQQKcbXETXdU4njzCtKau4eMQo=,iv:z7SDlCp1SKIAWTBKE2u75eMcdxTXiJ5Fc1JKhS/2J3o=,tag:avJ5IxV2xPkJMNYfhI6KAw==,type:str]
        client_secret: ENC[AES256_GCM,data:XJIdhPOv7jwkHKBeHgLgepQ2nu6DaOlEXzcy5yecjii6aGdAfnd3V3LPj+kDOHkOFlHeAukCPI99M3sprBwWfc6b72oOGUSo/FakRa2Bgt2b5Vhb1yo=,iv:OVZqSJUCxvtFhU+B/qrmRIGXTgLVLLqRr4NXkgjjzd4=,tag:8srUsusvjRfO/JUra6v0hQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-11T16:56:00Z'
    enc: CiUA4OM7eIE2KCl3U1/i4R67xbekXyrqJlifgnqBxyrtOPt2C2E/EkkAsHDEl8BXnU83sjslSW4QdkHayffu17M0nbSSTCDNttfm25Vy4HS5nKXE68zWp2q/TijlC233cxQ3AjWQD0ZKnpcAMIdKCIGX
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-11T16:56:01Z'
  mac: ENC[AES256_GCM,data:kjuhAT5zMibtPQWlrm1lcB/sCiTo9xKB9S3PJveurJm73qZwGBY5VdB/mNzZziFvkZkxuw1NAnOJaSHrJG3QZ+h9W+lE4NlqcCc9SwdoG1Tiv1toHUqVv5gt/VPlXC9RKn1nmn1MSCb5Mfn4fBLGGxPzKw3Zse//ooSIJDUmn2Q=,iv:0Ny5Dx+FEV4am11KYZYmC8rcabGDi38m8r5d57CBq+M=,tag:frUtZ+J5mo0RGUrP4aVmPw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
