jupyterhub:
  hub:
    config:
      GoogleOAuthenticator:
        client_id: ENC[AES256_GCM,data:cX9kTXz4mGJTyH5vAvDVJmiMdjxDr8lHATC5r2kLm6qPuZktZ8Stp0SDq0tFrRstPjBrpIf6yrzBf9hYUJ41542Bf5Jpx57p,iv:fNFP2qL0+AHonRpiM9akIHcV3CI73sGsUBIhpzJytNs=,tag:zGZqNQlWKdDfjhhrgzHxiQ==,type:str]
        client_secret: ENC[AES256_GCM,data:cGVxKA0nwW6Yc0jc1tFilZb7mfSFv1v/r1NchJIOxvEfi0o=,iv:RGrZUfGqyt+xm2QkSWOZ7NiDwNZNYbh2dqT3Wi9vHYo=,tag:fSIPOxFXNrFXo86WNpcPOw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-01T23:41:33Z'
    enc: CiUA4OM7eJvPpsDLetaTOqH5p6hxbCA0upG+T7giJZHsYc/I3k/tEkkAmy+ekgVU36v7rH1jW+JRMFwETMeNbj6hEJ/SnKmE3YeDDcseTCSlVlcsP+sNUYLqTOwvvLoT9iZvFXr8cDq/PPNN1yLVLMM3
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-07-01T23:41:34Z'
  mac: ENC[AES256_GCM,data:j6lCdzNar1McJrJHcQJOMXI4ebRMyx53sqozl3h4pBLppZ+XOIGcep4WuIYQbI01yeo5k9AkczU2KXyi3vGh394+jX9W2PjsfRGlmu8/ELrZRSNDuopYAVVVPU7LCNygETCpwIo8wglcrE50OS4nhkmTBnmf9jWELKIMe5U0Q4s=,iv:smFLZ7FthVykfns+5TnDEAxoF+CUAPOkKgToTT7QBDE=,tag:gU1R8AW+ypnv4lTUk2THnw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
