jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:/4FzXPOGVspA+TU1NXRm9oaemFo2NCUHzI++nq5hEcuEeKCC2pzRMDc1i+2BNO0YOeqA,iv:Y/oxuGz5ll9XD3P75bI+QY3xzH/64SpJEnuj4EqDkWc=,tag:ucW7KeeSoQFlwSGYZ01/qg==,type:str]
        client_secret: ENC[AES256_GCM,data:gx41YbvPCmD4DekjtVLfyBE0Ce/ZjYyDifjJy4p78frzxk7WCXXPRNzFG0KbKnaTi5U5UDwLGC2pqCi933r/9HHE/UB89OayfyEcACGYTX0U4lq6McE=,iv:XI6YYOhRPmA9KxVolws5Pe0L171YgK97POsyiEPXoIw=,tag:NbcZ+/l1O7lBR0jPuRdCiA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:28Z'
    enc: CiUA4OM7ePQYc8FpRpKBioXDAuI9XMfVKakhwEcu2eIFkFD4QIChEkkAsHDEl87chJ/aLMsJ2vOTDiC6HWw8XLSoKDaxx3qASMjbS7CSU1fT8iuESt37tJUgMbfwDPvx4O2KkKHXJY4h0TdNJOVwsKYx
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:29Z'
  mac: ENC[AES256_GCM,data:73AcWbwcQZw2RtaJvtk0yQ0fPcYI1Se/lSW8I8XPDTrsiHAw/yLnfAoL5+u5mofRC0bVkB4UcvUVW3A0obAKo8BioW45fS1MCOwvx2Jd5RfbtkHI28YR6UeoCDEeMuGhouUT1i+5A5PSaXJSM+Q/+XheLZbwKxeWTSDJwok+iUE=,iv:F+8SzkgRZ4DPLr8VVCW19XznoIUZYVas4IJVIN6lJfk=,tag:13HDXP10MxeXUzqn8VioPw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
