jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:UxiuJhRDZk6Jzpaaz9Y5zLDOFt8u+nzjsM5HSpoJu/fhoZGfac1SEeYiGLCYqZE5jhOc,iv:lvvhd47aD9xK3KxO/eN+lQwS7i28tBx9MtsVsGTWtSI=,tag:BNjCQ/QOtu9MPJj9Hn9wRA==,type:str]
                client_secret: ENC[AES256_GCM,data:DKhj4tc5QJLfh8OJPLv8f/Urx5D03cLqHPqSQyoNYWvEvC2IxYGw7R9m2gO7BPhFkGYlbRza0HeMLeXbJaINr9+JuXemveoBAEA+1GnnNa5MDN/xbpo=,iv:LDKrGnlebCRhArH44KegWFDsl5BPs0REITQPWlFFbBw=,tag:Q9kqZHobisU0AG1ku8plXg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:25:01Z"
          enc: CiUA4OM7eG62PGtysOJrlfOzI5n41I7l1DAvxqwKn+Xt5lLZFfpBEkkAsHDEl6T4otIn9dEKzV4myhtdxGDHTZMZuodTohjYT9Xda1iAxJEv0FKu5oj48jUo7wZf7+JyR0DkJP/8jb40rfOcSxjuSWSM
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:25:01Z"
    mac: ENC[AES256_GCM,data:StAvFJ06IOHPD4IsOSQSQasETyt8e96Mw0qer/wp5CY9ryW5u3MZK2eGC+QolRJhOcfxHGR5y/gF2RlQrddhfWSvr/KpJSLi6VpdwW+pd/WbTGtWLiGNhNQkOu4s8ES9tSilxAn/9wviqb0pEADthmfF2PbEBIZCHo5EIQFQoJQ=,iv:UAWK3TczO76ZKgx+/JUpIL05su3V5HK+9dZiFiIv33I=,tag:JElyD2P6OczLbqN9mwg3JA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
