jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:cNOoH6Dmhp2UJ6AGWVunGW7EsAhfkm/ER3JHjVPn4b4VnVR3c0fX4hES1Q6ojNY1/GtC,iv:hXjb/jPPzYbcd5g6weVHz+XG+hKdrzZKAQs+5nQoOdw=,tag:c6n3dTAEyqUyvc6x1MGEsQ==,type:str]
        client_secret: ENC[AES256_GCM,data:2JVDqrSgZGtVBzf8de5A3rKCEGAa/NcqReiM0Dd6I8Sv2FHCvY51yPzcomPjHb0sR4aWo2iFGalUYcAi3eyGHQaS2YhumupB+SQ2lQdsCP1f4dtT7+I=,iv:Qk+6+TGPMYQJbx6w6RswCzMMCx2a0wyAJ9fXoGsmch0=,tag:P75Umo0ZlwGLuWDO3F1bgA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-09-16T01:29:33Z'
    enc: CiUA4OM7eMxQ+54AhT8nCMM0W/szG2PY3U9W3baWyPfZh9OvHzwiEkkAsHDEl7oWwuckcpfAhNkBsjjuUhAr9JM8khnUvit9d6LY3d97a5xnRgiCHJem73ZEb6+raPEP9owV6bqK2aj/MD86yABSJx46
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-09-16T01:29:34Z'
  mac: ENC[AES256_GCM,data:LKZUES5khBscDOMWeok8/x/a8Jnb1KF3Dt49l6SQio4ZJdnrzGBaiz8EzLKGCVk0ose3KhCe6GaXgcGB/8TUiMsrimRlHTPfBiIO8jRYWiZDz97WHoJ+D0gzIeRMBU9PL49JPYe+jCdmuK/1e289vKn7Jr+Yrwd5QCyIhogAOOc=,iv:99hGeIWD7gjdkUtQ5NyKmHZF4556P2tKPqqMlUc62EI=,tag:Ali3aQqwm5aYNXqtS79tgA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
