jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:NocTVaX/S6vtLwAmIHvYmOzPdwqjGaIC/ZZ4uIAaT2P9odoxiuTJyF7Ap89KBaJUIW35,iv:pl7IvSrEd2Z14wjM8r0wpgU0W9WmiafZq+N34+4WJ3c=,tag:7EndZmzMql+hg5BBRB3nSw==,type:str]
        client_secret: ENC[AES256_GCM,data:060ZTXrwin6Y8VvCHyp44m894AF0NdqQ+3WxTtDl78tzMC+JNkhsraVPGJq2UeXC0mdxVFt/cTKE3ShoU/13jN3KaX2eK3CSRts6G9S/+CYXpcM3fxI=,iv:g4jok4SsCnJdD3mYJbrFCvJCgh20V9qkQ2paGlUleds=,tag:R3gcz/bLtrzaoXqgNFQCKQ==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:P640JXSvHWx2epX3Cj99dvgUnEP/W6IsRqVtKX/olTLPM3h5oASSdkuEcZpZYYkg5IOC0MeLiDTquf5uw+gnrg==,iv:8edGurdBvfh//uzKbQEkwFBd/L+RaKIBZuKa4zSmivM=,tag:AwIUavgmw4JBL9+GYJxEOw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:17:12Z'
    enc: CiUA4OM7eH5vm7a44Gumii35UPdHqhrBg9HbZqP5+9FRM4jkJlECEkkAsHDEl4wrr5/9WVoYzpsABhYOOlt8EkJ0DYtfKLqtt7UkHnn8sAyIj3XCRAH7UgwAOzXCwx+gZRxiE9FDW3HVUDRJOIySaDSJ
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:17:13Z'
  mac: ENC[AES256_GCM,data:Sew5kwPsfstZ2oOfd5opiEKxwgmHmHlpeM8vmzHERQ6+2sNOGTcpilHNnmB09b+xzBtI8YlraeraD4/eGqR7x87+5iPbNxLZ+Y+oUGNEI5IG9+3a/C1IP4bULMqEFMdF7bGJI0YQgVX2MoPkZoe64o13ow23HW8+AZnn05Ux0/Y=,iv:1u4xh6GeQXA/myHt1M9oD9B0suy/ZBFcs8VheWqGk1I=,tag:lDLpc5aRu7Byk+iAyUzRbg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
