jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:3urN0XxlCvWkzujg84qSjHkaDJyS6xnBc6V4Ufmf9MEQLCWkXL2u1/8uaJrDKRwI19Kb,iv:sP62Ojxw7pz9ooZMg1MVqJtCoAStScDvXDtHAVI64Hg=,tag:d0h2cicrcjY2m6OgCRyP/g==,type:str]
                client_secret: ENC[AES256_GCM,data:mkb9mqncDRHfHWTHJXlHfraXa3qx2o3zybBwN9lglE5vck3/NHr2QQwTKlT3bHdmOIPth9gma2+cOrwAeUSH7M3c1eCE6Qq3bViLqbV4Xkolj0OHNo4=,iv:WI1XU8Vq+86tRtVHI02bVkZ+oK1SH1jt0RwHQPozLhI=,tag:yv8PA8i1xh3l6z5gLZJ7qw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:48:02Z"
          enc: CiUA4OM7eFAcLSCJ+gOWBoOHhcxIf2VILL+EdjR23PEcOaQLnchzEkkAsHDEl9STAmKCtjSBz21TcksthgaUaB8iLo3KsnaFs7QZtxqk1CK2qkC62rlpLPyVgRUMQ0ITYWonOTZgAdFT1C6G9yexl8Yq
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:48:03Z"
    mac: ENC[AES256_GCM,data:tjFCRYi35bMK91xAnEiov4rtDHcG+KEwBPE/IlWOONP5bThFmsBhLOexF3oscgvjEGvEvjFpI/N3QIvXItY3XtnHLl2CQd3bClLZvkn3kGLHELKnQvkRFUldO0VJqLpmAEPGlb6sakA4W5XVXkxmCIiyh9fj8MPrTk741K1ERNQ=,iv:4G9BAJr8a34HHvMI+f+DWymnvuODPUQVs6UGSOX+y10=,tag:YYpSuPRA9Hh1IUvebRZgdg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
