jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:nRSveag/FoZSCm0oUM4dZEFYzcpjOgMPC5j13Ya+SdKOdtiFgKAoGXCojrrnTIN/mhg8,iv:44JktPPSP3pnRLZBl78T89N2fd/ZIsOZd5SACQAaXYk=,tag:hb1MNUCv6kVVlocVlkIMhA==,type:str]
                client_secret: ENC[AES256_GCM,data:56ct1WM+kik1ye6qjwMomZinNkd+vBVoNLh+p0pvl16d5cFzN+q3Ag70+PTh6KZp4Qsc++aiuMurozDjucF83bb/9Z78cX3YeCGxTkSUQWX7v3JLnp8=,iv:J6PQCr+mp2XmlaQ1L1fbdvWUuPoeIabFQdRzAaqLj3M=,tag:f6LKgz+PRcz0Sb9X9S3ePw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:32Z"
          enc: CiUA4OM7eFejaEU9EFOiABhtTvWi3lQ8fXb8gBd1NMVDRr1nBFzHEkkAsHDEl7TZvqGfqQJy38H1ZcYOyTVv6mB7GdDLtfEdiKxLYF6dDEgC0ylSG61EeIH4yjWfJAR3H4kjT4kFBPR3xYn6yrwuYFVE
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:33Z"
    mac: ENC[AES256_GCM,data:rNDATIle7qjYHVBN60YEaHjJxvlEVCuQqYs13MDYT3SJNx6ZbaLBGy+DEy9mhM9Gl6QXj3Uvfz8gL1d+LLJpenpYRvqUD3aPlSwWG6zPrIwCVpBz/1DdESebS/mHrXTFH3BO+xKGPJ+0+AmBnewMv03Xc5l582Bs2wm8i8/XfNg=,iv:H0ycaC7jMs+NiPH4E880wNR8BpECnsOGlWGzz8QH3zw=,tag:KyTNJOHjL9VirXI7DvnwEQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
