jupyterhub:
  hub:
    config:
      GoogleOAuthenticator:
        client_id: ENC[AES256_GCM,data:Zbsv+7LnNDE6eJO+87Sn1d5S7P71XiRy2FXll5AUScAcBuuyX3ynmLPdKvgYG/K+8Btr41TdnJQhd6l/YpVJPV6sFdPc3G3G,iv:r1tiKKR9t0AU0WWwZDRBJmXxwUOXYqQ6vBfP7m2Kt4I=,tag:0adlDDXlh/iTbg7/Ul59bg==,type:str]
        client_secret: ENC[AES256_GCM,data:avZPJKr9O/2dmerD1JwUDtU0C8MUSpTDgDqoFQF/LzLmg9o=,iv:4lft9eJuKxM1Lk5ZEEayKxnQr0qXPlnvorM75cQ/nVg=,tag:8PCT4en9KAAw1ErsSXAlSA==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:EnCtqUoT7SGjkg4/D6yD8tYgl7zQllxaJpn0P8bylIiNDUP0z473Wr3A4xaKeBM720WECi4OkdSPBqb2ggsnJw==,iv:mmhL6lbf9J2mWG42Ds2sDdRtXNp4ZAwnLxFBLOUqpfA=,tag:lsR9deYx+CflLVT6X8XKdg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:18:41Z'
    enc: CiUA4OM7eImM4YhvNiH1Kg9sKGisBU1EGiQkjZf7VT6vWId3RPQMEkkAsHDEl0OD8z7WGom4qNOZQirZM9uyde2QMR2iRkKnNJ28Jie8a4H/5DD+FoNgOmckXL+SLFho6M66qBcBCXtwSWSTTxR9GVbW
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:18:41Z'
  mac: ENC[AES256_GCM,data:lbMaaz6p84drA0VCrV5h+yQWprlbo+HXI0VhTk2s6OqT1+YgXlR6pMM1ueIzevVZP/1o2nb3y9xQqOSaCAhWanXfkz3OPQqLjjFZaGw+k6GSJ/5ke6JbTA07LIjfkxHQHcPctNhfd+IcGlY2zcaMyG/i2kMcb3HRLpcGmT9xuS0=,iv:DLgUNapijOCYmVKkHXgo8cX5XucUO+B1LlgYsj3FBlE=,tag:nH8gjVGirFWPQ3iQkXQI4g==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
