jupyterhub:
  hub:
    config:
      DummyAuthenticator:
        password: ENC[AES256_GCM,data:03nj0dIc2lKft04bJZEE/ISQQBx4Q6hVkae0hREmS4fEm/oc18C5,iv:A3biD3RcfoURlzGu0tr+iudBgVGyctz1/pMMBMXX3+8=,tag:snMiI26Cw1Rv0F8oqKfRPA==,type:str]
      SharedPasswordAuthenticator:
        user_password: ENC[AES256_GCM,data:1vzrn07WmpzURsEP6Cjz/tIamgBxdbuzfdtd7r8FePNKK3dTFPdF,iv:Y48fskWA2duPHg6r91dcfAmRTuyHtQ/gQlZTaj5UbGw=,tag:p9iEkduuKQFysabcXl8Dbw==,type:str]
        admin_password: ENC[AES256_GCM,data:jOu9Kr6JdTgS1VfsE9UUNN5cqO5x8YREbuexZicx5RtbSQ==,iv:l3gr3QbQPnFzK3jPpWcPdaP2YoybZCYEnbv18Vn70bk=,tag:P5Elkgxriikc/DlTdssgIA==,type:str]
sops:
  kms: []
  gcp_kms:
    - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
      created_at: "2026-03-06T17:29:37Z"
      enc: CiUA4OM7eDhFaujgbGtD9cPg1K1dM11BQgHbH4Dc65ZBAyalg9JxEkkAPHlbmbI86OKSPF6G0+yC1hu3kH+79JBEbNvUukoLYfVRHZHnpz6Yv2fO7awE90fw4gmP+zREl7kIDAvXrWM7Z8vGxk5Mp9AK
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2026-03-06T22:15:43Z"
  mac: ENC[AES256_GCM,data:POrGJZjfPyc2GxeX+4qZzEoaf7Vfnsvq3DM8JjTK/MYDPUvL/KnmyHMZ4njoUqD6WrWuzEs8Zncst8LV2tYq8ac/nzVAGrSW1I8hAj5Y3Yxh/EJqP5fMTtBM9yzjlG6QWD8UOAJ0VkXnYscFl+0CJSwwvCeCBpIxILVvBFyt/ts=,iv:wIzsWjWBzSGNBSn0THKShUrYqz5XAM+g5+5ES2rkp0E=,tag:yIrr7pRvpS9kie/sF+kznw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.11.0
