jupyterhub:
    hub:
        config:
            GitHubOAuthenticator:
                client_id: ENC[AES256_GCM,data:colEJgsAlfEPjNeZ+CmnteJFW1A=,iv:/6gCcLqADmy2fatFXwDXwbA3NU/Hiq9Gy18mlFB7wH0=,tag:Ak3dwzhInDC/HWGHLagj+Q==,type:str]
                client_secret: ENC[AES256_GCM,data:DIfWWHQAuyyAQl01PWeVfjI1PkntEWUta+JNPVxQ1ij4ky9VhwykBQ==,iv:Ztx0Al/RtVRhtd7Kx/ZgSTRkzjSWD/qNshGCCc9Ktms=,tag:WneKNy+wN4ateZbc4pr/YA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-06-25T20:49:30Z"
          enc: CiUA4OM7eGNN6p/Afv7pxFZyiYbhPmdfhKyE7znmGw+YPZ0+6CiSEkkAmy+ekkz8VXV53buVA+3aiGcLfQGlQvl0VjXEb6ECoq8MfAGl2/IQiGB5WTHgirl3PLEWmZsKb/J9PLypr9Ra3z+rdsAJIRjb
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-25T20:49:30Z"
    mac: ENC[AES256_GCM,data:tZ2rb9+Ra8NNAW8ePHRReekH+DWZ3qj5wvRIepIwTEswroBa0NuikZsiPuY9xuy2L7y0pvAKNoJMHXGuCaKD+oNLgIGNuKQGQcxWLl2XWIiRhnLzEQJkUHWMz9dmch7onld3LExI8MQEyC8yLygJuZ94ls51N3eqFvpKflMXgmo=,iv:Oa2ctGP/nNtChWYyMyi310rbjOLrxdNvPltmfGdy4o0=,tag:Op0x1PuGcpl2BSrY8hAS1g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
