jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:Sx1nBJhUEaUTW0cl9D7GAln0hAQdkd7M8IY+IlpeDfOPmKhLwSP/K4fvIxx/ILs129vy,iv:+MzppVMEa9QaEih+Hjpreu5NWm6hbbd/hEZAFpoeWLk=,tag:w8eLMnr8t+so27dBHureUQ==,type:str]
        client_secret: ENC[AES256_GCM,data:dpsS+B4ozXSWW69bsf3WmHZ1vZhTf7Z4Xp1EjQoNa7YCUwdTROdl5FxlyyZxo25xcwUekz6ALgI8cz3aJSeSWRjPlhD4SXtQUGuqTqIUb1tTkli79oo=,iv:JmvStDdqfvc8f4RRD4sFNwtGgfxVKtbPIIwuqFSypOg=,tag:S8W9OaffgzBoe87TIZuByA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:46:59Z'
    enc: CiUA4OM7eKoLtngOm/tGXoUlKjA+Eo1Ayk1HoeR6CsnTLA7ctdLQEkkAsHDEl1sMS8qfBxUV0ghilwiu+MoxqDiFeDulSzbVMxd1FgwRHc2k6vAbCdkNMPToD7KsnEV2Zbmz8JNW8PavGJGYJSXPpkF7
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:00Z'
  mac: ENC[AES256_GCM,data:+P/jaJLsup49gIcMH27OHBI3hbVDqy0UalGf3VrRH6/CHR9gx7j2nfAzrJJvC7W3dgxcrteGH8WnqEeraW5D8OxFCnBBi+SQBghs8LK5glilfW22/P94oHUhj4jDiGJVC7bHiRxDKreZeul5p9MVPoO2GTiyh76GMXIwrQgEaIg=,iv:L0TDkiNb8Qw1M58do/r9vkMaxGTv2+v3l6twJdZhT8I=,tag:qzzvaUZKcLu8D7WtX8FIAg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
