jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:V8FCt6ghO10d5TLN0OPrzrJnyOSmFTBAgJ0ds+BdJzUf/kqdJDi5lWQf9zM7U+RYSnfH,iv:uIA5B2uAZItKPCVAwNi7MZbbM3v6Dwa3RI8vdHdCAYU=,tag:YhX1u6nhRSfczcn6N3iPcw==,type:str]
        client_secret: ENC[AES256_GCM,data:dJZHdOve7TNC4UwW4YmexLtP9TBPKedltoANYjjNfhkyT0GzHB1WhGzbk8ymSHs5H80t3DijpOBYl71d68QXVk/pNvsGlzrcT2ZVhSl4VGjfpgSOfUY=,iv:p8j60RfdvrnaWice/zBbwzmlrJC0nbbcPhnKh1nc6Rk=,tag:IkLVitQFbWw60XPnOJRpeg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:9Cm+2SXKEP/MOp6D3Y9w0C3u5rgAzDQ7wuFLyo/XPZWXJY4HXMmpDoHBcdnJQSjM7OvnpCprxoTwRzEDE73RYmXxvhey/vmq3jGBi5hxfkYDH3q1utY=,iv:RTcAoAWtOPClH6zY4KJraRlCXn0xdI/UU1M7Pls4JpM=,tag:2WjrfmaJm6THSrzQM8L79w==,type:str]
        stringData: ENC[AES256_GCM,data:AvpjeXyq8pqVqtncE+p+U0r1nEDTQV3x8HgComsKq0mhNmCPeFXrhUglZKeyXj1IbxMooiDkuz75iZCxGOjbkG3S3F67uvW6kJpmZLFYkv3cR4PjKW1sDtQ//2faHIB+NLdPaUAkhh22r4OnnSEn2HZbXq8egnfCs4klOQ4oTMQuIeAfJ4I/FkufVFKjSCt2zwA0vR5w7YJtLeif6yspRp2Usx3ys7Y+WTx6t6bHrKdAJgHkYw2aryzzTV/gIUdraqXLMil7RTrbIIz5CXJi7/8Sa++z1iqFMs4JDVJQvo/rY+QW2QIGVGAkrD3gr7nyV9cCD2e+ixgGFGOIfVib08y2dyT1nPG02kB6UJ6l44dfLl8gi4qcQQ/jKlM74QMuo/pQevsNxbGL5J+Qp4J3vnctimjA0g0eHCi7M4tfYlivskZaNcHbTj1Z/P2eJ2fB+zIPeyZqlB8EmY/in0PLlu056E6y4OA3+LOpeCdCkZEhXed55iUhI62hyPef7zyygDHMC9XY+gtc9SZwb8wx1Yk+VJ2m7DG3dacOD24UngNaRsH2TVwLY30PDpkRzqHkWQDZNPd+Rfqt3KoFF/Zj5KDg2CKkDwAVjZpFACVK9h3ANp1+JCUzKzMiJY7Q6wTIHjpY+S2EDhpEWK7q7g==,iv:u5riHoV1TW+EhQuIFwBaexfYMBme7lYTjjMLhFxFvEk=,tag:dmtOuqsnlQrOAXfLME7Rpg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:20:21Z'
    enc: CiUA4OM7eMkJHQiW2nQVtFRKIpNKow1vMMyzyjFNiPQVjw1Oc/BaEkkAmy+eksZAFm7zITYYbME/WZUUdlx4ljVBKHZZXwmLGGfRm3WwZpAWNmC9ChX2EcTev3iLAHq30iJEuJ00W7DrH2NQratBCom7
  lastmodified: '2026-07-29T19:20:21Z'
  mac: ENC[AES256_GCM,data:aAeyd5j09uM0Z//z1961EFj8RBsflOKi11l6TTllqBgpNvZgWqk9LKKjP0iP2oVxQkp9i268TXCks8fQE3O8B2NPkzRBa+uScf3MXQWK/QSl7pS1Uk2yMpDuKGfQBhKszuYt4U739mCbrC8S+CkCZedXM85vQZJ+DsNaYBQ5bLk=,iv:H74ZZhAqceHp+drdjICi+MPzb/KDRoT7yH1pCXMEpLw=,tag:5wmiOPm+nLH9obJ0rAntPg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
