jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:G02p3dzPqF8c9aDpbjz+cmS0r5m330vOalbZ+f2PsIjzgzsHNDsxVp/1zKWfAZPVyxbk,iv:/tnFL31FaJI1u++CzfOB85d4KrRb1GrLwMupne6sdhY=,tag:QX1BN3OYjg7XFYM8r2Cx+w==,type:str]
                client_secret: ENC[AES256_GCM,data:rSqK5a+R+J4EzBq1mNsxabp73ap3Gh98AK5LOddGDAxSYa+athC2SeLz5+MU6GINUnM0ptc/EwJU4SVl1eHB2aPcLyiAesix4/OBYdh0lHazzRGOhTM=,iv:Kn1Tq50KkV+vCqYkg0+eborP/2RQVzwlvq9ohJBzmTI=,tag:E8UyLMWD0A78Ia3zocynmQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:35Z"
          enc: CiUA4OM7eDhv1m0rYOWffp+v8riOdKkWXMPTPU9mqDKqJw1LvhwUEkkAsHDEl7DLPMt2PQsDZTuwxXiYO+sVA+Cp8M2nElF6lhbiFFdgVVYPIofGi6ROfe5Vxm4K6501yY5/PIwGzaklx7kCRV2+oL5V
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:36Z"
    mac: ENC[AES256_GCM,data:+HFMLKgmfnyTgIoJrqD3SkUixvSCW1sWuEp7gUzUUP/MnGoY29VVDWdBwjwFBSii2X+9BUsRiYxdAx0A7pWeU26rcLFlZwnaUciaRM1Wqs6uFmKTnkjeVD3F/i6DyZ2WjwwaQbsm+glEoEZk70yic/f2ZHLnqURjFvNXX32rZi0=,iv:S84ihmaBUsFl9nAezcrnkHpHVOdpgozatWTBpZjT+YM=,tag:AzWR9+jt94/ez+fMh4XZyg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
