jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:Wo2dHRcrXPuu9EaSKm2nGah6E2gO0j9ZrAohkBp3I8klr6ClN+9kVM6ZKNWxNqAirnUzmrmdYR8kQDVMQUKR/ajTTHa/2Hs3,iv:r6KDumTOz8L9wmMyeSVTtbOrR1Ho7ZHqT4/g1ZTAAXA=,tag:7rOMkGg8cIi9agbHnlDIVw==,type:str]
                client_secret: ENC[AES256_GCM,data:NaUlH3KQG6ReFYDAAl2tLnxBV4memEJ7k3qBuZiI2R1MRZw=,iv:QTrvLvIt5bcmbA4bpHS5pD4gBDzTkplCe5HBjYx1FtA=,tag:rl3C1226siE46pBwHtV5aQ==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:X+gQm8ssR+ffGBSdg/Ei4kfcKT/9nUspVr4olBGmbyxAjR7wJjQ19AGPRi0fAS32vImOtRWrd9qDpOoO1yzQ/w==,iv:CleB4/mWa7T2si4g//8F2uq1ifELZq8XBUjBjbkYYTg=,tag:ZSvTTsN72uKdcYeSBGP7DQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:18:35Z"
          enc: CiUA4OM7eCgdMobHFR/xqh4lbGWuE4UUgvsegejRraCWQg9zZFiLEkkAsHDEl991TkYeT6te2DhZJhfIpG1w7PDximo+eXNEL+jjX1xeMffQmdOidN87EwkERhNs8YmLizEcBArTz0zh5Th3rj1m0ZZ0
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:18:36Z"
    mac: ENC[AES256_GCM,data:Jsu6m5Hv9b95diLUhSVaWmuoK55xYVsCS5rFhbGyoj0Ou2iYKxNVoY2I9h6OLsqYWRQGAIl8ZWKhsqSoIe8qomKkPdvL3EcRWOPBL5k1Ozx5o7qlVgcKHJY23WME9Y6P72BSQxWmap6V82joKVzNdA2RJdRRh3ppJf8AslsN1EY=,iv:F+aUpEs7zZeDPgVq/vltR8wQdFDdMN2eLzicjcqhE14=,tag:d8l1lTpoRikqOGvbHDMWbQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
