jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:N5tXu3AZKJxoSiIee7FiW7q4SA4Eh6fMyIVverRKgkwhzEPxLPQ9X+Z1L05OJT2w5rBj,iv:vMpPUtYAwwjd2YIfGgpumtcgjMYKSBXKiytnScDYU3k=,tag:RznZ+MHTAFHqXUNuQ9DWqQ==,type:str]
        client_secret: ENC[AES256_GCM,data:ws/qYPNsBTwf7TfQj+/gJ9Hwq+ltp0yCu+/zOcMCe1e3WuoxEzzbtrlWVtkb72jTum/NiNHcgXMnSLZoTGbYd2Pb+FXZNaMm8KrZj7BIeOmreaELLoA=,iv:5Pa5eeGs6XXrMe2fePgpE2KWSodAA7G6rCNmj2mFY5U=,tag:p4cegGiXFSK/azlMEhgyXg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:FG/uMnLMvrs0BOkjEHn101+VIr/zAtv483EoQHdXTHc0G9fTZh+lCWfSEHYe4VnA5Lq+B+rgrNVC62MjZ1QvFvx4NaNsiwVm+bdZ+TVT7gzvVAVH5jg=,iv:aXsd90h71djawlsxqLcGXO3uKMgNHoSsfc8iZIAWt6Q=,tag:lyycsrXbsyzZnb4aHlHWMQ==,type:str]
        stringData: ENC[AES256_GCM,data:UsYOId0yBphtUS9VhcI2GoKsvx7d4RnvjlqVQMAzkeKqBXetdB69wdRlpvbYKHN3OHOHvQje6Fp+aySFYGKOj+5lIyBVqA+f81FOjr/9o9yrduGlkEbTGdJrdCu2tCkred1jPc0PbDU1TIQbKErwkZ8Wo9gxz3OkXl9IN1/XI0uQBm3xvbbGCyf/ehrTvlyjvutlPGVxBcGK4w1W6H1ewt+l7VAR7wruE3q1IZP7mtzNqVxj5JblpadzPXbONLYDS0qM0hhiIT0mR5Lw8oIp7NsH0M9h5BVEmJvFfMwE6XYyi94ZK9X7E0dem8tWjpxprQEKJuJ31TQRp2Ncx1CVWCLu/eMy1V4PEUDwr/Xt6ueEgyDF99cXqj+2+LM2no4/z0nKLfonwWkuhA325Gu5PKNIBgjuSTvAjTAou3mJvPfOtWX7n/3eKfq/SCz5fPxggxMTuJRqK84OIji9mMmYq+t2RwhHsJp2c89hs4SIRKSZXg+119VtG9kHlXynTc5SOoJg5YXBJNDrG8c+4HS+bzl3z5uRm6jwLhgjHgtDKnmbj8KEnKjOqcCyfhzMFGJhapcjVSMgxvzHuotu9SgnBTYIAxIZolGWQ1nCY42gET8lkDylhKwzvCivzb0pax6/imSu8gFcFkWhQviT9Q==,iv:t25xpg/WdQD1S9plvmrrjI5k6HfwYvalu7uAE4IJe1E=,tag:K2ENWAnops3GqSpYZRz0aQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:44Z'
    enc: CiUA4OM7eIs+3uUWwjYWzzWbR7MzspLT0t2UReL2LcYj/RlmxucPEkkAmy+ekixpVCk5B8Zhkya+5PAxtu6KRv7BFgznjP20V63WMpOcN6CI2PQQkMM8oxfiPQoqkAcPWZkD2RNxnTNaBHXnwvibuWHe
  lastmodified: '2026-07-29T19:18:45Z'
  mac: ENC[AES256_GCM,data:nQBw8Qun6TkKtQ3x6P+egQRkcAXA9ftOwbKVqLVj4k+KtnCxblyJwLSB5cVYjRg8iQEU/eaGpL1oHLzeIRs2DHTs+OFZJzc+tUzJqjZ3T1/9mcKrhzZvbEap15BvuaFPFoGPXvS57wWWQK7wdRBO0yJ82Ss+9jM7NkjrZk+9zfw=,iv:awCBu59/XrrLOvln8i4HhVDnDUBE2//Bq5aqR1eNTyc=,tag:26mzUQUjNlCI5w00MTp1zg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
