jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:dYawzM/WYfYPWwqnp0/os1m9baLJuZe07Zbn7pIa/Nat/fhpdmXThASwKc1sZ+/UUP2h,iv:0XM1G5egz8Y9lyh6wvHR3ftGik23Cn2PTVXA8JV+IxY=,tag:2Lkvor+rRCkFCsfbbw8QPw==,type:str]
        client_secret: ENC[AES256_GCM,data:6YbTz5zt76XhHilHr/aBPLeapP12cBpc6T7Y9D3ggBvG6XjPnmITrfkg2tuEVUgWdluEF6KV8RtVw1CvhLqxbdiGz1OaU1uQo3BNnJiMMFGe3iQcCas=,iv:QNK1YJmo7P0INwAHlPLtdoAyZsUZ3ua37swiFbRf0pQ=,tag:EyY/nl2QOWPyDMmr+Kf5EA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:46Z'
    enc: CiUA4OM7eBXLuPkEusYxftx3igUUYlVMDK5jc2/38EsKM7BUd052EkkAsHDEl+foDHNb3ecUGkuOzt8mY9tGHWCdRK0YKiKyNe3SvQk1LHCq+rjrkFGqZNGZsK023bv2JFP9Guc+ZBOJhWcLmapNSAoO
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:47Z'
  mac: ENC[AES256_GCM,data:Z9CcA44AJrHmyuur/MTGGsTYAFRbRwpOat0ox1F8uQ4DwNFf9tLKndeUoRM5Td5j2OzHVEPgvDGp7DuOOgAmGML4Dqj/S5cqMswE0kg9vGO7PQce/UT6SrV82SnGjahoN9nA9OWVLjwUb57no1NeK2IZQoJjnR2kkbqlqUa4mz8=,iv:bNu1S0a5BwK3mJm1EaQehZFpwExULtocAveLLuxoTLI=,tag:FrsQnZj6PGzN1ujKOc7BgA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
