jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:aqaTd+hugIx8f7ouk/a7YJ1u+mjqC9+90HhI2xuhqMAd/Y4+46zZ5wE8ZRm2jQCkTI6d,iv:QcmMhYr6L+ORJJ4fjeZNXAVQvjhoAhueSTKz9TueQ9c=,tag:nwkuRhWnWy8chCgBJz1nBQ==,type:str]
                client_secret: ENC[AES256_GCM,data:lX5ETfMYia7TVP02wQ/pRRU3CGUQNxK/4JQz5QJeWQu0yoqkS1z2DN5gP7ztXvUPw1cpl/AY6r8Hw1MVpc/r+vDZ+hTXoHFQlAq/yCyd444vkwojjlE=,iv:dd3uSLv0Rw3c+wBe2bjcQiuWVynDiabUv3BvdUFrarw=,tag:KT/nuLYtdYPSkOiph8DSXA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:25:01Z"
          enc: CiUA4OM7eNxPaOkBEKfIkMoCpTyzbzveRvNxLltD2z1/QqTXbBbtEkkAsHDElyDLqOTH0H6k3lxs+VuLs7eokp13bP4KD1XWFcV1S9boiT8XkZ52z8+XOAU2quavEpUWSmVjoIkegfszVhbVlTVv5yEP
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:25:02Z"
    mac: ENC[AES256_GCM,data:4yNELCZLZKO71zvBZUxoj28KrVTPeaq50juOlpYiom2j2bSpWYwPwMSnnBx9xQ/wBMTb2giMD0UTW28aD5iwJanodDH9lZz/XqgnZ/nMxADFnL46ekLEPG1onCCD8ooyU9Zu3iTs0AVx4bDIYXbOJfWlSceGxJXqmcFcLvZgyKQ=,iv:SgdMuVIZawtlB7ZLi1RKtHpkXYiEJKaI+8EW8orrzfk=,tag:U9mzaSV7fVhjAQYlJ7uNPw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
