jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:Ddy8o14YMn3hycaUGpgvlX2tCGFBro0Hc3afnkoW9TD2u/NEtb3Z7UvOC9BkyWb3dCSs,iv:7Zc1d9t5hb6fQraw5mtaFxVo7GIWctRnUjc8OlGVOHU=,tag:D9LQOG5Ah0hCcXIkSE+Yvg==,type:str]
                client_secret: ENC[AES256_GCM,data:D/KN/dXUI9DdpxqiHgFkyqJ1dmrsfOlU5tSMXT6SjJCGdRSTLgC9jUPWtIyU46CHtdN+MK3KbTEqoqbOeSuFta62zWsbA0lnzKKdW4fR7k2mAIfgd7Q=,iv:3fdtdpH+Q2NCpzeVBNNeScvn8W2pK4noN0lZR3hxeU4=,tag:XxR3hTkgyMJjrUaS6oIjEw==,type:str]
jupyterhub-home-nfs:
    quotaEnforcer:
        extraConfig:
            secret-quota-overrides: ENC[AES256_GCM,data:BvE/p+1wp43HufD93e4v2fIakWDwua/4GtPzmeM9DUiTesr2L/n8XB+CpWF6DqbpA6yP9e9897Oc,iv:ZypeceS6PzeEc/IBWDD4eCXzzQDoUkX2SwL4wHGdlt0=,tag:i5JB1BFZoEKb79Df5zGhvQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-10-05T03:11:02Z"
          enc: CiUA4OM7eA2acZwvYzzI86PBdshlxDCJkIgpr/EP5vy+z3PCbg5oEkgAsHDElya1RhGsMBEDvEoOHiLsRDfhtAt4vtElR5bwICFDndutK+EHIV52Bko6nY8LgrCzII+ZJBYAAZDsN+eqqWuILLLjcsg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-10-05T03:11:03Z"
    mac: ENC[AES256_GCM,data:MBT0n0SDXvB12DNqtlR/uGlhbElSmu4yeIpp3vwxh6i1S3OfGGUkrzRzEpAeHLpl1ZnV1D6BOsGtvCdD175qlA55wpdao4uOPuRWzIfHgXX+6KpHbPNwXzETjigQG3M2KKzUYSeKHgxzTZy43APFvbFTjxuPDm9Jl9epMbYLmLs=,iv:PYpZecjx4vHFiEVuHufPL2YU53GokMKj+9LjXnqMFOM=,tag:wNBvN/CMzDeOzlos6ndP4Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
