jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:fHs2O9LniSiHdK3lmcFqYSSC+uBeAlKd/6m7DbGEO3Pg3OUfeSshg/lgQX/ll9EQRMOL,iv:KR2SSoGwe/adC5jzxrEv96/kAUW+JeTObMfBlfFlfKU=,tag:uaQpZomLvRtkhbCTv9dC1g==,type:str]
        client_secret: ENC[AES256_GCM,data:MuWNj6SISN7nJD4/SLwuqNIpFDipZR40Agcknft+OSkDdBRuuzPKMgKTh9Rb7pT23RkS7NufmM1lvszrUyzK5hfrhVakeE7EEEQBC3/lXaDUOrlEff4=,iv:EKYFYc0jIOXQV7NvTDcnj3Yd9zBTlis6b4xkERHG3sA=,tag:FPsvfUAvKjuplYtWXTSR3A==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:p7m7x4TX1iwEOTqmD45V0G4lesZxEh2sxsH58LH94ZQKHq/WtqmknZA7mswGm0WpCv3/mpdfNXJ6Cx4TBCroEvfVqJNufo4qtKXvGXsdhOidwMJyKWw=,iv:4fJRSk5xoRak4AjNNzhOdQFTZiXBJxF5d2VFbb0x/Lk=,tag:iCeyHfVN0DGgEaahGRe7rA==,type:str]
        stringData: ENC[AES256_GCM,data:dQhOcfI0X+dBFCD1g/ISWDrMo3yuxO9IFRLbAof6AJEEhX0sHfhYaL8ZqjQIqpVU8FyrYcjTOEuEPiS+MzlISNapPAEK6eQjkWl25mm2DcMCGPPhlrQ5neLlLNjveq9lwkAeoBP96up46x2YG2ksCYZ4OUGaw1uSSkZwbSnVok+m5KvW8C65wA9FfVlLYit0U+CJ692lUHOeVMcJGS1N+ur/CcQFezv9y2I7g9zkgxJIeIM95YSYpy88UmieA31nloFIUKxWpFm9+QwiCJGtf2k5P2Xf0SOaz0Fv0Z8F/jFrXs65sdjx9MGXBh+havKrkKx1k3uU6iZMkXtC57fi8taz1AGKmQhgo73Q5YgDgmlJU/BHO/hnCPC4AXFBZNVsfRAfimbIOGHzGL4jZjLegB8Qm8A0kbe3BvcN6qQDdEot5txxDAv3YYwonyySvO0OUD1rH1QV4PPNqiH1YNz3mM4rB/o7Dmut0cDONkLM/IS7FhchX9/KT2KXzEDFiBu4Fa+Q8/ZVK0W1xgzOE1AJTqPJk7AEKvyWvRo+OHCh1Fxb82O1yo8XjDQAkmiH8bnjhX/vsYsH3JaotqkwXbiY6frKX94kr2TH3JJzJEIMRWAfv0snGW4s+aejeBG7xm1Fs6KmdT1pgmT5US903g==,iv:FQt2O1tTf35K97w66dFwNB67kRKQG21ejx3J8MzOUVU=,tag:ZC0g1Gt9jZ/itO3KeZcWeA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:16Z'
    enc: CiUA4OM7eHn8QD1sUVfACHodGNzbjktnWGgaDX5bSQ+tOG80h2TcEkkAmy+ekjOirsmPk0aiV/+s7Use+dYKWh9YEk5QzkO2fUI6hvgQ3Sl9cddONHI0HqQkr2sd7/l3tg3S7y0oqX5E5LI76PPHofm7
  lastmodified: '2026-07-29T19:18:16Z'
  mac: ENC[AES256_GCM,data:YJl6WDdyoJv/9iy3vJ91cHjWequU14YmZ7VWi3kMGvLctjb2TCawExSGYCfrF+ptzA8Pqiy3ZdIuTsx+Wl5/bYOxGGJPz5Q3LpDO9xNx1JHBrt9F3wdoak19jmfYUTLT1nv1bWWGJ8XpiLUjBroC6H+6Pr2KBweRtLcAendOFxM=,iv:U4ix3LbjxCr+j1GwtW1RTRLxR/bKUVZQg4bu9I7FX48=,tag:Zr1VevO/ykzciJiCH2jwDw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
