jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:cvzKAmCJ9uc3hgsfhQZh+kXI7utezKqWgktXSDiuMoA9CaKo5AZqI2AeAodmPXi98SsC,iv:5ETuASnBGi+VmDzghOSctxLFJ9e9CWkK79hj5BDLDzQ=,tag:BNvfxDDc2rYAwSZzVxOX3Q==,type:str]
                client_secret: ENC[AES256_GCM,data:RFzwA/h07Yk/gDiJ14N7/6809BTXVuvJQ3ghBdHOsKztD1VBXnF3dO4YD88nqbD9TgPxfzxuJlrgt+qQyfHL4xipkROYZ9ntCLzWdwMdzy+HkIEh9Qw=,iv:FQCaRrJ0AUrS/hhT2Dfux3/T32yT/sCW1aDxxIQvOnA=,tag:YTKt8TaDsKRxRvpHXdqqog==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:00Z"
          enc: CiUA4OM7eILSSQyHuXjafxmhsuFT/8E1Vdpar6T7rK1+d3zFtMZKEkgAsHDEl+nKpOMMrehdiHURUk951G+y7LaGPgk5Y0ZnxnAKgmUzI0lkXMVFv/yS6dMWMhvSofSK+n3TKX5w+E3KHOKXcEQKbPU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:00Z"
    mac: ENC[AES256_GCM,data:QfBnHBQRKyBD6oISelr6HVM78KHnaLQgbiA2/zY5IB+J5CTqlecxoR7H95tQ0TD6RyHeIYUdMsbvjZn6c+fL5UquS6UNkq84kbz3kCTRuvGc07Ul9zC2F2hxGLOwONesrlMNyAcYULMtaNiiz2AnqpNKXs/0apWzEfPlSx01ZQ8=,iv:D3q+wCvo9dZksn9UG0MdzthnM4AgnWzHUA6lunTow8A=,tag:Tyv8ReMT5ZojGB5oJrmJ8Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
