jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:+nnM1cyUGM/ddvMhmjwU0uNrsbGRSuew4b6k2njIw6NBo+cv8RQ5hpjp025dcMMEIuoV,iv:oZLAO7/XknmQqiBDDAaaQ10PwBnoDlO8QQbt3SBC5/E=,tag:E7WQ/JtrkMxOm9It2BjgCg==,type:str]
        client_secret: ENC[AES256_GCM,data:ESWbnChN1zcc0Wp4gxw/bZNndTFPyBWITyebTFSYhTjoIM1I31osBVyoCH6CVUg018C+AiCbvZ/iMA3QgWYa4talE65kGQ4HWaj81L+pWHQ33hIFHf8=,iv:kyHrGaF7AUZO1xUgOyVztT6Tby4LaFDXhlrCGv+mwmU=,tag:13QAIcIVaOGGYq26vJRPKA==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:XSqoUxmj7ZbG6Zw7G7vyxR+/S+KeEYS3To0E6TLlglRbAsr9RFOIxoCfm0NQjVUZerLKASeDA2UREzgz24Hh1ySjsesXsB9Z9stsmIz0E3Dt4UIMIik=,iv:dgk7ntXBM2pO5zQqu/rN7xmLRf3AmgeipYIJY3oSUNk=,tag:k+iXDOoA71qZ5mzpXVVnWw==,type:str]
        stringData: ENC[AES256_GCM,data:NLAFXHpbVL5JARC6qZq6Q0juF7dvOdHi/uQzSGmns1js7cIu2jOneTS8Hyc/Tf5lsWPfVTQ6sFoAVRCt0ojU46nSBi/52gBvlXGfndasYYufFOrE3UkFnOP/1sUd+fRlJ6uqqJ1Aff+0xSui8cpyT4RHHrgo/vYqrZtYgwQOxmXa5Zb+nE6JrPKUaxRS0qjN5C76Z5YEVp8yRliZKJN5H0IFSVGE0VzK3HRyiS0gLJfXVGz66HgdNC2Fii75CaooXfFCtXC5aqexf++yEu/Dd0L/Gz4c2OMtjlr0+lRVsRDtv62yixoUDzbXqmO3bQXIAS5GI7ZSCcvxWbe+zmxEhunDr2xdncMmjq8iV0wJQxsSeUmcPI2IPKt9HtyGa4cjiylSMhE37Ua/LpRNxqzCSUN3/Ehkr0lsHaFA0zl9lJObg4fn77floWVtMZzz/rdrAF1HQoLV+J5Z0zqLXfhxmoi2/wt9Un04xjBbpqJtTEdzsbaE0Oc/p7X7uuMwzu3ppLdJxDAuKh93BEcn2AxViA01W5MLgOqCmxsPP9fbTc5vmZZ0820QeB2OmL8ZE5QVzw4LoBWUHJ9sPtXIBDO39inqWNAz0/vXZq1jOOKlPRZ4BOVRBo5+WA1rDUAjFj4ooEPzIY5CXQcj/sfO9A==,iv:voxvt3czOXsbbrW6xhqLAVRzymLqs4cLja5dKTOAwxE=,tag:LIJHAcKmeqRw7lysw8OORQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:29Z'
    enc: CiUA4OM7eHAGL13LcWYIAAWi5yQmhhZUAqBcZ8ocfpKtCI2I51P8EkkAmy+ekpc+Hqoeqcc4QNEBS0XU2pF0h/oLJCmVuld5dTa6n2XceqzGAj6fFcdl1ApxUF9n9Elbflez5mXF2HII9xqBhr1RMQqL
  lastmodified: '2026-07-29T19:18:29Z'
  mac: ENC[AES256_GCM,data:IIBIMQWky85Z2m4z3nJ7aQTiAVeVFS30wGwnqTKbaRluLF3cb9cXOvU9YEtJxshMyCu0TtmLgEwPd5exkGtT0l9AVzE8XciyjdIyH/9xNooXN/ftYcot7ETnJzIratoRLyXyapzPmraGME4n1bXS+wlk3T8DFyjrUahq6N34lkQ=,iv:Ribz1IQsvUbPBLpsUSeeitJTvGpXBnNnVHfomLbJtPg=,tag:GsyU5PCcwPhQlH+9USE13A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
