jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:XuXzMCjvbdV6gcWd0Q67kHefhlTixkA4Olq9Dc467qI3eTItb/LuUlVMMkB3BonxJcw=,iv:rtRTqf69TnYjpzpWeB9TZp3Etu/P/pNDZ6TdySvouvE=,tag:aL6jmTBZireUUCTjphYnLw==,type:str]
                client_secret: ENC[AES256_GCM,data:7nPC44HQYlseQpMyWLQBhJfszq1M91KXw/ret2dV9Bp1mVU5gI2VrSfyHmq2x4qUkPC7WiBuz0x39ofIgBbXFf8pZYPbLKNAgnXcwFCePcqprV7Uokg=,iv:3tmxMg22eJNu0ERhmOKrIPksIvojVqKGQOp5p2LX7A4=,tag:2kF61iRDkh60y/Y0i8At1g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:22Z"
          enc: CiUA4OM7eIYtMALtfHK5HLrRqH6l7MR4RkDXyXaK6RsOTvgt+q7YEkkAsHDElwbI0ORJbHHXMXuLgrl3lbSGRLNtwvK1k3tfTlbulHviEFNag9A3sNSRkxDdBVP+seiniNACVGzMUrxhJDlKhjMsmo/V
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:23Z"
    mac: ENC[AES256_GCM,data:6HyXHpMSVi+oE53QNjcvidWuQiiErwaPB+y0+Lzjgn+nMpvpOkS31m/uvxeJ4PeLdacj3CRT1Xs03QYKkVD+fbHv9mgii1Xjq0EAY3lCZ/ptZfOKP7zyLlkEpKwpIwZ1TSIv+4OLauwJgchfxzhUi6GIr5nXgm4ebVEybr+Igz0=,iv:YjUduA3GFBlOSC1T7PeldT413AgYdT+q6K0gfwlBC4s=,tag:nw6Z895nsyEqx5wKVK3gXQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
