jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:LAYOsHJINTplPrEdKUgRU4B6G8dgAe+XI7bx+ninx9Jdwm6PFWi+OO9mDf8RvPmcrOrg,iv:SfE7PqFZsnFA8wSSyZC4WRI7Ea7tMbCYGHhySfFOt3c=,tag:k3wQKgvOpJB7Jkwow7rR8g==,type:str]
                client_secret: ENC[AES256_GCM,data:vOdn1GnUEMXs5DGCAIPTMrbY5BeXSlheXXE34uP7e7Je14LqD9XL+9a67mWL/+vUWmriKsW0uwEKbClCaxS2b1ljWL18wSpmtAWyjmOEkBZHhFlvWVM=,iv:vp9Gc3dqJky8r5ptZyx7SRKE8e+ELK5GEZBTcW8m2IE=,tag:nS76FeVNUzARmZ2oCoBm2w==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:48:04Z"
          enc: CiUA4OM7eKl4teh+kgPuFbCgeEmxZvb9PfGj3umZpKasEd/d/ZR5EkkAsHDEl3NR7pcOIFp7+e4CaPigUas6sMjxM5D/qV/fsp2OGZM0kINy5PjlnyxG/QMxcLncOsP6Y2u2fGvyKkB8rsN0PKvM3/tU
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:48:05Z"
    mac: ENC[AES256_GCM,data:440JKvplvydqYeOn/X/wPo8agS4musSGIChzJYrmK2WwidsT7AKBe2zHY00cnCLYsjpdUDUGW4pm1hW3k8F9KjtT3nEM4DfQQ5J91ge6VqyyCDkqp67Q0oN5ckC0oyhg01w2z5VQTHteHk51EUQbeWh0lNTZJa3jCG0nGwPj1FE=,iv:i0moqIevBalM0fWuT14v3m0QpJZTycopLsgIrWwGcYM=,tag:4Rdudc0oiE+PkXZpVzbs2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
