jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:rTjDSkGIB7KgcuN65pFJZSzplCAA7x1//YbP/JDF4hhNeRXvkJT94SM41iOuWaPmVTZA,iv:dxFExtZY/2wr2Ex3Au4+Ww/yalRdvHAnmiL8s7N7cak=,tag:1pugU/h/pOrJmMroBX8wgw==,type:str]
        client_secret: ENC[AES256_GCM,data:/SzkjB27FqBjDMpvrmzP5g+p0LElhRniguQordj38SpdDEiD5TJtHExtL2e8Lj6SC3KshVW3/7VhM7BJW1eHV/D6JeKPlTERt+7bJbixn1VPJQ5jr2o=,iv:ffFvJGTwKF/KwPttmLy68aCfxkGxQF0DzBxz1uXEaJk=,tag:VhBGQx+bi8MSZqM2ak4e0g==,type:str]
sops:
  gcp_kms:
    - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
      created_at: "2026-08-25T16:24:01Z"
      enc: CiUA4OM7eG/JGiybFimLJJ+drLrRHLq0VmF+R8APeMl2DFRWpgYgEkkAsHDEl1mru1UbRIrBcMXwsViabIuhFmx3gtxCWoiKMZ1px/RSfPEbfW+kEbeP0wXlFx8buqVnbmd0JAjDtIPmJI9+ebWdg6kB
  lastmodified: "2026-08-25T16:24:02Z"
  mac: ENC[AES256_GCM,data:DOmCEfpoFSoEF3PfRzqsAB0Qmu594sw18LEcSL/qn0g48mtulFcsKWs0Gtdz7yaTYcMQOJuvZcgCOXgDCAUi7GyIWxoLkCkAuwr5uCrkcdhODnL3CJoJ9RNBBFm1saV0UuwETo/pa11n3IY+VfecmUIGYnQCxHs/GxP2LpcSLV4=,iv:4AMqucqt5ihTBaauAtMWJYl/+5UCYkgqBT+daCEdl4s=,tag:geG6Q/OR2TECy73oJ1knTw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
