jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:eDiUqcNTa1viR9ViTDdDjW/abfPk+c1xpEnSinfx7huCBAz7/zyCUgQAgjsR8pLAtsif,iv:xQHLfamMCY4Ku5WQyOQL1c5oKmumY828P0rFeIztJo4=,tag:a8oNv077mDThzDTernkFzA==,type:str]
        client_secret: ENC[AES256_GCM,data:i0YeHk7joLVSB8wXKX/RNZMWYQHo5cDP053inIuXTJjGAK6/kLc1m37V3o9l6pWZFMKTLPqH1ZngeI4f4qvmZPYX+miiDSDT3iiMJ2aZWFiCvdHS0Ac=,iv:I2tKdi/WkjJxPQb7c6oLQw/rXTNwKtUUjvNVPFYHlu8=,tag:ZYn1NQhGOP0sRw+kz42lrg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:cG99VDvEG24drHyTICPNBuAZpje4X6CQSYBN36Guhc4O/UM3gmJd9L2Iy2YLBT/2evw50D6kvGGScgMW73IEm/DV4yml7arNaITOKyx9wBJDi1byfAw=,iv:NZYbgctTiKHbsm+8zDKAAcoMOSFXtHlISLji6bvCXQs=,tag:CHMYsvKR/eVE7FyWXY7Trw==,type:str]
        stringData: ENC[AES256_GCM,data:o7atMzFoaIxYehXZ0j0FJzWWSseKHoFw76fpSAg3zX3F0veET/+dzVWfneBd4dOPX/cKPJd02lcFmcJTbm6InkXaYFE6r1JWO1IL5qNc8JJRh84NvTDwCvWpdSVA+ibi1PFdsxCVWWP35aVjLBE7e56YVPD8JFw0yJQhoEZUrDKrkTGHZhORNIlhY3WD+NkzC2rSgDlEEgTQFvrXZkyhuIMXuUioadyW6otNeTGOZdZ1ZpXvjNzcmUcICJk27ldJk8KxWjtA6lVQcII/agU1y7RI5nF7/KN/lvz3fDHhkoVW4aE/k0gnBEAtFCPkIFsN67EKAHSlC+Qm89ddstKxoTYVV550k1sg14v4+MWqp7tnpGRfB7wq0CsLvFtx+ZoNk6WFvkvlFepXaSZKCaKj/+iRXCaUk/5AP3ZzIB694hho3Yt0rc++goYND9EbDievPep/fGNdxBsAU602XVEL4KgTWBKMXwO/r0/voGk4QXVhe70VIYXoj5TMNkOR5s3uehYXKPnYpyGBEcSrek2MJ6Mhe81XOelxlujZwnY3lU9DT44XEVWcTJZhuOKJPJSgW2tRE4Mhrb+Uey0ed3c5TCZF3sqVg1nORjNXEW8JjvN19tv00JecQ80vY+6NLH84s00YcG265+RqXXqnpA==,iv:Svg++vzcgSymNZuu+Md3ZXTQ/+cUzYP3AkWwV+45Gkw=,tag:n9+z+Cqk4mlp46o74lKTsQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:20:05Z'
    enc: CiUA4OM7eIBpK0nQkFjSuap/VlYrwgHg13OTUxUeK2SAw4aIg6+0EkkAmy+eko3tLQ6sxpm/uzUF9IgaOQB2XxIMYk+/ZbIFXkOHCp989WXIbq2aw+OBfXPTgCkUPqkssRzZcZmv8SUTVlUqWs+UKHoH
  lastmodified: '2026-07-29T19:20:06Z'
  mac: ENC[AES256_GCM,data:0P8YAwVWPyJkNIO7DT092TLuK3w/5qmvlbeBCTJgPCagDDhxyv/Rxhl/N9Ik1gNEt7ZLYGjmWngjn23AJMLZCV+4KxnDhwPKZP3YtSlsvwCKiyo+DgqLSXLiAP/G87gtkSHfoKRZvuqt8uwlYDM2B1vYeMulchsprQ3KIhsazMM=,iv:pZezu+uy1bHAWwDp6dkuEp4kDcE0KSb7jJ4jTXRMN4E=,tag:ri091BeMiUQ3LZNpmQFnow==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
