jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:IwyMp3vv158QxSu+zembvFMos6VrlnxalTFV0dxKe0LUo6vyeXp8E7DPuBc54MBbNBDr,iv:UttDyRBbroDoAuE7R2S0ORDPG28Fc08qJnQqDv6W1gw=,tag:8EXezUjiyuCeclsGyu6Acw==,type:str]
                client_secret: ENC[AES256_GCM,data:mfsc01m/LCHuqB1j2eog6a9z9Wr1eYFZIxeZ23fDhuCFYnu9Dyy1lMgHkITNe+Lj/AOHaXwbLq8m0xlspI2YAnpN0Tw79h0zogJXLPPWlZvJoDlKZkM=,iv:EBLUN3XLKvN30gz1FpxCkR78DD3D1BjYGBJ6yqqTFIM=,tag:c3ROpEoncGWRuyUey+HXjQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:33Z"
          enc: CiUA4OM7eL96dIOiWnVMvY6TEI8w7wuWcsBgNFWeDBrivnPwQIg6EkkAsHDEl/dRLcB1JmiOvucGQCODDn1WhO5FzUPsIPNeo5Vv4rPpnZDwcRzGZIlft5uw9D577/ypUhI6Y0tvx0vuYXBSofbQR2mt
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:33Z"
    mac: ENC[AES256_GCM,data:ar64SnHrerDk7B0kdDiLT1TdDiD4JBTyAuNeKTynG7pskykaQ4bbQen3kQYLGO8qrsKu/XWB8e/eY4sWV0JefhmqnOU6meq+tzIHYOInrgyzW4ZkZod3k4Tz0wkxtocBxHQR9fdAL85FrlD+RbSYi//e/Vt3PoEyYl1yfaaZYNU=,iv:gJxBtgfFO6YvBuDYyk8KCvTiGuQza4DXt9ucD0u5Dgg=,tag:V8e8hXqn4uUMmZ8FtYTK2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
