jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:PLeiL8W+o4MjIfHu+1M0PNqVVrPOWnAe7rhj1+aJhuGXO9jesV7CDdn/5Z3FkACgIILR,iv:YJ5WXOQsCryBC0n+6+WN1lxbdfypzKH5jV8+Lbv236w=,tag:xmPNzN0icGTMppINgFg8gw==,type:str]
        client_secret: ENC[AES256_GCM,data:kNLnWbhswCjoavheLyUxI5e0Txdt5fs2DTXNlItKDqopfKSyFsCecoVetGoYXOt1Q2FGPoYKrrP0EbX+7IA8HeaPMXVPk5kpbTHS6i+qgOQOUcWkNZw=,iv:9Ia8RcXYVR+Ap8iycS0jrFEJYgrHkcGuINqiHgOV8AI=,tag:bOJOwHLL5mMCdOvuzSbQ0g==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:COvjH3mxdQpz1a9poCmmPobpfNMc3AK1/RF10ZdqsyE3v/v9WeJL2PFLapoFIe/9LJN6AYRCfkJMml7ZMPPn6xP4nYspbk3W4suP90RHUoUmhyLf/mA=,iv:M2B0YWgpnY/1XegdFOmc+vHYKAdT0KIWbEv032DIaEs=,tag:Ir/EzOqXlKjbg+Kkv5A7nQ==,type:str]
        stringData: ENC[AES256_GCM,data:mhDkVOoEyzoB/3b1hVc5QxWbEtPzfzy/zmD+a8hFUfmCTyfRpWKpAxDyqCp/wwTgjtWTQUNUOxdca+N/7+xkm/sKjqS1crev6grKffxc9HPlzQLgaNI7DSMdiNP6XE2pc9vjrGR6Y3PFeyQy5CWGd58Ge4UXM50wQYNaNUzyyqRIvPXCsHap1z8IDNXKlTZDD9ZQ0jZHlyY7r4OBtMkLv0dD7BLPqYgYKLtFZT4YV3sS09+Bsp600sKCGqWr/eby1fENxRV/TvNzfzNcJJ00EB/nWAcH7QfniPBOz0QySPIou/dFoipzeOY2tfmaNQ7YxaJAs350Zs93ttLdqKqstBWbL04pvSrmviQCIdbhs7RVNdmmtyXnrUXLIp/MKEVrWkZXgunut4TQRm5zqYMjwjvTIYN9go8l4Faj2tZtH6jsQ8ishz1zAKvbRnWsQ4WCyiQG7A28rg4vuuqFXwedqxU9xY/s2EQeSfCbmruBonlQMSmMHlis/3hWNbzai/dsoETeenI3tHyvLYrkBtMOvAsUwSlr+kn99UzUGU+7iMUnTb96au7aVnSDXpnxxqsaQRQ1M3yhqz6IdgxrnMzIYW3EiM0InrYzqViFLMVaTxes/alF+oDDMGDECXEAoFsqOHSLuoT0CYpd6MjQZg==,iv:QFeOAaiU8e7q7Ss/baHAUz+7if0nRXQec7T4nCPyE5Q=,tag:9F0l9qNlKEjTM5C0F0U6tw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:17:34Z'
    enc: CiUA4OM7eL2ul2E1OqrhVwxzaWbfQCqVP2Vl+svU1FUXau8yzAtvEkgAmy+eklEMUUFK8c633o4AfzapltdeTQ2O8B2N9QiGeFd3GZuDQrU3Qa9ucfFsPCe3dC+4FgrbYvL82tMUlqs5QdI/xT/XN5w=
  lastmodified: '2026-07-29T19:17:34Z'
  mac: ENC[AES256_GCM,data:T7vs3eWqw5yC+wQcdRrUXe/oDpKIBXUhAHUcOJVJ3TxhwppK83OcT3CFbtsF9JVYnDk2/94qtCCxEPKM4wQYV3gghy4ehsLrF9FzPAwgri686VhQrMVJpuZYrz78FjsRTwxu3rFIt8tc3md3DTU+4nzF/B/J9auH7v4bKK4265M=,iv:KJPApo8fKfgf8JnRqvmjhPl1USGkQb4VcjASXuKgFnA=,tag:kS0hRyKbzK4fefPy7UBo7w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
