jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:wxiAttaE7EJF7JjhAyYv6DrLCl/e0sEfa4lMKnUWsod9qF8NUOoaNTVitMARe9yEjWI=,iv:TLXXDzOS+8aAGUExfsjJwtPGvAZ2ccTs/EIUaEGxJwk=,tag:/xrsg7MADuhZQr2fSn5OkA==,type:str]
        client_secret: ENC[AES256_GCM,data:revQTC24AGmD8oqX9QVagoWYDMhXwxPLIQlj8xmHVkvpQePZKYVqU4Zv4cu8P7M6SeBIAJUGTq5N0WHMXgi9xQJj/nxBF2bhvI2Xuu2XnE6QmHTAnQY=,iv:XDufKoiGxFxxUJUQdkfIkrpNy0db5xeGFMNn1GL4s4s=,tag:ci4C9VJJx+qWqL3pPve48A==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:l8diEI9DNH0c2BwgEDBzLrp7WhNX1ApI0UZmpbqtaA/8pMqhfsqK6ou4D1rGn5+iKjcB2QiYrY+V/rpHafHxgw==,iv:H8RH2UuG/qBaursQq/lgIYXYd51Gzb8gVVU5NbP2ogA=,tag:WN0ZpZtgRNTFLNtJtVQFwg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:17:52Z'
    enc: CiUA4OM7eMphPUUF1lzXqGu92GVex7Zo2DMC1WmvEUphd5vCj0SUEkkAsHDEl601sVLTrsrBAnwuINdLvYQkIHcINsf3vZYpa24KB8jNI1PukkLGkdP+FWwOscs2t6TGXz0UG7oAPCD+HuDRtCrN0YQc
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:17:52Z'
  mac: ENC[AES256_GCM,data:x1HcIbeRLLjQYjAjrQxsjd43mc6HcrOkBNcxuPkeV2CixQ/4F8bRqEL5Eio7+Yk9G8iUr7EQ1uQUvxtIUUIq8g+oojYh7zEx4aIKDwnO9duOj8mMvpTOCGfIT8VFbKJgMqxf277qp9l10PmtIgK5xm9TQhdxDm0GhkDtczF1Nsk=,iv:EeRUrW6FUxXMLarwf0Aauh5QY/eO2wYCd2YGubn9cAY=,tag:0rQeYXWnsg4werEjXAfVFw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
