jupyterhub:
  hub:
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:JDqXJ7g+t3HqV+7aRJMxt4jS7kciiV8QdcZYDbOYqpouMNGvBtLDz4y1549b12CgLadNySKuZuw2BmyWvIVPIg==,iv:9gGe3D2LCWisoYMBpuR6w3Or2u1obC2itVALbntXcwE=,tag:hUyAJWgx2l062/QR7uGzgg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:20:49Z'
    enc: CiUA4OM7eP9CrPdFAwg1biu2vs/13wc0NO1pVv9TO3xOVt5+cEZjEkkAsHDEl/Bw7NGtLwEo12WQSFx5O+iMahEOCsfqmrw0hbXqfZtrbWlYR3ZPc7LYidWIQ0Eb/9HmKLcljYp0i65YTSd1it+C2hsr
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:20:50Z'
  mac: ENC[AES256_GCM,data:u3mc4ssPtjNG6XGOC4I0wtf/qepVMFVOt5Fs28YyQenh9VfQEJR/Ewtx2V9MpPkkoun/wp2RDdG7uNinAFY4E+zhMnqSPW5gaaxn7rZhgqUIne2Pk3kIxMAUFVlLfCaI/A5HQqVcGt7xO4hnpsjAj9/7HFqyfL7TeaKAx+43Kz8=,iv:Ou5Jx45uQEecufZGXPhr2FjoICvvCQ6pmGJ5eZ/9D38=,tag:tWNpqTsKl14FtJdX89Q0IA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
