jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:1c/hcLuGxsiVJHc6tC4hR/dOIyUwtZNzI9JHTeVDyGl/lg/3wJz/avi0ZVPS1Nki0kqH,iv:RL4XVNV7w9XvtMUnVVQ9mmsN4GXpbVZfGE3kcvd6B/w=,tag:KR57l5QctFaGJb/vBlLOig==,type:str]
                client_secret: ENC[AES256_GCM,data:8VTGDu6+fYHvj3/5xBDvNktvo17Y1VLolzYGZJIggeBSwib0MtxmhGYUgykjHdrAtn5pIOo8KuC/cSmf7Vif4ZceoXVFr6GAPahVgHIu1JeN6pRVsT0=,iv:dec7gAg90BTyaQZBO/uKSZkcax9TI9/cgu8aERCbJ1s=,tag:7kF4ocZstJF5Hf/33XVoPg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:40Z"
          enc: CiUA4OM7eOWeHTTAuqBZtDKeaOBGX7okK7MpkDmeEdIlZhWlBJzqEkkAsHDElyVSbjT32o7p7brsTIUw9B66LTlvGw3NSYAJL3MQSzV+m4hAnc5ITtUn17kbqy64C6cGwu3q/XulGZYQC/Kb1AnVSDa7
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:41Z"
    mac: ENC[AES256_GCM,data:aG6J3X95BECxECCUe48neikLyootXsP9IWc/Ds1Z3bjC8N6k3kKqqOx10cCT1V+loVA2s6SrtPKmYw1Z9w+k5edwyI9qh6m/dZgU+cVmdp+IBOR3T6xGBm/+KvcR3WBKGBSEUihc01LAHwQL4ikrV5T/p6E+tB8ExtoRplIKabU=,iv:Ypkn1KJs0xsKplRiYjHA48TgfGD/hV7D4JuDtmu2pms=,tag:ey7MdyUFHKQAaLd5Q2Am0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
