jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:rmN1uKWMZmzF2aiHw0jUrJTBpyJpF38QwG2fpwc9N/MQmvh3OxTKZhl8zyYEsNUEUejY,iv:QgXgP3TOCKlnHl/yk2NItuVyeDs73eP/0MrQfEusRXw=,tag:eBZEOTEkrg/usTQkEO936w==,type:str]
                client_secret: ENC[AES256_GCM,data:iqbI0/WUlWA44a7KtLqPXPp4PoVrZLJjZzxu7UnH47lit1H0O5fv7FP7GZ8GwEp3XegGrrxnL1autJa4bJTSggkYowFlTvR/PTyU0QRzMg/9iMjptRo=,iv:1WOChRgdxQ5dFZ3aJU8wCwzvFXWYAWyjtKKvqp2f9O8=,tag:V+uGVYa7RHbcn5+LHYtpJg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-11T16:55:18Z"
          enc: CiUA4OM7eOwpXT5Mj8Ycm53ZH89WAAm4mT/x3R5ROSllTVLdiWaWEkkAsHDEl4dsbhvEu73meXeRg7Ptm8odk+KDoCqa9n3uQprG/cn2EtXkriGiu+1UIS0IN6BhsjceGdZ5NFaO8Az/9Xa0ewcPIPgv
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-11T16:55:19Z"
    mac: ENC[AES256_GCM,data:85Qd/uhfyC+O7jN/z+Zme3ucj6F0sWGURYz+us51yNozDKVLge+yoQmAz25dUfzp/8jQ8NyFW0Z2BO+K+/Xh5fSEBCoVG6PXUBxaiozFNtJAKo2JRP6uXfGdLHhPsiSa+ajXeJe+v/Lvv+n9nU313LBt1Fay+H5pn2+r8aVeY0E=,iv:ixdt9GE0773TgMkkHq+0ehLQyTjOce631EBVJGOPOUw=,tag:tAI2e5wGOLQTiIcyqWQoKw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
