jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:AtmFwyLS7w+6opCRvIrvk5AYhvfC2m5ykjlv8NAiNbYdHJRfEo7HQjPIx5xf6ij9MHM=,iv:puE1y3iVEfgPYx+OS4AfqxXhp5j9t4Dt4aNGpDB8sQ0=,tag:HYkobVaJUvhNT7iSYUc5Lg==,type:str]
        client_secret: ENC[AES256_GCM,data:pUWWupg7AxocDjeOT5CUT7OHTgGHSrzJA7afl7dr0DtE2aGMjcVQNVZ/DBE3NSeuk4W5Y04rvNpalTuZsqDO6a9JJsxMmQihbTbBeuw29P7CjXLJ5ec=,iv:nEOmxRdezIPzhbpiuxK50DcrRE/7LFij7zeCea2EHFs=,tag:pq+wp9g6j59A0p8CClNhzA==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:/Ae/7N62SJmylrJZ8xqPerhaRAWSpqzosQuX8KuqpdXgtcnDt+7xtoAwBxi8AoAO1+Zm0uYEqW+xwpj7Te94LjmfTlRwEfwvPrClKGsBUCzFSWGtkI4=,iv:LFxTQV/wG2LP09K2QhJKHhkXpJMbS0ZX/RiHFSPl9Dg=,tag:hI24h1xjcChKbz2QCIRhTg==,type:str]
        stringData: ENC[AES256_GCM,data:36pN+oOYPG8wDPULg2jGDeyeQCrMIYpPSxLXABU4ObyVwNug2EemvJ0t6Pc4u7o3tbE6NFx5lb9nRfJuMRtGH3DL0rD4c4FbzXU8WBB2Z9DKzrE5nkEhbXhUIhzcsx6RDr1fFJotq6yKQZq2MPQ5588NXvBqndsgWQzD+n5RmTtFg1YsVJFBkpKhyGp9jU1tDpUYvowvV+74wrXm1NSZfK3NVlKV8w/vuHc0l87xuzJHxyfan1I+kFVLwmHhlooFGTz0g8QjjXvdjMdz7zqwisSwnd+Cmx5HORoUtw0fSWd+2Ms8nS6ZnTBFzRy1NoVd66gzeyKpQgHZKgmjZTFVs0xzCs7UM7iD8ozPIgwEyaZifvb1tFfnam7YF1zNWQluUkAcLpFN2YqIg+/44ypgxvxqEQKH7ecWjgvGaOq/6hIa7zsl1I53pGiZUBttF3eJpIBOZ9pXxnRvzZTDTN4z/9Tr3RxU85Wsp7nC3YMX+e3QoPpp2WVglcsuwKxl0pVKqVw9EuQYtEQJDmO29ZupYapUYdoDal3nzq3H8rgMBDzTC3NmxZDjcipcDBrVL/3FG9gHt03Rat1gHI4rvZ16joyKtXxF4c0nQSQ76L58++2QsBqIxjtMy7wQQVAK8mPVn3n4rKCfzqsr2kHRCg==,iv:rNy7irvAM9GxGlXWbLUd3IHo0Or7RSPWCC0lqFMFAm4=,tag:aecHuseJ9osYk6DO9FODRg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:22Z'
    enc: CiUA4OM7eCbZ3dm8DVKp4WjNMYBX8ceFBfDGpNjIQRMCyjEnQt0ZEkgAmy+ekllb0BpIyRNROsIjN3JMK4QdgrwoEBxwZMfLIC6DeCgebQBgPpSdJjuZBcIyXKWg8VhivY+jai3N02pb4WOwKkqjV+0=
  lastmodified: '2026-07-29T19:18:23Z'
  mac: ENC[AES256_GCM,data:r8ZY4EzE5pyH4tCnSMlsOpcggTwjVPgu7v09wxbq3RUiv5oA0XzJXNztZZm7VeqwCmjzBpy+9qdNCkA7R5RhhJkxDpL2hnXvd+grRW+pIW9BzROEmsC171w5kVSimZrWCjPuw8yAf8J+rJMufEGuw5mAq+t6IaH5ueOipmocnKo=,iv:J2saFLRFXeKQt+VW6OgGc8My4QwnTiUoZenBXIlb6SE=,tag:S8ruyLcmuvGAoYEUVadYvg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
