jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:e8syGjdGnYzqSyMXmxN6SVLVak3FpMx5kAFeQAmlBDisc4H075ggM18dDLjLD7v4Nno402rpPaxYUK7ZkHIc3/IzhYUqVRou,iv:FGiiLGqfX5WrWFNUeHwAjYXc6eeLMrQqW+9Px22rGSw=,tag:He4UPce7RYIZKgVDq7sKFQ==,type:str]
                client_secret: ENC[AES256_GCM,data:91XhvlXGktjBNsFGQBe4hFTqip97nGY18wz+gyRiMBk312U=,iv:jRD29VdwH8YTiil5oG8VvkZUpzamDM9N1exBujCSS7M=,tag:2u5p8yW7N0SlJ82tO4L3GQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:44Z"
          enc: CiUA4OM7eIkfnvTHKnjy3kkr0nX+qqPT4Bxgs7Cm04CMAjQy3DR/EkkAsHDElxm6LHKnriohOMbr4rs3NGzXgU1M2j7A5T0sEKO3oNzIqs4fWjDx9qMmKvkj4QuQLSs52hdbPoryib2PZFyLnrRif2AD
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:45Z"
    mac: ENC[AES256_GCM,data:6LQ+Eg1UoKS5xxN605h+sj+bmyk0CZiRErEocRJAgd9QDQ77qyH0doH2JXDUvDr+VkVWok98h9wFnGNXt6PfldZFkf0LQTsIL9EFNpGC8Yc3SqCEcYOn32aoIGuKDBBPfGYJq34J6z//FfRdSGP+IHYWCeUCQV63ZNU4n1ww9lI=,iv:Mks0n3YPGE1u9C5l02DNODpKoR/iTezyrfgKu5qDNAY=,tag:xm1zjEWBeWWFEnmDCQ9ong==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
