jupyterhub:
  hub:
    config:
      GoogleOAuthenticator:
        client_id: ENC[AES256_GCM,data:rpc0mgNJZUM6+clLD/e9UvOuhOOTd+11u7v35clqXi5O7edndRcd9ASLDtMIvo6CvqGJVUfV0f4/a7aKoNdRrJiDiuzmRwaO,iv:qy3WQD5xpbBjpDqeQjkqHBJ7QiCJhEQv/Ll2228p9BI=,tag:QjR6uYiP37O4k08jIfi+qQ==,type:str]
        client_secret: ENC[AES256_GCM,data:SZH1jifN+ziuQgxY9G2X/+347Zhs5WJvXF6VoAiNBiM0nP8=,iv:OZYqOnHMhL4nwC0thwRRrE5KwhinaiI/C32jHjzjGnM=,tag:S5CdUXYVss52REkhNBE94g==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:SICX7xWdmqDfe7UU6cnz2roEK/uo5pgNNS/myGwmKC6nr5J1AXz7RjP6TUdZv+ywC6IRfmv0veZms7eWyZbukkP0rEQKPT3TZUATgh+o0KKChXbYRrc=,iv:sRzVjCLES97+LWah0aqePFFC1tduanlewDkuCm2/6iI=,tag:Gg8OR1ZmrWEcIPK1+crZRg==,type:str]
        stringData: ENC[AES256_GCM,data:naXbk5K/XTZJFaza0cR+DURi352o/kVgsUYEW8dsBF/CqObroxnvOLojQ7Jed0n9yc0leSWBOvurk//87L98OaAOHwhOZq2Ixxk54LZTAQKztofulpmLvbfILUDgAUXi17oTTUdNvEM+yTyCgXIZjpbRUA4pCXvuDs6R1KSIeyObhdsn3Mj2d10KNeqinvGnIAoVbxBHJHGY6CJ2+KVf7kxR3dC3lmSuZPDpMtKVuJaO01S5h3fE/bOYpSTrpueMAdO4R9Rxkn9ktg3OER+P5SBOB6uT8wXB9HdG6j4JM8n+XyOQq8MY33t007Seh686ga9MoeH3yxSnEAh6eibY8MCmh9o08AskTGKd6WUw9wPETAXMoiqymxgb7rtTFSGzi1716bRzJUEo6yVNglhQmSPdtofB14/LH/axFvZAytDhjUdYFqu3e5WEgxyILm0K95MBxYi6DtdBIKG16Pi/UYZ1uBKanydgO29E6Utr8MzeASWY6JhhwTL0E2ZmgBnOl/FObA47/zlUWruga6VSpNBre1xPjBAyEc07GbtDeipB/54UTmE0zKnYhiJxYNmnQp+afz/ms1rT+RSsPQNMp2xE27dReW+IgPOBrsUbKoE2q36Ud4SnuMpqZA2fbRYFhmbpE9WcDITPidYotw==,iv:2wpGb/SB3gVamFsY9CbtRfQdRX67njLfufWRSap5cKQ=,tag:lx+lBFodxWVdVTsJrEo3Dw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:22Z'
    enc: CiUA4OM7eI+06NftDChJOu1dwyVB9SUZurFcdOU8/XXSIRnohZuvEkkAmy+ekldnFAAP/PzakdLRzw7UMSKCXYfrkUx1xc9VJN4/4+74a9yBPA/Kpr+OExLPS8VQbTzj0FIhUKV76uyGKrafyw5d+F6Q
  lastmodified: '2026-07-29T19:19:22Z'
  mac: ENC[AES256_GCM,data:BWkyf9Fb97mJusp0OqBPOk0+gDS56xdFIho2dnIOeLOKQ1d5F9bONpXbyHTbE8XeJ9mOhBhXsbD4lYNHo65f0FpHzASerp0WQha7GSCIT3XGSv7AZCrx0BQEm/E447OcSm9NsInOIb6V1/ZpufkbjumWeIYckFkFGPdGuLGUSCc=,iv:nr9NbyKvLULI2QjrKAUqMSj/gl2PGZDALWZvkrEx/yg=,tag:xMJ5Cv5BTZSesOR9d85PxQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
