jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:PVd89M0JVdcxL4iiONUTVdPKH2SStvojiHkfB8exLPhqqIRRobgeGVI2lUT5Hr5S6xZc,iv:qOLs5KTt0Hw2GFsY4pf9FslH846JjR3RljFyxhTDhQc=,tag:i5ajdpP7UsFygdiRbCc5dw==,type:str]
                client_secret: ENC[AES256_GCM,data:7d/luUm31Qqu0BsA2VtAWSO+dSyCygOU+qVyFgVmcyIkGjfnGM14uSkOvKXzGxko91wZYPD4PS/7ARATNvbIFvQi2gfhH/WY7F/IRb1Pe2DaS2C+sOc=,iv:mYNo6aKQ1xlUzeCxcT43nG0fR7aYVy9T9U6wMHaYrhA=,tag:81vG4RFz36xK+2MFmKfCxw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-07-22T20:38:32Z"
          enc: CiUA4OM7eK2iloOOLN3J0ojxejMrbHjdWSaMv2hdJ9vZrU8frflJEkkAmy+eksspLBPExrA7gY+66LsQQJzyS8eXvpne4YXnWgcN9Ru7eA9TdHS1DkAlxkl+lUdcZj9dNwkRDjwDi+Qz1Mx8aGHJh5i8
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-22T20:38:33Z"
    mac: ENC[AES256_GCM,data:DAqyFAdNF3uA8dHPXG8XmC/BkH3gLI/Olq4e/C2lXGoOTnDjJRxdVjfx2PRI7BoNWqT9MMDs+KMRLIbgWohAZB6tA1J+Fvxm3uMhn6uoUyunKj0jNBV3hEI14/Qk2oMY3QIfsZYecT/4yPcX3k9bZhr0NZ8o4hHp4f23Y2GkytI=,iv:2vizm1FkqRn+GOy41va/bmH8eTafXIMHuzKkts/gkL4=,tag:bEbSqI2xS7FjnJewle4M+w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
