jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:HVzVFxaFJ+SKpXKl0FJ4jzh8dnV2iG6kfv8VRduR9owbkbkIKl4Z,iv:omA3/QTWnSThFnY58rOq57DZhtIpZpWvxa5wqP+Zi4Q=,tag:qN+DrpVqsPHuqso/mSwt4Q==,type:str]
        client_secret: ENC[AES256_GCM,data:6foVVr2Zi+vnOHUF2Ush3a0Iv2y3wglKBmyPcrsRIEOqfsEbXBwTgA==,iv:kBoPzax4sFiOzC69BeZSLt8v0aBObDfUg9CJ4F9c2Nc=,tag:rzuyV1DCvfL4eZOhDxWsJw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-06-25T18:57:52Z'
    enc: CiUA4OM7eOrhWrd66XF567A8ZE/EDzFjgmbNF2od+p3IFOmIkd8IEkkAmy+ekgbs7r2arf8sBYwDOsoD9SJ5l2ybORh8bHqWYZyJpd10tTLQxEsftEsYeucSf2yAj/FHlbJQN105Jj7SzmVYcALfOlkF
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-06-25T18:57:52Z'
  mac: ENC[AES256_GCM,data:Ywt24phINdnH/QBH7COj+McV/FKNSXquyJKRcJy+RxS+nHVaN8LAr60gWMD1lPN5D7UKXo1VwxtVWtgWVE85LH84p3rK0EkZZIx1jUZBfZNXKK3z+dzFUu+yqhX3jOWOQKpyHEgLKuBLKzpfdVDPQdKa2MCYu0Gd78xV5NTEfJo=,iv:d7fdaTh9isLLP9HD5InY7Aebk/7PV28dZ4VYdYbjGO4=,tag:4VqAzyPZqnqfr2lu5yAGsw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
