jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:10+mwVdO/RUZSuPJ4TxltougJOq33L9MdacVXAIJsg0Rp86xM+/tY2KirT0UBfXOSHDE,iv:HP7P4qDw749jdhplVYcilQHJ45kFfd/xMsyaUBBNHXk=,tag:2xZ+CrZCzUa2EiRVH0a8pA==,type:str]
        client_secret: ENC[AES256_GCM,data:Gym5DA1tbggUKUIrzkGKFqWALZfheTJrd6XMyckHKGIovcxmWiq9sbTc2RAmom/TDd7QOSZNIkAjQ/XFJEeTQtnnlQeiJs6KH328I0zB37vyS4NiXrg=,iv:s0qSqkwmNzpB/IUP/KZem0sCthkwSRyfPYKp3F8Dz44=,tag:asAfxFzMir+YOiLS5xHKbw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-06-09T17:00:42Z'
    enc: CiUA4OM7ePFuvzaCwzmiUXTQ52s9kxJSqBjekQeItPWjl7Q1LBb8EkkAmy+ekqyLSDKcYQLlBuOB4RnOcmdXdn12b6efFUMGIn9W0iE3CRKkc7PmQwizPx2/PnDUsohJK8zWhD6zI1Ss1W5qPM/mMX20
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-06-09T17:00:43Z'
  mac: ENC[AES256_GCM,data:NdgcGJeNsCEZG3OGBr1eHfmRxhl+78FBRLfdFA/ocCQfETfGAOjaGmV6iCuEJWcXwmVSw21G3vJiPGu2uQ/xXcfGoUXLzFncLF9z/6ZLF31a2uiBxMxH3246NPpliaOLzCmNdvjQnQjVDu5uwjTNAcjX+r2b83hMfJf/GsUz5Ik=,iv:abb++9Y/Sr8S8KYNm6MckCdGcB3ST4W5lahqVNyHOCg=,tag:USCYVxOZ+ZhkO/bgOOU+oA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
