jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:e+cbjje4YmFRFoqvNw/FerAZyU8=,iv:vrIdM4EPdjYT4/+XFGAZUNxosh6eRHnprVWcrw4VS6Y=,tag:tL7gPrGfGNMPWQowlg+cQw==,type:str]
        client_secret: ENC[AES256_GCM,data:2dpyNxmvaVUZQfDeZlDbXQ77M46k1qWJh+YZeseP5ZegwQZtQ0noSA==,iv:vx9m9ZbeP7qhmbWB/EGZN/ecfRHEUTdAL0MJHr0g8jo=,tag:X4wRCAppkb0Kd+3r2eMZFQ==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:LWRBy8ZPsbaTYExxN+SZhaGXExLsQBVS+hSuC1E58LGDofcmqOjp1Q5yYwIQhGSqYoKxLplbRg4Q1s9g3bqO9nLR1bcNR467eOLPc4tsmIZQWO7AqvU=,iv:P5D76Lku0JVKQvNlj/CaApQXZvkzx8oYSU4WHZ5xA3c=,tag:3VIP04bago2NmbeGs0jytQ==,type:str]
        stringData: ENC[AES256_GCM,data:/0594VNo4JiV3CEOOc0Z0Uxa/SJcax+CgfYf8oPUZRGpA7yXL8eGhRoK9MW9Kfa4Z2OFWENc9FqbrUizAbgXfj13TdMiA40qJAcxB9yX38eY1tX959g20x2CajSkvG3Qx7tsE4H7giOYk5kF66qvxyn1OZEyjohRMfTijJ7Pxu0+LeXiO0SL4LWe91H/ZTBfPUEe0yysSnVJWlCKM5DZyLwikRTunlPPCtrLQMyI0/zBR/XHikANnWQfsuKFPMStoYYao4bffnRv1K3b1d9diBoPlTFVYypPPU4ZrwCqm9Howx/V9dzHRQZDQoRnDy+Ab6JJ2JbqG+PzZR1kwoyK+KP/JNWbGANd8G1WrwsQoqkscwTQ6EzqK+ax3cJUq+cC/JUCiyxv7gcBjDAuMoJsOdAo2tDLBqe61FzOQJKsTyJ6qm4wT4egCmjDWK5BUM1u8F4U/9XYaUSwXsx1+fyRH1jDkQAiHNpUp7K/kfCc68HfB+cdyG1I5X4QLKR7rcWfHGyp3ydU7J0M46l0fSwPP7wnpKQYuoB9PhewO+xchlo5oLA3pjOqysYZR9qV6ZmGF8vQM0pmOFefGKkSfx6DN9gvZRvzi4aRh87ShxVcn7riAGRRdm50QbZo+kn3TB+flDKDScDRw/drPZii7w==,iv:R7BpE0I0BPP1QT7c8BFd9rqTEEO6fZR7BQqgxj0pOis=,tag:IPuJNr67ZhvP+UIrORztCA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:28Z'
    enc: CiUA4OM7eBR3ux5+Q7DMZq24BJlGOx7/f6o6uP36sM2pGUnTgVAxEkkAmy+eklDcTSQuhkMYCXkskOKUi+EN/l7l5wlLC5sl+Wlz7a9ii0zhEVLwj+Zj46ClKSw5QzrhjyduVaTM71h48RH+hA9mBXPN
  lastmodified: '2026-07-29T19:19:29Z'
  mac: ENC[AES256_GCM,data:q0Ftbp5do8qEELKPvKP+snnbeGr0wsC9VrSoiGMWJaKBC4nXi05H0mzfJMh7y0jLcsvmww5qC7DHNqnjycMrum54ZfC9WQUyFhlIuJro59x0J1nRpmqRld5TQvPyo8nXH8J2OhROrqPjzD8sT4+0YRV7hAs2oCxxpaeWTsT7p7I=,iv:gD2/vbgsySA+mlYWW1HBW2ZovfvcqP5woj/vdxyX7XA=,tag:cnZ1mztYK9IE1D+aIRSyBg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
