jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:jN/EatBu082cVyemts82jE8bQ34UN5N3Rc1Azi3wlvq/qh9i2MfeqzbS/AFUXqkXPtqu,iv:NG5U7+g7iHmrHQEt9BH4h6OOqtgTIgYRIE2DoVDYBFM=,tag:+iUXc2LWkPsDXVNvFBtjJA==,type:str]
        client_secret: ENC[AES256_GCM,data:0A1Bh13wtLev2DNe6wFvx5m+SwmG3l1t65CTUF9ABjqfwTZC8IVuel4qm+MzdjkL95O2TAgcJzW3dbuXIVUB96293dO9UHTJcvUGnWkhjObMloQKftY=,iv:mSlny1YYp0mmW7JR808DETrZqq0nZlnBL+JOPLxaOMo=,tag:rzAGR1VFe5FkfTb6qRkVMA==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:M31NcGu8kd5G6hnQ+gpDk14KhrY/z9MHLU3TFyIl3EJcvx4UEHyKDszg8S5AEC/3y3HFKsjTb8BVYINscCBZ0g==,iv:ZMVtUBxqszENrfwnN5Z6JpKbEwc2F95mBOITsWI5VMQ=,tag:bpJKXHKYwXaUvZZpHS26RA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:18:25Z'
    enc: CiUA4OM7eBfAfXJIfwSG8FwR2NLjVuj+wOrldUJb/AOnMRN3vUPFEkkAsHDEl6dIDTKkud0ni2XNvatNZzRToxWMdcPJLkNduu3x252g2JN7BWtPuFjVEYRg+viA9hxAHye1ZDZr6qs1suZ44Trybi4d
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:18:26Z'
  mac: ENC[AES256_GCM,data:P/A4ke5s0SMqhVYZzSP78idC0mldPRie0rr9yWOzAkR97zxJ1sQGK2ey8eIT5ie9ajPkKtiMoppahFXCXFbZoahRb1Qb/pm0wN/6G6gu2qALSeJFZXgJCPjEytl5Uwsph/qSagBFAQniXHusrT08nYT3Fx5ZTHl2D7vsfOosnFg=,iv:p4+4me9c3n78gjkuy8ICs3DNW08XG4SU8/IGNpuV3Ng=,tag:vc6leDH2E1UrcPyxqSma1Q==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
