jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:wGrclrk0lVMwBaK7F6G8b0fnRaOY3w5fWg3MlC1IkA1EqaVOz8OUUmTk1fE4yT7GMrS0,iv:SLdqzyQ53F/0bvJTBaLuvH1o6WgoXLHZwTbBK0FYhR0=,tag:l1LK7GkwFHSZktwmHHJeww==,type:str]
                client_secret: ENC[AES256_GCM,data:sYtAWuCYK3dC+iprhHrgLlIaF+8c+75BTGnhCeIFlwQ4XmmyRXHY+mI88rJanVFSlR5RwBP32Ur7NrHBaESLDw2O1Bw4xcbs5s+jtey/JkWxnHcjdfg=,iv:NLNEgPLfXlEyxEaPbnuOn7QecPNIFJKOZ7o0qb8BU+M=,tag:QcibRZHZBpo9nT1/e5sTDw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-06-01T23:38:14Z"
          enc: CiUA4OM7eMiaXE7yTxL7l+rBj0vlbkWy/tiu594qPr9uxStTn8VYEkkAmy+eki22no2cg+HD0BLEOuLY/pWhgX7CGtMLjEW5D+hf24ZMYBtuUaG2RgKfIJ2hCCJb2CdgjtW3516v2fvM0vbW75GtbP4I
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-01T23:38:14Z"
    mac: ENC[AES256_GCM,data:9Je57bfVhwkkP0+FTKvX8WTxHJ/9oVZIf4jr1OYAL76cEuTeFqAhhljGefiFb5Kt9tcR0N8t2EOerqSc3PgYb36e2CmpwuAmWscCn4HM1eYhFeq0i+Y1SNbOYLYcv0Sgmsq0/AcLBOx2o846WQ+AxQmxE0hmH/THfME4QS2m4Jc=,iv:mhpfVZPO12OIJRGTYm7Qet86ckUyzykZYt0L3BEnExw=,tag:JvcjUSWf1XnE4nndSVRnog==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
