jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:i5UXNXPxsbv2KnmbYSFigM9WLPdBU0LgwOTP2PAQBMuTlLt0JS7FPEiy2o/XXtet3pWI,iv:QFYwDt80m5n9GFWIEb+Wp3+DBM9kssEXCO17+N8BABI=,tag:H2hYvVG889xJ5cxCYrbaIg==,type:str]
        client_secret: ENC[AES256_GCM,data:OtMQBUKW5FdMToFQtJGo4rulbI3n2tz6ewFDb/UM6CUz/COBukxI5+KYiGKPKBbbh6Pj4G04K3ppPRlfv5ZlW1rtEDp5Pjhx4wzgPq9VJ7WN93CHeXU=,iv:ddTsoFGITtyl8UXYj40JlDvyqs0ZbCnWoicHuEAz2Cw=,tag:AI7WVywp12EyfOWMHiJzHA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-06-19T21:45:32Z'
    enc: CiUA4OM7eEsK7ZT/x3YLX2uiRD0IwQVrhjEbHhZUnaoUifgi/w6NEkkAmy+ekldredG1zYZKsthzFsJSQAzGQNymthyB409FTqSSYQjYwTIXfa7+O5HArJMQSbRYWNVnjq+qq+1U/s8Ni6qyqVCgF7zq
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-06-19T21:45:32Z'
  mac: ENC[AES256_GCM,data:sVMnmpKiL/vILLsNiKA2HlWV4C7yWVj7HEfWTVVkCGVfI3Cn8JzHvO6FdBs52vCcnnrnS3kNsqHd1arUcZRT0X3NonMlkrdhC73upYCaOIqhVdOQcokBXxz467fPBy4rcS/ALTo8sIpqftsRXgmJxxbvwj8723+wQpLC1U33CH0=,iv:nG1Ok1v9okLRxhkcoinTJOyGMRtCcX1ZEQhjVtUiCHI=,tag:vb54mslFzwb5a0x9hT3fNg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
