jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:7lkC1SBk/zPA4Y0mcLVbHOP55glT5XXBZ9E1QhxQhIEsTO/GPXI2pPp4k5s/h9hPcTc=,iv:/qSzsFJ0rr7iJEioVUNyd0vai8WtRHN1GoTYifV+gTY=,tag:dnmn7Q79KDmFLr3o8QU2mQ==,type:str]
        client_secret: ENC[AES256_GCM,data:bCF8XbsRTUdnoIqjVjqR1bhBp+qkGJiSTv0xbMblwn37riowwaD24Wsxqt1AiUljY2Yf/K+secOw9gbBQqT9UZOt+ZXKghjiyfALujHGadDlb1pqCTs=,iv:8kgjdYnzO0sirZpHHamStBBDfgbMQub91zDKcUHGDKo=,tag:DoRtD7cCxeptn3PSrOmGsQ==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:KLMd+rIStDdkDMZxW4evZHFRMgo3D6xMpyxk8pcqaZ9IEtkP1Ri42Ajp9xc32Iio7yR9bd6azs4gIU2ZtbfjEuzHWZwm6JGfGRfK6+oeqK7WQ7QIU3s=,iv:ZwR+6z2c33zmvJ0uvECcPmgOw5Ui4FKXZV2uQv8D/ds=,tag:MgAtrm5TtNjKi7t5H98t1g==,type:str]
        stringData: ENC[AES256_GCM,data:jBY8UnYWlcfrYRJVORL7RWYCUdd35WuOCGwzMbT9IWavI3O3y3Oe6mJYCPWhz0YIkseK34xB74o/URQ8g7tqVRBVEmyCbghaSGQTF5ayfQ8H6646FRtwKEfBcM6AdomUwZSsfp8r2m2VlrITQv9r9t+oaaB25gCHlQX3GLl0TJHQv0S6Sxo62uwxI8manB73+B3+lcVUpnfSV9kQhJoo+uO1q4jb6CpSc3DzLfIxuDG995pP09T2WBWiPBaqaQwvS9ToDcpiATUF9I81tCRUXG/84YD0udxwJWzTcf6ybSxBiMkGdj2dXBkARlKUyAk58jHBP+XMCpfcD+w3Efs2tC3qBp2G7h2vzVuXbzmdv8CqimTSHdpyWneeCRep/VKygYccMghryxZplSLJOjAV6wnoY3tLb6HLLJVpq5UPddiSFBCkVOtxlHoexgmv0LSG5JVI34Bhc3yfGo+K7oI7UEwc6kpISrielKQJ+V3eQGqJ4tI9qb+Zy/2ZoPt4ZdD6aGDP/63y+yKi6ntIwLozPzyRAh3a8S3/vt3LmKVanwf+aWzskdxijE8G+J1xg5Y0the6O0kgYKEFXIQeCN5rJyRCmhzruJBVQB/1MioXexviKTI/XchiXw/NICy1bQZ2+XbdlwNK26LZQ+7JaA==,iv:v84Vqbssn5Ky7rS4BenB0KkK/hdSCwwvq23VRUvyjiQ=,tag:evZz5fIYZEDXo/D+Xl//Hw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:17:47Z'
    enc: CiUA4OM7ePvhUmN/DVbgyCJrMztEbl5TOsbJ/I5EJOVhWnDYU30vEkkAmy+ekkT0GgaIRwmod0o7X/2CYvsdWepGsg+Y/8In2LaMZz1Q7xpyJ/XSpNapSLHOkUtMwSrmWoYYlXys+aXtNVBrduZRfbBB
  lastmodified: '2026-07-29T19:17:47Z'
  mac: ENC[AES256_GCM,data:uL2rsXNNWEFA91llz6p0IJprV/QX3fwD5DzWfLqO1dWDWc4fr2m9A7HkZrnSKM5J7fCmT06jAXjiSO0oeuCtgrZRIlSaHR4XTFF00AGoyppQY+hZuK5miPgjQj87obNHgCUkasRKlHqhCBoEgXosU9XrE3+3bhDzIPpZpLsDhl0=,iv:xvEmfSPRMVl9vicgy/9f7iwqT8W1AEXPGRMpCxtyNvQ=,tag:1BbrwE+pJzEVb6YGKmAdRA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
