jupyterhub:
  hub:
    config:
      GoogleOAuthenticator:
        client_id: ENC[AES256_GCM,data:XL4YnQ02/YcrXaPsyvJblAw/pZazOKU+UHMC1i9ULSDiR9ZVYw5oqjE2R4v7y8yK4T3i6UqQOrmAHfT0SyPNT0+Y31zwwBfT,iv:zoWZNC+ubP4lOtKlvtBcbvHZV1goJ59NdfEyKySp8ck=,tag:ZUcBLqQuzjJieZ9zh3MfFQ==,type:str]
        client_secret: ENC[AES256_GCM,data:fCaZ9v7RHLyy8FiLYuhEnve0QKTDoXTgaMunFFzfNFcpnMc=,iv:ykBuwgUM3zvQSzfBKX+78BGi3akvsxMYhAdwIMxQT58=,tag:DqH3fC3s6Q8PI/xuFGdlUA==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:KZxOnS9df0ItzxDgwKfBorkzCEs1N7x79JXipAsDo6PK17SzjsWzMONnZ1AGwm+8lhdQQqK2j0tqdoA4wDrXTJAtIulbxRSKI+QQMxLqer+pi7GxZO4=,iv:nLO5ADF4crPFezgWIKjccdCEvNOXD7INqqgvJXLX1qk=,tag:d5I85CNUiyGLIxnPO80AvQ==,type:str]
        stringData: ENC[AES256_GCM,data:iIXeXer99ez20la/R9gnOXravDCpMA8owzszGkhiF76//kvFQ1KRB0ICaRdxObF9AC7mN9X2PzKa74pL22BcqLNqtgrzqKZH0xAXZuyAzso2muwYyAT3fxIQe2wycFNjnRUwiFMTjmIPIB55FGgk9fOle/hLcgaBsweXtCh+D37ayWe5Fdod0I1sYu70xtrsGcE36/+xJGCgqG2CSrLn+6bIUga1M2gg3kv8zk0+ndnBBXq85NNSYxb7HG+uJMQbrIRKv6rIPUPmVDOy0zDRi/YFLqP8dD4dKN9K7exykhKrNfSJVmgiISWyoEEDBVoE3X4SPvoRtWgOb4pp5ez0orXEFp70l0RLjUJmbaK7Vk2IC0AxoiGKGq7NYZAhTpmIGvQpaDheLonPpkiF3slxY1vjTqeRL4zkdp845oPbI6gqecwdXvniclEM522bM3EDC1fmRvXnu46p61XYS3FP+wQ/4pcDSRITuFCd5gbszjnfiyHb95srmYd9PFoKOSCqxbj/ZudJ93jv0/3RXPiDpEu4Hx1P0qZiAVEPtpjx3u6Yt3n/BccUgJxT76Yyc+hr9mS76XmUjW8QCKI8KwIXsAUFQR0qrpNnWpxRjhL3iLdZuntlritdV17jV1XYwr5o7sHJqQQ6cRQSr4vF0g==,iv:HcIBN42pd4v/kMeWv6EAnj5lXooQt1Wk/FVVEGJeC0Q=,tag:OshXOtmedSlC8rNvNZ3QKw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:35Z'
    enc: CiUA4OM7eG2WzkO53d0+T6ZE+gdsAq0Rl18uBr44O3KFeFz5ICNIEkkAmy+ekr/fcYIQePvXlVI9uVX98olA4Xmvio4UIqmRhcwpQ0rhxsqvTl32VyLxA1vj1gcCQZw+hxmXnOeLPn1U2lOk1Mh/tf1Q
  lastmodified: '2026-07-29T19:19:35Z'
  mac: ENC[AES256_GCM,data:jAfsMXBzYoo27l4H5gTB2yrFir2fmSFl45/hb1ORKoVnNiFJgiljEt9sm6onvu1KRW4ABjTOEMh597qLDVJkvDacjsXpMAnxwY1fawawTvokVN+ANK2ksBEaRTOrTvViF+nElZz6uPkVXNzcDjG+Bh0sF9Q4fJHg9ghaJDW4WI4=,iv:/odH/3jjZHAYSeOY2+9xyd9i/PjIvm4Oog1N7l5vK9c=,tag:8o55/LDKEjXPWf4hv8u44Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
