jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:KSfPUH4i833iHaNkGi38ORV7DzbXwVCu1KCY4G2NDF8gnfG3IAbNPOKhO2ZcGdzPxS/ul5RsCfeTX6iXTwiR/PKHIMlYEJqr,iv:JLQyHwXn8DByRPgXD+eGnSmG0k7VgNaIk8uaCiBn0Lc=,tag:qLcGyQiNkxlwSMKlg3Woqw==,type:str]
                client_secret: ENC[AES256_GCM,data:HNytFNC0SjSSBBDTFfLlHg5Ekdr6Vu7fUpyK94cIo/8d4p4=,iv:0lOTKOWKVLpg8yzaOgHoliFmh4O0F+b6Or7VkfuJ8uo=,tag:l9fmJ9Ta4rORhx79m+MgKQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:43Z"
          enc: CiUA4OM7eADR6UHyf2KbV4zguFzBnrLrKqqc+m1mhw8J8Zatwv+lEkkAsHDEl0Gx1IE8WjsGy9QSDDjZ1I+AQjlsvnQQLoA7KY/lmNx3CNXe6jBwNo9jA21NCkDD+gHTS/SUkcooBFxXOYjdjd5kiFeC
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:44Z"
    mac: ENC[AES256_GCM,data:B/oy25RALAqXONBqRvaPi31FdQU8+szywwux8KsigOiPRlRR7V5fKujxXZju0MDEAxHNKphofNxVpQZRSYT1o+bQQX+yggE2juTQZrARTtqgJ9pAfI2k4wQWV6LW2/O0+8oJPpBY32faXKvpqt8xDoxMrxLKle5VMGkIuJMnomE=,iv:DNRrvko0IFGyuTZW6ItHgTbW6s10+VoBZqMihK4Wovg=,tag:RYKept6eksYPXIyhu1Kk3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
