jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:/sn1MutWeZVf7AkK6QeUNT69RZbcHwPPjGLgF9Uas0mY7uc5JxEm8xhCT1QuGChMHYje,iv:Sjs+2kU5cjG28mHDFQc9XTXgpC2yRLyjXxyUWhIH9DA=,tag:+gCLKTD9+6DIdeKNi93qUw==,type:str]
        client_secret: ENC[AES256_GCM,data:P4b1aXNWn9lZk1tkeqFtSguKcttfZOafhXP7rhNcwQLfhsh2pqcQErdCahQkyiGszV/whHf3xIAYLe4RQc8I2rM8Oxq0h2NcjUZqyjlb/Uu18mOgASk=,iv:Kl6ZUWhfGXth65ITNJ6jNE75oINPQGr+IEFTtMAljp8=,tag:cHlazlPlniw3oS/R9Ue8vg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:21Z'
    enc: CiUA4OM7eBaiB8WzOKn8XtbfbJHI7pEroLa0SWde3ZBcZAqnG/aoEkkAsHDEl+vnOHbTp6UmxPxvEwB672RNzUprC3lkRHRM1enic6/BRuxqQEIV31V73cPqdtAclCrK2zGK2v1tcCKZKI/v9YwjzyiQ
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:22Z'
  mac: ENC[AES256_GCM,data:y8D0UpgyAT2AJEPXXI+DW0SO1/RHrdD1iX1mJsT0HfMSzdgrJIYZo56KXxAyqlNy69kvDPHOUf3qVVaReOaaEmxC5axp+kw/Om8RtpOhw+xjZBr7Rk+58VuFnqNb/AW6DIHRZviXNFxQqkMe6arJhimkPbyg3SmvHinunH8iWXQ=,iv:8suxbFvl00o/eSXfTpohaWq1nvPdra8Ecb4wN2vCa34=,tag:vhbX/OJ5axt5tQBlb4SpkA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
