jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:/1HCN1HK4WzKAgsIxHqbzo8dv2l/t+Beay1gbFX6q/JNVLP9JaM3nuzxAGicnwC3RHjf,iv:/R/e0WMO6ImKBNZlelbq8vUyjnawTEsF1t7IQxVGhbg=,tag:wD49QVRgyjkeyulFMcukwg==,type:str]
                client_secret: ENC[AES256_GCM,data:masios1qkshr7eHK1e8cBklLT8zVGpITQaNMiCsv4ZSYBnPnWOs+k7/agUp/XTgclHvozae3cFCGEO0M+I+gBnNCUKyk8rzYB14nj+uzi2GOLgWAn8U=,iv:lyJp/JOn0g1rs44vtAZ+zjVzx8MyO9jndhO76Lqdps4=,tag:GWNDUgdO0+FhLfs/XJmGzQ==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:MKYThZHi2Os38KxJp2pVzfBwfe5Yx6iKscRdFfboSdprEE8UJKxBGMBny6Whwlj24clE9rsFdWtWfOMUasJmyw==,iv:3kT+FVrpz2SGG4T7aJ09I7NBVtan/9quLW0G1O1cWlc=,tag:j7kdVSdij2rAwmucLkzaDA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:16:11Z"
          enc: CiUA4OM7eIBS7tObgqWijIEXJ17P4TbtjMtQCvo0/ShZRLbFAjkMEkkAsHDEl1p63wYJlUzMJtZ1xbutnTryH3YpAYO+aoLh3VeJYzAH3rkY9+eeu5/Tg2S20NjjMoEhmXUTURbWWyq2rLdIxLCXXEKP
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:16:11Z"
    mac: ENC[AES256_GCM,data:Yvjy2hbpRVziE2u3k7oDPM6MO0kOn8+GJGqnlcfvsYg5mItTvV+Kez54h6eTEUHdwDiyxfxFicH6U3XD1GsbNes5zpUPA8B+qQ21bjCw83tdQROzTdwJBscuHXni6dECApLiP4aN4z5nXP79sZw7Vj02HPTRaczMk4z/JOzTFGw=,iv:XOmZxUejZikKPS5mA5HsyVqUp5YL5ObLyOGJBF8fUUg=,tag:alRwzw4h6PYQRfvGeSdPCA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
