jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:HD+qdkwy5ajdcfAjhz599eYxXog=,iv:12g9zS4x3sVrE0+q8M91rYIENUcfSURRpBazy+QFoGM=,tag:96J55r+fACbAiUmRcTwsjw==,type:str]
        client_secret: ENC[AES256_GCM,data:OI/a05Z+cbhMdV5JuJs3HjNDSRBZDlPpbkRa67dBgxGi8Rcyg8k3fA==,iv:kli0d63iEX+H6B9ROfYY9yFSe/fvI/OwXcVlJ8IKzfg=,tag:VWxWfGEUvt+ol1+ZSilF6Q==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:irupwsA9kGozG65cYyZcJ2OuAikSPYwDMawkFYB7brslt33yLGfBPdMyc7ICQB64qyCysGjsYCFv4CdaM9qlBd6kopmyiMcKxHr5vK2b7o3kCRbjNJM=,iv:f7KnIhFjeuYFUxbZCu9wgFLnpWGASBVlUNh4lc+6KXk=,tag:RvgoCKHn8B7lHKV29KsQUg==,type:str]
        stringData: ENC[AES256_GCM,data:oZ3nZMjieN8ywp9BhCl9DTBgMOtgAsc4wWZ/RFvo1PoMY9LpaiJWtv0jbTyCV9+4eYiBygtj9ZshGKUpO4GGVZgLtbFn4PHHJWyNng1HXwLSfZ3KQ3rEWbtxgYWdz6vVn7uHl8W8Qiza3XDVcGJwKg9arF5v6/jLJiTEauYYqAgwnkpYQmOBcXVeL6YUzNeJA9gm1RsF7v1Uv8bykrNr5ZrLOHa6f5rCy318cARlkQfDb6Kc5teL5l5c5t76sL91ubGHXTgZqnO24gAZjVh4WnxgPAuey+aTFNa+FB0yJq1Kha4pBPWe0zOz8NyvHYNoyQXilWzKgkqqC4FHeGnYpkyJXKgz4XTWusXF25ddy63OWAc81kimCcuYHLm+6Y58GX25i5oRngwt68hoAmvQpNXM2MW2eaaAt6yX7hOMzvn8qq8z9GhLH8oLIXXdZLGTh38m4Zv6dT6iyuHa82lmcTw8JOIJoMTuekTdcP90NohxUu6mI/HXb2xlzAiKmPSDmOXFX/e6Da8K+VV981UfCrU9hqzDszpmuRCJtHrX/VtLmgWm7goeYAy9KTWFOWu3RIN4y8x9z71kaWlAZqaXi/s2sYnnW55hOba4LnOk8peYPCfa78CFBKMKyYn8uYbfFhjP4z1q8RUyQlemBQ==,iv:EisfosqPBvEHZKy84MdzMiSlbNzKZcgi0bCN7PLAykI=,tag:E6UU7KPpZGKYBTE4W05AHA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:46Z'
    enc: CiUA4OM7eB06aX1kdpaMmwPcXDQpYbPKXaj5WZK86jM7/4q+NRNrEkkAmy+ekhjkHC09nNCP7BwRM0w6MUMp96NaaMDUrh4IxRWiOt5QoUODObwYmCA4MP1ZTcfa7QfMKaOfVeot3LDPlS8zRMLdigvC
  lastmodified: '2026-07-29T19:18:47Z'
  mac: ENC[AES256_GCM,data:j/btJdHuDq+j2q/FdeXhCDXlzWVHIGUlZmipJodpKetzhSarccr9W74E5TrK1X3ZOUCBUKiJPboS17YAu7VDsD8v5Cgq5pK3mIksDAZV7hoYxK8UUdt5M6ujLNFJ3UNNmvhNRWRUrWA+po0l3umi/VcXB7+tpYm/bDWdchEMSqA=,iv:hCgnyXtVQjCSq03KNVCR8RIcVtjwCsgyHNGHF55TUNs=,tag:9ERUK36uThMG+PMK2UvJ/w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
