jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:V1vEDjEG+7wxMgoF7yniAV9AcxOZv0BiQA==,iv:DvKLtYzGuaRmBbku3VtUPiNawZeLzOSw1pHcfeeaSnU=,tag:GLfcm95cIs1Pd9rs+MtTpg==,type:str]
            SharedPasswordAuthenticator:
                user_password: ENC[AES256_GCM,data:8XOETiaGDcju86gVHnZ04LWYDfTyqV1gxQ==,iv:s+6XAuBgRinwesC6MfUdU1fYDTzkExaMRUwwIpgK7/M=,tag:Ej0y2b6la/Gej1Gfh4817Q==,type:str]
                admin_password: ENC[AES256_GCM,data:hfYb/k51bpUo7Ug5iafr1sqY1Wmih3JXlxSescIp,iv:shnFT6nuBMfVk33k2uxr3i1sbLfonDiVCLXmm7TF4ys=,tag:taRYS6APiN7xqOesQ/0g9g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-05-30T00:49:25Z"
          enc: CiUA4OM7eKnlhNhknMSfmN5r6izWbVTJ1E636TyFKnd0UOCUcWfWEkkAmy+ekuWMKlr3+lYYWDFrr7iCxf7utq70IYEXntWIsZIUk+kbtiY7CeWHI5hMaWahA4HLdYkeUcPetq9mhYwLd7qwcj6gYZst
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-30T00:49:25Z"
    mac: ENC[AES256_GCM,data:it/mMK7/Kvca54Qvcqsz3HO8uFuidJUFJLxbCD4MeYOJaI4ch9npXIWLMyz2vl+sJZ/5I2Rsmd40yLMV2wfrZZvPgShs6jhqKodOZquyz0Bih/mPjS8S/07X/pOYYPciM1hDvy89qfyjT6k60itZVMbZWkj5wM4v7kE/K3n6tzQ=,iv:6t7C80c3/TwBAM7PpIXtziYdHgykNKhWKCPOVPr8g6o=,tag:2FOWZavUyQlCeqw1enXFhg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
