jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:E5TcoRT7nT0fnVxq68cK/y2JVU9o33yGCCp1RRe8TzZxNhCrtthaoak5bGWkDOlKvpKZmpznJbcRRn0AaTsb10LyHi1jBMi2,iv:FUDdjHmF0o0ZSMCXH4EneqQ8JLVXi40vNKNe+F3AlLA=,tag:XEMFl8KBGQrd4c7p7we+5A==,type:str]
                client_secret: ENC[AES256_GCM,data:QeqKQdL3OekH+0hTCe79s5pRXX+TKQ8NZxMoTLYaRoqjZo0=,iv:trdtqit4/LVKsjfxJtEljpsLaP32TKN13GBl6nh67e8=,tag:cu7aJOJk+7XaUy67w7Zegg==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:gUuFPzNzEViQuoGo6bEhjZZ14gJOOWmcncQR6575EIE1+le2xnD0IK3PrG5ilFrqBrJIaBd4xKU24ghlXWCd7Q==,iv:L+pfFvbx/KUCDPy2rlrOhixpVhpr2sU01sxAprNgEqU=,tag:VBo2ESQuIDF1WfkKI94brw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:19:08Z"
          enc: CiUA4OM7eL6Dm4ZZrA1mf5CxxzkXV7GPwZaPns7mxZ0tmQzJPaVZEkkAsHDEl6J55PtPn9dVN81QNOMmduaK3JbTN1FeXUfV2dL+uRcpBjdf0U5icJfJ+xWSJ0r8vBaRySaprNhtXHEFaWcy0NjnJrB2
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:19:09Z"
    mac: ENC[AES256_GCM,data:gHVL0Io1skafs2hnzzPAUboShwGI2yZUCjHbZHuvV0ZNfn0HiOtJj+IXOvg2BxfSRbeMng2EWZAN8GtiNuJ9Wr93eSPyNW7T8u0YC5Lo02xVEwXqEwLaOwmKGgJ04BNlWr2sFN3G6CTIzrjW79HJzadEodgWnbWK3cRn05EbnCk=,iv:JmlIhfjpLiUxdUNTgyWK6V63lINp7jbRb2cvV+4FuVI=,tag:1pXfe3MWk7DZwMORJBgS/w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
