jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:UFW5cPjqqhDIdJXIIO7JTf6RznEJQGVn1cevKMJPOkXOWtgjkGuoe2sSA3EiWYJ2Fltq,iv:XlrC6ZJvWyJTV4URTyY933erh2p0boSBHbbCaq73tgA=,tag:p/d8EEcsr6jVnPGUtJDzyw==,type:str]
                client_secret: ENC[AES256_GCM,data:0yXHRwZKZcl/lkbTgirIdVe0o/9PRfvbkCO9vR2J9DFgMS4wTLI4I2/4IA9W3jzToAjlEQlrcAPsHUoCIo20y3wEtWxCciiCY1XvvcfZIIOmV8N96mk=,iv:QsFP7U9VrueaMQyHvqsBPkgY0H/YWTNhgaSACbPUveA=,tag:ek6KvI76T2E9e+af+bapNQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:12Z"
          enc: CiUA4OM7eAqCKnQ6yL+X2u8vXWWKtw4yJTUWmQQywSZyybIFwoceEkkAsHDEl19HMilr24bZlLbzoJIuCSDfg+W6Y7mpg1NnxljW72DXFfu0NJq/KiZ6X7mY739KHrqduGfZC1gR5qTrFrcE23W8YRZN
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:13Z"
    mac: ENC[AES256_GCM,data:E6Ul8PbYzl2Qlkz7lfXxIJEeqzMMTk2D9BKgNzjjVlvG1C6nAQ8HHgweoucQaMvR3JYxHwkhaUycpdOjHDiakcJVs8Hz4TbPgrUu+xHBHM9XSVTfQgf0j6h0rh870DYPZTkepUWHHzC53ncgtqaQIVr60YfGd86glYcL+E1wQAc=,iv:oRlWZvBdebeJZ1olpGj2CCQSBqGBaEiIlFUvAj9kdkA=,tag:1RTtmAdhq0YhD0y/121qTA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
