jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:qxKTCTnAa+8xWkv8YtxBhhJa8I+KMdz8RGURCFU5zyPPPFMYgoQpYKVU22YMnQE9sdkP,iv:JGgpqCRxFIrEoxlu3fNb1yTuBpKgIiSCJMOVrCmV9aU=,tag:V4Uuxl1Mmnp/OOrWL0dyhw==,type:str]
        client_secret: ENC[AES256_GCM,data:FfaAUOHNI2K5byQ23eYJsobFCkel1jRceR9V/Olt78LErdNiR0d0Y7xDe+c0Ez8fSxobNC72YMcGl9QZ5Bug6a7wUHHojtspi4C8H02hyFGlAfYHyTo=,iv:c8BlBBrQZ0o+FWXAWh59tJPGn/mHZsnyRc9dWmEZKWU=,tag:Ze3tgKsoiEsIJ5fkzAjDEQ==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:H8AHtT/n8sARjOE80SJ+sKxH8w3Skc3OL6BPUn1texNa6A9HWM4JQldqwE74dzLDPv+hdkuUfJ0VIb1Lf5MjmptbIyyXQ1K0fGYQKPskcIbiuOf7Hms=,iv:yWodGU2+bHxEcI6tfgGHRmoTDdp9Rme8WMnqmmhSdeE=,tag:dUyma1YkMGDdmeMgStfh5w==,type:str]
        stringData: ENC[AES256_GCM,data:CCemvawS4ihX3mVhMIZNrVJPRp+fpkkmeezAI4MlmHUmaTmoeg6WvOwJgGPWDSTf+UI6WNIhqjUNqPMwakxkUfZwdm/kTSy4NeN4f0d/qZWNRLswERiQQvQkPX2PBmX4Yp/ExvNyqViKN8CvqMwpPP1I7s+vHm5ZMB625aEkDdZLAocHgXcomLIpIaAlXM8SlnnOESrRYV7ldX4rnWnucK9iOBph4uRvnKrD3acTeus7M8gtMMLCdwN5kZMOMwjUlMfxC6AWN0BwOcohrG3XD3eaMaPK7w1iQ/aBQJU087a9dyAr7+dNlLanMtIJxEJRQCJwWo5xnswsHtSUCJEIar4JGTW9Q21045Ncwh02FpLlwEAi272+dZUq7J66F0LAzRkucykObiioxXmCo//gAT9ROe4fFMlXszHvucMOcsEYh5rf9NBT08Bu9jhdvg8GCpgPKDvM842zBDgHJ8P0jkU7LTVjzb0vvViUSWfvWlHvsvIdBf6gFBGgVVwRsHs0E7AD08lB7ZckVn17vfkf+4tv0ifBz8JVm7dnO1/RK/9zRDig7u14gmxben3DlphsenI7PlOByijq03OlzX702uRR5Zd3e6fgPQNLedrfbsgOK42yhFQ+bUChOyGi1jJNP+XX4jhVbkdXM4G2VA==,iv:0d7Zl8e/LyIxWUTHbLo/1YUSQ9jZnv54na1JEx1gomc=,tag:JiVrsJXs/c8p6rnUk19LaA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:25Z'
    enc: CiUA4OM7eEW1t2EF91WjKAMtKr8LXQm0PvIIxKUwaUEKyg5g7FpqEkkAmy+ektiJ0IV6xrzKGLqnpDRrd0rJrUqwCDgZjiy5DzJ1usqkqz0JYfZ2Y5m4GGdfQviPgdLilQ7FV2H9jC4MN/hU5WyADimy
  lastmodified: '2026-07-29T19:18:25Z'
  mac: ENC[AES256_GCM,data:muO7UZ7IYsVFZ0yhSj4COf2wRyuFDXhsIyEXjaCvNJTruE/1Pfwbj/9Cv12gmhmsF2UiUSm1kLc6BU08cYkyDyqEA762tlra+CoyHMfUimHaAgf7zK3UlC4UcUyXzhJfcW7XOM1AcKqux7OhGIDgk3sf9OjJMHnZ9VRzsS3ygM4=,iv:Xdd9yVGkaUoKhwHyqH/8AlMlZY3rYqgmniJAVuc2BRM=,tag:L23WRWl1IbWah3ymxqnbBw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
