jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:znIMRRfdPOq89Bu49kh1IpOzkYYZKdR0i1y25rUeI3CIBk5LCxNBAIphqAhh8xvt381a,iv:7vGCO7lXceYWKWpgnnoEQjxp0lvw501hRUT3p3H/F5I=,tag:CiU7eD2EcVbqvr4Wmn0Vjg==,type:str]
                client_secret: ENC[AES256_GCM,data:ExnvBzebZJhAmpVzTuKsMggf67vShl0x3xHw189sWh3Q0Q9McY9C5tfELYJVwUtXTffsuUsWYRCIacV3xli4Y3u8TkNeScMPlF3+WaLac1pmChZ/9+I=,iv:OphfU1waOyXBWvww29GstkOoMA6KPwvqrfN4hMKmpWM=,tag:92tXZYH8pvYJ2yW0/4atLQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:41Z"
          enc: CiUA4OM7eJdjng5L7hzOnDMwIK6+1aa/5DQ5FB5fuaGqGe++UxmpEkkAsHDElyh1hQ2RpJDfItkMu8s/aAtwhZQ0PAqK8oVxg4gwhErgDfeZpJ7Huu6rDW7Ihr8YKphaQUNLsz2J1qg8eqFwQOlfuB/2
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:42Z"
    mac: ENC[AES256_GCM,data:3GaJyEIl5rl+1LhUTfw9itJwTDOEzKCHktNRkHxfk5jdPGwyJLkbGFdfGjnulWF+D94pFAj8heB2NME9vLAc+Ks84Awh7Q9j5EcCseZTnJTeMAj7QoZsQNlNW0b638s1c5bP9uUSNXdPivFnKvmuNiJLLFGC0SZK5S2Cx32Ttxk=,iv:SXIIJb6lCfOA1WPFNxo40NFLLFCEtUJhRHL9u7RwMBU=,tag:XNszWtvwHXZ2D4GxY9MmGA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
