jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:iWMTxaS0HVgfnv+r6hFsrmo+SsrBLLyPDbMdsw35FETUJJOUXBdNTU9J2W5nhCanhFU=,iv:q4ifkI65Rsspb5lcEsba76qW2/saGDJCPWoG3IuBSbQ=,tag:9tmlyr/UJx0Ercdkn92/TA==,type:str]
                client_secret: ENC[AES256_GCM,data:6l9bIZS7o5XgQRfqcx1u0yn3XmgvJHxzBbv51YsPIHILYd7euFlqXCaXx9PPPp5CXhMY0Ei1/O0LAYMlOEQyJM6KcXyTqIQq8bzWzhWOQXqxYvl7t6k=,iv:sjcD3Q6jQiovL4HTRu0VcjrNmorlCKRmNxnoo1vkIC4=,tag:UJLxDgzBRgVYG+sCOMrS1Q==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:LryUMnquywJxc7aTGGkEfFZEgvgdEwvu6D4wzVoXBHkd1/kwAVTWriADd4SotZrkqwNkMOP5mCQoR04fhJAfHw==,iv:oesKkKwdBFr1ou6lp6Os5EkLuUYgRKq0eLmOIDzCDEo=,tag:B8Ww4Z11ASF/w7y/kMSvow==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:17:45Z"
          enc: CiUA4OM7eI5JK/VCpY4tkSmm201hfiRCAo4pTYt3/ue4AQ7atEHxEkkAsHDEl06TdyNsEqETIEhDI2Ht+YgTG8+FcmYfa4osN7F4PJlXn+oiU9POpd169FsOK46XmHkdXZefW37rx9+hmm8kTfNL0vGn
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:17:45Z"
    mac: ENC[AES256_GCM,data:LDK4ughHCcDlIJB9tWuD4VQmA5BocLmdtPzh8/2Nc6sIlMDp7bisvDOgpd7lbZEXx5araf6qdrD9FNpp8y+O0C155iSm3lBEbu2KLOq5c8+22ojpL7tV0NOYrVBYrudoIqjkcTI9L4Wq3EqePTLLMBJzwC3VUvf9gG1jeSvbT1Q=,iv:zo/RBwN36uVnXds14z+KFJ5N9Uqcd3aeLQgbGaX6ePI=,tag:4+6ka7anDDwZfhCX8rLdeg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
