jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:eKBZ/6wS1Q8w/lYbTyguIySEqSnm1wRUmc5iaSOhyAa3aJiZjHKcvM5F1G/ENyORMDg=,iv:Sm0B6TPU7AGG1tF/hlb0WJVY2XsSYz7bUW0X9HjXV4E=,tag:PEaUzh3btRfP22uRtTzWrg==,type:str]
        client_secret: ENC[AES256_GCM,data:OQasrBb40qc4sA4dE96hTs7HyIl8Lc/9S+69UpzWeAP2tYyGCaUct+JUqVLCcrxyk9Qq2HRpbA29OUXyUrgdBF3zkvZCC3UDsTtiEdjeqeTjGzbNV5I=,iv:z+dLkPA0og0oCFXqdQrqpRkh9o9WMb37MdNCHQmsmFU=,tag:+ZR57rDhol2vTe9FsYYmzQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-11T17:18:21Z'
    enc: CiUA4OM7eNrcRFaCYZI2hZiVTmeE7pCbnOWjy1eFbSeZP0GdVNjFEkkAmy+ekv6xniXPN9FHn+JmdlARXyXfUgxDaiY6vlkOCNc0GHKNpPVNQBzDTPT6EqiFigJijmmAnVbTCkPQ2ieuI6G943ZLz82G
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-07-11T17:18:21Z'
  mac: ENC[AES256_GCM,data:H0NFRqOoRBFZTdIrKVEd6DjJYG4hAumvhzVo1OseOmXyijAGuXrTyo4kZz6Cbi+dfrhPyeeEA2V0romyIq/kSB99AWFYcSoPKDMn8kEzx7WTHVm0dPBBSLvsJBlcsF3ubxSy0ZpzWiAg8sfeLkm62TqLj0SFaHvO0ffealnrdw8=,iv:PMA6pTe1N31mvreFle4q9m3ykPDzXQBKSFuuRWZE7tY=,tag:ITdLvv+7XSS5lpwIO2EXzQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
