jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:CUsD/f0yT4uFZwIwZrIQN/vQwGyc1EXpIKxN+4fv6YUdiBj+vzXb/MlMQyrPR5K0Pboy,iv:Rq0atjD4zIpFnTEXC4IpgLBejLww5MxDcNuOgmEUGRM=,tag:3eFfe74zrQ20RZbWWYQ+kw==,type:str]
        client_secret: ENC[AES256_GCM,data:+LurNyuwWGDlCZ6TJohucUx8Dc83nV9ef5DXTjAc9CO71YuV2JLKWGIF5ZehNeMHGy6Pbueo/RCkz9ari6bYDXaNPJ7560vdIZmCzlu0nr6HFsjTQz8=,iv:OjwDTX1FqxD5vpA6pFauVAFufSGpaUit24NuFQapXoY=,tag:dKAxNHQmIneYv7fzbKOQsA==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:RpQBkcUSOsoD8a0791MLDyiPAq/9BeXQoWPuGuxyZ5XmoTL+4M/bxN58yuU5X2K4OEt2ML/dOBMhnwsvMXeVXA==,iv:cRwTXAxfzyRi3ZgY+EADC4g/43acHIqpCCA7jX60L00=,tag:w9DpyJKgmpFnRzG8ggwTng==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:19:02Z'
    enc: CiUA4OM7eNumXdUk2ZbQ86KLMJ0DfMdE9IOpkTDXXlb133pdu9B5EkkAsHDElya3ZPUV/3D2HSJKYYP8l3KyEMKnchqSqm1XNyB1seCUZeC3P+0MNrTT+/shZ5FyxUwCRSJ0ujmDzXUaLkIx1Extnpmo
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:19:02Z'
  mac: ENC[AES256_GCM,data:tz3gGefIFEILsRKl5wfdicdO1IMQWzszBf+FRZ3eEkKoUTw8KIIJfJXGhdMBLtsIwrOlnKW6myLQfpcobxGd5O+67GpC5fh3Hi5zwucpsmx4sVSKsL07Xo548bto9L19PIk/Vo0Ep7yz44bxTtcqNsYrnDcd0LL02mo3aDuJqyA=,iv:Tp5rzRZiYoDghsokrF5oLfsKEXqYIKvO0mBF2N/3kQE=,tag:TC3gY2nA3hy6MIYJTI22mA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
