jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:Aw6NsHuOvUTwWAqC05K8BhglzCuHj6cNZ5cek1UJhdss5SyoXyN1tjSd7qakJU8lRPKN,iv:k5FiK9DcxhyOgwSKXdGUrXVz4Z0X/EdUPzrD3XclnPs=,tag:fuStq+LNvswfbE6nAOmfKA==,type:str]
                client_secret: ENC[AES256_GCM,data:a7/fq95o2QXyDuBkF2qMvkkfiDJ/nzmPvb/Rx1QvSW2dILb1sU3z/VpvbU7U7b9d7UCzvK1xOP+R7VOKgpUbDs8sRWch2fnATETPbZqq5Fv9VO4rDp8=,iv:X97uaMx9ZP4UkeSA7ab/vOZF2TVoMOaem7odUBdoZhs=,tag:yo/tumJur86rx9JXiH8R2A==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:04B7Ok6m2jRDje6fk/Ea0y464Qh6M0gRbatzIOnrBNWB5TjtpBsy9kpRb/BaK0vHejZexGgI8fjLQjbjMXrCow==,iv:1509rfNSxOtwNvV3R/NEgakJQ3xWW24IM1pXFHSO/H8=,tag:AQ8hrB1k8uF50M4MvyGFww==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:17:35Z"
          enc: CiUA4OM7eHz5xGrKrI2l20LSC9TS0A/ckZg1zY4S5mTDXKpr/epBEkkAsHDEl9OYBQ5pWffQYGy9H8K+5llDtb2dUZ+PezuwfK94vKx0PVAsTSH2Upv4NJRRCQWD0jo5RLjw6shOrBNiJChp9ceWPRhG
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:17:35Z"
    mac: ENC[AES256_GCM,data:/ipuNlNjSU6NhLkiTZGsw7oAgulUhtFBOSGf993TfXctK4QHoAM3zy7c4IlX9iwErEuTpnPCALmh7EYXWmbsT9M3OM5bXQA5XYMAMoZ+/OPcylwxkRg6DnVRM1GvdVH1BUjG1kXSQs2I32CT9W1gkMWx+dwlSYqBEwxvqiqMI7Y=,iv:LPIgX7dibqZZzWtqi9kupiBl+D6U+ib6G+SZ3t1CQF8=,tag:g2V5MMOtBUAglaHVWtMC0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
