jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:EzeuNvbQMfo1rUl2lafjyZsJFK4us0HUMP7drtqrrFCU1/x4phw40SrqQxQ1T/VAfB3/,iv:746Jene4IUKTai8sQnheQK1FELKlI3EwOEdAq+cI2bM=,tag:uT6ZFTYtFyGVSx+qr8We/Q==,type:str]
        client_secret: ENC[AES256_GCM,data:82BX8RvUVV+OLkpharVClp92YH0PBpQ90Olp7kjbHisXMM4kagns03N+uSvK+N8ywGA980ehy2KGec7Hyk/3GzHMtxKV8i8jiTgfWYg+F4H7qbCB91A=,iv:kv2ZLu9ygvAkgeOktmqQHceKlYOZWXEmQqjZkz3tR30=,tag:pAwaDPeapIzN/3FZDLJ2pQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-29T20:40:23Z'
    enc: CiUA4OM7eI1imxYN6Ma3SUlFJqw9PPHjpNCV+IF7TxpERFqF8pc+EkkAsHDEl9AzrRweALm+eAyvdp/yNpj/dYWATmqf/O7AAUAL9YaWyYZ+LNWthN2nzaZwgk1w3H9X7Xgz4yygHKgSUJYApkENBK/o
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-29T20:40:24Z'
  mac: ENC[AES256_GCM,data:AYmwLDrDZ3tm+VaST1e6ZumfVWOK8b/rjJUfiNrzzhL6yyVfcyPeJA5JELNGZRWBl6AKKJmSUbJBSOaqyodgJCnTX1ok8jhOX09M8s+tRU3Ok1O/iRH5XHLGDtrbOUBgwP8GCnjHx+Am5E5ZiAYqu4jV1vOobqQDbpE8F60zgCU=,iv:7BpYcQxjGsQoIVyO86rnqajvAhuLhhH47IfsC3frnmE=,tag:0B0mKPg14BWdd+b5GADj7g==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
