jupyterhub:
    hub:
        config:
            'GitHubOAuthenticator:':
                client_id: ENC[AES256_GCM,data:ZEsPiNyhOGkMGMKDI9eUs8gHt1+S2mO45+7UI5nH1qMA7t6tCkj7,iv:O7w/MwBTRXJFLmO9wDgZjb19pBxEHYzBJFo4rggeaXY=,tag:LEBP/XAudsmlfKHr/rIzyQ==,type:str]
                client_secret: ENC[AES256_GCM,data:w9ZZmtXEBZLtoEElW68/n8Zh34LTf5rQ05yGqotBj+zml699DaNoGQ==,iv:cPJ8eSTlsWUvuftGuBiR/vzwp7bOM/Dku0zy2jBDeCI=,tag:y8aOFW7yQs9nrJ2zQDJ31w==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-06-25T19:12:44Z"
          enc: CiUA4OM7eDri9j1ur0jrETt7iFxF3RqoEowa9qd3a6Z4kXpHINDDEkkAmy+ekrRExtyAo/NKLBRvVyivLSYxPqDLX2LOykhs7JYRtixVtfmyMA4RbuBWVU4b546I1T2M+zV1VEB45Tr07g91hczbBdnL
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-25T19:12:44Z"
    mac: ENC[AES256_GCM,data:/HiymyqHxB+cEJ0m4WUpSElFHxBJHkh9iHRQ+9/PQZOe+BvvuUI3pl22enc8hGoXl7miFEZTwshfB2WLJuhdEeo2yChuDXKL6KLiXEDXp74HRN68zkkvhAocEQKvOlFW9ox4rjwN+Qifl6WRX6tdRxlgDTlm7PzCeyChK8NwmNY=,iv:+j0OTAFG/MpNl6yvALV15gd5qWTvaSkmLFp2paaSgfw=,tag:vk4NcxEcgf/cJxPkk3ERKg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
