jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:H7aTVMx1WONoZrHtfO3PrrlWhqzSpRGb/t4Jhrx3f0jphr4k2FYW18oue+r0hVfxrJB0,iv:izNPvt4ZRyOEoEiMOoKf6qIO4IAicN84VZLaOZhMT9Y=,tag:wIdTnqo084p9TgoHFZqzpw==,type:str]
        client_secret: ENC[AES256_GCM,data:7FI1A+c0gnBLX51USRSFYEk4P+cBm4mTcx4NMFzkFwnVmmE/ry+t6l6RQBjBBxJ7UTWzimcurQk/5ND3cGaDj2INjcPSBgjGvCtpy1Qylt+Z83Put6k=,iv:dphaNbZ0ebkdWdp1QL/Xnilp0BSgTwvVKeuHexb8tZk=,tag:3MUgKIQujSN+TZhjYK0uag==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:psYWmlJp3L2qvm8r3gswg3/VuMjA91EQa8V2M8H0IAJc/sGsnN4j85TsahwW+3OfKpNoVGXVuFhpBeTM3mI65ATYs6IbgvX5Y06HntBdVjciuFZ4Ejc=,iv:M5EZBQK1Hk4QXey0oAj4JeBgVxwuhWSgq5RaU1pJXf0=,tag:6DACyts6MQGUQbVv9NAcAg==,type:str]
        stringData: ENC[AES256_GCM,data:gBkaz28LGNV24l38/1auNXbTwaCVGIjhfhAO5nIrjiyFzbRTKj+3V5z3kf+U4zafo/PtpwWf8WfqzZ0hRhkNBTwCCc4qOaJN+0LSmXu5xzWaS4Xzq89muCm1mjJVwVN2CnwiPcMMt8fvx8oG/CyVoO25dCLUTqDDnZcw7Oo3PsRxQKvbAyZ+26zDSKPDzbl4nNo6pD1rl45X4urCzmddYBwJC/jRl0VtLNQNXwJJz1INoCQq8l8GQhQAQjvn5eZh2d39OCwsvO5br75o6+aU24sltJCyHJEZIlHyXetLiB9sI9o7rbu8lm8JyWDHeMM0oc2xpj4YyQex9UM+6tOgA/v5gvNziycgsgSLzGBj8Ez329ixveXVHTSYqCzvuMwINZjKcJyMxuszyLqfWPWC/SuPZS+pdtd6J9rl5DLcxkmHVXV3Z13NoLDfqVb5TLNrdwq8QelHqIq27WpwZ65DVQC+wjoz5t0KLKaSa+fXxV1oNyDWTbIeiUqqpBnxilaE0CLoK0S6/YbvwPqEGzB5FD3Z/NrH7mgQYWFGwjfsB+scb2UOfZMwsmZz4Ngg+8qggZ+lP0xLc45G7PsQwiI6VYt1ZSbH1q3Iv9j2jnxRCQN6aG/r8dHdmXxCvskgDX28z+yqVN1zJwvMBjr0fQ==,iv:eHX8+DZySWUsEgtGyYgx4++3RuGhzyMMhSrLtJdC75M=,tag:tbM4BPEevhYV7AmOuG47ZQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:18:07Z'
    enc: CiUA4OM7eEKRu87//zFA3K4dV/jkLD1c7SBBpIq15TDC46TpQZJNEkkAmy+ekqZQuS0+sjv3jlBTZoWcKAl9qgTfJwwvoRVb05wH36uDF0FF0qVgJ2ZPIUFr8+Wu+Wf11dqlOoxe+uzQBpgZBdfiyDWk
  lastmodified: '2026-07-29T19:18:07Z'
  mac: ENC[AES256_GCM,data:1QumLze+C33cDoLGbPNXf9TXWP2ubkRlEOnk8oIs4ThQDzgQKSnN2su+bQWzpFhtIvsg7Wn4mS6dqFLWiDSrktxAwhsm+o4kRIzd8dSQ2lsAG139/S98c8jWdLUFcdQZIyX8gzq17nBGMTcoFOmBbD6bM/tRW2cYoGFPMj/TdP0=,iv:y+l9saNAcz7SCqMdmzyJc8gR1O/OVGoJ1UNHFlZfKeo=,tag:pJrgnLQ+pRlOE1gKHPcGkw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
