jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:x+ksAdX14t2D+GQjXjrzKDZrpGmB4lNSKRuoFfVPsqCh2DqBIMf5L68ZZs+gg2/GoNTa,iv:D0QXL66Qm9yeS/QsaKGwxw9LWzBsMRZ22F8Rc52R7ZA=,tag:ikD9F0MJCaq1s1ZhDdQzrg==,type:str]
                client_secret: ENC[AES256_GCM,data:i6UqYegw0zFMOpOL02/Gt7sRh8amGKw7L91d9jEg9c6hTbyjyGsiOr/sAup1Sf15/NYQb7Cjq5QUxdEtTNo9KL65z566XyPYHF0wbpeu029sBAfEa8E=,iv:WUVzpCDIP2dJU1/gd2dQQYhl2LaNTJ3mhLhZl5lLV0A=,tag:sXL6dFu3/w8weMU2HLJpxA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:31Z"
          enc: CiUA4OM7ePbmWMoPnj7yr1XPMdSWFaaKWTntKtCld18TO4q4nzoMEkkAsHDEl+HKZRU25Awp1eQwjxCRvLY+ycSDaRJL9T+TB5DFvFrfGnohok50DnqqDcTwiSVMktzNgKtPtDlQqpwo2VO5XoeaMIa2
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:32Z"
    mac: ENC[AES256_GCM,data:H/P+ZNBfm5bkX3MwdWO8Sw8iuEgCq3PpviuT1vpWsVAR+I58y8H5aNQM9f6hMIP13z0qIAIhB17dPWGXfNJVRbJh5mq460Kw+aQdQelmqJQ6530FnRvtW7HpeWEfHLQpN5iHvitW7dBYrPmhWgQIbJOclmbq7bWZCxmkZ+vSOkU=,iv:1RC7JKCElPbFGIBnjdC5WEG4XT8NZntTcGqz1Dn40qM=,tag:WTTaj1Uzewl/a0kuEzGDHg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
