jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:nnYy1n2YT53Etkej70rKKKwQhrDq+bjTNns2/K3WLzG81zYAIBH5X6Hm9btfm4vxqoo=,iv:+iOgdnNGxq/Q/3b8ohh6hZx92XVmW2CTxiwtwK+R0k4=,tag:LwhSU2xyHV5YA1gf2lEMLw==,type:str]
        client_secret: ENC[AES256_GCM,data:gcOcrYvikjHKfOMFNlOnrX29dY4HeJzxQdiqtgcN3EurpLi2w3rCqnB9B0MmMHmAIeuUP1kAopNKo/r42O/v6WYCroIUt0nPNO6NI8jVUWhh9XpBbeg=,iv:mPxrMvBt4LMEmGgntZL7AYM1LcKS6XHKxYXJcHwYqHc=,tag:YkeDrI9gaobyL1gvPO4kOQ==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:fIoVI10A6Oov3YpNGUG/+8fHlBy9bCbPxMIv3Bh1rmsiLysPcna1aC1fidJIqt++eSw5cuTxwTk8rd3EgMHfGYauXsxVLpruW7tWYlVBUm3CvrgHprk=,iv:AR7p3PZE84jJ3ZXF3RhyJ/oFZHQX5sS9jiW36dLt5Hw=,tag:GCftN7+Vd4cJfUWXMGO3Rw==,type:str]
        stringData: ENC[AES256_GCM,data:K04zfEkn0ocF66nKYQnDGJz8ZLYy0zMt7PYq7qLXHTNsNXUmF5SuTG92mWiCWOMpmQRgVcgMx/2O/q9qLOcR9up0TtlObTRYTt4Zwfc5NLNQ8Ya+rh1FbG4j0sa77yzSN4K0zJilEs/kS/8IwNPwrkVVBA73kWCNVDtzOamiuSRTSgQGvEyPyJn3q8xeQLVtc1OYW6DGGD9Jfwd5h0rQIFpkoKSQ5OHubyg5uIAwqaS/MZv3KEtZQT59UdAIK5xO9ciIo5vd32SAOr32wa2JZIRCDwjsLq4D/T9E5y9KEhzr9UH/BHrUqg0dQxMHm8svbPdahWfMF6PUjIPRWBycQbCJ5sHvjEYPJy+3eO9MZXnfYH/IbIfaCL+lWuwk+ovGRxWiw39pGOC/vDqui13WRH4V730Bp68tzdYzvxMbVtRNci/KCwhe5JiPppmC/kCsk8ZLbeu8oyDJnTm2WK/3LbT/pkwBI9Y3m24i461hDpyQpOsgeZKIVUuRG6ybQhmrZ4+tm66efhOef9h3IM3+skd+Iff1ll8TQ/n7LPIgDkvlb2g7px+xLHfNV8XKNGtK9JSrNmDlRyxbu9SBzkPCoN6eNZ6Lh79RenEBMidrqe0KlXC4fLSikwnYHpbJSJiwIk29FFoaO1Ka+01zQg==,iv:Iw/DbCJMaCNQCaV3GETIcKpL9+7qnfbyrDqCMfbKk3o=,tag:/qY3M07KhkoYmK3Sv3pdBA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:20Z'
    enc: CiUA4OM7eK8LUxcBGkGaANAQhCGE7urD0X8p6mrMvvXNJBwPvsY6EkkAmy+ekvyXu/QujAsOUa5XRq5uPBEdG/Dgw7BxlWQPr7TsXuBGUjlUO+HLyj6zBdma5nDjJIuC5AmnRXIcvLobCvWfLb8VW9pm
  lastmodified: '2026-07-29T19:19:20Z'
  mac: ENC[AES256_GCM,data:6qaQKcOn/AyVo+sA3dkA22lIjxdAiDb1D+Mkw2VwcqUMjUY9JFrZQUPuJl+MENXmWgfOSwlhM3dVe9ZK9qjriGAyVkMoHqYEkA9Wp8Q+IlsjwoXmYvFKfjD7evLVJ3O2DfZfSzCu6Er0IT4KPXeLgsfs3M3I0QVaYlkLKiliNB8=,iv:eKnvID6/SWFiBBR0C7nAr4hyiS/cBcpsIMzxPxHvS8E=,tag:BqpyBd+1n/EVH7OOee0yiQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
