jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:xQ9j1coN67yLT2V+MJFazHRDF7s=,iv:PAy9mzC+F7AuD2cTG0UpdMEYWRo3KRAZJpOM1N+2sOQ=,tag:KfRcEnbEAwiM4p09WQAwnA==,type:str]
        client_secret: ENC[AES256_GCM,data:laqM06IdhRY42pc3Ao6dzDsZPE9IX7NN66LxXK9N+kfSCA+fvUoLfA==,iv:518MiBl6RqxiMSWxTg4Ail2qUy66Em0yJLqyCCZ361M=,tag:JuY4z3GgI7rdE/iJar9wCA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-09-08T02:22:53Z'
    enc: CiUA4OM7eGzaaj2oInphatJoq7SRfup9gMCMC3C07EZD2KYJO0OgEkkAsHDEl0+NADwt1HecEv1dBqq9e0EBlJIrzD66g/hxvTz9W2NOkhptRNugAHKyLEVNh9YJd8XDQZVfF2+ser+3ujF29iZ4yEcV
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-09-08T02:22:54Z'
  mac: ENC[AES256_GCM,data:AQpgXRAKIYQDpgM/ewvdA5wNC/62/1UiDfEgmXycxanWOWCZBigKvlvo4q0VeKw3tkcIV5fTYV4jvz/T9He+wwTQWyPeViXO0B4H0lFdnDn2uUs5eOEOLRYspuUhoJhQl/VNkGWdjrY9H2YLk00t4+LcagHjWXIwIs2O+qzYthw=,iv:/YMY2ZSImUgW6NTyrpm00SRuVIVt+Nt5t9wVlE4LZl8=,tag:7LD332B0BTcLwzgn6s2yIw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
