jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:Y27CcNpVjA/ZJHeHpp6A3sRW0rFpJ06iJqLd4WiMfNiya82s/3vwKFWed4NTM3A6ar4M,iv:Qckn5jLZB6e0mbRALTU7C8g8SJJZ3OQH/jHCYEwWDIY=,tag:74JdgVLCRBrvTo/rhMqngg==,type:str]
                client_secret: ENC[AES256_GCM,data:8/1t/lj8i9t+++c3nUI9q/CaYGnGitNbiULFPKy42PGdeKysGZ4hhimm23wkKkw5IH5rFMP+jpMBA5qlVFswUDZtw01BkiEIctOs6ohHFNrctrftNgY=,iv:3W+AwUPxCt2L/yU8kfhBOV8ifgnBFCEBMfeP+fieAy0=,tag:YKy/g679zl1ItGMIaSo0Jg==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:/93La5p4mg1dlyJvBV8BFMZ1urEw8rLlTAxqy2F1GBkNqaS3my/07aA88DrTG0SglInZie3/0uV2K0JrjXJ20A==,iv:YexTtwaZDwdU3/vldnfdmkV82yNbAKTdhyIhYA4TMms=,tag:YnlXBgXPfx/9OALpb74bPA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T02:30:40Z"
          enc: CiUA4OM7eBysa5DHddr5MZSUeu7P3tTbG4kvmgwUB4QD+kP2AbRGEkkAsHDEl/ZzNyPwNTjHII+iMv/C4aRp3iWmXKS/dPZ4dyAYksOdi5JLVRuULdYMs2AUTa3cf6nmq7GYaQ52rEk2x3YTyugR74xO
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T02:30:41Z"
    mac: ENC[AES256_GCM,data:I/DGdWcDR3cbWspa+Zd2+Z6Yj6wPfv2u9LuMDodjmDxlEgS96moVDveEKjaN/kxBDMrqKmGFMGkvrJoi/x1QQMeCJ3VC804gGtDeWaowZMohLC0hVi1TX2a4IrWQ2/H6uuUKYFWlYnhl3z4msoak0yEU3vwR5OeBwUSKJeRrSd0=,iv:QiVDm1QTDt7LlXuJLy9rPKF5Go2zyZBXyH/wwjR+3VE=,tag:Mv+bkN+BWtaoh+4e+p9U7A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
