jupyterhub:
  hub:
    config:
      GoogleOAuthenticator:
        client_id: ENC[AES256_GCM,data:TVTqHhItsA/3NcgtJGMldNatm/iaeTjP0FPgdFJabYlS8I9kaCGxOFFZYi9PQ6gbZ0ZmHovxAl+JX7MADpjoZmFSgmv7Jief,iv:NuuSXKRE3UUSvS0PO4d4iuWi8sXp3nPE7VJeEllkED0=,tag:GFExPXRY0rncmL8/ws6uPA==,type:str]
        client_secret: ENC[AES256_GCM,data:n7MhoOv2xNNwfC3aosPQyFImetBc1kl15x7Bjl4WM3uExvA=,iv:8VPS50qdEUNVUsYQ8RZWbbiptUWahujdXjaHFruI3wY=,tag:dMa2htnsN0LUJMIaX0/Ugw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-01T22:42:46Z'
    enc: CiUA4OM7eJu2jR1xbo3RlyAtgk909HgI4B0Ck4ErHdbrZg6iOfZ3EkkAmy+ekhJLU4Atkjnqh1neXqY/ohYw3qUjNrevD2D10FHUZPNsXHXKAfGc0kS1Bjx5fvEX9fuRwpufHPwe+PRn+OaRyhM3uuGe
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-07-01T22:42:47Z'
  mac: ENC[AES256_GCM,data:uvb82FTrqcObNJy1sKkB/2xqxf3sz7/fapK1LAb3nZCl2H5ACw+WNl4JQdQ3ODYp8DXqInOIvcokpYpVo/LLXNC2mQmyR11Zt4Kg/j405anMEkiAY5pcnrh+cSxlw5DrlXdscN0JEys73FsCmiRLUb8jGM8bxL8y8W9xJINAh68=,iv:jYKw8yE1Vnx0n6x5AompxL6hERPrjXr/+S7jgJO4PX8=,tag:8KwGUR9Jhk8wdBAnmVKncQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
