jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:b+rI1gLa6WgU0MEFBOi/ToU4Do+f2MX6itrOCFa7SRtqqm3B8PdIT8R7sy16scXw/8c=,iv:V0n2F/uYNI8Nl5suXZWLafu4NEJhZPayIbXneTH0vek=,tag:3U1cqsEItaXpQUXWL25HOQ==,type:str]
        client_secret: ENC[AES256_GCM,data:bnbgcLadE9wChxU3muxDZsAfss7GRp/S3o9XUq1RQbtzYWSPjf2g6f26ts/X6moq6XiP7jceSBqkwpAEAsU0+t5rCiVIXMikzViYC38oMuACXsgo8ic=,iv:KYLFiVPaYuUxOqqlsGKn6GQx3FbLO4j3U5+m2JKLQJw=,tag:2B7DcfvBlFhaQqVOT3wc8A==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-22T17:50:37Z'
    enc: CiUA4OM7eN3FksLpMRcBHVVLSN5xoryGP16YcFPnW0dZiTWP5dHwEkkAmy+eksIvv6YsPdsJPnNHOy3XEpZ88rjXord/ihHTJGCXdqEdEwuRQZctLURHJ0IDHo915mKk6ykXgGGRMm26+3z+S47n0vSi
  lastmodified: '2026-05-22T17:50:38Z'
  mac: ENC[AES256_GCM,data:wgsumIjoyqvIEYi7dS7TUlILMxLbrpdAkR9Jr666W3NWzFPQkNqieSfk8bOjk42bg4NyjhLN1sjN2xzj8qS5nunWfHCtVbr5WR0bn1fJe2yPWL05ZUzvEMpt8GqjtH0uS+PlfvHnzZNwhg5sV5mdyBoMue1/ozmUXM0vAsF+2q0=,iv:xvPEdL8Te+vLZi5SJYbVXlj9TcrxjCbTTwwpzn/0E6s=,tag:vsv+QcgVltIVRqkSNLWxZg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
