jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:ipkYmLRVFFMOE+OMM46gI1gyzlWEfV10X5IfCGvNubBbBEBAkNNoTYGaDNUT0KWNw67W,iv:mAS3J9kU75cNdUmT6a5mFSVWRLA1vLow8bGfZf1rTos=,tag:LLSjaNRJUyn+0ARdNBrmyA==,type:str]
        client_secret: ENC[AES256_GCM,data:jJgcTraVrdd/O6IbzFxqiyLBC7dOarcj8JAaehXMlfDQtR/HklBv0nByEjCupNVdz9sHFiHwhMk6N2bxS72vms8mqAaPgYJ9lPRsGfU39k9LzGiFzIA=,iv:z7Ost0O6ZFWpG4O1DAapzi95tmPUIp3MYLAiW3vQzi0=,tag:D0ZqTEnqs+eHLuw7wJc4RQ==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:HSWyIwWALIpZ5mKzAYOnw2ZquUalk05JcHbknxP5SM1BMjI+hvCaObgje17K6xhi4870mmIsx0/P6ioWipvb1A==,iv:qD1WoKQyi2xRm8tlJr1eODXOk4HNd88NWnAmgJ+sR3g=,tag:ewrKzEu8hvy1BCUNRqhi2w==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:17:40Z'
    enc: CiUA4OM7eBOZhIKZYSOyqy8gy6Ue9fBLEblV6t69BJUTDBas+nMLEkkAsHDEl4mZltIi6eyRmHa7npRcntUtwiHVoHUO8LxXVViapGBq129DlPDvTZt9bMWwmE4jep/OiOQJ8bI8u3J8ojuK+memgXSz
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:17:41Z'
  mac: ENC[AES256_GCM,data:X9Tj0EKb5aNKfrebroOEoKhdq2Qpzm0dzYwcFf5pVWutLfz9ada4/aVRFsYgUjJtmlv6wnsui3aOKih/yntAwRmzkYupjxIbmiTxtsQR88COA2u/4cFXpt5cXSLfT+fShxLiAI51h5fHWkveUx0pYMqQgmLUe2cUCtkNqW6r1uQ=,iv:uVfwKsgEhNcZsoNswKil7I8fd9orgUNBHDsauzMrx7g=,tag:m5Lm0SJSQvKzH/pveCJfiA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
