jupyterhub:
  hub:
    config:
      GoogleOAuthenticator:
        client_id: ENC[AES256_GCM,data:QkvVlOCH6Fjb8Uc3bRRHdMEbtSGtjuC+a7zD+u3vhQ4wnzobCyDmuQRib0bCg4X3tHQLJJVmcq2EeqNsSG/xS9RynW8vIzX4,iv:JqvaBzMv33ZP54SoJv78y2BYCFcgaAAhw1CjUT7E9dg=,tag:Y/0ydUZbpEHhBYMHDwZoEA==,type:str]
        client_secret: ENC[AES256_GCM,data:rgKFn5+RYQRQNOo3aas5yYNT4rlOic05adFgBU0sYaXMB9Y=,iv:YqLFMjunm+79Kc3cRTrqpCzV+pX/ZYCbbsO6OptBFcI=,tag:5JRqX7GwS48zNVTHY2jBeQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-01T23:41:28Z'
    enc: CiUA4OM7eL6dyeV9/tTzqcB5xzAapN9G5eshkgjssvFb2qHKuytWEkkAmy+ekjx0eNiXLd0JpDOidoT95d5HerRUZwbs/GQdcaNjMD/LPzgkJgrJxxZfkRu23ElGbOstEcrvYUqjsDbF6bQBj8kPhAY1
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-07-01T23:41:29Z'
  mac: ENC[AES256_GCM,data:YoTpPCMIuB+NgI+IGpfdRlD0pVa4cSQD6fGIIzVlzlX9JwaVsLYGHTvOdE7WbG1vxLVx5olNiOABbraGPWcE91Hgngo9XkhqXc7FssY6HciYkxY1nsIB9gsMBXCu56sFnd7NQO7l7GUG9bKfjruhclwsa1r+jLuCk2izPqNSQoE=,iv:3GXP7rAHY3Hc79a4enubPbM6bq7Rs33xOS+h6Cbu75A=,tag:twoC+dEoFBYLsVzO4xB9Mw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
