jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:gl2hpq0KFHv9PQHOQBqjcqEtBegiT60ncs4Y6Gium8SjjYehk4NgL2OobrYyidZk+s2Z,iv:fcZ+Y8ORYqQcLOqBRcAcvSAkmdseb0sw1ui6YgVKJH8=,tag:vMa5TsGJ7T4yG1sVfdYZPA==,type:str]
        client_secret: ENC[AES256_GCM,data:4wsPb0wc7F7fEi1R2vYtqQChS9aOD6sMkvRtE+UwLWRZEGJ34ZTjsZgpM9xSyFD/f3y9IZrYBXiKZke6YTijq8ZWThGL5qZOrahrg2aRSPH7DY5srfI=,iv:7XExBU1Vxd3t8+cV7UFQbAxwTNCKiA02BPw30pYqZII=,tag:kMig0wKR2dB2i2Ke3nDKjw==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:pM+a9n9NT0pFEpx7UXqvRJ0nZ11S3/ZcpR7Mkij9Ng6yti+q+l4lEZVNjZKY4Onl0dUmg+qH5MjgqFVTA+jY5g==,iv:LIBP6qHhHfpzoxw34eXN5NTuKWjuVtJhd0sU6GEUTX0=,tag:SrYj4TAfBbNp3++rU7Y2uA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:17:46Z'
    enc: CiUA4OM7eAgUgFjvPBIbB4PD6u8ukaE0pSA1AAx5nz25xcLXJVucEkkAsHDEl2lpThxKiLQEfpAWl3C9EasBg3AIi+hudm4KC/8VA4oZHQcQ5o4cBHfd+Ctw395ToxbYC9fBY1PrFBgtwJGfLSjPkymS
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:17:47Z'
  mac: ENC[AES256_GCM,data:o9U/JNAm5r7UZYC2MqWZ1YnnikHt9uFyHWjjePB0FC1L/TaKLzPGcKmft0j8LA8qgWh4ISG1mjwRuR5j9nzLjzl262+3djlq/iZEHERLIUMtTC6oemFXewGJfi10ZEEq+wpSPjH25pv97v7GNTZTDStFhpZ8L1HloOpG9/r5M8c=,iv:4fVSKFde6MWSpb9a19aaFGvPf0YKtWG7+077c0pSR78=,tag:qvE3IppvT2hReU4/cgMroA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
