jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:VSAR/usltCyddqaPanz2ba9ZcT/gX+3qn97q3uVpak1iNcNFiZLJn9sPX9dFgqcrVUSM,iv:kmIZvvwy9MnFmM5rIi2RHKjAN7JqA0pD5e8FfaKUTSE=,tag:5lPVZCeYcTTeHNea+2cEDQ==,type:str]
        client_secret: ENC[AES256_GCM,data:GDcdMmZM2aOfBfH0iybm9cOPkrzsTdx59cwaUy15dH2W9rthJnFeXoWPf426k6Cj8Tnq7Rlg0GzrNFyd/lki+4uFKCfefin9LuCFkiCwuH1uZi8+Quo=,iv:a4xrXGaCK/c+SspscuhR4G1FGbi1hqihmNQ4XGC+YoU=,tag:F6UTyedpPUPlHx1wuNCPRA==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:8juM8JcAMTdeIWx0UlUz7l1CdN2MOLdvU1mzuFcKc9UpqZVrYoZE+UkA7yrhGs+W61jeVuwAqfoBj04ol/QdWw==,iv:MOx45CC5Lp9xvjBzC2lkFRnz6w9xfsG8nz6SzxxnkP4=,tag:+7bZuzhZAaNOeJMlli+a4g==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:17:50Z'
    enc: CiUA4OM7eEazSvk+Z7bQpSg3/sb5esxZaOC8rPbLnL//pcSuHJ/eEkkAsHDEl1QSj1p4u8rHA/g9U7NyQBjWxQq1ZBTyFoAJ83xHRXyxjv1Q3lAZEiqC7pGGR1NCGN8q/8PUUnxRMCR3PzOQSYK7uoXV
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:17:51Z'
  mac: ENC[AES256_GCM,data:q1gx34fRvp6lt/KPyUojKCQkq7WuIcBO2KFQp5P78npz4u8VrpoIboZaRN4xePFRxVzUEscExt60NdX5R1R9rosS1Sm82nsU3pRt56eQfPQtk0u9TxVMoMceCH6D6MTJa5wBLRTQM+WsFQEqhE/GjAsX5FRf/dTDHn0NuYCHmnk=,iv:MY4msk21ZNhVbmYz20kxLFXo+BDAfzCYr7XyfhBhli8=,tag:Nu/ESXGKunRHFDHhhCFSIA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
