jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:4zQS6VnA9RYHiizNpWN/VVjN2vYt/2uyKnOdWzhcza2liBa+tL8oAYCNJgMVvulN3Whg,iv:soxGO/YF37UC1CPi5FWoexpMfyIZTL/c983YbL9ferQ=,tag:iNzsmU2kkD2rWGGntGRv/Q==,type:str]
        client_secret: ENC[AES256_GCM,data:rJ+W5Q+7nFh/xOVQ6+1xYRym2CyE3f+y/MR3uwNSOJbz+uJTvFIF+uaEQEHX8D1bHDOl8is9Zkytce3ni+Ot4214bSd4hZ3voECe4Vm5PfFwQBIodsk=,iv:gGMGSLZVAuhkx/TdU5V8UYZ2QCahcWK+9lD9NCdbmtU=,tag:gmjLkYmcHsT7I1DpTXLswg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:mIkkO+RXN7rQtAH667X/cmVSWZsPmfaO5ZhHOK/PXL9LrnNOlbxcYUaR6a0PXv8p7ylCr5269l7/0AswT6FWkkhJoJCqMSV/tAxSwlm8i+QyHo+BGbA=,iv:lVscn1yHBGzGeHnA3lSr+VBfShPLGgLzeaGqD7F2ysw=,tag:2MM6qflBZdVF9e/Xbq7OCw==,type:str]
        stringData: ENC[AES256_GCM,data:D874TtiVQL8Vwgxxl1sT3fKv9+nnEViwyp8wsFc39xcrfbicYQdKnqUBc3rWDiZfywpXgby4kYStuBmuqeDpiPw3X6g1Iy1/2YNyXUSsgopwgBK/DKmWW+HLNNKsYMdquYUY/FxN/YAQl0G8/eEyLu6Wusvubar6eypWIUMq2qWKF6IUiE5EAf7Y2Dt9TL8zsDOQ43UXimZImfN5Zq+Z+ro1dW45MZpJ0xheTw8I4XmqX8oYZUZXCQXWsozNrinH0V/iJIyxcnal7DIBYB/TOWwmwmMjm2XyQKFMoirEczU6XEMszIuRpeO35IArvNATHPak4xPGWty/SxLoy89KkyPHSh4NmmMMbv1cMazqXptSUmzfg9ezzp2ZGQD6CLaLnWPsndnftEe3JdS4ZdhNUPgZCMLHySp5Z/JfA4p7mRmz92aEnswYREDVokdhWKZ7W7x99N3DpEsud2c8q5LrLuwJF1WxJ592pRXjy99T+JhTPeIJzDUze1jZ1IFJwlQho0VICmBH41NJqhoUNqUopaDEvN7ujrQymh8eg4cFgnCQBwunWzDyw5MIGStlqzBRTYPt4TX3rvNX/KgoDYGhV1no0Yvv1NvoDw6W3XeXvpw9gfmqU673q5Rw8OYMgCgJ4Up6AOnLW7rPe6VEWg==,iv:BEApgsI2vv3lW+5GLmsu0uZRRDpY5ma3plbvliNpZ/c=,tag:B2j0he3M2BGUuddP/RIn4g==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:55Z'
    enc: CiUA4OM7eM4XWvWcFrjbtPQ/23i8C5V56wiJlB72ETkiKHqlSh+yEkkAmy+ekmR77lquHCbS9fIumkQQ+fVTMCc4MCddVmifEIo5xdzv8tEbd17G7NMu/Y2G2jb3vZxeX3PrAt0ld39FNSR0Y5DV6U2N
  lastmodified: '2026-07-29T19:19:55Z'
  mac: ENC[AES256_GCM,data:TLkFn9tV1pmXBwIhOzTEouaLmMOm/Wr4i5RBQtUGUDAQQQFFF1NGOs5jTQmKT1Xwhvscn9J7MLcrsdgrPce6ErKSsn0FrvEZql9gdU2rj25hwM1Zq7no1gZirkgyhQKuO8eQb/CpNK1GYnW22uF16S3SHbZG0yyVt3UhShvncTU=,iv:a/7vzJrQb6ivIlqBFGgVGMXY6Hh9o6cSqmuomsmZQPs=,tag:pgXVDuzyxxt2M1EudarCzg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
