jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:Wh/greCOaq3vaWRbR/52DgIKU1+EutU6logSCsLqj01DVrigvyeO77cY5o/xGDqPGQ6A,iv:5MYZgeJ2XDHIFYTNH5kYYqdjn704tFxeGtjvzCV4Obg=,tag:IgylI5qh2TDVBb5BoBg7Hw==,type:str]
        client_secret: ENC[AES256_GCM,data:KsTmaLbJa1fIMPlGkaJ6qqX7OiTsQ3c4EZpucTBsXoL/YNc//rb0yldJga+YbABLH9aqdb/PhdW45GwkdP3WUaTDw7qjchUmMF15AiMkVZQqAC7fFdg=,iv:kCHABtdFrLCTDh84ApM7nBqK6NjvpX5ZFuHacyPnJMc=,tag:y8rpHk7jQgV+QRlQ+hZ91Q==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:56Z'
    enc: CiUA4OM7eFJN717yyK38ezt5TS3iUMvZ0JTiJTEQJbaGnFako3YqEkkAsHDElzZXcwFtZa999Yahbv23d1OaYUUIhERBQqhMq4SONiX+J2lrKeYiu31GEU0UFzhlkVWKV4aQgff8Mxj05E4a9Sde9Kfj
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:56Z'
  mac: ENC[AES256_GCM,data:jx7mEieQeNmwZAvpq8zZ0EgSnF6W2ANKdvEyDAOm25SRUOrfiaX1+bKyTAfZyW5Wwb0SPOGlhLnO4U5X/Gg+7tpbNgxse273rLDJWPXWl1Bl1BKO5wJLC8wjZ+lkBSggh+cZ/MUAdClWcUp1YfG+bby+isTS5/XybiAweUmNl8U=,iv:R52W5shce9Sv5aRRG22UEtlovSOPL0Tgqv8gG0qtc3A=,tag:9UU/VXAPZnRpp3YrVycfCA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
