jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:STlYSAnX+gFeEL1TqD0NjPMz0XGiWsRFuCbWLnHu377GqK8tRbqk1ci3A80HPLDoi2+X,iv:YpAtlk2jX6bMIuiTxkBkR35RIDXAwDC5LfaTsjIy9bs=,tag:CtDjwzxAj+2bLK5kY6ftBA==,type:str]
        client_secret: ENC[AES256_GCM,data:K3pyCvaaXy4jIpjbZ7L2OJzjjn+CgaUCaroSEj5GJCRSw1jciZ8ORG5lFBi9tVKRH94AXflOvcAm/5u6nEiueikL4YNGR3wppxOuobe5ywW2rMG4d9c=,iv:m0OStfo+Sb3XkoojEATT5BnyDRZkujL9zHoqCNfumcc=,tag:Ir+nE0BrQ4hEFhZg0vaSQQ==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:2mE84KBzpPkhxBFEI1xXV2FfQcV4ix1RXXy+Z6PhKPuxcPHp8bb/d5upt3/89KhiDRxMYys24n3Wziu5LYSbTA==,iv:OT6dc6xFF3aQSnGRUMvOVdUOs5j0qiOail2++1k0vks=,tag:gQJrNOKfqtk5JkyyS+xfcg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T14:51:27Z'
    enc: CiUA4OM7ePt4/3M+gdJtY+hPFni/9f3hvlwEKjSH/01VkBQi8UwOEkkAsHDElxlct79PEhgsuxXcEmB2aIBQpBQ9Ol9zWVbe2GjC64bQjZgFYP7d0/eI4ipdSXfyUPtXRPUytl4fX/Je6hyuYqtJLy+K
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T14:51:28Z'
  mac: ENC[AES256_GCM,data:S8jtWCc/yyUV96KKSmDA66je55lOsYW9Y7bqLyYkdX4cyfKUhaHjI2m0xCPvM4t5xtrc5st9ZUcGVhy1O6N9FLhZDWP6aBQBYC38qfly6I9tCFg5Jn0LCP3zZHGtY+wSRhaIm2K5oT/nuaVNQ7LSEwDs8vbae5/EykYY0kGgmFk=,iv:yJhQkVZs+rTytrSe4XfNDlhTlBXPpKY1/lzTDDC55k4=,tag:cmJ2KEJlyIr1DbA7mB7/Sw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
