jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:q76DPeL7xPHb3kX8VE/fWlLRL+wzMWlgODfRrrU3lq1qJL33M2zYmpqYHYGSsVSHiuyR,iv:rypX/HzSmP7ewCVnnYxwpXZcq+0QdUj0nNPB6kiWMOg=,tag:wnS9IN8xgxrVx89XtF0l/Q==,type:str]
                client_secret: ENC[AES256_GCM,data:d70a8K/Smnvt+oo0F5vwK3nBrRTfha1IQDV+0w4GF28MWH+EfBMdGz/nsTQp5BHe+Me22tPPiNSwld5iMFwZLBZI7xA23afMZ6WsH1Smmz+q44hrLwU=,iv:TMNaSfKO5VraHkb8Jfq2AKUOjOIUPlk8bJffCVmWT+s=,tag:TWkNM/tm4tEwOxeTaT4Vpg==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:qOzQQUp1Ht2RvZ4DcEknQ2vzyE/b8nD/o/X+y4AogLy5Ad348tBhKbOrwaE9xEwKTHKKTpzirLykctxKz6z5aQ==,iv:7GKPJTTh2K6jU6Cu8npnCVXqyBqmeZmerXePBWoZRAE=,tag:vCslZe+WALtq0p5EA36XvQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:18:15Z"
          enc: CiUA4OM7eMuEhABLUofkrJ4SftNh+oOrYgqU+x27Yg212eNY7JC9EkkAsHDEl0xHJCgmihqSoPZyzyeo/DcNuJelcVEu9zwcV3r4bjJV6gb+yeR5qLGIRcQL8Q6oOTlzMSM+bhLRX0IF8UbErun6ljsD
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:18:16Z"
    mac: ENC[AES256_GCM,data:LcqVD6hlesFHWUwasMjT3io+UepQ/VzozjYT97UFS9BTM9ycCzjkQkWU/ZKDaP7QxJSSp7Mbe0v+GSeAYLtx9ZQ85eWZ20tKjMorwABx6JvCYs/ph3XCcCuwYum2eqr28o3kWCEm1Gh8Ttb8Ok8xgVybaw+5SeIs4bRjlIkRxNI=,iv:PPhML0kaj8TB7p2WF2rN6q1nSWlF8TEbnAgB78dPbXk=,tag:EXIOYuHlf5oGuhxXgLKzsA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
