jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:g7uSbexLlfco/3CvYd3TaluxKi1xNIxAC1NMGx64fPG8Q1+QHM2rV8hyMbnIqv0uWUyn,iv:i15tlwCpq/4WjTAR5AIzCnDctkclZsvwWF4pr+OmDg4=,tag:mZj0ybrJPhtO+Tg5IyUQhQ==,type:str]
                client_secret: ENC[AES256_GCM,data:sKlLRkI7fjfS2Bj9kXsLVp9RbhvLlUsx79Ihmf9p/DimOxo2g4Mc1C2X9XTuOLyFmBuMlOgOEhzIsbbVm7MoyseqSg/XcEPZKfj69UVLcVNsQuDP930=,iv:tDRG7S9SpA8ZT8HyL2Z6/lDwAIgXCunEpPrdnA7wdNw=,tag:IFFGDghYhIJrbbT1+wAzVw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:20Z"
          enc: CiUA4OM7eDy78h0LE79qGOnJHVqoOwizSXkqIf02Pciow9EQtD7QEkkAsHDElzdH2AdnkrdNfjTdhuSe2RMHxpkxpihVMkq35pyw9BKgWIsIHMHpx08Bwt2silYmw9JXmFZzd2cKh3pAe9RkeQOpMtE0
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:20Z"
    mac: ENC[AES256_GCM,data:31H1f+b6o6CjuP5gizAB2er+qse2viSTPToPY28R6js+nfRKOnR249MtDf9cWhHFD9P7oja2+8HB4kdmVXEv4UmNxXs+TNNN5PyFBFKkToU7d1PAEmo9p0T3fWPRbKOF0jNYTwrb05E3PbbO35IDql46K+2ywDdXpS5Omvr540k=,iv:BJK/umQQN0PqI6GOnrSOYafbqsBX+gsGKI02AUoVMGM=,tag:nXr8RUPk49AbhRkVuAmRkw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
