jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:qtGEj3og95D7iudyI7qlfsLIrHn/MYoT3km3eB++7etJT7y20sD+Oz2K6Hp6UkPwjTG5,iv:f/506YYFOvCOCdIvB3K00/7Pl2fB9XdIrNAjoDfXFhg=,tag:c8bMBSKElXJxgbBYquMzFw==,type:str]
                client_secret: ENC[AES256_GCM,data:A4tAnwxAvCHqWU8Ff77O99pFukyO2OG1STWU1Htw1jlFjegIUHMFgc38wYeHVe33vZ6NA6v+y+RbdO831gijj447r7UswI7Du/NacVFjPQV8bEpuBjw=,iv:OfhD0X/VVUu4pbmnpDiMqThCvdpSfWeGCgatCbx64lQ=,tag:OwrlMcYDucBXc/xfrdvDIw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-20T03:58:55Z"
          enc: CiUA4OM7eDWoBYDEBZxaUbwR3k8goBamgSYl/n8UflhKWyItYkMWEkkAsHDElwOecazjOpfskz4O+XlM5hzsYbOLyADke/7RliXwY7I8U9x05q94lFV4cKyS5OIS7/jNwoqTxHwqq4gFpCHPkfhm4AkA
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-20T03:58:56Z"
    mac: ENC[AES256_GCM,data:typHX+Bilhs3fBbJaR2haxaaSv+03myi3pKV4Ts3YGshBNWeIclIlGIGPSTALMBxLcGf2zmfLOPQHMCbpYag7vrG+KTKTBUceJbhKWYBq00O8MVem4hK/RHcx0my5rGII8OQbtucCARi349TG3XXrW4TumsQbmk/t8oQjCV3TFk=,iv:LHTIn7ZZdOiHcssxjf6RLuBAA6UM0KZRz22LGvfN7qM=,tag:B5a6FypZ+t1r7hUTEzY/gw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
