jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:8hATU5BovcMK5lNMr6pTrXTvtLC99YXqs0koCVjU2A8pWPfxH8elagL0VdXqg5uNVmiA,iv:zrfEYtxazaXkkbHXfe5IUGEnBcB5/7lMX0onCVz3EEA=,tag:o8Yk/TeLXVbj89Jw76MMbQ==,type:str]
                client_secret: ENC[AES256_GCM,data:rR83lq0dEUrp7aML0rmQpIU1rX5mPymXWtLmJ68pEEGDvn5xC1UX1cyXYzKSAUt/fxpoFKYfQNIdA+YNh+EMFdN5fv5zqAnF/Ne7ydrX4zn/H7OUyoM=,iv:coKuwOhlc3mjx7V63A+BLqLcFPWbwrvWx23cG0HiTA4=,tag:7kmexW/Msdk0dR97ZwQL2g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:25Z"
          enc: CiUA4OM7ePayzb+XpaPIPH22XcZuT6k3ZMPYKERDhPUYYhKbrWZSEkkAsHDElyv+cwuYdrh//FWHqrmq5P2YDvNIUtldeXsRyfU91J5W7ptU9FN3yR4ToGjpZwSooNRek7cgjSfiZU+9/K6Qsy8LXDw1
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:25Z"
    mac: ENC[AES256_GCM,data:hcWKxWLdOFCYCQThIFJiJegykC2ETg79xqosIQEJ+ebzpfiZ5jNYKtzcG3oZHa+XxwsKEFlaulYRwdqKE3UYz091oW15/aw3ek69AiIqhIqBgc2NsWmJEYhZtMQbN6fDD2YY1k6I6uz53PolguCZKMzC37LZ9ylhuAYKJUnWv2U=,iv:u1E2FJ4off08LeOO0jHonU9HggEIeVpV0MGFYDIzxlQ=,tag:lj9yoHEKgFjcCO7cHweb4A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
