jupyterhub:
  hub:
    config:
      GoogleOAuthenticator:
        client_id: ENC[AES256_GCM,data:7F0KhZb9CI27iPmytyGs0azobB0CFmDhLX0GKp0b10YO+VqJBOXbqxXjWrvakoCCyUZXMvDLnPE/2erFBd4ApVfHs+pX2J0j,iv:XwEAGVVHGrh5cdQ/CFqXKsJ7szA3Dknc5YaxSkBsGyw=,tag:RA694Ds41QDx8egmq19zUw==,type:str]
        client_secret: ENC[AES256_GCM,data:7QdkPDOnfBSB+KYgq41EWd1N1duQjKwRO9QI+BzVF3q/lYc=,iv:guJ26VZq0fLtDAWYgSA7LtXhfn8IlOVCaag/F8YJvzI=,tag:SDSiJrBlQ9rOVLuuuR4W4g==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:35Z'
    enc: CiUA4OM7ePExAFcMwOypmIlUWQCvXj6CtGOPKqoSK3HsWJq4g64oEkkAsHDEl9lSHXIzwc/pds7m/mtOOt51/BnqQqr1srgxBCOMdj+uTZ1iQFw0wrb+MOBQ1yf/Ciss7poSOCywaGLJFDcu3bsEzSvi
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:35Z'
  mac: ENC[AES256_GCM,data:InJCBb0vymdQfECkrnvfcGRxJNQGnbSnupV89Kl2r+P70rQ2CZ5e108e4yOwO2IWwD1M5yyU0paWc+qgkgSQlCBc96vyZFELpuAKsmGV3Pu+gTebqjKjJJ7J5PdND1LITo2NIaJQCQFQQNI9YrH1Yc/U6TLLcmxibjDbVNPLAd4=,iv:bLKQ35kYoKenyQCowmUHx7Z2LXGhfxJMnOgQAR1wCb8=,tag:MHKOTkH0I1B/Ig2qvFuHaQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
