jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:sRwVNjv5fljdWCxWmPeUuu+LT1f9tOkuTd4ztjt5E3LoZ5xzh1hhjQIn7SqwFE5kWID/,iv:MELW09pLCtNwX8jYNNIlv7G4vf1A7g+OuoQAKpScvEM=,tag:4bZC7IbEeh9XmeOTrSqFzw==,type:str]
        client_secret: ENC[AES256_GCM,data:V28f0OH4gnBs2cAG2oxvPp7pqeDmMyhS3FM4zgC72fPRse11Aer59eLsipx0DtDws9qntyvM/4B/hP6QuWut6MARtCay+d779hYmZwXnjz+SRWpfXQQ=,iv:o2R6uENaMr8Buged0jpUTqyEh52d/DPMoKe7uSUL1wM=,tag:l+DZf+3O4XmX+i+tkqtKCQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-11T16:55:48Z'
    enc: CiUA4OM7eE1/AKSbrT6L7MGN6yUKSr0/QuE8dn+nVINQgWBComDfEkkAsHDEl0z8EDTrAbWHzmmKTRieoXGnyilevLKs7yDwl7qD/XkuehWiNIDNTQKRxp3YmTnfxO+oaE4g4RR/CaVgFTOiONH9ojqO
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-11T16:55:48Z'
  mac: ENC[AES256_GCM,data:RmYQzcoBplGyHqn98R0YPbmuoJWJBICvFB5Q1TmrNXFeDUD4W1J1CI/rnv+iE48UdyY4bo/8zrvtiSBMEFREoLfjGZzc0LoSg832r/qRJswQYnFKSGuld2yauQk6rR3470qwIJQ9g3vygoMR3JXS8TIBgvAjU9XWEuinQBsxzxo=,iv:2WYHgMfHcq7Ngs3cPvtKs4T2jyT2XuOFvb8f4ZDtZ3E=,tag:rMUgnB3jtgLZkXUl/iWM0g==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
