jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:a0R+0n08rdrE5IfL/mZZgT7IIewerPW8CObIxLCCiyGkAqUClKa2ogmp92JmvPVd5q4L,iv:LU1m/0vN+1NktABtPaq15dK8hyRbVDdGa7jJGPKmHws=,tag:Jl+c8h8P4EETiGYHSjdADg==,type:str]
        client_secret: ENC[AES256_GCM,data:CZmnYk2Bc0a9SEXNBRqIO8wCbZLnfUv+oxG8sOYbAVAbV5SldYSQ2DqijzWxHE/4P2pQYvsJFyQXSJUpTDLq6KgtSNn1nXzCg7u/IhwMGwiMgmT8NNA=,iv:ifzmLNNl3mycU71JukOYZmhHm7qkZWkDGNuUsSnxoY8=,tag:n9RmWAMhz4orH/SrFPsQVw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:22Z'
    enc: CiUA4OM7eBMMAkWhyODyEApaBbhkVJCNQpQpmVySxM/MCXahzztmEkkAsHDElzTtbO7MeF3Zl0fjXDbze5oDaI2kdG8oqquyomOODaGDL7J6dDuAfNfWqdbkpztDiQpAaKfHbodjMTnIrwYfBWxrT4tO
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:22Z'
  mac: ENC[AES256_GCM,data:mWp8uJOFGTYJzQH6VgDo3736+NZ36xzeKyiDT2o5qj3BVdUbXdYBD+AmA4V7rkXsckkIdRptYIoQEkU/E2Y82ezPm+UxCxEEmn0HyPsd1pp6Mna3QJP7AgUl2QUoaV7zpXqquGvc5zkCbB7dlq9+0ioN2T17U+EeQ7N44uJCpjo=,iv:mfF0hI9v00jSeROMMD7irT7ISGw/RmqMLErXn4vehPU=,tag:lNnqxV5D1kBB/cUvn4zHJw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
