jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:Y8Y4vUHjZD44aMoMaXlI5t3PK/dS7pQmtel0pCGKihbUaMDISbw5iv8vV0Xb1gkBKzsY,iv:LTJBNYq1IgyizMigFT0j6x7wX2x1le08HPEs+IYyZl8=,tag:zGdm7Yz111rlg3jxXA223w==,type:str]
                client_secret: ENC[AES256_GCM,data:tm5TB2z/ukVZVy8axgY2X1SBJr93UWPU24DXNBZO530NYLIyzZjTlv+AxFxl3Ee2IgMfxwV1WLcoVHpks2utAgfY7DOyMVht7B3Y3emDRuqcUZK43QU=,iv:nOwWr9FiIW8dQJi3DDHx/aS7yca6oFBIzHyNg/nEXJ0=,tag:ymS5b02YQlTVoPVrWWUEXw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:bGFe5Ji8s6JYbXuYgqfoDhtvOpxqMsdReqXLCj/fe+4222Gb/xsbn9ZLCsgfJu0QcL6pUrI1khd4GWOym1r6ZA==,iv:7QrYNwiNPMi6gpirXI7PgBf5dV+CtVIRxZve5eK1Xw0=,tag:+0AvvyWf2f2LUPLlI0I/5Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T14:51:30Z"
          enc: CiUA4OM7eHKw4tEvahshBn177hpCDoZaGH9+2Za4Kc3ciKDREfHEEkkAsHDEl+8sipnvwvi6q11W/wwEb9DECc8EJdE1Rhh81UlCX1Cc21zMNrAlg66/SREYvQs46+SHd3HfAosXn3619lG85rRE6FfU
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T14:51:31Z"
    mac: ENC[AES256_GCM,data:R6/Lzlu7pV2VPuf90cpO8E7OFuXlrBIqvbDhc9CBZv0AoxfzVqU0nGN8rReeXR7Zllw8+OD65VCCpH4bBriatcUF1Rjz5SzLgCaA6iniZQEQaG2qj8vrbGcOqDjgt5sGNGH0Hb3synB1CoXeNXUKn8kiz200vLLsLRfxZl3nfFA=,iv:PsLtq4CCppqQYUBWNqkwL2ya7a7C0L4k2+9dt0aTqcE=,tag:izI8ow28fvHUmosX2SejQw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
