jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:u435qAs/1eCgaxnu465ErP5jIDpnJqmRTc+JbZieXWs2ukWJa4xo8/JUZDJNxZezp1rf,iv:UExWgaaCj3Svmsldyg5PuhMMDQZ7xzbDWDZ3hZCOCus=,tag:pVsDYZ5fwRfAk1/U6qeIaA==,type:str]
                client_secret: ENC[AES256_GCM,data:WjtzfsFsPxXujTvodcesiYH6ex4neBl+Gsj0c2sMVVpsa/EXexZdUWcMhwfDK2LXG0svMvkoyHU0P3urFRB2yCNEu9rBFO9bmu4SQDkZAJkzK2ysZZQ=,iv:sg8xzOunYfb6APxOclHdFS1SBiJ+1AuX9hxstjaIC9w=,tag:c6TxFedAaO3kyVDEfXRoPQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:15Z"
          enc: CiUA4OM7eLKnE4HS5kyqAtJiyPid1IK5XeHmWpAU5QSNMGSRFm2HEkkAsHDEl+ixmhd8dBL2/FodcDc5s9kuOVQFMKSiEwKQ6nffJpRrhpFSk6G3+XxtqsgjuVq2gHERcI9LSbn0OZpj/WLeC2L5J59M
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:16Z"
    mac: ENC[AES256_GCM,data:IhnQvRz+PosICw4G/rz7WCvTKS1F3YhqtkXwK5ONwtkrK0gvWEUc4FN8Tx2m9Klqwm3WqwHyKTN+r+a1/Cr92z8UGPdgFSbeSti9iaS5FDS6po2U3RlOVSMB0Oz8wjQ+yM/HRbv3k+64WzB1eDV7HYSIA+Mn5e4a1WNvFHV3luA=,iv:KLgC65unF++MMaFSc7qARvhDIPSTvcPoR+6kTpYq/lw=,tag:pvrNeeMY1F02eEB03UPDwA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
