jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:B66OFh+AcN04mLnxwn/Yuq2GLSJ45GVdMnb0cZBN58ipbdMqHAyuoQRYVXfqjRFOU4S3,iv:AHp5bvfHY97UDiNEqtL3WIlHKG/R358s68wDN7Ro4XE=,tag:7yMS+EJzydfmwrCjPEKKOw==,type:str]
        client_secret: ENC[AES256_GCM,data:Wf22oGsCUkffVQmbrvMJ8tvt44sUNqpZ1qRFH+g3dFFkwcn4j244IiQ+7SlY1A5je4Y0HccVKBBYr7wfLUMwffyipgQWw+7PNgh22EocXh1/he5DAZU=,iv:Mjb5xNZR/laT8iTofpLfnivb/LkC9JtfduF6ZhJpZgk=,tag:Ql+vZ7Ja0R+qrchAF9nu9Q==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:ijxjFEnL02nQF1hzwfgkNEWhNQNCcylmzyss1uV9yzPmstZpoVUA3Nx4Hu3QSRGuF6QenIhHdSrMUK4szeFKIg==,iv:enNkKkfX0crQJ47jVertbxAEV4xdkQ9xGOGQiz3BZKc=,tag:chPZz2ajMa3gT5FR2o0uRA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:18:03Z'
    enc: CiUA4OM7eJcNPC5h4KK6E5D6WjPIBAm6wLJDWv6DvNe83u5+Po7+EkkAsHDEl3CNOOgLa+AZtMI9lVcsiSc+uoGzXpC+DNbFdjUFl82znsEZPszOvAoPiA3O6BSSg7hxm54RE47Q+Nq0ZPanQwrrp8IS
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:18:04Z'
  mac: ENC[AES256_GCM,data:eG4BCaOlpxArTZZXaRdaNf19XJQ0roRBhLoT/4AM5SiUIHPDmlB4q2qnuXfpV0sQzXjURC71W7luc6iUJ4vkrJF1YznE223X4nIbCr8wEBVenBkMG3jKrD0OrYXRnPZIqGVQmUt7SZwe1KdffMPuNJTHM4K2xGdwT5sluGFBhZk=,iv:c889PhUzBtumadA0yaeR1w0U8Yk76JA5bhkH6w0OPS0=,tag:3b0Wp24DJPpBB2ili/ZLjw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
