jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:SOYb3SSBjo9pHgkBvx3oJc36dMw=,iv:uqn0fGLtH8GH22VmZgkXA1dlXRph2lTEy3ErlOum1N8=,tag:1xYJB3bfJSIsX6HyhNSWIA==,type:str]
        client_secret: ENC[AES256_GCM,data:I2t8zF5ZXHUYngblRl6um/zZhfX2LRJFSpLq7lfjIC+0Q5vblw2T0g==,iv:KO3wneo/ZeRVaXymMZdWB0Z5WdL7rllyxD/xHJwE4Sg=,tag:AyylPqbyfGwSee3AP2BuMQ==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:OBGM57IR3E+u/QTjbDr33mSs8vSdADTcAtfN2Uqgfdv6SPBebWzVgQmQaMicyxu/Nb4mEJEt3xwUKG7xviJMHQ==,iv:DrhwuP46v1ZlxIdzcta92IYmr3knNPw1TUe4snSWy/w=,tag:52eu54gkPmlsvIC6XmlUdQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:18:28Z'
    enc: CiUA4OM7eNg4V/Fc/M8p/6oX6MuKAlboXBVsfWmf7WBnd+xp2woTEkkAsHDElw/1uiDPLWyzFMYnv5JvfCaET6LbMyDrtZ084fv3PuYYiYM7HTD0GMX3aMhUnugRgmq3w2thb6xSxWCKM7wlPsXOclxb
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:18:31Z'
  mac: ENC[AES256_GCM,data:zxnKIFKe8iZ2VgAsCIGS75bcI190KO49gJK8kuTcjA1N0yktW7N1Wd1S0pJrguvowx34oR9PxoFziSPKuTRrjR5tEYtpT+AncAEOTRTg5/lQ7mE456c5duJ39ycFww/nSyHlcHT1xAtK9xKHOc7TZsGvJ1Y8LBM2kU6VvbMZB64=,iv:w2q5z2uCZ/z+W2sbccskgTr56yeZFjHn62O3aDzAhbQ=,tag:V42nP2QnEXCsCwf7MfhbbQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
