jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:3Nut3cZSaQg0FZe1mzF0pZbY56pGsrDnFwqEpxcjWg7Gw3NVXM6T5qBl9yA1c+ALQs5B,iv:oCUjibZLNwBa/vrOMkmfZgvCWrxZSMliS4iqZyYsteU=,tag:qG5YELp520HeucBjYBf43Q==,type:str]
        client_secret: ENC[AES256_GCM,data:65cBcUdlEdr49kEBc51+oC42LSu6k3FDlxpNNL9MNi0tvEOTk9EcjWd40lSrOEMQbhNEMSOHCYYfTarqCZ5QpEg9KtMCIMYeWZwmuWkcLjRCt1fN5Hg=,iv:tSEfvb5LwTpN8MuapXk60pSv87GlPF2edPq4fLiaXh4=,tag:IGZmT1ECwjA0GvgA+KC4zg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:h7Mc9hi5AUxhhSGMCeZ8BVhtLkPYL9gol4NY1kCajL9/A7UpF5C2PoFzzaX3+svLToeS4PFfq6foEU05WSPx8gxBU6Qw2ovx9VBEitK+vMIl+UePAOg=,iv:zes1kGaBhIKgKSpasEUzI9HIipBbtMIf0mXffwIJmeI=,tag:b0el7iBgoQ8nN1IgEcTX/g==,type:str]
        stringData: ENC[AES256_GCM,data:2zVKECjGbszF5a5u7O9Fzd2iDyHhv2IEXT2Zx9XIOWvBT/CNAAU5/9gtVoq/NfEiAnqb/u7fF6vyCKDA6BAfj8SuKQGyFrjZNCQpCb8rG3F+XD+1Zr3MrMv1csg3rIjxvUQCFZgrH3KWZSVbLK3x0OkntENRJLk145h8JNhM1346H5LPHqRSg7L9+H1bxB0B6B+bZ5BKbtQkqq6qWd5GlqjPFYbhnrgh08MDUdP1f4KRFhXQFOInMKagqCVim6NZJ03rxGNVtOMD7lz4N/hWbjRTymUx2fVu+I47uFSOC9h7fOXwCS2mMpYUmrLRPXn0O/WX6lwHkxHcxVYJo+TjGTf0EvP3gper8yJdOpiuiIdOqWxrVCkvDgcBjxy1OWX5ko5EFlmkKSldL00WHsNhZcCN4Bx/xXfYdtgrzfYjLwXo58fkkB0ShBpIh8ialpWZfXzuTOs+KWYYpfeE/14rjnt8HgFhkrcM4quaxsjKZ7Jqj813eKB9HKUu+H/DsKab9m6LB3F9pzhPqyjO6es9xL96N3nOV/HbDb1hiH6SSlsZIZHeRLrlCkd5sQWB6Y9mJv1+A465iVvIH6kvwh54clm0UEenc/ppA2z3MDfz5SD+zP+CfAzJh1hP2VS/m5b6W76bczfAsTRyqEn0rA==,iv:OcFd5AM5W/zpvcIES7kGvO89vZHx4d1gNDpBgdqhFAo=,tag:YXHwzgz2BxxBMvK6UZm7jw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:00Z'
    enc: CiUA4OM7eHddz8oq+NXJXTfi3l+TynswfXw5sxIoh45RwlpsHscBEkkAmy+ekhKrzd6bld8BqHPX2R6uaqxOjiGrzsi02qV7dJD95N5SvImtCl2iulIMeuvzQYPeFP1ya62oTUyODFBSBnBx3w2LAz2x
  lastmodified: '2026-07-29T19:19:00Z'
  mac: ENC[AES256_GCM,data:47iz+c6BibfQ8nKeYli7KCeaJuB//Bug9VFPQZDuN0hMptCbtdOMXwN0YUkm/zrAwCXo/kJfd3EjLL/T0hOEbNv7eeFBE21aZijpxJrMit3mK5O9YqoHgZFwddrTgNbybA9MluDSuhv27dISamenj0FROIRyZPLnzTFhjIOJrXI=,iv:28hM5zJCG1dzGoR659Ir9HrNXL+V40KyyXRL19xHycM=,tag:iukEeQWc2iJIbGkROuhsfA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
