jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:PfBWo9sdCmmZ3bNxUNmOPiQ4LPPeCeEuSBP8DT3ghiK87+DNnJk197EGna8GhqVJ8qmt,iv:Grh/G86SeV+locDUCZfJXpgY3wU3VHZMJfDwx+WyQ+A=,tag:Yg4/ZWnKC2ejL971o/yHIQ==,type:str]
                client_secret: ENC[AES256_GCM,data:8ymZEbnfhK5PGz6Mv3z/1gR/B84paIY2NEzsPNcAQWjR/Twhu+a8cwEMAbppArhSPFzW24YQ2VUD7NLgx62GtGV3sXm+S6WHeB+Ca9jMEAXnpIof0tQ=,iv:VgnBdZe3YkCEE+ge7rTnhuHnL6mfRWMhC2DaEmf87NU=,tag:szFF0p1/4M/1deosOoiNcw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-03-03T02:37:24Z"
          enc: CiUA4OM7eAeFX6hxNGzyVyGX4V1oivoPPORndzV5qeeQQoAPJP9QEkkAPHlbmbmOFjzZgY/lNqNwVBlMt3cZ4qVQnISf+cEDyw9iTIWgm09OZxJblOPKmUAvuzi0va5KUhO6c1K7BAENgKhJsoUB0zie
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-03T02:37:25Z"
    mac: ENC[AES256_GCM,data:hvF4i2LgCPpCOKIODg8cti/kqO9dMZR1cPI52nzjKH4tJiaYn93w726+NfSlMQSmNI3/wLBKnVrhhQ9VkylM/IOGCJkn/DJ/GeQkYwq6CsYC1c48J0fFFF1MXKMGSDzkN/f+td7y7xm1XYTT+geJhGwOb2ezCHcZ47rYCTYFuAc=,iv:2RPoaQOsnitoJ9ldQHJ8oy/ZHoPzajgUU7ooLoQOxyM=,tag:IWWIt/3NnqdGV+djuCmRdg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
