jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:WqwGJsW0ADGw+BDUG1DzSrPiErZC+poLesiDxQT6MoghAM/sdmc64vh0IhYnYZhyZ6Dl,iv:cZ+7MGJcnyDlSofalVXC8WKFmn+wDdR2E+A0rvels7E=,tag:ews5l/cPnsDO12yZICsAsA==,type:str]
                client_secret: ENC[AES256_GCM,data:tmtj3zQTswe8uK487HfixIeg9cnZdEuiLQHy9wjWi0NqsrrwbhD6WmWtb6j7QxSI5GjXyv3QPFn7yqhzbApCcPVHyyG9Czvk8R6RFrOvGBVrbFAENj4=,iv:gEfnuWv6PYLByif0jFyaQJ16KPqZBeN2XbdtWL83vog=,tag:hkjMSZHW6D3r3tdusYoDaw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:2lYBJEMpNhLsmsXou435OM+N1NDrExbyp3FEPNpRnLIbWrd/tIQoBcyZWBP9ngWxyd8LWFs4nPM03UPBe2MnSg==,iv:C40cO0c/nU/yiZOiUvNGNHEUtAg4mkf7Pag9LjFFrqk=,tag:SY2O5Wx4202jj6yb7vYgPw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T14:51:30Z"
          enc: CiUA4OM7eMI959/Lmc02tbkXubnXADXIhmGoP4LWM0OOWCOLYVjWEkkAsHDEl3Jip7FuZ9W3IGOeIiGbhHVRWPlpojZygtaNqqFBllZobNoN3WccmMG9exbzpO7RbdFri/dzs6HXlMTSoTDEwewm7/qR
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T14:51:30Z"
    mac: ENC[AES256_GCM,data:3D7JQVF9C9IF6gLqT3rzFVDWcJpIhaKxBylMW9fOQxPTzP36nilDDxvhXipM1tRK/3LvFtCpTRTG4XVs82J8P301ewvGJqPLAbL64YUEzuKk3RrpBUOaIOEBNkjYIWbk5GaFZTaUX8bttC85VNsIFmuKkiu7cJfF19dasTsMysY=,iv:HcaOGy/32QIMVEUEOzvAQ9H/2SCYT9CGA6Y9gKtkPoU=,tag:vTJdhC5Ntbt/3NQfLCuMxg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
