jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:Oi+pbD5HecisDycLWxK+atmk5ZWxwQSxyNYAqeXmCWKmyWEoAhy7jSzx4z/t59iumpJH,iv:e0mbwkgoYbXhc4+SUjA7DbQfwhvgsCkxyZEHyRG5Vx4=,tag:yDvYXqv/NxosUpfunfDTUg==,type:str]
        client_secret: ENC[AES256_GCM,data:dNpS9ftGAESbrNLOwqSOqO931czeB08w58VCuP9KpuInmaGU168dovK7hpVWoo8yH4WQDK9gBkC944TfvLsBeG/p6ex268DgSv3O5SAU6qWxY/hhfLQ=,iv:C9lKATqtZuLAlWsDQ902PMfBaUubo/D0zLoKGWHgMZI=,tag:plm/Cgn40qFYnuJrrXO9zg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-06-09T17:13:28Z'
    enc: CiUA4OM7eNZ10cXTeYA0mTQ7MqEkhfbwWwUmFDK5/NAB7iu4KWLWEkkAmy+ekqK29wMqitiqtyJFCHp9cPDHpcLynv6VERIBIAXTgsrOfUx3veRCSwpcX1AUWUoTz6lUD1A4SwNluGXoLyQq5pgZFoID
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-06-09T17:13:29Z'
  mac: ENC[AES256_GCM,data:XeaE0TGw5H3CSs0AQ32NIfflvxuUnD3Gc/u0bX3EKXGZEdksm8ZEx2IwPOm7UmGK280jU231CsvPSGL1fhodLNVOSRTwsQUDLrvO2bRGuwWqekzI8QlnkmC+gTMT+G28T6CfW4OjZyLznQCngz8fdVgoM/rA6uOuUpLhj6pTJAc=,iv:HpfqsuecggxiTH/ikGaSUfAECAu0K8JHLcb4OQFYPbE=,tag:+6manHLc4wLFZsjuYz6mcw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
