prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:VOTOXk8dqO46A7vPxbRl8OUcfkwoiTvaJWrv0wdinOTd8lC2DEb5ZfLS2llU+C6BQArsD94Jl29GJh6XMzD3bZdjeqR4wFvyu4nBkj2TDFgTiYEqoby2iURU+qP9bFfpqeypgqyouyOcZUKUSIJy4omzuZmzVzZHnr0Da7TEviM36QrUSugEKaitIJwy/XU6vDo2hIQvi6J6RWiv,iv:j2d+xHtBAqQM5CWn84YWV20AcvGlocDLCDx7T4Vo3RA=,tag:/ZSob4SyrzQDJ51ziFZziQ==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:G03MA2GhF/Q1AUC4H3pB3mjrEKwNNJIdt8Gwi17F35o+GMZldpRH29bvCdK5IixLrQVRB/w7Tv6+Vix5YMdfEg==,iv:WuRxuZ9le6mIM8ai8TKm4dB4NaixYSuh9BtZbWWD4gE=,tag:+SZlvPYFuJx1IS3FUNn8nw==,type:str]
    password: ENC[AES256_GCM,data:HmW7FHYgFm2y6jbcxJ5Zy3swxBjiUAci9R2fjHHnp9YLEbq+/NrAvJi5Rq0IoixhzWHZDbKKMB9FVYe0KWBTpQ==,iv:re9jMWnD/PM3Hi8ywj7gj5bffrVCVxDRwmteQYmgFqo=,tag:qJJRWd2YkwRC/j9NfAVTXw==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:EA==,iv:SrvMrzp1PJygqmRQF0npb4djccW6yWOkMQ+Nb5+KSwE=,tag:BA3Qqv3OuMiq2g/GhfVG4g==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:aCEoYC0FmbZICA==,iv:2v9aQqVT9wY9RObPgKCZYtvMtg+zhmKfHEOTPELYxfM=,tag:YJsjtwo3TD8z1+b6IaJNYw==,type:str]
        orgId: ENC[AES256_GCM,data:hA==,iv:9UEwf1dWFF72suis4jgeZiRBfEcJptEm+Xm6AyreRsw=,tag:ePbVJqkb3yJ/5rnnsuYmdA==,type:int]
        type: ENC[AES256_GCM,data:OkJoGWLoNQWNhw==,iv:KTJQCEWHlLVL5Ux9LlzhGpp6yqFEqsxT/Tr2w0i6wrw=,tag:7b+DajiG4Zi2+yZUmX1xTg==,type:str]
        url: ENC[AES256_GCM,data:mT5Mx/M0JQ/DZMRakwn75/okBjQ9i8OJ/nWxpo4jWR0=,iv:gkJnuT2zZ2DY5s32OEFS9KtxKnbOYBn0LFPnP816mmU=,tag:/mA6XmQ4V0zq0C6hdf6L7g==,type:str]
        access: ENC[AES256_GCM,data:RsMW7kQ=,iv:Z82devM7yMz3lt/2TX4JCVtIkImndKIjta/mm4HoR6M=,tag:IXqz8iBOhB/rDdciQ5ponA==,type:str]
        isDefault: ENC[AES256_GCM,data:AnhnzZI=,iv:WdqLb8uTjK9wH8K/5IpAmsL3scWsF2m6PzDDncnmjaM=,tag:Qro5+unZgEGAkmsS8vKOag==,type:bool]
        editable: ENC[AES256_GCM,data:WOCqorM=,iv:kQhCVST4nASTZSCZ9Z1lPv8V8+xbpUUq/Q64B3N2IyQ=,tag:26Nuar5kPASl+5dP2lAG7A==,type:bool]
        basicAuth: ENC[AES256_GCM,data:VWU58A==,iv:DfMt0vthiB8EyTYsPhB3SesAsegT2qYmQH/5w8BmdG4=,tag:XnZl3qmj0Xn5NGHc586mlQ==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:hExPBYoQwAduP87syoqu/CUdZCHQw92hmSP4mCTaqg75tW60t9E82zy9foO74NGSQQA0l5hKbPyDMEg4PQn5lg==,iv:1PY5Hb9lxN+u0ixIMCHMzRB8WVfx9m9ljtit8e19VHo=,tag:RFgt70sxaeIwK9TLSMP5YQ==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:2caKd33CzelbRYnmlVXWaWNVm/LwwZV0tRPyN+mjhnEQAQUjafu11tjnCCmtGpERa1LMXFuLTxeEli9jGxLPsA==,iv:ucolCaIcO9MbNntYNwn4TQxe6XX7KkBCBUWp5ZxnadA=,tag:eh1uUo1xZUqno6dRgCsk4Q==,type:str]
      - name: ENC[AES256_GCM,data:5Gm8ZQneoo6U15UsdHOJhroNpscdyMvSqs02wUQtIw==,iv:VGeD+5Dz95uSapJrtJnB30fNquxTXcEr7EKy9UL/9tM=,tag:2F81phKKZlm5f0j/2L/IUA==,type:str]
        type: ENC[AES256_GCM,data:dv228srMV+cA3efmQSihUybCLzpqJ23sTbw3AdorJg==,iv:tyZraBSseyMjVRHTFtR/8Omlkg1q96+6MlVj5CKNpOQ=,tag:CMNMEvUISN2HpIIwWei0eQ==,type:str]
        isDefault: ENC[AES256_GCM,data:ic2NLKE=,iv:I9ky48A2C32rLykBAzXJ84HspQR32uufWhaHRBx0lvo=,tag:tDEsk9VACsuQ4+18FbHKCw==,type:bool]
        editable: ENC[AES256_GCM,data:OGp0Mg==,iv:5YAuuVmzFi/99IdS6x6j8hJddhj5BnztKMlV7GhmgSw=,tag:XyM4fv4aGAMxdeLVZBMUGw==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:uNwwV8qZIfsAcTLdlA==,iv:pb87NKxLGQzuQA18hlEge0IjM/KrIoWfkpZqPE+B4sE=,tag:SGMMY1oE1jndeWPGE6oqGA==,type:str]
      value: ENC[AES256_GCM,data:w9Gu7ccl/WINJoqP6L7gHsNikXaLOZ9XrRClogSpP8xfNaZctkwCb/QEbnP0+llye8Qlw8EpvV+df7TRtPQXTmW2fJkLo33QTJVXhSEnNFiD3Let9g9eXSS2gEBnNwQUxRYy+PMHB08kdxedLPDKSesG4AAZ6+wn9lxtkr0NCh73fn8nxba76l2B/Q1e/mIoMtxS753V/ywocmNRcQgrFUwcShFt23JFHGwOcFdR14RGCw==,iv:ex+6/NA8rUyBbrLwhJ6gc8vRWsvJzc3xZ90WB3h+MwQ=,tag:GjYMFZJBndHVkkthJcN2pg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:7IDL+XXguyGLhENAmioImalBc/dcIZRtJbYyuV3D+1tueocDGpB+oAW2d8xe9UoqRKfgehI7ICdtd+cY4ZvuVg==,iv:EvB7+QbJOsHdNdweKCpDBnZl/Qbz4Di3z+e3p3xzN7A=,tag:tVusHTMQdJRoHOt7qcnJoQ==,type:str]
        password: ENC[AES256_GCM,data:aipFUQ7ih+3WAAxoAgl0kssOIE1MaSSysSzHQGaYiWfLx+WLuHmj5Xh0/InIemzlgv+uUAwD14hvNm7zHQ6w5w==,iv:XnGTK+091EYGeCk6ARAOUfblHqc4FBhgj0hgx2XvuLg=,tag:/gIDbFb3m+teREtpfunYFA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        zaepio2aingap5eehohneiLoo8ooHaht8kiezieTh2oneiRaitovoLeenemah6ti: ENC[AES256_GCM,data:+Aq21kQQvPSNYY8SWGdGXvUf7wdY+P/oHREh9bcIhDg8fbexhiMPkPNLJXOKt1+qiH54DPJfOWB0Xs61,iv:HSou1Q/qG39QHycSy2b94n9Y/HT+CGucVBteJP9stfg=,tag:uRBIQ9BlCsXFfs1dGQrQqw==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:wqMnpg==,iv:F/aP1fm5hP8RxE1wJwYYgMRq9R0Iz0RBLy2kWEkFnG4=,tag:GwhdafHLdxlBBrLVq0II2Q==,type:bool]
    username: ENC[AES256_GCM,data:tLZA0tqYgF4YU0Pz2rCJuL+vtiigCosXVV6ihTgJJ6OyEhZncwkWDa7wpVUnAquO662HRLOtRye7haAC+xHWAg==,iv:UkR11vccoPPSv6IQdZ2AiMiH0LKNhPKdP/DhFphfzKY=,tag:lJehCjDvtx+Gs52vgB651Q==,type:str]
    password: ENC[AES256_GCM,data:eJLTHdrsUjwdbFgNVUSRu6HjGYYlIkhtpRhOJiCh9KnsxQJhzHdxCi5lkfiHQiQ+zqR2/xJIIN6JiS5vi8I78w==,iv:SINokzcGyfNt1d7rtrseXyJb01avOr4yysfIx4exOr4=,tag:M6rMrwCfYiyFMwjc+Lbwhg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:54Z'
    enc: CiUA4OM7eLlI7pk2Ypxi7m9dBmhzowc8ykRAdJMXH8FFLjmmPeu2EkkAPHlbmUZ9dTAOB/wPShkDmf1Bk78Ncooo9RswIvnS2vr6rZRBACbM7S6VxEjV9s+nCrs1rNKTVFlVpsK8CO0xzpr5RkMhiqX5
  lastmodified: '2026-05-01T14:40:54Z'
  mac: ENC[AES256_GCM,data:Q9Oh4ABQQ+T1tYmubHh+wrBJNOrfLWJ80noJGcaJHY8YHlcPJj0GPYy8RAGk3SF+N/yhXVS2YedWvJawyhSUBcdMSKxmFxb3b9M6fGwL6D2c1tUaQqOu2LpiSlysgLellZhFyraSI1stQ53TTbozynpSG+t0mFsD/RstRSQo6Ds=,iv:cQ2u2ZQgpkP8T63/Dlsaqgo8X1/rtSx9zmDsom0tqoM=,tag:0WI0Rn6sqfzYSYxrKykVBA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
