jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:u1XBRCbRc9/9BvFLqpa3B0uCTWu+PK2xCjw8HUHGXaIZBV5slzatNtJBCMMAkmkdw/dz,iv:CQFjX6nsmrC+SAHlTwiZJSKO7DpPcs7N7+sK6lF6TPw=,tag:2ugT98/pw4pvlHP9mltWgg==,type:str]
        client_secret: ENC[AES256_GCM,data:X+GAG24ELOpkdXehwOTTTOU1b1Em/9PNbxKtMhvcb1bETWsNtGxqv9ZgFA5XrSNh/cA3KUTOimHaO7B3iJ9XrsRpwTTrujQZAZDmwkf97+x4brGhwwo=,iv:pSq5V0u362wftL6aFVdlAAA2DEkv5u7YhK+ica9OY68=,tag:2oMzRKhczoUpU4wUVJRMTA==,type:str]
sops:
  gcp_kms:
    - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
      created_at: "2026-05-22T21:00:40Z"
      enc: CiUA4OM7eF6n9K+ZAfkNJ4WXHVk4sqZ2ygA/pX8UNZ/xqNyTtYMsEkkAmy+ekotetG74LH8rNcCG/D+Y9hAwyErSBIXb+7bDlwxH29YR2n7R12aTqFJy2vZlSU/n+ZyIhtkgsczVbEEKnT5TePxMOMsY
  lastmodified: "2026-05-22T21:00:41Z"
  mac: ENC[AES256_GCM,data:Na+RBue1WygfJ5d0THk27K/bltEy11Cwol61iOveMHvkZrgwVQ+ya8Y/VUGhL6pEekELJlUywUixciOdYZn6IcM8I7QsspPBjnk1DWjw0w1e3PgNbgxL1oMvc2oTKEr/Ry7gA9E2lUpRedF9LyzbX262MTBohBNWyH9mAwdfPSo=,iv:+2SOFdoxqTZAzLcNk3GfvlWCE0sP1H/vdtln7/HH7w4=,tag:kVOcEmu7lb9LEOW3T87Hmw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
