grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Uw==,iv:9Td+ioyt6pd1YBFAd7bsPOpD/KQ+s5aCifl2qq2UN64=,tag:lQ+iIPtAAMrBGKaNR6WqfA==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:L7hij+f4u6Zzmg==,iv:iE0kKI1q515Q01QIENO9lKw1mx4/LiwBfAfN38F9fOc=,tag:prt7JO0Js3fLHqm2IOi+Mg==,type:str]
        orgId: ENC[AES256_GCM,data:lA==,iv:ULP9zMwBxoiUzhNje8wdrFk98NhVjqbizeuWrD/XZ6c=,tag:C3aDgIUBULn73QwerDtRsg==,type:int]
        type: ENC[AES256_GCM,data:g/R0bVaQU0iwJg==,iv:UGibvW5234ZLb6L6QTCKNPLYLl5nduz2XbJ8doldDOI=,tag:IslPbJZ+ve1Xrup5EMWh3Q==,type:str]
        url: ENC[AES256_GCM,data:ikK63cP+mbfb9IWF9YQykXq1z1YN73TomfxV4QiNdCQ=,iv:lPS683BbqgRdkeKiaQMLgqsznS4JgDY4QxmsIG8mm3s=,tag:5Irv0S9DsPpQA/CRl1G1gg==,type:str]
        access: ENC[AES256_GCM,data:ByKv80k=,iv:pc8/4sBNFMUbMEDPWY1/iCjN9WTntVgh6MMjq3fcRdE=,tag:VXcKK2oyz8Z1QSoOdE77FA==,type:str]
        isDefault: ENC[AES256_GCM,data:mN81aAg=,iv:L+NKi6PijPEQ/yjjOJoaD+QYs8e7+lg7jvU0DSZZgEc=,tag:zVD9Ivm3/J6QAm9XE1HMDQ==,type:bool]
        editable: ENC[AES256_GCM,data:DwrzeZs=,iv:2/Pcf7XkZ4flA7bM4ly24SUo8mHVmqyqMGA7YY2qsDg=,tag:W0s0nMfVvfZZ+Td/a76AWA==,type:bool]
        basicAuth: ENC[AES256_GCM,data:aSdoqg==,iv:+8q6veJX6JvqmNoEn+b6ldR8hizqwQjrCVN/BmM++9w=,tag:1zoJtX/zTrOWzcpB4t3/Cg==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:tchxFAVDYdkRfJmjY5pEl9RwmHEzuXquZZELkA0s62ctDqiJ3V4m2D/b9Y4En3mpuOpLhngZ9SiD1Jg0HQPb0g==,iv:wXYjywfP6uqmwBNzEFMfsYIB8joHiK7hYkERDHqzPCk=,tag:D2ZEX/t5Aw3xDHVaQQhtag==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:0Hdh8lHl/3RVAVA5uKcf5tOvkDVmnQw/2r2vvMIWkuCvSycPjGe9yPtaeGE6NDRjrj1+d7EnC7LYJkurXrIrxA==,iv:LMh1HnZk7t9SOhukv8n8xgxAQuAhK5+MGKvYHU7mJig=,tag:aBloUtEZvdvUH6JslKlrfg==,type:str]
      - name: ENC[AES256_GCM,data:qbOo2RAMUgd3oxPSI8ZzweKv/QVwBSzgRWy15MwPbQ==,iv:eVhInS5SXtND6hGFv/dxXfHJggbFCmg+Egs45zaJFxM=,tag:tnHI4ibFqOyTOmcjwCADIw==,type:str]
        type: ENC[AES256_GCM,data:ZQZoeUAHx7Z1k4gQ6mqtSkw+EDlH+Hy+Ch2/MbxGeA==,iv:Is3NrLTawaTytVUt2IBBkZ5IBYJADlRNh3TmZuUZb6M=,tag:qK/PpGOHoLwHWustl2Yq6A==,type:str]
        isDefault: ENC[AES256_GCM,data:dAnbmQg=,iv:yhx9UoYvDGC69sc8f4orx1JvZUjHLoLbK2f0r6o3IUo=,tag:Y2e1yz5BRNZmH9NSL23K0g==,type:bool]
        editable: ENC[AES256_GCM,data:Ju4pAg==,iv:MNEyiNPUIiv9T5o/H7OVFESaJkwj4qSEbfNQUpWE2jk=,tag:yZykKOvS2JXaUUmA2xJgSQ==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:olp6ZFEYAbuaDcVzNQ==,iv:x2PErg5g1kHTrfTsscmZfAorSHNXe2/QDain5uRYTTw=,tag:YZaDDbt7BnvIplIoylQghA==,type:str]
      value: ENC[AES256_GCM,data:OH8AY+l9ABnU4Lg9NACLwuFqyQJlO7S6x1PSvYfI6pZLyhPncQ5isZOYD9GaSng6kZrBnuPeROU6bGALLhQw57zQYjli4uqcFL2P5r8Fg2yRX6sFIYWxoswOcJk5swI1rz/qlVgkGTK1lzBl/MTVloYMaXtytTRVqvWI7B/e+4Jb6Zrva+bCOnh2y+K9FXWwKksFC+aQQW8oN2vrLbtd4oRbW3uTpD7DWCmBgVGDMbEXVA==,iv:ikhjhtgKM+fmOz1l0r5Li2tDhRPsNU4GRPL9WC75nt4=,tag://7477Um++8o41mRcYZ/GA==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:r3vWvMe2ss9KJ0lBEa8Vd1K2tf9o3ERKgEfloY/ohxXiKEilBeFD+oSA6LmQwFXRtBOc2KwXuY3G/QdHgOTR4g==,iv:a93ULUn18mH/sTcoSkQ/rhHyHIt1jCgek1tvuKLCp+M=,tag:daL3bzJbcfpnh9S+ZEE+ww==,type:str]
        password: ENC[AES256_GCM,data:X7SN+IcaYuH7xmQehzDE74t/QZNJ6Yj4D6PbiT3p/mzp9lXQyA9VOCdoa2hX4xhMxQMWFSkI1QNXtvhx+8VHmA==,iv:qvfY2FOjJZzG3wwIj7R4gX1lw5VIZN7uLMt1/zVKJhg=,tag:cQlIUXa1nx5oGwXn1pdCZg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        zaepio2aingap5eehohneiLoo8ooHaht8kiezieTh2oneiRaitovoLeenemah6ti: ENC[AES256_GCM,data:MCqbhAqR9t+tpgIuCLXyY3gRTgYM/zmoZQdwqPStjXz7HA5F+3ZLMC1PR/wm+WoNsoV1EJ9QDFmVQ6yk,iv:dFK/1Z+/gsD56RVGTEsXyf5dcLdd6trREvKm9boc1wE=,tag:8cumnD0DNHHwOraym3tz5A==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:OZxBTQ==,iv:0UKwKvUMelwH0MCJwwgepJNM05lGlZkx0WtfFYs+YMk=,tag:jc30NuTGLsfJnVIA5Dub4g==,type:bool]
    username: ENC[AES256_GCM,data:218qjfZFayUihHb46DQTbeu4dNB6DGr/UzLpdoN25IRpHLHZ9IPg2k5sJKYCFEAIaU5DZgyqoNG6Rxia+8izyQ==,iv:Km3xDgl17PvLJqzn4ORFdn9mT/RXglKJeLnakhGnD/k=,tag:LXjJi/u9kCN7HdewcnBUtw==,type:str]
    password: ENC[AES256_GCM,data:PQZewqoLFzJ+t5nuWcild+RL3M6cb4f9h+JKs40gyKCg7YICDsiT8weFukY62i8A6PrSnqHzSyn1qXRn5kSF3g==,iv:tMbJBsBOkAVaZSrIUN7IJcAiOD9I++748p0Mar99Alc=,tag:CVmmtB+NimldLQkfN0dKsQ==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:2aqJXIxoqiJHD/uOkYFKO7VKCh4TkZ2sRjyYRancJ9vc/BeNcYIlsb+kNtVIkho00YnOJnojnKMKQ9SHzq3C4g==,iv:jBcQSDuSeVotMYzoivfyruWWHpahL62+3hscJvu/QE8=,tag:U2ZuMRaHgj/b+8wQK+X3Qw==,type:str]
  password: ENC[AES256_GCM,data:7ZXycx+vgjHENnwWuyvIj8zg1kZirO4u/oCVb8Rwc4E8kiGNYEMGsZxiC0hMVuStEQbkOcPK71708sekPuRKuw==,iv:EaMNn5UdJUHokm0b864S4dcf3Eq4TNiUnivfAQYu9Bw=,tag:eb0feDD067hXB48WX020cA==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:36Z'
    enc: CiUA4OM7eNUk0AzSARPtZ8hT3HMRl11UgsJ0Ygatx9GZIzRjqzc/EkkAmy+ekrHwxJgGf+Gz2z0Oi29GUe7NFntTdUj4bRLvTkC8ZVylvduVIHyI9zIew8JU8yoeFIHpbaA6cTOiKyn10tkdsFcBsmUh
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:11:36Z'
  mac: ENC[AES256_GCM,data:xdQHCD8Thwi8M95WJeEhL0hndR/UWqdUhNzPiQeg59k6ueKzFRBDwdRvCRcR2Uz7r9apGFdkhx+tSVhFpRv1gl125mTL1Cv9i1s7ls61hELsvQUlccJTk1T1yJwAW9j2VTSeavm2Ut8L6LWeyHUAeGdQ5qAFifrwmrBQJrpsztc=,iv:6IMHaxM2M3V1jtDzXNlC26ILdn7D5nVeD/brc1EXhis=,tag:akKsvV48fYpJodA1QyTe3Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
