jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:KZ1NoL8snM22YHdslcPVm38RirNexTU6kbXRJeeSTwuaD6lJw1iEtbYKyKORE524y0Cn,iv:8XHJTlZJPfJZOBgwVqbtBFVyV+iSrLfI6APwoqxnpac=,tag:wBH/3ikabtJFeH6aDz6Flw==,type:str]
        client_secret: ENC[AES256_GCM,data:kJIx14KWRwxIiXEZnPAtsFfbE3ZDr2DNqDpXr2Xslspw76a2PJKDe4niykZ75gvPTDnLwEb7nxSa1QyHS3SaZYGWQTslxAnd0F5KApaqqMx8e4qUPKw=,iv:WpaE31Oca+hYoqwfmE9c273cJiFDruyFe8TQ0WvJdFo=,tag:qRXRsVSm50L/SV9iAdP1aA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:37Z'
    enc: CiUA4OM7eLJyxKaoWcYpx+FbD4tpdfJjvgm7guHFmjGcWAjYNBv8EkkAsHDElx26IOFImIt9ilTI6AGxEJ6XXrhFOARUBJtPZS98FKQq6PcvnDijdmfYnD/7cKETUpr3RVfN5lmRQ3TsOhYkjoK5Niz6
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:37Z'
  mac: ENC[AES256_GCM,data:ME+K5byMKg8wZ/3bLNGzvsFtKdUtTSACZa3WtZbWXp+oXlbMI+10Ft4+p7+McKIB1G0ASUVdCNNhqpinPzPZDY89tvJg2+vZPhA8sEfVyr6tZFq7aDOcFgkg+NfAEO80QGKaJfSNbxD8BGjmdiFBLqK7S3SazZQ+0BYfLhR9gKY=,iv:LiMPbqupozNWJNcepwEZuZoN9KQnqYrJw1AdWpwYOsI=,tag:NWB2otQc3to1jpp5rss4Lg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
