jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:jgwmYtwkc/CDAvKOFl8woCl3m6aNEqA82PFBmmN3w1AQ2IBiaCJLPIeKG3CPI99w+km2,iv:IyYQLRitn1tqrj5i6PtqktHDVy4XMk2aSEBWQHHv+Ko=,tag:o3SZyuAO5PTLMFcDYHe0iw==,type:str]
        client_secret: ENC[AES256_GCM,data:ayLjn72ogqu2vkpcpaFyJjJ1CwcqryTiOQ/oVjxp5chCf/dgW/ORAgARboRMWwpk0uDobl+EN4UjjxKCgTXF7zvfad19Yn0MISDtqg8l5OoPymGMtvE=,iv:6EBFKpS8ksMNw1CQHtpj6XeCEgJhNDVCEQ8AIi1pG6Y=,tag:el5zah+Htgu1hbt0B09/Jw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-30T14:47:15Z'
    enc: CiUA4OM7eKK4TSw8iXLIzf0kppCmZl8z6oZwPKm+ns4+yLhEV+/IEkkAsHDEl8X+wEx6dUOpdEK4oZgHkmt/oR4bot0e09kQfN4hx/g2HppN8R64z0bnBRrsfduu9M3ifkgZh0NLGwapcKMdMwu3EXKB
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-30T14:47:15Z'
  mac: ENC[AES256_GCM,data:dJGn6Q3PJraeu4Rz076MWsmUXTR7SQX7cQlEFpGuWKaYPTdT46ho6nKb50PqHKo5qa6jtoGXv6H9hs6euzUufjEABTAnxNdKUcl1oWzCn9LZcroj9xuokBuvCevHTwrT6H4v3ufndMA5BselypNAAedn5tzwty87A1bPeISlah4=,iv:9sA9sjCC2Op9XMTClS4dfDVI0ZCi2Wu+L/19xw0Ipis=,tag:qMvDFnRCcomcmAl5niDRfg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
