jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:j3cH+C8qQHCSyw4ojJLjE7nQWbG/McxySqG2KDeWKPipAVO4tuhDXcvdVN/hr7Lwll+fGjYWduxqtPnEujF3TwKow+VbMwBN,iv:5xxniuI0uyIF1MzIrSEm47IHFytK0IR67Jfgv9YenpQ=,tag:CIa2uBq2dFHbjRRXqsggZQ==,type:str]
                client_secret: ENC[AES256_GCM,data:eo9ms1ufJWnMHMN6NI4M+aC+gJYqHrh/gFO3Fn/WLXtJLjE=,iv:pvxC3TWVEY7xhiu0bYLPTF1s6//OTB9yhAvAhcXaLDk=,tag:k2eXDNAAUeVahk6OiIj/Tw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-07-01T23:41:26Z"
          enc: CiUA4OM7eLLPWGFbBVow4Tg3oYN1KTg99pkcWmBZBe/ivhTed2TWEkkAmy+ekp1CzbOGtFCtnW5nK1wF/7WsuZFvkeIJyqNPRB6+HyV14lzL7yEOfca/DFl/yyeTflJRLyTVRTOuA4P09qcCiYzerfFo
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-01T23:41:27Z"
    mac: ENC[AES256_GCM,data:uO8H4EZ9WGCy742Ofo1xn13ul6Exmjz4YzemScrgYV5ORWSQKYZ7BUcH4LfVbU0cnfiC+Hsp4j4hKyhEIHeHwRoTw9AIHF8IWyjNYDpKYC+XyYRh5TpnOSRA8kVFMGsjsMDw/FwtC7ehEDbosbHwKtt6rxpPzD72TIwAvv5stwY=,iv:0SHjXqcluMJ/D8r3D6yK4+x6wIQAuXphh4xLUP1OiFM=,tag:kqy6/KTLxEhNw5KF5vfd7A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
