jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:VG41vAyVx9HlPSde9t0K0fILML3fiSGOXjs4oeputSP7f3CoMOBw7MoJG0UCQureHV0f,iv:FYlVhi037iJCoc2cknquiCyVjQs5PEcaDbRNNhU3bpQ=,tag:+z8tdPEE8lHvwJy1rb6t1w==,type:str]
                client_secret: ENC[AES256_GCM,data:5HjNJc8MFGnR3b04EPt99IE0y/KUJp6hrkJP+1ppq5/tlEl3GqsuH+d09VGRJZtDnIc4atp311Pr446wtQK12hqpzOXn194Vx9TGj785slNnsT5BNzE=,iv:532gnNzXTviWCtz3v3R8FZhOlg19WR5EogtttpoGaxQ=,tag:30t9UXqU05O04Emc+87GXg==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:XL3Vb49uK3T/QZYajVFy+NvDwWDuJI48untx96EvJ/PuLcbD6lBuuv7X49caiR91G8mpj11JklS/SJzCWBr9vg==,iv:twTamRZ//2IkVretZ904ltYokWSyYQoTLUn+RiLPA6Q=,tag:94jwlf1Sm62u0PtDCXYyQw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-26T03:18:56Z"
          enc: CiUA4OM7eJGiux+Y1+qlu3J8/GoGUfjN8AifjVUi4cBp/PmFI/HLEkkAsHDEl6jY+STiPZNaJlTHOHmRdzENaIpEtat+qx8+sFPuMK3UJh2vI6GrYuU9WCtNy2DC+EG3U1PmV98Ilp4XfTJqNBj1nJa/
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-26T03:18:57Z"
    mac: ENC[AES256_GCM,data:odYZfs8mU8CxZctFw54+VSef6cZJti8Bx37fOh45x9IrY4eLnZG77RUCwgoX7peWFAxIBHmSguKBRyroP2nkIVZ0lSL5Wdr//wYy86naXoMvBJ6FsZQtCS8lfC8CN9j8Q4oVw73ynWYgyAO2iSnRnjT4Fi0a3YoHkKkLMGW5YNA=,iv:szi4K+uQiPwdTrcXhykX/L0p5viMZXCBd46JYiwZf+w=,tag:s/fGEG6ZMO8fMyQPuxTbRg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
