jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:ljzC91C4TD4hk+UD1tuRwIyos0gjGDrOEOvanewNU9s3M0ET3b6asEfGIl5NcTe0C7w=,iv:3JgflCw9VMqnO3C1s8j+6DkmrYbwnppAZx6vmiRb37s=,tag:WVSCPKbh8S1foRwkfFzqzQ==,type:str]
        client_secret: ENC[AES256_GCM,data:ZqNwfkMbk8Vc1JiHoFVF5Ivt7vKAmTH1UL8sQFn7ld+2GKIO2a8whKEQFrSSM53kYkGaBnRPhIOFuAP9EAmG+Y4O6VRiqss32McXynLFbPLHtD7ldqc=,iv:5ZNBIv0CNQKBiP83l0trbhoIwLTLWgkyGshaDe28BN0=,tag:5oPhCuHVLohDumuTwX6+fQ==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:BQVioQISIbhNv8ah4RR0288G+VGtMngCCbik9fpFyxvnsec8IbjrHW1vkJqrFmbnyByYl6rRGpLGwtrSuprCxFBa2hyFMXHAiAB65/yyxlmTwLIwUH0=,iv:mVRc7zIWYAYpyqoSAR4VN/Xrg3EIDBUABI5kI6ZuUgI=,tag:yyld/03ZARNmaZZYSNVLqQ==,type:str]
        stringData: ENC[AES256_GCM,data:/tx84i99Nq6QRA7Jq6KbMb8jif2L+9yrRgOeRa/xaL+bSXMIhg3DB9kzJGgbAVDO7egb88Rd+iiuNkgUt7tAf96pqnO+xNVEYKTA3reqeZjPAydkmNH0B0DstmLaQrjhtrdG44VI6/z/1Lk/mGMSe24D9qQvI8maN/a9msn75gaa2DH7a2M/4SsQVp2ocRLmKHq7cleAg07v2lKNdN8TMR6I7S2Jxo4LmEnZYr2cRiMli8IRh/WxaJnW6DgX44oWq5gdDwIZMLuPvSm3GfjyKl7FVhJeEZFXDaDKgxLWp/bf4zgGLe3AJyWIE3pRIWMSWBIOOIHuyJ3yy0/WZHYXJmw6HagZghWrzhv72ckJHFKBQ9FsOLHxxlrAwn+UNCrLfj2mcG05YMwMCBpI1EcF1XzeiioF5DydtgPURQpnh5f3jKI9l2RXgdly9tJsrk7L7FPOIPBFLuZBev9/sCiXtNkn8t4/dYGvkv2jEs77BLd7LoRNZIKf8KUHROStILCE+e7giKQsGDAvLQpODHRM4O8+fNn2u95kjOMBZHbq2LPn1hMGf5wNgeNBrP85Yrlnstg/c/wLXkSTotQ2VjFyw/BQT2MIwbWa/uQFUHatRJw1TkG5HhSbvByDZFTqvZ6FsoF+v1FBJbnXNV3SEA==,iv:u4MuLqUgk1cuf28Kfl/muyBoMEXapyZL7hHZIgePwkI=,tag:A3OAFAwB10IoJ92Hl0/FnQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:17:21Z'
    enc: CiUA4OM7ePHA/YR/1kEmYviiWK10eHueRqZjSQkqMpk3qEZ6qml3EkkAmy+ekoNSuxRBWH04aSSGqtql1z7FkDIMbUMsrnkrFSCxMzxFLLVwHpQWe/XPCF0AEh3CVVzTtDgK3osVUDaV2YMw4cyzFpGn
  lastmodified: '2026-07-29T19:17:21Z'
  mac: ENC[AES256_GCM,data:VPOnOSaaB35/XtzpUP1EGRdndFtcxGlqIq/Brk3l70q04xCOkA8+giBnC5WN+oc6RiQShfsDWmSkh0FtLLUaZvyBx+0w1k7Ryn3ThKeZmHFTneAGQuwJWgcKpPfNabDRJDwytroOe5/67iDEUBMBjRyV0bs8ZOyqg3bTaO4yYqU=,iv:xljuT8mH3pVA0Z2Z2tvz0uotNNSTojHoJ0aXcAW1eT8=,tag:MalAofhZBnZuAsURPtmYsA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
