jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:X50XWDmUWDMDc7VMUDxQI9TMc6Mbvw1YrzikRT9Gd1IFkJVlE2u0mm1r6hCnVxufqwMV,iv:3WimtFm/+YwbQVaHkLXV3Y+ZuGbK3B9HPKMjf64VX10=,tag:OyZ/QQjY+qezkShmkSiQ8g==,type:str]
        client_secret: ENC[AES256_GCM,data:9rDdHWPcwdVq2o+MWOL2e4Q6U1osZZgEqJ52A1jSq8veJVd9dTo4lYoYxSsysNnLtFxDq37pLmb3C9np9LcSOJNFXAJZ+PBGu2HsbVc2n02lEJIxs/A=,iv:olsZaK0mQEd193cafrg3vgy5o8la0mgFqGvxH199BBA=,tag:J2oyDaJJIDTURchxjnGc8A==,type:str]
    services:
      cloudbank-pilot-hub-users:
        apiToken: ENC[AES256_GCM,data:2NhEl+rWip+kYo7kUdMRdGSKAZkPJRzQ96ab9xNGvHwJAiRIlUx3xHvSIgtSCoOfUJvkBERwhDEUnSgFWvR3Fg==,iv:4QnusZEVQWtK9FK6NAJBd3pPmVf46Hu7z4JtHsaapmQ=,tag:tCDrruqNlRrpy/LoFErQJQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-08-26T03:17:38Z'
    enc: CiUA4OM7eO4gjJEtnGmv10qnB6Sq/a1+dce37ZVdTN7F0lh3bT27EkkAsHDEl95vYeKs3lidI7AUnt8ZKoeaihEEMTy4a3wi9pGaeu6FjoLdJEQY+RoxOIHwe6t/3qI1k3yTvef3aUMg8okaJ3JWNSs7
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-08-26T03:17:38Z'
  mac: ENC[AES256_GCM,data:POEKyvvprCUmk+4Y8NW7nN4LMt4QU4G0Uegem8UcSW2WtuN5VWTnKzj7L2gJz4PLs3g8s1Xsr4XA4S9jIE6k3MeXYUaquE1J0OfEz1Mx5tQySKCvgSJnoVdmncdQzPHmhqdYjN7lDvgSLYolPzNBQcDUnAmRFPyMeYX3eID4foQ=,iv:zlixgW3i1UfRhr9u9FItUQJOGzbDq4V0dYYeRBUrxo4=,tag:2wPCDqHwP20XdWFYr1pLlQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
