jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:JL7cZrwhMzWnCoKl4pGLoRDO78L//uMQJGoVbW4MJRUCmGyscic9kESNPP5qhHJgKwE=,iv:ZRNP6N4mT2QSpsD5otjGxV40NLU0wZKfyGZz6/KIJhs=,tag:YKXXdsTm9Xnu1Kvwc15Hkg==,type:str]
                client_secret: ENC[AES256_GCM,data:9fw0cDvzdC6cDnwTdlxoO4n6wjDtGAd1Xr4OWTbsKZRrZSWW6La7cL+tkM2Rk72OxcP8ZJRkGdaKDjzt+40MO35A/xyATZ69519xEBGRSQHaimFb5Xc=,iv:xcaLIIwdIyFDY28R6ujEz3lB0zLBRbWxYVs5KU6L+mA=,tag:ezYFlb63Ygs80k006k456Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-08-30T14:47:55Z"
          enc: CiUA4OM7eO2vhbUV+dKk28nEJuUAJWaDINvGA7X/5NORXXgpXWp7EkkAsHDEl6fCxCWiC2/yWWHL5FFWdaKWXiGkOHawPFDE5KCMlZGIjFGtkECgsSFZmJFgUtnj2kY9FfLi7PNS6/q90IqFy1WhBi9p
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-30T14:47:56Z"
    mac: ENC[AES256_GCM,data:UR76pwn6QrSNWEz0yjHjEimZ/TMLleSX+n02qEn27KnlBMtiDIGjagjNhVlRXkbhXG3jcpZ62HQmYxyIp8lzN9Juu7ZQOSACFMilx5U9kvjtgmFgOXey3TS8feBIY+GFnA/g13vCtqqEy80TiGNwMnEfGaR7O66A17ouQdUXIJU=,iv:kzxBwmwOSRZH6vRiVhQZXHzEcGFR2e/k+stB5n2JrWM=,tag:jd1pfiFpWwiM0NPDb7UWpQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
