jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:D63L2sfaoE7/pxb/nOBIvAP1I6g9Zam2s+m4XgVXoB3TXppp0OkwQoGJOTnUs0Ed5q8=,iv:YA/vS1jRR3m27U0sb3WA6y7jyxyTM9DBvbNWTVVTF3w=,tag:/5hQZ7SGULEdiO4twa0ygg==,type:str]
        client_secret: ENC[AES256_GCM,data:LmA8JwrGzuY1XWwsUABqCke4lRagE9lBvjw3WKL3erJhhujiFssIBZmjB7M/OHQ5Bt9C77U2e8qbcw55Kn8Ud82ry18c5opa7m7XIt9kax3/AavUIhk=,iv:NUvLysEvPEASZyM6ujR2a5Sil+3P/tVwrk2alrkPLXA=,tag:KRFytaBgR8+Mea4uBRkxYA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-06-17T16:08:52Z'
    enc: CiUA4OM7ePc23RKzBUKixUfDe4eFRrA9l6GW/ejbb9ShHsG6xuoQEkkAmy+ekk0vkAgIxb1uy8pfqjG6xJuwfrGKYIwasR2lDtI1z3/ciB/GjwE0Y9PSNIjseQh1YuD/Rkq9u/Tc/sNUIJTJcUlIF0Rr
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-06-17T16:08:53Z'
  mac: ENC[AES256_GCM,data:PJ8io8FrjTPbQl6TSAgUysGRiMZRaR9vbxe/wVLnt7+bKuwhUfNkt0zJIRzEmioCiNRX7rIdZBtAMNzAbKriBEBjdi65dPdkoGg2zq+PGKw0v9wgL00JyGuq6HufWBZrYlalyV8aImRAMAEJM8yYRgenRCFGtJeLWldfWrmqalg=,iv:gSj+BJ4UKwfwV3m6Da83NKUaKr8eOdfpuiqhwa2jbjM=,tag:mOWULbVn1DmsRxJ0/tl4Jw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
