jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:dswO3LoV/w/Ryz0+PoPJMYhLbUiuWvzvVCi3e+qk0SfQmdaRimnGiRgSE/Rsyrc2UilT,iv:p4fXU469aJHZttdqTwb/sSMOkxUWEyH7gh/7ew5z5gk=,tag:eUOAneJAQA1vaQr75S+gsQ==,type:str]
        client_secret: ENC[AES256_GCM,data:rxWyQpFkCSK5Xr2KbH2n5Z1p/rmZNL+qTF+9CKhw6NgzhFQckSlMEzH/ZG14A0yBM1vAwBzsXH6JDuTtHH09K1caZ2iKuHIXnfDivH+isbzerPUhIXY=,iv:N2ZcNlORAQBa1PQ7Rp8MgTskQf8g27rdJS0TiSw2i+U=,tag:5JAPwm9W51rSJrjxyJVGfw==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:0xdempdX08fj64bIHg5SzPBA1bzYi81MTBjylWR9YFcZKuqEaaRkXjUB0DbFwdsd4UKpQx7fVY+4I+X7QltldTQpiX27JQ7XX7iEk/yijPcQQF6r06w=,iv:EV6jvcgO7sEjnrM15WNUoYhpl+mjQljEVcnziAozXss=,tag:uvipKAewAaFknWBqhDo6rw==,type:str]
        stringData: ENC[AES256_GCM,data:MWDbX3wDswSiavBmCymGirQuAGmaiAPIdxi22bMRi9IkUYZlEn2kTx7ByCUg6qEdbbIA3u6MWYnY0ktx9cI23xHKSdjTaDxKY+6JoTVbM1VvPOpkJ6SCiRvsIiO5YtPvbCFGW2oqpCrqv2z95vLLW5RQKO7dwF8ZUnCGR8i7BbRWLyzaRJMnkU/7yhZkfiHLr5dnfY+ixHvO57lZEgA6cteeTq1jqR6bwdkaM7rlik9TELU1/F/lTPTWSpZ/Nyf5Mlb0P66IEUCRJwV5d1ejhKje2HzmHo5sqJ5EiYF3rmXP8ei3dS10bR/iIrif179cOccUbCPEkCYADjDkoroCquxuIViM9x9TLz3T11qttm9i5kT489SrzbaAl+7GepTZuiBRhqNU9uIjb9qLlMYDpNmA3jkvrqE1mmvSlhqQw5IaREJ6h9aOabAB5cE8yhZCqpZsuhVxa32a0s+CdLNqW//wHxyL/KiY6QLmu20v3tzkQ00Xgfp9wUKl59BzhQmgFix6T6f6bMmLjXlQoi8TaD+DN/j6i4ZqZmga9fzs+/XiURN9WRCadXGV0gl5l6OtBKFadI2V4Bsbx4y7hIeDDLzwgiHx4zdd6uyqdOszL913H3AFNEDXY9iMLpg1dSNXNQ1dkSrAw1S8e4wANA==,iv:QF+2iET6ED6lXvygLkVewCq6g0S4NUoae8+830HOw/g=,tag:mEk5BmwxE7Btp2IEoeA4oQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:33Z'
    enc: CiUA4OM7eDOLLzfqThzEGvI21XZxH+7gkmKuTzfeZwIVRhL6l1c7EkkAmy+eku1tLuLB5ypn3PA9khDEW6IKT2uAI6/lzTFLvYXNj+74ilgHju7qUAoHJ9+YB6DR7AHay3GXU+z+MnwivakjTJNGu9QL
  lastmodified: '2026-07-29T19:19:33Z'
  mac: ENC[AES256_GCM,data:R0rl6Vo7olqO5h1WD5CEjHCvHY0VGyNTt4c+29Dkz5KSz8O6E0S8CSyKh592jfZueemg+HGHOTE6OXdzU4ECP2U5G8OedE36fRKgYrHbD+vSXQvIcbLvGjyOsw9pb7PqAMwvrIYKjHrcSchFIQXjvXJTKrK/jHj7c96ezS52xvI=,iv:PnxiDkea1Mg3T6TFlUciaKIgbZwDBR/2VvdVgeDwuKI=,tag:P7eREaNQ8/WqJ8gaWX1Btg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
