jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:UqCsRxeH7mF/slcRqETXwo8yETcYAgzyQngp0lZUSfSgVBTVaNxTwDUWGF/CliY78SBT,iv:WoWfMrRpnTg5KibwS64XHrZZQ4QJPfj4022Fb4i11wQ=,tag:ZA1p8+D+ky2rFJ+CG2Z+Xg==,type:str]
        client_secret: ENC[AES256_GCM,data:8gXpZ7RW0AKYPdWcMABD+QZkmXpZ7wx1gHvgrpI2oBsERLoiWbRjrJ+T1sxHPefejimtb8GxC0aLMg7qXMZnAxXWTvOFOm5KOVKToypEtT1vhuVr1H4=,iv:iQwIheda98cyUJ+7AC99nM92MeumMF/7p/iQk1Q2pq0=,tag:eJb8seXDh5AdGhvSuD7e8g==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:vylpriXotisO3eZGAzqvb26H61iQapsKAndEyZXUDdH3t/emCR7gl5YTT2D8vyns3uBB+ox/VbhJTwcFxiqlw459HL4/+GnSY12P4DpR5ZO9kNouChA=,iv:BG/Z0zOeeIC+f24qbmg91L3o3Kh2uDZdCimlJF28Xm4=,tag:31OkwnidPUIwgr+gG27lgQ==,type:str]
        stringData: ENC[AES256_GCM,data:hL+6rHwixDR6H1VAcgIX7e/c7guppTmozZ7g0ZWbfsvMqYzntRpkjw5/NLoa8le2qMg/qqidzU6b3qlncxggFpdeWViVzjjT6ory+FWDHF4GkfqpHtqcivsLo4x7KDaE4UBYz3loTAWW/LOzDvfDdYlXDYBLFRxOkc8ZYdcdVF/6yZ/Tp/1vOijT/FyBkrcPVDlos7UEb64YohgRAbBS2WsSNmcHhMjYu+snCd61MFPP97WhtmEzSz9EtElFB6420AjkN5/RU1bzDDxRIrEF1WVHyluqtE1PwqUJKPV6TXFWqsZT5vGc/ejo2mvcZwXf9pyN5ptLMQivGjoxVgrAAvdXyM5yalp+G1tg0/6/giP2k+HyJmggpo/T3FmJgTNucjmcHs/OlQ8C+ePLif4H6xCcEAc28Myc0/rc3xvR/shQhyE5SsEGQZplIng/idj4DOFgQYJ0xC+a0zgRPswCHQPIERnISXcqtvckw5XRf8z+/Vrqju65tsCqy8HqFSfKEGnvEKUVIz08Pwum1bx8ET7kdR8wz5YzB2FrE1ZEWY222PpRbriz+dIHiVgOEFlKki+pmpAVOmK2V4p+0Pnny7HmF7qTdKGkDjg268fiy6Ng1H+e+4dNOvaex/yjBJxddM4hks9UaW0cv2r9aQ==,iv:nKaUR4i3HVyRTqPJyvzChx9CXpWFkICASWSNinlPID4=,tag:roZJ7oMsV0VIoUU35UuwwQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:13Z'
    enc: CiUA4OM7eMWmRmR5JfxsLWuKspIaHJ5aKckFIQetwxb8k1aJDYRuEkkAmy+ekqrAMXhtwAF/6uVwKl4zxTaEMecdj7qX5Xs0GFKCmDtp8iBxU2Z4kwlKaAUhlayUxQ+XiCG192232y8Nkaa62zCweZgH
  lastmodified: '2026-07-29T19:19:13Z'
  mac: ENC[AES256_GCM,data:68HyF5YVggHvwUniwt3jocbcmT6uCD6WoaUd1kliNesIRgdzRVXC+ADhVaPCoRlhHbylXoOAEq6WkISm1cI37r/JJICvS0uN37Gup/XQhuIMgOyM4QosfLGl1ed+vnZHNaxx6AakIPoJ3kh013Qe/e2QvRbnqfukRCFPYve2TMY=,iv:1mSgJdEPvSqFmJSXC3Zd/nrYX2b4wLNcF8ZsG6NM8ds=,tag:KNucojCWEPKk3t9DseLjtA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
