jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:uEHEpl/zYCGhw6rfC2oJ5RpKDDo8r0D0Y58+Jrwun810exI+6lWEmODx4SiOqDZzWFYh,iv:y2rbIvBSfl55V183a4FYu0/RPcPgFkcKOKRPlm/RoTk=,tag:JQgn8U87loaViUehJBaewA==,type:str]
        client_secret: ENC[AES256_GCM,data:21HrQDNDJ3lRGyAs8gJTCFoMSM4MNSuX2FEDgP5ZhKv7IwH3cWodpEmGEJQ1lDmlC0RuyuQdcNL7ONTjaTWH5BW+nWJ4UX3EbMT9JeE65+968I8B+PI=,iv:LRPenOjGigRFR+py0hohbImvYwDnzZAdu+ffKOOIUQ4=,tag:kNgMd660pJAu87Xm0teWBg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:/KEaFA+mTux1nQxtkxGb7Rro9hXZwMhhhtR4ZLWtFieUv/LoIB5NYEfd6M9ZWPP0NgTfESOazsMnqKCfvVYJplDVQKp93pm+OigaT+8BxjvidY1RpII=,iv:iQ/JQ0766kbuUiR0QSOIOdXEre+cIK9tftUBeuHpYnk=,tag:o8ccEXM4s8NDzwvPq0YZzw==,type:str]
        stringData: ENC[AES256_GCM,data:vLWpYqit2fe/p3BYw0rnivGMtVwY/lm/lTsfGY/3R3MtA89Qsl7np+kdp5j2rAaRBycXLBUYPkcZSFYtbiSoMV9OihsWov4C2W5NoNX2UJFaXHlaM9qSeWtxcbE9IwiOJVskyGc9yxH6zHQdfnq50lnxGAUt5+vqzrasqRFT31Va1c05QRuMAHvKBQieoh0ultHeEbDFYiEUXjll4F8G/wVf6n/F3T05iKARJhh91cbHhIfTlWE+tx1n/shL9gEkayIjWLp3P6OzShX7mtAzvQ9myAJGZrMCGD1ulkyoiAYAScipuvhnKuu9RESNWZ/DCjzseCzNy7Te9KLjPX7ZbKoXAOxSx3lYaTiqjTKYeMzUzaL07rlgVQilPRbC43i7S4/WIS+ItSBpWzSns44qCSbdTSxBIZ2s5UznYCR6VqxspPjVZzMZLFmgN9Nfm3rMTxj0fwtHHXPYhMVjUrRx4eJGP+RHtFC0cTwRxTM7pzyQXf+xrt/x+6f52qTuYP4tWlz6zHfpUGAxJ4KxhLfnk+xbYbjmSLzM4WjPmosYqfY8/9cSNtsRGlNGAig9uO3bVtxhUCl2LvpJa1w3YVmDIYy43OYSApMU7uWWCRiDpIkRNiRkpKApOQPWujBfesVPBE3WHLTzvKDKjMWVwQ==,iv:0Cy195sKU5y3H2UkIJRskPV9xrucbxsx+DaSWinAjfk=,tag:+d+3+b4PkKGKUUNMZ6VOSQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:48Z'
    enc: CiUA4OM7ePWS+pfezaQq7SZFFpHyZI4lNXJI/MymoaNatQtBvpkTEkkAmy+ekiGZyeKkVswZZYs5GrWej97WdxYXny+cP7LEu3f0m2tivNW2WaDz9IkzeRmc5cJ62/218BuESCoBK56BNw1BRNK11DUd
  lastmodified: '2026-07-29T19:19:48Z'
  mac: ENC[AES256_GCM,data:xaz4gUL9th9XaahwmidCAEAR+xWIDGNdb0iz7FgXNVJT4QrHgoe9v5i7b1eJ+1x1JJ1Yh523erPRLYLJZWKPBF9q6DO2zVh/HigUQcPuBmmvA5FCAEryDPHKdtfNFiTsdczHUUYMkZS9Eg5lUHPpdeIlgKmilJFFGjTzisSiBDg=,iv:lBe+CdWV3Qk1y8WIxdMqxEnj6Bv1g1MJHi5UqXthNBY=,tag:tK8lO53EM3QH2dZ2T0D5AQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
