jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:ikmbyg52pGt9NRXeqplcaKWSUprSEWWa2tKrzwzer2ryqFNrzSVsU/c3ZMepvc3+0PQf,iv:PaHj94TbRha0NvadfbXEdnQSUGSeTKn1FGPdDw9cnO0=,tag:ulJZ28bllb7ZlMck48/qvQ==,type:str]
                client_secret: ENC[AES256_GCM,data:EqvwYQOhBHPMBf20kjwjJnVSnnWwoFD+pRzClJzf6Iee1XJ+hFihx1Wgx2c30aUaTP7Rr88IlT1EWlWVQhnWZnbdkClxZN1FJNn20cugQXgkm1Hv5OQ=,iv:C/ZEp84LYc2NR9mx8AIwElwel274bbw2RhF3w5vUQlo=,tag:Riehj6m40W0QtCCVxlBoyQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-03-03T02:20:15Z"
          enc: CiUA4OM7eN9YbeaL3z40utCThGccmP6r8Kl1p0EM39BLps6EOk0UEkkAPHlbmUbnuedbBV0w1xsCA2JyIjSs6wR/zJpb8ovgu09N6mHp7ne5N7Qud8R5WoiwHflnsmYvBr5Afw+li4VKADhCc74pmuIY
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-03T02:20:16Z"
    mac: ENC[AES256_GCM,data:+JJ9e9lxVzea4GlhNOp5z2nrMdGurgBbk1fn1gXK0iyspQ2X6CRV2Q/zeQzN9iK5BVLKsHjzFKCAUgvPpVUdcf+9r+dWb1a10V1vR3W1+r+1gQbvBCJMF7pfVoLHsXggZuzY2eXSdnkcfyxm3YxvY0Tz+o+75WIMxTR/DABkhMI=,iv:DNBwJlPw2LsoCDmi/DSMrVONBvO5Tu4Y/+iRqg6Nc8Q=,tag:2OJAsHZ0nJ4SsV4gq6V1Ww==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
