jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:BdHAQkcLyCphnLJQ5gpQ6OKJrmU5a01g9T00bODkf1kOr1iQo9XUJQx9nzDwEfyLRWNG,iv:wCaoce6zZn6uyi6XwCsCJog5GCCv5Z0Ow82vZ08P5zE=,tag:gQLLuslAHhwRnT1WATijng==,type:str]
        client_secret: ENC[AES256_GCM,data:ykl2NRlKG56zjjXx1+GNnKAdwd8impzS3Kzdr+sFRc+YfFcRftMN4zpuerlmvw20+jiv8+aw1KZh4dsjZTxVBMt67i+BQVnQhaoDyGEu3wImjPRVEdY=,iv:zxcG7VCBdZbte/MCcYqXVyPAvRlPuHYP0t9RZ3p/qc4=,tag:R+XiJE8RQvDonxcESJf1zg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:031uTWP2yVBek/dedeIQj36l1DOyR0/gPD1kyzqOFS+v9aNLPDqGfb2gfVrol0YbXnQ6Pd1PqWTcuHNzkHMMR/hlHzAmCRmPTpkA1G8m9vWYM4J5hbA=,iv:olGTqQCpq7y+AkzjPP1qgfeUfy73/MWmq+t196Wxz0g=,tag:JqY+ew7lMC4B8YFtKjJrPQ==,type:str]
        stringData: ENC[AES256_GCM,data:1S62v3rlyZrbCySQ3tXRK5QdjHIeUHDOYYRrDPoNgC4mn+M39MbtwrqPydf8KAAsnL9IweAUR85NYz9wInN7UygJahxG0BAdXVHB8U+WuOKksTzBn8mBGkjOLoswrAYwpYGlQ7rh+3hJsvrWpk1MOY+AiQW64Z0AViLpuPVEAKf3N+Z7Quxib9iFvjf6cQ8dD131T6/96ySSeb5S/8zR4+b9oyuCjjLc9MUSjMJ/5bUv9U5HfahNlmpQXqKC6lVRTPi32BXZIuhzlSG9o6f4b5f3E0tmrzelgeBkslNf2jX71+I1AG/8J0faths+OxMCZYsjxEotBmXYZA46LX9D2ZFB1E0fNeTOjelsiGeuEBSV7jEv4WQSr9jqUUEjamRqW1N87aMTOc55Ef5y/8WpGvzuGgpeWBXQSWI7eJZV5CAiNHi3t37c9TKTgDPTg48NpOo1WjTd9x8d3uOdispBzmw+NWdIAPxoDihCysTLuNVJvgY7xR/AjMB0osWIL5WzXYInhObgXgw2dT1N+UAxsUQR4S77tIuMIa0qeDzebJq7KYpGC2RJbFdn61aNHmJrK+Dan3nAViDL2kriIsz7l/QGeTOJuy90IooHU/5WZw0XZDOsERilj+QgQiea35GuwAIb2VV9xym6Vuf7qQ==,iv:W6UKVLX4dmQ80QIplNdAQX+oqOKnHzvugixoUTT9Zo0=,tag:3UHH+BoH2XDGmAAw1a0hMw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:24Z'
    enc: CiUA4OM7eBqAVMtXMoNNnJ+9RvhMOjynsSO4GCWpi/ZZ9s+nABwPEkkAmy+ekvZSpjoqqb+O13mYWtoPCnNegSGIjb2uZ+qkZ8sNsQhsUfZuMK92++agrw2RMxtKfS3XE19ZJTU2mUyQ4YznrE5vTPXF
  lastmodified: '2026-07-29T19:19:24Z'
  mac: ENC[AES256_GCM,data:kgGLaX7HfKzt9MFT6yOrLJ0rI9sOcf3sejRTY2CNQHTR3nyN0lUXKFKgJDtvMHNSOhGq7o+qvBxQC1qdl7fgpbCocmr3CCvShS//SgsLwRe3VQBrjJZRX3YCDXVLnN5apLXqlPJI7YDIv2/ycbUWEqkQTrSg1ccIloNEEdhRE0I=,iv:K15/aJsI9EFy2XmFM8n232+RK5ZUQ5mW1Q0EtgWblj0=,tag:GP3AxiDZ/UsTuag0SZRfEA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
