jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:w/Pbrp1x/fueDmBPfg1rRtybbYg=,iv:swO5Xxgo+AaZkmrIJq82/ILfY2PhLCL9Yqz6J6uym5A=,tag:gd/fX2iOkF8LQ9eT6YvmVA==,type:str]
        client_secret: ENC[AES256_GCM,data:qAjPQM3maMaTlF5u865PRnqmSTQxE5MVwlcPCsM9+fARF1vQYdWSMw==,iv:821PiqYD4UB5QXKeRRr2sGjg4T+p4LmdqO+lWGENuBc=,tag:5YF2dhqY28FCSYksnbcq2Q==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:9m6zA39ypE7faaTh9wLJs0Fu+2vmL0mCWmfE7CzD0UzcjD/WonD3sa1n/06AQKzKsdyJNPvv1/nmrBAjfOOQ2zlmzaRc8+Z53XLVwhzGPrzid93Rp5Y=,iv:AIQp1CsNJt2G9InN93+/d7Fd13kfXfJjqg3Dgs0Ot2A=,tag:y49qCcQKFwCdzeJxGVwdQw==,type:str]
        stringData: ENC[AES256_GCM,data:c3YfVjcw+2UBQ2b0jG6mymjbdVooC7Qa4zn0oiNlifh93T0MvjrcXe7EAgNxVGr+D7ZIX0eeVvjMuoKoe4yH9i0sh9gaqm7yzI/18HD+Tg+A95x+sekJy0uc5y+EM6J4mHoBEiqxS5l4SnoUwh+nAL6OqWpXGi/1lGrlgP+jPrRhxROGXBf+0s/GmtrGRZSURixMvrnnYiop6CQZ9wfEEM7ljSx6bLfUrXvGdWBfGD+pRCnwynURZ2/daoEDcybtvvNvOPtnQRy4d/ObCixaVaSqmdW8VWo5i0MFOk6c1p8TOfyrKYvntYuaZmeqjIsdpOV28iGZyL422a8dfdveWXr/I6Xh3U/iW3WjIqy1VUfzJTqb3JNA74hnbSmGk4zCFCZkTLOtsPwUqOe/TiBdjOArU7J4xLpFWze0WZb52ObCjttsLgUWIQLQQj1XyS3im0Uzb54OOpGMampygk0d4NERgVXSTlLE3TZ7xmhc4yozWtjAmVZTwRu2TWTXEufYuoC4eUa8yaYcHpiCf7fRe2gu1A5VVTgyatjSD8tpDKyTkzfY6hByZ8Ohlsauqkk7J7vF2hVjTcYAjb607aGY7WRVBd0iQdI+wBDB5UIlzPl+bIMy5dSKrs5+Q9tydIfZeiea8Q9pukzUNA79bA==,iv:s6FyrTLUen5XRzOWUjWE5tQjp+pYKStUWF3mpxoqt5E=,tag:LmdCrvDR4sxhskrw6F52wQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:17:23Z'
    enc: CiUA4OM7eAMR4jmRwGBMqxYvykM5doSg7T00/mlUW+n3aocqYhiCEkkAmy+ekpq1n9xdQ1WeTR6V2fH9gGAKbRUsy9DaRky5plkNPfuG/OqH/C0Yt1wbF5lwbiHpEgClpTinCxY5TGOWex+0zza9yU3d
  lastmodified: '2026-07-29T19:17:23Z'
  mac: ENC[AES256_GCM,data:OzGh9Pe4JslEebeX4Kp3qGCh1ZgMkAVaXC53IwpV7hPH98dFlUJpWtTAKUByPoeBSxqOq5ijEU+YQqPPh5qcWsyS0Umo+uNkUmEQmNWwbkdbuBcuuSzQK/MVAdSBI+vYOn4LPSI+EH92ZCFThI2FAjUuVvBaphpuROk16f7If5A=,iv:XYDLpjMTGrWTzC+69JLU6zkqigSwkrZTpz/ejugUkUI=,tag:niQPF/TxnoaVf7wHpVHnPg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
