jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:KuuQpv+B3tCA2YqA4XEozqUebx9RECa+XIqKgNRVnzRmOPWKORMIFUeRhneJICFZpeAc,iv:ot52Thfjfrel3T3qOG8IZ/CMC6qFY27NBtXJbw345Zw=,tag:BQ36GaiELb5S7PMvJJFuFA==,type:str]
        client_secret: ENC[AES256_GCM,data:RrzPhZnJ0ByFqHHM4FaUpntrZGY7/oJ/xvpVnqzTn6/975HfBBctWHU69JZnYGE8UAdlZBJNxLRbyXTbHvZlczUhLCOQj146qB+0F69u1Zl5X0zFY48=,iv:k4LXXnAaTHetM/B6r4MzGq2eLVu6jzA9tt+BTqot0Rg=,tag:TByT7UtJIiTu3Z8Yr0nLZQ==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:r1KDetlHGXJKin7zdvNNT2vTPG+0Og/6Kr+IXfdYolpZoCI6XX/D1Tho+Ordc+AIuj+K94bjoVl22BWF9nraQbFGTt7RhG1BBYQF72d4Qs3spjH9meA=,iv:2jBMqnog4Wqg962O1C61xqo6m3Dl3+9cInh9RDEWysY=,tag:5zHQby6O3Lrom1ZLe+WS8g==,type:str]
        stringData: ENC[AES256_GCM,data:QKkounHFGvBPcAB6On8td/oPpMwn2NWC5THX8ARCGgD6AqUdfdhK1CG2zKfQZyEtTDc6WK4Iz0DaJ7540NaNblMj0jEzKnORwHIOBeihdz1cWI92o7Zko6siL1ift/TS4f93jZ7tpZKUHRTIyrLeOQdGTmcG2cA/lImNfZs7D8iUVEJBPcPZNUehohoVnoiHzqvrzcB13ez9QlcJ7wG3Ep/qJvPYpCNnPbkAptqNoVLCThvYbojN0pVp988APnzimWEYdwgcw5NL5MFLWCT/+ppgMCNQz20Gaf1viXc1O3h+/FF3NT7DlvdPjtYgd71Zp1Ml4iBzG6nmULICWhqp/MEGgC2CFDFCmgoq1iZfVvx41cJDJeG8Vml+cRhPCLyUwb2x3C4Vb+q9An8k6DD+KDGrvtRIb9LXnvVQDUimr9U/VsJXTGkriAZ3cfzjrfbL2OO5qEDzIQuFBA0MFWT+YlGfEYNZLZn2nJmIFj5Xys0AD6kXo6r2FXrC1flgU/Ic9EUrxyC2P/Uk2zRHNi3K64FiPECBoytHZMYiXtsiYo2MqV1fAtrDrqtH5u41+xJdZYSPRoTPhJX/3Lltl2Q5LZTdeVVdUzSLO5Xf+0I7YtM7gjZ2ro5oQ7y19No+vXi6eVatIo1V7J36894iTg==,iv:WFYAJ93oIZcWxG3k3SKfsu+OEHP7JqqyGnfYHbEfaMQ=,tag:J9Opvl77axoAb5/iUcaA2g==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:19:52Z'
    enc: CiUA4OM7eHrfC8DihYNuCeOi0qoE0XnKUIbJhgOoYo23p6tG7jZtEkkAmy+ektCrFMpTmwM5fq4cUjadxmKFjSFMJSAyII4WuJ00KbVexGwbJ/N9C/3WXf+ArEvqfahr+EzLcxKA+NbNcoVlZxI8okQ4
  lastmodified: '2026-07-29T19:19:53Z'
  mac: ENC[AES256_GCM,data:0Ny7YMJ7ElRzUzaVNoylJsRxJBNZ34R5VaK2TerkD4+s8Dsx5vfeACMmWwhcZ1KorUX+MHeeT2LupYYTl/C07v14m0XOMRdAXYOHlNyARJ43mlRb2OwGNEd9dWkyD5JQE9UGzh97OF41SUGSwdLxjr7GrwqSBriva6MAbuLyLK8=,iv:G3EVDzlVuZq0DT35o0PWyx8Jlr+gHwO+/fS58LtLsHU=,tag:Y0dcCN4S143Ui8J0d6rjNA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
