jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:y/oqlpLe3l2t9Fly9hQPGLd34zwhqeZYWP7uk5K5pyfpwhZVK3kxz8jcwbIWLP+SYsKO,iv:aJNxNe5y4WeSvJZjbJn9w9PEyW0aX0zYQYEFexqZ1q4=,tag:3Z0IE+FXwafMd2n0TqUOkw==,type:str]
        client_secret: ENC[AES256_GCM,data:cbeuDLd336mkOn2SO4d2PaI4zTuHrnddW9P0eUxad+4Qkmdd3ETh20CdKiiL7OSwcAhyvoWhnxTwzC59E6RyL9NrplOzL53LTZoQOjpxAdMMslxvVBw=,iv:gc2pwG4o6h6IBDuy+/E5tMcr1DgW78+sm88lzgWbPiE=,tag:+ZzGMyRubYBPFQkW4Uz/HQ==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:4ZEJHxsKkZwL+zFkXrJGXbRxyw0Kv7Yu6oXBCocHEZh7f0ueCr13Duf7IJF0pEDMQ1ONn1/qpBGazzRU0Bsxprj/11a6SUh+ymiEQHnx8BjMPXbFHRM=,iv:O7AyKutiupkG/lnP3vzzT6X5moD6YxzsbghTgToPfdI=,tag:12/N6HkX9fMWmtpQZJgpeg==,type:str]
        stringData: ENC[AES256_GCM,data:5tEAwu8M+cPOgQfgoStCSDS5H9F2Nnlz3y4dgcfyupKbUKD1IqkrlCw3bbEwradQKTyAP4fDIwzhuTnv4e+gE5iNy1fdxdg7HzkwrMsxbbxpURjgGwO4RQ/omUfpK170ixLqOzz0xA4/XkaxCNY0HVHrzVO07gyRi9+AWfE23zP8tAI9x6weHcfJyJPWRenP27D8pcKswPmKkJ2gAoB98UDQQngi2KQ/+Vxh+6cQmxGIC/ZYTr6yItE0OuMrqUKLhf1uiWNbncd0XUBFOmk03PNwCewzZURqIExrECckXTtT7VzEFoMZhxBz6KCh7BdwuKsnhQg7ZZlCqiLkalYwtHNR52aRqYdSun5wZnKxwvLKBYgprVIwKsCbBOnRUVmslrlSiGChQE+KF8i8LC85Nj6X1/1aDPCOZmZ6PtZ4WHFRnWgpNRGFULK6aQvgIVCiC0UEuAjBoLNsJi1BLYcB+WckBl+CnF/N/O6/8K3shhTva8cduK3jZCJhPCIm5u4AID7L/JDRsQTE6gSPyNuZSEdRVFgHSRR3iD+xRcV+0B/q/9admkjQGhH31reYZkFKC1ZH62UZy5yuS/fjkC/agH6EFsbJmjG/rMui3fvajpewecq+aTcnxUYo5QvOcVGNmDIWQzgdKbjABGIRnQ==,iv:HuU2e1au0qWkTwm829npKSxfCTxFgqhib0rgOGQpFgQ=,tag:LK5911heVoUNDpaAaOlzwg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:20:10Z'
    enc: CiUA4OM7eMsTw9lTGfrbleRUioKn3/d65yy5ePbW1YvXeio8Xpw5EkgAmy+ekpfWfbTYgDqIUFnOpeMlSil0ZhBpbdB/SLZrRlgfJ6mtAPW1+wgDlCt6hoNJ6DBrp2/dqUaRrBmdtt52D8/xoc5czBY=
  lastmodified: '2026-07-29T19:20:10Z'
  mac: ENC[AES256_GCM,data:5l84fplCBoN+ST5t7xgrHbCrVzAulqgPTc9ifuQW+lrDZifIXgJxgtd35puOBtZ7RGvLsr12sTquVSOs5hxu+y+lsx/WBCDnAVDUXUYGWJi2QAX6D0/eVT9+Ep/SznY6021Fp8UUFh3Dm39lQqTeLKcSWXhR2whU7aL7CFpFG3Y=,iv:nQzkBR12L0+Ff+wel/yy+qjWjcye1mVRmycnMDJ38Vc=,tag:4sjx+TmATlbHRpdlB0nr5g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
