jupyterhub:
  singleuser:
    defaultUrl: /lab
    memory:
      guarantee: 512M
      limit: 1G
    profileList:
    - display_name: Choose your environment
      default: true
      profile_options:
        image:
          display_name: Image
          unlisted_choice:
            enabled: true
            display_name: Custom image
            validation_regex: ^.+:.+$
            validation_message: Must be a publicly available docker image, of form <image-name>:<tag>
            kubespawner_override:
              image: '{value}'
          choices:
            00-base:
              display_name: Base Image
              description: RStudio, VS Code, JupyterLab, Python, R
              default: true
              kubespawner_override:
                image: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/base-user-image:e42c967c281c
            01-cs41:
              display_name: CS 41
              slug: cs41
              kubespawner_override:
                image: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/cs41_base_image:TODO-set-tag
  scheduling:
    userScheduler:
      enabled: true
  custom:
    2i2c:
      add_staff_user_ids_of_type: google
      add_staff_user_ids_to_admin_users: true
    homepage:
      templateVars:
        designed_by:
          name: 2i2c
          url: https://2i2c.org
        funded_by:
          name: CloudBank
          url: http://cloudbank.org/
        operated_by:
          name: CloudBank
          url: http://cloudbank.org/
        org:
          logo_url: https://www.smc.edu/_resources/assets/img/ou/logo-dark.svg
          name: Santa Monica College
          url: https://www.smc.edu/
  hub:
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        allowed_idps:
          http://google.com/accounts/o8/id:
            default: true
            username_derivation:
              username_claim: email
            allowed_domains:
            - gapps.smc.edu
            - student.smc.edu
      Authenticator:
        admin_users:
        - sean.smorris@berkeley.edu
        - ericvd@berkeley.edu
        - bishop_scott@gapps.smc.edu
jupyterhub-home-nfs:
  gke:
    volumeId: projects/cb-1003-1696/zones/us-central1-b/disks/hub-nfs-homedirs-smc
  quotaEnforcer:
    config:
      QuotaManager:
        hard_quota: 10 # in GiB
