prometheus:
  server:
    resources:
      limits:
        memory: 12Gi
      requests:
        # See https://github.com/2i2c-org/infrastructure/pull/1906
        memory: 6Gi
    persistentVolume:
      size: 1000Gi
    ingress:
      enabled: true
      hosts:
      - prometheus.cloudbank.2i2c.cloud
      tls:
      - secretName: prometheus-tls
        hosts:
        - prometheus.cloudbank.2i2c.cloud

grafana:
  grafana.ini:
    server:
      root_url: https://grafana.cloudbank.2i2c.cloud/
    auth.github:
      enabled: true
      allowed_organizations: 2i2c-org
  ingress:
    hosts:
    - grafana.cloudbank.2i2c.cloud
    tls:
    - secretName: grafana-tls
      hosts:
      - grafana.cloudbank.2i2c.cloud

k8s-node-operator:
  enabled: true
  extraEnv:
  - name: GCP_CLUSTER
    value: cb-cluster
  - name: GCP_MACHINE_TYPE
    value: e2-medium
  - name: GCP_PROJECT_ID
    value: cb-1003-1696
  - name: GCP_ZONE
    value: us-central1-b
  - name: GCP_NODEPOOL
    value: test-pool
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: cb-node-operator@cb-1003-1696.iam.gserviceaccount.com
