jupyterhub:
  singleuser:
    defaultUrl: /lab
    memory:
      guarantee: 512M
      limit: 1G
  custom:
    2i2c:
      add_staff_user_ids_of_type: google
      add_staff_user_ids_to_admin_users: true
    homepage:
      templateVars:
        designed_by:
          name: 2i2c
          url: https://2i2c.org
        funded_by:
          name: CloudBank
          url: http://cloudbank.org/
        operated_by:
          name: CloudBank
          url: http://cloudbank.org/
        org:
          logo_url: https://www.uwyo.edu/_resources/img/logos/UWSignature_line_Brown.png
          name: University of Wyoming
          url: https://www.uwyo.edu/index.html
  hub:
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        allowed_idps:
          https://shibboleth.uwyo.edu/idp/shibboleth:
            default: true
            username_derivation:
              username_claim: email
            allow_all: true
          http://google.com/accounts/o8/id:
            username_derivation:
              username_claim: email
      Authenticator:
        admin_users:
        - sean.smorris@berkeley.edu
        - ericvd@berkeley.edu
        - sli11@uwyo.edu
jupyterhub-home-nfs:
  gke:
    volumeId: projects/cb-1003-1696/zones/us-central1-b/disks/hub-nfs-homedirs-uwyo