jupyterhub:
  singleuser:
    defaultUrl: /lab
    memory:
      guarantee: 512M
      limit: 1G
  custom:
    2i2c:
      add_staff_user_ids_of_type: google
      add_staff_user_ids_to_admin_users: true
    homepage:
      templateVars:
        designed_by:
          name: 2i2c
          url: https://2i2c.org
        funded_by:
          name: CloudBank
          url: http://cloudbank.org/
        operated_by:
          name: CloudBank
          url: http://cloudbank.org/
        org:
          logo_url: https://upload.wikimedia.org/wikipedia/en/6/60/WillametteUniversitySeal.png
          name: Willamette University
          url: https://willamette.edu/
  hub:
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        allowed_idps:
          https://idp.willamette.edu/idp:
            default: true
            username_derivation:
              username_claim: email
            allow_all: true
          http://google.com/accounts/o8/id:
            username_derivation:
              username_claim: email
      Authenticator:
        admin_users:
        - sean.smorris@berkeley.edu
        - ericvd@berkeley.edu
        - hcheng@willamette.edu
jupyterhub-home-nfs:
  gke:
    volumeId: projects/cb-1003-1696/zones/us-central1-b/disks/hub-nfs-homedirs-willamette
  quotaEnforcer:
    config:
      QuotaManager:
        hard_quota: 10 # in GiB