prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:C86EVREuNB5/XGtxZ+ZUsgHk8uEvBlNoEz9EXLS4SmJpsP5PS9zgZN8QGhXLswRM5tyaIbJYZfL0RNzpf9EfuYRTS9UiEFWg+e/dvR2yN9bUO48yx+lalD/gQfEeDRJoW5Hqd0lZ2av5jJ6yRk0AoUBtNUh81HSLyv7Bf/TfhT1XP3lGan9RWqz9xzwT8eUTJJcaxddYAH9kPAG2,iv:awf80DEv+LE5IV07dTYJnG4pBu/L3+SWw8ZL9/6dsO4=,tag:4HADIOzkOIL5qs+KJ5ACsw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:mnd3dDyi9qklTFL/+ZbQH79NciCl1rFjdQnKBO5SzT8CWgUxfGtVOozzq49/3MJfjn3NU6ZtL5zxr8NiylhGyg==,iv:dsO8s8pt36V6GtCc6PSppGEwBm+DHQaOzGON+eFdGVM=,tag:BNjVnPj/a9Cc+euLmKKnJQ==,type:str]
    password: ENC[AES256_GCM,data:slWYDUC0NoNV/E32KIp3auJGHhNE5afsgk+OCz9RO840QW0L0J1Y4DwDy1iITzAWKP59WG+85x0ArKkYYx78dw==,iv:VroFlUbcZZOY8aCGieWiVc2r0ltGdgfo3HcMy1rStXM=,tag:40FeYs7FMbmGyA9mzXZWjg==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:4T8/GzYaZxRrquR4ug==,iv:J2Yi8/cDveK9gwQdCXM6KcR9QeGiV261KzU0u75pRvE=,tag:MkUK3+IEIn3vXk7/vTpUCQ==,type:str]
      value: ENC[AES256_GCM,data:URmTM6+tulsgDpFg8oNCH4l1jbW1o1WBKppVfu7oZiAdveu+9iL0PXhfbILaDIXXpatb+5dQdI9TL+tnK0fFUf6e1Bl94RkJtJ0ajeasrY0TV0YNEorWrf6HfcJZTbIajuOgyvPKJQxbZhWD0iwTABFU4ORuaaDS2Z4j2FIlJTk1vhKyuV3A1SZZnz10G54PB8cfwGt+yVWBZAhnyO1kCyBn8cQG2iIowXjd8BwQ3dm52Q==,iv:MTXbqylBN0jP/PRnyudJ9wuQzj/5mI7KFZVvAYiTy7A=,tag:Xyr23Nt6ioZqzmDV72vZNA==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:Cc5hJ7sNJYC69al9UkTrfVaeq8wYh4v/1na81oLxbkWRA+BbXVqEHQbODWgesXee2fMNDrUAqpFY8cd5y9TZwA==,iv:fjIwy8CPfNNgOg28bdxrdFCKk+GCtnn6mMtP+CcGk70=,tag:TzOj4jFTIGJCzoVwRUkxlA==,type:str]
        password: ENC[AES256_GCM,data:LR3aRjnU4MiFfid4xKlh2Lvw4r0TYFaZ9bySE/9YauWg8QZmgwGentPOaHcoOpOYEboBAY2OrL43BrudmobTcw==,iv:PaXO1rxcDGuNJu51vjI93dNXiySFsvAyb6LYmjgJ5R4=,tag:rmSITbFjayaJq2CCiOZfRQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        iIDrjTmdNs4PwqkW4EIvGVI451pyAuMXdEeIrViqEupoQkLtmOwZb4EMUyZQJoLf: ENC[AES256_GCM,data:LROZcrt5PeblHtRzY8hH6NRR6HWDfrO0Xh1vHdSen+zIKZnAJKX19zKn/EYhu0st7ugDDB1YE7nkHO23,iv:OkET46Eq++QuU9oEaRnVCAtEGHoAJD0FCBGWGEsYvZA=,tag:6obfZ2lAkhkD6lCNzh1GEw==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:kg==,iv:VSbGJW2JMzBgLBxy7ta/FqJ9p7/yypBzqnbaZNfZz6I=,tag:GJZVQ8Ko8QKxR/+HbRPmUA==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:vvF2PixS3jmdzg==,iv:TBptWowMK/i2/v++tSuk/hhAAUp+9KZH9r6hdKbpbSM=,tag:qMOB0UesHD9KYNjQnH2TjQ==,type:str]
        orgId: ENC[AES256_GCM,data:+g==,iv:MsgS5GWpwSL6ClfL+S4Y8ZJ5cvyyR1mKqtxj7vjKV6Y=,tag:2/bJqfIvtc/6UM43xuwqsA==,type:int]
        type: ENC[AES256_GCM,data:c4ZhA+x8X8Q58A==,iv:ZeumodDFw1u949UjhXxI6tyWKnbPEVf1NrNjPf5m8Cc=,tag:boHnPWUvH/+dZhvG5i3mrw==,type:str]
        url: ENC[AES256_GCM,data:tdkDEqlFqjITrT/vkc8KC5SQ3ZY73VPGGuIK+nyPnVc=,iv:nJRGHuC5rV6HfRmGbIAJvKt3tRInsUhh3A+UrSF4/0w=,tag:5tyS7/cZ3B6YW1NU5WIe/Q==,type:str]
        access: ENC[AES256_GCM,data:MWtAVOY=,iv:z7gr3S5Y3NPwYQlaTZBWkR7yF0Iq/xz6R+q0Xvyg6kQ=,tag:0l8QiCEI1m31kQ9knneNdA==,type:str]
        isDefault: ENC[AES256_GCM,data:MWoGgWI=,iv:Hy3afuXUSk3LC7+zzU/EvGK/EtFyZdNqgQ7sCbVhEJE=,tag:6qGWFRUdsFEAirslT64ctw==,type:bool]
        editable: ENC[AES256_GCM,data:xq8F2m8=,iv:QQspCvhatKTEP3lLOS/FuqRkKB8piyJO894bN9MVOtU=,tag:4+ORpr1NwWWASPbDj7ODew==,type:bool]
        basicAuth: ENC[AES256_GCM,data:ZUA74A==,iv:2BlN/4Sg7PrQa4gQ/kffO508p/IBzHIlrD32f26yuZc=,tag:wBK27GhHc8x+wYHfokmYlQ==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:vVGldgrjUXpftdvB7mWbsIU4Zux1XrnV1anXveIX+it0Hkzn1fSNmyw+vaboF2M/FBmbbVw4aTO5iMSBCc+fhQ==,iv:4o9xufJ2XkRa/+YFRyoHJBV2bwv7iPFnd30fiM8OGmI=,tag:3ph5aZtZxUGsi5VWb+0Vhg==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:21G7WykB27g0xW8Od//PHYJSx9g3H4p1YbTDIqZ5pU5uhntgbJavttjw8QQREoawQtEelxap7WkjO7V/3uXQxg==,iv:db3tu1MbMO4I8+H0TIwbvHxM/VeZBdvOySNKJ/woARQ=,tag:DEXL/+2FaehdJkqXG0K9Ag==,type:str]
      - name: ENC[AES256_GCM,data:WEKP+Nv0CrDYjhJbS5xN65Srqdydprif1joE/KocMQ==,iv:fSTPFxgucY8qEMBF2yE3m94nLRkOiKwhidoQeigugKE=,tag:EQ4uYucp0yDkROpEgAX74g==,type:str]
        type: ENC[AES256_GCM,data:bDcdQ8cHclUzkCiVXuGbwGaZfxETrL7dm1V4EV3/PA==,iv:deDOR3xnmse2+pJTJNu2r2MXBpdO4YcsMnshNw1bcA0=,tag:HMkUrfbACKTE4B+ccAi+ww==,type:str]
        isDefault: ENC[AES256_GCM,data:609cWcw=,iv:ZkX6l9QvhqnOnmLQKDVUmLfX3GFkQvRXXs/B3TNkP7k=,tag:3QzwA94ZOipeiQ6CBnjSWg==,type:bool]
        editable: ENC[AES256_GCM,data:hypLUw==,iv:bVYeT5Mu8gegqtr3KNxXxJY+6ZmjGsZGIBbOQ0skWDo=,tag:si6aGdCQj+YRcrO2F21lmw==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:H8VN4Q==,iv:KxKQExpEqmvS/nwnxmFsZOy/5RLiO4SEPJigbAEU7qg=,tag:0WerjAh2E6e2xrnerSBhHQ==,type:bool]
    username: ENC[AES256_GCM,data:lSgUf7L80EOVFIxo+MKudca/zuIlnHzHAdCKP8KlTwe1mmZdemsauW1x+/7qH1U6lyv+YV//ZFCoW3lmqv+s3Q==,iv:lle1xJTGUy1FPeQBgPqDW6utNSG59wSt/4oVf4vRRCQ=,tag:lHcOCUKZmMDSaTyi4DYm1w==,type:str]
    password: ENC[AES256_GCM,data:uW+7ADqnjBM+mfLcAzMMyAoHkFQ3y2jcC0PoMaSMbgVit9El4YoLZgLy0RHPmkUY8U10wN1kdM/6cp0UprHgaA==,iv:VSkuo7q2cbtBve/T6Yx8nYsv3bCKKtOqt8YvZjvOdag=,tag:IuYGNVfdSMGvqRs6C8GPSg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:40Z'
    enc: CiUA4OM7eGZ9aYOLnLqOcv/N/rULEkIAFJ8vzGn7xC81+svloBOGEkkAPHlbmf/tXzqyp6Yn3q9OH9qIEY9TUrNSZQUyOpE6aJBzKjq0u/vartyAE0Nzseld+OMW05OMlAIN92gDbAhczy3C2ESVQQ4v
  lastmodified: '2026-05-01T14:40:40Z'
  mac: ENC[AES256_GCM,data:kTSxXkwQnvxfyFpv7Mm06aKjX3hGhzJ0ZRa++3i1BBEegMQXMA/MiUnxLYf4XtpU7vw0gsbX9MlQB4+SX9Ql6FPG4X0q3EU3Nzebj5re6iodtfV2JCG6S15WnGhb17Qx78q2SL+Qr8WKNCHtcFH5wUk0AZmxwSJDKREtBEUBjbg=,iv:uzKLPAXQ+HDCxgHThbFQ7GxKX3unGCHNWp6PJL17iyw=,tag:0THHkYQ0QnKwGhZ30U5k5A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
