prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:L8pvrunzpt3fAQZfhA==,iv:LIj1IZxFlc/KGYsB1tzqJlZZVz9w2j0x8SwL6tjlYS0=,tag:wfGeMLKeMkc0equ6PkK+Yw==,type:str]
      value: ENC[AES256_GCM,data:t3BwnwqnaMX24xNWDNNphi5eo/MzABH37u7q419VtSN71JvnXG68HYHWc64JjBZlMHfsAzhKwpdgu4s1ehz2ziU7L4+fG9YQyyjampt9uZPmRXXVkc2L1kU/aFkuBx4qlRD+jijZD7+PSCyWZ1/H0aqaJn7fBu0HXGEzGwb3IrMmORu+d5bklvNPvBiecao7L+iyjFeCoNhOeigzeJgF5DqfyOM8iWlEU6BNEf8R/tNhfA==,iv:U7Jn+vAieU/V7YQ2pCgsMEA43rFT+BLqQjty4kwP+uc=,tag:shfPrL8IkaEsGb1N/sDh0Q==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        iIDrjTmdNs4PwqkW4EIvGVI451pyAuMXdEeIrViqEupoQkLtmOwZb4EMUyZQJoLf: ENC[AES256_GCM,data:lN5G0y1/K5rfXs+cLMKK4wgsuES0DzYlyIYWAfnsAgbhuzOdnjiA9At7FOlCn35jsXA1+4Z8rJ4zeUiY,iv:XRlmptkHexsIvoeCZPHuiko2kCN4QdrtJTR012GlnwU=,tag:2wn8KYHCej2wsNYNcSISog==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:scDCLw==,iv:kNQ4auyZg3UqV1Ig8qoxBtcFcwGikIyaobGy+OJmYzM=,tag:UyiyUhUtC5UOhF/eGi0xNA==,type:bool]
    username: ENC[AES256_GCM,data:luLjPWYIPVtchDm/3cA2/moaxL8W7xJw46z3mSFHRM6r38jk+4HEMmd57tHCiu3lrZhkaz8ejiRsMikUaiilRQ==,iv:lgWIbMe8oaO5JI+0BQsWDA7Yhno/o4RBBsgEViIH9Xc=,tag:RfALXVQX91N2EfDcCQWt+g==,type:str]
    password: ENC[AES256_GCM,data:w6/w5ad6b/910KqyDyv8bOkhRmh6Q/1uTgbtrYqgq+KSyDlM+omRFK84oJUkMZTWIPOURIIWml4Si8OZHlidng==,iv:DrU6BcmXc3LJ0kTGU7WzSZ22YTlIGNUqbwgL1HxgqxY=,tag:C9/o0brLGPfUHLldFNzm8w==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:Zd/QwMmoIb5uLja7uzNRl8xLw4Gg5pgZjrwl/WU6+QiPm9dr0lXF1AdWlEa59HYeJ7fYSsNwu2zBaCxhMHJ39Q==,iv:matGUGbJ77kQqtGUH2XTk32m+9VUp2OjEOtHZfr15Q0=,tag:SnEtai2BMztQpivEASJQnw==,type:str]
  password: ENC[AES256_GCM,data:WAy/Eq7nSY+6DGyogwvRI5oJFbbSdmY/1vQ6KbR6YvyaeyUiYKsR6ASLBfYXoAvRsDnAU2bbYAKRP+AT8uULfQ==,iv:x8fQq/y8Kj3byfPAkDW67pM0Fw6DPk6mV+nr6maYeKk=,tag:A+R3JwOEFgGzvMrBCr0Nfg==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:21:55Z'
    enc: CiUA4OM7eCVIf3QF8GBuVxdsgk7TlJqB39CDb1gtmm/J3SO8K8NkEkkAmy+eknCJ/P3KK177lCJGAKt0XJyElj4FMEd8AIwhhtrD5nhVPrAEP9drOalGDdB4/1UZ/D/oNy70acrUSj/gty87hAseRK4f
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:21:55Z'
  mac: ENC[AES256_GCM,data:q5GbCc8zbAz9eUxkHnGwD7U34adf5nLMmJ38R9Fo1e+phjifQ/DnZIwWvvCCsxgHjFdIr86qYbAqVyDSCEsUc7GVkCEyLfhwYX5lOo3JRek+yBSynbtsy0ZxTJJMYv5huT38v36X1bnFas38e/1Gvq876ycceZt6rsUOx+g+MHQ=,iv:/sq4q7PhGYoTeHbqoBMOo2G2BJR5yazAug1epwlmwHs=,tag:q8D7t9xNm5Vo8HOAyV9xeg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
