prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:R41n9iaGWRh3CPtEBw==,iv:A9oPD3IVluls6ZTXZ7vlyBTZ50sTUfeHFmjJ9UUgE+U=,tag:yj6b3Pib/Z00ySe0Sb6Ahg==,type:str]
      value: ENC[AES256_GCM,data:OmhfMFLtMSWysqPzMwnfHx7qmdE61U0Dxj8cu7yfpsApObXH/FsmFhx35C8QppPsIsotqpRVK4+/ClPObpvhVJOJXJZ9e2jsyWRAE/QcYDOCjD5khmsBRzVd13lyFm1zRbzR5wL+OZc7w/0IfhH5/hCDn45n0ELtW2RDBD99GudjCOS9cb98L2jPtYZ0kh+98Cb9Gy8ZJJbBGytAPiPprohPSyQ43nOxvQLlueKZVMXzUA==,iv:7ZkkyJGIhiU6DkNzwOrEVgROdg+4Vizkfj7MQKFSDYM=,tag:5D8Jkrbjh0UEJ0OBd5oXxA==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:xzary3BJlLJ8AEvKsF0/XtsPhDipgY7Ve/wF8gEXMCeS3SGcHHnMUBFpRDc2BN+280I+9VjwbKUWg2u558pkUg==,iv:8/ilbfoPWyr+fVjuxOtV/6H2MxtxaIFqG05skbc299A=,tag:DeOs1hA3RnFRajiGgyZcWQ==,type:str]
        password: ENC[AES256_GCM,data:+E/6NX3vdGqehvinDdZg5k3buI9Y454bAKk2kXBdMzTXyMQygunIqBI+LMUeo8YEfi7rvszmc4pFgzCgwNcODA==,iv:zzx0Ixkh4Tuua9zvNwLuPB0/WpVtopYLl891HisGdRE=,tag:vI+gRUrM15M1mZE9Q1c9Tg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        iIDrjTmdNs4PwqkW4EIvGVI451pyAuMXdEeIrViqEupoQkLtmOwZb4EMUyZQJoLf: ENC[AES256_GCM,data:Dh+IGpZRM5jSHVibRsr3xDD6sni4IaMEzf1h6wWkBOG/WQUTjpFOVADNY2eS85hSGKUxrC2K4AhBr2YS,iv:p3zg0stHD6V+tQXTaVacMiptSB479Bgg4quJlj0bOOI=,tag:1byCkAk68D4ywkK86q/9gQ==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:zg==,iv:zM+3KAlueKaqDbO+mg6tXYmk5zuxi1jVFVbmJ+4CEgM=,tag:LDxNSpZjr98Krez/TD1KXA==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:iUVJT6AYtvdf/Q==,iv:yCurWCHbqnvi2dicR/oc0g7lUokziCTJzAeFHn7hrr4=,tag:X3mz2NidXXpRvfLkgBI5xQ==,type:str]
        orgId: ENC[AES256_GCM,data:dQ==,iv:xxkftddU82c4AH3HsUtkKLnqHUtbSyfWTvGZ2G0f4ZE=,tag:wDGH1WbIj1MXa39+21EPsw==,type:int]
        type: ENC[AES256_GCM,data:fAj1waWZU+JC4A==,iv:g+WuGGxpDkooY1s6zNBHgo4ucO/RXkq6NMSyi6+xi1Q=,tag:EE78DxKp+YOO9Eek/EEV9w==,type:str]
        url: ENC[AES256_GCM,data:glBwQkAL8xJcW0aKNqzGDuTgfpMVFOC8c66wVG653Uk=,iv:dZVjrUd6m3sXH63PgUQVPwrCLUiUP2nf4YpWTxL3AAk=,tag:rWYFF3XHcueNdT8o1Pme/g==,type:str]
        access: ENC[AES256_GCM,data:8vF6leU=,iv:HKfeEBsJgN/EFkYqjwmwsSBWR6RZoXIemRqSZRVQkE0=,tag:4I3Q9BH0h0CqIdVGr2JYyA==,type:str]
        isDefault: ENC[AES256_GCM,data:IaU35rM=,iv:5P3tDUZI07LxL3zPrVINi4CFhdzoFczpKeuU5jk2kpU=,tag:1Gc/TSQVx2A2vcGVCBaR/g==,type:bool]
        editable: ENC[AES256_GCM,data:wRlsUOc=,iv:Et31x9zvzcbTO/IvWhIAOtL85EtnbI6PDEflu4FjyZQ=,tag:BG3fwWH11nYt7VuSbSHTLQ==,type:bool]
        basicAuth: ENC[AES256_GCM,data:L/hZGg==,iv:YQx5G8S4ooOk0Xjsk3U79T9L4I1/Vk5+uOpq4T/2uRI=,tag:RtctsryzsLAiR9mTM/Rarw==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:vYe1GB7Ts+oZO3EOsU6U+lV7Dq9Eb1Pc/7oTYTOKO4+naI4O6aZhIcrMsyN2fFKambdrK4JJRlrvFfH3UM55+g==,iv:GhgiCobT6bK713GgjEpe+9ItGSyn0jKWJpgBcPC1NzA=,tag:7d+9MZyMR9SMmo6k7BV2Xg==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:W9/RngQQLpAtyU7cuj+UyXq2egrFMNs2ryETjmi2WuHICwRDrzdlbns489e7SUoub8LR1Mgsgv0nI/eqswcQEQ==,iv:lcKrsObPJMzN/nYVNv1RyIs34/DVLvhIgmB1kQ/QUd0=,tag:hdwLA/K8278jZB4/fiO9Bg==,type:str]
      - name: ENC[AES256_GCM,data:h4snlspb4dOUBsbhb4Q6c7w70he49Z0EZBO0WxD+Dg==,iv:EjEm4Nxa/sXd8O//N/q9sYqW6b5OSXJILkPDVC8XBOU=,tag:5I+nmoCMF/5A5EdgAtAErA==,type:str]
        type: ENC[AES256_GCM,data:0G6Wfk8QrgKakmeN+UhlarfARsMtV/Mhh5zZlPCclA==,iv:C5c+bHXf9r0B2/rTf3oYzs0fID2FmftJzp7K2uyZ98Y=,tag:f+hfATbhjBPiiTEOD7GRQg==,type:str]
        isDefault: ENC[AES256_GCM,data:j35WzFE=,iv:UammerP+qGUPCYf3p2+Y4RoUl4JYSSpp2Oo7HRwqITo=,tag:DMCszz5JzoEUQ2RZcKZLKQ==,type:bool]
        editable: ENC[AES256_GCM,data:QISNWg==,iv:B6pIU7xgbP+JvJm2umoa7y/GiwzIMvza9aJNJBA6Okw=,tag:UdKgWxPwZthaFctmpbs0Yg==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:bqmpPQ==,iv:Kn85L+AGFGgcgVz8erp9314k1fgoVRBOJ99ielb4i9k=,tag:v0nkjyYL65huYOd+cE5Mqw==,type:bool]
    username: ENC[AES256_GCM,data:kRrQ3rtTNrJ8IpgO3I2ci0+XDbCdQMruVuJl7/Q71sm1gOIgvx1nKeupAA4WFPkWWL3ZCNgdr16920EPNXRcEw==,iv:Cp9ZfgWLLFiwKhH0AbKUzOUwwXRmUrVWwwPRhuGrTDg=,tag:yRhty8H8ocmj8O3WOe0i2g==,type:str]
    password: ENC[AES256_GCM,data:eMFnilJoX/rrrfHHWFiMV5y1bTLoc4xs7BPMgQUfzCnqoi7LxHIFy5ME2tGcGtd9O53q88HEyPfitmtsKyfiww==,iv:2VCpNFGh60HbJF2YJHtRPMeW9C8pdIoLykAF0nSJIYI=,tag:J5MOgkJR0C4nfz1qRncqtQ==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:zMk9MQTrksr2znY0JWlN1qPRq//2H+oI5I3nNmrZKXezGKsHtSoanDVjRdY8f/iwLq01G5ZeiX1qwtvRpcrkKw==,iv:odXUEgvKYXRCHOEr/J1V4Sj8VK/Us1zDHqaKDXqf0aU=,tag:tBvdGWXQ8ML3to+mPZSXlQ==,type:str]
  password: ENC[AES256_GCM,data:w1Y5rW0gJaIYTPPJAsFR4uFU4Zg/bKysipq/+2Q3ZeY/nnTwDUPpv7tAF7pbkkv+d0+0QCLVYMpu6vG/Hz07CA==,iv:b2SIyaVtFb+q8MZU//WyUfFY+6i3icUwv59UJ/rqIF4=,tag:bfW4vJTh+7N/RRObdGzxVA==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:16Z'
    enc: CiUA4OM7eKztYFS6UcSGaXZ6thwot0G1LioODyx4awXlcN2lJ9vFEkkAmy+ekr1exzgzOoTz6mmdpUtsZqdMtMnbWsvbZTti+/6DDcPyGO5J+ivhk50oiryh95nRkvN4KT+apvKQm+FKGA5FlyPRtPeq
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:11:16Z'
  mac: ENC[AES256_GCM,data:JrgQBhO81v4WvJK0kysClgzzd5dzysoGB19dkqXZZY/A84vzutEelxT5x7xBLYXl3NA2JFSO3qNb9fNQRJqnvvOOtVRjEsv9dIU7mbsr0vTSY4XlKzCbbsrXlmjw4hV+/7oVreyo5Ni82ChMoMCYVEA5TFy9UuAC1EPuFZLien4=,iv:oaRqBJ8mibmix6TKjgbnVUx0mjWtkRh6VzTYyyzFQKg=,tag:6RbnOD6Jj8DntuyAxwSCjw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
