prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:w+opvCv17Qp7KegKlg==,iv:krMJNLypx6/ZiQ/LiOksq2bLIge2EtcVI1b8K8xsbu8=,tag:eIfVrhXg7Ow5fjL4DmhfVw==,type:str]
      value: ENC[AES256_GCM,data:GQNjS3S6SEvSD/ZCFJ6F16zV7RjOduQlzjbIs56gBfhs6cT3DuFHTFhKYlAofMjIu+EIaHdlHwhbuV/l+Y1MdRwZkqiqMsUs4U4pRRdmb4/cZ3+IEF9eVEUlcy6EcREoCqP0AIn5lzVAl/9VOk/tODcDt0AMf4oo1hXSb3mXMGakLquKNm6IvTg7RRK6cKvTwnF9uC8mKH840sSaUbcz5A+okrlWjQjPJr7+G/OChHCA7Q==,iv:9i/CWDIF/1BWkQ8etHowc3ffanzsDpCQA3BFAk8qBRo=,tag:s/hZ0btX7MKQ7mFLj8AAVw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        HL4J2oLIovCYWRg0oPemzW6GEslQ6ZeccbGwscEojHkevGhcleU9bIpXHJkthKWu: ENC[AES256_GCM,data:bkCbDm0Iybflas0G2tVfVOxQmrfoz5Z56sJ0//hKJSggWFC+nHp7o3Iid42oliQcdjkx7mcM+NExFBPN,iv:XA7x0eAQzyzS1BzF03J+Cl4prC/XnnQsLtHfKEzFre8=,tag:pSygTt8Mnj8+HU3PRNnnmg==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:n5iw+Q==,iv:IhvlC4vKkayhvMYjXNxdYTXWpMATGTwQ5rwaqg05wPs=,tag:+v1QFCJx6NjhmFvUZUoJRQ==,type:bool]
    username: ENC[AES256_GCM,data:Q14T+DKT8YCZroWYklRnGd00z/xXXc8DnOXbdBdOMgKWYseXVLYwGB20u8oCaHqTdlDUJS2dZasPusB70aABdw==,iv:P+dDb2+NrIO7ZBGh9kq2t2qLfG9r+TKso5XEm83Dlg8=,tag:jRphA/bmypJ1GHtcyqEcSw==,type:str]
    password: ENC[AES256_GCM,data:D5LorrU3kBSr3sHAD1fIKi6RJneG9ySnbRKRsvi8anXCFu5rA/rEok5se3hB/o+aYzMsDyQVOqsiMw37AQIzHA==,iv:kYOJuYtW5411CtUAkIn5RowX2sLjBdXkg8X19PCVy4M=,tag:PV3z54uzASNI/wWvEOi+oA==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:fkD4mXdiF5sVpg4w6QaFoqW5tO7v1JbY8y/43+1iTjanecS2n/VHI0cRf93ewbw7k4+pmsI9ZVnLIiJt+lM32A==,iv:d8asa+J88jfFzZOSn95P2HvgLlk1YgedKcmTxk2L5uA=,tag:O//ADeDbK1dVXV+Q4N8n0Q==,type:str]
  password: ENC[AES256_GCM,data:QeRCAwaFASKGMVqfGmaOmA56YJ7F17/rFXR6RVfk1J4RUFm80qchLhPmWoNKzybqKfhz6slhGx9AjSFdvMqPzA==,iv:UxsyNDRh7yQRncYb02l7vYTg9U9IVU2N13QGHquQN5I=,tag:SNjY2f1Iq9CPfZrT2SUVpA==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:21:33Z'
    enc: CiUA4OM7eGmDJ1S3BSS/fkzSbZZn49gQWHKfIjkbBa9+trB9Bb/QEkkAmy+ekl1lIquaIU+432PwvmoBnM+NeO/GivJLubfBmx5fHlAyNCfY7E3I9cKSmfO3w7y4X1GB0a9kH7M7uHP48jsjEqaCjpHm
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:21:33Z'
  mac: ENC[AES256_GCM,data:sKNCuUaIsvMRnnTeXRHDSGqx7I3QQ9A6V0W387zgLpWDHR5DObdC2eBPTQKZmMFzDl6CfX8hE+7N2YPf6NmvuuI2Re1gwbyz8WqvV9BskYJKpCCY0VDf0a8azYjwIXXi6vTs+GeAWvMB28xzLA3sNqJ/REHQc0M+LaGmKR9Y78Y=,iv:Jk0MXh7EWktuwRDmOfbKYf58cNZFM14jhGK76SZ+KSo=,tag:hPQMia9mfI/owNtWQ1QVOw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
