jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:oWZFIHuiIRRIJnkIEsYOFAzWpiQ=,iv:v0naetySDy1w/xUYN4JqwrYYLTO878XvTkb0X8Mnc/E=,tag:hAq3DIzvhHygmVRdUpqiNg==,type:str]
        client_secret: ENC[AES256_GCM,data:Ka0Q1azMQ3J25b1tEG69krHUtSOGG9QSAdjWcv11Et0vIC+XyaAMdw==,iv:FpiRwvnhePbQTeJ/TC5wGS18skFlHao9MnCkRZkT7Lw=,tag:/IEJexH5DTPy6ckOvIQ0tA==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:qOlDnASkaAWNWtuy6YN9c1/V/OyEvttoOd3JfvHZPD9WvZ6LB7e8zWn697B/6HIAYRq/eXn37CtI53+QAhVs/P4rYG+ctcRLH5ktu0RsdhUO3BSNFyQ=,iv:+LL/ManmvPd2mZI8f8kqAV0+VTHnTC/sJ/KaWMgCD0w=,tag:KrEqulmhLrSv8J/zJRvl5Q==,type:str]
        stringData: ENC[AES256_GCM,data:3gYkNWmBMwP9kM8vzHASznYMg346RF8kJSIK245tjl9kKlb8+scFc0AmAVI4Mm3xSXV5umWX3cq9QvEsM5ADOyzRJi5y3MEr3dSfuDNy3DvKPmPo4ijzW27ccvaXRJ8JIgkK9DMHftAIVmTEdYc5iA6tFBn95VdVu5JI/2kHwxRf2qe2fK2rYWBNVYZ+DVLwMLrpYFE81e3jDAoNWZ47lmEmFvncqZZDVzmjt5dV6bVNsmv85T7motOGL1tnonARz4RE/JTpHeZdT87fiHWIDb5064n0i4vXAK1JS4A/upPIAzsVHVtL9kbNOUEyww8T4lFuenwqZkN7hyYcNZNw7u6YZRsRmHu+OmfiFFqMcOppoLZ77aw08JX/KRgMhqpg+9AXkYTioIwajmA7n0ohArFp4NB65wmwVoNTmtEJVfQLtc7yzUT3FL8PPtbeJfJLmyoQr8DAOr8s2UMu2N8WMVG+HSbrndAZDsnnk7xE3CU5XzzeeT64cJtmKeKg6hKkKNNE9MGMJxoG4eVSKxbJ4MSfQbFMSO2yF4ooJWWt336I59qj9Fy+9Kb1BPT37q2+GnzjdpUaqz/XDhtFnaBldQxGheyLGBQohx/j4ekDyKMyTMg/q4eAXFzYfs6ib50ADIw/WDQlc6K1ZssaQg==,iv:hLIm9IHZJc5QJHcl6enG/ZVNdDmiYn7gU5hYPaiMzyQ=,tag:TqyUhxL5GkUOedK6/E7hCw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:16:14Z'
    enc: CiUA4OM7eCb2738Q86dUa3zmyDQA81107fG+jaKag80mfFbY9+G6EkkAmy+eku/LLuwuygckV/Jp8GvmMzP/pCip7ALhQht7hqAGi9inbyrpfEhfYxyPjDK7tdUXfYYvuQ/k5tvIJm93QjQDJyF6ZsX4
  lastmodified: '2026-07-29T19:16:14Z'
  mac: ENC[AES256_GCM,data:8/A8CdOkDwcosHErkAv67dWurxOV5omGcHM+t5GGvsb5Aj9io7zNOwNoDT+3A/BEY9lpQ2dzEMHLUzFhgy+y0QLorOs50r4PGO2SgfTHiirbtvrLg3rwxB9IyruF7iLSZ2iuEtkFub+Mc+ldhOamlxmrNwmuHl0AnJ5dhJ2t3Nc=,iv:sScgKpvd1gSYNdlsI8MyNZ9dEFOuPzVm6+Ttn9PlPlg=,tag:yQNU5Tq//1TYcrtIULPyDQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
