grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:XQ==,iv:O+VlRwj6DYoDNEHgNl7AIUjEpEVem4qh8EV96jL8I08=,tag:2wtTdcxk47hKG925jqmakw==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:G4Yc6wQPLyIqsQ==,iv:vc95sBJHKYvnkgpnzgQIc9mZqlNL3vj/4BJPNYZbZns=,tag:XONAe5xL6EjwfBiOl7bdKA==,type:str]
        orgId: ENC[AES256_GCM,data:Og==,iv:JVToWfTREJOTDBm9QHJohPe8WsXrJ8CE5xMphXuA2jI=,tag:Hb7JKo7/GkvJj3GShv3iyg==,type:int]
        type: ENC[AES256_GCM,data:mWsa+wSlADcemA==,iv:Eac6EVIdviauQxv/vegrTlAEzAjAgS4zlf4eYdQ+Nyg=,tag:wxGqKQdsm6P2rvZFZGPX9Q==,type:str]
        url: ENC[AES256_GCM,data:KdOjEqUqfKZeFoeK99RtCqLBHwa4Xb5K0YgzOV0eme0=,iv:fN4ESSku6+4C2TYEkp1ZnSSBebH0P5JfBYsoVXkkxMc=,tag:doGYxt7IIrPrRd524dFhYw==,type:str]
        access: ENC[AES256_GCM,data:/vkCM8Y=,iv:oJXg1T6+vsrn2avCbbR315op8PSta0fEQvrnkfWFa6U=,tag:R+sYfLtSCR5VNxs11FNRng==,type:str]
        isDefault: ENC[AES256_GCM,data:/08bFu8=,iv:6H2D/EbEVQNqsvCf5ef3jPrgW6Zil4cHlP2tFnxaf5w=,tag:Et8PrVi9LaWC9UJcD+zDHw==,type:bool]
        editable: ENC[AES256_GCM,data:eyIKzAM=,iv:G5P+bT45jKRD7y9a017c7mo7mztsyy/zgBQqWBY2pcY=,tag:aI4IXFn+y6FB5nfmshaVFw==,type:bool]
        basicAuth: ENC[AES256_GCM,data:7cmOhA==,iv:9dH0fLYjfhhvGKVcMROgO9k3JloyDd/OSHgwxdkwZuk=,tag:ogR5o1BSW6QGXSGIhd7EEA==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:auzgkm7oy/u/ZKt3tGZ4gj2vgu0Tfc4RwJ1lRyZGeZP006nKBy1Jm2YDOaJQcXFBdUw72xxole1k3o5zC3cFOw==,iv:wM/Xqp30huA5Sv+OZAh8IOC4OPjNWHyx3j4WlOM4Lx0=,tag:isLAayI9YDjihT8QX+TADg==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:t6BRGBsxFMurMyvPuPkQG9VqOp/8JM/KSH3F0bIWOPPG+BxV70a+3xXUmTIKCGAXnASGHy5A3v0wDBqZlIU9/Q==,iv:SvDKiU45RPPWQOwmxp8z2zftNeGEQcik12c/e9uOG7Y=,tag:oU0oiwBTSmFAG2rBUXxxkQ==,type:str]
      - name: ENC[AES256_GCM,data:p4pbRZCcULRnKI+16wHtQvCtqNGUsdieI2fxinbQMA==,iv:A6DZrglXYVI358ATL8/P8K7nxcx4QaqKaFxA3F92Hno=,tag:6jX5xEnYonAZpfZHaUdkpw==,type:str]
        type: ENC[AES256_GCM,data:5/hy4q5rqkvfTLMYrTobl1r2uRdzzoICABEbediO+Q==,iv:MAZPMPCD9s2kd1APijmTzeLu5Odui3h/CNzKXcVgvlY=,tag:bgi9Vy0hLiFEv+v7Wrl4yw==,type:str]
        isDefault: ENC[AES256_GCM,data:wk0A/B4=,iv:qr33FIpED2paHYZjRGZPA98RyLU+3fyIZqlK6No7iPw=,tag:9WtphAUrMlkj3oDJovcSOg==,type:bool]
        editable: ENC[AES256_GCM,data:cUJYGA==,iv:ZLtD4Fz+s79nvu9s18x+apE5lfWR5jK+s8wxwD6at1U=,tag:+BVHIyuFIhXBiH/kW6SKVg==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:gWwgKSxZ36IXOYQXWQ==,iv:W56hOcy1dMXqgbqX18QS/B+KpGd+Gi5fduMshhuYVbE=,tag:piVvRdb3t0UXrH2y9AeMeA==,type:str]
      value: ENC[AES256_GCM,data:IIze2UTGTV5kGALbEx+KiwKshtwjpEOBxQVVF/sbGZuqyULnKuIp+WTlrEBjk8hE0NibWZbEcS+4i48TiXInKCD3tlxmoFq44Ie/NWzUEDx+Dc73A7JxuTnI58z6fQ9vlPwgEuMTncz4KaZGVf0F1wbQZQuyxVRhm31ho1xgIEEuj0enJ0w7Yk9ZiOJsCCak/TKd1GmKOmKiOR1HH+yk4IL/75UeVPMvhgz70FwrCqUEGw==,iv:tb3Yx7dsWF4BnAbXXPGbhGs1DspCRp5RNuEWBez1rzM=,tag:5pqBoh5bNIMFpzgfr8iq3Q==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:suycxrjncTNHjq/VjI+OaIYcWlLLkF2XxaHE2uQJrllR5Q8JITdRGmT1bjC/L0Wsqh5zyGLh6ErANHPSOK6/cw==,iv:ex3uphU2iciSTmai+FxWqbvJC1TYVTZsqmX8o/id6Kg=,tag:tLaaKo82P9O8915xKx08bw==,type:str]
        password: ENC[AES256_GCM,data:/tFLKu7w8srjv/4EmLfdfm+OF8K6mf0Cm6FboK3gsJ1lW4OWT+J4preFD/rPlqP4Wh/JPYvAk+VafIy6laY5JQ==,iv:P7AMnLzCWtBTGG/bO8v15HrjzpFyXayN75VwxbPTIe8=,tag:/INWmGs5Da1pB67oKUMERg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        HJK2ImmQhgclS5musEdi9AsP4ISIAjn0vkpKAcpW4FELIc4pfmcv2SjP27L1eLQV: ENC[AES256_GCM,data:0BDaUzUUkF8CUsGmbVbK1MoQ6ZgyW95GF/r/B1deseR5/K43XXsOra5w+h3wGO2jNaLfRr5EHN25Pcua,iv:v4+RydYKN9hiZO1d1lkTXcSSCn7rE+R29xjZXOdePtk=,tag:ps2eZ6sPkJ7HDKz/O1vS6g==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:oLGPKw==,iv:hSHT1GU72phUgcxa7faHqzelcJ1f3Hg29kjUY3DXyxE=,tag:2BbZ6t4GJKCtWNIHor1UWw==,type:bool]
    username: ENC[AES256_GCM,data:wHBRq5DcGQvABufqqNcmJOlMuJ+XPjgdkzhwRxwF3pc5xQwQqyLQ+mlx6NilDs1nS5Bft95wQif/zwDCICGxpw==,iv:aH5xHUULfdSbYafYt9caT6emtr//s1SCLSRJhqtK/oM=,tag:NRVu15rZAnxZ0gd21gp+xw==,type:str]
    password: ENC[AES256_GCM,data:IINuhPYyly+0t4QQiSJZvZWQ3wVJdT+NL9tBZD0C4k8P3Mm7HC7kKMt7NlAH6g+Xsfl5yc9EMW1omKIQwLbaYQ==,iv:+jK/vc9HuavGvoXdYM9ZpB+CwzCDPSpzJcgYdeRyqAU=,tag:bB2LeE4Q9m+yGx5o+HB6/Q==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:4bVyOmSLQ0cNoYYgYaydOHUQGPMTd9eJWjI+CBN7fd0MO3Ib/zSzMneBBIutU5400CF/O1Sow9r1Qx/zNI6JAQ==,iv:pWoSZTjaNQ+KiFZFwfuxJ34LMX1ttqsgKZrtQOGQE00=,tag:Ey+QxHTtYbfhbzN191VvbQ==,type:str]
  password: ENC[AES256_GCM,data:F/GKUMZ7JCc+aBeTg9MeKvchtIgW52RO0xUwKWQO6eOA57YqoyJctzrYKZzH75EpKu/JscYRrJfUMcYnRXGe1w==,iv:O5Bl7xiVl0zWBmc+uS/e2hKpwjOuF1yKGyNaNf/zHPo=,tag:RCT731MB0MYh1rSR3WWShA==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:10:43Z'
    enc: CiUA4OM7eGIRVlFpGnsD7vbO52sqoeLWnd/mIpy8gKxPHoX91eqGEkkAmy+ekkHcxjnHlwaVVpfqU+rpMLM/kAud+MBUz9so41xMryUdRG2kWotCJJiEsIXvbEEiVBy6hFMh025mM5jouME0yMgB05ui
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:10:44Z'
  mac: ENC[AES256_GCM,data:Cnx+KqdUaZv/uvI/ljHLYxR8jVyBi8QmauQnTydg4/H8V0We9qYB3l+qIB+23GiFLag7oFFgyK2OC3f/qAfHn89mAJCavBGMyUlrjz8fJex60vx+AAJzwI2s0VYxwgx1EwIixq8Fc9xzIWh6BoPOp37lCmn8rWSKkvgkCAjAR5s=,iv:pJjcc2xyOpJmdhGMuWSctrVCn46LqVzcR8jf4Cal5gE=,tag:LkKZf2jNLtc24r3m9ZDK0g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
