prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:NRJCiaCOwips5RatiA==,iv:BV0NU+JITF+Fp0RlACsw+vnpgxq0it3jBSzJjahT11Q=,tag:ndK5bt8FffvLf+LAsaqPxA==,type:str]
      value: ENC[AES256_GCM,data:5yGzoy9Q8yWvsub35V0G088DPwpoPXhGE/4UbiAU+0pj8CfQwl1DP3wQYFF2rTLQ7r/kAiaHi/QryOIDpWKb/gx03AtieeNFL+RrjivvRMq0vIRjKxMd5o0Kx6yNBcIoeQ89H4aLb3tB1ITOIUNegTA9pchxHF+2Q15PBfTT7QD5Ze7MxfNV47rkVyIofAOY7pPYhOXqgb1B6NBNosWhryM58C1BvxEz9amam320Tr/Q3Q==,iv:wP5ezY/A+CnvAIdV3aywDfGVpglMjwSTylSVop/rW1c=,tag:QAaTDQHksNB5B/GmCQ1AjA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        HJK2ImmQhgclS5musEdi9AsP4ISIAjn0vkpKAcpW4FELIc4pfmcv2SjP27L1eLQV: ENC[AES256_GCM,data:mxZxgiPNDr9Ym4Sd9RwLdoA74xVZcdHcg+wtfGS3aLD7+1YCbrCgt/2XMS7dpmZbH7mafjweOnFWS8N8,iv:tQM+c3IpmYCa/baY6PmLTDIkZkbDvYICXD/eutyWCSQ=,tag:c16RAF/ovussTrbitVTGNw==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:ctpsJg==,iv:z4bmS3O7JWPeYzIp6cF6N6rOXPueWbeXIDLZ1SCnEQ0=,tag:GtIDUzTiVX0G8xRbqgYp2A==,type:bool]
    username: ENC[AES256_GCM,data:cU+4ERhUR8lF3Q7GmMv4MXmNRusLzKwXj0LcQqqjkF5I+lc1/Ql0mEZMyXZGsiSoyqmnPIiwGNNaiz6m0FzFsg==,iv:GpQtrHk38DKRt4D9Soj8NW42GpyDe6zT3GdPbX3I+O8=,tag:GPtg90s3tPKgMiWM592dzw==,type:str]
    password: ENC[AES256_GCM,data:uyXsnWD/G7XEmUOthJeIA2fXGmUnIB1/72Y4sMd865lwQkGrHZeZnbzY9UzbQid0yhuGwzTD7IYTgkDYnjw8/g==,iv:X4yx7UdeXLrY020psrXu82KXA6Ofmt6y5mswBHKgSpk=,tag:sNpcLBMDPLWpNYQY63C9Iw==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:nbLj0gRsBKDvHi1IldoQ7GHYthch2d6vGK+yB6faQM2A7SQYAup9/JZM/BcuvC1Uxc7xgTd6/eeJBvchSND7RQ==,iv:db/Z1ts3VANGuENO8FZpQ3IWqX60vNwnd9RUZMubvz8=,tag:9/NXvFgUhLUWtKNCTnSMAw==,type:str]
  password: ENC[AES256_GCM,data:qit3q7/HJAhXQndq5EH/2eVcpYWAXAz/Jx6jOofmSWASFwdvJEgeMzrdHx5tV3EMThJigPEXtPr2XcQvcHNfTw==,iv:wP0w+vmrA4EZcRnn6Uscv8EZWlAXu9DcRaYe30AvdKc=,tag:CALDvO/f03JVIIc9X6fquw==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:21:22Z'
    enc: CiUA4OM7eLzFV5oNLCisJBsaNVdJd6ZGrs8mokco6Hy1bFr4V6wvEkkAmy+ekps/2KCM71WzBjXvK1ctDIYOmdPZjZrPk46zBrv3B+yxdj+HhcvIOLIZQsmIQ6hr72BCbQ11Fwi2b/XqwZCQZBS5speb
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:21:23Z'
  mac: ENC[AES256_GCM,data:bhePijVDl8sYukWfdwyymh6jZxYA5TBf2zRMdZaFgc1ZLt9JlWidhbDv1XYcSbEUWoiGbSq4Qj5peY1UbCSp4ug74/7Z6EYP7UB8UhElOCpih0P9s2nTFZn4cmiRGOBhfm57IH8nI0jYEXZSALV77N5mBZqxtVajL3IGnZfN/Mo=,iv:Uij7vhLRf2xcxbgU4+nV2egoX9M/R7M0TWG8mkLaD20=,tag:QTrv3e6KrEJeVJxNt1ANJA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
