prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:UQ7HQqjxY6qyxTqh8L9yk1BnQaWTeOlBdq74mrM35OKTNIjz2lNVtn98J8RqXauSRrAJoDo+5jrDOTxKQTg6qj3bbb8jLD68EEgKRPnzE1+zEEELNyjk31NrFch4K/2yGqgef3Vsi9RnQqWRMIKE+eMQOs+IFqzKlaw+GLJUwLgDgshEU0OsJuUd4ULOXWFXIuIA64IxmomDs2Dw,iv:KjxC34vmiOfbLS/MHJnpVpyQgAeILkFzWMVmRzwPZ8I=,tag:/FR8lshHBpsugS7BPofeBA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:eydZAbHzD8PUzMKs60dz/2bW3845BmMRqqwSTTck+NdqMMzTUY/aatLAXBiNEMmdY61qQkvKMYMlMKiYk3kLCQ==,iv:3P7XscuZNwXgeh8dIKsfWyKUJdaQR0kgB6M57dFLnpc=,tag:PRmibBmgWHlRGN7uhtmKgw==,type:str]
    password: ENC[AES256_GCM,data:ildrftxETj+34XnUkG+9iqsJKfA/eD4ULVzSW5H1zDxWqTFScBirrbgHN/6oi/rHAtOQ2KF/mK5Cch9KKR1U+w==,iv:02kGBmXSgfV13skAHrqnzAFGiLyn+gRX/aVq+9cxrPY=,tag:rA7NrCqAu7eoo1n1wWNttA==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:oA==,iv:4g56fEMuLqGwIkf0LwKmMxrtWXLkXUJyw5jT58BemKg=,tag:8Wuf88W4uCIe9AUXZY8h+w==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:D5LS5IgmkdEIRA==,iv:FM/84B/DEclQ+tvH1x8w/BpW/9XCYQnPtHivL3dGOGE=,tag:behl6yR08avVZYN8h/TeCA==,type:str]
        orgId: ENC[AES256_GCM,data:ww==,iv:kE3Y0etULDX8b8cjcIHaFi6DrIVC/Qn8JIccBdQJWtM=,tag:Nboqrfh2O8+KiKhv3x9dMQ==,type:int]
        type: ENC[AES256_GCM,data:vKUtl4pCm5+TBQ==,iv:gf/3nv/6THqrzvSPX9cTryPLq1E5mGo2FFzOZuQge7s=,tag:qqFCl1MGWW1UXB7exPcn+w==,type:str]
        url: ENC[AES256_GCM,data:CemWsgzBW1KZJ1UfIKhshNz2y2S6EN6WDkq2acLT4dc=,iv:Onq8JfJTRavhgnB19pFtGvD5cNy2s+FI7utvXuCRM8s=,tag:kugR9cGWPm7T4NtNw+fWEA==,type:str]
        access: ENC[AES256_GCM,data:WhN9IN4=,iv:5L70tMwAeSN6aAVyKXx+6FGADxgRAVj1+jCt6Qd3AzI=,tag:EpE2Kx1r7XUH0LmCXyyJWQ==,type:str]
        isDefault: ENC[AES256_GCM,data:l5KtIog=,iv:1C6qCjvzk703lq4SmIHoxgKARMcZMdfL1SxnZjVzmck=,tag:SbVJbiGs9G8Cdwfrzlt+yw==,type:bool]
        editable: ENC[AES256_GCM,data:UXJvFys=,iv:WMZ21OVkefvValgNrlCQwPudVupnWgkNr22LYZy+gm4=,tag:Gm57MWqwzcwM+NzHVIVdXw==,type:bool]
        basicAuth: ENC[AES256_GCM,data:JOjTlg==,iv:6zhm+tjEMClyrt8NV5wS1aExFyTigpq4B9K59eaniN0=,tag:wjYV7NxMQlZgLbWUDiA8yQ==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:nbd/T+8DR3rRarT998wqxG2Qu7rS7dsPm5uTKBH4292gNPqwuoSl/SLEQIoMKlX8W5R8KJHBK49yQEIMlaZkIA==,iv:YQF2i8mJTNGVqUXnvzn5Q1TG4ppUoRm9ZEj4PJNKd0Y=,tag:w8XuyAsdYWigsEu6CBIIdA==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:NgR1BuMbVncgTOVhyx59vH08awrHhxq3rcgSygsowQaUrqfwAHxdaeFcPuzmfAmMFif2hW80u2qy7w77RC/iyA==,iv:ZRs83bcz03hQnYRdS/7ZP/DoRPMMSuHS9Wx2iY0ILpI=,tag:AHs2SqyjWmBd8rG4fEe0Tg==,type:str]
      - name: ENC[AES256_GCM,data:F0et+2uqBO7Zd1x9YGDf0UtBKJ/+pXRGXkbGluLrXw==,iv:OENz9zcszUlCwNYuy2Dye81gb/KHTK3XnBfGqrIHSGY=,tag:XAgO8jRS5uP/rUlB9wL8ig==,type:str]
        type: ENC[AES256_GCM,data:v8UstQvMgrs8zaxSOk/EGsDekWE2CfL/XlK4MQWHcw==,iv:GnQKTdjVM3wWzzGFrUtgHwKFZr+sp3GzqIVwdb3cOBY=,tag:T1uVPUR0rymGrWYdvK62TA==,type:str]
        isDefault: ENC[AES256_GCM,data:hgEyZ0k=,iv:Sd3uc5IBx8VJSabrasJzj8Xaqoxjl0JaMXoH6TRkEcY=,tag:N4okegpX56yGHjzWe1gLDw==,type:bool]
        editable: ENC[AES256_GCM,data:Rw+W+A==,iv:3fcDILEU3xkM5AQGlVCLz0UMvbJyis/CatG+eP1HGZI=,tag:amJi1zlp4KZ0xlzlAXk5FA==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:31M4ttKlwhwIGMl74A==,iv:vNzWwCbNNrH7R44xhNZIDJ9PFOYNGQRi5t/xh9B1O0c=,tag:LtRINEP2IvOE+tcrHyoYUA==,type:str]
      value: ENC[AES256_GCM,data:RIcvcfGKoy9N8MLS2+rI1T0VtqEcLYC4AkK/DT2Hz7AcGIGAoYrKXC/TA7dIomEofJR1odKC3SDnjlAYclbPrsOfVt3pRt+x4N1pu/fE/vksSWV3dg+dxoxoeiDt0YAPqYLj2+mRU0d1ZxhXR7YZ+H34t5+pJ2b3LpgZVPVctOczPaX8LKe4//4Bc0BKfmioY6tSackQ32GYWuq0CuErxbsmvcgANxzGH3/JUruzLD2+Wg==,iv:1E3+WLSsXReKRzpSaNdjUV61Y6GT/lzbTlRkeEvh7h0=,tag:E9GRGG7jhyDVLEhODmvHmg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:/kz35WCMNZbVWVmmGSnjr3+a2q+lzlbiCXd/pGMvyIwVl6ZeziW31oyq5DfmHO6td4q4Mamzarx8DiExz27EWg==,iv:DOmIdOam4GDQrsQbwbTTrg4gDGa10RaxjpLVSqw1hdM=,tag:YZMDfvJccmJ2VeMa4rEfMQ==,type:str]
        password: ENC[AES256_GCM,data:Hgf1CORhvsNDp1uFN/xZjA4C23hQPETr0s3G9c97EPNaZWa0TBZcQgCwTZGL9Q6Eo2++T4N3p+3r/t3BDzETNA==,iv:AD0JxO8Ie4TJ0eIpgBxAS4YnfdNZ27dfzl0hH2/ZTEI=,tag:+vm2mT2pgFk+8H2fk5zEew==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        HJK2ImmQhgclS5musEdi9AsP4ISIAjn0vkpKAcpW4FELIc4pfmcv2SjP27L1eLQV: ENC[AES256_GCM,data:WhQchbYtBLL0kbv3L2VFHVRgksa2y4wlZZDkqG61Kx2DAJxjsVzK9Cx+javNUhy22Z0mFs0Y294Wl8gk,iv:9q/pIxCeM6460E7xT7/ELBcr/vyykWwNeEFCCyhwEEU=,tag:G/vcl9MG7O3KvHgg7XXFaA==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:65GfIw==,iv:W+EPgFDGe9gPilccZAhLIJNOXqQ+NONyS2i4ljSBLpg=,tag:C61OdFp84514Lky5gj3acg==,type:bool]
    username: ENC[AES256_GCM,data:hwCO9E0Eb/gIDr7tynz3uOXJlBhpCGEbJfSYw9bNWfHP/mY+WUg098ZCNgH3jjgskVTS3pfNR/DikEAYqEq/cg==,iv:s/AzgAmMkdrtbjaMxzmBgAueN89OooKP6U9NxcvvDek=,tag:wUZy3aE/oAz6vcw+7RPTqA==,type:str]
    password: ENC[AES256_GCM,data:xi2xwzBzkx211WpYor7J/qJfwAuhmPxnnBX6hl2P1yJxTi1C72Bk9MFH7PnwWcFgvYyz5emxfd0PjkxBCKvWUw==,iv:n6DIddDu9tk2d+/KWoWjkbrz/DF9IT8oGzqpn8JPH2I=,tag:5fSWjH0jId+va1KtAcQgug==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:18Z'
    enc: CiUA4OM7eOZuTcBxDhLfa0fpyG0ZNVbwRLL0Dzprk6DLGeL/SsXXEkkAPHlbmSoVkIGfSjYYo+vJ3Yle278dYMr8h1/CM1BLbL3SynpTyc9uO6hjNlnhvIx9yWvSr3j83TX7hHxlPNNMpiM3iOaCdSM/
  lastmodified: '2026-05-01T14:40:18Z'
  mac: ENC[AES256_GCM,data:NzSDvEEDHj8hsbMLsBPsBYoK6Y34Imr31OCB4MuXcOkniUUFRNuMFEG50j1hkWNlkYVEldUEUAJn/ji970YxXumDRlHS34wGVoaf4miSRXOlWQml0d+ZoFLgT45mtgWAojNvfgFB0Iurb2GNcFuPL3HXZ+/G+MD3MbVR/WmN1Q0=,iv:UASfclsONrOsNrlKaBbSkx2S3rNOpRg8ieHK+Toyg3c=,tag:xmiA6imcyyClti/pXkNF2A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
