basehub:
  jupyterhub:
    hub:
      config:
        CILogonOAuthenticator:
          client_id: ENC[AES256_GCM,data:7wNN1WRg6trpcmpybtJJrCrG9wigj0s2uUrX1zj2DK20IdGh6l/eMkLeFnHUappnEtww,iv:2CWD34QDMAng/PPUZucHsd7IXrfa5XiBEN88hUsHlPs=,tag:8qAL4CQrAMPtgtdensS4Vg==,type:str]
          client_secret: ENC[AES256_GCM,data:DSgff95I4n2iYCrdc8fLtcTXYyMj8700gfZpbDiJHODsQP9swtHIoZzJdTclUvI3xqmw+1NMEiMak99rwiT+KT4m6O8zHSL5xjOsXKb8jPySpYrgl0U=,iv:idmxa+fZlZrD4WIohG5jGS/uI3P3ZATT0UoOYNF1Ydg=,tag:PJLUhE5ao39f+pKZo7EjfA==,type:str]
      extraFiles:
        usage_quota_config_secret:
          mountPath: ENC[AES256_GCM,data:fLoX1CT6zS1pKhubMkivoC4e4PGQfxNy3UrmziCVUiZu4JvxaWr7qGTA0zjVf2OJy7D3rYpMekZO8p8/SBaluqrtL9J8O4PbSnENcQUwvEJROll7L5w=,iv:qSrE1R4Kz0ttkXnLbtROMwbkAcHJQ+MA6H52WkLxU80=,tag:xcm5nmMO3YoI9NDvWqGdmw==,type:str]
          stringData: ENC[AES256_GCM,data:ICBgyED+c5vEBITu2gV/dbM+he9birEgFJIYcWAj+/3ifSd9MPyp5MMWXmL0DMaZ+EIgID9gfGvks4xwzjl23qO5wQep1k6nuLkeD3Om7/5tmH/zsv5cZCbcK3PVd5i1InPbbson9FMSul2LI96eJ7fl2G5iKIyJcDt8NQc4k+cHPwkQCNdjV25/7H9zW7TxqduyHHxsW+AyJVHOcooGEC8lRb4LcYcuINqdgXEB+lBV3koEadx7HaolponCwo/giSzvKljtoaqWZ9Z+kZQmlZSQDfOW9pV15xFIhRhax6+6vhXeOPOxyyDmtAwSaN5MWf3PTXFPOhhMzvL97NQYumHihGPUOHGZ06Xp1Ke3QSWX+S6QkNqcM/DDEh7NQwVzqeNqMRljbvnYyHVpPWTro0opZo9gTXY6tVSyxwHnmdI+t+w5fJv0DHmdkhGrSfkcUK3RT4JhItHAJCqVWzDZNUatQmSVtvW4TvPZbbAI6f1e8l1n0yRjsfGl1pGT/Iss6YERcTRWYfA5cFLJZrgagT7GwLtV5hbwS7NpHBL+9iIWrEqRjfFHCKLCcPi7lrKM8ZPQHtj5zWfq3RbwZxbxozYzmCZSD7TsMCq9j5vHmokuRP9brTuZcFeEVznv25kHoVHQAotd4zjaMrj0AQ==,iv:5UeVrOKA2taDh7s1DPZWqRkoTD4xVxF68zo7K8yWQtk=,tag:VwRNRnTfCLMq2dXREdFndg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:15:52Z'
    enc: CiUA4OM7ePgnqlZ6OOiMDiQsqgs9aRs6Nfryj8LyijH6JYTD1xudEkkAmy+ektda1swGQt/kwOyai6hatVGFVKM7J+Lmf+PdeGh8/jGYkys3dsiWMmu1lqmNI4UouLClBIok+N733O1r/h2s/LhouMb1
  lastmodified: '2026-07-29T19:15:53Z'
  mac: ENC[AES256_GCM,data:KtyHhYsbcdKDZ99piR/RfmlSIokfxlArv7OLo42ExQ0Htjqe5TdkJ+4G+YnU+/4fVymcpmecbpmfdjydHydBDqMVysZZ/oTkQIl8eW8YtOo/oj1HGFmwci5xCfmsYWN2ffZrOghjNANOm2u8FLSuZ13ZWXHvlZ8I3scx/avhd1E=,iv:2frIuhyz+9l8h55JceECr5+KNJN+yZYVYS4KhDsff7o=,tag:PgHU8g2fMh2NUs/OCxwEoQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
