basehub:
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:PD9yvfAvVz6M3y4nPTVQGgmQFUOe4O0l/giNs0gKTDbhUdQKKad5/GzzQc9hnsqn0rvPrxnz9zskSwT5JILLrSiPMhwx8XoKKnrAdKK5i+orFpwSWNKx3435jcEGeJukHzpNmPOSCFdjEzsh9PnGQj+LO5Qzb40Js7EvNXoj8Kdgai2K+lFYihgGi8wqi9a7p20O9ksll2Uz4OGKoT5XqRZGueVdDgGz16W5hQwTiCooa8FMxGfu2O1SRs/q/0CoDwkLQaPa4g+A89QC2XXE8I5tBZGHO03Gly9Fd+UByaNfi5oM2NB8d+AwzBvs0JRabROpJKKORmKO8C8nEAFuiTuX2uFcLy+uIdm6P88AYo5MB5K8YWoP4f4kPvR2AT27t15kityuZhVv7700oUbkgmlQvQMQRiFd4VYfPGeeI0HWvItHOCUHu73Gv8gpEzyeT+tyRh3/UD+n/gGz6hAzxnuk,iv:/hdJz0XFnpJiUMDXIWABT9qjXA7YX69sJTf74ITGINI=,tag:W0SPFVogrhMOyTEU63LRnA==,type:str]
  jupyterhub:
    hub:
      config:
        CILogonOAuthenticator:
          client_id: ENC[AES256_GCM,data:3aoYDYuCQzYQXNJM7xjXbmN+VUqE0CSLPvKFxWZi1kA90pXO+xmOc2Y1Jrph8Pkd00DW,iv:el71JiJUNh8tLjXpmS7WcPlJWnL5HO/dHWITFpgPQBY=,tag:Pg2H42vXwVfvt0XLnGMIeQ==,type:str]
          client_secret: ENC[AES256_GCM,data:fxsYHX4wzEUTNJiV3dTgcQowSmzgxLA0vofm+JVF+9GvcbSVQxKGPLfJI/JBmk2qoWmJfDV7ZQdKnvMO0CudwgGNfzrSOtdiPHPZNJqa5vdW5JMnLBc=,iv:U3i1e0XDVUUvjL1XKUcBndmUgQ/1icM/+Yry4CRbTb8=,tag:ANOsu77m++uGf6OJPzCFfA==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-10-08T12:42:41Z'
    enc: CiUA4OM7eG2Bas1/Z12TmD3gFPegWFcj8aTtNr9YzN8Py53VxDR5EkkAsHDEl0VXXif/NQBRd5PeSaxL0XZWRlDD0othSwt22U6eiTAdKH68W4o91boZVS4XOx2tjwXAzceyI2UETygFrZKr3BE/NY5y
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-10-08T12:42:42Z'
  mac: ENC[AES256_GCM,data:6YoHIgrdijxsW90LlzGFl6SIZmAP1wjmPQ39mUG/QL91hvCC4SqlM9xFnyjlbPVnkHaCsYklefCmnwxJKnqTfo4zRg2p+NwA17z0OFZcevV6fF5druIEe9ileHSc8/OdkxTOFdITNA22vYVPv5jjavFWvC3o9LtW4EI57UaN9Z0=,iv:huwjKS80HTULuuWfr2rtz06TT4QYs2ejG1GyD4V+uAw=,tag:EqhulitNRBjbF8nuHxKwTg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
