prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:zpa1r4e+4GKuyXtWVA==,iv:0n1ZFSkW5pMlcNU/0uycANPRt9LrbYuuhytsKt/xazk=,tag:8IOltz6LJxW6G52Cm+oR9Q==,type:str]
      value: ENC[AES256_GCM,data:MeSxYu0niTt/LXofi28KDvNRnCqXVr6zNkHlKecVEDQ9Y+QC/s56dHddkW+IOZ1kjxXUXVMFqgn+D9npL+68SxpYh4ppP78FC2DpIT+HJfwnoUiBOgazW7lyYl8bRNe6mzHM9jW7rcdyshMBwuilL2FyZVsit+mUqWGU8W9Z0uslThVPhXXv25rCylgp3AZqgtPyZmm+X4YTbxPUYY63awv26TBZ+mRjBTYNZBXseWniOw==,iv:YDZliPi1POPEAzuBhtc4DAIUnTUkH4N+ZjiZqUA9+gw=,tag:TDOG71JbCeeWghNuJbHv/A==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        Appmkqf1qmz3w3rb7eKagIu5mSRcB7MiSBE9rY1wnqcZfw1fhBqbg8A5qmAEkubd: ENC[AES256_GCM,data:RZpgdT4B692sVvx1C+kW7LFYMIkTK4tgvIXDL+WCVegWUIAYPqLQaWeKzaTe7jl9OT1toD0L73t7+cDY,iv:JAfqmPAFr54wed66Yn1Ea07rX7G576qjC7bdT89d7fg=,tag:ErqmjYel+3ZspjmYPPhP/A==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:oeKm2Q==,iv:7ujVwSlFVD5+NV6yTMlnxFY54F0zTbEL+3/BS3OdPGw=,tag:F+CTsY38lxApZ6LZEmw8mQ==,type:bool]
    username: ENC[AES256_GCM,data:n40EpROXk4lfDFGj9uLOjvFDLZidnsQHsKSApFN+evZOT/+lJgzjEk27+2pom/rD6JqUxuC3JqdRQYZrnKzlgg==,iv:PHTBMARvH7mokvEZhNjEiFgGwy16jcECTI15VtU4rq4=,tag:Oq8paRHmsNMUVqdFhvWV2A==,type:str]
    password: ENC[AES256_GCM,data:j2LXJuGz13OKzXazlreoS5YVQaYV2zMiPgoHqTzTozBXoSBu9qG0sCLPVSHPInNEXN5lo2WAhgBRy5tkWV4GLA==,iv:j2lBLHLvVWf+qtigq9OTeKb5tG2sVL4WUKV7Hvaq/1I=,tag:F5FZmwCOPZ+uhFLcB4Cj/Q==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:QNfZaPQ7goP0xfxmIhwQVJtkbtnqKCL1Q/TEKyoBICOJzA6ZiJ8qnCvRfq/6o0ulzYt2MtZCJEyd+YPumrPiZw==,iv:1sJ3pbq3mM8TAffSPm590biKAwxE14nYIDHA5naqMF8=,tag:a5LHMBiR/wZTPbNcaIg+oA==,type:str]
  password: ENC[AES256_GCM,data:4CdmTcsBYBeuu0xgHcwkCrB4U49brxCs6rSnlAPio9cZABtDepN5eLhh0q0H0DPU5b1yflrRDdh+EHm9XIV4YA==,iv:IhvYbegYDDeiQ+LvLfrA4gH9TVN8uNZ5fVNyZ8ClhDA=,tag:N8H536dDVGwFEk8AjKDYYw==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:22:31Z'
    enc: CiUA4OM7eA7DoM4iOXAl3gUuX+yQLjXjg3dTMQF7BREO3WR8xxDfEkkAmy+eknmlTBKLDcUUvCVJ5mJMIIaJtOEkAKkvfI6zK31hL/6mCdQzvHmfkb2WRsMDXWQLqTmRb79Rk1ZLkC06KV3HJpVb+pf1
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:22:31Z'
  mac: ENC[AES256_GCM,data:JwByhFhqkTLgOKfGXPLLc6LeX2zeEUE+qDg2z6HHAfKscSPjIcPhiC2WFqbr4yTpq+fg2j+eAXQjSJIBA1dkRZFCspDBMA1wEILdLJsTJHyUV29QgvADEfXA2AO71Z6FummJzz0lt+Cusg815edKPi2CWOCDKy3WWblz98L8aKA=,iv:tlOUrM5jrv9sxFLUlxJSuFbRWg+AmfaO+o/365rBbHk=,tag:xZapFlnNr/0SibMPUPPSwQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
