prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:aVpdIkDVNi93f3eQ8A==,iv:CAUoMe5qEmDsmVNUewrRrzpkTqDdXchcCYhHTumPVxQ=,tag:Zj7o5sBq9gs+ApZuzV1pZQ==,type:str]
      value: ENC[AES256_GCM,data:LSIm5yqdfCYGjxFIBxDsmR40iUwNmQZgZrXNft+nD3gAIwn7sQ5djrDVnbdpPFGGq0zCRSgzZwNXS5owGhLRx1cPIJCu03uf463AhzzcXfmVtn3N23uAPx/1mqVvGxMjJwWfcj3CQn+v2uBCfxsNYIEgrf/8X3Yp1FIZWpHrrqKaL0Tg/jrxJXzsyXyu2gwAMPGVs/cbBmCYFDNd2gP+DQ79fswu+kM730Wysd8/aJzA1w==,iv:h/CaRDxTdx5o6b6fk+Q4dH7uIOHJqlP+ODjcPPAYB58=,tag:9RFsw1d8Ti4etkUE8SPVxw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:Xq0bhl51wNpBoiTBujAi9OwrEqxJPztKi76HsLxFsB2IO5RjMz49aP5M5uuM1YzcbSNfiulcKpTHRRW6RmYkQQ==,iv:4QO6OpX+rUZOcTqtJbEhA1Z52lliWSSgAgOlHvw2mJ0=,tag:KFn8tNbiJn2c2JTYHTcffA==,type:str]
        password: ENC[AES256_GCM,data:zbMqeN211Ta6nfAfHgtLLYtZgV6cAasbzYX4DeeQup/tZX0mRf5jRyhw01QyePCMdGnbBJ06Juc/l18c+svc2Q==,iv:rPTjgm3tuIutcBchNvstOD+3N+nkSteXygoU8g3QrtY=,tag:rhADvgp7P/A2vQRPHI7aWQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        Appmkqf1qmz3w3rb7eKagIu5mSRcB7MiSBE9rY1wnqcZfw1fhBqbg8A5qmAEkubd: ENC[AES256_GCM,data:nQ1qwbU/I4b3U4u6XeJ1SgKzVsxJzatnyWPqqm3QK5nY0o0Eq0jdPH2vuPrA8GW4oHfWadOITNgI4B+d,iv:86jWzQxagz7F/YENuSpB4CmpacmVpL6dwuYuE4EJUDA=,tag:KRtghIsrfucnU+K1SMu5YQ==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:mw==,iv:C170AibxImVdxmWk/ILCKaxWzIbWOyoUFJkuvQnKhyI=,tag:2BBcxxxNNGdmyJWqrjRj2g==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:kKYZfbOZ5OaIeg==,iv:l3Jtv/+mOWEsuFy6eNH++Vn53DLG79uNlVsMRnA2riQ=,tag:mXs1tQXggfvVOujHeT466w==,type:str]
        orgId: ENC[AES256_GCM,data:2A==,iv:715j4K8wk18RI2/NoPfsa0IeORPBi4PRzE1Va7vZA70=,tag:IMryu/zZITXFnDsuZ+WFSg==,type:int]
        type: ENC[AES256_GCM,data:pe+eimWXi1qMXA==,iv:vtKaC7tDWP3IHJSwLt7gOGyJU9DAHleIMzFskr27rRs=,tag:gR7ZkTuVDffXBWV0U51iHg==,type:str]
        url: ENC[AES256_GCM,data:+x8/toW1gojYqPHKvHJWgjzPPnMFhwY4hzGTtAxGGR0=,iv:yYX2BjGF/BksXMhJ6jP2AY4rngnHn9w52JtV9V+PQCo=,tag:pExdqSQEPE+rFAOKGNIx+Q==,type:str]
        access: ENC[AES256_GCM,data:Sfvtg0A=,iv:DUeaiHJtsk2NbVBv6+JYhjQAaduH8+BgpwRg3EotJrU=,tag:7nJO7yfPAGznwPrluv3ggg==,type:str]
        isDefault: ENC[AES256_GCM,data:bN7G3z4=,iv:WIvdUuoNP7OGgzHZ628MtPCqbomPqJT4yrWqp6kUwPg=,tag:KEJ0dpFDhfr5u5IiTyjzow==,type:bool]
        editable: ENC[AES256_GCM,data:UNS5I1U=,iv:c9E1Zhy8sDE2+BBUmBwcfQ6xgc/X/5eSwZtt7tPYv2I=,tag:7NmuLT5wSK9oZEIczZw8aw==,type:bool]
        basicAuth: ENC[AES256_GCM,data:Yb61pg==,iv:4B8yWZuTtw8h4N7Ux0j1eg0MP4MCsKzSUh2BAGYKy+0=,tag:yt+mwR+fd3lwgeDLbofwSg==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:DnnNJ/pkt+3bsNOC+QVs76cRlpMBooTr8d+fBIPyx3MG4GIhYEBcmXPTv/ETnQiaABLiig6ilE4FOM0pNzm4Ew==,iv:DH3ObU27l2kNf3N+bhWui06rkthE4OR6u66hsbXptk8=,tag:hhH0nHU3h/Cv1vVC8NOk1Q==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:L9FIE2f6yRmZX9J60noQY5fL2Y5+qjQYO0eWP/H8oVNV46WgL7r/kGtr1xqPZgpF83GWtFhej24weeM3Lxbv9g==,iv:PfljeItBxqwEaB8u+UPH69Xs5O4ya6+1+HB3FNG17cQ=,tag:DXcWvFo4mQx46PuDN5XKew==,type:str]
      - name: ENC[AES256_GCM,data:5fax/Xc2Gp140h82loSoy5Uz8R2F7SdYhQfueG3QWQ==,iv:aFbHTR+E1lWixFe8k2B/kQj24KpA8HvRqfgwBpUBR1A=,tag:2F8c/pTipl24kdXK8izArA==,type:str]
        type: ENC[AES256_GCM,data:i+jVrrmuNqnPMpIpl73AgVHQBehAI6EcBtGK9tz1gA==,iv:Vgn2idGic4IAaF32zWKLnB3mUqgY+bF9V/npZN9OAJE=,tag:C90DGPj/k6hPWmirGwxtTA==,type:str]
        isDefault: ENC[AES256_GCM,data:iqXfiww=,iv:/xIW7+z+zM2Bh9KdX7jyZu4pkzwt0wzdchWvn7zvLNE=,tag:SAbX1vI0S5qE5fUweLOCWA==,type:bool]
        editable: ENC[AES256_GCM,data:KEsrAA==,iv:Op2E5p7+t3+9VsnW2xVWI9kCYFwFGVnSjvUSvYZJ+sY=,tag:SpVDL+zIvZx6hUTBm/c4xQ==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:NhIptA==,iv:Rs5d0U9LS9hP9wRLUnlM1H3wZbDmowwFlSDCBCm3Q+M=,tag:DcITDfEbrNC37ldgtDhZSw==,type:bool]
    username: ENC[AES256_GCM,data:p15yyw6EPSASuamuAeqEzPogEOVYBwnvL+L1R/yJo2OGRzllFYpJSGFIcR4rb/xTFdOpupLCgTMi7hcFSwnBaA==,iv:Fwu0SuR7SfIBKZtQ1Gbbd0y/OUN4cKFpK+RvpjxhZtY=,tag:vFk8Zs5Am7UkwG/1xOfcaA==,type:str]
    password: ENC[AES256_GCM,data:bXn8YWlE6W1kKrDPaytMzDYTP36l5gpsxfqwpj1kX7n25icnvkH7RrupL2NdXEcQqDy6S8ZOfTkFNaLU2dvY+A==,iv:439IFt3S2W7n2B+czoEzyhhRvXGe8xMRdTQG+D6Ozh4=,tag:uoVWdk8/FGUi2kPoYcgCig==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:1efhgz1l02IQ32kCKo13w9Y+0oHLAtt//luDhK+TOQ1X2dLmGIM4mEqmhj1EJ6thjUYCX76ZYTt6/1474YB8hA==,iv:IgxMdMPTS0GJYQK3vz6rVRyw2AbB55Zlh86nOv7pxYU=,tag:R2UJ4/G88rgWQj0UXgMshg==,type:str]
  password: ENC[AES256_GCM,data:y2zTtSF8/wnaRpRcvzNGxtyYMvb9Pz/3Foxf7LrmBr4wzxw9cU0RgG9DbZZyO9p4c10fr84ZFtfwqtSPTNNmdQ==,iv:f3Vf4vkU9WFkHYgiePVhtqifhxNtweIVtTjuOfSFnfs=,tag:0GbUkoM6+yP2a//UvovveQ==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:51Z'
    enc: CiUA4OM7eNjnYApfYnt8wjVSkBuooToEJHsYTx9d9s1G8nCM5HRQEkkAmy+ekgzQHY2xZ5iSMCCuVF3CnLhHOvCqGMeFIwkUS8AG8i0Rv6D+MFmKgLObQbDakYSrJfWMIAg+IJjxjI7ZIOuQZ9OsAuSc
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:11:51Z'
  mac: ENC[AES256_GCM,data:Q3KnKHdtqUcvcw6JswMzAGsistTeqnY/aS/DwFNloCanZDEGppI7szwOtexCR7k6AMrM1cH4Kys+LmWI3LKc/8ybEmmjljnM4VErudCgvSrAVDP9/OGPadR6lISSoWUor7jXZh+XSie+w2LUHjMI5/1vtZXHiuqXKOnTV+MfnGc=,iv:wJvPBTPog5BtPvTlWZ73EBAJXgIKlFIqR3Y86qGn1Rk=,tag:S2wU3jwSrkvlKVxJqS9P3Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
