prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:/RhjB/b6jnkR1FDuxHCCr7AbwvIiZQG2MXvrBtQBzqmfFc6U/iv4WF1VXCwJI7U/EAQ5ynot8WvmcGtWyIeVgk3FtFJmW4veU/pKZpxcBOT6Q+N0Qi87IvXCRMEbwsfmKzIcZ06DfwM3Xi3rPRO/I1uNublP4cXzm4dLLEW97C9IJrFR07ZAP6LxT10ZVDsKvMaGhzieDG3ls72m,iv:ntJTDejWwezEvPAXdVOjr2mTd2/BwNvbCnAwVRj1qSs=,tag:j6v+fOPY67Gb5vWIP1qWcg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:YPibNqT09DvsItbHF7m7Kst+ozJXLZIOM81XOR/bgHKSZauWJ/4cBH86pXiyt36bJM7C99ktAmJO5SgI75xaWQ==,iv:cwcqKKwRnp0MOmO6Gyp6WXfdtPdOOU3IaeURZ06bxsU=,tag:NO8XZcjJwMf82B1hTCoIZA==,type:str]
    password: ENC[AES256_GCM,data:l2MYImPUPWoqNSeQhcMmWWAv3v1ZyT0ZiJjY+Y/wr2e/8ZTUzUubudu4rcPr4CnpXuaxsUd8dco0KqQ5NyCI7Q==,iv:8BxfbYF9scAdQxrJLgB13dOi++mPH2hdBIaFYw0PFEA=,tag:AHC2iTwEVNiKg27TXiZYpw==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:3h8iayKcYL6pb/Fhsg==,iv:Z1FMneT5AXV2yF/usM6dFUvVECrMlnXZdQivvXiJfPk=,tag:kCptremalC8HBMYOEfRpbQ==,type:str]
      value: ENC[AES256_GCM,data:cF7HyJlUplxSRsUfW4jlbX6J8Y4XkdiKqBhh4H5ag/fMxuyfS6XTzvnQgslXSE4CDDmuLbKHe1waNdjxoWEqqeB48Att2f0aJcDeurzLDOqTuWtJQlSL82GGkdpmqSA1NmabAJiRBnHsC3ltRga2xzQmDcYHKj1sGXou1IpHI8TSjg9uCO87LY4RfBC7x8n0h0ra0zBGVJZ0qcig3CRNl3Zh7tnVJQB06HaXCvVtAKj7Yg==,iv:z6Ms4eIqD6yWZY8dEmov98oPW6l8ihUYPQxO90X0Ef8=,tag:kibEI286HMx9RdlFWl/Kww==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:lm6SO1UICtqxe6UZ761BRPTD46uN2wsqU6HNXxWGyI0hahWj8+Nxem7XqIJq0T7i6DjaqhI3lYvEJpoq3SLe/A==,iv:9pNOOTfBnsPmN09zTJ3VnCvG6n96tTQo0ECCBB856wE=,tag:S5C1xZZWnycau9pM9PHi0Q==,type:str]
        password: ENC[AES256_GCM,data:Kt35VpvlMdADYE3AKOIkZztDAS3ybKJpgJjM5ImfLrkdgKlmF9XEtHI7nk5jrA6MU5cNwEHBhCdgH5ugdTKj5A==,iv:eRKmCkAyKykZqfNgiFJNiHjOsR4nPXEdkM+wpYmcSw8=,tag:yU5AKwh7PrYKGfK6d6t/DA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        Appmkqf1qmz3w3rb7eKagIu5mSRcB7MiSBE9rY1wnqcZfw1fhBqbg8A5qmAEkubd: ENC[AES256_GCM,data:0jHV7fEGeJW1dL0MKLgYyvao2TmYVHXnmTn9LJl/HY6FXFtQoG9WpBv/iYKcfYbTsGgka9X+G02GUEWZ,iv:zoVXzwM59x7QquARLLZ/eG9Cl3huRZFvSjGd53yV36s=,tag:vFmAHbnxZRTHF+vkoYhGYg==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:dA==,iv:y/pjGbkQgLZTxeteY6e7tq0xjv1tCCQ1SbTgLkkshjM=,tag:eOK2fpUjHjKuvl2FnaGLSw==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:t6O70ZAJ3tAb8g==,iv:tR9nA0/1E+HbdCWsGc/tGwQ4kZmyuJyr3Nv6j3FXCD0=,tag:4XdIbWO57umF5cfRtjKvcA==,type:str]
        orgId: ENC[AES256_GCM,data:aA==,iv:NLRApHbP93x/fPfsheit2nKlFHaHhd3aKTR6bQo4z10=,tag:jRLrxYXIbdJNEKXUMSCWWQ==,type:int]
        type: ENC[AES256_GCM,data:2PwL08Xe+CQOnw==,iv:oMxu7nDoVIFS+38OyLWSFrsIvS93q6nXBBKFaSUCUTg=,tag:ZRWaJbVoC+SOwFoKIjkBog==,type:str]
        url: ENC[AES256_GCM,data:+t87zYwQvxJP0wb+Og+wTTKeWNoBr/Oygpe/0/sOpL4=,iv:Q0CgQ/9QtX44rqnsPz4mzgpIwoeDj4bznCrW67b4XAE=,tag:l7dxevMkRpeHiAYRAUNg9w==,type:str]
        access: ENC[AES256_GCM,data:S9rtcQQ=,iv:7RBC8zUHLxnAR3F4N96AFOT6oGI+Shn9sKu2teGeBCM=,tag:oX25I/HtKJjNwWR3aMIeeQ==,type:str]
        isDefault: ENC[AES256_GCM,data:pcqPspo=,iv:gcjVOK8Ev70XsqjUdcCLi8jlHd7NKU1j7iIKp4690U8=,tag:XTMzywvB2IDeEuubV1GOxA==,type:bool]
        editable: ENC[AES256_GCM,data:ZVxnJiM=,iv:t8SqaoylczUXt8hOpUjIGPGTmEfvGUSS1ubjelkK/cE=,tag:yuOxzl3BCztv1bIFThal9Q==,type:bool]
        basicAuth: ENC[AES256_GCM,data:zlhJXQ==,iv:ngEQcH8CSfzckYyeS/pSWzANrSX4x5Zjo5u955VrAIU=,tag:GOnG1zuv3orQ1PppL3SNrA==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:35L4sLLzWni9Qsqrx+F7/Qd3JSevfixVPZkXsecVtwc16GcoO8cPSPHuu5rbVD5pv3gnKI8ArSYvsLLxT7ISIA==,iv:LXq1Y1mPv6JMg0/ECneYXNNIxtb4TCYSyiErADqH81c=,tag:rgQkVxx46iX1vbWrXh/5MA==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:QNybnPGCveAhiStr3R0R546M2bC9YN3wH6rFSuObacVQsLxhaJM94T3ooEuzNKkvCyZcslV7HPuGcsv3Zb/m4A==,iv:YZPsHa6B3qFZ2ggtTP9ZRZmdOLOK+9z878t4IdkMLGk=,tag:VmGiobWdizdgyy+erTFgjw==,type:str]
      - name: ENC[AES256_GCM,data:JnA5qxdDuNJJqjR6R3At2zMRS/KaJsCF0HUbP6FW0w==,iv:HXPslPfIMWbisg9EC1wwk1xWDX9q6GZaVgIWv2Cu+i0=,tag:DUreSnhZdrmLYhRlbhANCg==,type:str]
        type: ENC[AES256_GCM,data:BL9ieDV+jE5QhoWOSGYNA1aFMJP7eHkEbg1bpzfYNA==,iv:NxGShRuac2BYAgeKjD2bhEBWJxwc/0pu0p2LkOYXFew=,tag:buTjzW39zm8Zdll0JT/1vA==,type:str]
        isDefault: ENC[AES256_GCM,data:8/dW8Qw=,iv:opIi1Vt77Qjm/YfhitloI28ynDZNuhsW0fNW0INYFvo=,tag:ARwhPdgm/fmc6mo/HYfvLQ==,type:bool]
        editable: ENC[AES256_GCM,data:p+7Kvg==,iv:um5OJuxF/ReZ1+9bhWbg8GL5k2G9VrJA99fsNdZCCbA=,tag:O/FVfzKIL6i54O2iDfj9Jw==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:yIDh2Q==,iv:EiP4pvzvjzMhhexSV1eSFPVmgtgksHiKwwDzZIegIZ0=,tag:gZbym9WU7LSzGT/5ja//Xw==,type:bool]
    username: ENC[AES256_GCM,data:/wfUCV/2PiK5NO0/d6JnC1PIRPhQ+7GMZ8c6RSPXjY2vuXDsYJ+A8+tGHd7rG0mET3eUg4dKTynxNlyqOMw0kQ==,iv:Lfk2h9GSj1TBiNsb0QHTM3joSoHLsuWUN+mkJsvESf4=,tag:B/R7fX42Y0Cxe2zj9AbXDQ==,type:str]
    password: ENC[AES256_GCM,data:CTwISNpe1LQxkWR7bexNU1aXjX1jqVRNJnwgBeVQgRZOEBjGNlc68UtBk4Rp2B8hkhc+AfjFaaPNRRbF2SkbSQ==,iv:t6Kk/t01991BWyoOmvlWvuIvlfrXep+qzIo4f2vDYdw=,tag:My4uqjeVFOKtRMagT2di4w==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:41:04Z'
    enc: CiUA4OM7eIa9r00V66ALSaFV1taZPini+6qZSZ5TkzLYDqLmFsbXEkkAPHlbmcQ2f82+f+1Qx7nbDnza38BNVzCDYewjDOcCpRciLBA5DcyOI2k6MGXf5G2AmOLV2eNdWQE1gQyycvbeeCx+8jJSMafJ
  lastmodified: '2026-05-01T14:41:04Z'
  mac: ENC[AES256_GCM,data:U6oLWLuz1eXtyXgl603HqdMowtpapJ8O4M1b2EoYoGfaLBR3ljAB7Kq/bUMJR10ZXvUQU/XCHR8ajYix2Xo+ZNyKdOUHSBUaCrOAXenLX578xKH7wF0mMKP+6AtA5RFB2NB61j6oXGmo21kTkRarQ5FLjmdVoNqSSLKmK7Nr/FQ=,iv:IBEqujbHCQL1d3lvskvYN1U4ID30Dmww1ok5K8j5meQ=,tag:JC9s7Il+JlVp+bLXOXgBhQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
