jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:lvRgTedflgqG1p4r1T6wkHWL3rYetdVbBkGRWtyg181X9nLxIwNyciFhPoSPOHykiadi,iv:jFwoTv0Ld0BtNLU1fRy4Cs76BL1VOKz5ziZZJjcSTig=,tag:Y9K7IbVYewq2ygcv3f4CpA==,type:str]
        client_secret: ENC[AES256_GCM,data:ePkQstUwK+zhHXDU/FffJnDYYQJo0jh+uHEkjZh1wpG6rXSLfdh8QhKLUkotxQGVqKmF50K5W7QRiaiM0h4oK/cH+YJaETpi2YJtXCHkn0G1eWMgHfM=,iv:6t3UB8SKG1KoZqQQPn1s6APjrZAtcm+UYmm9xjIujLw=,tag:jlF80oM7oar2elRxMSIp7A==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:oujFb3vjG5pYie09Zq5GYIPKC5C3Df3IFiuH7Aq1fYM/XrCf+i9l4c6Bc4Jgf1Yi7DYVtvedf+odeBKRlGQav9cj3R50pC1XTXY648Puxx9Zl+C7RVY=,iv:5EjCQ4LcqMQBeoKW1fDzqKvbZ/n7UcHqs/714qKAvis=,tag:X1A7clBe+WHsZnHyLYtRhQ==,type:str]
        stringData: ENC[AES256_GCM,data:bIcl9s//kssTS+hRvDEOPBLJTerD1H8FPKwyVOvg1KP57IF9SU01F9tadV9T0M5lA8wjF8yT3QfKr0Rxe2vNqzP1FM0rwCWG1Dk09AdReoSGbI6WEu48CGptUSADwc0eFCkvB4DMFruJ37bFDv+E8xvXBt4eh6RgRm2XquMEMS6+OAjCwKqu+cJYuggzr3yaZdWHUApSd813xJrjy4gw2PiHA2H9uz2uM5a9H4qZ95vUg3WToxZmVxyw7w3ZYNGg/eInyi9AtC5/2rpSCIG+DLn7Oa2dVE1Xf88tcLDFALWgGigGE1KeUh8E/uw1icPYFBTLb9cnGxO+SceC5eg0OX46BVDaqHw9wy9BRrMIAZHN7MiuNrWbFscNp3T2lywT2S7/d68ueU03FyQs3W+mmubf3c8AlFqvHE0Yxbhq7l3fCtZCYTXViiuKqFEzYRvAEP1Vtzrg/vELTisWrVIP4MiqdyRoJD+dQCyN71qKoQEl9AE9a/LZ1yode1LGON5zrrTzx8CB17MEDzx9/SkPtMgfnX3lmw63IAEeGu+/cfkCK8PVFo4Z42q0aMJAnzXqLpckZ2IdWRlwidCb1PjEmgKgm/Od6kHrXsmjaM/iN/qG21/1ae4gL6yOetaYPKKuS8hRE2YB4ovGyhDJrA==,iv:pSBK7Ilq4aqafQ2UgI9naB5NCavX8bcPOuQAhpaTovg=,tag:M52mhdGOYKvdO4q7m9KrwA==,type:str]
jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:K1O2Qw0C+eOmuKBhZ6x45N9ccpFdQlzYJ8UXt0P0HTooY/LcetwCEQFJU+bd9hcodWfd/OJVMg==,iv:MHDQtu+W5w1ekmK5PkBQaVi+BI+o4Lxk8HProB2OdMs=,tag:bnX9fJrDIHeAwWGATcN9cA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:20:39Z'
    enc: CiUA4OM7eCHOodMYuxK83zDxRZE2RKk20bskzzQelxODZ5opgyRqEkkAmy+eknEqydaHX65jDDq1nZHL2rhYdvxRQFdfrc7UxxWYdUy9xSu+zu6wId8i9/SIwFpBBbybUcQg4IGKm+H1YdabreqoWia6
  lastmodified: '2026-07-29T19:20:39Z'
  mac: ENC[AES256_GCM,data:wjkYhlrbQ4ifhniAssIDUiytgQncBbnF0cqIeaJVWOQx8rrK3m5ktPBSVyJ+Yf243ltcH+KcpYfB4bCB9JKQI5kFRpZK11gp168IYntjwqcxjnk2KhotWBU1I4CAVnvBR9VkASh8SD80ml0xapbdWgsEPqLaLTYqYqOEB7SRLBY=,iv:j50ARnyndL7DipOTEz1EKBB67eU4PTHTdH39dL7iO5E=,tag:4oStEa746jz5U2dH4BqUkg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
