jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:dmVE2Tsh/P7sa/YFIsIOwU8oTom4DGqbejjEG87d4WFeJjoS6aye4VHKsdqpW+ZzcOHy,iv:Ur7BPzobEMxQVZ/sfj0KHoFNlar15xELtGRvftbNxKU=,tag:2wSpGI56WEeUywf6itqtkw==,type:str]
        client_secret: ENC[AES256_GCM,data:hCpyWv4LYleF+DAAf7KcXhvVF6JPLcmNy9VjQ7eFFAIsPT4xiVBrrDXzigMg4W4tF2Bed3IAw6GpILGclc2Yu5iFiWrD0heh375wo8AQXrqxJ1H24Tg=,iv:+kDEDnRKSGx5rfIXGH/auiMVQ366fK444G+SeF3bEMg=,tag:PNDsXPWPL3QFH6XvQUx/wg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:mTlGjO2zDkNs8vw6w3H6nj1lrl3RQYXxafIOhVXgme2Y/y1cu3fslFZdWoVsVvsHAklq612hqEBiT3KvOO+oDE6In/n81wPUb7wID74/RFAwnKTBoVo=,iv:naaFa6o3C98F3WAZO0Vpw7WFMFrEOxg+UmPPWfFHBUU=,tag:K/d5Pmc5zatEnO6+yOjp7A==,type:str]
        stringData: ENC[AES256_GCM,data:U/K1Jgv0enXvpi1WjNxw4I4CixsliPCGc6UniQcrD8Uh4NLF/kV9J80xXJFKh0P29NHKfxbaQ2PudV0tfmCtD+liKlkthoqeTh4GOBv0MLZIhNhqPk0EpKO/uY8MwYO1Sd1t9RVJj2rcMDEPUKTaZwhFq5a+nRiVxtVGKAWeZZabU1eTDu0f24affIkSkt+hqxzHHRtewHkhaioX2hqydw2b0qvGAHDF44AVkchX37QgoZS2pPPkBVgt7LOLotmYsVkd+T6dNU9kjzjLmKE2iMTdUvKkPNqoh/hyVVKH8Z6kpe00RSjPfmnZpaAQxQe66DcVES+FluOkDhWiLvw2RMeJT2DLKNG8ypq27B8kzh9T5Gp6FjEpK359SoUgOJ+4xyHIw1Kp14Gp0uTqjELTcoJkIz6XNZ+8RmvxgwSw1rxHrbotGn3dHt+NurYzn/0Tc/UlT/gRVyGNsi/1U/WZik29vRZwaPCRdNflXvKnrtRI3/x4LrKKh+MY5CXaAoLDxThpwN6AUr36Y5thItxRC1IfKaYS51LtQg0xvXJaUzKtO8pteJmst33Lmm1yxNOQ4CqC8yJsjbzhey3igFTdL/6vDXD9p6nU4L0riolOUi18FjXkejqoBe/EZy+8nEK06UngpCOFnR8XrAJbBg==,iv:xx9/ryEyeJxr18q/XB/DzVzWcILRn5DSQUrvMlfkw5c=,tag:ymsjL/x3OBvyNNQksr4cHQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:20:35Z'
    enc: CiUA4OM7eCRFUA5TdGPe+d41druKmfCjGE1BAu0/jrk6pz1S8e1sEkkAmy+ekmpLq/POquQ2G68P5mLfEqtzEuzb4Im1tSZMGb2kSPms29q31nRK7nl2t0kh3cwwroUEGd5fxdBeTxwB5/AFna/I2unA
  lastmodified: '2026-07-29T19:20:36Z'
  mac: ENC[AES256_GCM,data:Kmq9j86h+x931MC/mjAmpnBQFBbbDx0hO15UKYVmCYm60jRoY3XE38C2T2oRJ7sPvL2RB5XuGk5PrxzKGdjqGzxN6BZEAOlFIt3TtTyXDcvZ/zT+L9yslKPIgrRlgrUqWRUFPGUACJA19WuYX+jTUk4BDY3tHZOhMGCozb453rU=,iv:OvLo2I/OwZRhVaY/C4MF2QWEIBB+OUXizA9SI/LI9Co=,tag:Cf9XZYVeMNpABpn1Oww1rA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
