binderhub-service:
  buildPodsRegistryCredentials:
    password: ENC[AES256_GCM,data:FbTaGIexDB/cxX/2+IScsISEsoTKaKgZ4H9iTCfpzPpm7k4B3oEe6dZYDhImCNVCY1KqVHCt6F9Smjo/dpwYwA==,iv:zqity+fFq/gU72UKIiE2hEMz+gxih/L7FwDj1rKwu6M=,tag:CHDUNPVLd8eJA7SDi4h9aw==,type:str]
  config:
    DockerRegistry:
      password: ENC[AES256_GCM,data:Re1RI6Ot2d8SIQnFV00YljURpH13QpEwZ0wCmXDOKzhW+o0pC70H9I+qyI5oJZ7yEruSoBjGjsmDm6gomA0h7A==,iv:wAy064r+Yr20f5usNa/S1DQ1/9OiHZdyxVJ0IoEjU8A=,tag:UhQ4QpKDKU71Yv3/hzV6zQ==,type:str]
jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:Vao30C7QNyYzqtI1IPaPBCQsX2A=,iv:8MA5zYsB+bwWjKJ7H4ZaPriC1qZsc+yC0H10WseU6/g=,tag:g6muZj0NzEMuhq/d7N+hVQ==,type:str]
        client_secret: ENC[AES256_GCM,data:EpP9EVXc17+aO1GNheTmEvLamoyrJbia/y/MfHYx3eqLCidkab/Qtw==,iv:6OjXyYhVtcR8uQdsG0Bp5SS7alJx9/9w/wr2tw/zbSA=,tag:RoKvJnC0tSQL+0AYGY9LzA==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:uX5wIGz7QpQNgBGgpUU6MfxC24SKK4/+jR22mkIEVQUBtMcN5zsRzxgzzSgGWQ63RqvXfospW6/uyLKSf7BIRxjS5hd+fvhp4bI/ffH+w9DnlUZFwPk=,iv:rKdJsd+QxVxmjH1fJPmYsl3JV4WJKNvT0SA4u6UKXQc=,tag:xZzf56NMcFFnsmvc2HmHhg==,type:str]
        stringData: ENC[AES256_GCM,data:1D1bFden4P/vsncquQjTNL7jb2tAcDINnMQNU6aeqkST/zt3iBNFPSfwLgdY7HNIzPfcmmXqEN0qQF2Zz60RyXh1w8sbkIu0zoL8yyFozZ9hyD0R5Cb3+oBsUYjvKOO23B+Nj0z7Tmqtc2HKBvpIipeY0AW9J3gtlETdqZNxkSpX6i7l1eZNiq2Wssskknam02bj8811m/PfSy0YRCJBoBfAxlXiNlX1LIuS5OXRw8qekrqDoA3NMsiV3G+lJI36w5gQcTr1tJRUT9ZfEhtYHZ3+DyH3fw6JqqWGpX59uwyDHayZW/VFRHxNfWNyXICydV22c8BOvR7cfXQrF8W2W20njeGeL1mVyo3QElpCix1lw09fZfVDWvvpgmGnsq1gGmJu3e2JCohIh/ZjEC/6Q+WO4uGMZeFAzfCSDEAm2HWbxdyzZE48HKtQPhge4WJ48jMkIP/+8Y/+UWnGRWvB14ky6g/Gn/Gs2c74TfTQVqciCHA5rWwI1ZQbe9t+3m9KAX6Adb5pMYt7pFwDYvA7GpTuKoHqigrqH8MlXPtoAXC0Iy3dyT/pN+X3uwJfML0vFUtDLxpuBn3nCcAbV9Athq+ajfurr1eIQLKJMvmBwSY0Li8hsNuZiE8stA7FFSk4MmMs1r0kEXmsM27Jbg==,iv:Rru0Qe1pO4tRLjprqe2ZDIpODpiRwa4TzlD24np2ldE=,tag:kMKIFpTkdyNEDyL8BFzL4g==,type:str]
  imagePullSecret:
    create: ENC[AES256_GCM,data:HBrD8A==,iv:a0zI6BtiFmbdwKuvr3zSZLklshJ72Z6ANKkKRklKosc=,tag:2DqevPAOjOFATFRJxOoGFw==,type:bool]
    password: ENC[AES256_GCM,data:qXPzCyyl3H/wVufssmyPs/J/66D5MftVCFPhU87HZGw4XkRv445B8Qodorb1H/Vx/pgJIAqrvGvQhgbafmGvTw==,iv:SshM7pELCCwWX75sSIr7xKEBiaRorBigKXKNME522Yg=,tag:v50FkLfGzatK/dGsZiQfdA==,type:str]
    registry: ENC[AES256_GCM,data:zP2v5VdYfg==,iv:T4s6DP2GWlMeSJ43N2iXQ6xXUWNqrUWyiONHsIbJEEs=,tag:vt3rVl2FZY2RC6ql/yZUcw==,type:str]
    username: ENC[AES256_GCM,data:g4jNqP6cmj8aqcgDiei3dKENd/Vq6pJOuHME4Hl2ADhNwdnF9yI5pQ==,iv:IoEtWoac/vJaEJXyFUR2NdViBK24nVgtxKEEePQ/zVA=,tag:4/SVUeNlb6sB5zaY6/S3kQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:15:56Z'
    enc: CiUA4OM7eJQnIvEjl2R24kTIUzVkY06CuOcEcMzojk4jZPfw2zovEkkAmy+ekvJ67/q4yEPS6iYbId5ndZ/j8QvwJ2R6zD0mcwtkR/VLPhz8WItR5Y8ectlvkTFjuMJc/zTxxKuwqK297ZLGfoa3Brnf
  lastmodified: '2026-07-29T19:15:57Z'
  mac: ENC[AES256_GCM,data:3RW5qOGzO6koPYFM7qL3kehXaD0anNYyJnSh8T46fdeTAiVulm6ZNynAAF1/klUqhzSpnsBMYqmOUsp3sPvq25kNHgTCcWDohe+xVyDODdv31fHRwufdNj8QaOQ0IZQd8h0gOr2JVPi+g7v570Tam7rtaorGCgzpOk7isd13u80=,iv:VV4N/M7Uo2rmzxkuWVaz8L5PEYARcafi8Hcy4xE0/lI=,tag:xNHK77Eg3SyaxFz1YcJV2g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
