binderhub-service:
  buildPodsRegistryCredentials:
    password: ENC[AES256_GCM,data:G8NXIIs/twOW7qwZg4Iett4rkCncAVI+4G8DwNpDwvcrxz8spltHCsAg3zxGcowVVmGLrG9Sju0f1MLNSmPnBw==,iv:sxjASEqhJdpb4goKrjn5vEtnzu8YMfXm4IWhR05ko+I=,tag:+ugJp5VTZALdmHyQ3e0l9w==,type:str]
  config:
    DockerRegistry:
      password: ENC[AES256_GCM,data:pbpuwvCZlx1H8EbY6LuG/SjsmCRjfKvf1J8Gp6bMboyT9njy0r04azOdaLnt4uKUB2D2p1vFZH6z1Rp4chtaAw==,iv:SaRdw7us+v43GyXhZzPRX1dnJ62PVqk8XowoJ21J4uk=,tag:CmMJInwEXTLsRHe9vR8i5w==,type:str]
jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:ulTcIuOJG7nl7rKwRlN34dWrmHY=,iv:seyvBlntsqxr8FUu6yja8qqP2V+DHR4rOYKKWBSJovM=,tag:PQxK55I07yoyWZnt553zfA==,type:str]
        client_secret: ENC[AES256_GCM,data:/yFwv8QqZZZqI8PMjhOqW8VSSP1NDHGNnxcSQxJsK6zyXruaF79s3Q==,iv:UhqcbfQxjLEwikGn1qf+v0gFSrD1u+Qe1Qcdv7QR9wg=,tag:PmQ80G288/x0vxx8o7p4Kw==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:Ls6c2Kh59yr3X4ThACOJLbYKvEp2oMl+mXOSNXk047+QwtX3aHOfl198igoQGQu5oszuDevujsHUx4o5abPnyBVL34L+02sFXrGSwxkXhz9a/l5LVqM=,iv:xRBe6oVOsMw3AAZAeK1i777yCzr8ewzWNLaOV4H2SoA=,tag:fhjCrIZ2/WvCOjpis1lgAQ==,type:str]
        stringData: ENC[AES256_GCM,data:i4FSy1e1sFKpLtCQsQV2Hbv0bGUjNKEMFOHqd7ygSPy6KuFqENtuRaq8PeE1iDtRYtI7A7LAOrYI3NG0QTf0IwYHQn/oJdC4srWYhfg4pPtmzFPaqm3z/GXbRkzMYOd5eJcaG0KVGLhewRm4OUANYpLbn/HFD+c8Vpd0kMTOt/4Pq06Xhq1feWhnkNvADWMCtsYz9/mokJAWbr4hb1oBaBUdFHUzTtj7wN0Z5CJ39XOP3n1scHwA63FuQMZCIUxwdYRo0TwFJj8YAJj/YQqjGXLptzMRKCpzqWmTePWhlKhzzTcRgG2LPIvnLQCQRiAc6ILEP565VJfR60ix8DWtvWWnUkmAoWNu+8hqLw1sVrNKQq/2QvdjRR0Lqp5igEtU2GOm7093xo2LodwvAkUvyMRjRB9gvv94kzhzaTAdLvq7NB3LApDXmTjXtMmSF+XwyvFMAZiX89v18k36z/N6gxqCl4D0f9CrCrfg61GM3pmeL8kpohyeDCiwh+FofrrAaAQSsWEz2+3003UnxNgnE9QU8sjVyxvfmYCNgNJZ4+xhXHpDyqqL8hn2QO6JjqDXF2M5lIsEPrubI4iw8IvWBswSs/pd1VtwCiwCUIiUH91bMeF2QvqBxAMQEgnV5f6OQF8PjYffwUfsKVDW8g==,iv:sTKBtAtM9EYPuUGzXh99ohKJQZ0Jmb8pAGavoeGLkco=,tag:uaS4sA/AmJDb0yEGF2dmig==,type:str]
  imagePullSecret:
    create: ENC[AES256_GCM,data:f6ubMA==,iv:WfjhOzkKIv1G6LbqwFTpCXr125AfOSXoyLVfTnMxqPI=,tag:7LSx1FSPDhxnNZTfkvFOEw==,type:bool]
    password: ENC[AES256_GCM,data:sQ3+J79PgT592S11pRimP2BYtaXU+w6/Qyi7lWqTTgqVxOUF81I6siVJTaDkILZHARTwrr/DTwAg8DzmxJRb0Q==,iv:8cUk5MHzV3ET7z/PuACEfxXfXmCDz+3uhhDsFMAr4Fg=,tag:mlJsYWBZVZBPjtbqEcOb9w==,type:str]
    registry: ENC[AES256_GCM,data:0FK/BkHhOQ==,iv:Fe81yaoSLWBRx1DG4MQPqvY28ZBLTFBwHa9k9gAgcvk=,tag:R05JeMtHot76KBJdDvUJQQ==,type:str]
    username: ENC[AES256_GCM,data:Sgj0WMGXftZtyJ5vyG0guyL2JxzrxKxnptCIn+XbhyGljykujuTdzw==,iv:vk+0hJpHRsz/3ppsoZrPVY/kg0NfZmqGRU8ZV11uUsY=,tag:rwJtBlEZys9tkeQrmm/y+g==,type:str]
jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:XuMjaPJ7qtV24ZrjPEehKPrcTSm/Jx9Ucsyh47XlN63AHIWMo1x2b+CwBRna8tTadwQo4lnE,iv:ZM+m2ZMXhGAQyxW9XXoO+0Of3Ck89Wwcmjj+NhlPmeU=,tag:HsjGZHwJ+gL1qxv3NYtSWw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:15:58Z'
    enc: CiUA4OM7eES1lYwyvJhajchH+Dxg+/zij/Lr+cn0fedu3Njc5VOzEkkAmy+eksDFII5CEmTVMo8u3acUqJe+bZ/bx25knCnGj8OVteRbh8db2/bD9CzVMsC9QqJmrR1ep6Q3li57JcRZDCTZNBzNUFte
  lastmodified: '2026-07-29T19:15:58Z'
  mac: ENC[AES256_GCM,data:WfaSBwaIif4HJ9mKzSgpbjkKYjoiW43DdUy4jcNqtcTXbAfcJKGVMg+O7x2DDrugE8kZaWCxEKaP6Sz04ZQmWS4D9ihkI/XPQRsU+jVLl1sKxskb068uSASenFvkO72uIZreZ3/OLoCnQWdcZUC2VdJvgVC7I3oUgzV8VG+tang=,iv:SgIeOc/DfQzgldE6CXlSrjWsV+ChMHosviZar0gTcRE=,tag:5STroAxyYwdNv5tIi2Eq5Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
