prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:ewfm+GEd68cFNVy1wA==,iv:bCfoltuqyiWbp8fTWP3w8zJbbIfaHiYngEHySOjNyL0=,tag:BFqZAKsu3QWeWvAQDTtRdA==,type:str]
      value: ENC[AES256_GCM,data:jTaq4RlYvSEORgsz+6gJfiwZIN4DdEBpkaAL7XgJd26Bw9KP3oYq42Y7TeI3qAs6cZxGSUKHHmaRJlvk+hkdGnYXifIs8nUopa5XZ/Tld9xd6kqJGVO3U3o6aXqFCPzZkY07mPp/jKi60rQRVA9QwTLwrAB9pe/jcya9hnVjYm7ZlXcGZhFO1PY1CW6l4Cho4wgB1ypZE4mL35rcizDzAMn2rn3IY5TJErUDX2m/10thUQ==,iv:+11pr0siOuRVqbTxuWf2GJJ/2YzpsBEKpX3j/+ZCitY=,tag:zGdCTAIZROuok7qtL6qeaA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        2yHrt650J58UveAE5gjXMRBJQA5VHmsgNB1FuvwrfPVvdWYAOane4vUsGx7WNrDf: ENC[AES256_GCM,data:hnEjiWMSlhTmYLS7e9lr7PxbiwNGgoDrBMDQijMTvnH4dSmAa4s6pfvgHhgTIKj6sG/uv8yWK4YHYM8K,iv:TkLgZ0AKAx7LO2Y4evfM4pHb0x9t7NzscJgRsBByUao=,tag:IwOaO4O4OhsvyFTiDHFRtg==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:y8QCPA==,iv:OXTbPiY2N8NH403KpMRuE231wt4N7KUDJS9yS9gA8YU=,tag:wP15tDvfyta7Bh4kmjVa/g==,type:bool]
    username: ENC[AES256_GCM,data:XRFoYTGKJiTDb8HiriSADVxR0qOOXmgrb3hJns6f9y1vjdKp9nglCRKTONpK40UhmVkV+69eWxDHeqCyMwnqhw==,iv:8alL89kLlMeJk1ovLj0w/qQu8/hTszGxy/dPyQC4+g4=,tag:cC8YUGNmPsbjt4S22zYjRg==,type:str]
    password: ENC[AES256_GCM,data:TNpUiaBLaEwAYrM6XiRBAICD60sTNjdx7N9JxggxJlYKC+J7AwnWq1eHvVuv43RvZbJtpWXhQtU0sFimUMtOaA==,iv:agdPlRT58SBuhEp0G8WZaQpj9XqSzh9xmUpRRk2gnHA=,tag:cmVNGcfcn3lUSYf5ttwaqQ==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:KNm2GoYLyJyCQqjGAMOdoKHYvDHsT9JdoWEgx/dSJC5jOY73Zmr2+0bEddwy6eg6feeR7H0e8YptjyDJEetG0g==,iv:BNQxmtKSXJDSBuExox9cl0Zo2OJJyW8KBV3x854XK2Q=,tag:ViCDEmvATerjyfRWvsZ2Dg==,type:str]
  password: ENC[AES256_GCM,data:X/bIEhAmJ+UsuqIuuYOGXFe8x0YCJTBettKdXdea6RuXCBRPcMPw2N5+MsAXI3j7CSMKX4n5nvOlqJBKuhbUyw==,iv:49pOPg5MMM3hIvjXeiAhuJkA7PrSp4jfm/Zj4k20PWo=,tag:o8tU5VAM8z2jH3NAXKH9yA==,type:str]
sops:
  gcp_kms:
  - created_at: '2025-06-26T10:17:50Z'
    enc: CiUA4OM7eFs7pZ4LA1vfks6zVByRYgamKklwCW3VEATWZNN5YN5VEkkAlCBy9gLpoavDPrBJGGZGtHHMDs9QsF+sFIweXc5dOqQAt+Ad8JRKgXBOYQLENtoYOlL5einUQkOqlhwCGabnGdqQhgCz6LWZ
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-07-01T09:56:59Z'
  mac: ENC[AES256_GCM,data:026Tw0IK80KdeQLr7Z/gMH17aStUBJfA0jjmyAILzM65MiPxcgS5ezk0Pv4K+6zxdGgux0SayZrM6o/xoFTvdnf0TAdDCGNbkveBaXws3tD2I4Ns+8pqfTXa/5W4K/YdUsCCJ1zhr2gGIfXcxbfRQjMgS5K4HuP3ZpUvuRsvFBI=,iv:3I7t3ygdosInS0I94zAQ4fKXzrAR4JdWTywooM+TrAU=,tag:D9BT8QQGb7/44o5MqxKK6g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
