nfs:
  pv:
    serverIP: 10.100.35.81

binderhub-service:
  config:
    BinderHub:
      image_prefix: quay.io/imagebuilding-non-gcp-hubs/neurohackademy-staging-

jupyterhub-home-nfs:
  eks:
    volumeId: vol-0d3344882a11b2b08
