grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Kw==,iv:3tlbY6qtm9Jqt/d5oIsPKtoc13e/QVUkjbsijZ1YNdE=,tag:v/Xr4fcHIemgjjjPYwvd4g==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:Hqwwra8wCXslxA==,iv:zB7wGbrmKjNuWMTYFzPM9fO4vkordTja2xyv95+sZoE=,tag:oGBlfjPtQtkXBIn7OHpyOA==,type:str]
        orgId: ENC[AES256_GCM,data:1Q==,iv:eNHrwp7nqh/Q4DDYZLAOMcPnYAxbeal79dQxazpasGk=,tag:7vg4KNWq7ASLL1F9l80jdg==,type:int]
        type: ENC[AES256_GCM,data:6Ou8fgU7wmc+Pw==,iv:QQ8JQSDhDxjIMaBJJeVXFenB+HrNO5CMzVYD/lRNPYI=,tag:HRmj/jJmswNOpFj8xBfBHA==,type:str]
        url: ENC[AES256_GCM,data:7x7UOC26HY4c7jtQahM/bqIc0jMXh/P6WvrAQEmumSA=,iv:rmNaaVl/tNwEwRE36MVMzi3a4ZRqGj2V0JXQbBZFWME=,tag:iBnn4do6gCJ5022CkDlN6A==,type:str]
        access: ENC[AES256_GCM,data:UGuLkd8=,iv:NMIU/d4oGNpwifStd0f9DMEXO+SA+T10zdxBqfV4YKA=,tag:9WVujPvSeVoERBEBAyVQ5A==,type:str]
        isDefault: ENC[AES256_GCM,data:PhlujXg=,iv:0eD8K+V4HEpNurJsu4eRLwaiX41kaIMKP5j9JoacmgM=,tag:XQ5ul3nEJ1Ft/8HWl+YJag==,type:bool]
        editable: ENC[AES256_GCM,data:u1Poidw=,iv:81sG35OZuXN1CCeCncMRPG06aveI01xC3K3HE1+/Q6M=,tag:8RBRgg+RUt6M3iF1uUFlUg==,type:bool]
        basicAuth: ENC[AES256_GCM,data:3aPDqQ==,iv:pvT7K8271OEqKDtOW+qFqi3wzYKFpk2aNw9tQ7HtBuo=,tag:ziNLvkKZDLyWVWPWDzb6hA==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:XoYZXrT0lHughUPbS18qVJEGOcWL1iP8kHnJP5RetQ4OWjaUmvvWdKfA/r1m/7pJktMqIUaRSdvTz9TrnBXTwA==,iv:7d9wHBBnShwtIdCZPUqQY/fX2bR/7XHAUJ41rAP/rfc=,tag:ryY94XuDyTzjdmFnh5l0SQ==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:nReaB3MAWJmUvkqlWdUOZ0YxiLlwrwrSmGXsy/aW4H7K3LU2spqV/+Q7oNcEMh5X9cWuTvZ/DQu3Qjkh5hcagg==,iv:VLz3HRXLZ2g0GbrkiC5aE/AxalJmvWKVnQrbXR8q5bQ=,tag:4HwHdD27QXZ+PAnWz+Ti/Q==,type:str]
      - name: ENC[AES256_GCM,data:G2DJqBYvMwnMt7WKhtUcN8DTDY1GMx4+RMUWMHseYA==,iv:pUU5XI6npz+LLSQ2aqIz2tPVKJ73qUwkUZz+HBwYGJ4=,tag:yQ3bmJCrE3s24mg0jBHzkw==,type:str]
        type: ENC[AES256_GCM,data:INtk+Goz1aRn4lLJ2Kizlven1s9NYflkv9w/+WOfNQ==,iv:TJMRTDB9WUFjxkRHHUJ6osmyimkCOGL20ql3A0AIA4A=,tag:lYSiMFmd6TqAtlBpvQEDRw==,type:str]
        isDefault: ENC[AES256_GCM,data:7siQuw0=,iv:ZjqgMxrW4YzxrT0DNIsQOm5zV+cM/q6OVj3z78MmSDI=,tag:E3J/j78R1UYpRpbMPlpNoQ==,type:bool]
        editable: ENC[AES256_GCM,data:bGFM2w==,iv:v7n/EHQ1VIIfZgejbWq7QsQhq/1KtYGutNgYy4P69XQ=,tag:mhhkFrL4ySuNbXgdfuMikg==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:3BXgwO3xpEhS8j0PEQ==,iv:xUPLyy56jePm8W+J57QDT4B9daOKOwCG/XA5a85kA7Q=,tag:Jw2q50CZe5bH4TLfyfIOeA==,type:str]
      value: ENC[AES256_GCM,data:xfFn6gIVfwXz5AiKBD5x5S8c9xQceO3vHJ4z1CwKLR0smuZeo8tkISjSpqSkDS2gVOsXD6MFBut1/0JHo2J+rCh0geJkMGVIalj/SdXzouFBkOSnKuI49bWGc4IWzTR8lXfUQcc1FE/D5IHeWhj3vRPh+k/iWL+guhd2Y5CzPYzfIMp4GVusJ/+axW4mOnXvraFWkYMojnQ7icurHsP1Ka42pn4FfEjae0DI/fIPGt5/1w==,iv:0wlph3c2RLhvTbFWyvMf2kJ+Cm0PqS3ywo03zAF4wvI=,tag:pVEd1wLHjKfMWMh2qPIGQQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:YU9s77YjFEcs0eOEXcSSRcRHHjncs74/+2cTxVaZrDyTfVjI60JcfjK9DzMTDmErrIoeXdh6LMr5C3c/gQrVXQ==,iv:4mHJ5KZHLePt0VXHRuLtHIDoaHx5ojv5bPN62gE7CzA=,tag:zx+79P4JL3WJ0VkEF2wU8g==,type:str]
        password: ENC[AES256_GCM,data:E2SrBn6rFl5jm62HZvUUPjHfpaql/kux3CgBT11tWc7I7OKaMdrpQz6ROagFgMTAvi/pOo3U8ulJC0vfwbbOAQ==,iv:RaOONbC7ZZniKNT3CqxDIdSM11zel6NtlC/NctCMMNI=,tag:olc9oIPhxc8pz5U61xddOw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        KVCDzuJIVYDpLEMDrBsYDGWB9qF3mv60XcPALIjOCX5gyhox0gxaAgy6JcsTb8yb: ENC[AES256_GCM,data:zDJihWaN9cU1NdldEEugExR+e3bwaSfZYjG2WXi+AbVftBEVX314H9B3PjagsKnyvGTDT2J0AS4o1fJH,iv:oHSUiXco51oMhjO8VpK35y0r8n9PAS8IIRYhtH5lq9w=,tag:t2a25otTp9Vmex1NNg83Xw==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:591TcA==,iv:vn6WETVaJWnBoqnIfSOcUsMsmdz8lR8C2fLtJuQW/yE=,tag:RdlwSbZBBA+hTAJulawT1Q==,type:bool]
    username: ENC[AES256_GCM,data:O/WcwS+WnBJl4GJ2g8yVsLfVSWHDNPqTEyCNJDpD3PvhNwV3JXQHPMHgbWOhPInreQQC1/E+KIpi42BVjfvpIw==,iv:wv6KUDX/dnFLIU5RZuqDE5OLnJkppOoDCi+60eb0qp8=,tag:1B3fMuECAlJ5AO1QfEkTYg==,type:str]
    password: ENC[AES256_GCM,data:wwDzwXKt6v2vw8C2tVU3GWyNn2sOtJNQf5iTiboa3TOAcw8Zhd11o0TVAONN35qsHC9IpRaTryhOpoUfmbxzGA==,iv:akDAxI1N/DnH/PjY7AqRz8nn4TKsUwiA1rYt0KVUjtQ=,tag:Fm/D3EXd/qKKFFNye9eyvA==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:R7WyyXTnKT4pg0vrkN01UtPJq5AP1a/NjzAMg1OR+j0lQpb8QBUzYiocg+sN/EkeZE/xSuEgjuW0yzbbW3CQlA==,iv:I/WemVm2APm/zGJxd0bpLSiE9+DuwkUKs5nvD1XQQ9c=,tag:Aiux1TZfgLMpXXPH/zeQEg==,type:str]
  password: ENC[AES256_GCM,data:AvC1DhYOAegHk+1rCck16VQAy/Nxm2XCBO/tVe4qK4yB4qBmWi2o1DblFSqvaWCy/kJlLFQkNQgnV6T2xMCyxw==,iv:j8nV2Djt1KhETVudOPlAu5ekxyL4QU4Ma2mieFGqsxQ=,tag:wE5FzSJbPt+uknWNv6EMMw==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:22Z'
    enc: CiUA4OM7eCYZpdVdz6GMVea00ZiandcAwRQIF11p8rjPftTEbCpVEkkAmy+ekhCpshDZDa6zQPS3HiC9lE+oPpB2HgbfB4b4zWKS5uderBjcukN7BUqT98LikEZNF4Ecjt9cRZTpsOzp29uyam/JGDDQ
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:11:22Z'
  mac: ENC[AES256_GCM,data:7809+f9bQhTpvjZ9tW2qxjbDtZfgyVYOPzzIPLHAL6qxUCJ41bS6u3pmN7URT8/RhAWhNgz61KTI560MjhyKAS8KGr3PHmwXOUtDgH0q5nYg3X02ScMg0pftOoHjxOxm9y6RmyTW9n6PYBS9e9ma+TEG0eUbWjGv5kgsQCkyM6E=,iv:ECAtW1WCee51CSKaKfKbN5Fxv4H2fDL5QE06bKBckfg=,tag:HeAq7FeAyag2JxvCHm5PmQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
