prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:0+dEU7UGqBadcTRu+w==,iv:6cTlZbPwWYJ2JpMd8umuz/nLRm0Txqpl9pCzCd2rAIo=,tag:wX16CI1PjuT5tV2EqzTtRw==,type:str]
      value: ENC[AES256_GCM,data:7B4GMH4ddW+r5QbhGwYMNJMJxjWD6+uwIfRDkklvkS9hT5n9jrA7M0wdyTz3uT+mMCKgQNJ5fM9mXaojDJdCpCPyZfUjSSBw67Ya60F7KrQYbeER0HDqoVtAUPC/3CBItzPptU1mbXcIe8lja5Am7cLGLpTqSBuy+KWh+tMTz7Gc0UWv88aVfNS8y65+5UEQS0kKfWYAaOQShxbgVA1bH8lCBab2VcXMvTDM14CK3cvCow==,iv:qE2P9mb7ZnEuRdzjswjtTmpjvAQue41odaGhguaYnY8=,tag:5QqIa2IC9YRxqCaEKTxW1g==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        KVCDzuJIVYDpLEMDrBsYDGWB9qF3mv60XcPALIjOCX5gyhox0gxaAgy6JcsTb8yb: ENC[AES256_GCM,data:Y6Jaqfc04ss3Oc8+Irb/BiS2pFUXyfHpAZd5asiKNDdbS80oat47vs5rqCxGTym44oen8CtuyCMHAHBW,iv:/TuXkX+qsM2VVyJKWe+joRLlEz+bPiSREXOHFHazPnQ=,tag:elAyUe4UfkiVHn6VO5V6Cw==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:S7doCA==,iv:FjMyolLW8+SMPDNqEyFD8KTPb+Oryv/cM4PXmBZihsc=,tag:1qaS4vZlhYUSpnuheWXxuQ==,type:bool]
    username: ENC[AES256_GCM,data:b/23jczTZsCBg4MDXtYaIaNbQBt4Jx704wLSMa+pbWYUcOKYwH8RHxaw64A40E/OWKuXsxZEkch8oJWCsfFZQQ==,iv:MdBhIzerS3zt89hJeERJ5glptNDReO7zQ0NMom9voXo=,tag:rv9eL4oqSDI5MGrGyk8wgg==,type:str]
    password: ENC[AES256_GCM,data:iSOcjwLEX9DrjhhUb017+qAF2FYYQwgcFDKzoilC3vF6qyLOvQ1Tb5R9tpLTfFe3ppAxxkUsQnp/6vvzvCgJkQ==,iv:gttQnFH6prU4fqIWeeOr6m3L/s4tc7PxB5fykzCS43Y=,tag:VN0P+heAb+TofQgp2WM6ZQ==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:iQSj8GzHZH3nrgwlGEt97sNEYPnuwoNr6ji2NBymouXWuossiJ7uHEfrGVXKyRRQ34w2dEFD50WoiiGHJRp2iw==,iv:A8W+ncRbVyj7BsJZ2sqstbZqhVh52DG6z9noAaKvdCU=,tag:utvYxC6DgpOeLdP7kmcYCw==,type:str]
  password: ENC[AES256_GCM,data:UX9Vv241dSW/vqPvCl/8AQXwS5ws/6nHqsv3ayoMEuw1YRFE48UbDb1/57ZCBEUr/RQUsjeNUTN1OjaMZ5izzA==,iv:+Un7QsuskRhaYd/2EdE1/MMfINQVTJH4NcCC96UQfLk=,tag:fg6O4ODCKJnPehPKYHyy4Q==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:22:01Z'
    enc: CiUA4OM7eOy86XMFvZYgcECSdmVSl4tV4Dnm+MxwaqSRzSymBbLjEkkAmy+ekmmOwAf1B3WvKcJYhprQSbm0FZg59IhKMiElu6P8UksrRxNqs/Ixwlgmc24iRbvPk1u4V4PkPzL+8T1LSl+Vb+qfOw0j
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:22:01Z'
  mac: ENC[AES256_GCM,data:G01svrcWEuEY4DTl7yWhJ9+CcetHsmeyamPKvzAUx0OZa9hmnAZpSDsVQVoGCGaztWp7r3B8i1AX2QFlv9lLZjhOwHo1Au7a+9HPxSfRLJFTqxdsjPG/Uq6fpK1OjopNk0fvcUJds4FtIPS7HB1DoeskH3UZ6vMHmXXMqeIAeZc=,iv:OUKnjId8KfPfRwgA2gdc3gi1kkSl+NI0EIrrYCsYO2c=,tag:Ragzo4DgmkLVhPYIOlW/1A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
