prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:OdTnmMn50eMdmvOCV29MjkpfULkOoWrcA5GiY4fB9maoHIiMkWq7Ul8u7xGc6X4An2CWM5KGj0vUwAITGT57MyG1ebHbaj2Lea5V/Y/C4AWE2J/qSq+rPJWnZQzqIdxKfHGLwHEjo9nrj99iNY3hbDYN385DSxR1mBzxyDDBn1fNodaj2EPNGHVBF8BeBl3rdDM1oPrkQGaQyQI6,iv:AWyIo/TyuNadBW9D0Ks1LmnwVecdt5kezOyVLY/QqzI=,tag:DSLFJMIq/Wp8MVGqf8MrAg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:o8PtMLHXGMhwOzcLyu1i49MCN1VJkTypXgYTD6AyKLpZpC8kXtNYSqYscgdJcCvvEh0oc8y4w135WwPzOfPWZg==,iv:Y//Ro8thnafVcnRkFmF48f29dAX2yaXYgHfGoqcYJQ8=,tag:g5JPjIzvJMNmTb3xDLgrCw==,type:str]
    password: ENC[AES256_GCM,data:aR/EabP3oBTXUdinFKooK0aHxqRwMX9QKwSnxJCh+KwnO5qgJRapfx6fTDvYinEPplsKU1CTR8JP2edK5X6+2g==,iv:PmQEYWeKvlDCW7WcoKOmm4BijNIpNK2JwYi3ndrdJAI=,tag:oVbwZ3lmZxLaxx9Cwmh7Ww==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:UQ==,iv:ScYH16CGWlJ/M/ZFHjgHRgVKTt7z3kQenIMCFMBIhDk=,tag:DEZm5NVL6pyiG/5xGJwolQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:keQJA0Rpq0aVbw==,iv:iIpUUD4rWPbbd3jx9Zv5c/fXZesfK8t6Nss/FKxL0kw=,tag:C9B2HLe9ac24qJXHDB8BvQ==,type:str]
        orgId: ENC[AES256_GCM,data:RQ==,iv:XZN+bBys5e6zKQ1iZzNbW45ppuVy6rwLm05CdYsqiFE=,tag:bRXqBaz3918W7EZajdnPvg==,type:int]
        type: ENC[AES256_GCM,data:sxH1x2LzlZmt3Q==,iv:2ZKUn3c/cDkseLxvLV1jTAaU/lEIz6mdf+dJ5ddVmI8=,tag:aXXUg/8cWQpDIaRgIFMdfg==,type:str]
        url: ENC[AES256_GCM,data:5Jn8ZXGgSsqgadUlA2tgQ90/86Ahzo0Y7jjll707tRc=,iv:shr9+MoBxzka0/f+VEgkhh/9oYvzsoOQadc3TI9/egE=,tag:wT9LaBdfhMtBo9Z0Sr6roQ==,type:str]
        access: ENC[AES256_GCM,data:cBMo8kg=,iv:wqzMaGr92FE+o++At9hyhL/6k3AdHNi3Q3lrQV4F17Q=,tag:aFdshSchvSJZzWSQOYvCAA==,type:str]
        isDefault: ENC[AES256_GCM,data:S2bfIdM=,iv:W1GTASsek3zIcJ8qB+AK7snvo/IOcWerDhInK+0ZTvE=,tag:GWIKaO3B2D5zjjd4Rw0lKQ==,type:bool]
        editable: ENC[AES256_GCM,data:0NCKRnk=,iv:PHPlSHqOzLv1bsXivuvQyqMG60vIQPvzJjYrQM6A/m0=,tag:J+oquR1p31zYQLdfUUYzwA==,type:bool]
        basicAuth: ENC[AES256_GCM,data:MzJIfA==,iv:mQjqqu9lXcMLBMKLFYXKITCb0fZx5G+5iAe6AAzV6uo=,tag:w4/eqcwVEBsTnNZHcQo9pQ==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:+Fhi77ZdaXQBad1LGw74mUEJmkzob1O4aoC7rTyj8wnkG8qmz6/M9LSP74mPMyU/OcUi/ke0jYPay/7oHj0rSA==,iv:YQKy/cfgWXG5cWJ5b/k2WJv4P1FLl3dUDXyz8jra3iY=,tag:A/JbWUDCROGWaYTTKlfQKw==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:oX3alaObUi6wlVJi1YhRCWVyvsLApOJMXSrYDqqBAjatMxiiPTvHGBRpQyhEArcd/h5i8I524jCPaPA6WAVBhA==,iv:jSll82lJfIrhbv4Ju8yDiycG6zkaPxqKGySbypSVp2E=,tag:MvQYFi26J94hTkjuJfadlQ==,type:str]
      - name: ENC[AES256_GCM,data:UfwYqATkAXbdn/c5IuK4cHFLrXR+RRqiRqMyAnWvNA==,iv:/LBXHBOtKx0x5u7c2Mr+AVoOK2VkWdIrHqEIJ8bS5cw=,tag:xP2W6DQvvG5iCBGIzOxBFQ==,type:str]
        type: ENC[AES256_GCM,data:560xVJ297y2I9n7Mq+0qqqDcNAJWYZ75PUAzdOoxkQ==,iv:LAMKjiesDvlD3A0uQa/vpWn3kZL152QxQ0e6zoPmedo=,tag:JooHED9B0EZGGOP+Bl2w1Q==,type:str]
        isDefault: ENC[AES256_GCM,data:sbBXGu0=,iv:/1UnbFOdqdAOE1zk2beKVKSfUDfKgyOXAUIO/7IGbew=,tag:L87Rf7/vxbQQGgVaehBh1g==,type:bool]
        editable: ENC[AES256_GCM,data:H9Xxcg==,iv:gVkXAkSVMufZWtl9WMuGh4y+ZLFssVy8XxAByFBKofE=,tag:Jr7Uf79b/hd0oVcbGkVhEg==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:fG0KW1tSuMRl/1KD6g==,iv:ojYAM3/xKfjq3CKuOj7K5LD8CGXzrdr1eL8OVu+rir8=,tag:DMwhCDRNxvxgEywr77hXzw==,type:str]
      value: ENC[AES256_GCM,data:McB1/JEuPePy01iCKDySw5zR/UM54E6+HXanguVhqFknFkdUjWeEHqh5rE6zO7TXYumYXSr0exYmAGb0gfNxioEkRea47q1+2sFVCI5d45bx0XY3gQunI6zmzMEJD26lPebzXHEv7vNBaKDarZSABL4dtfkxK8uBxrA7trh08rmtl1feaiSc66yIqpcrA9zRwQidY4yWj+hUZpIrGTLi8klld4H6RDvwFeiTNvUk4Q9v8Q==,iv:SDTVCSMrlLIhPL9dMCvwmAQo1xHUV/ZdXnH6NQy6zCM=,tag:zwnvG3JOStqRhX90NSmacA==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:7Bq5+gwK6w34HVIPJOtAEQHRFmz3NTsUy5DluuVC0xkzCZOtPnKJb5SEkzPDSpQ/EPxDFJnuDVDkp0oLqBwKuQ==,iv:dme/nIgdpttAYXK2bQnn4noRjwzBPAbumAzrDbR4sF0=,tag:wR361cdJqa5x+1m8AHi2cw==,type:str]
        password: ENC[AES256_GCM,data:XnXyANbYgrOjbRDZ0QuWzC1MPYEw2jZxozKHKxGppNME3+ajc0G1/a4rYVzCyqTeJtQGSiaaMl3vC7agowX6Dw==,iv:iWd3iNxuu0UdNhesAoQh43IO34FBRYrycfsx4wconxo=,tag:CmGjyjmGDdxnjCWJbhucmw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        KVCDzuJIVYDpLEMDrBsYDGWB9qF3mv60XcPALIjOCX5gyhox0gxaAgy6JcsTb8yb: ENC[AES256_GCM,data:eq42jNvg/ZZpx9zsU7+SerWhG0YL49CXwyPbYBqx/3IJdGkaUnpBmX1IfEul/67TYV3ZRVZFLTFN47lO,iv:Mvu5ZNz+TOkjY0miJ5ufr2HLIo7aje+3EvvzH1YatOo=,tag:tQpanY/ejy3jRM677D7r/g==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:ENsXvg==,iv:JaG+5lIXcpfX8O1xz97TF8+1C2XZzXWYtn1eFB5PYYo=,tag:CbnyfAu2jbhFSXfb7D8ihg==,type:bool]
    username: ENC[AES256_GCM,data:zrizdyjdtW+e+AFDUYeb06Ph47Z+Tpe0NG66/muS99BaCag2bTTNILo3xy+iXBmv7St3avDU94gslQvlUTjOUA==,iv:bSssKXSUCG/hwbwEgsRXUZ1v/EMfadEDXYAZzyKpQRg=,tag:+ONkuv2uSihTw45lhWw1+w==,type:str]
    password: ENC[AES256_GCM,data:0Yb2o5gMiF1Fvq/vGCtdgC2PHD+RIGhBdn44qWF0CyfODV3sdBq2wTI8AU8VfZVBpt2boChypdlrcROb9lL/IA==,iv:vmOwJiMSyLH+GTjv8WjEZGzOrCcZaNVwZ5OqW2k9AOw=,tag:R9TKe1IwJEUASxrTPo3QCg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:44Z'
    enc: CiUA4OM7eCoDdpNiXAu+vHGxsDnWsO6WzKKyaranq6LMuxjmECwsEkkAPHlbmej3IwG5r8Y0HJfCtaIcwsco47qFrxKSmrSJ32MpTl5/GGz7DuFNh4IlZnsjyNaTLXYQPCMbQyYt2eKvBUnNtplCSnW/
  lastmodified: '2026-05-01T14:40:44Z'
  mac: ENC[AES256_GCM,data:NsaqqRXswEWpI44aCP/MY16jBnrtsVY06nCZKDCI0rIeFFOU0L2qw11MpCbi86R5k+e8J8uzh9vg+2hApfXJ/RLPCAuNz/E67b1VGhNsSnZUscLrI8dvQeuGNBQxnDplwGUB/G6IGt6GeGQImHnBH6rGJhBFzPAKxK2Z2QMl31k=,iv:MjFQaVfq7LH7mRKhP2HpnV1g+AU00L0/iKbGdlR8Kew=,tag:CmvLOd6Q5q6ecnwZn7+3Pg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
