basehub:
  jupyterhub:
    singleuser:
      extraEnv:
        SCRATCH_BUCKET: gs://leap-scratch-staging/$(JUPYTERHUB_USER)
        PERSISTENT_BUCKET: gs://leap-persistent-staging/$(JUPYTERHUB_USER)
        PANGEO_SCRATCH: gs://leap-scratch-staging/$(JUPYTERHUB_USER)
        # SOme change
  jupyterhub-home-nfs:
    gke:
      volumeId: projects/leap-pangeo/zones/us-central1-c/disks/hub-nfs-homedirs-staging

