nfs:
  enabled: true
  pv:
    enabled: true
    # from https://docs.aws.amazon.com/efs/latest/ug/mounting-fs-nfs-mount-settings.html

dask-gateway:
  enabled: true
  gateway:
    auth:
      type: jupyterhub
      jupyterhub:
        jupyterhubServiceName: dask-gateway

jupyterhub:
  custom:
    2i2c:
      add_staff_user_ids_to_admin_users: true
      add_staff_user_ids_of_type: github
    daskhubSetup:
      enabled: true
    homepage:
      templateVars:
        org:
          name: NOAA Fisheries Openscapes
          logo_url: https://raw.githubusercontent.com/nmfs-openscapes/nmfs-openscapes.github.io/main/images/logo-transparent-crop.png
          url: https://nmfs-openscapes.github.io/
        designed_by:
          name: 2i2c
          url: https://2i2c.org
        operated_by:
          name: 2i2c
          url: https://2i2c.org
        funded_by:
          name: NOAA Fisheries
          url: https://www.fisheries.noaa.gov
    singleuserAdmin:
      extraVolumeMounts:
        01-allusers-volumemount:
          name: home
          mountPath: /home/jovyan/allusers
          readOnly: false
        02-allusers-rstudio-volumemount:
          name: home
          mountPath: /home/rstudio/allusers
          readOnly: false
  singleuser:
    cloudMetadata:
      blockWithIptables: false
    defaultUrl: /lab
    extraEnv:
      GH_SCOPED_CREDS_CLIENT_ID: Iv23lio8dJq5euL8Y2kF
      GH_SCOPED_CREDS_APP_URL: https://github.com/apps/nmfs-openscapes-github-push-access
  hub:
    allowNamedServers: true
    loadRoles:
      server:
        scopes:
        - self
        - access:services!service=dask-gateway
      user:
        scopes:
        - self
        - access:services!service=dask-gateway
    config:
      Authenticator:
        admin_users:
        - ateucher   # Andy Teucher
        - jules32   # Julia Stewart Lowndes
        - eeholmes   # Eli Holmes
  scheduling:
    userScheduler:
      enabled: true

binderhub-service:
  enabled: true
  networkPolicy:
    enabled: true
  buildPodsRegistryCredentials:
    server: https://quay.io
    username: imagebuilding-non-gcp-hubs+image_builder
