jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:jSYPHNfO4E3S9ZIyfzO3+F2tTVnNGkJLG7roFJ73R9DZ1x8XmSOyA69DDzZC532u8k1s/X93v7VbmOwKXw==,iv:9yjcmNBnd5jICiAU1iRqvBIm+ecEkqYIMDJlw1LKWcY=,tag:kxojXN++TpKQPupOtozRjw==,type:str]
jupyterhub:
  hub:
    config:
      SharedPasswordAuthenticator:
        user_password: ENC[AES256_GCM,data:Kn39NnY=,iv:WAK3LkKQ4gBDxIIxN573PaAOywqaVXx8rPtcm9p0m38=,tag:pZeCkmYPfFxidF4QiYT7wg==,type:str]
        admin_password: ENC[AES256_GCM,data:wny6FClnUEKvyws7ryQYBbn8gukUGX2365Yps9MJGoI=,iv:wiS7aHusbxbslqqbBcO/4leZjKIEZa4nuYyTYVgAqqQ=,tag:keb7nZweG0zIDOdUDnvKcQ==,type:str]
sops:
  gcp_kms:
  - created_at: '2025-01-09T15:19:55Z'
    enc: CiUA4OM7eGez8KDuQZXma3aE2ZS9b3HenoeE9zJDAt9k+DMfqFVMEkkAnGhyNvSoFbF+zxcX/4id6Slvrld7haauv8LWoKhnKNroAKcT7U9aEqy80YJrXAMKJeuaWBgcTZUtpulxNqhb5FltsbNX8eY1
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-08-03T11:18:54Z'
  mac: ENC[AES256_GCM,data:QVasMcnFrZPKElIB9xiJFwIR+YvJKD1xSz+Gfx/0FE8KzP8QOhpXxLiy4NQYrMtvgcjD9+BfHThMlAMrwRkKzUdn53VwIgn2XLUT6dNutJqPGo8UtMEiZ7Sl47hTfXqRGuZfGsMC/t0HzLyXWAEu/cy3yblC5vvlj9kEAyCcfbE=,iv:Y4qKY2Y/6Db7zgW9AFT4ojyxe8iZ7kuTACgVGUkcRGY=,tag:IITQHno/QtynKUoqQzR7Ow==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
