jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:RSQI+M1M/yjnLp7czEx8UGoPraxMnliRaqdZ/ALrSrWlQBIem+KRWyAfe4O0u9okQLWclPOI1TNsP6Z+Shfw5bWve9cJNUlEtJ+HWz2+wgT0Z1kOWPfRv6W1X1WEhVRBT1J3XzFT5OFERc9yV9Z1/KDFR1uscDrPol/u7cwioQPEz9mzpKayxvZKw1zfS1EAuw==,iv:edMLW5+rtLiy+uCZ+fnyYBxLIehQAMPqIwM4CUZkHho=,tag:Q47xJF2YshoXMPSfP99hGA==,type:str]
jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:/kx3ZC05GIXwvPngSXU5bTZlW88=,iv:SysDo0MWDX8L9nJJm9iK0bC6L3sY6rVOruhvWXxxc/U=,tag:wHnei2oDrTs4FYEfUPsrlg==,type:str]
        client_secret: ENC[AES256_GCM,data:k1/UQcpZy1bqGxNN4GCDfK2Sxi2gOWevayLgc7lVaeQxbAuXlEuBRQ==,iv:KFgWlOqHoYAcNg8CT01euin76bSFQTbE5jFt3pi/VFY=,tag:RvDWgDYxlb47Bmo6IiDJSw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2024-09-10T10:21:22Z'
    enc: CiUA4OM7eIftbT461fRG4hTcQaNbGW6CXYmRwcmigijBFNx9Qfc0EkkA5dG1Q1Xe5O/suc94v4uBQ7b+F2ZsYZiI8HuR0qpZaY1P1MRUxKQ9YmXcX5AjCg0bEJ52XWnQHq5QV5zn+RvR13sk6yzdAvO+
  lastmodified: '2026-05-07T07:59:01Z'
  mac: ENC[AES256_GCM,data:axwYkOo82Khqg/7JWPaDZt3kT9OzrIKLbgXV2eLmA2fZHo7nJPfo5yeKhZNkdIIXY7GptpnIAYmr6L7GgQY/cMkh04ixVAURsYVg+94gNModYq29+KEXKVoSwveLGdZqNRKOwGdYUAz+Hm8cf1B/qfjceZ+xbCJxIoe1KPpn1rE=,iv:w5ZgMx2cwq2dgQK8gAFBvUfJf8Qfx5lbmyNsRuWQcvw=,tag:xMRGCpzopMr/hoNTbhfq8Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
