prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:y6bQRnnSxMVXT3LanA==,iv:31k0Bfuq4MYbXrfbTa4/yr24Bw8jZQQk8CzILI6e55Q=,tag:upNXMs8MX5N15yato+7xng==,type:str]
      value: ENC[AES256_GCM,data:GPNb7JxXXvAvGFdvHBlR0slUhWe4QvFa5CxBqYIdCk2ecXawQfQBlYbUHbDS68BeyL+JNIT9u/1HJmvNpQKgKWYqKylFIudQf9DAqlyC6MBLKUqUpEIGO4vD3XRbs5g0FlpidHfpEtv56GpV/qdBGAIDr9hslG/SbYC4HxUCxHInbZOa7FpSxDTQ+iYeBmQ1KGG2Fof7rDwjuRr9IBVQYxLKLKaVR0gJjEnJG5m12Cvyww==,iv:HhVGLz5Eg1Ty57q7QHwwY8jueZPH7ozu6+57KkiBZBs=,tag:fdGCCaJBN6fjvFg7GIF47g==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        hhCMzo991IiqZmhKUwVmJHh5XKEU1hFc5HMf9JAS7Y6YZXHaNzrzxyc7gUSWWibn: ENC[AES256_GCM,data:b5NY1n1cIVtzniVodyZch7SzbC3Fe2VATD0XNjxbD+BFly4pihVMPmQXOeTfCTvd2aSQziQQp644bfUq,iv:Kdg7AFFHu+IfZwRohnK4KwSTnFEtLQDqyzw3vCoTnWA=,tag:jU/+QMT3oLPK3/aaqnEPDA==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:tr0sQA==,iv:cLzGLr28y3gvgeCSBYLKylwZVZ5L7gt0Wlq7gztI2bw=,tag:qK1reOubXgc6Eou8b4byqQ==,type:bool]
    username: ENC[AES256_GCM,data:vBFnSIBd0qUYPMxrpBBI2hQ6pp5NEqlCAQqjNL4Ta6XIemO6sLnd7+J2YG/wNn1L0Via+eeM1AVDuhmICTMulA==,iv:D89RpjjQjrLJNFNT65cdSEf10oEO5xK1ezd51iHilS8=,tag:2QT/nj9idKl1tLap/GH2bQ==,type:str]
    password: ENC[AES256_GCM,data:a+D9ba0meEj+isXcGoK0o7CA7ZmWaLTakv7CMMDiYix8x6HEklsnecVVY9oVNaSeSXB3xcN5IH6+4RpBWGfNGw==,iv:n6C2fdTBDHhrMv9TnAv73+EkPnbgZYNnYk/wIHvZi1k=,tag:9lBuvsTWGdwvMzeU3eYYsA==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:FhHCAdDMamt15KZqo3zrwgESFrvf539WEXWY/pTsSlkHpihH8r7PJ5GQP6u0wPgwHe8bvs8+b4vNNW312+ZSNg==,iv:xUfM93Rtfco+Y8SC1JR9ZT3jZkvFC7xb5SU4Q6C/d9g=,tag:XYxBLXoIx9G7XP34Ba8vnA==,type:str]
  password: ENC[AES256_GCM,data:jzQufwnOr6mz9gJijLiK7upQFF63HbFStK2T5FEVmFRM2TwtxVu7fPS95MdJj353IDXhAzqIeshtYT3sN7MGSQ==,iv:+Rj/dztUmB5T69N39vxuQhdAx/meSGALANnYcqYyFZ8=,tag:VGQJi4RR8MPFrHV3mZAK+g==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:21:35Z'
    enc: CiUA4OM7eNMjc6/DKP6B5j4UoOsk/plU8aav8LSMPrafRJDvn9NwEkkAmy+ekogp4GiXo3VMpdtBrSYg0o2Kz8oLgarxIUg5Qs0FtEBJN0khbpl5JqOLa8j+76yBdXjQoI9X7RxBVE5KEra6Xg4nQDg4
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:21:36Z'
  mac: ENC[AES256_GCM,data:Xy6/19q33pcZTwRUPymYM5ubIbprbFKS+7Uo6T744u10OJTMvdN8ls4KfHx/HU/6oFzaX8mQHX0uIKJDShrcww6XEexMwW0cvXncdsuHKH2PovaZKWaWTVBTNUCQ7aEkRBvdhEEYVQ6fqbkjg3bS1xViVCwWJQjhg4mpt/q7Wys=,iv:ibIpkMEiBDiV/eIYdKe0+stGCwfOgu9Kj3cqg12RCWo=,tag:MN7mfJrVXa70eZztb/LbHQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
