jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:DeSoRLx9SetxvAGgcR7ghusqWhvQtDJDyt49bf0nb8ufsqQUiRa6Fghn6+BlEshItaCj,iv:d5G0xA1Gx6GD2wZeRX0jQcNuCfgVEef5kPMcJGOht38=,tag:ewrHbUeF5r6vp8DL9co/8A==,type:str]
        client_secret: ENC[AES256_GCM,data:QZ3A6hminRSTeDBhpEL+8NYy6vigdAwjLd2HWpPqfoeDPYGHyb2Xp3Gc0Em4q4lFVOGv95eEgAOvPKyBYGeb40Zdg/Btf9Gzj82vDC+rGXX59H0iUOI=,iv:2JsrmfzJI+vdJeZrurnGmBxz7z1D6BRzPXWvG0DUPpc=,tag:qMsH5jhvdN5WUh8HcZABtw==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:sjK+g6OKcG8v32Hy40dKRcJezp41idjXoF6sFNfbF6oHx4CBGLnqMfNo75bCgLMq/GjRDWqDDcahXdXgz5tMC/SevUsdV/QUKyttzHgYoNoNLx33LDs=,iv:IXL/RKh6yfv61/FZFXI6NYR4DphCwgT2VIETt6sB4jU=,tag:EovlX4tes+vcjEvhc3kf7w==,type:str]
        stringData: ENC[AES256_GCM,data:pAbuVkULNlVBc7uU3vk9nMEGxRJ6BEu8uCyCihn4zQaB78WQmaE9QMOLlhNTbJieAamgE8RJSmzLixQdZoLUNoj6fXp3oG1Kmj37v1fIRkW8rbpN2X5IjSFGmbDA1/ODFBvJxVKlawb5WR99KTeFO+peu85/OLWOvS9mLG9g62YGxwI+pJywK6Mm87+TVPjFtf+dwhyEa4F+LvLI+ejhaTxavNEPtLXIGA3JOP+f+5CLmRx+zGXOwJhiv2a5WXTr7Q2Rvc/PlOhm5VRNMIjCfIoxxAG50tiafNSJsIybOhdfncYrrPV71c5927NNAzuICWhBE9VrYgtn1XhwY2hedvj+s1ihJ1Y/c5GVO2b60cPvKVe2AQ0jVWCGcVYswxDLLxyW6+PNWS3aBfoHFjBuSXHcWIzCv6m8JfhK7Q3MotpWvYEZ0WiBIUnfgTyYceL2+ZoNsqaKSRax0cfMZe0csNMInk8AnIL8gUprEEh4U2e8H1pY2HoJpK+3pmmkvjXqR9ph4ARngDNNHlJ2ANgvxajceG1l6hi4TVcnFTonBFsWgY3oo5+eHglRInDkQFd28mq1C3U1JBhb5+RBrQ7NXF9crfXmesOjnvqbvJUzKLZ7jNdVMsrOGDAxNaQgWKO2s2ht6i9q+ORuKithbA==,iv:mRVvrD4iaESKZOVh1vs7s7vcT0Gv3Z9OsXE0Y5HgUrk=,tag:8ehXLVO1MEKDSj5woyoixQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:16:23Z'
    enc: CiUA4OM7eOE8Qys3Pfj29APU0JG5WlfwF66R1MKPKYF5QRDtfHTpEkkAmy+ekhO9zlqo3aC8AdEUMpn1GkpUJk/FM+QQfPtauneohUYwrTqHlsRh5YDx0YMfLmrWCgOOZWuGcMF3n/SteEnrf3OUGhzO
  lastmodified: '2026-07-29T19:16:23Z'
  mac: ENC[AES256_GCM,data:WMjasQkqspE50MYjkli1g3nuZehfrnF5cEkY6xnufhC7/hYc4OwO5/rTdVsdRYl38RGoUWAdremuacwGr/ODwV53HqgGpXh5cNrcxnBLO5t5bU18j4d1m5dhADbMm/TyOdGgnmB9sMFB3HjY6B35A1U5TzmLNYPLp/ErPNv/q0Y=,iv:X2HvVyaPdoTxhsfNPgFo4HeIV3LcHFwJG0hzH4MTWos=,tag:Qn5xQBImgQmHf9N9kWHbsA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
