jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:jSYPHNfO4E3S9ZIyfzO3+F2tTVnNGkJLG7roFJ73R9DZ1x8XmSOyA69DDzZC532u8k1s/X93v7VbmOwKXw==,iv:9yjcmNBnd5jICiAU1iRqvBIm+ecEkqYIMDJlw1LKWcY=,tag:kxojXN++TpKQPupOtozRjw==,type:str]
jupyterhub:
  hub:
    config:
      SharedPasswordAuthenticator:
        user_password: ENC[AES256_GCM,data:ZZgkf4y+8L36,iv:ys1OmoTZcaXslE/BjIHTfm3snhDz4x36z+LNtXoymkc=,tag:J+9RbQ+HOa5pIRaJhxBjIA==,type:str]
        admin_password: ENC[AES256_GCM,data:wny6FClnUEKvyws7ryQYBbn8gukUGX2365Yps9MJGoI=,iv:wiS7aHusbxbslqqbBcO/4leZjKIEZa4nuYyTYVgAqqQ=,tag:keb7nZweG0zIDOdUDnvKcQ==,type:str]
sops:
  gcp_kms:
  - created_at: '2025-01-09T15:19:55Z'
    enc: CiUA4OM7eGez8KDuQZXma3aE2ZS9b3HenoeE9zJDAt9k+DMfqFVMEkkAnGhyNvSoFbF+zxcX/4id6Slvrld7haauv8LWoKhnKNroAKcT7U9aEqy80YJrXAMKJeuaWBgcTZUtpulxNqhb5FltsbNX8eY1
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-08-03T12:07:01Z'
  mac: ENC[AES256_GCM,data:PdCp/QFPGjtB3y7Y+J/ptyd0GjSh/E/5JjNtqkc1bmhnkcBHP9GEe2WE2HL0Kh4rc2I4tbi91R4MbQK367JnJiQgUMoPSml6BueDZ8KtmJ8Tnnl12iijF34wMcMlCRAz3qp+KKZCA68nenHUn46q7aoNU6GWI/4+5tmvNvC1gH0=,iv:a0tBMC13w6YoPJuhfc8crtT8dgiplnEYa0l5Ekggvc4=,tag:zb/XOV0z32DtQtLza/0fBQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
