jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:jSYPHNfO4E3S9ZIyfzO3+F2tTVnNGkJLG7roFJ73R9DZ1x8XmSOyA69DDzZC532u8k1s/X93v7VbmOwKXw==,iv:9yjcmNBnd5jICiAU1iRqvBIm+ecEkqYIMDJlw1LKWcY=,tag:kxojXN++TpKQPupOtozRjw==,type:str]
jupyterhub:
  hub:
    config:
      SharedPasswordAuthenticator:
        user_password: ENC[AES256_GCM,data:l1AXzU8nESs=,iv:degKfJQNihBclZUS6nwyZQtoXxTPNJwdwajI0KMDmCg=,tag:ODPsnzUH+iop1IbPHi6F9Q==,type:str]
        admin_password: ENC[AES256_GCM,data:wny6FClnUEKvyws7ryQYBbn8gukUGX2365Yps9MJGoI=,iv:wiS7aHusbxbslqqbBcO/4leZjKIEZa4nuYyTYVgAqqQ=,tag:keb7nZweG0zIDOdUDnvKcQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2025-01-09T15:19:55Z'
    enc: CiUA4OM7eGez8KDuQZXma3aE2ZS9b3HenoeE9zJDAt9k+DMfqFVMEkkAnGhyNvSoFbF+zxcX/4id6Slvrld7haauv8LWoKhnKNroAKcT7U9aEqy80YJrXAMKJeuaWBgcTZUtpulxNqhb5FltsbNX8eY1
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-04-28T19:44:09Z'
  mac: ENC[AES256_GCM,data:2eUlhcNOoOe8zLcj6T5dGfD6WwINEnOC/jDBt26c+wG+N7jBW0BZaMW5NDmiTsbQk29AuhfhxaOPqmuCU5l5Z4PnPBsdQ6rkJusjFqzZnlL5tCciQ8mAvpgBS44IvY3qJhlflDGlqvc72PyGWYsyg6T82SSOCiWpRkqbm0wmmGs=,iv:vcmTFCnoWEqIn4KXwTdC6rZ8MiTpYElWKl+BmdCvQ3o=,tag:LhbPkyuI9MnfINCOgXgN0A==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.11.0
