jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:RSQI+M1M/yjnLp7czEx8UGoPraxMnliRaqdZ/ALrSrWlQBIem+KRWyAfe4O0u9okQLWclPOI1TNsP6Z+Shfw5bWve9cJNUlEtJ+HWz2+wgT0Z1kOWPfRv6W1X1WEhVRBT1J3XzFT5OFERc9yV9Z1/KDFR1uscDrPol/u7cwioQPEz9mzpKayxvZKw1zfS1EAuw==,iv:edMLW5+rtLiy+uCZ+fnyYBxLIehQAMPqIwM4CUZkHho=,tag:Q47xJF2YshoXMPSfP99hGA==,type:str]
jupyterhub:
  singleuser:
    extraFiles:
      rstudio-license:
        mountPath: ENC[AES256_GCM,data:VJfJrOEA6cYKrhvI8fZXRccNbn8NKRxr9FxPMVBd74CV+nKLhgSli3TEo+1bKYaIoL0SLSVfMXTPp6wKdfqAG5A9,iv:RAUYDurxgxxu0SZjzlWl8b35Qxf9arqrUHITK9MzqqE=,tag:X26lvQ/vCvbTBdj457ojyw==,type:str]
        stringData: ENC[AES256_GCM,data:M1cm9pnKFuiB+qta3Np+ukD431td+Uo8tO0cAzUKFtEcWaaXopqoe7NVMJsKwiSy6OkLQ8by89Aqb0MWYXrN/FndhNuR5WahZWtW8VBSeWQZfBZGeJQifgTyDCJXJf8LgtoXJISxKWMNK46Lzf7lTwZbwwkZIX5Unt5DREt85o6siaVePRrPON15ZFrP/Meusijb779NumRS8RtPlMnLe9Fsi+nDj9YqwZ6JwM39nVWwo69LiKCI+zlnJzszar8IIBBdTNuTAmcy8N/xbabROaPxGuogpqJ5DyWa30xvz/bQVSVohrHcM8xtLYq662kA8v8zO5Uddfmbxjxp1/xFpQzVDRzytitvaICU+fPIG3DI9CdQfuB1IPSow1gax8/35aU5pcAJ4pyqgaIQPN2Zg31oqMBd6Gd6hBMvkW8g9mCZcTZkg9pNrrM1VSNx6Mh6gwTe91OycDRKRK1xyqN1rCer3cY0Oa2TxoQXFMV6L1HTUQ6R1OWUNP9o8b3obqcz0AyN9C+AnaDsSy5kIAlRgUzfhFkM5UaGT112HGYo+t0vKoYncapR5WM7UPEGd3lKiVhDLZFH37tTDKwfqdNZ+Llq16C8WTm3DtCJg4m4JZYW1pvkbcVUoRXtc/TZ1Vu4HWQX6hWozo6m2KlHeWZiR8Y0smGHk445MByXQEltigupZditK2ou4sRpaN8fyPuk2k7n4pD0NPW1dmOB+vM4xz9MKC3Z7fQj+aBeKU95ma+gUZagogifYM85H6QpqizHioaCnq01GeiwB81omBkUp+C+EFs8oPcmjzAra2lD3ZovmBksgqq78h63n7EAqEQnEBHmtHP+WYJcB+xw+SXkONRKLuBzPLR7PnEfNDLpFFlVbPjSPLVh6TyyI2hkeiGxGPcbcoHA/YFO+yHFvUhr4KpZtIV3XXkDD2lhTMmK4gq1i1r6Sk6LDBI/tQ5mJOD+0YKU/dwW97mhBwrzTJUl+glvEcbqeA/PkYVG8te1J1hFOTpr8/AkXHObZ+kKSgMYpQVEp/ARBRs=,iv:C3PkULQAezTfjVUkPHol96QVIFmbgviknQWxVMn9rzM=,tag:2z24Zq3NSRKXIF5Em6EYvA==,type:str]
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:/kx3ZC05GIXwvPngSXU5bTZlW88=,iv:SysDo0MWDX8L9nJJm9iK0bC6L3sY6rVOruhvWXxxc/U=,tag:wHnei2oDrTs4FYEfUPsrlg==,type:str]
        client_secret: ENC[AES256_GCM,data:k1/UQcpZy1bqGxNN4GCDfK2Sxi2gOWevayLgc7lVaeQxbAuXlEuBRQ==,iv:KFgWlOqHoYAcNg8CT01euin76bSFQTbE5jFt3pi/VFY=,tag:RvDWgDYxlb47Bmo6IiDJSw==,type:str]
sops:
  gcp_kms:
    - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
      created_at: "2024-09-10T10:21:22Z"
      enc: CiUA4OM7eIftbT461fRG4hTcQaNbGW6CXYmRwcmigijBFNx9Qfc0EkkA5dG1Q1Xe5O/suc94v4uBQ7b+F2ZsYZiI8HuR0qpZaY1P1MRUxKQ9YmXcX5AjCg0bEJ52XWnQHq5QV5zn+RvR13sk6yzdAvO+
  lastmodified: "2026-05-06T20:47:16Z"
  mac: ENC[AES256_GCM,data:SHMkz4U2b8AJflyu3kMBMjuJYVH/mpwSDcttygbOKTkfH6kufVfb7JF1xVKzonMOzt601RYfun3Y41UU7PQV8ju0q4HBBxyk2Iq5Eib7/CKcJv24EZ67IzTmfbZhq7609p2M/xai8A7weewqV4/5stICDeVljEQitQ6FrEENy08=,iv:fCbU7hHRgUMjyzPgEh0MQc+m/HYkMW8HIED9JzpbEc0=,tag:4vFqJ8xtxvE80e+ez7lYVw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
