grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Tw==,iv:AXshauMbcNeyrjBabfIF50Do8LLvw1ApzQCxiQzXWrI=,tag:zNrPryRHtE9wVTg6Zua1HQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:U0Vto4fXxpQphA==,iv:CvuXYmot5FJt4+TJVI/LPNMZzwUaIaHjuR8/LgK/en8=,tag:t8+Ey24IQwtAQ8Aef12S3A==,type:str]
        orgId: ENC[AES256_GCM,data:oA==,iv:/8ObCLLcX2hciDttmD+lPGmBMZF1ainm3l7JE69OTrg=,tag:T6i/JJHheVzS1B5jxSbxoA==,type:int]
        type: ENC[AES256_GCM,data:r7vW6NBlWdgG0A==,iv:Rosrs6MWOJYlc5009DhL7qJRvXlpOXomo5x0wCW9btI=,tag:uFE/Wm5SH8Tswg0DuG/15Q==,type:str]
        url: ENC[AES256_GCM,data:ziSzOU6bJe55V2YRhPTdYVNPohq0OXTdF0TRGgLlqG0=,iv:Ll6m5qAWv3YtihWvCvVtADyeFt3rY2PuFR+F/45c614=,tag:8XgnUA3IZTzRnqRHfM5mWg==,type:str]
        access: ENC[AES256_GCM,data:r3cBSyQ=,iv:5Y76hkOhiIGVcZBVmkx0S9edvmVVapwOTUDc1vxsQVo=,tag:GdEmHB1EOnKJdw8uXpRWXQ==,type:str]
        isDefault: ENC[AES256_GCM,data:j4HaDhE=,iv:xGsgbnVZ9LDUg4GIgpt8KDxGzLGmwhnM7hxjzZiGySA=,tag:e4VNMNv4lj+c5yX2UEGtuw==,type:bool]
        editable: ENC[AES256_GCM,data:U6WAlBc=,iv:kTWREVpWY+KNrnbZyUjJFajDLhNqzFiVlHTD19DwSV8=,tag:wWcySn/zCJJvhEaH3KkauQ==,type:bool]
        basicAuth: ENC[AES256_GCM,data:h3hmeA==,iv:VgAgj+MKtowzYIjZgrp822QDjF6Gv5sox3fJ80O8WsU=,tag:CwhX2ZuCqFQ8vy+GaHbhag==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:eaGMP6HaE5+mfg9/GGxr0eVmH39MAvCeAndnW40CQ2TmNAop9ScCNgXjxEXp7Xrf2jaEfR5rPTh0tn+ONuHAlg==,iv:xFAqnydOqg5UUp3Hboa++V+NE5JG11vaO+KHWYtFSKI=,tag:rAbb7B199D85P2HJ8B1k3Q==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:kakjSdrpBTSI9i85NpTYSJEYA5BzcXp0NEK+QlR8dn7TXRoSkMvM9eqxca7ap3j6aoO673oUTzAsmu+v6YpArg==,iv:wNLfsH6k2UsAfeabK5fdAmx7IeXieHWlpJbZ6CkIjag=,tag:6fTP553cx/BI8eTo7jdLhg==,type:str]
      - name: ENC[AES256_GCM,data:FLwlRLADAGpTbxe2JSIGu8qb9036DRAyEQnekGsy7g==,iv:uqW3NAYS7eG4L2brOnBZT1riLWaix3iaozfMN2yk484=,tag:CxAW9fXkkdh3aE5fIyRqtg==,type:str]
        type: ENC[AES256_GCM,data:FPSVSwXfZp+x8JkPc972b1vZk9zlMYvHO7rXaGxvBA==,iv:WmQ6oiS+yiIjnOBUkV6NYle/sj707SrZNS3N8zKkyWs=,tag:wm8RSzu/g8jB3VWaMaG3jA==,type:str]
        isDefault: ENC[AES256_GCM,data:q/31G5s=,iv:PERRHhSaBhitjJperOpv+JvU+wYDN7EHqxeZE9hJkNk=,tag:iel5Ckn8QGxsxI9r8c1yAA==,type:bool]
        editable: ENC[AES256_GCM,data:vCeh6g==,iv:5WZj7Nqm7JFwzbMtzsdNjsCFgyQXBQuJMcFu+WyFYeA=,tag:X0acMm6qKwFjMPyPLY1kXw==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:c8rIrkhX4y4AW6I6iw==,iv:fYXPeGYx0N2etMlxufUCfUUUZcGe7Rnj5JoaZe3HzIY=,tag:FkFXPB4+oQEUFujmAKnInA==,type:str]
      value: ENC[AES256_GCM,data:d9I8KQZOwxZ2G+KhvKh60ya8WVP2oV/pDxqC3lnD67Z9BJXfMPlxptnJq16LoVavtQan73myW+gyp/ZrJIulorIOEra14QWKLWx4HV58EyQytS7UKYlHcwskDLSU5xe8+dr9pGr/qyetqALs6SygWSm+4LgMZYMG9gOKElrlxJ0WaPAJsjwJ9QSOAnZRh3yLMYvSA78YzvHm2WYvjcmH2aUAK9hmxLct3xG0/6tJZg+FnQ==,iv:Ta4Hpb2qb8XYiVrJ7yYvDmXWpXWlMXGTKRzruMqJMMI=,tag:kgyYHOMVKJN2fPRFmaYivQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:tj8dRi2rn2hYFxyIScN1PIN8kl8tMZUAbdAw2HPpPwm66bLjfeJffm+koz00O8G/XnpdusUuwXsUSb9RQ3OyEg==,iv:26i3eHjS9xFWiINQTG0BDJxhohJmv094ZuNogNwzVQc=,tag:+UtXVtdzrPz1YDJ2vhR6EQ==,type:str]
        password: ENC[AES256_GCM,data:4P1mTCpvoM1w0/vHDJVScKCt8w2iHFOhYxMOT0LYqfCvxE+WGik4A4hR/GtnT/7bpNjE+TZ2Mg3g5kMeWjqRdA==,iv:qldLJ4QPYeB/rdMoFKm2HotULK5XTjfR0PKy8sWlThY=,tag:8qUFqa1jIEcmGcVTUIlOFQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        hhCMzo991IiqZmhKUwVmJHh5XKEU1hFc5HMf9JAS7Y6YZXHaNzrzxyc7gUSWWibn: ENC[AES256_GCM,data:S3i0tzIt6Vao/G6zg5LhE+b4ZF4E0/z6zB5CsmwVuCYPdG+zmncEn2B7vq0O5VywwL30eRbZxGICus/d,iv:GLgvv7bEG7Ce2P25FAAdXwgAIYLgYp8pGaWTwT28Wp0=,tag:u/9UxyvtvS8fObQ3g26Jtg==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:aefFhA==,iv:Z9UJVWjQfu7p46ariNXRPeyTZK9hlcbjMr+grxbQ058=,tag:Hbod3nEVtdu1SKyAHmgEFw==,type:bool]
    username: ENC[AES256_GCM,data:CK715uxgra8Bce1Es49GKMBonmdQSWlwUQn3prU/M9dbnjiZcoB4aMqqQ/N7fYsbaK2glXqzTyukovcPYvlZ4Q==,iv:kBH9YEZXruI4rOkFeedmdx78Mp5adjNwcwtsMI7MzNQ=,tag:Giawn/UM4LuzQUxeY/L/KQ==,type:str]
    password: ENC[AES256_GCM,data:Xp/Qxum8uHsqMmMyWtxm5dc1L0/aa+ng0ovgylUMwk5Su/3aoETuswojMBWE0LA2Sb7GFVRNzcPcCkjTbfYUmA==,iv:4ovPKl+hCeaiS6eDP2zlN4ZOcoYa/dbBQCPgGQ4Iyao=,tag:eIgmevXRPqf7QqrZUvod4A==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:pRfnrMIo75mZfxkLC+5akSBkWwiXTU3wx8JJoVW+H2fjAW81wy/W8/hj6oku3jQlAQK4jUg8VoT1NHFVRp3fQw==,iv:Ary8kG7TlVRtAGnJnmA99ZfrIhbtnhFclQrdYFHVDBs=,tag:/l/qD9E5Mlcs/Bl85VA8xA==,type:str]
  password: ENC[AES256_GCM,data:h2Ege/5GApSA/FN9kG+bOUVtkp0ItZWu4JGaaLK6J/wZ/u8hTnsM2vIG+lklpoerukq9KaJFtyCm82Fb6QudRg==,iv:a1HgKlihPX9vq/jwHlWKq7sex3elcYTNgxhEliQE+OI=,tag:TRvGyc7ejLd4+aiDTm1Tdg==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:10:56Z'
    enc: CiUA4OM7eE1iXNiz6vLauiWMiJ2BFq85TQbhyE0ti8OqP6WxlNUJEkkAmy+eknmHVGcA5kFoouo7ZOutkt2VMDPdusaMgH+VMZxtlXEeWPsoSEIBjv56Id6AoBp0N11ww5CmDg5cT7k5pTqeE3noB/ve
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:10:57Z'
  mac: ENC[AES256_GCM,data:0fQOOoShLk6uWcsXJxUsxor5jiy/simjefcHQVDzW7vcamJjYOD+BgPIv2mGQkijNdjT4HlyVqjsYJF2n5iinCKWfglfJr51axT5SsqMXKqgiQuSZjz/p0rDgmixFKr5/ZXH/S2k4Z7zdYFs0hZTR1vnYWewXd0CNhLDbPestNo=,iv:n/frzvcyDfnUxxAJvyqeGz35x30MMb30kwyyFrDMIh4=,tag:J00Wq5G35l8RxBQ1hhaoDQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
