jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:hZEWlJ7zt6b5RnXPToH982zF4Kk=,iv:Spx6AqsFhnJ/IPDcMAseEIfJtsAWukQ6KnSw/aiEWew=,tag:tEzaPY8IwTJBIyIFXk1/yQ==,type:str]
        client_secret: ENC[AES256_GCM,data:teGJBsRryZywDU9gdygxyu5OLTiAv8iIXnKL5ytvkrbM7gWGsbCnpQ==,iv:zMHJyaMricRvhozrXgJ1sAnc6S8192JXqriTRlBAUFI=,tag:GVNcSlOB3eEhypNUT1ltSw==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:TfkiAs9LESfpBPAjPhaT03CU4qvu4Bh5M737FeT6kztsF8plidZ0vZ6asXsD3YHlawnnl2r+85oFeKXLuclurDgeFE2QkBSpms3whcT8gK1mcBiwVRY=,iv:naNastL2Mv5WbszifLrJxqIcPHGxRVJFJpFnq9oNeck=,tag:lgIpjox27v7kWnsewjJfpw==,type:str]
        stringData: ENC[AES256_GCM,data:smZVE18OuqK2CG3TLUCG0GSC51bd61UZdJRfyV9yP/Xb/td1RWK2LBJ1ntKBQ/OkML8d+YUYgNo4eh8ay/05Nr/12xKSO3k5hi7Ogn6js2RQ1kKG+dncgY+idFkeVkJX6yJSYfsxKYmoc3ajIUp8ZlI8ktG8MRpXG2HZkHHXTxHaQZmL8zHHsrplZpEOMKZ7sstUCkS+VcMZWe9bfMFTO7Y0Ry9oCcwEU0S28zfIm3pOXF9KGXoEdUEetG7jfIt3gfIXdnHpRTsEXdT/eqbDQE6yFMJlbjQPwVMzQp7ugFhETlmwFvi4HIEuW0AaML8BjT/bXwRImKacW/3kGEPzqNzQhd8X7mpTZPsf/CB4m+uoYJ3qHGFCTCVClFuRHsk/a7oFBHpr0aHGciYrLhaLu6QI43dFHpmB+YrO2dLOycwLEveU4rlWqxmBaDD+gJTDOtCGudwLeVsbm/ck3X6ernINDFL0//zDFyAqMGdMAKFM2xvrb6ZaIgo9unB3rUhPbGBuKfiU6hUryYGoc5D0IDSKfJ+G2weQ18bzGDYKNcEcGRIKurF3HoCHaO9VUKWncyC7W8eg4mqO40p/hwIYo3LZIlWQV1lmAMHteAVYJdwy0WmP/oNB8Y82PrAZK1HgsMgYxYOMDiQmRnXujA==,iv:H0Q5hP3fPeoewWqGXzKKL7gGt+SdDTseY/x1M3+OEdw=,tag:IV2Jkjg++g894SOS5Ye4Zw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:16:17Z'
    enc: CiUA4OM7eDXkmsGgAaJVHmUrE6Owu2mm72xrRCfdO3qa3Eq0uZaBEkkAmy+ekgMWXP2H1CXRfnKQN1R4mYWWF9prZkQGvXpl7IvA4DiZmjXGttPI5E464NMhGubDW1UZXhVozs1sgbfO4mX241lV/M0F
  lastmodified: '2026-07-29T19:16:17Z'
  mac: ENC[AES256_GCM,data:z61qQ0uA7XttOPqTJqFgCACMWDy/KLE0l7YnefHqlPfINArRkqHXSg3JDGWBi1Z/DeCLqw+tu6GomVVw9jDBZqHswHsJfacupbMOot8sCxtNFL2oKiOKuw/Ei3B3wMDY2fx6uFoaAM1zzigsvgherwaJEViWgRXZ3B5qepuD264=,iv:Z+kYIIlXcDSSvxYEo9K9vfdEdqhBY9We/D/pkRb3FPQ=,tag:E2/mw8hiCsHwRo+Oc8L+FQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
