nfs:
  dirsizeReporter:
    enabled: false
  pv:
    serverIP: 10.100.33.250
    shareNameOverride: prod
jupyterhub-home-nfs:
  enabled: false

jupyterhub:
  custom:
    2i2c:
      add_staff_user_ids_of_type: google
    singleuserAdmin:
      extraVolumeMounts:
  singleuser:
    initContainers: []
    storage:
      type: none
      extraVolumes:
        1-shared-dir-volume:
          name: shared-dir-pv
          persistentVolumeClaim:
            claimName: home-nfs
      extraVolumeMounts:
        # Disable default mounts
        002-shared-volumemount:
        003-rstudio-volumemount:
        004-rstudio-shared-volumemount:
        # Enable shared readonly mount
        1-shared-readonly-volumemount:
          name: shared-dir-pv
          mountPath: /home/jovyan/shared-readonly
          subPath: _shared
          readOnly: true
    extraEnv:
      SCRATCH_BUCKET: s3://nmfs-openscapes-scratch-noaa-only/$(JUPYTERHUB_USER)
      GH_SCOPED_CREDS_CLIENT_ID: Iv23lie5oLneHExwicr2
      GH_SCOPED_CREDS_APP_URL: https://github.com/apps/nmfs-openscapes-noaa-push-access

  hub:
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        allowed_idps:
          http://google.com/accounts/o8/id:
            username_derivation:
              username_claim: email
            allowed_domains:
            - noaa.gov
            - 2i2c.org
      Authenticator:
        admin_users:
        - eli.holmes@noaa.gov

binderhub-service:
  config:
    BinderHub:
      image_prefix: quay.io/imagebuilding-non-gcp-hubs/nmfs-openscapes-noaa-only-
