jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:T/vVhAww0g2iBgmyp0mYn2ZNNeA=,iv:s1he6dLRPq+AdT0xZDGkAQkw+tN6jEet0Tvp2ck7ndI=,tag:eFwBfLL6wF/Rlz/61aTCFA==,type:str]
        client_secret: ENC[AES256_GCM,data:xhkPCEhlcmS5lHR/71mHlNZGqff/1NCryV/H2nbhERhoSft0r4nidA==,iv:TsBJvENV1YrFnAkhdGKMQkDOFheC8Q51hB8p9mSQddU=,tag:dWrbvLtSeOdKPXTpt1etBQ==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:RP0i7CrqHe855H0wyQvJ7Y+1x78eCLKNsDtlIV8jGXyQnL4nXBqRtmgiu0o0oYPtzAUc4VMIGFxcO+5V0ZtABmvLTbSyr5QO03FmPUt1UfzxYJJctAc=,iv:y7P8FzLRqyqk2VeZjEAkvkg953AlbIZEpnatxxQ04gA=,tag:ioEgWMZuxpmm8EylQ8JT8A==,type:str]
        stringData: ENC[AES256_GCM,data:3gPkb7wzcew6tpppJV3A5/Ylb7lSuuGuhXcekivCbet1jGOlYFc8/UNt+tb1tG1ZExc83+9FgtucGNVLPybI/FdU3xyapHoQRBA8bslhciajapA7rQartQPhPh34FAnigbztY0iTt8h1V3d4oA1Xqpry6Cq7lL17BOP5UTcPrQ+TwvpAZJC5j1IAgSLbJIB7rnj86eAyt7dON6RE75uyVTI4ENch4Jl03Oy7XcSb3saCSg5jbhfsh0EiJD9TvglO83x08syLmD+ma2CfqVS73Y4fAC04/F1OAE9FKRZxhhKMbB+Wq5QrikpyyVHK+whbsoKTOdCcTCbr9zNft4Ld0AWVanZ8aH7/uphcdodp+PhQIuBU84prlMIahVDhqkYEBe+LhCVOls0hJ2b6y+p2ZX8TkW0T2Row4Rbb4w9peq2TgEOTiCIUog7Xr+5Mjt77o67YhYyZ2xyqCAqnj+bsvgruvoToossC57vChyGwvSBAUft78ZkFyfQqamhwFY/Bv3kVVcIViq6g7UauyQDCn2EYvwh2X6lceuBIRoeoBhfeAIgSwn5grBvn5kyPkxoX9EyPNWgPLPRCkExFs5RlZMvvmkRtjXMvz0O0chK7B/1yRiNH1cPmqhk0bY7Elyk0Uay65nRIDxhnO498CQ==,iv:rz+vN7D3IiXec3pPmBp7kPr93+tQlWmoq0IT7IwYs+I=,tag:CXTlbdrBBeMTJZNTKTr1/A==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:17:14Z'
    enc: CiUA4OM7eM28xzhMNHzp0cALPW1O0XD8Uxvl+SSDgYUZOZjODB0+EkkAmy+eksyjlMCfd9UTZfRij0xdRuHGTCbx6rElvtiaJ+HeYsZH7bT5oWZrhdtweWTFcHMIC+znJFdKI7HVGY957+Wbz5Sfdzqq
  lastmodified: '2026-07-29T19:17:14Z'
  mac: ENC[AES256_GCM,data:GxYsQg3d9+izWz4nnKke7+FlGIigsYbDB0ryHwFsXjpPI9DLM4Upn8zBwuEpxwW+IYY53A05Tn8QzZUF7CircOlHDzTmBRRmoNDGBSSGVRMXv0yJDHeW77k+hUM1LSesowMQYRdE/ih3MI6Oi28wzfzJGCtXKRshiQUAjzLWNVo=,iv:wm5NJL4Ahr6+t87zXi+KfSHFkl2UrsgJeod/A3C3als=,tag:mAX8uNyU76AA/RJ9PyXn4g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
