prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:qmqeoHT9nssFD+zyPg==,iv:zfDk+1o8GKWMscjGzM6HaUKIuCE+ThinxdFXLniZ/fU=,tag:+QzCWzjNDzH/6TzEDfEFvw==,type:str]
      value: ENC[AES256_GCM,data:fExN+dk7Ok0mXOr5mjlbALXsn3B8FbgN4BBzKjAlhhjrtco5IvhemRc2jiKBnD1F6owmz0MiFyXYUK4KwADdIPbgmkP4N7CuDvDGMzTNPuoyX2JRzHfrOFhVmOI9GnEm+lYDCMB/0R4bEAsobEBNa2jm954UyKMHE8AqK8M+xnvLaUdlpEDxA/VyIOO3Zotpj4Wkx0LfI/6cjPNr2eacjdfyVDKIFPZ21/uAIadhMrqMtA==,iv:QuZduWT74C3zTd/aVze//eLFS577XZWdvZHY6ufBVJo=,tag:usqDYFzI/IUy02Blbs6ucA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        qJwWPUjVMFJUjLdS4lWosJqfwrdLHM4q1V25iearHux6A2lQztgwA553oE7KpmBU: ENC[AES256_GCM,data:I6xmhVGy+sf1FjZloUEcOTNHt111SmZmW5pIb/mlVTgXDcef53JzFyqNYl5r72YT/qcs5mRrymC6hxIb,iv:RbiD0mPJq1Xug9yrXh0W0SqQ06o5ja3sh8VhJVmDWlA=,tag:P46Z3+P8ExziPMvdbC1ZyQ==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:sF3yRw==,iv:rPVcK0BL7/rKBOakhcqNQoaZJWATeg8kux01Qtuu5Xo=,tag:SwZI/EPeQEzg37mmXo48rQ==,type:bool]
    username: ENC[AES256_GCM,data:zfA0uLxVEnDh55iUW2UQy+FWYodwMaWdZyTnFXR0gjMJ0zPP5PeJfpax3hfXbbTpESuVVT+T27Zoqnaigo/fSw==,iv:FpYohEk5FtMLaSyeVzIuonZkB7qfv2EPzvgt9Uf/6Zc=,tag:hOPcenDLnKfxRujO5k+JAQ==,type:str]
    password: ENC[AES256_GCM,data:4hqPymTrmnXgMv4aqcFCoKZwTa5QMPPft5h4CR1nTB+KffRWFH935hXt2gWPdERg3LTIAJhlfooFgP1pn6TReQ==,iv:qSPgdE5BsYA41fJB0R2ysjimrpWgXDkXiYXGZaVAbCk=,tag:caf6wiWVzjGSjmPEN8bL0A==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:27IqxojQtvenRnR8iAs88pJSxT5/AP5JNV1lcW3fKpoPxJEEdhHB9bHV9cMnd/58hIbW4PX2YihVnSEEdaHdjA==,iv:Kq9RJeB0KfSezz1acv1l45aw0GHaVd/841RSowYXn0Y=,tag:diuZqkXtT69VDhhe+KnRcg==,type:str]
  password: ENC[AES256_GCM,data:85vUJztILb47XVjEfanWUhM2TgklTFDc58+M/nCjLNgbKq+DTUFEI95p4foKVJkrOa0ZAJmq1H6Tu1prWTZ8mw==,iv:2pZ8x3f/ZGCOlLzk4d1mOeCu72McV7wQyxmhbxwekiI=,tag:9SeJNqUPOA4YAmTOwNj/Kg==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-07-03T14:10:24Z'
    enc: CiUA4OM7eIPcx8eS0jHp6WDr2GKrbVarXsLLEQ4iYPrxFjFTdHSxEkkAmy+ekqMLTbYrlmvFyGZxyIOKbsfL2bLIgjKKrEhUVWuUt/1bPRpz+2jXHZLoRq7Z//eiDhYIoC4IYJDMmraXvRVLKZflwwW8
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-07-03T16:27:23Z'
  mac: ENC[AES256_GCM,data:vRs+WNWlybeEemG3AygpD70RboJolXM8bST/FzQVCNckVW5GuoMhra76VOSNKMplWOPH0ZObTMNozw8E9bzeBi3EYCC8OjTpqTriCKPyQp37IN4jNY8ysCcxOZYldpRaWheD/RlFDgaH4SF3fHEneebKyYTheVyy9sxCTpZBnmQ=,iv:V8yGCGhu+cqGXuie4vByh9CQ+8G3nQep9FkeO8RlFg0=,tag:2rqx7oMbhmz2fuRKDCYn5Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
