jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:aGFtEEgyoH+TmvUFCBs/tE8/7Ek=,iv:OKlDIzjvwJP3Whq3U0OjEJslN4RsUYnKD+kur/KfWSo=,tag:aLGIkPvLmu1nd1UkPjBn6w==,type:str]
        client_secret: ENC[AES256_GCM,data:r/rjbN9TNXHCLusJUtx2ZF+sL3OdtMIHwrZpUSFahOtmbPXw5VQH+w==,iv:dV/u5zvjxhNrrpvduek128elLKAmg3wVdnhFlrS6hgs=,tag:twuIqz5uY8p/JGD34jIqiA==,type:str]
sops:
  gcp_kms:
  - created_at: '2025-04-10T10:05:47Z'
    enc: CiUA4OM7eIq43NZoZ/AZorNtT2E0h3QN0ksVr6VL9bNsBX1IKDGHEkkAWOWv8K2rfPsIoql/u3CmSCwjz2a8YL+o8XecDdwsKbrxVYqVc5WzZXZ9CR3X2QqapdP27AipGtlQjgl9n/2t9INS3AKSIOOG
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-07-03T20:12:13Z'
  mac: ENC[AES256_GCM,data:FLq/FQU7pBLnZ4BgcyHfYdTU61D2125oIohSUq5hlxAHdt9ssWQV66rtEmaLVY/3iGkSbMonoX7IrfGHEXph1ezObo6/ZOeTSM2PviXT9jFzGk1iWCLBEZ5erZGoilO65gnezaW8HnUN+EXrXyEPL8bTVwlq7ZSXkwtLxjedI3I=,iv:1G7W1YTyQnOCGNOLOgNEGnR4HztFdKe32UAqvsmrmAQ=,tag:cAIBdZxKJbPsnPUnKG8vEg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
