jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:IjLz7xFZYtFVwMPl2o90x0Sf3XI=,iv:K3GunOh+INF60g0YcBQMnqIJRyPohVl4bEQntNWdMgM=,tag:hw21kRuAQfwr36Sly/cX1A==,type:str]
        client_secret: ENC[AES256_GCM,data:OVSGb7uzUKQvlBAjVn8KENCCHF2Mj74mnpCqPe3Hj/0Q0syHAZyl0w==,iv:O38WdMW4VkEKAICfypeSEbHdG2fpZFNPj/yoQan8lXg=,tag:9qqYmtzz7thJaZgrFi46oQ==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:Nz3WPTGZfeVDHTPxDKPVeQysfzVp+e6T2NcRGYl++SeAbNvYiNndM//QljbQyj03+a52/oeYkLazVhp/ZvGb4Pz7X95j0tqgJ9hCeXvksgcSwH/3xBw=,iv:k2vvw2cueiTkcdTB+k2CGAH4/URUmuxFB16B3qEiQH4=,tag:hsSmD1DrseG4F3KFbblvwg==,type:str]
        stringData: ENC[AES256_GCM,data:jNJQrZk9KQtHFURucjHdZ01wO4EAv/qUFYcJPqCDYb2hjzTqyV6GshEf2xApoZwOM3x+RwwBz3wWovKF+zhs8SGihawbsRX+xutC4RGMgMmomgdx7i4cm18tQKYkB3Gte5pDDl5/cNrqqvUI1+e6IW0HQN7JzpsS9+G/ej42SJj9pHtb9Q/ZOTztKIQ5dhLFjJSixOrguSR0eGlsU6MBWgEghq9ewVFXCOy9fayd7xyo2oJrbdQWOeNb1+1Jg9S8S3KCzxm94/neG5xSQhF/2SGRaMnWSaHfwH5FfPWEekowOon2IMLDuvesDoO9Z4e77CV0VxBx1n15sExhoQu/PCGwnemQ1lZCj81Yrl++IRV85LH2lCclMhLHXAiq50sf/s0p8Nfppl4WyyOOX9ZebqrDRdp32SJgQiIhDEZg4qbk3n0chWA0rTkLywBQ4/pg2lAmR0QwuRs+X604n5SlY/Q6KtqqP4NiO37GWxtgJmlqOj1O4bYrqE8L9hCOQJE9gXz/sdwVdQ+07Q+4GKfoKSxu+490MqblSmNSaigeaYBBTtc8ZWCbq6MSxJYh/Jgzvyx361UA6Zay/aSjVQ5bQ4a+kIlskXDOS1wqpzg/XaCMGW6KjANjcRiq1BWOwu0uk931pL8r5JvRZ4nevg==,iv:wQZhz/oz7kAF9wkDXwSV08Ec5aGCUvmAu2PiZuM2pK8=,tag:DE1p9+5TeCgHirG8AdjWeQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:17:16Z'
    enc: CiUA4OM7eEECyz8TpQ1OjEekaUBXeFJm60sd6VWbFoLzBfM9/HhUEkkAmy+ekmiE4OJ/aDu3KeloF6avvcUsIcJAeezCFbHMgg3iRM+pH3BMFrTcXBz21YL0G8PxUKaeeEy+3Xfwd+yA1IYgK5xyN4/6
  lastmodified: '2026-07-29T19:17:16Z'
  mac: ENC[AES256_GCM,data:uRft7m2LtPoubjlIugmt+G18CiWoak7Pzy9TEcHsG0/53GYdJyqru8yz5TTBdgt7BaYODqg/GlkRWJpz8KRAigTwj2dRHMfScNrzElLEkw6EjU1hFf1DVGM8RKRcjFbrAARUwHE/TxgNpajhoh7g61LnNLsBFy4VqQAfvkz1Tfk=,iv:GydQrBb8y/TxOc0lIsz2oNs4w8sbuL2tiptaR6aZWj4=,tag:5KiY7HhY3vvt0TSFFNOMXA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
