prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:nA1prv/HmUkCaPoAWr4GMtdg3XzFY+nVZCwC0/orSW3Fq/f3kwMZKDXCvYEjPao80BBP8p5Zrl8c8s/HK4chzzgRPMgyMKajo+TsEt2ZKZIG6A0ETnqx7u0pxITM8EhG3LL6tub7OXWR3uYXQnWmt4yidhsjhll6Osejco0BRMTEeIFW3Ru14ttk7mpXWwDJ3D6v00LxXQ13FWj2,iv:2YSsXrraT+l5xZ1sPYf9W+D1d1iwQ/ZmKsMMhQmYlPo=,tag:DHA4k9JYlBjCF4hPql1Kzw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:vzZXBrV4VhwamEqXliSGm3Bs/nZVQPI8yjT0GmZndEuZN21BsNuUA3Vbo2TwwsdIaDZ/vMumA4WzQklqYJNNfQ==,iv:BaI4sYjy4AR8gUgYy+VzVtX90M5OXjYtp13e5bmAhVc=,tag:4WHh8dtLTYu6smgj/G+gUg==,type:str]
    password: ENC[AES256_GCM,data:WsK0ggrC/LbLA9S6IvMtjwE0gQFYMXhsfkSVmvLoAuXkEejdjf/BNmNIxr20LcTEXz0vbgCnyGJ9BwSdY80aSQ==,iv:rsJgMA/cBd7IYWAP+7X+YO/smgc8mFbTO6u+aJwpuw8=,tag:Yg9jl692Ji1SJ5CCRedrVA==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-07-03T14:10:24Z'
    enc: CiUA4OM7eIPcx8eS0jHp6WDr2GKrbVarXsLLEQ4iYPrxFjFTdHSxEkkAmy+ekqMLTbYrlmvFyGZxyIOKbsfL2bLIgjKKrEhUVWuUt/1bPRpz+2jXHZLoRq7Z//eiDhYIoC4IYJDMmraXvRVLKZflwwW8
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-07-03T14:10:25Z'
  mac: ENC[AES256_GCM,data:l8E9XwQDxCy5Pj9T4/VWxLTJO4t97GOwMeikjkdbfESeEn8WDZznT4Gae8ZKyZAwczJotclBC+vVjIaVcwvitscoHvuVJeeVLSeoMNn5froeyMea3aEYOlrUymqVt0IfEDgVNw830PY6UyANTOu6jVcAMdzNn3tgMuBGFJmtjaw=,iv:uITA+v4GmiUgcFz+hy4EXxd9PmIg4lEYUmjfDM9HsuA=,tag:lJniB1v8Xnqsxb1u8mj3+w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
