jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:CpQB3ezo7ZIX1BBfRuUM4fGGd18=,iv:mCKU2PD+2kQLxTA7vS6o66iP1zq2xtFFny7Ep/XvJV4=,tag:nX+FS5zXn+WSCZ1sBEHKkw==,type:str]
        client_secret: ENC[AES256_GCM,data:WIHZJ/qeSp+py7B68km3uhgLPu6bXB44qP044B82r8I3np0WLQ3PXA==,iv:YmDw2NijC5DOzAFFaOU7fk4V3uR946o4oBLeSsaRzew=,tag:GrCcyvq948DBFzB9JQkT0w==,type:str]
sops:
  gcp_kms:
  - created_at: '2025-04-10T10:05:47Z'
    enc: CiUA4OM7eIq43NZoZ/AZorNtT2E0h3QN0ksVr6VL9bNsBX1IKDGHEkkAWOWv8K2rfPsIoql/u3CmSCwjz2a8YL+o8XecDdwsKbrxVYqVc5WzZXZ9CR3X2QqapdP27AipGtlQjgl9n/2t9INS3AKSIOOG
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-07-03T18:26:08Z'
  mac: ENC[AES256_GCM,data:cX2eFfGM1IfLiBvcz78tf8fS1qkCUa3O7OJsL2hYdg6GQJ0T4/S4BjR6jGBjSBW/I9bRgzAp/QoVdpDhbc/btHym2TwyTwPX7WD/vdN6jg8rqfTatJp1Czzd9AfsRG0telbTQEoMum6R4/vYfgCkhJbhhOK4FGDveiAxnrK7jMU=,iv:o5Mlutb+Vgm9QQWvGa7TQLU7ouVBoyzfIxLqc5ZEjso=,tag:lERD+/D8CWUyyWYFso1lOg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
