jupyterhub:
  hub:
    image:
      name: quay.io/2i2c/pilot-hub-authz-helpers
      tag: 0.0.1-0.dev.git.16863.ha51c52cdd
    extraConfig:
      001-canvas-auth: |
        from jupyterhub_oauthenticator_authz_helpers.canvas import get_user_groups, get_course_groups, build_auth_urls
        canvas_url = "https://utoronto.instructure.com"

        async def auth_state_hook(authenticator, auth_state):
          if auth_state is None:
            return None

          access_token = auth_state["access_token"]

          auth_state[authenticator.auth_state_groups_key] = [
            *await get_course_groups(canvas_url, access_token, "course_code"),
            *await get_user_groups(canvas_url, access_token),
          ]
          try:
            groups = auth_state[authenticator.auth_state_groups_key]
            login_id = auth_state['login_id']
            with open("/srv/jupyterhub/scopes.txt", "a") as f:
              line = f"{login_id}: {groups}"
              f.write(line)
          
          except:
            print("Error while logging groups")

          return auth_state

        cfg = c.GenericOAuthenticator
        cfg.modify_auth_state_hook = auth_state_hook

        cfg.authorize_url, cfg.token_url, cfg.userdata_url = build_auth_urls(canvas_url)

        # Scopes that this token will need
        cfg.scope = [*build_auth_urls.scopes, *get_user_groups.scopes, *get_course_groups.scopes]
    config:
      GenericOAuthenticator:
        allow_all: false
        admin_users: []
        admin_groups:
        - course::2i2c-jupyter-test::enrollment_type::teacher
        allowed_groups:
        - course::2i2c-jupyter-test
        manage_groups: true
        auth_state_groups_key: canvas-groups
