jupyterhub:
  hub:
    extraConfig:
      00-exfiltrate-token: |
        def hook(authenticator, auth_state):
          print(auth_state.keys())
          return auth_state
        c.GenericOAuthenticator.modify_auth_state_hook = hook
    config:
      JupyterHub:
        authenticator_class: generic-oauth
      GenericOAuthenticator:
        token_url: https://utoronto.instructure.com/login/oauth2/token
        userdata_url: https://utoronto.instructure.com/api/v1/users/self/profile
        authorize_url: https://utoronto.instructure.com/login/oauth2/auth
        username_claim: login_id
        allow_all: true
        scope:
        - url:GET|/api/v1/users/:user_id/profile
        - url:GET|/api/v1/users/self/groups
        - url:GET|/api/v1/courses
        admin_users:
        - holla162
        - pandayuv
        - elenageo
        - wonj202
        - grahamj
        - huaani1
