jupyterhub:
  hub:
    config:
      GenericOAuthenticator:
        client_id: ENC[AES256_GCM,data:AhLbD8TwqS6tSdp3UsbzUD0V,iv:aIepSssKhRBr9wjo2+k+IlXspLbmANqOUMbuMtXd43A=,tag:LGrEtgT6Kfbi5jXeEyD0Og==,type:str]
        client_secret: ENC[AES256_GCM,data:g33Eg1nUA3AeVHN6vWzdQbkmjZbWe6PbBYHIgLOavw1jW3urQv8ezGzYRZGVDW2kGvvjGKX4uehLeBBPHsLbDg==,iv:5zbTwqXhybIr78fYoG5fq2OQ9pafSHMj0eRpNXiJmHQ=,tag:wlMrTwSApbItrMYAPiHEOQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-03-20T15:10:26Z'
    enc: CiUA4OM7eAniVXYeM2TCLg9E7XJTUQecoD8CuEJKLnj/GCljwj8lEkkAPHlbmbXSNjkV1HyPh8pkV7k8r7l8/QxVAT1H9lUXnS0+M5bF14dt44NmbCR8T7IPfJWaS8Zh2Qb8PyC2imh9HxzWOOnl//h4
  lastmodified: '2026-03-20T15:10:36Z'
  mac: ENC[AES256_GCM,data:+xgSP3aGd5sEDAzXm8RbHkx5AbWwUyc/JLBiIf9PcmMYkLh60+vQA6VgGY9S1pV1wEaLlX7pmYYh9rtMbfvkOWHRpgxnvv8PZ1Wtm7QxO4YayMpFkbAO3XPvZPYnFJuvqFwwmfbYeQOzibiJnJxFdVV6HuNKRnDXZLBWovGzPiE=,iv:dLPraRkc7yuQDCPO4xo3umxiTYSK7/NWc8EFT1pXlCM=,tag:cDYfn31TzFGqtYrOXtyRhw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
