prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:zTKiIg+tmZy8j+TAxw==,iv:9r4esEr3YOfxySvrw7Sje39jMQ0QcoSVKTuuDsZXhU4=,tag:2gJER70FBHGjgqO2tEO3cg==,type:str]
      value: ENC[AES256_GCM,data:yok+vX9dnTA1k05EtSQVaVd3umQJLLa8HO5bLlU1SDFXephsGvjG63/IkjdiJw5VDbz9rZt1TOWVqpNqVU+n7fyT5EhXQT2IjYkacam7ktWU0vpwSP5wGuUk6yIZOlWd2DlnFiXCqb64F7TTIYKPBISZWcGAMVEtdw158JYT5A+cF1EDAawzqu1M9goUTOwO+cCaMtbTK/97Y3bKxHbrNjg6j57fFYCT4heSAZFenwmPDA==,iv:J1ORMe+t/FjHtWp63sRABoiGpKjEc2N4MOoZde862PY=,tag:FS4PRQavlObPYypB5GReKA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        aewahche8niw3Ier0shaiwieMaim4phixa1Yalu0sieFohdie6Ii2TaecohJo2ti: ENC[AES256_GCM,data:gNgyp+yOVcTpHWrcxcGt+v3W6sbjX247/gHXo8OTgtAaGQB/jDA1nR05CMRfXqK9to8G0Pdavf6Hecb+,iv:O7LGQrr/xFYwS/f1OnozAXZl07+u2bhQIAIlD/k4PYI=,tag:NLg7Z5zPFbe5kG1ng/s75w==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:yTJXNg==,iv:SChhnV3OA35dnROwxTh1mMDepplV16DdOKw4/mQpogw=,tag:Z+9hxI8Y3T44H6tJIbUXxg==,type:bool]
    username: ENC[AES256_GCM,data:M66o7J15ni0PELRjayLIiq+QlVjvl4w40M+Ex12DOTBdVUShyKJ5KXW5Mvcx21AoeUlSRfmY0br3J2l0MD2VBw==,iv:9wJXJ9zxSDF4WNNtLs/PWMGaRaK9Z5WDsFSQ0YAR4us=,tag:dhCdxUGkY6ppafXB4GZKJw==,type:str]
    password: ENC[AES256_GCM,data:ohBrJgXoq8BzNfiqPS28v0ACtQuXM67uzdeU24xmofi5jFnshqpzY5FXufVF0Z94vUy0Ltn5n2ItlaXOgUxLgw==,iv:S5Rn3HaEs1JjvCzPjaJUcaPluzW4y3pnxGzC7oIRgI8=,tag:qM2nvsKYxWpFn7TMo8msqw==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:xvBXUHbFkskVf79quiK8IsICsGZsFmxpPMfMmanhsbOa1JnAdrVeXM6KJ7/xxBMD8z1Ec9jF7+SzbwfLijXzAQ==,iv:c5ChW3nCyobfluquncexP/Fu9pSqYibhFTxf+EVOD7A=,tag:Zu9r4bhwjFx6A1N++QY1rg==,type:str]
  password: ENC[AES256_GCM,data:HMZ2fKk57JC/4pVNoYClz382i9tiO2UF56whb1AuJQRqC3ZzP43vYa/I2i9Rsr42JATkPJFpxnxhLNRtieoWDw==,iv:hsYOFBn93LAaUvdRlc8HctUHAL7c7+EXUZ7WYEoPt5Q=,tag:QDng/GbVefH4yqJ4Hu5x1w==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:21:52Z'
    enc: CiUA4OM7ePKOX3NYHrRrKTLy4hq9T9eve2eaJASbeBRTUz1QsAQnEkkAmy+ekkd8sn6UNWL9jjEfL6evFWF3ekZGXsCv3li8F5g9Hkne25jifL+RobgLqvPaYGZ30MBMBfO/r1gH+Uwipclt54diGkO4
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:21:52Z'
  mac: ENC[AES256_GCM,data:9G45EoOw8c+PxH0xR/hf7HE6QnfkpKho40e4e7RrRb9166T0iGFEp13ez4Ty6tz3Ue1uZo/KSYxt4cWyzgZTEkFXbTiiVI8kPfA0WO/xblHs6elEUuGhvopkzgoU7c+TpgH+exUcdUZJnT1O1kNMT32Glv3tljWiytxk1wOeWO8=,iv:RoNXn3fuUadXeFKtt2LCWzRT9NP0tAdv3S+mHJrq9tI=,tag:eKv8g0VKQhxn90vPHzc9VA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
