prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:WGZnPa39t1x72//ff6xCyfkGPYS1et83A+fRWseWw0/oUzznmAiodU6BxE6SPIPINmGQhMUyVVIfyAvgL3050zpBiqDuHccWyrWWOMkLjKSWJMHbKy/LOOtFQzsMhTHHwCPgbMjV2XdZkOqidP6F6zB54YdSqecMTnGLvtP21pWCpA39dfEigIGQPIOV82LaHWTv9q7FGvn11JI8,iv:1rp5r6XIXaevu00N756rS5qCQYoz979j4YI7DNfVisE=,tag:4Gw/TnpnqmJAezifMP38/w==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:WO3rDfwmZFo3W24IEZ8hPfD9I0bG98LSrWleZRebLaUFf+SPLjv7hJxva72Mw6D8xO2mgIO6fxe0oW9z7/zxww==,iv:Q6Ese/dIxiHYLLeKgHVHeCdqen6QDhfkJoIjgw2iXXU=,tag:kB6fxcIS8wBzbVGs2bEiBg==,type:str]
    password: ENC[AES256_GCM,data:L5/pygBnDfDQrMoP8mKonNk/TnTL2MUDeivKpSbPYZenPdAZNkYBkB0IGh7j8UAQVxRY41Xgq1JMQaVP5jooXg==,iv:7Hf5s6ioLJRZPPTzYC6LCXSnjG3VnHRcoNxni9ANV4U=,tag:ArMog+3mN2bnfaHiPgFp0g==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Xg==,iv:QTHCjk9/L2SgPnliKe+hvXAsi7HJTTlc7F6x0qb7t+o=,tag:vu7FUcYmhu4xzSiG7hpxfg==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:fuy8+fRy01P6SA==,iv:GhNYrtF/Qt2C+2XPcu0cfF5xiwlC+b97dNUG5CkgENQ=,tag:JabWFjxGKG/o8ESGgP1T6w==,type:str]
        orgId: ENC[AES256_GCM,data:pg==,iv:OLo1DiDnDr21RWPx94sNOlXKQTlE8GMlFZDm+07611A=,tag:tiOeQ/5iN2NjkdtRpgDrgg==,type:int]
        type: ENC[AES256_GCM,data:jZxolzi8ODQHgQ==,iv:vUb+JX3BiAh10Smw8wxO+f0K4ZXpzcoqbEkHqrSPZN4=,tag:Ta0CksWPGrr575jKCKQw0w==,type:str]
        url: ENC[AES256_GCM,data:VbB53nNzxy3mfaVGAdOf0cmolPrE/Mcp0C+VWCfMuug=,iv:8iIAzV2zJNZdKTL5CzOoGGQriDRlJz8U8V+UmvrIhuI=,tag:i0LK8MzrChKxV4JQjrfZ6A==,type:str]
        access: ENC[AES256_GCM,data:qpYPS3I=,iv:3hiOb9AElhDBpETtuC+NJlvDws9h2D8ZFOPrHsl+XDM=,tag:Z6iLv9GVz7LCiQUeaO42RQ==,type:str]
        isDefault: ENC[AES256_GCM,data:cST/Fmc=,iv:xn8YKn1Y1PUpBj28d8/MSKJawTJwRl6DDks+JDnxtjw=,tag:j8CGknF8JS7MWGWO2vKkVg==,type:bool]
        editable: ENC[AES256_GCM,data:wvwsmXM=,iv:N8W9SVkdb5G7UX7pi4K6GdgLIHnvWm1veJNX21NrpDw=,tag:He54siRbOp5AUP/LOg31iQ==,type:bool]
        basicAuth: ENC[AES256_GCM,data:Wi6H8g==,iv:4V5YJyCtrbuwo33n+xeMs5xHIBARx7V0IJgP0+ANGdA=,tag:tnGKRBpe3AwjOSJqOs3hww==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:qGNtg4RSvhcoBjIcmttEYj68JOWJScTeXFHM+Y+0abQsCXSeOih6aLPdO10qF/Dlale9UVaM5n4GY/yHNnj37g==,iv:LavxV1p5rk4KbQiJtaD5aYcORg0kv3fJlE9qE2IEApk=,tag:4x7+U/L7HPSQ38fwwcnGow==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:Y8XwYuPihkFW9qdM92yyXK0Q1oSaU9lx5BExPzuKNeBXw/kcpZhaeZBqdVBOH0khjdKZkf3BhBuzdA0SX57LDw==,iv:cyLHiGzGaEPRq7jJg4L+18bdX7i1R8YRR8lFt/wBePU=,tag:K6MDFUU9cE86UMOSnUMHBw==,type:str]
      - name: ENC[AES256_GCM,data:vLf0gYBfXL0zrGLnU17Ni1ajeOGJU1Mx187ODIBDNw==,iv:xwC+s0cMdE7B/gYgcSFVFbERHiZ9yPQS1N/JGzzJHUg=,tag:Odh8IJCHku+T2CINmJ0rjA==,type:str]
        type: ENC[AES256_GCM,data:HNsGFVjeHqp3wTwp3ZjHJuLl8tucFm0izPTJLPHuag==,iv:u8m1blKJnl44AkjCQla2sU6LXvQJcqsCH2vorA5LwnM=,tag:GdtpX34agkGH/U0B05vT/Q==,type:str]
        isDefault: ENC[AES256_GCM,data:Pf+PIjw=,iv:Gv8yYme3eM4xwhZA9EiAqvzzLvWi+Eip9cC24bMGFds=,tag:KC/6y0zQRnIRXQ4R/YzUlw==,type:bool]
        editable: ENC[AES256_GCM,data:6prsGw==,iv:bjAOb0wMVe6/zgmq5Uy7v/1hO7NiFBs1WZ7+sYok0fU=,tag:ZrP1nZOBLiyqIoCQowPjvw==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:Fop/WoOyBMKk6mMPGg==,iv:T+BO+9kAiXJxfrT2iHbRuWC3gw4eiPv4qPFZFLgV4Ec=,tag:eRkCDWkqiL4ylmxF2VpwAw==,type:str]
      value: ENC[AES256_GCM,data:RF4tcAWhQUpqrjxwKFZsdvkaNVuo+Z7uxIghmybZ/6ziz+6kJ66l+zljdUVg68Qs3FMw+6e9lRm8n6j8AoMi90BDoCSnMFiGmx5MpHuIFOqJYgqWW+ewAwvaWLHTmLq/7Y4Zp8l/H0P+YJKkm4/ErlSa0JSCFBqraRVsOzwFNVwW5D1whMeVp5/i/w07UgT8yqqRY/B8qpFW+54Je9MGCwNCDKuSSiS/RJoFUJn02gca7g==,iv:lfLmwfRVQgfrhm2VZ54mTcjPUPUOCAJa9H/19znvUxI=,tag:xZpqMhTBeUvic75hy6aRtQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:VY/y2TCpfOoC1JHjVFGcnQfJPlX+dPELP+85tXvUzXqxMwXz1B8wZSynQC1uJh/QVXBN6PSLGc4n49GvGNrDQw==,iv:i93Uyglbgzi6ByedONU5uJzUIZ4mJ6tIx5howN2ESeI=,tag:IH9bsgE9toC0C81Y98ysIg==,type:str]
        password: ENC[AES256_GCM,data:6FwEPWl5KJe7qx3JYq16dE6jsB0blOe+/hnknnDDYhhBbpI45KJBn/3K+BNz6wN59CUM6SzZM7H97kZsJQy8Cg==,iv:l5hpz5jsfjHEyGxJ9jPqweiwQRBwIn+Z6SAi9ali4Aw=,tag:IuT6aCNGI4PUbc/WSzrfJA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        aewahche8niw3Ier0shaiwieMaim4phixa1Yalu0sieFohdie6Ii2TaecohJo2ti: ENC[AES256_GCM,data:c9WOikSazA0WCSBvKGTSKhR54XduPnyKcMDvVUSJWnz1z+TLVN9HzZvlmL6+GBqT9oeEm1/eoMGsDN1A,iv:PHlMDwTam4g32AQoA4GSZjKbX6sqD/cX4BNGiocYH08=,tag:f/qmgTAv9Y+cX1tv/8WALQ==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:oMWLxA==,iv:PNZ6lftvaj4FUoNVyTHCt/gI9/R2zWh2F3ekN4TCT0o=,tag:GtMJXXxQmgd0ty03zTXm3g==,type:bool]
    username: ENC[AES256_GCM,data:dse6F+4YIOPsbypF25+1Mvrxu9N2NZjqmPs+p3pAzwRwbcmUYQg8a+VtBEv8q5TbH8CBUVBpKevB8K6wXbKX9w==,iv:f1GyPm8wwz7MiMMJfLihv02A8bsCNlnReh+PghfCnC4=,tag:WwbCew0+Us3DIz5O1Wm5ZQ==,type:str]
    password: ENC[AES256_GCM,data:X9tWUAPSCBCSO70A8ruTeAgUfDl77VQgQn8abVWS1AEodaJ02vJE2ZesxhYXY6Ld0IZUOSeHLAYZwNTtDPkJAg==,iv:ST0CuNsWODvQCkWQXE9BexiTLZzkPfsUsVBD52TqpEU=,tag:Uq1YQF0bRWgqmQqby//riw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:38Z'
    enc: CiUA4OM7eE8+GlKEJ8TCWdt3+GXdtKJYvDxUo7aEJBafz5CB24toEkkAPHlbmXxWy7+meElDPXaVzd8kAMH5ToR+7v5L7Ib2poOQ0te4jQSdyiGfIaLmmj8nmnCxUsGmmsLH3MO6LDrcxytm3Eqhy4CM
  lastmodified: '2026-05-01T14:40:38Z'
  mac: ENC[AES256_GCM,data:03Xw3CwwQI9GBS1u61jKuSxWWc2q3Z8SbO779hDPEPch1Wx9IzcFGFbi0HkhsuIDMv9bHnT6LOV7V5fWuHPl3F5rnAuQDxckUFn+yrrBsF2m9t6C03bcxqYZD9D6640NdxXNRz/KKMFeJGlxniXByGRdhYZck9E8tEoRCf/k9rA=,iv:40WC3zJZq/Td1gfmerU3LEDLaZIlng6w2Rw5zsF2hpY=,tag:hAg5ZLzG7rAqoHBQLyqwTQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
