jupyterhub:
  hub:
    config:
      GenericOAuthenticator:
        client_id: ENC[AES256_GCM,data:J9u00OyQnUnUaFglWRnEVOC8,iv:BnKdClQ6n7mlR73xzo3l8F921teLM00tOTZ9tRukqDo=,tag:dlkM9V0AZF3EE3GnhbNafw==,type:str]
        client_secret: ENC[AES256_GCM,data:gqlp8/4OuFlx2mcD+WVTU77P6oVgEhD2xQ/a2+yaIq+ucAJf/7TP+DpU8+1HBunRuPq64GMjZg7GYDqXS5LLcw==,iv:0Fv4dVxiwcDUL+IJDIUDbv61yfo7QKeOTrsadLiDEtg=,tag:2sd92A+qzqiWhA/YTa28Vg==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-07-16T13:57:53Z'
    enc: CiUA4OM7eFv1UIuxHEmDNcJsk1n6ZejTi6LJMZwW+swTV4IaVDJ8EkkAmy+ekrNT41OErGBI3fBrEzKdGFlrKdwQEmxkgzXaN2ARHGesBVFrOnGQOG2sjx64UHt8e95h6eBWxY3FIHUq4OriFC47Yyam
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-07-16T13:58:01Z'
  mac: ENC[AES256_GCM,data:3k+7YHEgz5a5JdcDA0v+aBCwHjdi+UUZ9FMHpFIV63mLzuTg/P2KUKLJ4P0rA9O1rvRjdonD5pvcamiKy1a0beTwTK52e+vh+x3RpmcauQHUCVDBSv24onfOVQkiQWs3d1bypol2coJhOlkFOgAfOQcolzdmtSQDYS3UbNEyiRM=,iv:wtOJv0W8RWiLVUlmcwJ5frYnQ9EGuTjkwfzxTBFjGag=,tag:q4vJ31/6Y5cenEM38xY0Wg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
