prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:zPkAEZh9wgXdiFSQxQ==,iv:Eb7YAcFILZoUskkoxD+m5Gd++QL2FQ+TqJcRieAw43g=,tag:cpa6Cbj2CUeG16Ynj+Tbcg==,type:str]
      value: ENC[AES256_GCM,data:9pyL5PzfSl9JkHB+BqwJxJN1RI6lyqnV4LtMegd2zE9CXDfzqybjdMAR1WuYYfgsp3/00VkO7o7HObXEGqrsfrtaCbOPgm5VL4c86k00diuPBV5EhM27jbJj9d6UKYHHsaw115S8j4031ntJOfiY/ObEmNGT1aLUO9pnwIdT4sfPKz9IZLTmU4oKDo9LycFeZpURdjfzUjXpcS4dLyBBtZCrbRtpGGaY+cgC3RgrYn4GQg==,iv:m36OZptcTUFowRhFr187i9xJAwEcKf/IzU1mr2lK7yE=,tag:5t1Kh4byLv0pvrOM+uZ8CQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        TRZdTFOy4K4FSxvLNImzO5NCzsXcYAHBQbAzSDZl9nG0EpE1dLUQKYQqxaKqiSjy: ENC[AES256_GCM,data:+Rt8gw0EDvlzVlPW6NkmaWCKH7GpXx7EeXTU5QdSqoMN6on/s2DYNI9hdpGfUeblANSAgZ97FBcSCtrc,iv:02HJqWycsu2WZH1rAZzsPLeV+SgZTAwzZ98Ph6aE5tI=,tag:opRX05bQ8WCUCGJ9xUPdcA==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:n1wsjA==,iv:WNp61ZhLjiJzPgeiRjJGfKYtQhiHdcVoREQcZ3BdtUQ=,tag:7ONciXpPNfmD/AbauNAPQA==,type:bool]
    username: ENC[AES256_GCM,data:KbfP488eh8tWMY85h052vFNRVHEAYpg3hJ7UW/x0ytEFCEiESou1fIiRU7b8HACPfRF+eJYz1Dr638VcBtQxIA==,iv:rqiRayF+CjPqykppoutO0APJYov6elBFr/nvRqA+1eo=,tag:Nn+7dcjYDpEhq8ly3VQmXQ==,type:str]
    password: ENC[AES256_GCM,data:xGAHABf/aQUKzL1Ir8ePrBEA2uM0i84tMuCgv7pWSv5aLvPBER6L4IVUqFBGm1LudFoozermSAgBKIKVMapLxg==,iv:WzDgTpWw37KXxAF1fFVct46ug1hSQqVFpYSmypuVEXw=,tag:K9n/cc1oGzywfX+jIOVtBw==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:KjGqit0R4M9QK79UD0GY0D7uNKTuZOgbxmhTZVe504ifYTEdPJ4jjdzp5Q7WUV+AMhebXjJJanLd0Mmgd7TgmQ==,iv:k50K1P3xN5OfZ4oJgzElZtz8yTdZMOQ5EGZn6fh0lIY=,tag:9foZzdkEynt9eUoZUsDxFA==,type:str]
  password: ENC[AES256_GCM,data:wjjyjpDECrlNpvIy16Oq0QJSDnm752eGk9RkIV6qo5NL+sgbxtmzgs52e4s2LNtfsyWAX6y0M8hixMQvcMrNpg==,iv:vDCoKvC31EQO/ndGzmiV+PEc4UbXeZMdzSOSaw+qLao=,tag:auOiETnDX+nclMAFdVjoQg==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:21:25Z'
    enc: CiUA4OM7eK8s+2ekYyxjJ8v0kwEPd394EuY/ikjUCp6ER2HiyDAcEkkAmy+ekgQDGzdvede+Dp7Cgp+Uq7KGENOmp8q11DkF13Luod2kxoWH78xQzFlcmqFPD7VXAeFQKkU8ALrl8AHsUhDnGDydTsE/
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:21:26Z'
  mac: ENC[AES256_GCM,data:BiGjQR5PnTaBS7qBdIMhRDkWPgnAbiJMOCD4dGc1jAiEa1AN2hb2h3ZiF+jn5MNLP40/9TDbK/MMgriaN05TGb3jNBrjYeDsUybSWEzhNLG6jbQtkEj/CWO3BNVpPoBT9SOOWfVoBREvuDJkt7pm7JV/biEaUp1o13ANiwzzVKg=,iv:/OJKivOIM4DI0iWPUzuQu/TVEkrFguO7Fu+SyFpfK7c=,tag:Jj63RXHrgetpW9dUGyQwTg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
