prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:toBWg0737d1IhY0arJsyNFib+wh7496lLcYn/NA2Vepy/FGgKwgWuE2mv9HtRfHklAeO5yOOS0+utfFKHFxN09iwopE/aHpFqoWRJJFXI/c2KCjULK8aiJVqGj6PU3Sy123FtE5vBojGUQEyxJ/u9E496S67SoKo8twYGOAaWuOZcrbliKO8otE5IlY7+cV5b0VbUgtFkSaJr0Jj,iv:QVpdShrY852fJ5pUoVIOyfWiGwbbqtuIzDuh4qTXVFk=,tag:WhGqQqT1Kt1vkyWa/q8lbA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:poznLpndEGc2R/2hMqF4kYMiaC/DCxh1GgUZSXJpADgGk7hpzQI2jAdXvgKXD5dtnyFrOdSDqOH18XWAl52Dpw==,iv:S54GnGRYeF0RUPf8fA3q/5LW++HnK7PjfAmXf6RR1PM=,tag:e0DGlmg8EcKM56sSs1MlWQ==,type:str]
    password: ENC[AES256_GCM,data:8uUp+gaBh34KR69cfaqg31QXWW8vT8C60XN5mdDH4hOawOWd+y2ctNdk08RtzxxFZRaLqXvq/QaETTLNLDSR1A==,iv:tzUOXEDzhNeBiIrCvTDAS2CQ2rYg6w7Ig2qSK9ZA/AU=,tag:q4/wP4qQwoLyi4RnL4eTTQ==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:fecUmRtUjL+6oixeuA==,iv:RX+eXMs4Q6CJoY5LERVnKd2CEP2ScGm3vvPSBPOdBKk=,tag:WOvH3+quelITrqBNAlLSgA==,type:str]
      value: ENC[AES256_GCM,data:H/vqlPezG8jXiumXp4QGAqW1hdaVLyEOUBJvMapF23yagQ/yfl5T6DoZX1A2NRqawkiupBx2JsYUKgmcEJny9upeRh6/tqXOXo+CT2RhXcoWQaDhGViZ9l4SrwdttpzOskDYtf3cBZcE/gklSOjoHpFjWEa4EsKWbtZNT5Cl43SLN5RSgE+1+Eb8ZU8oojREq2AuGYnQOuCR3ChEp9ApwqdAVYc1bEUzwE2K3Gxn4tF73A==,iv:jKYJsOx9f99FEzI+iRFGqM0HG1zsqGCzsVASn/e1Ax8=,tag:jClffJZi8dsHEEage4VeAw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:ekCeW+to6JUUroCmniNFQtLD7QnA51aEeVvBZGisCoyYGdYqNmAoxNhDt3rOOjsXj9lMbeJ6TQtqyFMLMNBtRw==,iv:DzOx7E+7vWxyZywMWL/HSyXLwGygRWnniCF70PIQu2g=,tag:RXQqBCPuHWgz22o1nHnavg==,type:str]
        password: ENC[AES256_GCM,data:+TJnkgh3+7o2545JxU+q2a1kE/BFeGR1iZFcJX2tO99l1liDXcAcFwsPdeY4Z5aZK8ep1i+1jZ4IDwrvj8SSDg==,iv:QPhgJYnXOCFqabGTyHYXhLqeI/oK2DbOBwJ5+akfKbE=,tag:3I62Lb34fcdCOU47nF4F3g==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        TRZdTFOy4K4FSxvLNImzO5NCzsXcYAHBQbAzSDZl9nG0EpE1dLUQKYQqxaKqiSjy: ENC[AES256_GCM,data:tTKDndPBu9HMSuPJhsSnHc2nELPFHQdYVpcsbvHo5a+e/MOlqUx6YdSZP2LTv427xzQTZxV1BULGONNx,iv:R2ufg1YoB7jAOgqQ45blZ6ug6oUQ2WifhUzD68ExuLY=,tag:GsMQhUJdiskhBNx3NYZBsQ==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:1g==,iv:s1AEBFFhKruaK1rQTi38/6rhBPX4Qsh9psr2tllcx8E=,tag:9nzeyGm4fyTamcZ5k3IZmQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:5kuEA/kCKurMZA==,iv:AClpymdMQkS1P6dYGJrColMpTKEw2TGe1tPLa/TD9cU=,tag:9Es6xEapmONaUj+DjKj6aA==,type:str]
        orgId: ENC[AES256_GCM,data:4A==,iv:IpAKft7Pa+v5PjgK0nsccCZ7i1Hxg71CGWu4inOl3g4=,tag:qb4K1eePbMPlo/RCessLkw==,type:int]
        type: ENC[AES256_GCM,data:1F9ofdNnBmP3aQ==,iv:MUepA0OocEGndcc4gDEXqm3ad4piUFn28Cgr4pxB7HA=,tag:m0LXW2w13nwlSgIpGlF6jg==,type:str]
        url: ENC[AES256_GCM,data:C48Wzyo6ZYF4o3EbEcCgZBL/Xs3jT3+Hi/Yida21+74=,iv:58sGUmG/FHhw12Yeuk52O1u5vS760mjGeMgP4X7RtY4=,tag:i+yi6mtO318PcWf/v+vAlQ==,type:str]
        access: ENC[AES256_GCM,data:KucvwxE=,iv:8zofFKJ+M+8mvu/UX5N1rKDCsP1izEzZLX4ZucZz8BE=,tag:toECui79/h5VeUegQ84bYw==,type:str]
        isDefault: ENC[AES256_GCM,data:ATB91fQ=,iv:2evfnu7mcKLn7RNLRLxbizqvkz4ii+WigR3MuAzuJ9I=,tag:S/If1c8Duo9XNDNESTXnpg==,type:bool]
        editable: ENC[AES256_GCM,data:OS1Yfog=,iv:Puantf1Bq5/3hAoU4ZL0OTO6wamESfXknPHMCEyRVwU=,tag:uxTSvm15kU0XDXCCQZZHgg==,type:bool]
        basicAuth: ENC[AES256_GCM,data:0JPudA==,iv:H++p03httuZA1GKJXz6eG7pYoEC4JorQJvbI9ZzurVM=,tag:hJ4oxTxIkIqVx4Ca/Mp7fA==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:RQhAImJJtVKi7cgUJ4MlST6etfN3CkkeuxZoWTShoGOoXTTmmMrSxc4mEDdz6Wk5FR4yIwuVieNLA9Jlq0yTLQ==,iv:AhcXnDEOjmTGRxXoRxBoLeUAQtwnncj0Z1bFhaUgHsI=,tag:48olCR5GJNVQj+FsafKtVw==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:4HGjMWQMABT/ANlQ5kCnFjtra4WGQGxDPpyZgu4VRojJglkeEeJPasllvk4MlFjXgjFpF9wE9vgkvvTMLnZmRg==,iv:2UqbfVo+EeOBSC6yb2xtQaQ2gR3dIgMPQ9pBGcwmM3I=,tag:JEdHOnb7LWc08+5LkbaPNQ==,type:str]
      - name: ENC[AES256_GCM,data:Yq8sRbemMPz12GrDsyBPDaYyhHZxAYojO1PYBWszqA==,iv:ggyWHrUpQiYEqHChJX/8etmh4i/PW0QbqxfILv+IpgI=,tag:heX3Vkv6rh/g+K9fBk2wwg==,type:str]
        type: ENC[AES256_GCM,data:55k9guraCXwVtQFxbMLcstBOMmGWrYNqupXqTXV+Xg==,iv:ahKL9gA20AWkFoMRuPZ5RcCM6dhAHT9GfKRGgYcC6to=,tag:k8b6kXH9smugUIm2liZ8Mw==,type:str]
        isDefault: ENC[AES256_GCM,data:KTq4Mdw=,iv:tJUgH4oSMvkrbQ45vPaot5VG/0t5xfgGqp8Tn9rFIr4=,tag:ly1On+8lBCSCJRHRrOJUkQ==,type:bool]
        editable: ENC[AES256_GCM,data:gsKHsw==,iv:zW9T8d1oKjuUIMx56wZmwjMLBhgolVewlCsG5wusKes=,tag:PhUunqD/LZzwaCm6WFDGMQ==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:ggcFPQ==,iv:/fomAuIJmCHuMXCaEAAfbNVmPJqTS2A5xIFuvHYzaqI=,tag:v5/SezecTuCQUk/fo9cQLA==,type:bool]
    username: ENC[AES256_GCM,data:ljEYDwfB7DQrnimyJBWtr/teEEG6xetolNi5jDPjemQixwPhAQNPWkRhvHNyTXHi1mrTCQCbmdv0VmfnFaWhpg==,iv:YiHkxPtWs4G90evPJTZ7yp70r8quVe2jbQ+tix2hflc=,tag:v+tgqrK55EzAK4WOGnS6HQ==,type:str]
    password: ENC[AES256_GCM,data:MWNgdQNzmqwJwDCrygBrbmwLOa4SPlxJFS6hM8qGL1B7ynL6MZqprtK+zuaSPKIDvcSFP2O27CrWS/4/1+fuXA==,iv:W/Xm7YbswMoU+3mX2/lJDR9tQMc2FVoZWnwrH+IuJ+E=,tag:iR+zGxQlOvO6qZFR/7p65A==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:19Z'
    enc: CiUA4OM7eB+CuUaUVJXmLUsnUjIDaTqrAkXZj1Gj6dD7/vDyPCyxEkkAPHlbmf4jFpcHcrJIfPvGaD3guFz9EYqeQs32gnsnZteXQHd6aUsKm4aKER8UAd0+9anhUJDTtSA90uXAca0l/TC8hBI51gav
  lastmodified: '2026-05-01T14:40:20Z'
  mac: ENC[AES256_GCM,data:0cTHwH1O3jn0+5GQHNuNbjRDfLOIebS+nc5C8cSu0Cx5eY40Xe6s12apTcAe6ZBE95W0oYjo+OCiKpWOknCy2vjbu2rceG3fcFbe0ZiVLrkZpKC6uDIxzoU3DluNQGrumxBqPZvzllxZXoSVzqMqORAib8Q04UVEo9eHmAj0b3s=,iv:RmOoI0crvIupMIAPGmfj8OOnc4AQXnoo5Fq6LBCZPHE=,tag:bo1oRliG8Pl5buvM3v2tvA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
