jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:/lTwBJUlfxvVPm+r3ku5cPDpCzk=,iv:+sCCulbNvgqyrl8IizEgi2a9PR/KVRsi/I2k+5+leqc=,tag:DS9/v/H0wEkG70ij65aIDQ==,type:str]
        client_secret: ENC[AES256_GCM,data:VayR3wPx9J4NwzfUEu+1v0diELoiQoOUC9a2U3T5hhrnUbkX2XN7fw==,iv:KH0Am0oHTw39N3zACXcMxvZPnp6ynBHd9Q8JgEgBXrs=,tag:0m4As2TdtKY4KaBUIoTNFA==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:T+hWZ1QwE1++Sg58UKGnaWoEYicH5iMAKSqF+HiaQNmXo567Rz8g2tRgF32guQ0vTb7jVleT5rYu0Fi7IyRBiUnq+yauoB+uWquWytyeM5RP1B4yB+c=,iv:xLhZm2oqKyDdLsxCu2Xq6xAaeyNL9xDR4CgnskQHL+g=,tag:TuY/FEGAq6TGHWyp6Nb+LQ==,type:str]
        stringData: ENC[AES256_GCM,data:sPPl1FhQ7J/SBIxO7+qzIP7pQ9qDad1g+IpWM+HCKM5fxKyjEQksWTDiClD2llLbatE1sjZqKbR+e8DuqNCKA/OexJ3xxcjSqqqJwAWDfDGpYS91MCLzsk0cOmUuXGKbV++c/N9uZSeP12T8E0ukbTCpiJb4RjRPBp1eYwMmyqwMKx38C+B6hQVGVPdEKYP6WdiwW5P5dDTxXv9hUhEOrlkxH73NKWoAjxIL4NVafIr9vieBZ0cJQRfaQipR+rvC61z7OLo9evnsSp4UE6kFiJbszFALyqLxw5QboN2UKfd5ET/hw2PiyFBM3MWLWJNcYrB0jFtk8XR2vPXUuSCkewKPCXM/RJpFF60juiFboUDsclFy5KYDkiwuqBlMhOsugxSFeSLCu4y58d7/OxEb6kStuaDJSxksh83EcJhob71F8aIN+2UEcrV1Qbrf1mKipO3D2DOQpWSflnera0GP4NIZcjc90OykxN+bVvKFNwGwhF83Emwm840v/BA6pPd3jJ6hhfBnI0Na/l5JKE8HhzILm6aHm4IBj1KtteMLIPsDmtESBuzdiq4uFRHOVVA9f5Z29eayxSuNsCV6KA+gRCiFVJXDCBX5/S7zwX8ITvPWqdMMbVGvAR0tV4jU+8I3pVxBFYmdk6a31n0Yrw==,iv:3umlBAz0sOCBG8zIG5+GsL0NPGkCMnWpbbVo6f4F7Bo=,tag:x9Hg88mI70MWewf8BabAfA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:16:00Z'
    enc: CiUA4OM7eDYYKMcqDA8bgLryKRoZcNM0QyoHWt53lnjAXmFzZAUFEkkAmy+ekol4N6gLmdP/430WM1nOrzTyRdyRiTtfri5AkThMO5yJT3F7gQrxkKGQQyQNVX4rzSIz4uSNuDDdRkLOWOrmfpT1xcgz
  lastmodified: '2026-07-29T19:16:01Z'
  mac: ENC[AES256_GCM,data:8Qi79D5elPLVnVKuoNRwQ0omjxQnu3ktF67pLDHlSM/TNmc6H1MwOcAo3R8Z7hi5J6rmsQ8iP+nTkXqyGVxARosEhqZzpABN9fWRTsWuu4YM0StTHWd2mOTsi6reXFk0Gw+7m1or6JOne0n+XO4HcmP0g6nPQodZ2eSQqmxmDCc=,iv:nIrnJHIHpRnjSZ/hkAjhpOB3eDV2j4HE1xnMYBv1vII=,tag:PiClOEGVu3hc9r0tng7dEw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
