jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:A8rIO/vpnLtwo7xxUlmAyFzh30Y=,iv:pzI/Jhkh+rgjdMcYuNAss9Ed+GV3Hl2E8IaqnyZ7deg=,tag:OeIRX0wYNlFLmR0/mIWbdA==,type:str]
        client_secret: ENC[AES256_GCM,data:euAe/FkKzbJXtVCVGzSOO8StfnsyeTKhof1IOTxoCNpmqb02SQA0yA==,iv:Sqi4ZTzmn0npRPLaA9/w5aQ3/J6KL5eMBotP2Fym/OE=,tag:y5yslQogASCOj3V4lQUe/Q==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:WM8alNyWL7xabwyYPcC5ju/hrf67OS/dvdermYH69IAv35H3HphklAJZ9dPnnU9O4Nb0kbUJLSKk3f0KYiuBGQ9DIlLJeG2eijWcj9IMQw7g6HbHfvk=,iv:pTdTDC02mxovkpzydIqN/qHkpWqHU7YUd6ogFXiE+lI=,tag:Uc+6Qn/o3UZygD1KbM+wjw==,type:str]
        stringData: ENC[AES256_GCM,data:CXqjOfP4eZxXpk7MEI8sf0bNNEC4qyRYVCtvC8N/X0yeA5W+YCtSwWaGn4yi/P1rJI2mhvFJEltxt/J9BEitLDFk3OZ66gpg6VBEuC6PO6ujO1qJ90blFSjquDQYgEE0hpk2RxFAdfiIwCSGlnkbFlJSt/eGjSsbXfda1cAUsZZltJNQff0FP61qv46LFuQhxcrI7DQ8ajo2+Jr6DeyBNWYiaaH55piK5n4C8SDjBe9LDjeVdxkGQ23HDUlq13ZGd74ZWelkzvakJBoxTPXNoUjHJDCSqk8COJoPujLw49O+jL23+VMFjLq4Wt8T9QbNwCDbHAGjV7/7Js4UbhnvfePRc0a5+3CHnbeb2Z1X6eOvtsfgPGSbEPv/+kjfGFW+q6w1ICA0c9sq8RYy3WTjsMHZ1IJEBoG2+WQtrMg+ZZfriDQZFYJ7r9d5MhBiNcb3fwwNMpL82ZhnYb+dZPaMcxjJeMbwy/DaQwRd/WLnLVKMbIbOjP9vyTNgKFgFZR6Y5SCLvo89svtKNT7CWAld19Ld2fbDTG7cqvnY43f6iqB2ht/bGSU1Uz/ghXp82yTZu9FYnCYm9pX5XjnfOFplx2jcEocCn5HEUFPeV/5DTwNNugK4NFbkHakBdMmkeKCUGEnJVMf8nELUdRuTHA==,iv:9DI244PwIK03s17YKjg1oF8GoPYURx7XwfXCQjg4Rrg=,tag:lZ53qHjKBVO1KDWS5QieqQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:16:02Z'
    enc: CiUA4OM7eCOuJ7UxqSYOGmhVfDPKoLpXloPIebq5N324JfpUJvXaEkkAmy+ekrbYSR/i7k1W3bV+gTWhL1RKKzNz3kRPlq2K+JoMlpWygunBbC5M88ApSXZu/cfSgXfoMXDZ7J5iLCFLRAfBP5hFXM4L
  lastmodified: '2026-07-29T19:16:02Z'
  mac: ENC[AES256_GCM,data:iwOdPd8yjE1ci2s3DhTAc65kykjIwqix7RMS0YKa7qoTkyuKajgaa7eNp2nYar7hBvtJwwSgdZspi5p7+F0tdcIUn6q56nCXIxl9tx+Si5HCLwXI2IpV2AwtrAtslpXAfhrdqjRef8Xp/hRjbesxCd3OWJaj/3u+D0amROkn6e4=,iv:qHDHRuRE7nwUDk29hRMLP3tHaEFSS4+3paxNSP6CzqM=,tag:zjk3988DVReLSoep0oHDiA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
