jupyterhub:
  hub:
    config:
      GenericOAuthenticator:
        client_id: ENC[AES256_GCM,data:aq8DFS0qtdem5szdEWwWKm0g+FHrcpTH4e+tyg==,iv:9O1IOaLwBfiuaGeUJwjcoJlg6zjbj67O+/+Ta4yHiYs=,tag:AEVaHFoJUMZqxsQhDHaMyg==,type:str]
        client_secret: ENC[AES256_GCM,data:aRHiVaKFdXRBAV356eW+Gw==,iv:1eZ5/N8k1CqpumQGagLbmg0j3C7BggrCOYuIvqlRMj0=,tag:deZU91JRJ8lLj0sVQ2F5xQ==,type:str]
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:NH2+wUj7rs20FxWC858UV0SgoCA=,iv:Cj7h/JHxe62x1n735H6RthYte9QBxTHAFL8qdvWRd7s=,tag:AcSVg7ZDLkaeUYpjBEdMMw==,type:str]
        client_secret: ENC[AES256_GCM,data:FldN15SpEDxu/q2qAji9dZFoeHxnrGA2Di9HKGGBrNr8NiWmcjZUWg==,iv:xtjmAK93Vau0OQCATUgmZfLhdn/NMjJuPhcSNERQavk=,tag:kmuoFJjDtHI6oR/jgT6TuQ==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:syqQzm/HePapAegMEgQ2rB7lovw1Hdta9VxNsLKYBRedioGHEmaEcrgQdMPlIq05n/8z0hmHF4yFTFbyydUQiIXtCnUs2yoJehzVsNmqWu/AOeQvM8k=,iv:UfY4SpFOkATRzcPutobMyuYUKWKBw79YK7GKJtu/41s=,tag:7Tb4WhSRME9yQHsdqwNouA==,type:str]
        stringData: ENC[AES256_GCM,data:RxKF1okRlE+tsrr38r6VcLR/yo3oEWQgctVkWQQjFBKUHAYlCbxqco57IP8bNh2l5khGa23mBcYtTBttLnkcYUyQsUqrm/J1MuL0vAjvp6m7xeTDp2VhBAZ7igwBfucPiZyqj1Ty45Foyx3mWuJ46q/TlYSEipdVgVS8fJOvQkYboLa8MLAcB2Z24ZBRW61luUyO2iOUbZs9Crtw2Tvuhpk8frR9Q0UNJ3691RhBKGjSNpYHleJQe/zJbYeAOdVW5Fe9L1tYUMkrILCFz6H9yX0LedhNpFYZB+EN5XhzgV9MXRABAMm9Rq73bbVepBiK28wbkA2AU5RyryDuHXXNKMGmF42porKFdBYRhb3eDSlN86BiAH6QgLhEvJrGsCpRd/1zL6volloAf+o63+U=,iv:43PHd67OtcmLaM1L7Nb1XnwHS4EQAnF2bafOboncI+I=,tag:vMGwNM9wNYsq/UMhjIopvw==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-06-26T10:19:59Z'
    enc: CiUA4OM7eINuKJ7EneuckMU+05k7E4bin+Uko4RRe63E0X1JMtLzEkkAmy+ekna8RgYdcnuMNz0FQBGHduo38ApWhO5gKwHbskRSGojlxQ1raH91Lon5GwOTvuk7YF7tpoPio5GDXQSOT+1FJQI5fBGj
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-06-26T10:20:01Z'
  mac: ENC[AES256_GCM,data:VTgDq9YuMK70uSGTikDffbn2Hq4GCaE7KWQPqKARFzoM7QpcuTCcbAaGmZUuqrlPMp5S1bOVZSsHr4iVcWWj1eJoI5DRVxMtRx/TPo4AIwO0y/cuTbv/o3u7qKnXYR5QlGKQLd7fDsf/LitplII10QUwtoj137ppxrMGELq3BTc=,iv:CU2+948axQNrT/jrI7RJ+G1tyTIQcm4/r+uWS5A1wRI=,tag:IRgRBcdVbYIxSqC1lT+bVg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
