jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:c15eCFHcfGeja5GaGhMp0a0kjMDsTh1ftTi5JvCsDJJ2c6dgqOTS1GWoU8rM3oQ28xmeux/7xMy18lJj4t8NFVOTqp25o8hyF7SEdfCs0Q==,iv:t2V8Cn1edbioaB8XF9sSv6OJu3i10lwO8EiE9Dh8pYM=,tag:5S0lVMfem62pO5bqwdZNRA==,type:str]
jupyterhub:
  hub:
    config:
      GenericOAuthenticator:
        client_id: ENC[AES256_GCM,data:HVbHaWRV6LNsvGv/3cVQTBTWvCM=,iv:GfL8xt5aIf9XoWCQPZMYzhvq8HDg2sRUwrDIuGJfV84=,tag:B8qB5EftLXpOC7ECzW2wZQ==,type:str]
        client_secret: ENC[AES256_GCM,data:a1+++w4R/fPhEEhBsuUzww==,iv:Re9jv1FK0cgDjDRcwg1oZRdQd9blMUpaO4qZbPjEvVY=,tag:W4fcOhBvin7NGDfScgb8aQ==,type:str]
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:13cqUWHb7ZtMYYVULO86yrBwRyY=,iv:nEexkJT3/+I+C4j0BV0xxXmQk1ZuqiALowkJik9TXdE=,tag:RPlosN4jH3nGPChxDYhEhg==,type:str]
        client_secret: ENC[AES256_GCM,data:E/Pm+Kqc4WjSkg/us9i0Pt0vulNGerDzcPOkNan1qM44uKtYQUyEVw==,iv:X5N5WBoH1m1MI28TO44xXL8EsEkc1fxZxp/7cmKPRU0=,tag:fFUq4piIIFzlgAWR/veNYg==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:iUAOOY4d17dbRJ4v01PziqJtwYHOsZqHjc6o1tfnviiQlYT8vsJjX2lIXh9sK6xA+jPjsTXKp4Tc9ac+7OtSoHWu20NlH8qb1fFrMF1iMzrEhiHJYjM=,iv:FZ4Zt0jtmPpFrAEZwGt5zmhFKh9697jkcwX+lDiie4Y=,tag:YcGtX47oLFViBSO8mNYWFw==,type:str]
        stringData: ENC[AES256_GCM,data:FcN+Wlz4CJuCX89cWrxGzQ+nmhgxvB/rid+d1SNN+3kc2Aw9IPPmvlG2onifdxwkjLKn1jHYjEI0fNwBqYXkYhSgqTxI+gjQAeyD//x9kC77QWvoKGpvYhxTDCyqpNDOIOPumDSZeH9gTNfjXM3i4Wa3En4ZVhQQqP8Ir0v8KzD4p5CHcOQokoQM5rg3ReCfJJPyg2F4sf+DAQsuktKARK6rK4e00uMa/o1HBszVHsWN2cYcI3P4y9cLkJoLkEsyNwkPTGX0bJXZU6g4aub6s6U+86rlUF+IoFTxErOJ+9P9XryFfL+t5oIFxUOpQMj12fpqn9o/vU89rPGwPo8vTKT2MGhxzJJWx4nx2R7Tkz9zoD+T+flTXUoY+QRwJ3dQQHTuF0wToc9vOdSZG5s=,iv:OmMKB5e99bxMlwscjqIIpz5FD+JjI4+3dHa+grlFtp4=,tag:mj6AVrJmggR2PQhV4PDUGw==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-06-26T10:20:08Z'
    enc: CiUA4OM7eBp0plriNLFNedNM5E3rxTVBiRE/N00nc78CHjjDskKPEkkAmy+ekrn3hjXG+ZgR3WPlwSshaD+57OwZHAKxerdgBqHh6cGq6DX2OjTUCl5xJuWhjo90dzNcHRFnNpq5Rw1GHYvnUxijj/fr
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-06-26T10:20:09Z'
  mac: ENC[AES256_GCM,data:Q10encTz/0ufIqE8Z5lBcU5GBF44p1VaZh/4vh/BTPSVP72vVLuOgo3savgk1FdW659C6KeIiJW4m0RCeWSKuWK6u5Gz59B8edyEX0+qUfEwvN60tJSqE3tn1TtWbGiYWUaKw98mQzUoDaoDXvQSjjTJqkAhY2M9Vybol3eR6nk=,iv:JnEz6fL6yt6H7ofCNY7Nr3X6u6ojwY2sQeoAVE6TFDk=,tag:GmHU5mwTWVmrAWWFasSCLw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
