prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:PBMdx0tk7B1Z90KAyA==,iv:JFdhVHnnZ1NV8LvdW1Jo/KFgDkVX2MjM/+h9oB3pQmA=,tag:bfvyWxoQ2qub4kBjA1CSmw==,type:str]
      value: ENC[AES256_GCM,data:/ylr54mbJO4jNeMoaPld1xglPU2lSvkhO+eqdq289rWDh1OXl4g6G5RjapQ3RSk11KsedLJLPCgDDv+ArY3oTixe9iG1f+EpDcAm8nHfYnGahZsAI8NUYzriTYNlDrA+RaZ2FRYJSgNZlM9F34DHOQqMwaRFoJd9siziPOyGtXirpFU+3ZgX08W26J3XJaXuGr/NqMSf95rkAGZCRspCkmb0QjZlLxWjyFZbIff6VxJqeQ==,iv:2oDzsUeCU1EGktAQJlKn39DXZbSvZweFZmPhSk6Xe54=,tag:4a3vvb7ANmhTLQSfUslWLw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        Gm2pjLMUB9cj15epxYJQqLKI8oobQzLLTpSf9yAEyKxzvRNu91C95lE9dtLXd92m: ENC[AES256_GCM,data:XUqxyLpuagNDT1jVbsIlVHM3Q1fwCeQAxvq2k61hUrsi8F6rMmI02XQ0Dy9aJp+HBipXTZp4Ny6SxpG5,iv:UfiMPw2AfakFanOxINbJekp/+Wg9aFHmhoN+mHrYw4A=,tag:S86n6FTz2FsLEn14QULbQw==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:5SFiHQ==,iv:b8ARSNOO3/M6gpRHv0QUoIxF7h7mya1DQ9ZQE4yWf54=,tag:P/GKkjpvecSqodmDwaagNg==,type:bool]
    username: ENC[AES256_GCM,data:yV5Hi4c58MZzuKapNvq+D62fIeOLOGJ/gJTLyvdli/hHJz2JACml3zF1ZuxDdn1uhZI4SaicwgmkgCvlfWLEZg==,iv:PkaNhPg4vMVrs9vemkA/hzbv2tS+bW1SKBV3d1YhIcg=,tag:xhxxh5my7jzGgVBwsmYDPg==,type:str]
    password: ENC[AES256_GCM,data:L5jOMRoT/znOf9vo20IfLAsAx64Be4oAI7aJ8XysdRa1zAXhQJlhHFE8Lq25TnYMbyQQdhrCwh/Mqa4NfVRhlw==,iv:OHrRM3u6OPiHtSF6ihAIql5XhAUNUua2H/hkIju1IO0=,tag:zUctBWNCRfukBhwQynK83g==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:uOtBdl8ifBvpGmFoqurO0fjBjt4/JcgW5oHHOcPqGjetylGccvDvI+XmK8G7jWCksFb91rvZjGoubZNJzAv38Q==,iv:p0GL7i1Sl41M+dZUPC3m5TiUew7Q6STI6ejK5iWoVIs=,tag:2sN/yXlanbgUyZ0HNzIvdA==,type:str]
  password: ENC[AES256_GCM,data:E3XK6c31qE/K+T7DKOxvVRSKRMDSxAdAgLdWVwqULbe1XPJCfvMecDkLrHywa7+ak1FYbrXtH/+h0XTqFW6VPw==,iv:pAeVEnQ5sEFLZUJmFwJ1E0TIKpt34IH5RsZ8mDfP4Wc=,tag:x+x3Ua/gcRvSOIXHX0pqxA==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:21:20Z'
    enc: CiUA4OM7ePQGXNOiLy+/a7SCUR7/HlkcjfbsyTosv0CKC3lSTdQtEkkAmy+eknbknz94OmzlR5vLwdg2hqE+1Nv0U/7GS6qYMFHNrBi2gQ1JHcqgs8AGtj0x+BarCT2dq7er5pA6m9xpRmr2gEEyTG1s
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:21:20Z'
  mac: ENC[AES256_GCM,data:upjmnq6Bk9yIzQOFq5toBEQ5HaEoQvbSPUsJeNAQeLfY5MeCkHMEZpytQIwzn+9cMSwBE6FjhB41iMgx88TGPFyNNGzCpglaDekhKrYjcOvH9EaD7zU1Pk6Ydf76MzCW/Uj0II6RCj3jVNLHBeU1itc7Oq99hatdMcu6pXDL8KE=,iv:/+O8YSx0czSAG2uLj1uFvkXhIKY2LUZcFJ/zRP+3rqw=,tag:R+u4bPgVH5wKY95KLY+zHQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
