jupyterhub:
  hub:
    config:
      GenericOAuthenticator:
        client_id: ENC[AES256_GCM,data:vKfCiqlgT6dmLR59+NLfOUpN5fc=,iv:ANlFjNKVSedqXOHhE7HFdc39RxzMiJFJO7kLPZ2NkXU=,tag:K+yyVtgG518FYskVza/p5Q==,type:str]
        client_secret: ENC[AES256_GCM,data:a0yslvnHTLjLuI482GvRZA==,iv:RRrrGME5LgyHSnNg9n7RjdMtVpBI1bpzDldY6hdNtWk=,tag:f4pyZU5AtU+D8mXk66gKVw==,type:str]
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:em03M+a0SUMpknDq2X4HG5TbSJQ=,iv:omarqADWJTythEpaEXGQu7VhEVcUKWgk2rlCAi3sIyY=,tag:gRwxhUEqBZXZprk26z6c/A==,type:str]
        client_secret: ENC[AES256_GCM,data:OESQYWfpJHmFWZC8Wzvcxv8noCUBDKzwPo84U/nzvwyZgi//KWW7WQ==,iv:xG7EAyraGeBTV0LdbBjz8ZB4nmYELUubx1DVFjpZceI=,tag:/fzkaypReunLo+LIHKnXXw==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:JqpnLAPC0ZmLlGnLM460APZzSREH9BC4mv8hzKhv0CjPOJu99/R8eHzj4AUPb0rkrEFaegjGtQQHIviaKfI0b7KVWFGedrivHieO5u4uRIimUldEs/c=,iv:IHguDYve4nZnwlOEsEvfZfz3h/qjQhKy+nF9qaOnhrI=,tag:7dPVM7ayRIdCC3L/Uv5Puw==,type:str]
        stringData: ENC[AES256_GCM,data:P7a9PMhUDpE4/GNJqc0k1PDZPoafgSuCf41xnyk3Xa24oZD2VcuL3bTSncao3psnVDLCvvJwNRzWWhvtlPhcEXlKmXwDp8he8ytSZ2BpjRDTOTcks/Z3nXjMGpiO/JWtr4MbkYehkbLzLi8v6/CrG+NNAMhI1PeKTXHgydiA/8YMh3/QRV8XQKB5CaFfmkALSxoOI7kamB2uGpk/0Z7XbdH9ytLcJTIksV1TFlZFiqKKYcSN4/vj8tySnNWzJ1/yG17zBnjC3+0HfhtcghRopGL4cY3HJhRK+6xDllfTebK0A4Ds7AJRO1ScHMmoRBO9p3td8C3IFmKZ9a/EVrEJAY8Ess4ZJS5zcK0dNjXqXYefCmQlm+djWchFmQ8LmZp9fs3Sq+cK/yRrAA9VpWR6hwFVi3OAWjokvt7Oj7u4JjO3toa68lBtOrW1MVaVYHTGRNKno7Wz8vbdZCxDVF6zA7vlGXwk9w+Nh8q7ZNmcM+8oV0V9uVR5Laqnw5j6xERltd1vWutZgMnPCAYKHnTdfRS/C6xDZUpv0BYmBKRlCdT6R9NKtEsUy2Dlw01O5/x3N+n/JMJbmDBpaAkCyYaJ2rFRFesYdTQi11+gm5XfQUWUr0Y1mmtd9n3/quKDg8CqcTJXv0iP+v0+uDjwIw==,iv:vNlS33tSmVZsxlVpuRA5OAF3bllgJrYJanA12LjpyPE=,tag:IPm2h8lGXlRrDYu3Q31viA==,type:str]
jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:Xoz2w7VK3bFfOvxIMdU2tKyB5TW1B06GfksuYyQihyDnY6eJe79BK+/8w9WZcKXuveZu+JzqWVxtFzxUrH2oolDbtkSZBmUcoWjSIMblRg==,iv:eDXPOHSpeuJGFafRdcBDyjWX3B2J7NSEjKlkitCyZiI=,tag:BWpBx2Uu8Snb8Xov32h+mA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:15:50Z'
    enc: CiUA4OM7eO5fA6c8SaiJbve0lZiWz2/UtPVEk2mspC0b7leJD3pTEkkAmy+ekqNRr/rucvB0sPakyf8AStQLs8hX6YvtPQw8IyTu9BcI4YOgRSIIpWMK0OhhdGKQ5IY9FXaXj1HKIw9D4oMmsBCPsXaA
  lastmodified: '2026-07-29T19:15:51Z'
  mac: ENC[AES256_GCM,data:fCx6ccopqDn3kvc5pH3sNr1SMl/aPIIR2ct7GTYg8C5Xr8Tvphm7GZjsK7E6/Do+eVdfmXkuQ29r2ThTW0Wo50hdgWKNxI86PsCywPHFQ6nHmrbscU2xlDOjExJGlb8QkisqOs4Ww+iTrmvb1H7trse8GulyNFELhyQnhxAxkfg=,iv:3hNub+9Gf7iSlgHe2gPNImslaXAVtWaRVP6zITjwnhQ=,tag:yReq5DB2qJkUQ6oguexSKw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
