prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:VJXINW6fEFfpaq649Af//kzJDv28FzcOl3NOvovPdksEV+u3zhbtS9tbfnr0B1SePGuSft5F3silpUIJKbIJicA5RhMn/JF6mtmVJnQLI9VRBMDH3iUxYpx3f8WOi6myXq+BZ/xFydTOoiJKSTgZlKfCu9PFK2bDRmyei2r6/m1CydO0ji1GF06fS3B56Mt6jZ2lYmIWeIc90xwV,iv:DMfUGh9VizIskMDmfzFo+E+vWxGYbFXNcvWrnmZTIug=,tag:DxKwMuVGc37zaYSu5Gt7oQ==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:99X8ymc3l7AkDdnVLj3zsNnZ3je0R6efqTTM/HB8fbLAP9EFGXefY7xaGeUrHChQSdvluyvhrbRLtrDY99EPMg==,iv:4I/z7Ci50jfycEchB2cyHaCIMBvt39d887QLTDJcbmQ=,tag:sbjDUAykPoghiyDNwJe1ug==,type:str]
    password: ENC[AES256_GCM,data:vlpo27MLSYZPpp43Zw4GSPCkbE9pT09cwox6nN4A2z3mXwgGumS9zUZfpu2B/txTZGh2n/IiM3CE0KEE9F344A==,iv:HX9JjPw6lMmDJejh+z9dF9uPlYH2J1yjsI2J3U7zzEA=,tag:3v6zCBK8Z05rGg4TtRHKHA==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:dsTJn3lEwWNVsIFQcw==,iv:da4SVfcsTkyIOBiySkPmS/oMGtsAilKP2HzxbFTsyVI=,tag:TrNsKf8xHUfNtx+PcIrZQA==,type:str]
      value: ENC[AES256_GCM,data:rzD5q2PkUG3moEiQad+2FCrWjSWN7qd1C+SRUtSwnsKIdzRfp96r5jN1KZiniEc1yRconfaUzlNrptgNAP6bpwPglmuhKtZLGvf30P5NRqaYLc4RtpFH6oGZQ7lAzCKvBvvQ4Jk80bFz+H9vS1zcx8UFdP0RwHw5ZQJcRzzmNE9dpboeD8ErwImdHtYREG74T8jWoqzQKTjqQ/ONXi6S6aqlDiwIS4gp+Anp+gaYZyzVug==,iv:r2fUS9Pkimw/HIV4qThuXIDXAT0mnzgBrCS6OZCQgcE=,tag:njM12htOHAKjQg7ifsRh4A==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:ieEwYtlK0JKScwhwApMopqjuvmG/6c9dPFeyOkOGBuC7UzXb0EXCZdrG9ae9Dzp5b6lmbwwWGPm6zPJ9SLDzBw==,iv:WSacdXN6vxMByl4sVBHnrDb37aBYrwvRmd7z5DKwE9A=,tag:gkeuiu+Pdrf0tWCg8CCCYQ==,type:str]
        password: ENC[AES256_GCM,data:xIcbbarSMr6ZnyGVheOKbsCcBjjsCBBZxyAfk/vowNrv40pjzNsksY0l/EWCVT+OC4iRo42Qsq7bs7fzeX34kw==,iv:puUso4AH9FouKdNYNKXZ6/4FmWrtxkku5V2i7Dhe0K8=,tag:1W8ojCHZXuzI09iOfY+OpQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        Gm2pjLMUB9cj15epxYJQqLKI8oobQzLLTpSf9yAEyKxzvRNu91C95lE9dtLXd92m: ENC[AES256_GCM,data:C1Ynkp4nNvUu+pcRtWiGsokKpxvy/iMvzhidZcVU7ooQJM3XONyedv4BNuEMQoZyO1QR0klzXy+8jwnS,iv:rGnBWGop1LEsWBTpLXdRsgftBiE/qpgUFbkZPz3wyT0=,tag:QiiSBc0rwHaYOD6dN3izqA==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:0Q==,iv:PgzEbdcCKzVuKORJFWTovg8EKiMw7Hbev+w7nTQWy6c=,tag:MNmB6dFNHuZiIYDZ2V1Obw==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:pZ9Ac6WOswFZSQ==,iv:OJb4JYfLWvz7JmgXu3IcbT7LoByQkeSNZvVdXhxKVXM=,tag:frW1QIgNHDqmdsVlfORrVg==,type:str]
        orgId: ENC[AES256_GCM,data:tQ==,iv:xZsIXUtH0xni2Pbvw4e20KzC5IIrxHR3bq0pAnztOCE=,tag:NeSKsV5F3Jc/lDp9GQQh0g==,type:int]
        type: ENC[AES256_GCM,data:wI0Z0u6p94J9SQ==,iv:sc0hUnNVUEquleLPUb6d3/tFio6Ed+PIDHGy4ZSgcDk=,tag:l0XlM8gnUAlbz9yaEU6Xqg==,type:str]
        url: ENC[AES256_GCM,data:kKtPH7aYdRHfX08j0QITevnH7Q0qRPBslK6Fpl+4xYY=,iv:CdnaHyMU2Oz76Cn8ekI8vlqpUuB0QzTUKXRpB3btu2I=,tag:LO2iuztJ2XajiSgyUBk23w==,type:str]
        access: ENC[AES256_GCM,data:5PhXYCc=,iv:odduQ5P/K8v6HIpB5OCwH0gbkltjMn4OfpQR0t+BP70=,tag:KWTpOJGxG9NKmSqt4EWjWA==,type:str]
        isDefault: ENC[AES256_GCM,data:C7MOwbI=,iv:7lkuqSH2E1Rq36c+nJHOOcKYpOTMvt+htvktJIDc3+8=,tag:bKrPEVFmDPytKUmTCCeZNA==,type:bool]
        editable: ENC[AES256_GCM,data:SV3iJrc=,iv:6Ywhag9heBTtVMhHeULI+b/S/zpRY22+2pXXVD1Y3XQ=,tag:w2yqCCrQ6ZtyT4fpyRLTYg==,type:bool]
        basicAuth: ENC[AES256_GCM,data:m024bQ==,iv:u+fX23l3KjMIgnSHnyphMBqNhpEJQ16heUXnCLgNG70=,tag:lz5ik4C2XBuAFX5EOIzhLA==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:BDQfxCNaa8jHnQl3sUENDtTe3HSY/5xkX6ycpAkoXd+R7ieqPdHfdkO4PGviJeDkSSN7KDwWwnEDyej1Dhg34Q==,iv:YM2+ZQBxGSoKBBq/zZorsMBxM/yOU2aTLb5bUHpiOVE=,tag:zlrRQ96iNt+zTbJA5S5rfQ==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:cgTB/rmJK1/VvuzZvZdyhoE+lBdO6OKv5sXRsgEPEkK70nPm2P5+Qhp17aoji8RvsXuxuINcyFZY+FwD6NQuzQ==,iv:CNZAXaj74V8DTeBJqB3vCm1dpN9cH83bAjD29zbmSWA=,tag:t4huOZT0KA1f+FWVAQwTzw==,type:str]
      - name: ENC[AES256_GCM,data:/UxwfptIOibF2q4FHg1RL56M0USapCLtj6IKbe1umw==,iv:6RQTqWJ8u9pEo1OSfpA7/58DD65qoOqm/y1Uk/SfBSc=,tag:KuW0Yh5Bh60lvW2sRIXpCQ==,type:str]
        type: ENC[AES256_GCM,data:jWcx4JR22Dos+9mHKlDfYfzXqfH1VhTpj9tJykVE6g==,iv:U0lRnwRKJpjCxFZoDNcqjpgiPIkXsYrIkrnsk6MvT20=,tag:nEVq0ue2kWUu28gAeYRhaw==,type:str]
        isDefault: ENC[AES256_GCM,data:DDqNqU8=,iv:xubh5r5fXmqKm72MuI2N2DR48lGSMrkpvtwUoViTPuw=,tag:nCQpDrdK+7EKomIttD16+A==,type:bool]
        editable: ENC[AES256_GCM,data:N3Ynow==,iv:tLQ5T545jLNB0/myU6Bh36lhVRZwTgRSDBelzGH8nlM=,tag:k68jNXZgwDEQ0PMVF/tAfw==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:ccXPAg==,iv:rlXM9A53iO0vPn2voO+0goqWMkYo4FKcL3bH5+aAyEg=,tag:KDpHI677c6NwuPeo/EgddQ==,type:bool]
    username: ENC[AES256_GCM,data:G4AE24Rh7xDNvP7rsuGnKXi6e6YhvHEbxtga54m7gx+ZgRkBFDc6UD0RpyHckBNs5t+ANbz4NIoAOyv7iQvY+g==,iv:GsbL8dV2HF7SU/qZDN/sKMOSI0IFNQrNsw+hlM2IfVQ=,tag:KHn6qC6RGASiGWFLt5dPvQ==,type:str]
    password: ENC[AES256_GCM,data:57C6Nk7k2ruQ7wnouVfdAOguBO4JS3tsvC1QsZaq607NAjjOnoWYMcs2wA0Y5s/n4RS16wPrCfik5ahT95+SZA==,iv:2veypS+N5u+A8Dqk9WcTO4SWD8qAyQeAxUlSSg3Q4/A=,tag:AMame5bZRQ5QrzazEyfKlA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:16Z'
    enc: CiUA4OM7eHVCvlH7zfUA58ac7ohQZu/LhUfoDsc7T8Muog4wU7IOEkkAPHlbmdF9RBesE5/XCsl3w243yMYsJvtafE/KuSCmGANkLCFKqIJEfdBIqscK89pbUlLBRDQTr6Pmcw77Oj50uhVjJASvbvBf
  lastmodified: '2026-05-01T14:40:16Z'
  mac: ENC[AES256_GCM,data:J70CEiiiDXjzA9EVQTTFeIg1eFy9eMOMGKQSgL9YUYvVHb6K2uf4Za9eFELCaKUU5OgVcpuKlwliGstwoCfnRpGbnALZfQ5VY68J2WG6Z/CuRK1S4V895DqmgID9FBtCbRuTfbL+1OXGBz9mXcwcywphKkqg//icNWTMEQKGr+k=,iv:E/l8pbk0cJpKVCVyrnz65OMKyinWpw2B26ixCoyEuDo=,tag:+JLAnXyj8uuL7zZQdfyL1g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
