jupyterhub:
  hub:
    config:
      GenericOAuthenticator:
        client_id: ENC[AES256_GCM,data:+JiDAWkRHsXmmNqQeD3gB2cUFPmB/lyYHhrffg==,iv:/9pl0dJ3Cq6qpUQ2HiAniUJfIAG3X5iwJq1/wS+UgrQ=,tag:TYo4cz9HIbN7UOqOuXkC9w==,type:str]
        client_secret: ENC[AES256_GCM,data:KGYl0LXdRSqRllgt4ZwH2A==,iv:3jU7G8/dFV0d1R8w+2cd4ynxrlg9BcbvfmBGQB7VFUU=,tag:wnEb5/pYIQpjZl1ngJTCsg==,type:str]
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:viDjax0OfolJ6Ze0XxFQK6KE+hg=,iv:OXNhvj5DdgBvdWAe5RmgGcP066DoHH6ec7942H2+UAs=,tag:cVan9kMSJAJNd57d0r9+tw==,type:str]
        client_secret: ENC[AES256_GCM,data:0gWQq83uIG5qjUWe58XpABjxMWe726mdp8tDz43XMEFb9IAK72dyYA==,iv:8u5s2y8DZqfl21U2DQh89xKhqOBGiC91X+P1Z9z23MI=,tag:gg+hBGWLPKRRLX9YQawF2A==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:1WzfuRFi4NAvgEa2QAvK2UdBHpnRSh2v9NiocNRj2+3iVOqJfyWOQFPpsqUb+eF+iTkH8mSPlopCisKS93wombStx832ajufYjRSOyAQJQ6+yAErU1U=,iv:6JzFjIwiTZk0ACcklXg4NxhjtSgrn2sdkm4UtThkfGI=,tag:DCEbHubnLvVMy330OrC0KA==,type:str]
        stringData: ENC[AES256_GCM,data:F2Hzmto/KOFCdfUr7bPGwi3tK736WUmW3/PeDI8L6d9PyE+EgWF2T9wSnnbP6khURXxoPIFd4vH9rIh5fMdZOz140uieJEzl9uu/hOCTwrr69v1tFu6EnC9epCI4Eh9Ly5sb7v+X0NGX7w8pOOzKNI4hDuYXYKkM6dtaTMdr57zJ3WQX3yNeW7yVXDUIwNbaDP4smfDpevxy9GOXGxUj4pD3DiqZ37AB9NoZyvCLsw7ENDYekhapoSdB61Yv4CVZqcci6FRQWml/1ySJmAdk8Lxc5VipzE5a0EHT7NwyAlZ7JS16qzwFXFsxSQAtLwmYHbK7u3UcP9F/3jNFV+iI8Cx3sMW0qNOboCBkxPEhdG5Q7CWuRVl8h55g7sG7aVs0RMP47nrjFcNB1Det7cYoDKHnCUE7X/50jsfMLGCLjKOFzn8AhIWt1FCGTrNmP8d8Bz5xTKd4fvLpB8x7vvqjxeA12Wj/9uPnSDx8LoMT65J32CuhYTLKV7/G8lOVcE7csrMw+QdyKtU5O9YuAUsJTyyWlpvIKpknJYQamRqAz5CCRZ8iy5gB2QYPJHTRH5Tchqdor2UGlOBzj0EWr85apI2CgX/UF6oJTSP4+ImLH5ExVvySh7V151FY4tl2Jb3H6NgwKihJPobRrW8/xw==,iv:UU3yE/feSyOuVcXl/1sog+dsah0Igov1TnfjBMsT1JU=,tag:ZvTYq5yQhwWXvu3IzGmxvw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:15:48Z'
    enc: CiUA4OM7eFRwKGLnoR4/A1VfEQmwkt5VO9fiHIp7MwHdZNrYxeWKEkkAmy+ekr0BTLhoathiSbBGJiLk5UXltGVeqeqx8R27kkE+Vr8U0Ldu1AiYirzTNGda1v3HV66xWlGKrdW/RcsFcOt/Yv9OnIM3
  lastmodified: '2026-07-29T19:15:49Z'
  mac: ENC[AES256_GCM,data:22bsrfxG19cAusOPktcs8/IWY9tdDKGNa9aT00gXV76sfW8p+V6SW6O9WEFawL3R3Ix5AO5COmD/ez0DIjBnefvZKGFEbmcD5Lng6m74j8KDE1fP64gOWcmHozPpmxRNSWVAbpBtO40K3gj5pWY9MPP+ANscNpCrKxadDJv3Yh0=,iv:2rnOlLdvo2VuO/6V+xq89Yz3afDZG6842GY+zhppvto=,tag:h67gPgbNJukMYuGT3a2kVg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
