prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:FdyEL5EEsafvfS55fA==,iv:oGdCcZv7TGDoO1YYsw+3A6LZs7D+F7eiY5mhIWwDh8s=,tag:avNKD1vmEbxfcrmw/8GLDA==,type:str]
      value: ENC[AES256_GCM,data:iwtiqKuTeyLeL8qCHI/ig+K8V/1PfhpEthQTXwSYykLoQM/b1mTb23GiOjM0ZFAHZ0omd26V5LfLE6yn0xfI908aeWA8+IsiEgT7e+J4HqaSCPK/T8Hy8JV3G918km0M8brefWJDPEt4bqiTDAkEl6rzVXEeVFKBsdRhmCX1uCms0Bjj3Egno53OlNP6QSMHywkJZop5Ohp8gHdtwlAJCBXBOwLUkQvYZEfZXTg9Y8H+kg==,iv:cVYZBbuMgBqaTDT9m5O7X+3JMeA+6ppoGlUTqRl2apE=,tag:vAV1dkrc+rY/f6ZBGWb/LA==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:nxWLiO88a9tpKT/9Hu3lvPeliu29iPanpcEGhYgGCiycMGIw3I7iD5OkgbcE6ft/Z96ucdTwaSTIsO820UKDtA==,iv:HlGq9W47JN0QZsjvbNDhCtVOX1nEIWwlgT9PJxXfxis=,tag:sTYmoGcGAqdv4dkTs6cXTg==,type:str]
        password: ENC[AES256_GCM,data:oC1lcQYwOc79lPy2tqhAmWUbb9YOjeDTqaSWX/eskQDZmNglH/NKQKK3SzqMkMVGtIknVg0hgKIvj79ipJCHqg==,iv:3H9GobGe+Lx2nOtKXe2TmrShdADmyk7ksACfqIyJ4vs=,tag:bJkGBImqgjvkVbQzWKYL+A==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        Gm2pjLMUB9cj15epxYJQqLKI8oobQzLLTpSf9yAEyKxzvRNu91C95lE9dtLXd92m: ENC[AES256_GCM,data:QYmHybUN+beBphFmNQVpj3z3SKoSbP/1S73lh7kq2VGO2VJf3+av4tAejXc3TrF+z8/90AHfgh50YOoh,iv:yh7E2EdfP/5mAJFjW2QgMSi9BFKNg1GJ+WfJNavDKHA=,tag:6Ajv7WeeAoLzbeTjZ3oQEw==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:2w==,iv:9C2yWnk3shpiMx97w/tWVEw366NIt6ab8B42dv8Dig8=,tag:MPdI1ikAv3frGse90v55BA==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:lNu0SzUdZWDwaw==,iv:UPxjqCIQhr6EIwR57GlrsN+eisF71Hq4ORC1TQA1Tjo=,tag:CQY4Djfgc55rGdSk6odiLg==,type:str]
        orgId: ENC[AES256_GCM,data:XA==,iv:hDRYUja54R6X7R2+Kse2uTf37vh9dxJLO7CFOoTTgrM=,tag:gp0Tj44TMWzUWiP4MN0Vtw==,type:int]
        type: ENC[AES256_GCM,data:p4vUU3XVI8bQLg==,iv:44fVYxiIjcXMMJVo20FEGi/QPtfDo2dPSJN3Bdn68Fk=,tag:6pli39Htyfol/hcUyW28Rw==,type:str]
        url: ENC[AES256_GCM,data:YGjnjbk1WGY5sEiI/fx5dPMhXQErI+rsT2lnHvhaUOU=,iv:DgMpbmcCj2SnW12W6AetL+xU1GIbL9dgO8+I3qvNNnc=,tag:90l0TLcaMlRnlsQ0mhbaVQ==,type:str]
        access: ENC[AES256_GCM,data:UP7y3W8=,iv:lAoYsFGlb74e4GZ28o8HGwmNyf55wuA6e0k4uE/iQ6c=,tag:lbkQacdIkQkQOiYki7eGDQ==,type:str]
        isDefault: ENC[AES256_GCM,data:5qOIV0k=,iv:BIvqnkb0v4N0zUjbYRy2J59QKIpV5IlK6x9GV2jSihc=,tag:9rghBMcM34bFBsyiFPF2JQ==,type:bool]
        editable: ENC[AES256_GCM,data:Ep5v5gk=,iv:zri6TtmhwNCoQEvDGDbVbm4GW1facGOlfm3d//9T4js=,tag:KobdrVrknzvkKUfD99Mekw==,type:bool]
        basicAuth: ENC[AES256_GCM,data:BpHKbA==,iv:P6sMjs4WLtkbEevfwa45nLXFeDOC7hVRrtEsGzc612s=,tag:0v9gJLm3+Wd+XxGNSe6euA==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:dg2lrYmu6rBJnoQQTc+IGdKPfYYEF3S9MUbv3UEqUZ8eN6+b5qGnO4/z+yvNLvTqoJfoEd9QmYis6cnioIp/FA==,iv:6YLCpMyGMHHHr32Fe6xwGDJIYQ+X9GTPr0eQriFCvMU=,tag:eh9hlohyAUyUgEoyR62NJw==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:ZNaUxB1gth8qi1y0mHol94xy2eay5/1IsS2JAFZOFbwO7T0dKhff6jk10B9X2xg97Zl5+8u7XrcpWJZRD6EqDA==,iv:XXjogKT3B9Pk+CGrwn0CmB2aN6mTX/kBTiSUW3Jzh4o=,tag:46qCl4EawEFBBp1yHrp4GA==,type:str]
      - name: ENC[AES256_GCM,data:YiliDBUQBRm8+m0RQF0aNglXuoBhqc0PvwxT+tSWZg==,iv:jLpD7qGjhdOk6/oLNpEQ0+Z6il3Um2POBXqoG3183MM=,tag:JK3J3/RVnC7fQkkcKDvC1w==,type:str]
        type: ENC[AES256_GCM,data:2HS0UNqEPW4j7msmG4o5rGkF7NDmF11Lwpmk7lTSfw==,iv:xslNgwv04npqGeR3eA0l5QqkLWEyEz6JxagJ7G3IAYI=,tag:0xH2TmGakacoCVNf0JCKNw==,type:str]
        isDefault: ENC[AES256_GCM,data:txUVkrE=,iv:ImM06O3wYrA/8hFInlZqZFzGv9pr3UpaZgM7pM6TSak=,tag:qtcv2E/2gMvXgKGMOYEV7g==,type:bool]
        editable: ENC[AES256_GCM,data:OSnRpg==,iv:rJQHLNb97PB7UrhG0aMFfpS5tJmTvi+2xcb84zn4SeI=,tag:ckNc7J3mSZRK9F0dVzSNBg==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:TKz1Tw==,iv:5RRgHSRlKMitob4iFaSzkEnkQM7g6YVcZ1WxTpwIL5I=,tag:+E+joiNj96N/WP2vSxoEGQ==,type:bool]
    username: ENC[AES256_GCM,data:88W6ze/GfWqjYhifOq2l7U+bPUAX3D9VzCPrPub//nQXiGEg54nhCzlB3mULvBPGUZUsRQQ2akz+xrMAIguWPA==,iv:nhtn5dAonfTx4pSM7cgIh0zr4YvsRaCJiv1qPOD97f4=,tag:UO9kUpm0iOV01IDVM1ShwA==,type:str]
    password: ENC[AES256_GCM,data:oXgnzZJXWOjEX1OhFN2eKH4Id8KPkLbMtAiliNyZRqJP7Iul2ABdqB+nmeMBc3fNBZkpLV7yYtLJ1qBB/SNJhQ==,iv:BnEdywgLCzfq/pS/Ue8gIkI4ntQcqFbIpMg+jnNwkjw=,tag:RfZjf8pIJTpZNEUvZ5U77A==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:XFpDgP28y2ENmO6FlYd1nK+9GFFICTJgD25qigT4utMaSL4TsfqbeYTmc6e5iphgI/p/EwNbWFaDPuhjbWYcpg==,iv:HqcuF1b/PoweRAiV4vhupnLepO8Ivp2ukTnlntRkAN4=,tag:tHIxcFT9M6AiustthuyNsw==,type:str]
  password: ENC[AES256_GCM,data:BnFPOU6P6mdlhQlDK1xOFSF2EFEAko9WMWZ+lmHQT7nv/KWMTpp7DAbr0qDAkcw5oEzAok3Ko4plTrE9M2p17g==,iv:srLvryVyW09pPw4ybCD5UpcWpCYVQrhRQ3zNA7kzI8A=,tag:N/Af5Lkw62NrXXKhEuGUNA==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:10:41Z'
    enc: CiUA4OM7eJDlypk5iY27x6bM/doVrUgXuCj0MvBgOeYEDf3PK2PNEkkAmy+ekrz2VHHS9HbUgnCpASUt7bGHrC/uXpNZB/97Eo7sQq/wrrbvanpNSKsZvDR+A0iZrv0ZB/x/9PoQjiD240YUJV9b0VTb
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:10:41Z'
  mac: ENC[AES256_GCM,data:BVRfhJeTxGG5sKBwogNCI2YEVQeCkqgMjrAQtEZr3sz2+F6VR+YwTP5jUz79RlnpRaBc6wVC2jtV3w4EDoKF6wy74pfO/3bI0PdVvdKsDgyZLX0VyobPi2rXrCsLCiRAMA+ypI5fQkdbCmUus3pJVALok+iC8DkcXLj1hF9koeE=,iv:NOKrF5m4ZiwKFY8hoeFhTt3vZrkd35//qc0chQpuTS0=,tag:27N00q2JeAlvBYxi6RvEow==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
