jupyterhub:
  hub:
    config:
      GenericOAuthenticator:
        client_id: ENC[AES256_GCM,data:brdFofEojzAK2lhcQBzuaxSSDfDEOmL9eyTjaA==,iv:cCmCVBzmgP3+aaohMsiH1J0nKg5KXT18VLXsjeJQSWA=,tag:gSeN6cKjGV3i2yYw88CuCA==,type:str]
        client_secret: ENC[AES256_GCM,data:s+LplGR5wgaZ5knMSloKKw==,iv:+5Wx/K1Qj7boxZPNtY4ttRRAhAHFbacdTWG6/rweqVg=,tag:sMaM/Iw+2y76JSE9jiYXfw==,type:str]
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:GbLiW8Ef8NRtrDdid8ea+CcfZMQ=,iv:MIWiopg/D7oPFuFiXmZs7jVZGTHWymS3Lhgr8NWxrcs=,tag:nyE56wmEH+DcuLFUWc/K8A==,type:str]
        client_secret: ENC[AES256_GCM,data:AvuO1x/tSoTFgPvTkaV0n3rg57CNyoElOP9oWzIlYRTL4mdFca910w==,iv:67pdCHbb6EaUjEqN/waeoLOg7yEjQ89QEx+UKLM4PUs=,tag:4Eyxa6Rn480epWMdhGa0mg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2024-08-28T17:11:51Z'
    enc: CiUA4OM7eE42MAnJnSRbSgcixhYQanLcxwpkon6oodvg2vfsHlPuEkkA5dG1Q+XBCcm6hV3EDD8c3e85Wdjkcv5CgftsEAzTcvFNGuijE6dUcPxi8yRhjELV8cHYPOwXuFUkdlq3L6LekDrzZoda9fjH
  lastmodified: '2026-03-10T14:25:04Z'
  mac: ENC[AES256_GCM,data:wEJLhpC9GmKlUTQaKPhDHgzfau2TnxAn/As60NMB5l+G79H85ildjF/HMnBd7hSsVYvjLLZMHe7ZRrnJhZGUJgNR/32KaLzocjcBlBQHDKU511QobEfEM2tMNEnwm9IArhO1xnM/mH64G7/XWdbAk570f0XG+mbai8PYVteRPRo=,iv:uGAT3nA8g6i4lLnvW5VmOtM5EHMjSqywpBpxIRReEMk=,tag:OG6GixggqLjl0hLiMO5GwQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
