nfs:
  pv:
    serverIP: 10.100.150.169

jupyterhub: {}
dask-gateway:
  gateway:
    backend:
      imagePullSecrets: [name: image-pull-secret]

binderhub-service:
  config:
    BinderHub:
      image_prefix: quay.io/imagebuilding-non-gcp-hubs/disasters-prod-

jupyterhub-home-nfs:
  eks:
    volumeId: vol-00174260142d50e1b
  quotaEnforcer:
    config:
      QuotaManager:
        hard_quota: 100 # in GiB
