nfs:
  pv:
    serverIP: 10.100.150.169

dask-gateway:
  gateway:
    backend:
      imagePullSecrets: [name: image-pull-secret]

binderhub-service:
  config:
    BinderHub:
      image_prefix: quay.io/imagebuilding-non-gcp-hubs/disasters-prod-
  extraEnv:
  - name: JUPYTERHUB_API_URL
    value: https://hub.disasters.2i2c.cloud/hub/api

jupyterhub-home-nfs:
  eks:
    volumeId: vol-00174260142d50e1b
  quotaEnforcer:
    config:
      QuotaManager:
        hard_quota: 100 # in GiB
