nfs:
  pv:
    serverIP: 10.100.200.179

jupyterhub:
  hub:
    config:
      Authenticator:
        # Disable for now the authentication token refreshing
        # https://oauthenticator.readthedocs.io/en/latest/reference/api/gen/oauthenticator.oauth2.html#oauthenticator.oauth2.OAuthenticator.auth_refresh_age
        auth_refresh_age: 0
dask-gateway:
  gateway:
    backend:
      imagePullSecrets: [name: image-pull-secret]

binderhub-service:
  config:
    BinderHub:
      image_prefix: quay.io/imagebuilding-non-gcp-hubs/disasters-staging-

jupyterhub-home-nfs:
  eks:
    volumeId: vol-08f3d124fcfd518b0
  quotaEnforcer:
    config:
      QuotaManager:
        hard_quota: 10 # in GiB
