prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:AM8v68a3WpjwTPw2Hg==,iv:FeB+MXwfNbrhKpJExaBSlwptHULZTj5hp4cbVvmo0xc=,tag:FMzaFf3NJTjZB05qozQrrw==,type:str]
      value: ENC[AES256_GCM,data:WoVaeHw/+q2LH9bIbsG191Pgn3uGjgsZ2BQ+JtRDNbSlYsqBAB07GM8Uzy8OYfj7mXDJHPvy9zKwkGemUvhitg2sB39y3AldPCayPTRmzwCvkmQrvYjPKcaWkJFb/bYuvoA5CXRy2Ar46JdxCW6Yjn94qi8yimhhNv1MMCJWmbv6Oc9+oa1CedeJQ/qz+/DcISv7XLgWKSC2bLOQF/arCwtvXFqqqHp4cqXcrkQoQVzXaA==,iv:j2l2C9D3RKpoGJhOP7hsjbChftPAO2yVucI9hZuZHRU=,tag:wXso16586O72dq45u8gt1w==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        QTPgQAZ1ZvZrSUY18vSTMmdLHZTCPMfqOuPOqbnQCZ0gOCERQJTIAfgQSgTYyqmI: ENC[AES256_GCM,data:c6PtN0WbtK0a1PrIvthPffn0PcOrpFp/GIxYB8vpSvhxoH+CSpNOlY6fqVIuJYn3acmKKrpYTujfgBzf,iv:Ln91QLkUJ6t/gauUDB4fHoI4KIxT2ifkiCRA4+H6zdE=,tag:O76ZxuH5O3ySizyv6aLuEw==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:RV+6RMlwBnozr8vJYf5zawBBjU6Coj5mTVjns+/YWsOXB6eV4xB1l0A4B+jfdc95mnZewk7fYOZCi1GaAtlGqg==,iv:fKgDuWVs8QHmd27tlnwuZ1z12w+vgFf1GJMXAv5xfos=,tag:0s4y2j/xrPPIv8EmDswqnA==,type:str]
  password: ENC[AES256_GCM,data:L/5DBahURaZjP2G+EAugFvw/rW57qOqCLjNMJ+jnwbGJJCXEJ7TJQBi6mPRotwE0gFSmb4i/KzVhhMB+53QYBQ==,iv:FfxngrNRAGmijQOp7wkJI+fj/FZZYLT9Qe6p1zR752Y=,tag:b19FRgPhvRr3BfEt/WvIQg==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-07-29T15:01:31Z'
    enc: CiUA4OM7eCSys+tqhwlogwqN4DrKK7rVhB2kAj9yGqAQjUK+oSF3EkkAmy+ekl8uRgvhAPzBExORM0VmtdLYdz3H4jjszt5TVolUTn51DM8LQ0HGHkFtW//lWnqXJ5iw7osJAp0V4beYkkY/W1+3Okd/
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-07-29T15:01:32Z'
  mac: ENC[AES256_GCM,data:Bd+9NNgivrKzfGZ1EWedrdP49FJJDxtDIyiKdON/dB4Ayya2Y2bjo5cz6MO9z2dDjbkJXRurPpdbthm0SRaMx6N534o6k7FzUnbwAOKocFxyg9pPVvzEgB45OyCmKK5REDhkrTuMdma380tJ3EiVTuU+7p5xcP5S/JncBjIZAzQ=,iv:Lhl0Yyh5RDysLenrQ8nYOsKTzGCyMZVFQX+oomLGcvI=,tag:JEygI0Zc3kYTVbVYjmFUSA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
