jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:3T8+i9TQnC40iejZE+Dn08H/2oo=,iv:aMwFnSTCpl3P8pTHzxKMHS/dtP4wAMXhX3TyMFbSh6s=,tag:eWpd4WGOU8JkuHN0SSdoqA==,type:str]
        client_secret: ENC[AES256_GCM,data:QdwIeWDKB/reh66/x/mb1zWYVIU0cg3R4W+5HJju0+JIKIStkjnC/A==,iv:iCmv4VnQVbkSi85smpUOGfhN+AA0L6mp2Xm0JiNmj/U=,tag:8jLonYjTWiBQ16C7jSPgYQ==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-07-30T15:58:36Z'
    enc: CiUA4OM7eEPR0hh+qFqW8JDIgBsr192Jomt9meVXxbfhzJ0MEvWSEkkAmy+eknDCpDCBo6vK/4zeoBQttoWkwd24RRFNRJSGgd7DfI3Lz0620PlI4u4ejcZRERP6OrITf+xP80mHrdjnOmqHlpqcdx45
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-07-30T16:31:43Z'
  mac: ENC[AES256_GCM,data:XCISf7o6ZrjRyWBE0nRkUZk2CpmRUNSG8hd9paHgYDYQMTmHcFhI0HhHVqppi65mgKDRLjAKSe/CWu+GN+JHmfJw4rB8wjfyMDfAPkSQI7/0gmsOmU4v8squnbwNUn5aUboSxQxdoKVFF1jZC113HmKvOdzHgOd2FsbCCGH9Txc=,iv:Qk3qgSTziQYw1i4VBXtahfkHzjJwDKLzxtGvrqtUVg4=,tag:s8NYrVZrx2Pgyv1+yOVFZw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
