jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:WMofT7oDLFFmfwDHjXZMy5LexRE=,iv:7qMeCFR73sjFT4D2ZyVQ6RdqcY3eW/RceORj/DE0Byk=,tag:vG4QzU3nmx8Eboej/tKtOw==,type:str]
        client_secret: ENC[AES256_GCM,data:aoWF8+OxZDC+5o7QHEUUdXRQXLe+7jZ+5hXyf5sKV7wa/3BPzLrnoA==,iv:d5A3Wcw4Vmq0bXDAN7pV1u9XMSaV98jtQQYTo11uzH0=,tag:WI7Xlz2ixO4NJzwRWNMV3Q==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-07-30T15:58:36Z'
    enc: CiUA4OM7eEPR0hh+qFqW8JDIgBsr192Jomt9meVXxbfhzJ0MEvWSEkkAmy+eknDCpDCBo6vK/4zeoBQttoWkwd24RRFNRJSGgd7DfI3Lz0620PlI4u4ejcZRERP6OrITf+xP80mHrdjnOmqHlpqcdx45
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-07-30T15:58:49Z'
  mac: ENC[AES256_GCM,data:jQPJQaUGPns39yI7lQeqPZmNf4vSoXJikBgXeitUrksEND9+21IcMRJXKj3uDEgKs5BoMedUyNnyp48sthNJmFINbNDCSkN4/7WhNm3xhDoS50yBgbbiUz2fI4TnU4dliwDG0v/AcHFzsoLC2U5/4HlqdODBC+3f770EO6GA0OM=,iv:wFhl9DexGIrKR1JHzEFYtA325Aql/UXiJB2rGWiTSEE=,tag:YQfUXlpBV2tq6dKW/kADdw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
