grafana_token: ENC[AES256_GCM,data:kzvxi/3NnHQHvqptIq9rx3MjyGj2QE03mzDlfhn26cj91O+NkL5i/uIZEaQDlg==,iv:NU4XgF9EY3ObpcXH35mP6pDRdqnNuvepSNu5wgoYM0c=,tag:bbZp1vhXFsO7vo04nnO1gA==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-07-30T14:53:20Z'
    enc: CiUA4OM7eNYDzdjafDnC6c1Eian8twlsjpKwxQAJViZ4MvrOGKvCEkkAmy+ekrO0ewBY1EmkJ6Y5R3KRtL5RuByAQwmQ1UotLYXWaQC+4z1eJxrEcqRbBkFTVwPHLivv1d4RgdGW/RkQpqfrYaPReVDB
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-07-30T14:53:20Z'
  mac: ENC[AES256_GCM,data:Zax+Ve6pOnNvBDfQC/Z7kfZ85SLwnfymq0jAvlqGBoN2GklxR8DncE4o51Ztlag2pdVMpTZAB9M1R3wfyI+gNLJ0QZ1N0ZL5k2oIlDhDzYUfjUbVnt9sqDyXlvQ5fcNkrLVZcsm0KdHkQkMzCN9GDMzSbIbFr6F/QCL6kBH9om8=,iv:Ji3SaGpmCFSq3/sB1wjFXzYKgbkObf1MNMMyk5BwYPs=,tag:AHTdWiuzB47DQst+82GItg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
