{
 "title": "Usage Quotas - Experimental",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hub",
    "label": "Hub",
    "query": {
     "query": "label_values(jupyterhub_memory_usage_byte_hours_total,namespace)"
    }
   },
   {
    "name": "username",
    "label": "User",
    "query": {
     "query": "label_values(jupyterhub_memory_usage_byte_hours_total,username)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cumulative compute usage over the last 30 days",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GiB-hr" } },
   "targets": [
    {
     "expr": "max(jupyterhub_memory_usage_byte_hours_total{namespace=~\"$hub\", policy_group!=\"\", username=~\"$username\"}) by (namespace, username, policy_group, window) / 2^30",
     "legendFormat": "user={{ username }}, policy group={{ policy_group }} ({{ namespace }})"
    }
   ]
  },
  {
   "title": "Monitoring - Fail opens",
   "type": "timeseries",
   "description": "This happens when a user server is allowed to launch when the usage quota system is unavailable.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (namespace) (changes(jupyterhub_usage_quotas_fail_open_total[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitoring - Denied server launch (last 30m)",
   "type": "timeseries",
   "description": "User server launch denied due to exhausted quota.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "changes((max by (namespace) (jupyterhub_request_duration_seconds_count{code=\"422\",handler=\"jupyterhub.handlers.pages.SpawnPendingHandler\"} or 0 * jupyterhub_request_duration_seconds_count))[30m:1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}