grafana_token: ENC[AES256_GCM,data:xouPHaXgmc0CgvrPjeD0nBKRitjGfRNxAWMRAFPjavOxDbqQnj4pD1P036ODaw==,iv:dV0hWbdtVSM2UJAl8aDxUEAPShyL/hIW3mjVsDIkzf4=,tag:3cowTxxWHdR3TJgWmVZ6/g==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2022-06-17T14:11:08Z'
    enc: CiQA4OM7eGC5PqilEvBdn4ZMfodM+4OmUMnb4Ay1GyEsX4zFU+0SSQBq6cPrCibj3755yvXiEq1fgSa9Z9WTIEkBzQS/vlObSGuWmqB2oGpZ+oBd1Y2s6POXzypgONYrjLecO99jxZHccXfmmYgbLog=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-09-29T19:41:52Z'
  mac: ENC[AES256_GCM,data:DnARWzQ4nLd8rISEbM2RUn7DstY4peRqSDCq+D3um+NWopNKhuItX8hdBPhAlvyp3xinBR/s9eTvlEhuHJ2JNiRwjiiRW6eX4UIeuHz/OxG7iLz/6kPRUM4TYKcqVBAqsoBJ59ZfbPyOMgMlX8MTihfkt+mZmWDwjrd1GhAlStk=,iv:Duu7L4h3wAQk8d9yf9Nsr3WbSG1sHcTyH99V3EZDnMM=,tag:dIodi/HBOfB0pCRy+kV76Q==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
