prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:5NzI30j6WsxmHf3MHQ==,iv:kHYKvrR8DMlTnkgVol2ewEaJ7F064GJLXkmWYQQ9THI=,tag:Jr7y6dFTwtQek/bULUI0Zw==,type:str]
      value: ENC[AES256_GCM,data:OtZbQ+6KWaWfMX3MTBTMKfZQa9ZXisgrbMXP/XpCpuNdxa5FqSd47e7YiMXw/NWR1bFxsCiF6iPklV82NFHfYVMR3jcXEBMPoPwa/H2cVL2gtR4xUlqwxRmtQwwF91fauDVQbWAD6MbW06dRyBwqSepmvYwZNm1WRxKocoCzvrVhbXmBNBZoAXtl+2wDVTG4YFnyTkTrTLl7033OjNqBji02DP8/qWiIZ8jyLZdWfbhbxA==,iv:iGtANB6c+HgF2EkZ9BJkCGUSo1bHMjnEJDa75V0d4rc=,tag:GzSXzAMgBrvcXrGwmPzX4w==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        iBPzc4muIXY7PVB7SLytLyztOmlNIcczE7rRiSM2FOPjBHIpbMLgsEDEl5ckz717: ENC[AES256_GCM,data:6Yy18aceLluRFxvwF/MK3Jt4HPH2DIyjvB1iBUH1Zuh2pk6eGQD0tGqYpZinptXl4KVEYpd1R/rIbFnB,iv:vDhOGR1UwQog8jrY5fRQKGRnBxy5hKiCcGJdNM0SIFU=,tag:fo07GCGGACmnXH/eEX8GkQ==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:GmuQ8MhBPeUbIazzZyAUwTNHrH1qhtPWzr3dJmQNvLN36/FIyWfkZ6uNkcIJcgPXD3ar7mSXQ6X55MwKvwMzkw==,iv:hvxJLi0Jeb5QY0KEyRl3/UlFyUg+14ElcDvjCVvdUto=,tag:Mg2yB8o2EqpTom2kK0+ggw==,type:str]
  password: ENC[AES256_GCM,data:9N0WWzAUFdA7NJAzThT7lJhwEULVR5LsOhaIYLcgiFbLSzoZDLsnV+r4pn1dEp8hIADUQ6IiJ1RQGGiGRPjT+w==,iv:d2tcn42CE6Booise2FXQdbYSb0vTlg36NeYnAIYRaBE=,tag:bgDBaZs/IXXvRSI5MPGFrQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-09-25T20:56:24Z'
    enc: CiUA4OM7eK7+xPwwS78KmJJykmZVkwrxPzN98s79E6ySbO/4xQ7cEkkAsHDEl1B/AGRgOfzVONalaJ+7EmGYncx4nP8nVL0vPK07yV1lbS210qJX6sYr0KvdfhX2BIMOuL5yfiNPI1TEUpyQES0e4YQ9
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-09-25T20:56:25Z'
  mac: ENC[AES256_GCM,data:oCzhw8JquZhQ+D9UwMsnEi5PaI4ADMyUFHkD1ZWl8jE8A+CcIxY5e7inxGpPcm0FMqzEPAD0SyDmP2l/DD+67XRj93eFnXixqB395mGuOOpkNeC+uBtAwMi/fgbaF057xH+6OWpze67UeOTeZo4+HDHFLCmwEqep16lyVhPsK+w=,iv:5EdNivx9gUqAND0S8oHEaGOuDv8+hA70QMn3x1g4Rmw=,tag:aSoh1DwdB22FNKlveVeYGQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
