grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:IQ==,iv:iqhnH3uY/v/4ffWYn7AWvWnmp8do3gpF1+jwn9dkWtg=,tag:dbqm2cILzoTjHimbUH/Ajg==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:X36ODG69sT6l3g==,iv:yjeZiBZWGximHcAeyh234Rcro89qFuWRMofuYuujORw=,tag:pAIhbzsCsIdM6O1rEAX4mQ==,type:str]
        orgId: ENC[AES256_GCM,data:Aw==,iv:sYORPETu1o5F/PwX0IUo6UlUXGd5ZDx8SKjnKtf43GY=,tag:8CHZrx4v0KmdiBqoNEP5hg==,type:int]
        type: ENC[AES256_GCM,data:ZkymEWUBkKJQIw==,iv:VAYyFVuP0f9cC946Sii75jt6qD6ULcx8NOBkMGk6Exg=,tag:KGNeEq2x+GMdPTczFmHvJA==,type:str]
        url: ENC[AES256_GCM,data:b5ofb3tV0w5JCaSR93UZ2PLN7NuI5R/mVsz2nTQ8ohs=,iv:QOKTw+k4y5rFn3vPhm3kygXzoa6z61RR1W2Uw3pVopc=,tag:ItlYgm4fDLpA+pJzjf8vlA==,type:str]
        access: ENC[AES256_GCM,data:SDSrM2E=,iv:3Ncyv7kVsHt4slUaFgzIenwBufwPZO3czQ0POGH29as=,tag:21wr8jcNfN75AWQ6UxwV7A==,type:str]
        isDefault: ENC[AES256_GCM,data:dKpfK2E=,iv:Z7CRPbKNMLNa3Z0In71TeyD9pjePVM01KqwbDnYAtMo=,tag:9P0wQEvhrlnhvo2dG83QXw==,type:bool]
        editable: ENC[AES256_GCM,data:3lsdb48=,iv:t/uUMyZv5Y2Ympt8FWr9d8eNue7BMQTc1ra3NN+v3Uc=,tag:N/HEGbt3/aRMfuxuOXrNZQ==,type:bool]
        basicAuth: ENC[AES256_GCM,data:Kbt58w==,iv:4mK0CRgS+sGt6nzXL8bG7C0XAeDO6leRPAHg06TSVVE=,tag:m6Tt/RKrD0UUpZT+qKkdMA==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:gI6myRJ0zDxlgX/sRFTktuGfBxNMkuSX8cHf/4zN+65clfyXA8TKqTGMeUnnHFungIYAOnoPPsgoLhAApGpuMQ==,iv:Ek/82kp14q/sTCdjtM99TdcMXgdrovzJQ2k6jt7lrzQ=,tag:DHnkzxlDXNmXxdaJr9xgSw==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:nADJhx5axLE+ekvmo+bVNAEugtEltwP8h0hcMCBn/0jHTjE768+AJqmv+WF9kp3Q6LbJPbxGR3ocoY0riJBLsg==,iv:swDmAmB1u5uFE6TjpzvT11TBCVT7UCC751Z8mon+4bI=,tag:BvruKBgVaUfCk+E3cZ/OgA==,type:str]
      - name: ENC[AES256_GCM,data:EKT3JiJy2f3RelMheujEdcTBS9Fa3XxH0PhPyTvk3Q==,iv:EdhuEygwou9TLRRpKRVwMjPOkAyDRT4Fm7EvWMv9Dpk=,tag:fvIjFKXQvoGNCge0tDQdvw==,type:str]
        type: ENC[AES256_GCM,data:B00Tbu10IvrU7ojbmlQ6jyIYlW3b4Qms5dPaDAkiLQ==,iv:qppXJklDz5mcVcvzSFmLy+EhFDBZLx1yMHIjhMzAVZ4=,tag:jcljlCCd/TGvtRTnOgJ+EQ==,type:str]
        isDefault: ENC[AES256_GCM,data:Wcjvi4E=,iv:xlVZZs0I19vbn5SS7hEd3Fzmc8Jzsz+ImOINuMmLj+o=,tag:XSp+J+6v5vL2fJlpJViDVA==,type:bool]
        editable: ENC[AES256_GCM,data:TGsYAg==,iv:P4a10cUS1Qpuc6veWWvRJjRzJHLU2GMMTmwByOJVyiQ=,tag:7EOhKMq5nwK9kZCp1rPYgg==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:w0dmCA8UCVQzVrp3Tg==,iv:NIoLKcnk0owE+yXTbtyTpZNvnn/8sht+QaMySSXpfII=,tag:e/2UkW5JN5/XnnLAANRHQg==,type:str]
      value: ENC[AES256_GCM,data:j5VNSSuNw+222grNRS6MKuPu/1+xYgwzPMF2SZQ82rwuZ8MDWN2HuvZqndq4Ydd03eIXmIBx2+oyJ4kb6ZdyK4A1k05jFIdf5tMT25gF/SBEehWh7O7lEeGi5nM9586APkK1VX6yfSPvFrxQeFQHWIdV7hgTaGLwTDXRePbzAlLucBYM5yM3QB5iDJEY2BUjiEyp13HK+JebM42jZeF1NcAMMexvz4qxZcZ6JCcttKnSag==,iv:MSzHIIddtg14Zu6B+CA3DW96xfBzeqWStImD1XvrNRU=,tag:aKpkDxAi+nFq7wE5j3XOdQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:hHWKJZEKZve134XC/gemMxfspF+qXX6/E7C4p4iu8MlQgCBCxvfhnPkwIGkknDO3wh6UWxEuUJjaHw9zQtWg0g==,iv:SoZCJAR4jBXwHBtxeMUkdU2Ej5GOSUZAHQizAC0//38=,tag:Fpy6cj/jfjxWrnlKrpG2cg==,type:str]
        password: ENC[AES256_GCM,data:0osYWaKwNPp8gCqu8uRXh/lPpAh5+iJtjg/7RXU/N71KFHBmMZlIE2aMtdbQKnKIXayE6Xgphabm7y083xyC1w==,iv:6H6YEPYueEhS+LQsDXCTgIscIA/spunJAmXtvsaOeog=,tag:D43Deouzn6xsN49/zWvbGA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        hLdo4Vmj7JiHKF7xPBJn1KEBuBx6Fj3iGg3lXZnxuMZ8OoWqQyRL6bA6mWXXne8z: ENC[AES256_GCM,data:bqVauo/PKpRb1u+IpxaTvz/XkmtlipIAtlz5ZnhNqy7hd4VEU7CD54JWTWwQShKnl9gkHV8m/GV8YYKF,iv:hnYUuTKzfcIx86AVzxQ2drpkdeoC4CgucVzLtcLB1LM=,tag:q6/MfvwyQ8Wgs12F8SHJ3w==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:NWHpUA==,iv:7l3yYodY6PU7/S/CeawB++DF0iOuDTltZv2RK4qNkH4=,tag:xhF1L/VVxxY/UzKWkC46YQ==,type:bool]
    username: ENC[AES256_GCM,data:GlVXnrHTcOLIrT2uWkgyLC9DsxQIjsZTJssgeGA2vnq5kNaueZRrm/SbbIx419xmGtns12hpggn+PRO7hhZxzg==,iv:Urt8SOFEApCMSHAnYgCKlWnkRNi7kJeov43JMv3b7oM=,tag:AIOuLvHzxiFtVqVCpKX5Uw==,type:str]
    password: ENC[AES256_GCM,data:kFlUOch4otSYtw2dhWSNG/l4eXKIkEF5zqDQiQDtch7KhWFK1G/V3GRrimQLxyQiIrxIB3VLw366bwiZOcrvuw==,iv:ZE38/82V/zMP4viQ3zBi/C/kgVVn9L95QVO/6YU6bQk=,tag:pYy2FelbrFOuwK5FnrMfvg==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:L98vRXcfv9yS9PUNYlviEAs4kHvl5A6FKiY2aRlovjJBFy4cG/ecqd6urTGmWrwtr9xZ6WgqDYTNH4lT4gH/vg==,iv:s3WeS+dkEctLTG2GDF4DXDGqQ+7Ibzlkxx2hN1wcV1E=,tag:v8a+VgIPrjsTW+pv//M1jA==,type:str]
  password: ENC[AES256_GCM,data:7mv/vkjlQq1ou8IuFc1uc7f1x7zPCiTu88uKvO8PAnk9tZte/3cB2gxmgztG0hwFYPmAJl3r/I5Bs0eHflEtOA==,iv:3ixtIol9DESnSPYKoOte3zxk2s4iwXGUQ3Ww56XIT5Q=,tag:7fVRrpiBVzKX7D0Q8YGsWw==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:44Z'
    enc: CiUA4OM7eIea0b4CAvAWFqNyDoS1Qx/914uSa8XMiteAXoUmyBO5EkkAmy+ekqbZrfOdBEXe7H1wl0EepeHUjuB18UKla1cIXapcAS5u3aVXog2HUiSq/Smcu+UEK22JZ6+4uXOvnLbDnPlrQ972hK4v
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:11:45Z'
  mac: ENC[AES256_GCM,data:XE8LoaX+DErqO0GGTpNLs6c5xzIdOq/01SCMbN5aVl8nTJ52QcZDSMkKW4IkjQwhfI1W8yXFdwIbceL79QLGG2FxP5/JjTtqWZx1b0dfPA62G06qdPiuRQQ1Hzw+LIA30GtduDSVMSyrP3r3aK18NVH7DeCT5xZfcl9vOx54EEc=,iv:azEMhcX3aI27Ka8V1+BerE48qm3R9ghK6vh2nIrEwWA=,tag:W+TuHioIRMIDz9Kjk1eLpw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
