prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:pajxdr0pEb6y6Ux4PGLvYZDZCxEtfh6RX+QcZAkrf7E/Vd9ksLAjxlZZazyuPFWSVtsFYnoCjBBsDqcBdEC3n6AQSTUHMPemYrR1cWbcwEa4I1zt6lD+r4gnONdUxAnoOajhKdtmtYNIUh2jjDxc1xk82edNOtTwoEvKxgj/c0CZr68pQvW24dneLzmG3BJgoZPIIk38B/GCqIE3,iv:gN5WbwXYcPC8xHcydHBwaZtTE13qrsTdOEYzyevzWlI=,tag:MbEwb5HwfabX2qfODMv/VQ==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:jcyBH6qUMuJ1iYCDsODOhllHJ3EcHWJScMm/igrRSMk1VeqpaKeeBTyezJsuQrcDBMAFN3juM/nGxOfnSNVzWQ==,iv:fhOfEklK67LA/EByPvZs+KBJ8k9mX5gQL2Qdmd6j0Y0=,tag:s4Iv/pdKUBLCJO0wGH3gSw==,type:str]
    password: ENC[AES256_GCM,data:N3n6JvCWbTNSR6X66c1D4xxH8NfTMH2fWSruMdnotnTBsQACpSvcMZ8vZqcwEZ8d4MsWbYrqNbWvKW5pwf2vhw==,iv:kmoVTwKqNWWuEyqXv4dPWnre/bca7+9KVTLrslEIUmA=,tag:ounZgigpdeEwYHt9l0j8JA==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:1g==,iv:xjPAOS6PDFStJiVb5Ch76tAwa4ly8Ik0wVam/0AaMKM=,tag:hrijOlLhG+PREx5Jfo3J5A==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:b+GANyTxo+Itbw==,iv:tjgrbCAXGxktxnUYXuUnBxfNnw/ZXdCZdiRIBjwxZgY=,tag:y9rUvLN/hUyeqiJmnyvc4Q==,type:str]
        orgId: ENC[AES256_GCM,data:RA==,iv:DUlicAdXodYP8IricdP7kKbBxBWx+cD3dXPyG6nUtzU=,tag:9pm7PES0l6CO5uGJXfxlgQ==,type:int]
        type: ENC[AES256_GCM,data:NmS1rT+02kMbHg==,iv:8vVwqhCWgtsFFNGhtjkMEpdRGsq/tPAJ+oiHYGALurE=,tag:torXggJbePhgzpa63kV3cQ==,type:str]
        url: ENC[AES256_GCM,data:sccc9jEIgXHL/1vLqKcd2TKyjMpiwHpZpBzGd5L8QK0=,iv:XdR6ijW0+nfJpV3rO1+9vtGRgIGlly9MhhItwaTKul4=,tag:P1qvRbuCy9jBhmDP12JQ2Q==,type:str]
        access: ENC[AES256_GCM,data:2L1WRJc=,iv:IXSEkuVkVEY0L9pCeCqn2Fxjx/kmf1j6u2pUaJUo2OM=,tag:nSYDpwlXJGh4eAJ0Gt/7DA==,type:str]
        isDefault: ENC[AES256_GCM,data:7gkKrGI=,iv:9/9wfFf7aU59PhDKgz5y/sLi5OfRb3YcIjkmJJ+6M5A=,tag:QdcpnHE/W+Gg6KH1AXMLEg==,type:bool]
        editable: ENC[AES256_GCM,data:O64/N8E=,iv:fZbteBnt5iEo5Ny0KvvsTelw4krytZmDvSPZGElXf9U=,tag:tJV3r77ieo6LrHBgM9R3Sw==,type:bool]
        basicAuth: ENC[AES256_GCM,data:iQrNyQ==,iv:wduA0mgovpbl8EZkup7rP23Sm2j0OQd/f2IxaM4lGO4=,tag:c/6ArFdrCho7KPhwUfRLqg==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:oYOb3Pi7xKNHC1oOQr2QWCJfFKMmzo8YLxwCOJy0wwilbSx/jVHc8LbstQw6GsUMVLFx/VnBqaTILvoT8qIwPQ==,iv:fOTiAE8AV2oxYgJP/1hGqvpjHeH8eHsGJxZLhdiIrS8=,tag:8+Ke75GdCmrhfPIXYnPD4Q==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:Ww3Rn1Dedcv2TqzRA7rpIJls7Y05xs4DxPrlEtCorlqeYya3wGHgC0qxTVoa2/a1dOlhw31/pBxRK5PERQvgoQ==,iv:hTZUcMmBniTuhlFY1VW2OYjOh0UF3vwWiBv9MpOVXhE=,tag:cxZcMWe1cdejEjEhigpX1w==,type:str]
      - name: ENC[AES256_GCM,data:mcYNn9zpA9NwMg4rHdFLYWELrK0oQCrdHKGzhvElLQ==,iv:rzzCtz3+NMUEYPpEXj2YMwTTR0MNXAxEXml1CKnZQz4=,tag:/NJOd1t5NLMAb0ozGS7g7g==,type:str]
        type: ENC[AES256_GCM,data:GHDFFTLrxtROkjFhgj2szj9awPkysvABkMqCWI/FJA==,iv:H6goCi4AXMK539h+6CGhpIXfmqhR4Ab+ir8hbGEjxsM=,tag:AC0HX6supKrz+Nt1PcBoPQ==,type:str]
        isDefault: ENC[AES256_GCM,data:fMjuzPI=,iv:QhqpB0eUlptRcRL6w5InxihWpS6xy1CJUJGffHOqv6A=,tag:YJEUyREwYGGXH8zah4Vr4g==,type:bool]
        editable: ENC[AES256_GCM,data:IrQCfg==,iv:3OW4qiifHyAZml47Et1aRg2MyptfukO14wEkpGx9cNQ=,tag:iYHVQMdVniS/eAzkStAzig==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:GfU5PhSsKnm6Swr8IA==,iv:bpcQHm+fwAro5DDHAw3qSJT4Es443lbzI2KsBWCi6qM=,tag:5/gzizlhTHKe7W5TKfW3TA==,type:str]
      value: ENC[AES256_GCM,data:IPuxleD7no9OdX10VvxA5lKLM6csYTEHHykC4/Q+hb2UUrv4E63I1IcugYfvRC0dLiEb/ka13/EcZK2hksUvvGBMYN2jfp08U6L3QLbe+k/B9UfZVUwIZrZuASrnBlskLDWRcBZWdBUhrJVye5HIITIJEsfp++7eK/m2ukCVHMY/h9Tpjb7U3JFz5Eb4EOpCdJlykdaAYD63CsJWMi4K3NWXeUqoKPJ/IMQEuXgLg+PEUw==,iv:WnitohVW5UI2S/iBNhCiE67QQrzDr1/8ccgvndqSfqM=,tag:9YGxqVcWpPiiWej5NCMwGg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:Y3hrj9ZYuqdd0n090olbMCCMKhSSdc+AQ1C5gXshzCCbVD6cRkfqIekVLaGdU1wa8No03/EgPIYR6Ba9OlKygw==,iv:2fAYRwcNZVSSt89zMnlUzFfSqy2PXcjNz0WWw6nMIGg=,tag:PGAGwwQYbbMr0bYp1PfPUg==,type:str]
        password: ENC[AES256_GCM,data:QzRo5T0QDLumx1owEYUd1V2XxqoSRf/WH4Letn5L/cmuGX9OQv4LJiUYAjUEAb4fxprL/Mc3Fx+m/a0Vzp9qYg==,iv:UKUCVjy0PjNhk2qCZAdrs8Dub3+VFrAWN3eh0gm/Nfc=,tag:NLp5qQm/P1+h8AjXjC3e6A==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        hLdo4Vmj7JiHKF7xPBJn1KEBuBx6Fj3iGg3lXZnxuMZ8OoWqQyRL6bA6mWXXne8z: ENC[AES256_GCM,data:20CuMHmSn7L6GhrkfwXoGsQCOGxxpL0Y0JeHk0pkUXSke2jg9+kpvGUnHy8WoKH7Z2/TBlMNcFKyVbh5,iv:WT0JnQdc6dXJp5EV6Xcwr34EJYBXrFFR8rsKlfgecCc=,tag:MXIRxRLFz7lNgGfRP4F5Gg==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:gtKrlQ==,iv:PRUWHFtnLqX6jxBzljnLTssxZGZvmJ7LOkZZ8OTv0Pc=,tag:hD1ZmNJkJ5zAfvrIZNOSrQ==,type:bool]
    username: ENC[AES256_GCM,data:0vdXO5qklnAzGjFWQJQJ+kFUp/N3alQL9/tnTRrfWXKvV8QU2cIBYxhHVxBYLwp8nsvXra5I9do2P+qjN9PSwA==,iv:Nnb8kZt0zwoa4XFgJJff3Sq69QKRPYOT8Xf+C16WHiI=,tag:WX3+Axzzu/p1C6K9Qz3dDw==,type:str]
    password: ENC[AES256_GCM,data:qVLCBK+wUMfwfvJl0Wiw1c9Cyk5AItN/my0LhPMwpQsVgZzctKUnmqweaVLEsTDic9AtEJ6GS59OczjaGkoUaA==,iv:nY8mey9gwcv4+Uo8zWf5q7zSBHkQv3gmtJy4aeZUPrg=,tag:JPrH2MVpyNyx82gdcXZbNw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:59Z'
    enc: CiUA4OM7eL/4tv0GKDOQ7HH/J7jj/ZgbeqtJw7uq3i0aKwWtSx73EkkAPHlbmboIScTAJK37Wp1Gh67hqAI6/Jv7yOWGbVWRruetmrRejCb7y0Mu+12HHWgCdEFvf2hqaObVlHwYKgz+xWYHL9t1HJ0f
  lastmodified: '2026-05-01T14:41:00Z'
  mac: ENC[AES256_GCM,data:nuJE00Jzl/AXVvd2Qu4wzvOIy7NB4ZZWLfsEJDkC1micLVX3Y0LGyEMB5yj65oleDNoWxFmEkwg22Tr8KPvm4JTwfB6BYAG4Dwz1HZtmzU54bEUX9ds7xDV2ZIpYHBOs1y+fCeQzmI0ovOH576fX5ewTB12xlpwy3LITmsZg1h0=,iv:SQbkwTWnDzBaNea/ivCU/yJvDSC8/ODor6AFcxWaVwM=,tag:XY0tS3Rw36SvLKTVP/644A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
