jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:zejHeV5gcnCkmzBIE3pVQI6soE8HA5/8lPPGla4i5+2ITvMbntdmIh0DCddd843X+aUi,iv:Hugj6RapTJSy5zkr/B63mGMNiFD/r4gO+MXcnH9spqw=,tag:k4+/jBapqva1QWfwM94phQ==,type:str]
        client_secret: ENC[AES256_GCM,data:mYdD4tvb26+CYmtbhdIjthZXWTc/YlCbHu4K2Cw2xRhlyBT1R/W1duRt38cT3rF6KTEgiuInVvvVnUguGOIuzf7la/8JZyHNbYjC3tqSH+htdsWpcQU=,iv:E7U6fBkMpxQA6lzf3/DpmHJ5axYz5nNEd8CyNjN+yVA=,tag:8kbqOqgv9up+fJYpl3tJ0A==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:o8vRF6oZpN8HOFnXYqAt/VzrStGsxWnY7PkBDiNIOS2dRwGqXaoZkX3peyZ0s2f3JI5IdrrlOK3LtO8kfzIfr4LkrpQBPnruF3Y9GNkL97HOsE7v1jI=,iv:9jjLYhxUj9Kvt1+Opz7GMtGen5De5Hp/XBAafDNAY6g=,tag:nmg0lTepZofSTBwnyaSihQ==,type:str]
        stringData: ENC[AES256_GCM,data:kf9+JqycNUZ2tadxhE8OznSxa4TJVLlI5AHxSCdlWKImZL1QIxvu7DNY8pEpdCIyqbUPKQO7ioA/lZDJd+RKt0/3bv6TPIOCdguYql9Xkwvw6zcZQB9CXt4A2lwyyvktRajOjBD9L4cQ4aFE9ODUYphl94IfQMqRLu7HprNyxVsGWub41hn0OZp3JL7iKm13k8/VR8NVf0agih8rKdQNIkmbp/xntdY+c737kDUYJLWeXYZgIBE59l/4izupFX8umWwrjbCWpZpGED0sBsnUwSjdxodyyW5/yu3+O2DsnSnHAnnozC3dINtvfsp9du2kvMhcomckHMMLLM8uD67LGh5quD1vTxb2zbsLR9wLxGQck9BCDY0fIZPQzfjehV9MSjqmQrGISgxaNqFagK4vrnVO5eUfyV+f3KK948pO+x7Gy+n9gKMoZUiq1UUEBQMSlYqyixpNQ4YTRiMpVdWvscRo3VzD2NG2QeX1eyUfRbBwgNAWUFCGUmMh2RgYNPynXtmPJnUQnecTgSz2LXuvVjR7kaz9f/zHhqGasM7xWYXqT8RzaY05URKxwfP56NEJQJpYTEFZkpg6XvFRK+lx2vTcEzKG5l4SodIHGVQ3BReVSlzj7WRtHEkN5+PJOvhnEwof/Bn6WFMgb/y4Rg==,iv:rimrX7DGIkocEFA05KjHaNSB/X4xia5hpWDS8+IZOKk=,tag:IZ4FAZ8V9hFcUvEI8G684g==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:20:28Z'
    enc: CiUA4OM7eId5fFh41yBJjHFcsTe13NJv1mHak6rlD4CI5ieH5fyZEkkAmy+ekkXQ+EbB1kFjl5SeIzhEAZcGltD14yOOrBMd12GzVKULCCTGzVRkiEQxclFjSrhaq9r+qVy/4vRHRVGEn4PDoIqZQLUN
  lastmodified: '2026-07-29T19:20:29Z'
  mac: ENC[AES256_GCM,data:VMLJvJ1o9kuV4V3n/JaHa0KCGRSEyPZ5yoNlMANZQ5W85H/f0JscrAFJ0VWF/cYJzXHUbvYCVojJIm3QmPA/rLXLSinGZnvYS5o2D1JPBQixIbp6eFO/bx3xGaoYhBje4WYKZnYA20oGh63WHdogdla2E2sQTWdTUo2doavwSHM=,iv:wAaY49MCyG/CNx4yHC/gFH6FPZRvNm/SHmT1Qlo5+a8=,tag:5s5OxM9jb3pogOtsPKtTzQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
