jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:zJnKXGGcd5E1oZFvGaQuB701si6wkiksp3bYnSx8W2q0nkuU59Z8aizPfnscW9IX7jO4NvHaA51WuMnmZmuUcuCXFRrmCRaELCEYnZcYovyYdwuzNZFNsM5RqIgR+e80+zvpl4e5CCep6P9rgXLaCgQxzMDaRmpU9FICP6K9/i56wQijsH1UjFtmX4mniXOvTes2pYUl/5BCnhqFcTvrwumSVLGVBHuy+MShdfZhqUOEBBf3L1Y6YYWA2C0gHyP9LHU6E22Y/nnvjAMhBmLwqxtdVx8F,iv:zopqtRlxKze6v9NET6T1LPvgeTCjE95Qe9EMvWKAy5c=,tag:iubE1X/98qoKVzqpRPrmiw==,type:str]
jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:9bFbTU6ynI3E3EbWgBmtpz0Nf1s=,iv:isXELxttg41JfEn2tAY0fz+56WgWlM0L/SG9nfiHubk=,tag:szmvivRnDjfNIJJ0v+LX6A==,type:str]
        client_secret: ENC[AES256_GCM,data:9appIhrQqJ+wyRLevIgw/ZLot8U+yZ2fQ2sHSrsYdWoXTIXe8ZT+eg==,iv:LB8U2bMRAob/eptEiJ66u+xh6oC2WyR5SIW2HZ0iO3Y=,tag:Spis7hzs9NJDzeHvCcsqIA==,type:str]
  singleuser:
    extraEnv:
      GH_SCOPED_CREDS_CLIENT_ID: ENC[AES256_GCM,data:RuCaZkKzik0TE8tnSVfAnAgmQZo=,iv:6c9rcURg/FfqhI6eNyZOQRzmpnWorrKI45R7w2DVoR0=,tag:y8r70d0izDAHkqqU6Lg90w==,type:str]
      GH_SCOPED_CREDS_APP_URL: ENC[AES256_GCM,data:b2sle4Hh6V0TkEnP5Tt85cvUx7tI+Xu8AhnMs2FSczj7Ymc6nQJFzYjT4y4v1AI=,iv:TTLV/vEH0ET3SGaCoIKUNhqHetZtGHkhM7fl2w8wK20=,tag:HcWG557zBIYMEhHPx6/Kig==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-10-08T12:42:43Z'
    enc: CiUA4OM7eNZqwIrJQR4gBKCIVzTyKqNasI/L0NyYr6c7B5mgjBjWEkkAsHDEl+AQIVWGhPh3DYCVbD3X7LFfFL71OwhwG57E4+x0ui5yyznoCWsK403bL63f0c6b/r0vQpbK1O9n6g0Avc2uSHNWrjOQ
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-10-08T12:42:43Z'
  mac: ENC[AES256_GCM,data:YehbVdfoOtFvXAN8USSQkRSmmsEyT14OmLYPgQ9zC4J5aGkTldmuil17VvEPREWUcB6y4thHbhUOk+NYsD2a2MdUmC1mqiGk9NZzEVJRHHGHh3mb78kaIMzEDJ/Bj+U2cMeNvHgA4TgpNga5VFHzVCIiuj4o8TIaQGa+mUvlGkE=,iv:E/7xg6q7OLKeETyI93N23l9n+pe7kiNB9B726tc58NY=,tag:XuPMxWINjWiZo4e7Q9Ga4g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
