jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:w/ujdOF+QvHOr3dn4E9bmyWlqWM=,iv:AuIoxiAlv+gpTB8bnRFQLx2agOfTKbWoaonQhKyoGx0=,tag:sEiWzwiUt5+Qk6yfk0Z14w==,type:str]
        client_secret: ENC[AES256_GCM,data:cqdC5DVOSdaRebY7as343/Ze/f9E1WnH+mIeBBpv+BwpYn/IIyjn4g==,iv:C6yZDrJtRgC68ZjGyHUvUcErGSbLasYhiW6CAjW4gtc=,tag:p2TRv+Mt85GJ6J5G3b+GvA==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:sEUAWJZoADt17Ul1uB7nv3fKRBEZeiJRcXWRF4AdkzzIDJ49xVDxC0tRcP60kzAokbX4da7LUQMe4wUC78CKeoXUs4w7yJ9j5RsJKEEXP36Ihx6SS3g=,iv:hXDffkPbcFBeoUMV9s4D3c8imth6OdbJoVreIEyQNz4=,tag:X3atKgEs1fps/d1/Kt2+iw==,type:str]
        stringData: ENC[AES256_GCM,data:F1fB1Mvw9uEzXG+wi1+W58YO1TgHRkc72hzBi4r9dpw/h5Eh+WCvGHbYEOQ8dyc2pnNNef/F1j8B5X46b005n6BwVAsfHJqGp9JVRMZimmFAKtCu3Y+D9AapuxO6eiZYDt2JWNzYwUv2UE3dcaBrzbChv+1Sub3ygNR4keGzKdO3LZcn9NumnhiOXXRt11XtVBSIXFTrxYK10kpQblus1CzOtoK0VTUcvHrjMPjTAd5q3OCF+teJOZ262zWpbZUHKMC+maJUXC5LVPKmKm/kb+ZZ87w+XerOzYjXnKkHkszU5SwBb/N7Sjc7XXWwhPKegpQObU5Rh3QRlovb7e6j3PRF6uOq91POFwpTs4xgj2r3YOlLlHIP9P5O+hXJTaC2/zrXX2xH9F4SU8rKEVh5oiVTOOD4bIHXH2sIcpBUfGuvGDhYVho0imbOVaw6Kaj13axR/8WUjTumX6pbOFY4XhPJWl4pgJHLA54+NTJh0DE0yHSwnmsOV70E/AVUtpOmjGz0+giAQLVRMh7J5e+dsp1S8Ven+GFiuvNfH/jPo3bLxvCVHZMCn9013C3ua19KXI3FpQnxca8WQgH/tCvd7leFofinOoGM2/OUjwbbJcjTMvZwSgo1XZ23hr/xG9U8mSUg/Zu5dDbG00zIxw==,iv:mKJpC/2tjBVGtWL2Du2js7wTx7nCo9x0faa+ywbI7qA=,tag:FYKMf0yq1fV79keEMvBliA==,type:str]
  singleuser:
    extraEnv:
      GH_SCOPED_CREDS_APP_URL: ENC[AES256_GCM,data:KX0NBHnSNef7+p4Tymx3nvNpRTg9GHyhBdDdNCirFShzTCvuUDc3dYLqt+dpEH4=,iv:KRL8UaVevh0gnJmZz2EzwIOBHbrPsqCsqEwmuV7PqJc=,tag:dq7RRHVedvGbdttasHxYeQ==,type:str]
      GH_SCOPED_CREDS_CLIENT_ID: ENC[AES256_GCM,data:Nr7wfZfPaqLZkYM7ifmc5t6NNAY=,iv:HEf7SStNInKPm0PtCc/UXVqax2wsYEOz51KamapAi08=,tag:rC42PwGZ7K/4hlM6wnIdIg==,type:str]
jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:brHjg7EJZfIBhkug+EJEtvQkSj05Wz47wGW4lIMSw63Dzuy00TkUHv+NhIH0ibmTjcg+o69Z1tm5wVpZmcPmThLsa6g0tN8AKMc/KvA7QynaCBlBZcDceFfMp9rLWUA+1sp3fv3RYfHsgkuAIu5oLFtKkoMmqftEcyj+cisrzqfunyM+kJuxleM1f8+9hht0+jS3g8LhMJNv/d7Iyp9DF+lmvEfe+D98fPbWyRAvutKXRiNOX/qKEFp6sf4lfOEmw1RXeAauoa8oW3w6iLb0AryDyw1glZZRg2QI7FJAy9E=,iv:lhJso28nCqGjwpq/i0/0k892h3BJlGSE/8T/GKoZvFE=,tag:eBTf81SRRD298ZCihi7Wag==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:20:30Z'
    enc: CiUA4OM7eFCxyUpsDEdxJTmAvAioJ45PetGNJuYLfX7hkErJlf/6EkkAmy+ekiSelr82/ChOjtmwbSXVI7othIhajEOcLrzaabHHSpkWzKKjfY1tmomHYpLND5zqWwfzrphkJujm1FKgyZyoIU+vaBHi
  lastmodified: '2026-07-29T19:20:30Z'
  mac: ENC[AES256_GCM,data:jDuSkhxxNIETkp3Zv4jRjQcg8Tv+8MrxYSthup9Js9/YYDR3H0GGZkN8qr049EvTjpu7zRqmW0/aK6tHd+doIQx4rVixE5UCKxhsJNZWBhf5swMi/aQX/sZIB9SRlgwrW8cTIk+Gg9dF3rIJ8nYxcJOqbiTn7G6ZX//OwBhvZm0=,iv:rKMtLfO2VltQpxtlHF9ZEPrElpcNS9Hq7MYWs5eoZ54=,tag:TT0DNhEptZdK06b5cKj1Ag==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
