prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:f/5IHpZI7Qfr63TQgA==,iv:eZv3F7cgmVvfxFWaiJ7o94W0c5cT2HzA/2W6CmOiywk=,tag:+3J+JgoNvP419bzAZb2NKg==,type:str]
      value: ENC[AES256_GCM,data:8nk1zk3o6fF1I2w3nWR2xFGF0xybyr2BC6P1I4qgF5YVReZyAVgV1Y6iwhQRLVULykygnkP3SnntP/UKUTGIRg+LGQe6W5tbYjLI7HnRh3y6fdbGgGPD8Ux6BrQuV1ydryqypBlkJqFxLZISg+s0/4l54LP/0UaehPRXLTaHOCw2XWlz9SQ85DbYxelgj5wMNC0VHnDseP22TpfTXgoQ12AilXY0R9wHEKcHdo++IRYKsA==,iv:3YdM+D+hfhnv8NQbLlcw3TtzRT1FdUAfMx0vRzrbHXk=,tag:yfaiW/6jQ8MWsJ0x7qyuyQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        1thEnH5ksw6UOJnpFAWabOJfUwReU0czdcYzU7H3tAYtsVA2NDfRZyGWj8YtTsmx: ENC[AES256_GCM,data:PQeklR100iaJ5MXyd7/Ezeel82O5frdJvjRpKGqq6tpuMyJAE5k1vmW2tnyCL3BYAEJrRejKQQ1Ntd2f,iv:mOxRbbZQajQDXM53X5mE8W1lGRPN8YUUzHV7xD0J3ak=,tag:UqYCPx8gRHtABNSE+t6eMA==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:wDCsAw==,iv:2C8dDni6Ap6g6oE8oQ9gu7niAVzYvSq5DVRz9zXKE2k=,tag:6pozNr09b/axDKrWgvC/Jw==,type:bool]
    username: ENC[AES256_GCM,data:kws5qUJOJD4W9lyWMfhyF8V/8wlrdBn4OBauU8h32l/Utkxz2jMZdsIX7h7hUC+yWn2DF0yK6KQKkAzYHL5xjA==,iv:uKB0YINUjdl47VOWQ8dWEKLuqUA9GGkkACZap/Eq8qg=,tag:JzO//mHkBhR4oAhPHcMjMw==,type:str]
    password: ENC[AES256_GCM,data:mL4NUCKLYEnJBx1n3Th2pKjbPQbQ8VjJ2ifzo0P98zP/9pjhNDYCtbUp0lhrwasuWUrBxxBoreTh9Wfl4+DtzA==,iv:iWrB+mthvEI2mq2I0CayYc8Jt8cLN0kdgolXVUKWRJk=,tag:6a3ckYHWANYXt5QMiQYVqA==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:pizko95nTo7DZrxrq5TwutzZxAmc+fkqKCdQIewAUN9fv5Lk/W8aixwK5/sorMfEaJF/BOC17rwA2FlSwQKTTw==,iv:on2xb7x0+aEBTJXocNuAQ+/TcKbFrVBfmLDFqeufJl4=,tag:n8X3lGbbGEvT3TXut2A3Pw==,type:str]
  password: ENC[AES256_GCM,data:hKcDc/o/EpPvm4tdFz9KCdKA30ns4kjV9hXrE/e2zU09PZYBHADr1nHRmjS7UitwHKyMiBB1lfZY23pdfQ7Whw==,iv:ZamkVCjo8My+9X2+iToeHX6RlGifq2b5b67Abzm5hIk=,tag:SR4dxocknpr73VyLbTHpjw==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:21:42Z'
    enc: CiUA4OM7eBs3COgeIeHcTbTVRXFCFbIJP/bsxhi12Zd89TrCPJF2EkkAmy+ekg7ogu38c6ke23qDq3qn53MIwZNRrn4lFNCvHR82b4nnPmyoCfmKQuLc/OYqUpQ+Spk1jX0nXV1joslOyjEmmFBoxsXo
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:21:42Z'
  mac: ENC[AES256_GCM,data:almv1zudpZQ09ulu7W0Nn84HUauylo2YyHbyOY3+qw4Rf79zUbZvLh6+fBFYW//L6bFo41u9wQeiGHqz1sSNb02nKMjPgurEdekquh2J0n1tmEIr2KkFTGombJS9xJ0TYe8l5I2nMvhymRrEYjpgdkJYxHn8sCc1UQqFArPWRnQ=,iv:W6mZdPxvICM0ecA3j7VRbgD2nZSB9zagIndgo8hvJAk=,tag:spFYlJGEF8i9s40aRWGi7Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
