basehub:
  jupyterhub:
    hub:
      config:
        SharedPasswordAuthenticator:
          user_password: ENC[AES256_GCM,data:PU76mfyoala2eSZsw+SvB12uCEDmxNU0rBB3QUv27g==,iv:7ItyZGYy6MsNj+Oe9THtot6GJ2hIqmsIkgl5avMwtNE=,tag:k2vCgrdkEqNV+82qeIef2w==,type:str]
sops:
  gcp_kms:
    - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
      created_at: "2025-05-07T08:07:12Z"
      enc: CiUA4OM7eIHDivZcDvslLg3elkX0T4pYR0gVADUKsPLIdE9tM0IOEkkAWOWv8DPVHy3QKWEx9fdZ4KRPWJMSG8CKO+gfeqYiy+AOSoLZZpF4r3PXiCOkQIImX3yZbe2IrxHN0asSXzsJop8A2JMaTAkn
  lastmodified: "2026-05-06T20:28:12Z"
  mac: ENC[AES256_GCM,data:HImhIeEWzQkOl0D4gaKSd8+/LtrH0NvTVKIID9y5Km9WUAAZe8IFtNUlzuV2nq6WN8KcAtE7cmOjCLMu/PRhbriS5PrIALyzFoDg776HOqbRCnvP23N0qc7kivbqdqTHHe9Z50WdXmXAPvNwDxY6oZ/vXup7dYBW1a72A4RGNe0=,iv:tqNd00AlWokZ6oDWBZzMkTsUtfs2Lt+4qZVDboAEXF4=,tag:qDTig8114RBtOpI5ZsMqMQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
