basehub:
  jupyterhub:
    hub:
      config:
        DummyAuthenticator:
          password: ENC[AES256_GCM,data:67m3vfLTYQane0YUDXMX3W6ZEg9uQST3GH9Bnxh+pM84k2v/4BQ=,iv:Haf+iY8OqsoItEORu1eyJhQr/Pfb17onhEfn5EBVdF4=,tag:q3ptO78RYtKK93p4C+5fPw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2025-05-07T08:07:12Z'
    enc: CiUA4OM7eIHDivZcDvslLg3elkX0T4pYR0gVADUKsPLIdE9tM0IOEkkAWOWv8DPVHy3QKWEx9fdZ4KRPWJMSG8CKO+gfeqYiy+AOSoLZZpF4r3PXiCOkQIImX3yZbe2IrxHN0asSXzsJop8A2JMaTAkn
  lastmodified: '2026-04-08T13:08:36Z'
  mac: ENC[AES256_GCM,data:GRBDbHnAyailB9DaRCB7efLLu1o0/KGjzeaRx8AYK5oHeWlz9L2yliViolCw0ZDXQv0SFxUfvC971Macj/1Z7RrdxzMH7+OobxHzHZ2A0DtBjlKh2kfg4h4bXAQTSDkSmZy5OxDmyLyouMpvs5Mcl2Uoa1ARwTVAiKeZLH7ZFW0=,iv:J+mVv7BNvRO7VbSdHBRkUlOYJ0PdSEfVoSIDjfvNp+Q=,tag:z8bPSrBs1QwwzBnLNnnlTg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
