basehub:
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:wyJPxhHn5OkR3xzxgDev4IiOhvakMAAd01mrZoqj6+veSR26o+1YSZHGbjhxnum01DkmjOJILViHgyzPc4g7SbcAGAGnrgK2+udh2PRPsG6tBUh4fJcCf+G8MMDBw+bOR3VJc73J/vcNX3F+fV/hv9L0B0xGd5Q5mzWgWZ4zqFrs66wCCoP0AxR9KlNuklLCr441U1EYl1EORNv7ymfJuFMrU/+WnchJUvnJ/LmVIvSinIX1NlUq77Q1HLLI/to1NTUTicazwDvZ6Wl8R22qlq9TBvgRFAz2DHYzKMnQXs0n9bch8bC1ABpcHKQ9tSLAe281HNIygJLb3BxpTjt36D1QmutYlG0x3bpqMrMoGBn4lSDmfeB5D668u92fCD1rGZXHsmRafooi7AkPHLq3DVCtZBUVIEFPh3OU4fKoytcbIQsgCT8bSXQcYwJpQuoeloAin4KE+Eg4lseES6JxBQdA1+z3og==,iv:tV8zJmlb7yhGHeEnABnZ1YHH5J8VpCc32YoxKqzHOOo=,tag:aXMWMcEeruT13Jzcjo5qmg==,type:str]
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:bj5/3DNV04Ze101XPjVIGrWVgoM=,iv:xMN+XPDJMwYXeAnmZoP46sgxAzvUyE1mA2wljmw3yZY=,tag:aGbwpYGMV9b8nuDEBcxsrA==,type:str]
          client_secret: ENC[AES256_GCM,data:hrB5+iW+fJjewUobAl5lXgXFpc25jQmzX9SxWJ6nMks2Sf6DwkoEWw==,iv:RM7JIgB9/AcpEM6pa7kMzoddN7wi80+zIVn8ZngsuNc=,tag:0H1dJRF3xi9D7JJYlj/q1A==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-10-08T12:42:41Z'
    enc: CiUA4OM7eEk3pLBKvI/091MUdbzlnnK2YciRRdVGjj7aVJIgd3ZXEkkAsHDEl4yxgrzpY3BWNPFDUWdy1CvzGKfI0NGvLlc4wscjHm6pcd4WmEaUUWA8rvKD6zJq+of+Te+u4cYYdJ/nAPtta35nPhcv
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-10-08T12:42:41Z'
  mac: ENC[AES256_GCM,data:ntd1TkVxdWlFXB2VF/L/oDeAJSZrPmYqvYs9i4F70KN0jb0jyiVVeedjATn5dSnJblIplSX8oVcyFflFQn4qZyYVqxY1EXFM998i/kqZEO2bJK5iNvhu8kEZA2NCEA7qImrVVM9XAZiulGqbbxXHbq0XOqy5AUasyBcA+rzjGBs=,iv:R6FiQCmUtnRfg1CyzsQo9YjQaYjNhk2EenB7Ao/v9f0=,tag:Tmz2hn0kSyi7d9aBy+JCjQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
