basehub:
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:3J1w0HIO2tRvVhANTd+mGo6Rc20=,iv:pscDV4OvimxFPCmzgjoj7yOUZNo7zX26vFAnOqd4Ccw=,tag:mF3iP7HwwHCX7h53AZyfmw==,type:str]
          client_secret: ENC[AES256_GCM,data:MsbvwhK1G+X/5wN0qpnpkX2Y5tmT5kD1IGIoWuVcljoLMLKLRkBT1A==,iv:FlTg4AZLuFefPvZybIDSBKZP3fqm8Ww3A1qlGVWO5DU=,tag:PyNOFkBH+34c3VS/pj5RKg==,type:str]
      extraFiles:
        usage_quota_config_secret:
          mountPath: ENC[AES256_GCM,data:0NRdh0ncA0A3aCkIQhIvK5ki0PYWgPIvYfv0ZpvSqaTbWEDlUtaO8MJCF7PNr4X6sfp8jZGmQe5uZ7eJEL2xvb/gFJ83omLdGaKKMh0oqhPg9IWSPLM=,iv:KxuxDcaFxcKpgvTOC5A2LiP6/WQhyP6DbPSTkcemVcM=,tag:jJvfswN2p2LvQI8oeBC1dA==,type:str]
          stringData: ENC[AES256_GCM,data:NFL7wsrEDAI66xALPJa0MHKEleiqeeHEI4EdOBRgcSa7gEkC+4mAUO2BRFpIgd0m/55SpTo8Gjw20GDCNdEiav5nROB29400AT8853samI0elyXpSccLqT2HDcNfwWOEWmpUjuJq9F1BXb0IZgoV3P438/u+Zjtxn1fURwDTMpOTyDKg+vEcYLAxRVX5+R5Cg12RaY78Z0AI+wF2OYeivWhlOIc7W4uZQQ20SGsB64qV8vqf+rJbTYAeGemaP1Bn94d74KAfsrAHtR0gfrMBJ5gwBL8lPmvD4qTAsosJuhBiLLNy97uhVLlRArZ7dMP1LEs+7LA+dIumbMwGgbd3YjvijbUnsxsWX9y5t7tCYiB/VMT4kWdnkz4SAIj/OI44X3MvfUU6ry+woff8hnADw4r4rVQZ3L4qHNFsfhQ1QRWXgmWDb46uSbHJULGY21qRf2r/glyzwby/1FFJ6f7ydb7DY1zeSUhktMvM+CB/0eNoOyhc4CMS7daCYH4fVZHtRNrLR1LBwFqPzbd2/RRJXC7ZOSbuXkvcd4vweaUguzkgeBVdtbKiL1s9x++DEi/bw+vxi2FVa54RWn/m1CLGdC8ImC/PevH/Hqz7o5ntPWJDZIWdSXGi2iuzUQFR+W7D3ODHFF2kwnsbs3KCew==,iv:37bSt1TFVLrih6gNuHwrK17y0a/2roRGoHrbZdx4wBw=,tag:8YLzaq2M/g7qZ/y+DOOVjA==,type:str]
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:WeFzmW7vqd1Kciwk7nIk2Qp77Q/+9n9TdmC0VCbQhY3dXTV2QoDyUnJr9wLgY82FtCjQKqo1Goi+q8fVfZ52MPz9Io+ykjHXG2Sds1ZAYITJQJzSEqxKp4YbIejGKWH9DETWTSHXv7R8H13YNgyMmEQV15RlR+s5IsHz7Qn804HfQB7xzCzGddjfhdq3lUkt17v5VpfiPYoUturoKeIcLU5cKK/qxIi1i7u7XMmoDOV5ipKYZwG6LbdQ1sS2XnoHWWwzTtFf/ALr+tC+okrpsFmnBvsz6+uRgFhgrVlaEA9JM01SJOoq0P4bHw+45SYX+iJRJU2D86TFc0oYhYtQDI6qtUuda7ImK2upCuO+NsVjzUJrCs7qTfXroGNulnnCrwrbuXqnfCKdhVd/li6XjwXz+LQLlENJWHVdVJo2Mb7dldbz3CkJ6fzN2LzRXNFuUPRXPM9kPlNeiOelavF0XUcs2NgGJ6Dp/YsMsMqnLshr,iv:eQE05lVKeLyICxibMdiR/Thnh/iXUA+OPQmIdSYGoxE=,tag:lm41i5FgZMtaZKRZy12ARA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:16:31Z'
    enc: CiUA4OM7eELy2SbdPs0vqFLVvGNRF/trR2exXu1ynMs03Q2Wui3yEkkAmy+ekuoGCQ2/7CS7f0J8RyV3OwMDk38ND6Q0Tdx5CBOGGbMHrKjQNfTPq3tKy3SmXYT73NOLkDbj/zifj3R2+QoFiJPxw4h0
  lastmodified: '2026-07-29T19:16:31Z'
  mac: ENC[AES256_GCM,data:DaP5TN142k9h+t+Xk4R7S0H+b67jzPhXtm7AAybGBklXyZ2mFAj6mz0XE+Gb8nFP+WjEqIHoRKu+FZf5fftHzhWqV4eYteZrLZneSB7IU3dbm3jCnj/V1Sa5K6ZWNBcAK5L3/xK0osmeA0pv+/BpjP6OI8vMeOykfiX7ckT79yU=,iv:5eJ1tJtp3WhaJcTMb7u4QtLQu+J2+gUdsHuqyHgsamo=,tag:3rIsn212sB3o8aLmaLRLKw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
