grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Ow==,iv:Rain7TNQV3h5jsF8Y60XtKaLJLN2WHr1BWPN7lzspsU=,tag:sOz3K250B51UBuviPqUdnw==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:tZ9PY1EpjcOJaQ==,iv:Qv2/6BeltrYEt+o12CAXpN2IdFY6hXQ/sVy3hEFYBcs=,tag:XQhHi+zXB7ci+CKyyjO+Rg==,type:str]
        orgId: ENC[AES256_GCM,data:9w==,iv:TkRAyj0y2HZK3tM/3lugqUjmMnISUeUHlfxtmQ/ss6Q=,tag:ggZXVy4ynFTpwPzCfDCNyw==,type:int]
        type: ENC[AES256_GCM,data:2uLD1klvS5M0SA==,iv:YqUwwxs4o4tFrb65kzWYTc1jzrCOOrrlSwrr8Yu7ia4=,tag:Kgo7zA1qAeQcX/H2aUZMgg==,type:str]
        url: ENC[AES256_GCM,data:wV8GwgSSKYj+2iCZTMKZvvqZwbqra7orywUHGTxYPE8=,iv:ltarnWES/QOen0jHgiwaw62P8KuZt7029mgW4IC9Srw=,tag:hg4dOHyiqlZjId+OOyhkTw==,type:str]
        access: ENC[AES256_GCM,data:HymYhgU=,iv:4DiGOTPziwo0snQnzID8MmmjxPqHQgRYhGkRAJsofuI=,tag:Yfbszl8Lp8w1KP6WkzRpAg==,type:str]
        isDefault: ENC[AES256_GCM,data:z0IlI+A=,iv:yLJmpWb6RWPPDe0YzxJoUFJdz3xo/DOZkDVKJ8is4g0=,tag:6PUXGb3NL8oglVm17M6aEQ==,type:bool]
        editable: ENC[AES256_GCM,data:L32nOwc=,iv:4Spbx0DDwSWmhf4A9NNF6wDIWOXkux4KdJfy1PX+CHM=,tag:iyl78Ip77iIVB/wbhXoQJA==,type:bool]
        basicAuth: ENC[AES256_GCM,data:eWjgmw==,iv:FGi5qZGS4uwVO9gEJoZdo+DMd14OMNHeQY8YDVqS+bI=,tag:BCVnSE1la4JhPmookc1fmw==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:9HodNzgLXuzCNM9KmKsbySf7ggYTHVPZxcTGGqZ262+H4u6YMCRBEyVyQMjKPnFnjVye2hqlKDnprLxptHsvyg==,iv:8e8XABwlU+AVUrcgJ2s1QFgvBAu9pgZl8kpaxUf4S/Q=,tag:hkYjSXKKPXtkwsqbM+BNlg==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:Px1rbaOJteNmKVwnxB3drG6NvPJQiq91cwJjOlJ/6W/e4mj92t9/qg2ZTkGz2X7y6vodzb2zFjv7J7Y9VKgGsQ==,iv:hhb2ooXBP/64mgy3WbIYBa2u+VkG6bv0+OrW8JdAvZQ=,tag:H3TkNMVc4HmaYL95NklDmw==,type:str]
      - name: ENC[AES256_GCM,data:QBDdbX7N/ro1BG7ed0SCjcKnGo835G5TB7sssW68Dg==,iv:Cl1+qSxJ8xzfBQMO1IqLtvT1FK9ArpS4vBy8YNLBfi8=,tag:q7t3CpMuZbap4rv7eDqDiQ==,type:str]
        type: ENC[AES256_GCM,data:FIyfBAggqMWKo683JOiLhtakxzu+4xutM6I424Hzag==,iv:SvosirvT/YhgGVieyowjHLmP/0cBlNbfp4LwXhVKczA=,tag:T+MdvvudNjIChsSK0fYQ8g==,type:str]
        isDefault: ENC[AES256_GCM,data:lU5fbOA=,iv:wH/IFPZq7NBUBy12rxdCsSoDrHrumioYkxLnDjeH6nI=,tag:8NgoofHOMCHXUi7xmyCIUA==,type:bool]
        editable: ENC[AES256_GCM,data:nD0dsw==,iv:BoDPnEFFciUx2n65Yry34aVEJJ0zYRBhFipiXf8tO38=,tag:IeMAKMSbryYYiBiW8CQG8A==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:PLBVL0p/HMgZLow7Mg==,iv:riVscqQOMqYwWSKmGXgOv7rWA2AAmZOcFZViLlR8Y90=,tag:yGGhgRBfkbRvE/TEeQfvRA==,type:str]
      value: ENC[AES256_GCM,data:EY6FfaHo63hMCVngxfU5o91zTJiFX0L38QEf1HMVVY97l//CRfCrXQsEWMrkQyj4pdsTpImu+5sBbh8PdkN8Qbx4dcgRLc6qlGSR5sgAmuy5bgZSlGVsjOtQ7q3iVkvpCERY6oRRHgByccb/YqVR4/ob2tNWtqLtOA9to1qHoOwGV7UIkTkR5OVi1tMh2dgYQ/A0IKm1fF7q40oOB4zHbAzwxKHEWLuUtbu/4mqdYgei2Q==,iv:zxaZeB8QZbAGU0cbtv9RPFyskyQ/PqGR7D2lIyMzoeI=,tag:oZrE8xMii+iOcFi5PPT1CQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:a37Z0ABR1V2sgNFujvJdM+1TvFU2XXrKGIzETFD0wW3mxp6b9CvdhHr2dtb36CKZ1raLJ+2z2kSOu68uPT/15A==,iv:wn2Dx4EWRst4SoMUsUguY3YLypSP/JeYZ5tLaTwau5I=,tag:r/ytTfZXXG4mKpTtf/QCbA==,type:str]
        password: ENC[AES256_GCM,data:bc+PohqJt/wu//65jerujYUvgZ+uxmk/EAyfExJQN+jxfw6Z/DyFygaNYXAYpPJROAmUFXeCunpuAKYQQj/ZJw==,iv:CfoTgWtP6C5oMnHYUAuAXdCbGPVjFh8RjkynlEdxA9M=,tag:kd2EwJRWoKbx/p1Y7XWzew==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        1thEnH5ksw6UOJnpFAWabOJfUwReU0czdcYzU7H3tAYtsVA2NDfRZyGWj8YtTsmx: ENC[AES256_GCM,data:yN3YOwWmUBo7xK3e35sFTK5Zq93BuIFKipHVfDiSUJRormCpPPIpP1YIpSXPzkL2rfZR0tXQczkg2Bz9,iv:kDqouzCwaZCNROHMlyK9CXN6qparhep/E4smzh5aW4Q=,tag:XT8t+vG+io7B+917RNysOw==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:h/qneg==,iv:j30PP71mGGL7L4t5o50+rePESgXzYi1wSd6byJucKw8=,tag:nyYjjTIgyaEy+Jy182FdnA==,type:bool]
    username: ENC[AES256_GCM,data:XeWfRQSPent5SgL1rSUfhXsGp7FsvDfdWB5UC5+NrCSQ/hvXGFTs90d2JkwtszCN5ctIQaaUD1iaKZ2CsRYWIQ==,iv:fcBeW+15EqstapUfmHAbhn6V3n8YVCagjhidafPg81o=,tag:/ew1T17BlFyFfHpV0GhEcg==,type:str]
    password: ENC[AES256_GCM,data:3Br8uiD5Vq9CJU4e/tpz5glm8BYn9xAk2uiJSKVvRn+yGAafElEDRR2i3bfmTrRjFOnL/z1CrbYhQFLDYNlfJw==,iv:rzTaO8sqpEHKBWoNWNxR2lwW0rR3ttYRm/WPvDoVKhg=,tag:V2IkdGdcPICiSNytaxPuAQ==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:unMdYer++rF62Nm3zezrNzfy333EZhaaEdqTBm04wHKzjOyH4MvFfnghkG8oJ5yCtVebxdYkkND9i6juYexDyg==,iv:5OkyTICS7HjQzWngy1R/CaiBMpA80nKlqdCT3ZjyRvk=,tag:tU3QgMkBWK+MKvwy1s9fWg==,type:str]
  password: ENC[AES256_GCM,data:xZ7qnxFYSEvk1FWg6EqS50UVon9fJyy9e476eXHd0dOUXiK1CVjoY+/GPOKdJVGE41UlM1bE4XLn4wXmvqK4VA==,iv:8spYjUgfs8I/vyxeF565we4SijM98UxGMJOnH2eSqLY=,tag:FKjonNGoXv13S2uspBagHQ==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:03Z'
    enc: CiUA4OM7eKbNlXzEEosxDwhsgAshsVQ+3KrkcI5HLWTkJorb+ehBEkkAmy+ekvYPneSnE8F/BE4Umj7bD1T03ZqKVFOSVHiNR/id9Ma6l3GGv2DmNStLhxQKflq9NIos+7AGetG5Fy8b8JKH2ie/Dbr0
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:11:04Z'
  mac: ENC[AES256_GCM,data:dbpJQyRbCgDK7/MKBMcv+Ga0YhnbIHFtnCQdYn8MtQrt0txtmfOmZwH+ta8JGgNa01X1Tn7rVJcxR2uU7XU5lgNht6sZOEhd3A+/vTC+AGlO6k1Gpcw9DPlVHRHgYIxbqVooBRVQdhScxmYLLAkI/E9CAfoklrIR2wGHGE+894U=,iv:zJWut3O+3NbgF2j9wbj/VDs6NbuiL6gkEtzZ5Ey+Gs8=,tag:qFzxQ7Oc0haC74FLfsGWIQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
