grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:1g==,iv:HioYRyRAtneKNlGCDeKXqsnu+ouVlIar3I9HRiaDd6Q=,tag:Y8eorBtUQeeUEfafeVYtLQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:wlNOSa09Tjv9Qg==,iv:C2xtmHN4tfTPxH/yz7kfHyzPrvGy0abZEb4Sr6FJeQ8=,tag:KW8p4HLjNKBz2xUif9wt0w==,type:str]
        orgId: ENC[AES256_GCM,data:wA==,iv:bB37UF6Aj/bRB0w18upJgSZlovxw4sl7H4cEbKd5Njw=,tag:JyDHpqwiY2MYOXANy51ETg==,type:int]
        type: ENC[AES256_GCM,data:u6VaBHvcjyzfjw==,iv:r3TcIGBp65MF428OXIMWocBk57npl0rsQ7SPKevJUuw=,tag:/i3VSNjMZBr9kGWQJYbKSA==,type:str]
        url: ENC[AES256_GCM,data:A0GYgAzSPVpxu34sPBEDPKe+5Erbfhd6hyZpdDtKXSU=,iv:PpIeWRituwXdWyxD9yP0ZR33tzutoQg6UeGxxiPqUHE=,tag:W6Lch3aNtJeaMxf2FfEc6g==,type:str]
        access: ENC[AES256_GCM,data:WNMwBms=,iv:HlqFJD4IcfztQ0W6AG5aDtYqQhHcnRymKMaU679jFkU=,tag:RFf7K2i75npP8Xz9vgZHWQ==,type:str]
        isDefault: ENC[AES256_GCM,data:OfwC5ag=,iv:ZzDov7pm1zs8YQzuP8QhdnqHJstt0XtixyTViq6tlJM=,tag:J+eqQKpUejcJUtlPR+m2tQ==,type:bool]
        editable: ENC[AES256_GCM,data:5qEffwY=,iv:xVeVyQOy8V1YeMEh0LSrymXlB1/G0+CmxUKH2XTGfbc=,tag:v+8oXFgfIwCx6JV+3q/BOA==,type:bool]
        basicAuth: ENC[AES256_GCM,data:r3VI/w==,iv:eqtH4Tiwl4gWI1ghp0lokKCVY+MgKvAuqRncK8IWLks=,tag:7nKI61vM/lY19XcOGA5Eqg==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:K9WKK6vpnslKd6lVyAAa9tocq3cd1iEUyLUWtdFwqKKyHshhGT+855qsYOU5xX2iVWPrEZZZiKiHbFqVOmCJ8g==,iv:MZMw2RjeNhuz9xWnuG1HCZdoakEJKhKlUc9R1UwJn0M=,tag:EWH4reNDcj9UXz86BRCliQ==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:HBYeADduOQBjgprNpMdgVhqEmqkBoq1Hn7wML+DhuIhbAWHlgdVN5seqk11BEpSlYUp1h8RnE+L850JXiKuYEA==,iv:v8Q4ptHMLqBhrzZFTja5PcIvNlKANczfyUvi2XkcU1s=,tag:DhgnzyKJRVo178appANHqg==,type:str]
      - name: ENC[AES256_GCM,data:c5haJylTnjZDqxoYyb9orJYesTduUIiHcEl8PAVPYQ==,iv:C4e0VhiJub1RNdKm8eMhIIyMwz3+iKv+ipReUBerjcg=,tag:nsAx3JJlfDq0WECtf7KVRw==,type:str]
        type: ENC[AES256_GCM,data:bGTTENYG7aa2RZ1WX20OxAZxn9vBOvSRjnjQ5gKoAw==,iv:b2w8yHp0teSJWE9f/WNeyQjMIJnPSbLWNbReSqmNVAw=,tag:7XHMCqqs4SILd4KYIXKrmQ==,type:str]
        isDefault: ENC[AES256_GCM,data:iv5E32w=,iv:t6SSe6zFurWSfiG6L9jj3jrMqTWSZycnrkIqO1Zje5w=,tag:5cqhheNjSt8ZxqcGooUUlg==,type:bool]
        editable: ENC[AES256_GCM,data:YeMYsQ==,iv:+pidJUMZ76Mj9jFhkuOWndVerX23iv/NZSbEXzlz46o=,tag:6GYYqerblef9fNJDobRDoQ==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:rY2lE7/iGP9j/EZSxg==,iv:e17aqSTLoapcypOJQFOUlowlpdO3vWjX3O3A98tza1I=,tag:yqRpeGJI36l1l+3afYbOxw==,type:str]
      value: ENC[AES256_GCM,data:k2+fI1XMBR1rDDSG7Dv/ecGubgvUCfjHCRnz4fUQ9dnwcsSFY6JEpqxVj9G21wVhdBgRzI8mNvetscChmRgbGIlJ1CeY3phMr84+udjWVSd/MfpGTI6YcC1mnRV1lAne1aKvqdZBXj/hOdFdY+lnkMXZq+6H/pA9HSREbHT5FfECl2EWxUq5qSKWF9KCsh6I64jJWwVbRKDfZQJcksXKCr1SVM0Y9SGJHEzN9pilyQaYTg==,iv:xd09A1FkiJfDFNB7QRQFWpgLEuBsuhslklVtnEP1wNA=,tag:7d8AvyJO3+2Rk77c/sNeYw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:O3H16y6tCrUz/6qLC19EFWQX45Fje1t5efl0g68znQKoJWImGRpR6JjnpFm1lKuXi42LQmjFbKa+he5i16mcWw==,iv:RbphY7PawtPjdefrpPmvCJHFnwdxmaiNBqEtoocskvk=,tag:V32dJDJbDcnAxAZlulD0yQ==,type:str]
        password: ENC[AES256_GCM,data:z4mlhAHmgvzccyuywR/q7wY1TXIYmXcTFm1P1CnQ3jGgBiV4WTfhrn7U/dbHg0FSnuyJ11VtP0e4DL4p00rHNA==,iv:XZTGKBuNC8WMiuVtKVTCTxGhBHbaMPc/xwbZK1+bYEU=,tag:GaQrz/RJCk2zk2vpJkgwkQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        J0drkJz8V9PuwBTA1ctEymznzwgDri5BsAdfL2M2YT7zSOgBozmKiPaFHxh11ipU: ENC[AES256_GCM,data:IbaJ77irS7QVVoIcGYtdsfLRWMpG8lewRppHcPuuqvBBi2XRHosc0QGKPg/b0NYPAYCoO9nmRVzPv8R2,iv:Fwj6ZJQ7UF4+NtcaGkmmIYgSoGtauCok4X5Ghggrars=,tag:nJddepEMEGLCmf45VejSSA==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:qblDpg==,iv:CktP7cqwdV0SsP7SEq9K7hZTjs5Xc3nKdQQ7Xex/Y0k=,tag:6RaYXPbami3hSNZCcRbYgw==,type:bool]
    username: ENC[AES256_GCM,data:1JyUpKwNrGNy19SEP6SXSXwg+SokcNzfv+AA7mlFkxYbs0y7cfvNcNe6+55wnl+4qprg/v3nCMAA/eylY7Zf3Q==,iv:xTU1DXUo3rOvODWwVhy+msHAtXPatx+dO3ce+ARWuuw=,tag:ar/fBSrfZnXISwphj/YS8g==,type:str]
    password: ENC[AES256_GCM,data:aVhnrmtydJwaQTlkmVJ/yuUxEmvB259ytq1wJhgIdaQ6wAEQ/M06XaK/+iD//2zOEzpimM4lrSKV8i+ZretpMw==,iv:sUXEMuQb+5g9pRwpLZvc9YmsQPirahsTVGcXCvtV0MI=,tag:9U1w2IP44lNQTu9WjcqtXQ==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:8s7vS/z7yS69WqGE77a85ejJ+3Nr8curdiqaVxo6lQ2x050GB4FJfUmZ2G3VBz7U29Z9rk8rH3mh5jziRepedw==,iv:A8JyhyxbofMXtO67d4XTMSTLHRAr/e11vGPuMar11tk=,tag:h+JvZHby1ykK24Tf7X/jXg==,type:str]
  password: ENC[AES256_GCM,data:KZ1qc9Td/9wB0X0PfEfKj599eHf8POqYTjFQwZ9IlmLej70fnwOHvfayDWcc189abcnv7L7o/VReGLJHguq9OQ==,iv:1YtSumFJdBn5nkg4mn2Z6iERNQN98pnTeanCLiic6Yc=,tag:zx1Fg2haQNdDujEQ1kC6mg==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:24Z'
    enc: CiUA4OM7eF/fY5d/uylMdnqeJpr5uer0Zfcus8xkaANqP99MihE+EkkAmy+ektZsTadk4RjSo34uurhNYxPrZA6D+EcZcheBFkdiQsWq3SSftEXaCILoxv4QsnEOiK0gTYP99eNlne/kA49Q30J9pvEY
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:11:25Z'
  mac: ENC[AES256_GCM,data:YZk7WbgF8xarKcu1o3bScbEPDzRvqGqvg8fneTf8KBeqjgoDwD/qgtvqFpTn7wEDsXmoNYtokFlWJ1y9Jj1JJ5CXNScm9kOIJ8Wzx/FXBmmY4xSWv1nkJgvVIwu6sWDPpQmK6pm4MxZgHT7u9TRMMG3j2sr2HNfYPlfpog8v9hQ=,iv:0MFSqgMWw7LvxXIgGjam7sF7toEGJ/2ULCpvLX1xlKg=,tag:KTLArVQTLpnQRixTAdbC1w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
