basehub:
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:WsahNcD1m6h+zleU9bsiblVTNLBxMOD2CvUUiLc/2l2qvtrS5rFHMnUZfXw9iGDzPbrTFVNNfTKp95EuTQFWjHclkgdXNmi8nZXDn0rt9K7meC6eoa+cYqcrJ9gIwXDZ5ZTJPk0GVTIPABkrBlChKWt7tkQCqOBJbu3OvhYfr5LR+rQ5XbDdOPnw4uRfTftfjUcDhK9ILqrqnB8g5hBQK5k6NP+TzZuCfPOI2YHOzyGNN2vTunWzxPyXEGU8/C5kd2zEN9HBWilY4RMng47M1uPEygiXKQC4n0H+MbFdwuAEibyAJiDcJqInp2b917ny7/M1Qb/1nudl3jXFev7tTOyubDQ+OsoE9k+YH0OzbA+gHDP0VDWtmNPmpjvNC87x0Ql6DODr5WGGBdKAWBiVCph98gbORs8jxOEVk9LejAkT3of3NTX7ljXdR7zULXFgTMdEn5dyyfGLT59rLYzJrk90b1qPzvlaCQdg+J9Nts8X19BZMp2cuhKqMMN/VdCUyOG8vKAYkq4U1A8hvo5Kae/7Y5pSBHZyUcmvBpCwzU6KpFzaFLgVQfrInEJXjj1/Jy2eK6sfpx0Ku8fFn5rCRU3NYJWZ0yF701WhHRwDHfKP0JZspATCks6VhQyaLbSrUXJHWzmL8F/BlUx2ckRSb4KN+HfdkZihK1CLPCe+12hSVPKgP0wJmN121T2beg7+gxfrC5A1vGWgW3e/W9pOmFGn6I8u+jTf/j6tdun28Mo3DPwetfj7r2iiFI5DNwNwsDf/n0q4eyMg+BPVmHP5jmq/Ka53BTBsLFbcfQHBOsHWAX9ACBqjr0oJtIhCloYXKA/O9zeFSIqUWNkmLvguF6e4ZtWfxYuY+TnFO09nyJGzhIw+hOxINNT0+i8glWIoExT5I50duW09Z9jcHkgoeaJISBwXkS4YnjeH0oRCOr4/zQUYccQweyJsxGW76A2krnVsts5bAAZ/vqHOopLogJaa,iv:XuvVsSmL5cm+KDGKbUsJYT9X/zzhptkxsSbgDzw+xCM=,tag:INOuZuWwCO8Bc15ytEjy1g==,type:str]
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:VI0OFF7o170B3//p7N3OCXdm7zU=,iv:Msp147JI3fATAS8zYc2eHB0vnlEavdZlez3YxSFY0ks=,tag:qfAefTaU8EcyV5dGcBDkLg==,type:str]
          client_secret: ENC[AES256_GCM,data:t+Xo6xSTkuGGQpN6LcTGpooThjrHYHXvNCtoX2oLieRc3hsHa0/1gQ==,iv:iNvLtoHzU1BBoslo06bG4sEe7UIBsplnJbGqFhtHoVE=,tag:H9R+agh9AKhn9J5lwc++aQ==,type:str]
    singleuser:
      extraEnv:
        OPENAI_API_KEY: ENC[AES256_GCM,data:NWgOs/zrqKLVkeI5DH+Y3NXWe9FOoHySpomX6+JxybqUpNE=,iv:ar3sbAbyj1lxMym7Zi3eajBVuL16GGzcuqmvoQ824RY=,tag:aW7WS6bJB2GZAv/p5kk4tA==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-10-08T12:42:44Z'
    enc: CiUA4OM7eBnGi8HSmhOCe7TC80d9GhBNC0ryZca9WZbKsjXYpbyVEkkAsHDEl3gpbwYpCqy5G7IlTry14EAp+hEFXzFCTTLoKlIVuqrGaFXRfgMeQ0Cl8RtvhsLDh4ADmkdUf6av5A0ZUU9vt4YGe2cc
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-10-08T12:42:44Z'
  mac: ENC[AES256_GCM,data:w3MtFq7Fus4F6sVD/dXI478OvnV3YbIFXF2CVQ5sJaFqfcj90QO2kefX3nt+5RXXudsbanYpsjN0vc/FpcYviy0goIcgawTbguJI+kGnLuicrUdpvpip54I+rZLAK/uop8f1TCAZonHq+0HJ1XM/TgbpoOWrqR8gp35JcAaijy4=,iv:VylPnMpFHjzOD5owizjT3QkpKbc9+vT5Z+xx7MGINrw=,tag:CG0eT2yXMqUAmGFgTtXa2Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
