prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:aNV+tkcX056Qkl+GVQ==,iv:ZsC74rt5DSVAGwIPhDYlJZlapymPB3zdYlbPrmQlWK8=,tag:nFnI39SjTeUrizyd1G6kTA==,type:str]
      value: ENC[AES256_GCM,data:zSOCPij/FpIXtW2gj4ypQdo5cB3vnYbAN5xcoPtUf7CMkewM62KLoWX4AB2Bv7HeXuhqDZ82RL2RyhwAy1u1K549VjWCjd61a9AWG5Gs+D3a1qgWV6a1WILwvTlrmeDNbmI49RKqcEnoOBlUxDJjtjYl3PIMPernqCRm47E4mO69yKTzaGB8ULr+4E/EwztAAFpLoLirLufV7orse9woa2MYrB98QerTvZYEM6RHgivB8w==,iv:ocm8+MU68LshzKk6RA6bNlFCLqvO3qOdMGIL9fTtyyc=,tag:nMr5Po0ex73MQ6LTFjF8FQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        J0drkJz8V9PuwBTA1ctEymznzwgDri5BsAdfL2M2YT7zSOgBozmKiPaFHxh11ipU: ENC[AES256_GCM,data:CgXicbdi980WQI1ZUcrrSav3E1KbSnZhxauPMQQ5zTxVeSP8kKNKkotdxcKosQOwJ33H+tO+OrVY9P2K,iv:xccbmta7lgB/YusfwI/IKnw7cRRGMZtldz1/XJFKUcY=,tag:YWfEmv3/x9a3LLllNPzJFg==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:+Gqu+Q==,iv:PQhIoP5oPXB4Ekz57lBY5Rio4zdrVxq3LEfHuN0lky4=,tag:hxFq/lWBLyVpvTIz0xKYFw==,type:bool]
    username: ENC[AES256_GCM,data:83I+MolA2waqh1m/DO3f6szgygrmkaNdiGI8wSBTbuHl02YSl8YbQNxJcHg70Nrx0kPREVhAVQWjvAL3YGY4eA==,iv:uz83kSb1MuWFFgXMhHqMmhOnehGtTyAvJcAOA4VWYIU=,tag:9QDYa6NAZ8vNFSLT2IhFeA==,type:str]
    password: ENC[AES256_GCM,data:1eOz3Rto72RWF/cs+YvNpuY60LXcVB6J9hNBpDhmM3U+0JW0edJ/N62KUWN1QSSMe6DR67K0yGIAJH/q5teuiw==,iv:G5AUTAlolenQU6IEbH5VpEQbANSdE7+DXqig/naqrTk=,tag:pEkHAR/SI4OgkE0MKPWKjw==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:Ww7KBX2DsuY8rrEeVZINKegqH2t1rW3nKmY2S53sfFV7Z+u/CEq0ACVnpT9SPz/cNg1yTu/+N7zDrWMj/X6NrA==,iv:GuPzO+CoCHjt3opJMbJFMlzO2Aqob5OuhT0z1zaBVbM=,tag:DQN/e5AKhhXiJECtNljk6w==,type:str]
  password: ENC[AES256_GCM,data:DGGSbNthuG4XweZRq3dl3MMloM3temnDWNgxKnzys09LGlMZdwsP8iU9rQ6Ga0Njz7pGQ+iygOj2YodGQ5wcFw==,iv:h5pghJHe8nkpReRru0/tEZjCmV8FwfcEwVlvvu3DYJ4=,tag:Vm5eRTNOdjzierFsKQEV7A==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:22:03Z'
    enc: CiUA4OM7eI55oCS0Qm4ugXIW9KKuU/+h3jlxM7vjvnZsKi3WgKQ6EkkAmy+ekkYvpii6QCBOLMFCZN7h5yZzriLXMp22j6jAOXoLyPWQyK3H08mDznXtHLlrGrynrAKsGsdPvsUm5tMnm+Pm1Wub9arI
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:22:04Z'
  mac: ENC[AES256_GCM,data:cTOOiRMQYNy63bk+zusFfSVxswLUgIT3cwRhKqz6TZ2N5PTEBsi2j3l3//zSVnGOzaxeviq5CxH9JSvLq6E8zXPzxfhfqQmnQtnYSvs6d46h2U7LmeflWC9TJonLT7Nfs/WvjmSlH1QcnKlv9KKX5u6iWhxstBZSBehXZYqZmPI=,iv:WQoJPi3tYx80fEpRvq6ZMPO0jaT8CvrDwlRFJIpGgLM=,tag:E8BRtHOXOGD0QqZ8mntsGQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
