basehub:
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:rWwx/QItthcKd7NgfVsKJ8gp/rc=,iv:9TBxYh4aVMIW9ZyRbaE7Ut6rmIIPpg5fjWop3iVrrUY=,tag:5l28YAtJd7o2r3BUeyL8iQ==,type:str]
          client_secret: ENC[AES256_GCM,data:p2g5p5SrmTwZ2c4//wB1sbqWmyBnovanW6c5nFEmOn+YhrjkFYYjEQ==,iv:tkxRIBA0Sd3YfQzr/C9WOz3KnPK6DAXEFXLFJkPw33Y=,tag:xthLoz/3cDHOXY0c5o+DBw==,type:str]
      extraFiles:
        usage_quota_config_secret:
          mountPath: ENC[AES256_GCM,data:6PCd0oYdG6SeCSSiP4Fw//rnb3eD1P8sBv6fJ3xzph/SaVF4B96e80icHAUyABIyKW6ufDAs9hE/OXcW6NmGVaN9ybZwjFDY97r8LYjJpK40SX4X1M8=,iv:hQdgbbTXAWv94J8PS4gqsYBYYb4MB+onUuyrqv/6CVc=,tag:CA+thNFU4GwDQJDOUYUasA==,type:str]
          stringData: ENC[AES256_GCM,data:cPA4VjUZJ8AinrU/e5zkdCFI9y0nFTwLBgJzgoyoeumrkQDMlG19P5x0tnG8O547xaHdJoFK404MR4gjGa0N3gpwdShiJ/pyTKfBSqbKrLJ4IX81rfC/H6mL1II7Yzq5QGnlYQU0rftJEHu1vUle4wzSJgf23pYpSvbB7J68O8atdRAixl/gG/vfldzv6WJUCIotnMs0DqjCsN0JsLkr8dLT0uLDwZ5FEqQrG1bWFC7HoP4zpU/Xm/l3oxSLsiPcxMCgLGHYv9YuoJCi6STl2Q68iP9Fm2vf+/WOz+Cc5v/7xR6scjHxS20qfgg/mxqSQqGI6YI+3KZ40LmKALgMdxoT+FRNJL9Wl2AOGQ3p0Xm3xh3+GeQLxWwh9KaS43llI3j6RlCZ9KHBQPwh1sZU08WpBPpdcMOzr/GlmDmpB3t0rVSPQkpvAoTVJnQRdd9VRx4svihNd1hW/P9sWp5aFt/u/onxQp7BnhmSlmKqrW/cm3zjINEf2QyTla1FCig7nDRi/Rit5beDoEE3gL0BlO6Qf2ww7to00YoEH4HFvqqhzeOT4Z2nxkgdx6Ws+65T3OxsZ4vazSH2W4OMNCsyJ6t9zDOVDrUO9nVkvd+HagMcLSyWWrH0QPmGMaS+ITxYwNzQ8sQSvb1Uqp0wGA==,iv:+Y+aucDrn4IocfgMZOn7x/C8JLNIkfnkkg6h8abQGaI=,tag:SkxrRcCU6WWz1ktzSWPrTg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:16:55Z'
    enc: CiUA4OM7eJkUV1RuN+PgQN0XOpDmpm9n9wwDdfGVQmpZ7KtzO/cJEkkAmy+eknU6acu6baZPQx/EncnZMO14sUNguG1spqUDRr0N/uar0Se80383S87twYsxnlNC+odFjGT80J7S2bvPoQcv5+2vCyo4
  lastmodified: '2026-07-29T19:16:55Z'
  mac: ENC[AES256_GCM,data:eRR2LlncfgZYRnDvl1BshAtF53sdv0kwqVFcFn2aPImcTdnNQznDiAn9WsqcnYsc6m2ue0/+dCGa5mSpaZegSHO/BrJoG0YN9Z7/Er7WMe7vpx8vUKNXDv+Jdt+4lUpj2Fm7UWjM1N/Q4rohKeqzneJnyX9mPMHvyBQhxveQs3E=,iv:kggaDGENQ66lm8st3Seo/iiFioLujvZ7f3QclsTir7s=,tag:IxhfhmKAxPSXeKwmNsE56w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
