basehub:
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:y+odthK/mXcBAkgGxpHHOw8b0zuAT41NNecaLlhdkkjVXwSUeUCAHwFVdk/tn2yqfh85/s2ysFGCXBFuf/HnonX2b+YAQd1YPzluSvSBRQFxmxXYs+rqxM30Gry8VrF+5NAFAZi99UL9aEXqvxkiI4QubTaN8xoqE6/eKjRsVS2JuzFnwJRoVKDpYpYflrz8SczA6mpOnEbRJOlESCyUWhgQsaprzmvJUzlM8CRNhXLf+JzsZtxQQt6SOhO2cxO7nKFAUhIibS4dQdToHd+GK+2J5BrTBVz/CFF9Rs8jeF2PN4O3tBZC9vP7Z+f1BKDTjVAeEUJvGCo3xDARorn+OszvgnRxXAOmpQax4koLbgjPGWI0At9aMUcY1l5vhXMkQw5PRukGEEsKWDTEWVQ76uFcNBCHC50nTkfqS5KKanZ3s30hEVzD9lKvUCbw5PioV7fM3QzBHNeMCz0ra/p8eudJUl9MZ6UyALN8dNndgq1bw1qqLhCSn5cN54K2uSlRyBrjYu3/IXdY60Nww/3V/Vu7wxdfHFwZ40NRXaElIfpvAnmkQfdULcvbhjq53Vuii8l7HIxX4RexppqhC+1oGRrqbB3qXDiLiM8Z41Wql8Ne/cK3l76J74cy8JWdGH7wVTnCoJe3S4KJ2mkZVMW1idmek6zWj5lGx8C+P6UeMFTRtXmfrNUxZUVQMoQUo3aBEgxVuvLZRmOeU77GcFK/qv0F91+og1XphDCRYLbShmipEVeT1xnTa0ctMGyAq2Kv2N6e89nsfvhwU7bXkQl9ChQ+jmOVt6ZZptXKCtA+9bStBsi91kc17EcgDfm5hvVQXQhirgjL9vGos54M0lGPos25MFhozwesg5e8PAccOO3mtXqUWD/VGy/TupsLR5zeM0dhTGs/JTfCIqSiGcDcQYBFc4Y3sR9wZlCOa8zbdOQ4Ard1boJlyxRlUmFzr7eD1BFG0udJGzvDT0ZvmDyjF3Xosu71hc0etuQqK0/4S0fxs/67tuqTA5+IWpTDE8zkLmQchO0=,iv:OCVfTiAibmDAtk6W1Io0y/zdOWCQwztqafY8/hFsej0=,tag:TGibWYxtzZ6aB1oYG/LQHA==,type:str]
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:ilEVTmjN83Y3YnOlBKjA9EOfUuM=,iv:C8143cwC6pB0sFueQq7T1XbbmABAHu6kiLnxbZy9hVc=,tag:Jc34Po9xZZShfq5l/2CEbQ==,type:str]
          client_secret: ENC[AES256_GCM,data:cSq7uA39SxQ9wIXAWp2FkEkGuzPXHCixp6iwRnkya9YngnUhufpIYg==,iv:dSXXOKhEt/ipOD1bWhcghks+Mjpn2oUexzJhjwEt6ek=,tag:8woToirTzLvX1WqHjbLpGw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2022-10-19T12:21:15Z'
    enc: CiQA4OM7eHhdeYFpxkSDTcwgJSCnGcXyuW+RXURXZyqVtBExJLgSSQDuy/p8cJdVxnALmGegCdGggKwgIqy27Dtr97EyJnjFxmQMGDQsWh3vL/2xXyL4Gw8E1cYoxh7r+ecwI4YmBOO+q6rBIM2fS4I=
  lastmodified: '2026-03-31T14:29:50Z'
  mac: ENC[AES256_GCM,data:Ui+Co6QlwS5PsrYpYsZVYVlFunJ4ZdO9CrbvAdeIOQPKCaqdNPKY3JgFe65iYr/lXWdjiemTykcSFroo5+XFRgtibj6+6KNxgNjbYscD5L3UfQIF+2i7HoveBL103JyPcuYBkmYuerA23bxxzib/t1RmIQfO11Hg6btZgO4PlXo=,iv:N4TcL6VjC7juE+jaRbLFWa4wvdooW3weswfGzyNcEXE=,tag:aEenjyo5J/8+RM+JKgHodQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
