basehub:
  jupyterhub:
    hub:
      config:
        SharedPasswordAuthenticator:
          user_password: ENC[AES256_GCM,data:61wh1LbVTiiK6neVPwtp1w==,iv:4RDVGhPyA6QKIEVAbYWQ37LywlI8PKp4UyR08Rcdi+w=,tag:aTiSStVRU78BlG/OVQ91JA==,type:str]
          admin_password: ENC[AES256_GCM,data:OaJ0Gc/n8/Xt787IhlQMuTCtyYpOTuAc2KoFL/VxzDDwjgO6I8THhIq47A==,iv:1785th9v/mWv1xoJsbHpw6GbccVki2JiahnukLUmEGs=,tag:6lZFV8fXYPMIqAeXS4vAaA==,type:str]
sops:
  gcp_kms:
  - created_at: '2025-08-07T13:17:08Z'
    enc: CiUA4OM7eK/VsLTEtsrCh8V+s/m56JPwDsKI3mIE2+sMDVgsZRstEkkAXpa10DqAg6p8ZMfa5mZpJHr9S+C7Nj3FEh1eb5d0a1jju6HzcHi01x0rLTa2DB2b5sVthiKLT5l4SpkKBW0iPAwl3rXOBmNB
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-09-21T14:12:47Z'
  mac: ENC[AES256_GCM,data:mvIXK5XNQhYBdSV1nWCIdZHT04RhhqnTZhHIf4qPLXXgZ1ET5hizzBkMw50lCLNoWBLDICKjNBeDqjeYqq0S4QDNdBIZ/VQWd/XqTfF1J2k3wX5kkwfPyUx8UH6wItLI0Fk0J5EUCE8huZ2iEDiK7/pKzdoZEm0zynU5M6m2A+Y=,iv:tpT8IIXvFCjiMdkYhT3sJxigRwswcBKW6tzdulYfM9k=,tag:eokkoD1c1zBEdpe/raPEDw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
