basehub:
  jupyterhub:
    hub:
      config:
        SharedPasswordAuthenticator:
          user_password: ENC[AES256_GCM,data:dUdsc9LHRgVBLyGLi6w3Jw==,iv:u4oHZKut3FF51o2doosmZIpwsgRYu8CBzLCLvIc1zd0=,tag:vR+nyVAxWRucDz34kcshDQ==,type:str]
          admin_password: ENC[AES256_GCM,data:fToycIA4LmyMoKpqqcLsq6KrjQiEr3C8bnnU/2r7j8A=,iv:8NzCzHhPrVvnqMEuDXpv5T7+qqzQb6Ka8AhN8Bqfx1g=,tag:E5gRxuIBS821RAs1C3ePCg==,type:str]
sops:
  gcp_kms:
  - created_at: '2025-08-07T13:17:08Z'
    enc: CiUA4OM7eK/VsLTEtsrCh8V+s/m56JPwDsKI3mIE2+sMDVgsZRstEkkAXpa10DqAg6p8ZMfa5mZpJHr9S+C7Nj3FEh1eb5d0a1jju6HzcHi01x0rLTa2DB2b5sVthiKLT5l4SpkKBW0iPAwl3rXOBmNB
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-07-24T09:10:42Z'
  mac: ENC[AES256_GCM,data:tHgM/DRZ+EqSZ2d7mHPPPq/yaMpyW92/0rNtW3a2g+/R3lXrFX5FH5IeiCxPlXWo6eUGgdTgM+IORH+as3ltH9VLRYzngsYsA/OwQyFWFbOsU4sHYU/5nfMOaYVST0gHoaY6C537uEXEYfrqk1+0CnlDDb7o56ewUERIA+s6iU4=,iv:I4Ul19HO7FdlrmBrm0aJMPjcqncMVZ0OYjowbkdrbh8=,tag:1+qtKbA5VFoZ2iq4cnAtig==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
