basehub:
  jupyterhub:
    hub:
      config:
        SharedPasswordAuthenticator:
          user_password: ENC[AES256_GCM,data:N8kNL3FuAiMZ,iv:Bel8zLH5X5NkMLM78968VdlZmTYuAe99jl0m/QePwv4=,tag:LJc3MiXz3y7OX70D5fxC5A==,type:str]
          admin_password: ENC[AES256_GCM,data:fToycIA4LmyMoKpqqcLsq6KrjQiEr3C8bnnU/2r7j8A=,iv:8NzCzHhPrVvnqMEuDXpv5T7+qqzQb6Ka8AhN8Bqfx1g=,tag:E5gRxuIBS821RAs1C3ePCg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2025-08-07T13:17:08Z'
    enc: CiUA4OM7eK/VsLTEtsrCh8V+s/m56JPwDsKI3mIE2+sMDVgsZRstEkkAXpa10DqAg6p8ZMfa5mZpJHr9S+C7Nj3FEh1eb5d0a1jju6HzcHi01x0rLTa2DB2b5sVthiKLT5l4SpkKBW0iPAwl3rXOBmNB
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-04-28T19:43:43Z'
  mac: ENC[AES256_GCM,data:8RXj1vMzHS8b13qad2aJ52FMxrpakSTIw5xsiCcfZd2G12EpfvXV2+rxBI45zO5ErpgX/zAK/aYYyqJj6LB9Yi99cI62s5BIMHHWkXMcC95FH0FSfgsMWbgXRSuYs5VzOFcXplxJiC8zyk5BTQqVaFbG+1GzhCFIlnbdaEd1cFc=,iv:Rz0o1/aUx6+Lap2tQvV/rG25kZmt7wyv0dOiyIoiJlo=,tag:6S9fiDQdNloKri1QJNXHdA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.10.2
