basehub:
  jupyterhub:
    hub:
      config:
        CILogonOAuthenticator:
          client_id: ENC[AES256_GCM,data:V7SfbE1nwxakSwyCLhk2hL34QQarS2x2De/E03cvBrAUc3K06vvE2C8cO1h/lcsnDew4,iv:nJL0UPtwMl6/IRq8uDjKBG5XA65u21P4tsf6Mz70P8o=,tag:4Q9yy9w+8xo2sxDTtnaWGA==,type:str]
          client_secret: ENC[AES256_GCM,data:iqO5ycwRSoKFKWPBnjdAUWdSQCIuSd5OTEQywBCATMWQttODnZQdCapiE4h97WMEwSaOG0rNfZR+/AtEpHPFgbWgY8bcKHSss3LmPDerBxEm0z7HmWg=,iv:77WWumCSxdjY0WqolYWcupa9ISYZ8iPmJ4ukHWdqy0U=,tag:4xxusitRpP5F4sv/lRA4pQ==,type:str]
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:1BdAQx2Ijf9GGZWXylobVhnpwP4=,iv:TDzstVZ/sN1m2LEJTE29hCjBK0IgZlHgFwU6uvy/yeg=,tag:dM/4y51Re7sTatQ0u7RmQw==,type:str]
          client_secret: ENC[AES256_GCM,data:LB9vv1e4bSFuxGC/RwB4sTjU05dATQu4BrEf2kJoa0UA1x9tqrUBAg==,iv:1GRJAhqn+AD+l6IxEPf/uyu7SoqycniPAIVtytaUK24=,tag:WMUKY9ycf6ZQC5C6yU7z+g==,type:str]
      extraFiles:
        usage_quota_config_secret:
          mountPath: ENC[AES256_GCM,data:G4Ye+7EE62huJ2b6oq4E2hUclSCJcvqSVy7x0Go3PmnGh4t11OYOoHYkIZf9UASbbxZKGjBKnGE08tvv6Vq9P/xSVeQIjW+K59nfxaUo0m0t/J36SSg=,iv:2eBJ5hWXNjlIfmW0MuaO0CZVCjLIXwVAdgkyXIreOYU=,tag:eJQYV2bQSkfb7V2IShNiMg==,type:str]
          stringData: ENC[AES256_GCM,data:WPYznNNTgfwbd2IXsbGjvoxln2H6krS5D/7X2UrlWhme7L8V5N1ClUK0AIQbKQGLeVV+C38ex2DBDJ6qaUB8J6AWpg0Xi7f8HEMS0uLg6Zp0BnYGw1jKOqQNHOKPBlT9CoHSXcXXHdW98U/KRS8PhcSYo8x/puv3/Oy7GG23Y9Jj7MBhquCCT5KboCNwpbhRcf4ihx0Rba8cmE9CWyE2Oyfgfz2S2O/BMs4exfn+rBYG4VYhCOx8dfzkY6eLgUVwxpNy6Q1ZCsPMxjCdk2WoM/HPWTPOwP8gcSuSB0qOkT/xRrzcgZJi61TZcVlc8EPdAaLzdneX/7oP/tFvPx3nbLbhi0bpcqslEzUIUGCuoJB0MAHreRVUVpHWd2JvqPGnd15hixAwjlvj/KWDQP7k1flIw1QICGvCh2N8tG5EO6Rk886OcyCfzlYLF9EjR9NmJGE1GvU0WpLzyffS++BaUxu5Cd6Hvb+aWmkDLbsWE7S2izpsiC2JXNdHwClC6pE3GjvyrVDVgBEbKI8+4+671vOIyfgwI3CTeNvEZhClf8VGn41UOivoXDDs55AlpR4uKsxK/5Z9GtcXXlvJK1mxvM0kzpnERAJYePg49mOno3r018ygZXdpKDH7UYv4dwt8LF7BVHI9FMpAj++G0Q==,iv:8LIzrN7eC3kombRhQfGTt0hE/NGt+z1ZMfgIOVEZnQ8=,tag:pzDnJPH7kj7ImdMW2H0Mig==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:20:43Z'
    enc: CiUA4OM7eGuvf0wOydFiJokNgf1ZugmRUsLVci1jNSJc5wswWqv8EkkAmy+ekqHwuavT3JGr6Nr1rRejLwxTUw4/lKWlFLo0xSNiRb4RQkrLJ7BQlD2Sit2Rq8zZG5u1dT28HSaBLTTBPs2D07jAdHCP
  lastmodified: '2026-07-29T19:20:43Z'
  mac: ENC[AES256_GCM,data:4jWNYIgW531HsOfERcrkWAgQUC+rKyOwlemwytP3SbbOpPJr7+yusXd+BeYQt1BhPO/SvfvYcYfr6zFx8hUqtmWqgr+6z/HrICWm0eaupLiRECdLZ4aPBteLM2ppbbtqxesCmsOxRhV2JEs7abHEJW9MISrgV+CRb4bXXBz+6is=,iv:Vd1TcyCzQ0TGkSh9EdAebS7w31pLbgLH1DFDUpWyOMg=,tag:EFmZyRlVvni4O1d3B747vw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
