basehub:
  jupyterhub:
    hub:
      config:
        CILogonOAuthenticator:
          client_id: ENC[AES256_GCM,data:8XC9jpW+vpPbUegdU3K2PhrfSP5CtgtlezCzAPKZc3dsQVRZzzKtEarB1X85z0DPNkzK,iv:bp7/+mr5lYik8I/7lUMG3iMfV9uUWJ8q3PvdE6TUfoY=,tag:FhPdJgB8nmYDN/G8vfTFFw==,type:str]
          client_secret: ENC[AES256_GCM,data:ybyAeE1XXOjLwyTiu5ITuaCXWs0YhR+ONwfG2z1d5oYzPOYEA47X7DZnzS8jIMy4VKC4m9fR5nF5cczFNZp9zd0iPAJczkw9mZCI2GkjJ5szlTCX2+g=,iv:CwO6duXnennBZAa3usYnkBZAfJvbNwPJdxqWvavNXvE=,tag:lsZEtzP6SXZ6cOJ6H5RJAQ==,type:str]
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:gVg+mWlbyejUQ61TriuLirBmW5k=,iv:OhFXCypYwF0LguoMBCNv+Yh1lb9b5ReurqGo0ehHlXA=,tag:ceeTn7t/1hPVdjvbr5I1Ag==,type:str]
          client_secret: ENC[AES256_GCM,data:GV/IPUzMrKdYWiar+A9Q+8bTf/5U3C8PNCRQZCW/PJ6wnBteXYbZyw==,iv:RWz0nqvAhjL7eFSP9wYVNwJNoBi3BqrxQrEGrL0SocQ=,tag:GewvPaF8znbzNo4j5CVRxg==,type:str]
      extraFiles:
        usage_quota_config_secret:
          mountPath: ENC[AES256_GCM,data:Tb02xBMRKXrqant4Lj5Sb6pmxW5KbiLMEmeoJ637c8APsCMoycWcBjvaqLT/Wf/WnJSPmakW04599bAaGH6Ju3UXJtMiL34be0UlGh+IS3tahCGSNU4=,iv:PUhuwtc74Mbclg+6UMKa4C5g/yiSCH7ckgmaoTImgNM=,tag:b9GuFqABJXz2lY3dHFY4sQ==,type:str]
          stringData: ENC[AES256_GCM,data:qbZ5+QVn7Je6iSRVQrdD7LSIG6QwnW0DMXy+6NkWDEWmCGfyCSlvN+Fs9g238n2EyIQUKeZvwDVf0XIkoJPNcHheZOh0lpFP72UOzqcBTEbo2xuUdlXDTNdzJfggrlnAANW9o6syC++e5VIqadBMQphsktdkshY/yu9ciut3bG48c5j6RZLxxMsimJ77o67JqWeRQdJ5UFZ0Bmn3leWRq/0FbNxGVgzJZhZUAfa8hmAYXH996/8CRZ2e6Raro13Q2lxqOSMHJmNUe0bkGb8b9Ir9KRO1qMuP5h8ZkNogDs2Gq478n4K4uivgmgoerRlNHF4oCCgwKlu5ilgGb3jyylik7KyEQHJGWtcGyhpl6VqFeRNyEZKN8m6y6SiO20skBer/7B+eWpKMtzQ1olZbC/sdRsJv4jy3PV/uhlPKvwW+7F5ezx6IJRIbaUUCp8f+oOC/cbmpmbNqpxd9oST9tUtse2/FQ1NB+NR3JO4sEmjAab1oxOGcSZm5ppd1ffNjiQc5lX1SD/QeptRizeO38MKKVriFiel2lRcYGJ78k9Nr67xXJsoyCry1DmYGMwJzvsnxmuCa8XIv+uzeq0Qv/WOn7lO7Dd8ThNWV+3y+woUHDwyorLs/WzExH0pepnPWqiNYMe+keU26yiRCsQ==,iv:JbabSnm5O2wUnNshvEF+r1FYivl312fTkau8WDuEXLg=,tag:4CF8p9ZdLQ9zK803WyUQug==,type:str]
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:hsOo3FwJhUQVfM56PtVfhBoQSd8DP8wBkTmLhrcqGjiSIAumOfLMn0ZIaCadVPZi+XVvpHxhnWGc5IUmdpDyWwNWwJcfsKgtX9jB0Kanpev+rS8Hb31U+VugMFmRPHfgvUscVEoG523PdlaxQdLoYP0mgS4lokQRw9uhhXTJyjq4EsdbASDniV45wlsVZRkC/GIuUzM2koOlkXrCtmlRp+6wEGYCb/+gsbE+gBjkzyo/RH8atBhvwfOaW7u24maC61/QBrg=,iv:dozI3FecqOv/5zI2VOUsF/rzLuqiBU91sUdsxy9Q+I8=,tag:0+jEVRkhU6+6Yo4m8FzSfw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:20:45Z'
    enc: CiUA4OM7eGBlEFFhNanqUQA8eo5qn7hN5p7XGyjOGCoIybARNk5NEkkAmy+ekg54dbmAaTMCW0Io1CdJEhXmoM1+Qep/0ZDZoAk2/1mxhx3/C3rUix7PFbSAa0WRLknDPzYSHQA66+AbAUaqDKd2wVVk
  lastmodified: '2026-07-29T19:20:45Z'
  mac: ENC[AES256_GCM,data:wwTUtrG9inR5FpYf2y7IXQOcOtxyYHBiVmA2WR5YcB/e1oVcg4f4Q4vjMAoH+A5/sBd8gI9tUtA0C5U+D4hUaJn8fOMj7bm0+dmCC0CKT3iZD+K7eDwNr4C2fn3uCLFIOemU2XOMA3rqYjzvzCOFALtXu5kB+y2w0ZKONMOiWDk=,iv:339u6yzB4KjF5zkJYbiGWx2rx5SskmKv6mCpmG3dk0U=,tag:SgIwL99kmw3RqqgAg05GoQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
