basehub:
  nfs:
    pv:
      serverIP: 10.100.90.25
  jupyterhub:
    singleuser:
      extraEnv:
        SCRATCH_BUCKET: s3://openscapeshub-scratch-staging/$(JUPYTERHUB_USER)
        PERSISTENT_BUCKET: s3://openscapeshub-persistent-staging/$(JUPYTERHUB_USER)

  jupyterhub-home-nfs:
    eks:
      volumeId: vol-0728f7b1555016f13

