prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:fTZ/MDlNBSFq1G6JEdxiGv/MmcLHJT8i9yUs+9uzFW1MEF2tuoBr74/MvLOtuLWosmm+eCQR+zIlxg5ZAU1jZ0Tfxct9ovnsacnuEY/k05AMq230CNEIRGEu+9GiTVc/RbMmU8zZ9wYGoZnCeOQ16njGtAHJMhWi4KAUgkReUGOzgrwJ3Z+PBgiM7n/sb4fU4OV6Nx6PBDKP0WTW,iv:dR6lJ/G15ty6YotCLO4S/Tc9bIKhj4PjLO69UU4sE3o=,tag:ah3bwxJZCwMCEwTtJA/ZuA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:ZSEpf5q+IY+CcNWKCFegdEU9f8CVmserx3BocqEi6QoWimrhQbpKmTu6BuqaUBDt3xmiZ/kBwf9Nh0OsLSvZsg==,iv:lG/QFhfviKDIlUXFVaWOEkdnXbgvSlgKtS31Op+O6i4=,tag:gNSJyLRCREHZZii1+y1Hig==,type:str]
    password: ENC[AES256_GCM,data:Q8hP6ry7HPoW8rTJ+VAnA3oUjusF6I/RldxNMAdHDLmiazQ59XzLrpc+vRb2ED29Snc8vZIyogcqesZZZv/PDw==,iv:8FNn4QJhcAt3FZAlcUO0h98SQQwPsTbCzE5hf1pt5lk=,tag:oMqODq89o5Ge5pLheiEAoQ==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:atTSAephZAAvbyBwoQ==,iv:6YekOYktXNPqK0qEPabwKV8PH0AZpjBw5oyoY1FeEF4=,tag:zHA9qKlsbrWgvchUckao2A==,type:str]
      value: ENC[AES256_GCM,data:8P3DXF8qqcKloLOLzVG7vt51ZAexHN94fCOwegGkvWFEstuL7wr3nXPNRLD+LGFPcXUkNh6fy6cZDsSW6667mYesnHHjiGgPe43QeKeWTgeL/DlxJ6yZUIM+Htrb0bn+1cF7+UM0TmomnPWIlY8zb4Rfg6JZMkiTRBKjoDg2ip9QcHmiEODbrIrm6a0wMDuOPZ4oHWfXwYDSTILz4F5lG2zOhgn7tkgD/fUtXdUP7lQD4w==,iv:fODbvIop+ynQEUKFa1/0Y+mqYm06QUY+lY6VJ7dnEms=,tag:qby+Zvh/+l2sqlOcOBkcOQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:u0xkxQrIJpnme1mlaggm2rZE1JXNxllAtEbqRWq2LqYE6pCWYbaqUpKaJvqdK4g5kvMwDowM+glSJoKbFTOtAQ==,iv:FQx3dHsKBuQZz0qXftwKeSd/i/O/zwHAC2+HsUdUimA=,tag:VQz3SW4MgQ9Q3BBhtRee2g==,type:str]
        password: ENC[AES256_GCM,data:i85eaLu1bnBrvMUaA5gW9gHyMpfNU1tpsnMl2wMcetuFUFswW3rfHfw63dl2YWMwNiDKmPXZ9fxL4NPW1B0qww==,iv:uQAGjl5G1eD8k7lNYQeVynA6HsiGDlczxzIx7j1QGTA=,tag:AxGH1R5hrkLKiYLbGSMTrA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        W9oHidAdpoHYau9kw6cLcYrzfueKUETjqXuohZEqIM7DPM4FAut4T41Q6fhhoWdZ: ENC[AES256_GCM,data:UZtUYPM1swb7z4iFxc7E5T9w68DjII7Y+N7cmV2buHdGvY5FWRLZsNC+r8NYUvU2aeSgk45+iiAbDoND,iv:Sd+p+UtA4vTxWwzIkUFtGQ3aUYE2o/d1DiXjKAv/PUY=,tag:Lu2Gn31UuL9hV6BnU4tY1w==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:NA==,iv:iYcQVk4zhcBGIIvA3lkPANdJOShGyI+bOvL3QSNvSV0=,tag:vWTt8XHSyLQkw+1K4JBAtg==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:W+KwFZYoN4sxxA==,iv:uLk9lIg6qNvvBCsJHzSc4+8j8pzIWk6ZFwOhKzt0N30=,tag:bKsF6+S5MWIFAtwtPKQitQ==,type:str]
        orgId: ENC[AES256_GCM,data:iA==,iv:s4w/+ECaAZJQXvPDNtPio3kqNbaTRH8TWilzOZBtKWg=,tag:2FUVUkmR06T62cJp/U7V4w==,type:int]
        type: ENC[AES256_GCM,data:pxBEev4vOAy8cw==,iv:i5i3qC/dERPPG7T5mwHcTVq2KxvrzPFb58UoKJFiIi8=,tag:8SKQObc/XWvNbzDXJ+G52w==,type:str]
        url: ENC[AES256_GCM,data:wbhlHIEbQVubUNN6q/iAsy6qpAdY495a3yH5eoVqf3A=,iv:Cr5daNdF/1fMYfXA4773RRbly/Cq8zJmaqa34J75l5Q=,tag:itvRdzYCbvKwX0smnC4N+A==,type:str]
        access: ENC[AES256_GCM,data:50775rc=,iv:T+sUzdOSbBhdn7PwJvMZs3mpfMi5OpQDXKZOY/L2q60=,tag:WgNFwUpDREpJWGfynQKkMg==,type:str]
        isDefault: ENC[AES256_GCM,data:DuIEAhw=,iv:5f/ClowE1jD8TO0GLbQGsaL9mzN4I6OfcC5IV9iikaU=,tag:gz7tyN5g8wnhKhuF6sDxZw==,type:bool]
        editable: ENC[AES256_GCM,data:l4LA42A=,iv:GMj0eTbwM8GXHXjffgQJkwvRYVJlJBAIlXKANBWRGd4=,tag:d/fd4R8SQLA2KrIfaJH1xA==,type:bool]
        basicAuth: ENC[AES256_GCM,data:z8tCVw==,iv:kLXRhjkRtFeHKPYlRO8Q+3/WjKESEi3MEVtONeEEeRc=,tag:MAvd+m21boKT6mjcArNZMg==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:u6LpegJbZBeNpMyfYT695sqSqMJLlrtRPIZlHqrRWScAxtz9DRKBGiVQKVtBUEyw9IpmveZdPXCPEkVX6f0onQ==,iv:fY1e1boLolFaHh5oC/edWO6s0pTEP4hGB3M9HUVcrTQ=,tag:wHU0g9FkRg9cab2azSnmpA==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:659O/IDlH2kDnXjzxMwLqjm/aHpAjd5JK1EO7SjtVIwhYpBQo4O7W6adgvrPIwt4he3tcU+NAG6kHp+5AqYyfA==,iv:ciXTLPiKsfvgw+XjyylolTXG9fnPPNsTlLOuuiLhZ4A=,tag:LFJnke2ecI7ORf/2fxR9uA==,type:str]
      - name: ENC[AES256_GCM,data:/8dNRnh/yuq63S0/uNShG+OpFgbjJR8tQWg20OCcvg==,iv:8yiWq7Lfi1xGCmXwDxXyKjmTqyTClo9KOkSHpURVIvc=,tag:5ObRKxoj3xe9gl75Csj1ow==,type:str]
        type: ENC[AES256_GCM,data:eEqZMELKr5SvQTUOZLvDKAMfMVfz6sytxb5ypNZBlw==,iv:FMeQChs3ItSRbVcs7LNBYZvbX4C0XxxbscOgGAtos/k=,tag:Yyk7Bd5pkqMYdqIvxgm4YQ==,type:str]
        isDefault: ENC[AES256_GCM,data:kavzoPY=,iv:Nw5iLpEYXNaF8MT/4GqJ1e4bOZTvh4OOIJkaUzBCnNo=,tag:ioX5oknxjb2u54uG6pofSg==,type:bool]
        editable: ENC[AES256_GCM,data:EYmQOQ==,iv:UC1MgZUMNKoXixm7255Qx5JYwT+ocHhLRBhQZ2QqyDM=,tag:UcijpEhwOKRcn5wZb82p5Q==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:6HVy9Q==,iv:fblx+HCNvcBR820AbCjsuDLyXeR0c+QcC5LAlueFD78=,tag:ItlN9h58c2jjH4uYTm7I6Q==,type:bool]
    username: ENC[AES256_GCM,data:fH8QGJtyj3/aBJKWNhqCdg1wYiID36etY2agrD3HAmOTvo09QBZmSNunQLiEjCxyDwxjABtjUpVx6sLyx7Nqkw==,iv:J6sVnNanxm5SAnXcDp63tGSlVRo0b+aV+SFThzTsH1Q=,tag:eSn/gjA/L7ia/KRVI8XKIg==,type:str]
    password: ENC[AES256_GCM,data:WFjl/G0GiKAhHlJN9LvWICYk/Armnb9JqagiccCzNUW/QyZ+a/rH4qbSxs43/q+d4fZzHzU4vRn19JBYsdFb4A==,iv:jDhZALrGoFvLP01PQNmwKg02hAX3lApERskBBcqzx3w=,tag:GLHkhWal9JprVE+7W+Dljw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:14Z'
    enc: CiUA4OM7eEBTLoO9X3PwUjvZ/UZtpZUR5K/9v9w/iidEZL6HCfvVEkkAPHlbmSJCJk0bS+7gAn4XbcmupDVCNYV+EdOMMqoxTY4WQ4AyqMaI/1py8TGBR0Kj/6oiH74lKVIpmHY2vFgWtj/HorD2dobv
  lastmodified: '2026-05-01T14:40:14Z'
  mac: ENC[AES256_GCM,data:hfie2Et8Lf3M/0ZyqRjE0jG7y23f+lyl4zFBOuXTzQaCskCjngngI4zMCDddxvuWWRP3H3x4fDaMtOwZvOeOVDcZ2EkfuRS3doMkPCW5aSUAyOwncjX654U9fClsfvtQ517pFDm2qpZmzg5zkLGqLL9il+Spv4NJ+5jvVK0Mbjo=,iv:HkZLn5XcHfvehABOSFwCsLmYHWKPB0tDzlzCQh1+X0A=,tag:NN0IxxGo3AlVu57HV16VxQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
