prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:hmUVsPOfJ4FB3HIDxg==,iv:AlZhGOXFz6FTdnDb9M9zVfIeFmpr2SnUliis4/obAe4=,tag:2eE4vu8Nb4VIiJ2Gbptq1g==,type:str]
      value: ENC[AES256_GCM,data:WWMgPkTL2mkBEceTzQ71pr8HeBdQiWyGxl6x84UskQhTlXLXaFM1DZRlasSQ/e1ON1UoStbdo30kIiNLtjhhN0bjus7Qa7mDk/COdhZ78yQdTyeTuklYXstc8Tc3zwUK08Ihe5oXbgdGZdLYcjC1EA2SF6jzbqmfEBMjIXAFO6xWV/nPwyYGFfCI90/sHIsKmnfts4fAYbZOiwO4L0Lkd/Cac2Mvssmka7Ig2+6pB9dA+A==,iv:brFpsTvpwDwL+TPjLP4O3ACuBfkgKySL579FY2+IaqU=,tag:NzGgdZ9JWY/MTBgAzgoTCg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        W9oHidAdpoHYau9kw6cLcYrzfueKUETjqXuohZEqIM7DPM4FAut4T41Q6fhhoWdZ: ENC[AES256_GCM,data:kO0N4P/318Qbd2iRTX+1gs3lqT4+btKs1pkEywl1iGsRfRF14q7cC7KgTyHHYEBIwtNUIfvcLu6WRk7Q,iv:Xkq3esGWWBsWhDskgGXr/bj05+USgwtUQYiKFZhiROE=,tag:Fq33op8THyNUWoSd+A1G/g==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:NKspTg==,iv:7JqqeRr/puUn5layMbkfoaW1KgPp3yufNlDYTcvy4IE=,tag:5S90QMCEwgrefV8RYNolog==,type:bool]
    username: ENC[AES256_GCM,data:RZ0dPXjqHMdyNvDvlUbf1KsimitVn8PGRy5iit9cU0ti3eSypXZdq0eyvP9G2ra8tObwRwYH18zT1DrQ8sedRA==,iv:cwAKabuHisiveg+uG//7LW49z/t5Zm3NNLybJwKYncs=,tag:0WqQ0OP4f+0O3fzZZ88jVg==,type:str]
    password: ENC[AES256_GCM,data:Ogn5YbDPQYsrJPmZn0d4TUE1lJaMcYZD/lNIWl1MPT1cJgMjIS6rOylsiIATjGBgtXlq0jmtowG/oGFZMo+WDw==,iv:KAu54aIc8zslIW8luCN4VsOC2zOfIzDeeiuumhN0VSk=,tag:CY4vGL2YDOGoj19B/iuEZw==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:/iWsVWVUhf31gIHp+XJBHrXSDQx6aawpV4gGFf3wPjNaMi5TVyRgokCCWVLi5JiMwDBJlztnQzXnZJle+NNg1A==,iv:bcW/FCMms7ook8lNErmjEOWsLR9nW1NNIF5GYFx98uA=,tag:2NGS8DUXSbVzmi/Fd8HAgQ==,type:str]
  password: ENC[AES256_GCM,data:iBDB8Qi4ZadxxAtgk/rOcDzS3DxDphUjOuiL7/3pCvjl1z/XqKIhbz95T2gXBsSIZypWGG2OK4gwF8PgoK2Awg==,iv:3hV22piKILzHlzRsqp465/uUiqS0gI4qYQNtgRrYHe8=,tag:dOAIUcZrenc/24wMAaokgw==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:21:17Z'
    enc: CiUA4OM7eO4jbHE/Rwx1txSmm1SAH38L9u1h6U3BqKlZKsikr18REkkAmy+ekgjIlkOD98Pqn2E+n5O4SA0uS3g5kxmk4u/qQ0M7FyI5QOLV0+ksowfYE5ZUZZnPbcBspAotcfHC3CcBOGgaG1Li6DK6
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:21:17Z'
  mac: ENC[AES256_GCM,data:TZtd1qJi5cJsWtdxrFaSdvKT2oKGuk/+io74Pnm4dBYHZeiS+BXU5N6mgsvuj8OKiTVxk6wUjEYJYFmetLrj9yZXnwSu4WLyGUgK95poeZVWXax8DQ4ZULXW3antPCzIfo8LHuGvZO8//r8bAx9p2m/ntkgTx9uBx2B4/UncC44=,iv:XFbnPCbEMY6f9MfKA0T4NmvAmzOxSoWJ/qdXJgbj94E=,tag:srb38vhpnwKkKlahVcOL+Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
