prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:8OSgivHiXfEnP3I/wA==,iv:GVYpj+d4svo0VG2KdAtwL52i/pxNE1EHUvrCIJaQ30g=,tag:MmD6F+bjsZAP5FLQQbfYWQ==,type:str]
      value: ENC[AES256_GCM,data:Q70+jrv6jS2kAf6GWoId1ozsbLft6IOsVq57pKbCqBI66nhseHg6opyK2cOePVqe0w83YiDTnlSbycvPQS2BHgVPgKFUOKUK1PqYoZFs7glK1tl3I6PWW3JbRfbZVN4LnS1+yArw8S4JYxmFLo9oYwm82DZ3xwakz/l2rNirsTuBrN1I1/0Sqkd6pLCBGEqZpOQ80Ylm1712sBdZvTEwOwaAfsaZDaJfJp8SzSdy/NsNvw==,iv:kjqqorTW89htu04FooI5aJQyODr3m7bQyTN2RN3tuo8=,tag:DeZPEEiZVANFK3m9ZvEJZQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:q+n3ct1OuNVZvqH445SWasxAG2k4q+7STtA6bF6VXTX6rNZjAm9IA3pNnMaSIRdBPjNuN5ne2NL0KdscBHYKwQ==,iv:LAbPaKtkmnlaGRooXKLPLzAhZThtogSzCN98GEQvJJM=,tag:Sv/jJ0Ce7suDjfk2RNc0DA==,type:str]
        password: ENC[AES256_GCM,data:UnwrCPZz5Rd5DA5OMmf1x+PT6e7Rt/86FRr9LVo8xz5H2qsgahiQewW2zAKnEbU3/itdcqsEB7G5ykJeLABVYw==,iv:Cqiz1qozXpnCrICDf06Lv8tSltwFbQL5jBkFE+zVcFk=,tag:I8SwDWyIYp1QBhYfOKs4+g==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        W9oHidAdpoHYau9kw6cLcYrzfueKUETjqXuohZEqIM7DPM4FAut4T41Q6fhhoWdZ: ENC[AES256_GCM,data:DJUF3Dd9Fjx0h4NmYBGdMx1zeeHm+4pBh1JlZbkwRwOdbHqjTZCbCbLt2x8negNzgxOpmAP+FwywV75Y,iv:KoFzZXvTcvSE3ZGzgscP4Iahgkd8Ng3b7jgVkZCEdYY=,tag:4DBt0MhzTf3DzptImJyADg==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Mw==,iv:6YUjeYiB+g+bL5/fHDCM4tMsEo65NP5c/aCBQITw5XI=,tag:MWII68x1E00Jqk+18CbCTQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:M3e1tNPsNGeAtQ==,iv:IYfEZQnwmWqmLRwa+I53V8Of+wkDOGblu4dZLrJhHug=,tag:XvGGiwQxS57pyY/5aIy8Fw==,type:str]
        orgId: ENC[AES256_GCM,data:aA==,iv:3RDNS/5G9OmcNRjj27CqiUzRrNBqTWUYRcH+F4tdMEU=,tag:unT9a/1H8t5ECz/iToczWg==,type:int]
        type: ENC[AES256_GCM,data:9fcmnDSorJn42A==,iv:HYT7BrP+HgtGitSFOmeBiVtS5b+s1llXOBaT4hZd0IU=,tag:4kYNj8QoTEWyj8FJ6lvHvg==,type:str]
        url: ENC[AES256_GCM,data:xMRsDurMA+BDKEp/PKYqZLCGVnB1ZMZS01JGOrUMcB8=,iv:f/eZcmNVHtP0b/G2i1rWVgtmnNsD5/X1xhf+Cevig6A=,tag:nw+a6H4kce+91NAwHWCgzw==,type:str]
        access: ENC[AES256_GCM,data:xRhK0xw=,iv:kg/8nu8YYNrPpzvhDksDji7puP5SimwVOZKQpR6C5CI=,tag:kteIqM40TxJKUahpV9jPjw==,type:str]
        isDefault: ENC[AES256_GCM,data:dqWh/s8=,iv:JmXA5dz/D2rhfSi6oGU3r9IhddZBpTHNESTkujBMz/Y=,tag:URRuIUtM8cmgKvMqvveCBQ==,type:bool]
        editable: ENC[AES256_GCM,data:i6JVPQw=,iv:asVgSkn9dKQo/IYBXOeKoQfEhwHjw43gLYlSZbLtpq8=,tag:Zf+VEdxPuIG7yzbl7vhkMw==,type:bool]
        basicAuth: ENC[AES256_GCM,data:E+4A3A==,iv:zJ/3S0GunPGCoCW352pg2CC3hcpqlobUVFXXgWXdyVc=,tag:3hCw8XsiIXFA4de8uwTH/w==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:oE2fa1hXJcwWSCZ2JLE5Cx4DjXqr9Ij+oV87uB69yN91+1zWvi4xqOEP8g9T00VTrePllgfXXruLsillflneAA==,iv:m685HLm4qky0maglhIT1He9cFmihiT7PBzwwZ+aKLVk=,tag:dWyWkfgX4QK7TF+PcqiKbw==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:S3JyCwEz3MYIbFry/vPfOAY8BMMWn2Z40y0wqp/b0Nj4c8ad5q3denSqIJODwk5sJg/+r4eP8Gfs85mrjW5OZg==,iv:kbbsTIbe7FNpi4WP4iMZ8t4cEC5kRELBkQdPiN5KWZk=,tag:GRSo9tNLG50NQgEvn6SGLA==,type:str]
      - name: ENC[AES256_GCM,data:hESxmsVbt0iAyaFxs7WLd3ZNTUF8bug7ipyRxKozbg==,iv:x9DrwzCEVJW7K3QMnBsyIHM4YQLgriE9NhRccTKUfG8=,tag:g9dGBZ1SAvlPK2fIoxXqIw==,type:str]
        type: ENC[AES256_GCM,data:XSiAgsRVc30A6xCra13zZUIFXBjRjFxT2jSqFgpRPQ==,iv:bccz7fiBGbhy07xMJETppSFlHlcjSbuvD16aUDYR8Ks=,tag:kIxRMzJAW2s0dOgsJ5p0BA==,type:str]
        isDefault: ENC[AES256_GCM,data:P7JlE2U=,iv:KtyDLMTMjNEjvPu1dnGzBg0QidWRMQ1WZneKv9ICT1I=,tag:G/D8ETdQXgbaEYcnpF5TxQ==,type:bool]
        editable: ENC[AES256_GCM,data:h96uJA==,iv:t7nCWz8AosRugkWrfoZyVvJnmBJKKLY5zhnuOPh3zso=,tag:LsvDdzX4i06KerqV32a9iQ==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:/oQZAg==,iv:IqikQbiPWyCUEsy73eWT6UFtTBY3K6f+PKeZlpE/J/s=,tag:lJcQqpLvrBrxwMwu+gu6qw==,type:bool]
    username: ENC[AES256_GCM,data:zR9FdubtCotCrqX2sJlDSqiiegtL2Uiweulz+iMt7qW4HvMRbSsMC3XcsgYGFy4vrEB2K1YjWe1paphqdzIcBw==,iv:g17zqoOEbKmgZx7shkW/v80EYYw8GJnYwUjkyIHAbBw=,tag:k5BMF6uD3NzSLqrnKpM62w==,type:str]
    password: ENC[AES256_GCM,data:FAQdG7/js2DX4qIR3lWI8MoHcv8c0r5oWiceKRkf7y0KY6DazmTuiaJQ65EhCkLaeMD9UiOwyks9XufYn8SDwg==,iv:ZwCbbyqtBdVPMs9wi6ROfb5pqgIi/CaoqvmKoydeIeI=,tag:XmCIJiJQ93IyGA0enkqNOw==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:ITwyJxlUd9ZtGxJOFLpiSmsyAaHYgCgYzItJI62a9nNWvBGt2sLJvm8h0yXuZnKnBnUZDbvh7KvAmcAjKCIcSQ==,iv:swd5m+MVbAoiAIEI8c5rpslUzBxLO1v4MfA3HYsBHqc=,tag:VleE4uXgOdzf7E16hUwXwg==,type:str]
  password: ENC[AES256_GCM,data:PWm5W+NIEaOzQzz1Lz9CYK/1rd29ALirDXCB6DAGh/uArNR8fFuKn7kb6/4TpC4vr7YzTFTW/+EEr6U2lVV5RQ==,iv:RG9un0iwdiWAgyvD81CUon6E3Kkqj8KeafZXgTb+YME=,tag:K/Dd6epwm1ceU9mPopiOBw==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:10:38Z'
    enc: CiUA4OM7eCWX0XS2dyg5o/5bnxXsrGy4dIcQRo0AoVRTbPiTDdV1EkkAmy+ektZRMPayJ+J5MPdAxxropLscep7VlyhDW3/8sZtRq2/4hR/GL3InR8Khs+v7ppmIiA6Vs9J1Hl+VkOt5SzFxg9AK1feR
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:10:39Z'
  mac: ENC[AES256_GCM,data:2rjDai0tntGSkpRQMD7zdAlvbdsNt4qEsrZMaL5sFDEXwwtljLECkM+tLELapN2ebqZrExW/tuJ+ZQ2rUl9x2HE4i0zswe+zpS7yYMtyozTZls86EjaRPfNXHpfjnc3BDHr8zVfPlXgI0unsXL4MSvaSaOBByzp7Mz6P98hK1aE=,iv:ZEdMGYHY0XoxrgWvqCBQa2Rm6LuVAZpz2lg3Dbk/+gY=,tag:kviH3E//4oc73jXwLzF9uQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
