nfs:
  pv:
    # Not a real IP
    serverIP: 10.100.10.242

jupyterhub:
  ingress:
    hosts: [berkeley-geojupyter.2i2c.cloud]
    tls:
    - hosts: [berkeley-geojupyter.2i2c.cloud]
      secretName: https-auto-tls
  hub:
    config:
      JupyterHub:
        authenticator_class: github
      GitHubOAuthenticator:
        oauth_callback_url: https://berkeley-geojupyter.2i2c.cloud/hub/oauth_callback

        allowed_organizations:
        - geojupyter:jupyterhub-users

jupyterhub-home-nfs:
  enabled: true # can be migrated to common values file
  eks:
    enabled: true # can be migrated to common values file
    volumeId: vol-03eed37ae04a744e2
