nfs:
  pv:
    # Not a real IP
    serverIP: 10.100.249.1

jupyterhub:
  ingress:
    hosts: [staging.berkeley-geojupyter.2i2c.cloud]
    tls:
      - hosts: [staging.berkeley-geojupyter.2i2c.cloud]
        secretName: https-auto-tls
  hub:
    config:
      JupyterHub:
        authenticator_class: github
      GitHubOAuthenticator:
        oauth_callback_url: https://staging.berkeley-geojupyter.2i2c.cloud/hub/oauth_callback
        allowed_organizations:
          - geojupyter:jupyterhub-users

jupyterhub-home-nfs:
  enabled: true # can be migrated to common values file
  eks:
    enabled: true # can be migrated to common values file
    volumeId: vol-018ab2eba48b7d895
