prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:o03cTovn0WelpEHq9A==,iv:uo1plaa7CrjnwEn2TvJER1mHrrFk2cTeAqKcD3mYawU=,tag:8iW+rAuqicjUjy7U8uit9Q==,type:str]
      value: ENC[AES256_GCM,data:xrd0bL5oc27fFU6i6dZULpgw08FpmAOxTyhSbYcvXOSfvPHUv8TXRdWxCriPMddkqzGD5mb6cRx/m+3MNTv4i0DSN67XsV6QiZfWpg/MGVhmh5uXyEaOARRBa42qvT4AYH+Xed00NfL2/eBaSEQfonl25ychHHyOEWV+u2UtKh96u2KZNQm0F9VDsqVdxKDgltwY+ROyQhmUwSlIJNnebWgZTJjvkOvn93fNSoscA9WUng==,iv:Zc0ziIpamIK6sw60ovEUIOxcHySF98W5DCa/IGRXH5U=,tag:XuBjHX+EslqvJZ+OyDaHxQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:6SbXrpedTYrBAb+jY+11MRa5ECX8npYaZGEhNqVi3oIXYDbIAf79FsG6KVAcd2KTvatCsZ9stIdHRvwHnk//Cw==,iv:cApYia62C69HjeCIutdx4e+M3AxYHNkBxTL3hQWYl2Q=,tag:GcSkoBorLBxOpV74cu/pJQ==,type:str]
        password: ENC[AES256_GCM,data:1OcxLi/yk3L+SOlDNGlSOihTQQpptuVQgC2WXWfExnwdK7jzGrTaOk43BmM51L6CyydPbuO2eDbWbid6a0zjdQ==,iv:TyhSxN7p8vmEsI1cTA3mULcHUHahe1fYE8PL+SyODnA=,tag:8XquiEQDprKL2w4Xu7qDFQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        YV521IqjWCGCT8ta5qGPYpdK5PAPZmpHBtDICjDG4x6FvqFa3IBdGOq4uyJzzU5G: ENC[AES256_GCM,data:MDUIoGRnsmEFk10UrgsYibIabzcwyzsa8sqOH997kdDo0J8Z9EH3F5tbjPEcBhLMg/YRaIKIHI3kBMWn,iv:0IkUR2kQsL99MN4Do8Cn2eEY8/IG0Y0hz1jrxzjVzgk=,tag:XMI+NsVHYwvthLCO97keKA==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:eQ==,iv:mYtLBotoYXZZotP8Br1APUcSCStaMhk5rEzzmipZL4E=,tag:MsxKYREn8k7BfnRH+H81zQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:CDshdTXXocj43A==,iv:WgIrvXUOD92SlH5k1OtnZm7wzkXTn/GY3fqsaE1DmdI=,tag:zBNyBmrWR/s3JYPw52N9NA==,type:str]
        orgId: ENC[AES256_GCM,data:7g==,iv:3ReYxWguYHd/IyGCY5ETHEOYdPAnJNrAo9U9TxtjubI=,tag:gVxt1VJ7WnKCxI/tTvKbvA==,type:int]
        type: ENC[AES256_GCM,data:/2fBwruegnKbYA==,iv:4oz+GxQLniff/+A7EwDNIGF4w/JbVTer2uU/pxSTkjI=,tag:69CSpj1C+asUicleNFQ4HQ==,type:str]
        url: ENC[AES256_GCM,data:LDLQF6AHLLNJaeLC+6mQKPJfQkJeURYPt68EWkB456Q=,iv:fmv+pJmnJ3hE+dwLIHDLiIcjogKN4KpAfVJxcA+3gxw=,tag:P+tJgmutQ+6SsHAhE6WY5g==,type:str]
        access: ENC[AES256_GCM,data:E3j7a9s=,iv:K7ZEzeZaaIDSdcZZ3mO036kcFMOBX/w02AA4AeO02xI=,tag:oCeKylSGXwMAsPkBqML7lA==,type:str]
        isDefault: ENC[AES256_GCM,data:Jpam6e8=,iv:uh63ZlgZJ7oWAQRcMC+IUvcYOm6s0PRA5p/BP7x1YAA=,tag:AwutsnRSRvXpSRpuxxpZJw==,type:bool]
        editable: ENC[AES256_GCM,data:rRh1JRI=,iv:Hr+CZrpRhXM0N0qSBqTs9CtowWrgnC4NKaIXseW4mco=,tag:EAQOxVphBMlGd2L6DVxSeA==,type:bool]
        basicAuth: ENC[AES256_GCM,data:e75qag==,iv:V7I0MNs806jv5frTF+erCWnkT3nbXU9e2KJvo+3YmE4=,tag:Grm/SBuitbr0rfkqc7xchA==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:du54mIy2z++d4VBmqJtF7yjHhlTBJCAqKXoKyRtk/Wwxa+0Plbc7XCRSr06byrjOfQpVoZfTwrs6C0o75eIsEw==,iv:+Mlu19HAfPXLTroNPp16nSZD/kEKbXMcu/jqV4l7Dow=,tag:MqYZR2fC4xurF/hIhjO8/Q==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:Sx608kj7IA8j6rdRM7aAAiic60A/wTutwBXi37MGEEZj+sqQdFrQ95iwFnpM2o55HzO80QYK6EPjWV93TnSGwg==,iv:7XexHN1UVuOfd/gDRTWwB56VfEyY2NLQpK0rk9S7Afg=,tag:EtPS4RRjQcDa2fq0ZHerLA==,type:str]
      - name: ENC[AES256_GCM,data:Ajwsx1cDOJkwbWJ3QzgcsWHJ1fmLtjc1i/TTNlkyMA==,iv:D8bN8EuAQrdab70MLqv/XE0tWpAx/KIqzKjnDuQF/mg=,tag:ygz7pCh8eCblcFP59bDRsw==,type:str]
        type: ENC[AES256_GCM,data:dAwzF4Wv61nNQ3r/jLUJm2rvKzF3GQINPk+4P68H3w==,iv:Guy484Hw72ZS/txx6XmSOpTDy/Ko2IFswCX8rWfLr8s=,tag:mZhRD5CMH0YNmxp2J6xlfQ==,type:str]
        isDefault: ENC[AES256_GCM,data:QI+o9es=,iv:aW8gXWj8QKlCio3i2c5v1w9Rd2HUA9QJH4V35yQjhYI=,tag:yzIYsDgDcprXsr/27AMtaA==,type:bool]
        editable: ENC[AES256_GCM,data:L6E3dg==,iv:DDDB4tVsuvwE7HwBa4bBEKVGUkBqigzTwq+7yCFRZ/s=,tag:vtSmFw2/I6VYyIFk56FhEg==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:9AVFCQ==,iv:+lSnvTYTs7BQIFGW06Z08kChnFSy12IQN5kczUp6PGc=,tag:SwXUvD//1sGRLML7Nxl2kw==,type:bool]
    username: ENC[AES256_GCM,data:9sKQKbmIhlIYLxNqqtz/LaJXyqVWgypym/YznumBZd77C+rkFT7ec7qR42Nj/T04PvW8dRGlv5CUGbvvF+ER3A==,iv:HxLIdqI82T0lfCX8YnmsnoyaMyLNOANMKPaf8vPROkQ=,tag:2vsIt5J6GqFghBYh7xsyTw==,type:str]
    password: ENC[AES256_GCM,data:uvLUHa7NA42z62DNbaTvfRIhfOclF7qZjjrIntKPlswibjGyJSu8yyJrQTFlrNB5yyBhEem5d2TFlBAksPNChw==,iv:2QZGEum9iK6t3asdrzkHyu63uXgWtXMveAmd7/Omm2c=,tag:DCxbOOx7aBGlQ78hkdENFA==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:2tfFUFfRaf/VynNCt8rBjnDMgdctRmv7Mm4QNfq7iKCEctxjnsji18fbioHkYwyHkkJpJK4CQ8fUblXwe3s/hA==,iv:TCbTkg4JxaJQe+M7wcnrTfo+PsmS+qiiXoPuGHHYLVg=,tag:RDEb2seCNmBsT0RlvjrN2Q==,type:str]
  password: ENC[AES256_GCM,data:dUITi49rs3cO39pshlUkZc8D5fJ09y9y0uS98LumPcviWlPA3eoSU4IvCGp5a+kCe1GNJgNPLBtpx3nBzjDjUQ==,iv:MSXuPoB3H2CMkHUjQdn+hlA3ts2iShNRgI69RkFpMUw=,tag:pw4xf5s2txMCEp6tGZrROg==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:42Z'
    enc: CiUA4OM7eJuoh1yNMPpLXgvPRf5Okieu5blwHTIsJJ5WJS9uK9mlEkkAmy+ekqKEhIwstMiVzlYsSdJnKBgLGqHKHkQkZe9UT4tv0uXgo1YOoPBty2aXMdT0rhhprkoZoLNAJTd3okbcGTW+HLyipWWQ
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:11:42Z'
  mac: ENC[AES256_GCM,data:xeofB0OUq1QaPJ7BAPiL/h2a3x63dXfzUZ/Ur+VyhsHfC6cmnWOhKRMF7r5ubw4NNqzRq5c9Z9mkhpg9xEnVRoWAWofn/Hb1GBru9gkJGSzEDLGcwyIDbCwNgLLwfmdK4m+wentZiurfFPvcCItI6GZaT1y8rcg2nk6DRiS/XY0=,iv:1qW9R1rjc00jqQRfslJJYDXtkw4A9LvWNc0YRIjg0ng=,tag:HGmf1NH1ZQMfNiJf0LJtXw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
