prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:yCYhA+SiUJ+3gP6ACYxMASm7R2F7mjyduTOGpSMf7Q7S8vcI7iA1WwT37u9fWl0j8PoK8zBkaaxdILq1m+nX4FAMI1qb7OyPb1DWsI1t9P3oP683IfBmh1iqnHD1ddvlWzsxnmTsUKKY9Tp7vdBkhr2DbaEB4ePa15shnuYO5Z7n+NEdFHcaWPyZ9s9gVtakLJeeMd0D9o+Naeu/,iv:Ilzfq8j1Wp6PM/4t3plmRQ9KVvCmdc1ZWusboEL+CPk=,tag:MZ90NY/vSpnuyRECQ+qrVw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:syRY1TLZZa+sLjaEsgBGfLD0r+H7OjeT1+dwQDclRy94hJqKQm79j+xmMBKyPm3z1EjRYDyGX75y0tdpln8rtQ==,iv:K71REpye6mueG3H4P+6l0P0ZevXf9TSQ2jY2qu8Bxbw=,tag:VwlPWdSXcFr4AeQPH4prKA==,type:str]
    password: ENC[AES256_GCM,data:LSkGRwG2isnIfL2eupkf9/VhwxhjstBXzfz5b528UeJbRcjNLZnFgxTEiXoKbRGXQ355rg8S5liVXp3e2qhVhw==,iv:cai/IPaN2Vtx5/mvUtfXfQjypu0VoWIvzuRGywn15JY=,tag:6Urtrhzj633th1xXmmsfmw==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:oYbqDD0Z18IQWA40pw==,iv:/UBo5u9hKr66kSPfDqL0E9YUX5WTCuH6Jru2VVGfejI=,tag:fW/suvwQtd/YByihHae8gQ==,type:str]
      value: ENC[AES256_GCM,data:02wSwz2qW2UacpMQHaUiKh537Y5PrbwlmbNKE/h4Veb+U3fU01MZgjK+6D5xLtotp7qfkP2RiKV/7Nain5Onhav3MC6PupKZO+sShb4WqUPp7IinxTHpPKCqp348f29vvhCXOvfD3ijDwZXZzEaReKAHK6Gr5WfpXn/s8rdsgjulZEKqOf2VbdFSpvHI6eGKekacGfDsAvS2Eql+RYpxIyuyGHDMAdbaSmuifjJZmK7/xw==,iv:/nQXvweVtx2N6dg21cMGix1hHjdp7tmaDQ66PLzOfQc=,tag:L0cdC+V8cI+T6Vnh16JzZg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:ls9smyFAeui+BP9g1LEq5F3So/2bgyo+ZBQEXJe+ngz104/3Xuj8L2e2lN6lXX/zfhnLnJ3eroLk2YsTZmY4fA==,iv:Znn15JQvXchoAcMahyMYQ0aOPLnbgeCo9axGt/p4o0A=,tag:mkRGS2Ir3dcXUleVEkvnzw==,type:str]
        password: ENC[AES256_GCM,data:DT2D1Rg4TYfAW9DQKOZIaUOnfX9jJtSVMMmJkm6DD20JN2TofeVbbRZFx/jCux2Sp6vIHFtGJzSHGTcjGNKwqg==,iv:D8N+9YgS4sUBofiBOu252r/7E4K7H8lXINufv75ZgQ0=,tag:xNeUZtoFojrDpLed/5e9Yg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        YV521IqjWCGCT8ta5qGPYpdK5PAPZmpHBtDICjDG4x6FvqFa3IBdGOq4uyJzzU5G: ENC[AES256_GCM,data:hNRdqQoCgfOWsrTZ1S0CTJmzVkCw53MlFb6VbJ0qAf7EfXrSJOVFlEYG/qKv/vSBsEoHf6B3NpSMkmpC,iv:5eNM7v8QhI0SEA/a3ZjCbp3SaLfBExErlEnNHvLqjuo=,tag:3/AwkQJU+FA1aQ1cySJrjw==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:zA==,iv:pd/+h0dXkchYUrWTWdLJsRcGDitFHvCMQjvFu5j2WNE=,tag:hr5GiVBqwL2L6WyniwJaaA==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:YnNjRiUNYPFGiQ==,iv:zIQ7QyH5qw2mqBPVAdSVkAXkMdQsJRAbU1IdQ2luII4=,tag:7ejgtVCcUO1KxG2F8pDPtQ==,type:str]
        orgId: ENC[AES256_GCM,data:Ew==,iv:CHVq56ufNBDHKBywqnl1QE0S+HdEPFaxvdpIRXmVfLQ=,tag:QVNKP2PZCL3Uo0lharcn1Q==,type:int]
        type: ENC[AES256_GCM,data:4+elSh4Tm21KUQ==,iv:Wyq4YlViAHDysBf2f8IQor+OhapQxijkF/2MsGtDBdY=,tag:lh5OGta5n8urd6q+zUUxjg==,type:str]
        url: ENC[AES256_GCM,data:llkX+M9ZiSE5NwjvdmQ2EOdZ8zmNBMjoxmgNSaRpEnI=,iv:pWNCPeGeZCb5u4emoB2fsQmo4p0yWAsnIKXp1m/thSE=,tag:Y0v6JYMa0Z6wplYjla6wqw==,type:str]
        access: ENC[AES256_GCM,data:9BOxSmw=,iv:wTPYGIsB3HdYTY1r9MOaIcRuN+yHt9r1hI3N4OUWKBc=,tag:4t6/kOEjYPuPEcbgnjQPYw==,type:str]
        isDefault: ENC[AES256_GCM,data:kHtwtaI=,iv:2ayMEwVzlnAtyp7gyBKDioMsX0sf7+PxQGTy3na7G34=,tag:Sb89AxOS4WQNWv6b/UdVjA==,type:bool]
        editable: ENC[AES256_GCM,data:jNkxxmY=,iv:CTzkEcEtBx17FaLx6Kgd4XtYE8O234SGkYmDYTbEu3o=,tag:oRJwwtucaMK3OrmuZi13YA==,type:bool]
        basicAuth: ENC[AES256_GCM,data:Ak4d2A==,iv:15q9SiXZPHKPAVzM88Eo3aebWqx+iMvO6cEtDGD0bew=,tag:35/61X9zKk9hF/mxXaCGoA==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:+uFeIhSUCBO/XpIPT47QS2/QXGq1QZ7QEWaBBtYh81VwmXk1xT24HBgYgXyOo/QM8qxF4FJlW2ToOMI6Nh6gEQ==,iv:l0wNOxbCZBm3qip0/oFCJkwvUNt4w6DwrfuV34s2ylU=,tag:F6rsCLvRZDqNWjPtyBKDAg==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:jQ75OW1lQT1DPTV6wjfPdTQxTWVLXKzYsXPcqRG91oiwwz1NxJJKkUPQkTMf59NUmIrlTITTkBUkt6EmxTIrhg==,iv:5N6MWdNoxIwK6uxnX6I3oNaxZ61z+OxIvp6d4cd3qmA=,tag:wkoT+wVsfmkLYUi+UIIMOA==,type:str]
      - name: ENC[AES256_GCM,data:iJEAf0A2yusVVJt8TTDzSKI3PawIS+bjYml4AHescg==,iv:RLnK9pIMUPWoUvBL9PUK7ZpRr1IX6/Jj0lTZsv7MnuY=,tag:s3zOI3iKDrGhFsFgxsSLwQ==,type:str]
        type: ENC[AES256_GCM,data:rfGVLsp6YZxCFkQb/Q9ah/t5y4PTT3ZbxftiaVWIpQ==,iv:PhnnIs3Br4WdvepDzIAi7z5Lhor00uXiwZCPdYFZZ6o=,tag:OsBfY5TiYm+U8YHehthJVw==,type:str]
        isDefault: ENC[AES256_GCM,data:mV6TJ9I=,iv:+Sd3UZ+yJeaYIuJaTjxI6Rx/QX+yxMuv+lcMRGVTS/k=,tag:htV35NvsWY1HjMyFVt5NXw==,type:bool]
        editable: ENC[AES256_GCM,data:1Njutw==,iv:9kocr/5q8w6G1fVGB/bJY7m+bYJM5w000o2f8cTkH6Y=,tag:Cp8Ib/OY+J1pODG7srp6nQ==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:AoIqSA==,iv:FMxYn4fb1MA9LWd/EhPun0UjkrSePGmCu3RJnSuA53c=,tag:pvaCDnyelz0cC5crnul7gA==,type:bool]
    username: ENC[AES256_GCM,data:rPn4u5j6qffIQh/eqZPyGdoOJinSagaMJQJh2S1STDEiZ8hFxKKu2qNNoJKZikVRNbQENTfD1ZjpCL7F9N3s7Q==,iv:jqfD7DMrORsRknknprbwv9ykD4+bmZgmO2F8vqVmEGk=,tag:81dUcnPmMG0IxMo3whTTPQ==,type:str]
    password: ENC[AES256_GCM,data:KOyJWbcTqJHHhm8B8/dT+vGYhLbpqimr+6as7jbcGGqEEGZ5grwLtz30N/tkAWabY/uSFkQo0T9tFgixSTO64w==,iv:cHTzC3zm8EkHz14WREOMWC3sarLqqHp1DlymqRdePQQ=,tag:4nAl54j0OylVs23qDfYFrw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:58Z'
    enc: CiUA4OM7eDDzRqDX7oltPw1D8UeCfiRqUHE0Y0v3JeX+GpxDf0tFEkkAPHlbmbDPHHXDL99e277ukt296Jj9158+q0aAP3XPPhM67J/Rd4RJMd2sESHHKwkZFxrSvv+w5vzfj9QMa8+/MdhWb4IYnexr
  lastmodified: '2026-05-01T14:40:58Z'
  mac: ENC[AES256_GCM,data:4GTfCV4U6ftP8Z+8xqFZsELKY6G75NBQlL8mBAa4mdIOGLx4MMERaSwMzi/TqS0vG3iU91riYtgU35r83gX6Gsja4li7fxG3K+1mbt7lpMJafGRpyt5beeX1K22mhtfwilxWfUCyXWDaFxzpTHt3m29rLxLtomIzewW/uiNT5kw=,iv:QtmWkM0nCFodf5jQEdwCu5K5fX/iXYKUF+6sbYAxB2M=,tag:zt5lRmUeXof6cnhglSmW0Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
