{{/* Used by internal services to authenticate with Prometheus */}}
{{- if .Values.prometheusAuthSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-auth
  annotations:
   reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
type: Opaque
stringData:
  username: {{ .Values.prometheusAuthSecret.username }}
  password: {{ .Values.prometheusAuthSecret.password }}
{{- end }}
