{{/* Used by internal services to authenticate with Prometheus */}}
{{- if .Values.prometheusAuthSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-auth
type: Opaque
stringData:
  username: {{ .Values.prometheusAuthSecret.username }}
  password: {{ .Values.prometheusAuthSecret.password }}
{{- end }}
