grafana_token: ENC[AES256_GCM,data:0Ukx6gQ9cMhneTP/LkWEsI2b6VBBcXrYSDImwIRhqD5+M/ytLJ/VUaIgaNKGHw==,iv:IiJ08Hhn9Bd7FGkc4pEgS1KbTCKxk8jA1/eOCia+EM8=,tag:WeHS9oM6+BwpIfcqfrOjuQ==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-07-06T09:13:42Z'
    enc: CiUA4OM7eMaUCPSrGgeP5BErw54UPnB/MvHR1p5DmmkL70z/2bq+EkkAmy+ekmAmM8S/13oufSeYrsNv59xVRK2+hAwVJmsPwUPjKh0T7O9LkqqeU3EX5gJetym3uYte3SooxL2RzVZ8ZWeK7n3xd3lN
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-07-06T09:13:42Z'
  mac: ENC[AES256_GCM,data:GADBh2cTGzBZSTcfg658rWTXkWirRMfjcFCpvAJ9YPjQjXU4VbxYI1p1TAF3oP4oznEmGG0m3ouvDiHmDCE4EXqtV37RBf8l70aACrZoPOESutiXcJB68UDdOJoUUob/p6Wufl6ecf6sr4/wN7dKwTlQHXBNqvktVW853zDnpm4=,iv:tJc9O3nKTW4nEQq26YXboPUA43azKUm0VU6s8f24Gqg=,tag:5H7wurfRhX3rRk9/WvtSaA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
