prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:zZu+OS8Xw7+F8cn6cw3XPxJ+mOqnyHP5rdUCH3iHQxwHYm4NgWoeh2Nvgm6N2whVaYwHeBwkNCXhtQ2/JwOrNlYrqw4yCA9j5oSWdFkglS/ibRttjpC8RTLBo0JCvm3PtrcI8KXQUGbXML4PuoN7nunPhPHZjNe2jxNBS7bhUoSUPq1aJpWhPGwkQ6FIAC77ZTDEBUoBela+f7GQ,iv:EQEsngdOMrg16aSpmo0j9Dz4kpLTPFtLkC96EfeW66Q=,tag:e/lqCnz4I/wQat6ORlE45g==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:dHTLomY/apsZmxP32KHoRg1ViKIJkvDogtSkg22QkU+4Dy55BNqbJnj2cjfEUPT3s5LtBRLpw4iKb1Zus9Idfg==,iv:meLPQVDCVJdquud2IPrnIu7PD9PfFIMy6gtDzjKNRbo=,tag:VMXW+2Zk7ArT9y/ycTmEUA==,type:str]
    password: ENC[AES256_GCM,data:TKU3QRet/ENcQEGGpga0AkJxWKBEyO1GOPIzSIF7eowpNKKSb8XWgAr7cGGSPNcR5gfm+HT0qYM4wCO1LfGfkA==,iv:HUQnwofNljVtBKKdsXOCotS3UhBys5K/EGkWDmB+m4c=,tag:VEbfhqiAH0BgEvccBR82aw==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:TCH6jXi1FxVEq+gykA==,iv:E6d1QYx5TgxwtVCEoft7T77umkJepwFX5BBrK+8dAiY=,tag:TN17QDMzVHBN5xjEBBjiVA==,type:str]
      value: ENC[AES256_GCM,data:w2+Dk0VZMBZmY+ZvDpN/uo1w23XlMUdALAIpjT7U6PQmNf9GICt98+vuBc6z3c9wS5uTdp0xz80iKCVL390Xn04E/alSKIrYMkRPQBm8z4/ACvbIP2jAus/Iu6DK6wwsFzif/5uUE3Y5mcybgwbQ7V7pybZjaFKmV2LUTPMqxNmniyFGZbci6qiJx/4xflcpUyXy4ntun/SUvxkE4Mq5iRG4ApLGLMKknVJqW/mKfEGdAg==,iv:Gy3bHjN+w7TvPqyCLl5uMvJDGiIYDCxzDQo5hcguM3w=,tag:rSLEeYlVCOrr2LJ1lMoMMA==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:j50gA424A9PdDNwo3BayEJjxriFaJRMJxOihbaxnl/fVSbAOUMqzUeC7yAPdJ81TLpGROxTzQV8mJ01mcE/jug==,iv:xP3RIFysKvbE2Ne+ljpELVxr0njvp5HMdnkl/ShhblE=,tag:dcZyGUbI5g51ksF22CyusQ==,type:str]
        password: ENC[AES256_GCM,data:n8xBBpP9aYzfxyYG5W9c0Sojw6Br8WoxA+drViTBT+gs2nivvbMvaCr6+buir+0ZshpoM2cS+kKDDIFr/Qv+nQ==,iv:2jFrM6hlhtnnsb2IZdqdKdsTz68DcUxkNDKM3pOksqM=,tag:+wcHBZoCfbHAOaqax36URg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        OyFZM2bRc0wzQ5pvRSKRL1ic3DPihHN2ZCt7ttt3bVkGwKvinSRGfpjEVXVh5oZs: ENC[AES256_GCM,data:Ks0KkoE4dGhgn1SV/bKmWxvQadmzG8O4+kEeyqUDrN601e5Mml5yDxvMEIdm7+45nlqRiCIl56sBCcgg,iv:bylnJremYmDG+x5VSqKk/MK4MrxdQFm8NUv7d8jpcHo=,tag:70HG6XUbUqF2pd9w/k9w6Q==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Kw==,iv:sKt7ToDRsW/t7iBDbCVPcLEj4VoIJWvYSj3uM6ks7I4=,tag:4YcQvgvI1iqn8DLHYh+b3Q==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:wM51BMiFF+iHXw==,iv:TUXCz1BZQtaZme3rpUwkNTfVztsc19nkUFQJZhJ2ySw=,tag:5RHXVzkAWScUtuVhnNrA2A==,type:str]
        orgId: ENC[AES256_GCM,data:/w==,iv:ZdS2iLL70TNRvtjB7tP96W8oEPtjUM3cbEw3xbfLT9o=,tag:VkEKa6a2BPRGFQU1Bz2/2g==,type:int]
        type: ENC[AES256_GCM,data:nNUBLpVCgVHxPA==,iv:0V3kY8L1hM9LgHQitjHrcOiM0CATOeej3/mKm0kuldQ=,tag:oGGHQc40vd+p53owND0BVg==,type:str]
        url: ENC[AES256_GCM,data:owBf/hY7GqXirURS+ri73II/d+F8IzCu0zJNmEBuHMc=,iv:lx8O/tGWaWKrCKwmv+lqcvcpL7SFOAUPdIZey3LjEm0=,tag:bKfqlsrqWKc3mqcBcGaKmg==,type:str]
        access: ENC[AES256_GCM,data:hg8Elpk=,iv:UA3UTsCt+aY29M0f1FH+G2r1A8LNmpvZjcGcHN3Dmfs=,tag:gF40upn9myKMRypCmTlP6g==,type:str]
        isDefault: ENC[AES256_GCM,data:t1EV6oQ=,iv:qNhHTOFsZQH3++aadg3C88nJWWzk035GX19TedVysJQ=,tag:L8gS+28DPBuCjoYUokhmSw==,type:bool]
        editable: ENC[AES256_GCM,data:j5s2/sI=,iv:ckFcctBemXq3aE4LI+SoWL2v3w55VhKQYYUGO+5SzLI=,tag:Z8C9TqDoke5EUzivTlACiA==,type:bool]
        basicAuth: ENC[AES256_GCM,data:8UKyNA==,iv:ecOKqJ/nA2Z8Dgp9zYlPLZOOq90cn4u5RJegVWKdTqg=,tag:uhedSrlX7d5AYYdQnKNz6Q==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:FvhOJ5q6iUmjXY8U8DBnjFjy1FLfRnDpDE9n7sOqn46IROyW2ISQSEhZVdTZAbt4YRWNzNZm7OighWp9Roa7Tw==,iv:rmyIejmyfsgdZrkY372lpooHOb7kW1cHYFuEN9YPR2w=,tag:J+fiqAXP86v8Sm+rrqAJug==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:tfc1O7vtl5UrXIFCNzAoxu2M+hBMfZo9dIntJ7JzFp5QzwSnu7kSuLINHl3ztGyENErqfaeIAu2SlhtaXrb2Qg==,iv:/4Tl/aSW0Lb3elWtGlj6WZJ0os/RxX/1h287RmADGcs=,tag:sICWC2xnKBf8cVhmYN08Tg==,type:str]
      - name: ENC[AES256_GCM,data:JlTJgbIarXk2b1FtX2f5WZ1BfXYYk8aaMDqqUo0rzA==,iv:+Br5C+WCgJ2fZBxgfB2WbcSL7G935sazVvE69Qwi+gg=,tag:Pynv1gbqEm9XUqYllntOgA==,type:str]
        type: ENC[AES256_GCM,data:/2dcN6rbcYgAa7Y/LpEVxF/cu6k2qbasXPEiaCmTTw==,iv:N8FRsgIQo571Bfgd/k4VA7uF/NlbE9laIQ8JsxTxX5M=,tag:yC2ab7hFaO6ZjeyesOTXww==,type:str]
        isDefault: ENC[AES256_GCM,data:FEImeM8=,iv:1pEu9QBc5diSXBXv0BFTPjoyqsxZBTQ9XZvxsmkg30c=,tag:L9i78j3A1ohonZJEcoNmJQ==,type:bool]
        editable: ENC[AES256_GCM,data:AhGAuA==,iv:AGd/pUf5/o2IOPZsbdY1Pi9dw1YOewXZXp4PlViq+04=,tag:z+r/e81SF8vVLUyGDi+Nbw==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:BSS1UQ==,iv:+OmSmQKriFmzcll7mC0Uxdy/o9B9hy57nPtBmN+Sfe0=,tag:Xj2KFtDCxGZjbkbpCdqcKQ==,type:bool]
    username: ENC[AES256_GCM,data:iCqGIRffqdcosIRwoPk9yP8Y9CaasXhM8D6gSBgksMv5mp/hJNg44DNfTtaO+6KR9/JGTaYj+FeMvaeWrYmmwA==,iv:1TcSAXqmfBil8qEddJp1LzXEh756GHemvhkOzmY+R+E=,tag:J/XNfFOPKXxK51Tk5Dc6aQ==,type:str]
    password: ENC[AES256_GCM,data:uJiyoux4ripRb90MB7LNXsKmfXCRe3/489LDOeyrAtkYiqxgAfXhuqs1kACESZBCJ79ZxdQ4rD8nsIoMdAQM2A==,iv:wAZI/c0MC6RZGL3HBGRylXWsOsIYCFybjCOj/LoC5og=,tag:x6DUDGUXdunCzciwJ/jKnA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:41:02Z'
    enc: CiUA4OM7eESrBsDO0gJ6wwNGuP6lsUCHQKbvY9dMBGh/1nndnuzYEkkAPHlbmfAHm68o7pBewi0nwB89D1Qu648UBxfKpGFmyN0zXyVcBXs1bHUsLcP1DN7RhjSMbFTa7sb5iVF7t2JfTjhSlY5MyUfb
  lastmodified: '2026-05-01T14:41:02Z'
  mac: ENC[AES256_GCM,data:jHFWc21tT6rvf3BxOwojo28DVOgGswAUy5fQbzjCwVxwl5cWc90Pm4F9lcDKj5Ihs5Vu1KA21nSljaCh3SmM/K7nhLOnLXsQod6WMDT9fezNfVy76inIPh8nE+Wb7SkfoomvfqNgjxEkd1DLGEOy0Dpkzk0qdwbCAU+GIVaUUVY=,iv:XU3oA9zaXZleJ0sD8NMXZia2v/G+oBb/474Nf+JyoNE=,tag:yGYWEDf2QMLxoJFk5C66Uw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
