basehub:
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:Zzyp7PB9GIvvjqWlhBtvtOckQ6EW9tCdbcuJ1aMeXh/ZS4qGgPCaebDG1/p3rD8VCWRkHctX1n4bcBq8Sh9yrwCI3ebWvONpSJKysqXOYFNhX3LpzhhxiPs1pMWkXq+D43KeE+BJ0Q==,iv:AH9QqL9srAWqAHcBCrX/Q0y2Lgnx/2gj89qC6mBP8EQ=,tag:h9eQb4YqCseWR86BhEAUNw==,type:str]
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:IXIi4bWgDJ1w5qla2rWBW9tt248=,iv:5gD5O9kAECgs0v58YuLEVvvnvzgylGRS14KbEzdhYhs=,tag:9LKVqQQXBqScmOOZPDc7cQ==,type:str]
          client_secret: ENC[AES256_GCM,data:NTxwkc/0+XQhsodm3UOfZ8FybwI1yYnbHaJobeUlXk1g06uirxEOiA==,iv:T/BC/ERg3H6TaQ+KZjT7gBh3oM8q5PLhONDRCMxoqBc=,tag:OkhReBlYFsonTGPIIoe+4g==,type:str]
      extraFiles:
        usage_quota_config_secret:
          mountPath: ENC[AES256_GCM,data:rK9ZXdYcvxzyX5QCqU6qQzd1R1cpUvRwvwsqQqXb9u3LIs9a37vQvQDd5PhQMAA6f+GzI0qyU34lke4X/nKZNJB3wdUNdBxxbBL5/76WmuLkKLFsPe8=,iv:vsJpEbwSB2/WC9Sq2XejzbbSj/2fviZh/YdmmChQIBc=,tag:utrNy9xwISaF4Lyt330Zxw==,type:str]
          stringData: ENC[AES256_GCM,data:N/+6FviRaf/Kwep+kRTef+br6BeaDkUcHMGHibC/Uj3an3SKZflh8u8jCdxgPTIPDpUHovNZFSSR+Hc76IM6G8Vqzmr3nooeGNyWunnsnb9TnCC5C6Q3ofgtxbtmrM/1qPP22sp9O37vOd1zzAPil9NHwTmRHJ9xCChIWJgLH5RMoi/axJBhy3s/rqpWs8BJUWVvNrKLeSRqD65pGKbbXyFTLrkiZDgBZUJF3JXlxhITdS5cK7zlzPAOB85vXQBEvGYDjSi0VvbA0d0dBlr8EB/XRw/d1zUy0gf3B4GgSP7Oab8kNNDk73v7cfpR5P2m2FcVy0pa6ZtcPbuDy8Wqus/8pG07cR3Q2wT0Smxym3lozqx7I82F03g3GAJw5RbP3DRMmACrLe9uUNQAp3tWQ58YXhouhOZo/fE1caKDvn6mr7V0rft5tEUoYaOShzB+nkQCh8nRhVZ7coKNdmb68MTUj1NqKO8qSa1M7cjRFIrAEurOv+LPJTdNr4ozZXMv6fbr2lzw9Ba3todwod60u+oiBiXpLHgvzyBZZiLCENH9z+LRSlDsRT5n3p9IzMw9V1vIZ7vUNaE6+YLVpFKWsRdfVcXXKEUa4V3et5NhdjZXCIYG3k7fcoDJA42JO4118ibWtbRvzFpC0E6FX6StVxdtMoJ445gCqcKO3A==,iv:b/iv5it/uIPdBrNEfscgtbwNuod4zRaE7NVmtd2THbI=,tag:W4pb3bVhl/5r7YeohOirSQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-06-25T14:53:43Z'
    enc: CiUA4OM7eMURDnfO80Bdxdmcz9PMy4IEjXLoHnr6xMulcXX3C6GqEkkAmy+eklKTUmHXw74PG80pDTl6LPPQd3tSsn9AP4M1xOC+ooqe1O9Au5Ofc4uDUbcz4xtDr7BqXfD04uz4ah/Q1FiVmxd2kN4L
  lastmodified: '2026-07-30T19:12:25Z'
  mac: ENC[AES256_GCM,data:lWTE9TSpsgN7wMvZ8eZLFrR/bfjf/FtLBr7Z26H54Urc9lGwKrAlFLlpJM2X2o3kzG0Uu1p7Wgl05kZSpgo/rpbtncql6zoMacxghrnwd1vAJt9643Vb7ncil92nTR528WpDcQhETxztaw8aeTZ+QkDeBD8Y6CDLvcSh5x3prPQ=,iv:Ou+/uobBzweLR8JAPNFrYFillCOoUGwinDyJ3CfnsfE=,tag:SaaNQh1OHuIHNPluoRq8/g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
