prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:XYtbes7KD7OC/0lsHnnFt6qZr02bjRcaCrNPjuI0AOJ6KQ6qBN8w0ot5iqKw2Sf4tGPrbTjXuteG1G38kQia9WH5+L686hkCce4FFPeinso3XuoFTbqnlofq1BL3XUJZoROPPZbennbUJucy5eeE8N1s4QcOpFGDA8Hnceuny+x6+kH5zC+iBETKQMZZ5u1rEII7UUOybNTRH42+,iv:3qgL5Jfz9JylubVZI0fC0P32TcC3pGP6K6+hnWoD3Aw=,tag:q2VDqAFTC/2qmlCCuUllEA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:IhHDARpxKkoGMACi/YF6iWXkoZw59HGH99PZrabsTElf7/UhmfZiUpHsuC+Cud0maUaYBuD4lgKa1ywkCeHcRA==,iv:21Tmhy9vgOqLF2+OfnB/YQqOytlXMoCPU5Vyxnpeu8I=,tag:1nw/RZfDWJ/HNAKKP0r9LA==,type:str]
    password: ENC[AES256_GCM,data:2XU4ciOdpv1DzOfKrFRZigh5C3E70NV33dt01tITqo3JxiQRSusEb3ZB3O7TVMBhw5Iz526YnLRwZ9KHWJRVrA==,iv:PQtnHtt6tHYe2NxcSx6T3n/sdLDg2NPyp3eDpLHKZkw=,tag:L3OMG1ySrSRlJCpAO27vlA==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:3w==,iv:NPmcCdZH2jd52V3EOntqbzCH10FMtIykYHZ9EM6+Wng=,tag:+C5EM1NX2qLcO6C7z5BmSA==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:1ZuWZlphESf0iA==,iv:yfdC6ZgHBPQ7PP7kxQBZyO9QSenACpPiQLTP4a06Txo=,tag:g+NmP6ScR9/EcDTbCJOmTQ==,type:str]
        orgId: ENC[AES256_GCM,data:VA==,iv:7rd5rhmr1QNjw7lvdwJQcy/xxSknFXpoVpPDZIFSuTE=,tag:QMOJH3ZTwhCyvDJOnMsYdA==,type:int]
        type: ENC[AES256_GCM,data:R05eoEtVU7/O/g==,iv:Cib8H/At2rbllMmM4bMmAAoFVjO2aN9nhtNNHirjGjE=,tag:9zATP+0Elov2O3YD8H6DXw==,type:str]
        url: ENC[AES256_GCM,data:TJ63wU5KhjZNdBcUP6QorWDPvQAS8DA21/Hp2bktfWQ=,iv:xqdrXFZS13sxIm1vwk52NE68/Gda8ZaYBF1gQsVjNI0=,tag:f0kNqwW3tx85SCxqEqTpAg==,type:str]
        access: ENC[AES256_GCM,data:ueDCbc4=,iv:Bd7i2rFxUp64+Q8ATaQOXGvFx52RwumNslnXgDdeToc=,tag:rltw00ZuNqd0mRbbjQ7zTg==,type:str]
        isDefault: ENC[AES256_GCM,data:dg0X8yY=,iv:KzSiHOmPvBs2eehC5yXkXxvSfmOJA5n7+lipksZ9U7c=,tag:C2HZBbYidBFA4GTISG8mXw==,type:bool]
        editable: ENC[AES256_GCM,data:6C3O4Z8=,iv:S5cPv05MypdkmKl2wW5HQwHS5mu8+kzCWESk1G+YZog=,tag:gtzAvM19OdhGep8Omyj6lw==,type:bool]
        basicAuth: ENC[AES256_GCM,data:DpOrPQ==,iv:ozrzCPCVrhtzEvpTFPx7blovOz6sgWrbIxMqvd2/9Js=,tag:CU9Y0RWpmMgrNXfB0nJymw==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:4PuK6bTA4Iyu3qpjXkivRL2whX71MmfmlNV7JCgUoSGfqI6wDJI9GRe2rkPmR2sf53DeIK8LtB5H0X31cnAlCg==,iv:h1rw4/WqrfarEGDTxoHq2IGRT/NOx5p5KV8ECAiAR1I=,tag:Ks8QW3LB852KSGNOcF4P3Q==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:q9MSH7BTRYSWtA+aQ4hwpqXMlQ3ILp8ENughGBMODJg/7M6EThGH+5OK0Ci5kgGapi27gSPoWfGqhdLi3BsRCg==,iv:VdlJfN0ZkkxiqO6/SfKuVNEhfxg8+W4Mglzin9TXlKg=,tag:HWyX1JCsY+MWnXHAJB7bcw==,type:str]
      - name: ENC[AES256_GCM,data:TBfjSKZHJU9Imcax2SNghLwXwS6kV12yl2v3i4N6hQ==,iv:eNQpV+RnYfVPAn9YDnn34/qBSEgJIvHGxwwykUHG90Q=,tag:5c2z8wYvY7C/XTlP+z4gug==,type:str]
        type: ENC[AES256_GCM,data:GBBviDqP9vS+zTpmdGYzpLQFcIeaQR/GzrEcc9WOeA==,iv:45vaviVLJYAAlVmGOGT9CSs7ZUKpwZDyClrYCrArOpc=,tag:KSZVckPpRWvRLiveU/NXNg==,type:str]
        isDefault: ENC[AES256_GCM,data:Rj7k6dQ=,iv:zt3PeR5OZevofNUdTNkw2nrSNpvkLuV/FpkWOitBpS0=,tag:0AucQcUQSSaW/+EoXPlIMg==,type:bool]
        editable: ENC[AES256_GCM,data:MIynHA==,iv:h/pDW1yxYgofEzluwXnFbAMR/QV29pH0hfc6+Xjwz08=,tag:a9wWwAltF9FQ+Jl4x5ZGYA==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:xedXzgHU8kAbMSt//g==,iv:sidMPECyAb8WEItuzP/ukImJ18df0/yDitqgYiamNgk=,tag:bV5PldbbFnchX1ym59jCmQ==,type:str]
      value: ENC[AES256_GCM,data:fJwBa1dOXe36ds/YwBi/xcjKzOo2cGAdUQqU7ZjU4nwW9uYVxc1wKevuhqd5uWnSAwwgMvi3Ag1pWzuD2W8s/7yfYmdL2nmfuJK+ohmUqf69wnWQhOhJ7iV2xqTo0wKWoHVfT1PWK0OA3dqWLzoXJeYqqd1lnNbzPuCXpTAqa+2KddNdm8fm2HkS4EAILIebNALJkSm8xhywc813AO6i0ztaol8It/mrxJxMdNOrY0Btfg==,iv:k/ey26/YMOzrsCVhY7JyXnU4Z7cBlCJukIYR4q/CIcI=,tag:5KNIso6nKmBCsROUN9NlRw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:1Agy58r3zk88klAMoVbk6dD6cNohw/P0jyJtFvRsUSZoJB7kv27FwIlCGIDCjtslMP2a5qskEwOBWpSJMnePIw==,iv:Hw+n7gL9EJ0qUBIEVfyXV8Me/glAyGuVqmmXpVgEa5I=,tag:Vzsw9a8pVrIhw29KGd2c4g==,type:str]
        password: ENC[AES256_GCM,data:YpEc5tjCSEjrHCvqLk7irmdL5PsQ5iq3ZhZxY9+pHNGgkrWvy54XZ8nnUyV4L2qVVUOrvIObw6hGoY/pk+2kaw==,iv:JHQ4Y2dYoOGpga02gJ2ASlP2oQNs1QRhLBcSHZMkD3g=,tag:lVJKjuy6iAsDcPpP9pPfxA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        SEMpzgVnNN2gJo8iT1GUbQZiApa5Yv64sypBVsqD6ozG6H5mjoUcfRLSoSQTqWDD: ENC[AES256_GCM,data:ScKtP6V3/9jm+rL50/q9mREfrJpS7MT7e/p9k3Gkl2Y1v03ivfQCTHoJIRy8jjGxJVhC0drBYTA/mPeF,iv:YcKpXMCFOgohZnQRAYM6AQ8rX2pFzv9d7Hn+x5k02sY=,tag:dz5Nipglfj+Mdy3EgmySGg==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:SMqyIw==,iv:60W+11qxq/95uT/OgzN0lKj77dB1L2z35sqTbCdARKY=,tag:qVJ287Of4AwavujU84x3Iw==,type:bool]
    username: ENC[AES256_GCM,data:xMoz3tIxvfjO3PZ1wDMyoHm5hPyFkXrxClHlcKYe/3gPbFN6SdTt8QlkthGpjl/+8anFPzKlFCUG2m24d9iwew==,iv:lKjWj0NlPei8YVPF7uB7KDB67lcfKp4WwGfWwUjSXEU=,tag:rf0yie6maRIRWB3zZly08w==,type:str]
    password: ENC[AES256_GCM,data:Y8kBDcw8K5wiBzIxpLN8o1uMWXtKT6Wqcbr12QfNR0wf6bvfLM2q0FBJmtTH3Jqpb3aqFgbBKIUjtwLK4udsmg==,iv:XLNOGlU/xw8EpjrCqPxwK45A1oPPLXj1KilO9puCJaE=,tag:DGuWtL+KbI/ZJNglYgeZVA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:33Z'
    enc: CiUA4OM7eNBJca8eYjdQukI3xiS9LRQjurwYSrqdCRDIGTbYMidiEkkAPHlbmeDPVx+lh8zWBkLZYYwckjD+GTfG+s1/eqL5Z5oSZrgnfrgEX+DjwdY+m2FhymTfupFoeQwOxAqXKdtJx2sL0fLcuGXF
  lastmodified: '2026-05-01T14:40:33Z'
  mac: ENC[AES256_GCM,data:uqb89ZcDnpWqlElCaPKj9zIMmBK2ZFipfpIdP2YH1zPNtonW/iozH+DAlLvJu5Mhqeg3zZ1XaWQykBvA6hmL6oMc1gaeLb3FxfsHnSpTzkX9iDWf9XikeYZifm23tSi9awS+7s7kU/mqUrMeJcg59fR/zdhKAo3WAvy1rllZsc4=,iv:X5T6yW3jcBHVC8jPdI3NG0wxLnHzrbkDl7DbhZgOcvc=,tag:N23TqdzCiUYK7f0PJEqXCA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
