basehub:
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:aOMIgz+tGLDjpk89q+pFe7TAsAQXOTyYWe5UIuwUYg+aRD6IliSTX4bXU59gHBzb5SvD,iv:pUfzRSGWR/Vl9s6PXQ5AVR6OvNHHo1fBFIwHMDL8RmI=,tag:0Wy+Igo3RqCj6E5hxMaedA==,type:str]
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:zam9Fd74Xlntjf/0lghmUnHe+6E=,iv:z/wK0demwfnY5o5keAJNh8GePATBx3M5hc27mrIFtoI=,tag:K0M0nCq9uyVvkwrxf1hDMg==,type:str]
          client_secret: ENC[AES256_GCM,data:w9dYYWq+5WQLHQqJpWzVAK+D2356wfcomtcYhU4BJv2u9dNdyAA2Eg==,iv:sQFOsgEU4tRCVwiDKM/Bl1V6Vlthl3PKPSxvURMFK/k=,tag:ML0Bl7lJK9htFCPUEy8B6w==,type:str]
      extraFiles:
        usage_quota_config_secret:
          mountPath: ENC[AES256_GCM,data:aRdgvhs1SflplAx6oJ7xFCyTAcm23OTX9eZZgjNwE08DJF9Ern2YDqeSg5uMdjWD3kDLFXTBHV38Ha6JG9xQ2QyMxGuUbiqYhBg/qeWd2xL19RBdYsk=,iv:aFtpIT5KagecEWOhZIcsof2iCU5AIW/m5VWpo0VUl34=,tag:+TrGIF4V3fpC7Pv2/VDjLQ==,type:str]
          stringData: ENC[AES256_GCM,data:GecxXMA9BiDDNxCsh9mC0vJdArJ4oOLYQDdtZGgbXxWM+FPi92gnDVTKX8N9dd8/Gtyfq8/u2gknN7Tna6X+MwnBty/nEfV/4UVoqcHlxuK+Vu2Gx9l+d4t+x7qJGMupLky8dtKb3R3c5NuNe2Ze01bGJI+qSJi0lFaLJMN044lRWuyzbmQV/+kJmiqLCemz918ieckg9ZeDECZZRYsBxLhyIWfpxZ53yM5im9X4XhszSAwILO04YBcL0WBARprgKkf8uPkdN5SpwLT8v0Kn34LTeQ1rVNrbZMOScHygBfnTHmNzQgVWw1KhSYKyWv7PftY25hNXJaljleqN2/EtkD8BSOqyCy2WjSw56gAtmgzJJZQpl0J05iEmk7Y85YlLi3he1t+BnR5mPqRlioOsGIG//vIfvDGCGLLGG7opXcPx6acyUTC0dftj5u4RJutffLcxnl/iwI9YqZjRTHlapMH8CR6AS8DKIS6OGDlJo2x31dSQcwSBEUTvWUDZBsKTOaXmjBFnxYHgiP4wt0sxZdBY/e5iFpIERWrL88dN8osq9CLQ2tpdxCFjpomUAIzzVhTYScEOmh/6IC0w0fMdNNqlyypgEa1BWVHrtRsoMxoB9Tttv2Mh9KglzYY5ABWXLcRTUMkDfhm1fzR3Ku6PguBR3j8brfpYHgpfvQ==,iv:x+T/CjC/iy03TCV8ka1mvTmwKROQ1awRoTH0NXS9c7Q=,tag:aO9XHoi9Ep8bZk6SFZzweQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-06-25T14:53:33Z'
    enc: CiUA4OM7eOVI6DncpyXnwSzngp8EHD/NUqkLur0rypgKq+eB+g5yEkkAmy+ekr/MpPjAV+HciZKSJ8Bt4Md2xeSiPfMV/6uOlvKAbybHiU44Ims/vC+7m4kxg+xntdLEzRMBVdvB+ssnG7qF5lwe4Fyf
  lastmodified: '2026-07-30T19:11:13Z'
  mac: ENC[AES256_GCM,data:+D4RlWequI8ky6efWpc0JttMvTL3lTMyC9LGATHquulIEqaFsvcDUqkCZ9StdHlN1LMhRo1AkXVZIkLUr7/zWDI8hwaVsQik8rxGahe+6YnygB6XB+VwLFfcvB6D4jfb1pTRMLtx0rctjYbtqkBeONlpGUwf+EqyN0bGTsIPF4Y=,iv:9UZ4RDPogZKilPuz/Gq3RvQsHLBzqSJ9F9nOfQhJ3Bg=,tag:RT6MUZvf+AHCwG7f8uQlYg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
