basehub:
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:aOMIgz+tGLDjpk89q+pFe7TAsAQXOTyYWe5UIuwUYg+aRD6IliSTX4bXU59gHBzb5SvD,iv:pUfzRSGWR/Vl9s6PXQ5AVR6OvNHHo1fBFIwHMDL8RmI=,tag:0Wy+Igo3RqCj6E5hxMaedA==,type:str]
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:zam9Fd74Xlntjf/0lghmUnHe+6E=,iv:z/wK0demwfnY5o5keAJNh8GePATBx3M5hc27mrIFtoI=,tag:K0M0nCq9uyVvkwrxf1hDMg==,type:str]
          client_secret: ENC[AES256_GCM,data:w9dYYWq+5WQLHQqJpWzVAK+D2356wfcomtcYhU4BJv2u9dNdyAA2Eg==,iv:sQFOsgEU4tRCVwiDKM/Bl1V6Vlthl3PKPSxvURMFK/k=,tag:ML0Bl7lJK9htFCPUEy8B6w==,type:str]
      extraFiles:
        usage_quota_config_secret:
          mountPath: ENC[AES256_GCM,data:aRdgvhs1SflplAx6oJ7xFCyTAcm23OTX9eZZgjNwE08DJF9Ern2YDqeSg5uMdjWD3kDLFXTBHV38Ha6JG9xQ2QyMxGuUbiqYhBg/qeWd2xL19RBdYsk=,iv:aFtpIT5KagecEWOhZIcsof2iCU5AIW/m5VWpo0VUl34=,tag:+TrGIF4V3fpC7Pv2/VDjLQ==,type:str]
          stringData: ENC[AES256_GCM,data:0eXwe4x5UQ8VQVVBKPLRUfpGQVh5CYYJPOXsRvC3+vKO+42MWs6zkOrpvCB8nEf6cTmDkkOJHiIHCJaraZ86/aNX7xWsghaB8Ss+Znta1Njy33hbwgjf5klGLaD3jTdogHdhy/KeBDttdx58LYRMafeCl14xslz48H3FUClytikzzq5DUVNI7hXVD1098GfZBQKRI8bpH52boKYCwwyK19cCD9N8CP/kyL0llgfXEesazpMEe6jVTLbLhXbMWa0XOjyb1iyIBkA4hLF/Hjmk4f2vmWe7dwHQCAN6XqN9KK5FgSCw8QZpJTJK5ofdeXfszZcXCdZ505cGkXWTAZrkWxHIil6Gztc+7UPmsG2eAjxDpJ5GeTzIJBDzmGV2V/v2PsCoUeUAMnz8sIr1fYg=,iv:6/U+EwGMSMai0i591u4BRkcju+FFvKiVI0WjjecT2Eo=,tag:5g1XeSLwOOV092tP2NF91w==,type:str]
sops:
  gcp_kms:
    - created_at: "2026-06-25T14:53:33Z"
      enc: CiUA4OM7eOVI6DncpyXnwSzngp8EHD/NUqkLur0rypgKq+eB+g5yEkkAmy+ekr/MpPjAV+HciZKSJ8Bt4Md2xeSiPfMV/6uOlvKAbybHiU44Ims/vC+7m4kxg+xntdLEzRMBVdvB+ssnG7qF5lwe4Fyf
      resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: "2026-06-25T14:53:34Z"
  mac: ENC[AES256_GCM,data:+0jJ5VtVtbFjT8+nbsFklWgzcXpUROUoo9zI4MzzM/rxvFnRhrQ5ZDhXGJqAmYDmjmgpaOIxoizYad7i+/WAxFI3LlK1sYhk4Yc5hiqm2nFd6H25kDyIZOt5Y3AYVZD7VX9M/2NXCQJadZ3EuMMwvKzkx2lWETUKVf3Xohnip60=,iv:c5AdjTjOTfYCJxl5sKcSiiGr8uJZRmrTNRMoRBBeqHo=,tag:5Hd56fBAQy1lFCQhvYOLzw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
