basehub:
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:Punl843FRa6SlFhriCs8zJZm5BiBRjSYgLj3GxgFtQdJEYghae9tZXHrfYhRYcjWJ+/wFA==,iv:g6UHxmTjlPfsH0xB1e1uv5vEmIUti6W2XU7RWWjqzF4=,tag:YTbaeMQchOGO1BsymzEwYg==,type:str]
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:EkCm7NhqK3kdix4pM12CTEHt9p4=,iv:tUNxs+TTBcB70USFNCUCFVn+EkXD/lu1gi/FUJOhWpo=,tag:9/qa6j7YgbgpGNBALVAlBA==,type:str]
          client_secret: ENC[AES256_GCM,data:epK6owEz5VrswtZWLH4kN+A44CQe4JCX1GIahiUkpHEgPUyemamIzg==,iv:tetOC1E6oF8DaOaLC0GndMRQcjhirFIaw6+8xV+tN78=,tag:kv8Ya0/rKQpR/Cy2vJ2VzQ==,type:str]
      extraFiles:
        usage_quota_config_secret:
          mountPath: ENC[AES256_GCM,data:Yv6PUr1wMxRYwFb4CSLeMpCB6uCyTgsDxCPyrSJgyM4YLXnm0E6pkk6iJQrX5l1QsUV52CY3fFIgyeeY72eyVkNVFPqAyy10+ZuXoH9ezOIt4NCX7Fg=,iv:FfrepmEstVv1Frww2YxbeutIrx0R2Of8D++EuFWonJ8=,tag:Zt261tpFV5NQpoqR+ImojQ==,type:str]
          stringData: ENC[AES256_GCM,data:QJxLVxM3O/sV4wvtGj6+v7JN1MmtYPXpjlEESpS17Ve0s1rzYJ/dyWMlSTxOsmHzLIGfGv1SkBZZM047I5bqerNF0Sr/WOlq5BNkpq1du/zBztAMddNXt2uRZPqsFd/Hck+uzx6iCoFdmncNQ4opMLI3Zgfxh6JgynAEJkCC8W13CcMOnMh+nRTJD06NkJ6h9w5WFLKoV/Wbz22Ndcbq0lAmBh0IENVJeRLc485qty0oCkLXG4yiWTANnLPYKRSmAI+fEqoKLMURI787bb6zypGkE+30K3+2TTYd9W+/SNKGz6ok89t+f9rv7A8g2ks1pKanR6HtNM4VUcdUWN8iY1jGsCkjOgJ2pOdnf18zC6GOZD/K4WhSQfp+cBizrdQO7EfHv7TQdUTG30dWlbTtZkihezg7F2fdbtzNEggHGljjEm5P5BvOWy/0eNINsaZ55QKuvmhYw9Z4D05kjOh/emZ4ZhQCA3r/o5JBfQGD/3AkHGlDK4sFGVpEjTfDnXPKAHB5GODhHnMXCUQ+MimV3mArq0byaweanfTt513pDOWjAE3wnAjxNXU5Llzy1UizPRLmgKwRXC1i3N2RdUqmssW1TDgHsSvUL9rM7zZxkR5ahxp73eqjQsVrtKN/CaWmWIvEg4bJMwW+aG6ZHpLn6aegBHOi2DIK5Hq6tg==,iv:1bN5oxuQK+UyTU3Ta9YmGHbxrR6rsiVLPF5yKG6rXW8=,tag:aNAsv6/P+hSZAr92fMPbjg==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-10-08T12:42:39Z'
    enc: CiUA4OM7eJqV05ALoFB+3axW39XmBQbArw01DHzk0Y/IW78fxKucEkkAsHDEl4e31qX4TpuDfwpbT1FNv4EK4kc3Z2eRltEU+5z5zW3XwIDVA0zZ5F4xY2HvvU17ql2E0P0CCE4uhIM/jFTYaC3bH1Mc
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-10-08T12:42:39Z'
  mac: ENC[AES256_GCM,data:SZcNnYdPGClRVNehF64d6zPUI/sGM6FBYMmqp4OKGirPVNaf4F3KFlvQClijAA3eHyOTVhy8qnXKn+pTWXMEOaVIAMUAXwI49DeFbZNUPhtjm5LcFU3fjMxucGhRzuq2pD1slkCccbtKkhD+haDulxQ14nPzfhSgbZFoZpS90Fw=,iv:XnAO8uYZe1GPFQstQ9lhqiFuKsgu+W44G+zweKWwXAI=,tag:0KlTrn1aNozy1BwHXnlciA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
