prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:Mrw0OfxYjDjPvmnvxg==,iv:7auL403Jq32BNI0vRNe8Uqx1q+0lViGb4pRsat2S+Wk=,tag:lErE9JnBBt24I3XlE1pzhA==,type:str]
      value: ENC[AES256_GCM,data:NFxYFe0oyHUklAmWdUOJMRzOdI8qFgeR9y/QVdM0CMgmQ12KR5CmPmuf7lkUfYKu0cZFkpLLC7GWEUu+0PnhZEHuli0Pg6CIAVw3i3W0DsO5Bt7VBOmKmefP4CFkygy02kEINqlrTfRDVEWvEZuQuCEryQys5/SCjDe9v8gZGvO6o3stgx3Qxx85xIOZkZNkEOFxSt1nsE9z6r4JOE00CvGgRWe3TnQL4Qpnp94nVXeaEA==,iv:AwhYHshs1w8Tu08uzCH+Mx/60GDdkiiErNNpXO06PJ8=,tag:dR0xlEhMTlI08bg8E59jgA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        SEMpzgVnNN2gJo8iT1GUbQZiApa5Yv64sypBVsqD6ozG6H5mjoUcfRLSoSQTqWDD: ENC[AES256_GCM,data:4R1NN69OYvQvA4S3JuhI9TaZAfRoEo5cNTF99xUuohqQklfoRnFf4o89PSWvHI983/hu6lC4Gf195YRI,iv:8+WcgoA0kDNl7cMZXNO55Na3ZzlsNRmB8dQt2Xw/wME=,tag:6aPYLTxPT0P//mqbvZVp/Q==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:dwAy4g==,iv:OCXTHyaXu0n/r7QQfinN0PyLbCiil5EK0NhpMk/AjL8=,tag:BpG96+Bt+LqqpkJ1p+A4+Q==,type:bool]
    username: ENC[AES256_GCM,data:O3RAbpxXOreErHJ3zDvQOLXCiUHcbGYD5q8ZRvLSLAIfij0Dyve2vVWlnmgLtmV2sXzoCwbj6vaS+/YFz8ZwoQ==,iv:Uk2a3JMAQ76zfZ5RK8HznloqlTjNAUxQdP8tysEO7UE=,tag:iZzJWUJr0J3VO7u7OXvlEQ==,type:str]
    password: ENC[AES256_GCM,data:xeeQ5iDB4k4BJXne1AjKcW0ufy1+L1yeiXV3eBq89IN09q7BF+IkkD4yewjZkfiUNUoeK/tP8hptpTaqUL2+Tw==,iv:eYzj4nZi88TTFf58l5r6kOZ+ZxG87h+XPh2mStoospo=,tag:2W+l042/5laQ1foGd3Bx/w==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:vwrqRwZWxNOgfJWc4bitFXstgSGmdvfECLqyXZHEpX0/7uKVPu5hwX1PPgMUEyxM/tQd3B/Npi313+LCoqEHDQ==,iv:YGuab2WuZn8ZDnL0LVDSYF8zZUTIyjTQyiRqzfUDV00=,tag:1sCtRPq5E8HHXdaGDJmixg==,type:str]
  password: ENC[AES256_GCM,data:+dgBSIuCLXlxyI81K7c6oDEwDizBS+Pq5WuS1AQQN4wa7vrR0686heoT6Mnk9QKHrvn0put9Ano/XAyoRUPAjw==,iv:7n24Mws9x3vRWo8Ic/eAzjqljDk/mzAzNpFu3nFEG40=,tag:z0O43YuWzVh8/mobpyYHPA==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:21:44Z'
    enc: CiUA4OM7eE/xPLcgzyFmxnT5MmuzUCdiPZVGJy+wEBvureA7VNAJEkkAmy+ekqCueVMcrFrH4569aQfACFjMTalUnAWXsIU70pX05M2GQ/1ovqRp4nXs0glJ1PfRcarfwyaeV7Aee0e9cI2pyrwag6PY
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:21:45Z'
  mac: ENC[AES256_GCM,data:D/BTVxfzYH4d3+n9zLAvPc92k4yCpmJPOBhkzg5soULzpjkTzQzE0Jh3fD9Xpo4PCdL90DNYnpzFCgobVJFvysucJ8g2xmCiA212isFvbBEkzRpZsq8ei44tJeWIz8uAb6I++OjosU2OovCiYs3lspeX8a+26vU11vnvnI8+nuE=,iv:AJQ6ACyWGp239IbNO8OB7AIUuiWxMNFS98WLALKjrYI=,tag:lSD75nFqW+87MoLgGx56AA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
