basehub:
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:V0cp9q6gaRtukTkUteh7x7PRq8o=,iv:sOom+QJYMPYIk5WCweH4MVoa9UbYsaimxdVtQf0YLVY=,tag:gidWjbfxoSgWUsxhTXw3FA==,type:str]
          client_secret: ENC[AES256_GCM,data:HNYOPbJm6a7odLo4nIGf9gIEvrdJezTrWRWK7AlnlFKFz0WrwLxn/A==,iv:ICVOQUI8JbiIDXWXr7e339HbbG715mYh9UQUi1uIyOc=,tag:Ti0APmhL+SVCYz9msH58PA==,type:str]
      extraFiles:
        usage_quota_config_secret:
          mountPath: ENC[AES256_GCM,data:dnfWqocl00+LeXs3/GrxKTzmmjF1fo9wCup7LSHWQhCWC4t+gPXCiUOxSIgu32CpNAFEv20ouKEGkO2YoKT815DBePws4ivm1SOPqGsTMIkQkrPD76g=,iv:LV2ReBn48nCFsSfeE2P75TFeAJIEgxYF0jx1wlP2YPs=,tag:uyjB+XPxU6H0SzFr+C9QSA==,type:str]
          stringData: ENC[AES256_GCM,data:CqCOAjttvaEN7c7FN/Qtdpn+s82WGvFAB4su4BKNUf9jd80FDsJuLpaFdrLg9RZ+15fo2KpXnnOKYMEE58pWcOv3dLuOtwxEl+WjLPUR5GRrT13Jcyubo5WtLfJL5jb7fHQyLIhkNIuyZnqSlxvYaRGhKvd7u/VnZ50sIhsU77+3A0N3DGcFXuVJnP/m+Tb5NQn5+2koebSnYJGf1YfyQPp6AX/LOTBGBxKHFBWWShgsPnrGX4Ow2ozgouOpdxcDcz6gMNB+gokNILaKYivmZ/1pH5Ae5zRXavwv62unZx0TLR6ZFzGppARamybiO/S6TcOALS7n4z6B4f8Z42oNmiQ7Ky4T4Ezf3YU55VmgYg31jn3c0Xnq0gdE4AGGeB0o/vd5NaDWXrT56tUbUAr0Y0VMJd29BK7W9vNiuBc4KrQ07JfHb0JJZeDrnZYP2viulPHu9KIn8L7Kxr36eFJMtzcvT78SiYTIa68yojvXUJhtS11cV4+wAHc/8XCOXoXEz1DF57hGrHDSb5qFgMq6vivBmuY0B/bRe1bpFVCdHMa5DUymArrY7PC5R1Po5kArYwz+OR9Nq2gjjLUSGunlZ4dZI4e9JwkZc3a+VV+gbTyZQ+ylIxeEZEEk/ClIixqdLtPmCAzDqti03WV6Ag==,iv:EYt4OoZ8FJPutdwOhEk479J6EDR/3uJzIqkvFtXmWvk=,tag:wooeBoQFGY+vOu1JgHqdxA==,type:str]
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:X4E3kwq5D3aOPURPerXmYFnTlkD4c0IkcfHXtHzA3vRnWErP5Niw1agAxOO9QiwxFJrxnCPmh+eY0cXEOdOPwxj+481YMxyGHq9JnuXIg8Ud9IzSUZIBEMlFvU1pN8Ic1AdJaxUAeA==,iv:NmLGSQE2OrVwWTFk5wyoRFtDtYp2cuW2Ma4dCWMHDs8=,tag:rzpfhW/LmHPvyqNgmMpdBg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:16:35Z'
    enc: CiUA4OM7eHN5dRvR3XgU/quDN4zLsaSwY1gGDk/YD597JVqR1YnjEkkAmy+ekpI+0C4EVojqbVX3hHzGIv9eFE9he4WHjv+nr2luwAxlehfDakBnYhUwvmgWN/+32y7JvKz8I8X8yIRsLUA66qdFZbht
  lastmodified: '2026-07-29T19:16:35Z'
  mac: ENC[AES256_GCM,data:jgh4NJkJkZd6SFahn55LPwcoqWgVRxZRT/D5YZ8q83H9rbDH1sXbBIskNb6hlBOoCuBypag/VIreLOwqzH9Gk+WwRtFQfAcaTAV2kmMqa8LjNEQr4Hn/B4Okic7aqKAiSYP5n03tRJjREseWEBzYHCCfE3Y9k7XTWMAdThb2g1A=,iv:QTZGLhyrJ+BF31lzLQux+jR5uwmAP+3UNqp767tirkU=,tag:VVn7PK49x6IKPC1tZWJzpA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
