grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:tA==,iv:O9b3WGYqj6353iS+K+SR6TVP2YHPwMxKSWuS/q4ec5o=,tag:ddhKjGgfgCu1oCyhNvYfMw==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:T0rLgVNZKXgt0g==,iv:MPj3MCq6XO5XREZSRdZb50o9Qgkf3S2yLWJgZqJOPTs=,tag:BCIiJliyh9BC1Gb/8Qfp7A==,type:str]
        orgId: ENC[AES256_GCM,data:9w==,iv:FxfEDHPcgF+Y3sR//HitpBE6zrtG6yu7CZX/hiiiXx0=,tag:im2mD8bJlF4SlIcWHI4G9g==,type:int]
        type: ENC[AES256_GCM,data:csivZP0EWbitRw==,iv:DTq+BxBCO1duxRzGbEaKJtinCnQHHEsfma/YC61846Y=,tag:Zp04oaJwihHsnDBpl4HCTg==,type:str]
        url: ENC[AES256_GCM,data:l2Chae8YXSg1xrBebluGbqQdy01kHrkEiOpzaf1ZhfQ=,iv:MTUjFDDH4zx0hEB0X9bB56aI80Xl91EUu7vGUZz0rrw=,tag:rBQnq3QOCw0ji3weRGcjrg==,type:str]
        access: ENC[AES256_GCM,data:sJoSn20=,iv:iGENuQYhUdKpi/6q4D5CW0Z5v8FuqrT3i4EfuRM+QhI=,tag:kQ9zA0Q2egdUut9GimtM5A==,type:str]
        isDefault: ENC[AES256_GCM,data:bHpGbl0=,iv:gMUDRh8vD6Htx+g2U4ZTLDN8upDMgkmRJDGof2EmILA=,tag:lCTVqudEE3J/yDpe+0wgtQ==,type:bool]
        editable: ENC[AES256_GCM,data:OOk/3EQ=,iv:9AX95eQPH7m9lG12NS/nBtA+yEdScVXbPK2SpGA0sJc=,tag:r5X6s7DJTNqS65JeBYKSRQ==,type:bool]
        basicAuth: ENC[AES256_GCM,data:jRpiCw==,iv:F6+noEGHbVoZc3SocHQR+HwZCwgqP+eumBhA4rKpP/A=,tag:VdUecNVaC8FaimbKcKeP7A==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:n1wLzrLJCNdWjMOQoxFWlA9CzY8VVlIoHwtinwRDG7Jan5E9bt6rqAztMuIfod7BtzCcmxDdRiXbUTAYcr11Tg==,iv:qQDNlldqWnYb8o9jGBPEcoP1dwncJESpxk87WwGWf00=,tag:kbKL5Ismt+rE3A2B5dXP+Q==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:0U272ZhY1xeta8f3wSnEJrEZHZ5bC9f7gn0t0yGEkK+3S78L/nn5vGuPvBIQdOi/kw7Y6WfgOfUTKM7rhO1hoA==,iv:ruuS0YwHQNjS5lXezdG3Dw6RdwL7hwNP90SjHOZ13ys=,tag:A6TvCIY8D7MI4Uw4P3RO/g==,type:str]
      - name: ENC[AES256_GCM,data:niHk3EKB3CMTM9ZdA+0VpduCETvasGLTXHackiBeyQ==,iv:hJP/vx/1Dwb3noWURiKS9BZfOahOGq6US4UZOScLqw4=,tag:MgIdSo/1s8IVWXws30wx1Q==,type:str]
        type: ENC[AES256_GCM,data:aRWGsdu08FHzQreNuElIke+ahk4NMc+Ygjxl5oY5yg==,iv:oKMsI3fmYXhPHHSH/RqYe3Mb5+E5Dce8x8jNywxSzWc=,tag:83dvkNq2SvIFyLGsWWNF9A==,type:str]
        isDefault: ENC[AES256_GCM,data:5TVHI0Y=,iv:dqJrMjSV+kvql/POE1j7sEH5JUBG4SU2F6wCcVXmJQM=,tag:3s1sAjRKx+ylSLmcrNkCWg==,type:bool]
        editable: ENC[AES256_GCM,data:sBjmJQ==,iv:rfvFdf1Je5lIcj5arMixHA2hLZTJN+hV40TGAhjZ8Ag=,tag:tP0EiFqmHPdYwhY4x/sEaQ==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:ldiJAINoqCK+CJzGlQ==,iv:+6D5xRQiCMbd1FdD/7oeNljITWKdk/o5qPvkrrwhdgw=,tag:MMcNkC52AaFwChCLZP7qsA==,type:str]
      value: ENC[AES256_GCM,data:ZeO8BnR0+jtJGJEGbDp+hq5DmaWASAjFZeSslfzQCgwCz2CsY4cPkeMc3vpu00AC9hzTu61KZORx45n7tApqx4ULiyMHdh1GFxroXSauejdqtYnFQ727GU5rKwyFMZ26mJAt1p/UA+OVdK4PJ/Ut3tz0qcwA6KuKTC9832mHnlWGkIkZY/Grg5VvaKPERdCp4IblXqROn/UE7Gc56Y6n+/mUGTIDsz53YwP3PAshsIbHxQ==,iv:cDad50L7Add3Rssw/3xj2hFnpKfCyw/+IT1o9Ya4KNY=,tag:yrEBVjN0mZRWjrFndeV6zg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:jaQp7OG1LlAp+j9eMoCPxqWt3LaYvomq/zoo3w8VLlOQidqN2u5tvrGEuqRczCwedg2QcDw185CYxaol4+LVpg==,iv:lKQ/X8sPFPKHrJxt4jQYbJITrwdvpQ4nUMF81lAWe8c=,tag:od2F0xMn7PS6k99tAMMvEw==,type:str]
        password: ENC[AES256_GCM,data:sAH4zkMYFGsQnNqNcENB0G5gshv5hdsvGXEXcQRJV/aPZGZBFCJA98iAfJLgGs/b1Iw8wq2PWWOabgP3IBsAfg==,iv:C8j67lgxqeu3mUdcxdkdoHiQTi9s4k1f0V28Qr1zMnM=,tag:lV3PodTWskgkNcELLBkRuA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        SEMpzgVnNN2gJo8iT1GUbQZiApa5Yv64sypBVsqD6ozG6H5mjoUcfRLSoSQTqWDD: ENC[AES256_GCM,data:m1ASKJMKV78oT0OE4sp2bCJY9XEXGG2all6it8HBh1QRJw11J+w5rKS/DX4hecmiEQ/MRpP9SOftBWqz,iv:zJ5PDVjmVxLzfg+pf7xfktv80MC0ii4WB7sXQkNFsb8=,tag:xeye+MEoljM8KJOHCxYy6g==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:bdC15Q==,iv:0oOMDn3EoGr9OAxupX2xgSWTrjjr67QsSlrSYEP66qo=,tag:QCUFw2hAng/M9T4Iw/mE9A==,type:bool]
    username: ENC[AES256_GCM,data:4fHvRGSfHgNLQEmsPJymXL3kaN9gHlAY9hddb82kURISxb9Lf2LERMonvT66HxafNW57Sk8HYhbwZ2m469bCrQ==,iv:F7OKYg52c0E/Bnhuu3W3BHED8VGNKQsI4YXMEvaSgcY=,tag:Smj/ZMeNF/14oP33xB722A==,type:str]
    password: ENC[AES256_GCM,data:IIKrCJhRmp4czSxGHNmAkhPdr/kAd1sSNnynf3u8GQWmC+jzSDJgZza1lEZ7/K9pqOn4UbxVfACgi/AvuBkDCQ==,iv:EGHTFKdhMebJ37I9Lip4qc1+RacpGxMno/L+8te/BIk=,tag:9GGZOzaH2wvaEzECRDVJIQ==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:6o7dl+OUd4FH1wbfVx9k8qBJt5nBCPTrqwQeN/rdXvYocR3aP0GrHCKEiwRq5mu0P5CLGUW+5P1aEzGBuMALbw==,iv:Jpbhj3RQIa3XWO0gp8WnBe/nOso3nUcgtj/QUVU3cYI=,tag:HaXbZaEQtqPLnzOqCng0AQ==,type:str]
  password: ENC[AES256_GCM,data:ZVHLk/oOmC+EIIrVEVLsm4boFxGEG16iJYi/mPDk2m4YXbG/lNJfz2t/pu5QXE6+bdAiLKhK/Cz7VsHpKNnn5A==,iv:putbkRlfLxRWMRb2+Drh40iOcp5lVtbhUTS7ZQX+Wcw=,tag:/QuZaZaVIWm5R/N35C7BbQ==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:06Z'
    enc: CiUA4OM7eGqEAtJMmE3xYQ602JQ9qlpV4y1hoyNHzfXxtrpljXMNEkkAmy+ekm7CeNTQZcV0VZzSzWoxfngLWdBOA4Ek46mNVNbTY7xBsdeu1dLayJeV9s5ILvvmQwgcLNlQeguarbsJatmDN9LPhtoB
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:11:06Z'
  mac: ENC[AES256_GCM,data:uRYJDwW9JnDgBpkggvAV7XbptN1us6Ig8VJzcfhX2R9VKKSqktP3o7sKPgvVRhB5+pck7rErYLsiw1ukrHkHVXjOvOJmR36Bu11FuKC5Yo2dpFYH6v11rdRSjZSuHmtijjqg7B7SnIf1RG6DQvVLuCcjlu9Le3ta01NzXInV+7A=,iv:p+MOmF7NzYfmyWkzZNaSNaPQGtmznk0kcrMFVMWxC1o=,tag:/29T5Z9uDg79bmNN2Y5zxA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
