basehub:
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:upUx1NjQscIb6laxYt7OhdtZsYY=,iv:BfHtJjxjHurxlBHeRximGi64T1QTGXujoHulQyQUMD4=,tag:Thgaisrg6vbXSQYDsaBhDw==,type:str]
          client_secret: ENC[AES256_GCM,data:2+gLGoXqnrKMAygstSwUphUdubwx7ITqhRRgHvqOKvY5xAgr29q0IA==,iv:JO+jHwWfMh/P7N94mlsfAXoX+uxKlDY+FhRULkXyq0Y=,tag:u1WZGPg2Lv3kOeEcG8SafQ==,type:str]
      extraFiles:
        usage_quota_config_secret:
          mountPath: ENC[AES256_GCM,data:fVM3vnhwNr3wYoWirlknW6Fgg4IIjWu41eIA7XZ0mBTRCacRWsvbDAw1z/tBACnvNRtJwgsBJnojeAgMWhJkmVmskYOUHN7lO0zURPUjkApDBSOB/pc=,iv:Jv3C/TJxA4orrUYz/xZfW1H/TdyEhp14nL8143bnCIU=,tag:lebIcvYi4yiBKjFXHbAIgw==,type:str]
          stringData: ENC[AES256_GCM,data:oJ85PXjxorwh0qR9XOW6JJRcI7McnM3LziRyfCm+lfrvkrFrkdqPsE1AAH6Fhq1WQJyRLfJ/ukPLRGW3EMq1cLojNu1pwyoLLpKGPcNL+RaLTbpIxDelXVlrkNOB6SanPU+aepC/EUiSeS8Enjza1ADKMbYjGdK8N1EW2q6qiIH0w7g+4aVKO8CDEijG+ILz/SWXenwoQnanOGzxwJJ48/xByEy8gmgHle2pLaHp5OiNkt/pUXsXz9CwfdBC50NqfzCXj6Wn6SfIDXTYjnO9EQVUtvIFpW+lysc8xwttYbR8EStAABjEftIIr2DgnaOkmv21zt3AT514AZDd2V83wD5nIVCpZHQ+zDSD1Pd5wNsTaHKwlDHTm+HA0fK8gnZCcPtY4kRI6WhPSVJ26xSv/lSy1/KuDrSldPdHB5/8K0BpeDFduorrLrvwigSkBHBv/VpEcwrR/pxwl7rGi2UShx7paeza+GPfhnb4YPMfUNF5ug/Bt4tZ7A8obNHlQVofP7+lEruueWMnFQWzWlVQbdL9zQJrD2dlj2oRmGqjr2qkbcEk0piptgRZRGJYaqne+aIl9PieOo+02RR1+PnvBUNOPEoLg+L9zMHl6xvR+hzn6fYndkPjbtLuK6oH3y9whL9Timan7Mv5q4Z6GQ==,iv:0bUEOSxLM8WUUoWV5SJ52BzLBlMAKwRcrABvjLE1ogE=,tag:DOFW6j9pLMzGy73i7e7q1w==,type:str]
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:7WuIzF8HIsEp7BT9tMWCbKbNbnl/P9yFBn1/PjQWgSerORr+2HscwkIq04xDdXFQ+SuT,iv:EUZb/4LesXk/J7jg97NPmEQmno1cdHUB/1l/9/AD/do=,tag:mtn9niozBOzGQP6y8ADPOA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:16:33Z'
    enc: CiUA4OM7eInSfOUDQ0fGcB8ULFipOoJxzTXpEE9aO9YFFp53oF+HEkkAmy+ekrK187pncEYHImO5qsBjoM0EOUCqPrQk9FBZalxo6jbdDLSbcT+eOjoVPnZ+l6wzQ/krGPBM9y5P+0Jt0nhr/pjOz+cf
  lastmodified: '2026-07-29T19:16:33Z'
  mac: ENC[AES256_GCM,data:l9XCo/72wf7NPMhH8/ZXLrqAn2I0UokWvINC50B+2CZfSfzbDAYklr6g1uIdvh2dpvgyygB0N5qwSOfx6fY/aiuL7Qj0IFQlpGFTJkR9jC93BDkK+tu3rQH4dOUushGOYwk3PbZcwAED6b3ZKL/C9zIysPv+sAFGEtkKnBlLEow=,iv:OW3wpYW+owvVxT3KJjjNLtInCo4dm14iZ68+oGvGZZc=,tag:D6Ae9+ov7qxyx8QtLWC+fQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
