basehub:
  nfs:
    pv:
      serverIP: 10.100.32.135
  jupyterhub:
    custom:
      homepage:
        gitRepoBranch: master
        gitRepoUrl: https://github.com/NASA-IMPACT/veda-hub-homepage
  binderhub-service:
    config:
      BinderHub:
        image_prefix: quay.io/imagebuilding-non-gcp-hubs/veda-prod-

  jupyterhub-home-nfs:
    eks:
      volumeId: vol-0063ecd342e052ef5
    quotaEnforcer:
      config:
        QuotaManager:
          # Community-requested value
          hard_quota: 200 # in GiB
