basehub:
  nfs:
    pv:
      serverIP: 10.100.29.199
  jupyterhub:
    singleuser:
      nodeSelector:
        2i2c/hub-name: staging
    hub:
      image:
        # custom image built to install jupyterhub-fancy-profiles from commit 9754f2188e337cd34cc5c533080583fe92fd47ca
        # from the PR https://github.com/2i2c-org/jupyterhub-fancy-profiles/pull/149 for testing
        tag: 0.0.1-0.dev.git.15561.hd27897dad
      loadRoles:
        binder:
          services:
          - binder
          scopes:
          - servers
          - read:users
        user:
          scopes:
          - self
          - access:services!service=binder
      services:
        binder:
          oauth_client_id: service-binderhub
          oauth_no_confirm: true
          oauth_redirect_uri: https://staging.hub.openveda.cloud/services/binder/oauth_callback
    custom:
      homepage:
        gitRepoBranch: staging
        gitRepoUrl: https://github.com/NASA-IMPACT/veda-hub-homepage

  dask-gateway:
    gateway:
      backend:
        scheduler:
          extraPodConfig:
            nodeSelector:
              2i2c/hub-name: staging
        worker:
          extraPodConfig:
            node_selector:
              2i2c/hub-name: staging
        imagePullSecrets: [name: image-pull-secret]

  binderhub-service:
    dockerApi:
      nodeSelector:
        2i2c/hub-name: staging
    config:
      KubernetesBuildExecutor:
        node_selector:
          2i2c/hub-name: staging
      BinderHub:
        image_prefix: quay.io/imagebuilding-non-gcp-hubs/veda-staging-
        auth_enabled: true
        hub_url: https://staging.hub.openveda.cloud
    extraEnv:
    - name: JUPYTERHUB_API_URL
      value: https://staging.hub.openveda.cloud/hub/api
  jupyterhub-home-nfs:
    eks:
      volumeId: vol-0a1246ee2e07372d0
    quotaEnforcer:
      config:
        QuotaManager:
          hard_quota: 10 # in GiB
