basehub:
  nfs:
    pv:
      serverIP: 10.100.29.199
  jupyterhub:
    hub:
      extraFiles:
        usage_quotas_config:
          mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/jupyterhub_usage_quotas_config.py
          stringData: |
            c.UsageConfig.prometheus_url = "http://support-prometheus-server.support.svc.cluster.local"
            c.UsageConfig.hub_namespace = "staging"
            c.UsageViewer.public_hub_url = "https://staging.hub.openveda.cloud/"
            c.UsageViewer.enable_compute = False
    custom:
      homepage:
        gitRepoBranch: staging
        gitRepoUrl: https://github.com/NASA-IMPACT/veda-hub-homepage

  dask-gateway:
    gateway:
      backend:
        imagePullSecrets: [name: image-pull-secret]

  binderhub-service:
    config:
      BinderHub:
        image_prefix: quay.io/imagebuilding-non-gcp-hubs/veda-staging-
    extraEnv:
    - name: JUPYTERHUB_API_URL
      value: https://staging.hub.openveda.cloud/hub/api
  jupyterhub-home-nfs:
    eks:
      volumeId: vol-0a1246ee2e07372d0
    quotaEnforcer:
      config:
        QuotaManager:
          hard_quota: 10 # in GiB
