basehub:
  nfs:
    pv:
      serverIP: 10.100.29.199
  jupyterhub:
    hub:
      image:
        # custom image built to install jupyterhub-fancy-profiles from commit 9754f2188e337cd34cc5c533080583fe92fd47ca
        # from the PR https://github.com/2i2c-org/jupyterhub-fancy-profiles/pull/149 for testing
        tag: 0.0.1-0.dev.git.15561.hd27897dad
    custom:
      homepage:
        gitRepoBranch: staging
        gitRepoUrl: https://github.com/NASA-IMPACT/veda-hub-homepage

  dask-gateway:
    gateway:
      backend:
        imagePullSecrets: [name: image-pull-secret]

  binderhub-service:
    config:
      BinderHub:
        image_prefix: quay.io/imagebuilding-non-gcp-hubs/veda-staging-
    extraEnv:
    - name: JUPYTERHUB_API_URL
      value: https://staging.hub.openveda.cloud/hub/api
  jupyterhub-home-nfs:
    eks:
      volumeId: vol-0a1246ee2e07372d0
    quotaEnforcer:
      config:
        QuotaManager:
          hard_quota: 10 # in GiB
