jupyterhub:
  hub:
    config:
      SharedPasswordAuthenticator:
        password: ENC[AES256_GCM,data:7QIZ5EgeEipjSf4=,iv:vEnHEslBrue035x2nPFpq6NOM75LM7fMfmZMc7bO04c=,tag:OT/Ij6D4qi/F3qcILRoLmQ==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:Qa4i4LvS78hVQZbu1oawp6AeBsVNad4xZxwrO9o2S7us0oPb0AJVmLQwmJiRqOc5wygyXkh6rhmrtLbrrOjFAOsB46LRKDOVj8lP5h5vDF+h4PhSv3w=,iv:uMT+jCEFortj59UnuuIrjy8eJZ292uk0qFAbVTiWTVU=,tag:+2aPXLYr9N4qrMEprstPsw==,type:str]
        stringData: ENC[AES256_GCM,data:BKdMMVfDOUfFTk2+SWhPApcutKsxFmLt2Jx8G0nVxgPealkTS0AD/lL/oBoMtoX7TlK2AY71hqv41LGSmaUlg7LaBxl0/ypaSXJn1l97q9qZs3OBCGN/0bEWKd73gmYEuJ5nUkZxp0QD6QnvcHNV0fkP9n7T4DS6aNYXFh/3VTuIZxK6D4YIqvEFJihL6eoDQgWL6NPFACGkI5BSKM2JmkfY/vpCdbACaXKFlFUbWCDb8vN+fu5wps0krK15o8OUHiZ/w9JP5b4C8F3nMKV32hpTJZUGonZ61M5XOP3VeykZSY1jzwiB3PIkMyFyqmGxeRekMhpbjXLToJQeReugfGzUKi+Z9iS6wZZRjU78SrxURVciaJTylSeFNYn5JYqZUoDo1mCQHBr6xL3ikQ8FhcNrriC5NlE7EkWLg2DcRcfG7G6cPxaU9iuOPVKB+RvNh7JwpRqjV1ah5k59Ha2gelUKPpMzcl24el93iSLRU9Eh6LuJUB/wWmnAmELEuoH0iuh0o6FFhLUKd5UXQum70z30PQDOE3SVZtc0EElphSwXa3K2PRM0VIp7NFLwTV5BEbVPFeatQCHRAbIf5JAoI4mwduRsBvNvHrj+O93vKUGKi506vB/0bKgT6fxaCiKrVGWMFUip7oYiY7WoPA==,iv:Mcu+foOKAvVLRRcR76eZxgsKSo4CFkfyA58DK4Xy1Lw=,tag:lec/V5mBIeJ2VyXLRtkd8w==,type:str]
jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:bkuAxDtFaitkzNvdnv2moQ1E8yAla/TH8Mu86UaBQqD7Hw8pghDHZXkdGPKkW+MxUOL+C/33,iv:p2ZTlzbh+ypku8bt8fWJHbJgnk1wsOrE0VDJ95AL4bA=,tag:iPnZTONKRvzptfw2axdY6A==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:17:03Z'
    enc: CiUA4OM7eEqrgkrXUbhjvd3x7aiYU+qa8cWVsZ6lRpY15SYygOkpEkkAmy+ekqGvKx/yH7FSX6jUx4YkiQ/2QM1WE3tPuypQ1GIxXNoxEc88r8PNO/iNF2cXThWGjeljy3GlNrSFxGxtmG1nYywnvjRt
  lastmodified: '2026-07-29T19:17:03Z'
  mac: ENC[AES256_GCM,data:Vf+KjwpUtyLlsbF1F+IK2geKgOk+aDzLSeQefsYgdLBHGN+WQJvQ9/GonZc2Wl6LD0SOaahTes9SubBCHJFiCEHdqr/L9grE0zs247/3JLp6beFGJOcQ1imKp+4h42gFHb3dLshJqsE0zUc+b+J4+3IFRZxWWESBHWRzyk+Lc9c=,iv:J2+4TwZfU7TXEYtYGmUXINJ5pjpYrHB1mFXosUPJHjw=,tag:JvFa+OWqTIegfM1WYY5eIw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
