jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:IQwfV4FQZBZxo5iAj5VxirSOH24=,iv:mxs1+nVIoghzONTNEBGcQYbemVt7T50nAyfzOeM132U=,tag:rR8gAA0l4ZFUkLs+2k6/dA==,type:str]
        client_secret: ENC[AES256_GCM,data:09zfX4ENvSFtIugE/pdcdHMLk/bQ9gqejC2GPvsIAcVqvTTI0vgL6A==,iv:6IyitVk5RqFKr87kopMCKKpbpalvfzQXFNUauaIcGUc=,tag:62w6GShC/s72hCOzq2+Fxw==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:DSFy2b9Jenza7qc1HJ+D6nSY4X2Z7Jd/P6yJ8q/pEbnR+8bExXa07bEfVj4WVQABJ5Hrxldg/oZg+oYtmcYcAlJAQK2FgVg43DDQufrWfiSmZ7PHIxQ=,iv:giyQJApyDgBae5W+m9yYxz04cwL1iOwRg9a2wC0n8ek=,tag:NmMInWDYYHFb6E020dhQqg==,type:str]
        stringData: ENC[AES256_GCM,data:96bIwabK4EA7dns+hb5zXA4AT33yJ7ZHowzrf9euK/iWPD3itvsYNGMzMlkGfsp5hssWppl53AJh5+ns/NYrpG205Xj76AZtKz08J85+yCYnI9kxVf3k6mJDyE0b8B5Oml4ZnZy+KYIlx7diYTPmAUzr1100jniCLrjrjXM2GbTkzuQjqoOWQhI5B76E0JFUwZIlvW9I2+6kbYWy59vPR9qNzjN0BwjVfP7TAI16rkqOhTBQbiGYnLUkFb4ePqO9zeIRExgxsXTInYS3Z1iXJpeVLNk9eesHwMml5Vup7CRxeQp6Wn6z8NfLi0UCd4MQH8anW2ajSJIVBe5iz/fsNIirbJDQ7PIYSE6QYibcDU7BKs9igttUnz8qIj5Dg6iPex+LOuDoN/gRezw9hmTZKI0ZkBkd4usyPM1de4V1auo9oEUqLCMHgMQmvxQVJznqdR6RImPw3ux42I3aV1p69djNM42RTyFcPd9mGE36T0hc9nTRmybJ1XiPoa9D/6D8lrWaMGi3wFVpWIqmfppXBsuxOMjuLFCSY3cDTNcFlXSaZmPBEdfVzRYkOOh3eC68Zk/BJhoWImno0/Sgyd7w2DJpGjf1TiR9CwCNuWfFbngF5qDub6CC/LsoPiPKkHq2LP4a1ALsf0enoFNWSA==,iv:Bt46ka/8I+DaDf2rYlVbc5xmHLTzNVO59PvnbNyq8VY=,tag:ZEXtJodk+zS0QqIIBgB0XA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:16:59Z'
    enc: CiUA4OM7eFxPBGgl3fIf/Y4rweaQ7NylwggnUGurjZ2XptPTpOO1EkkAmy+ekkudcowtAxZEOKM62vAxlafgA5HdHtWfyzab+fjYKsr/ylVtJ9xpvZBvPS+2YaVLU1qZg+Npsqk719MyEFBg3XsJTv5V
  lastmodified: '2026-07-29T19:16:59Z'
  mac: ENC[AES256_GCM,data:lkhVVgkO+3gEp7+iMqrX3KYcNTNEapb8fsUCwxS+vsEfdJJjXik2D5S3dEyTpNVjO/P16d0yVuyx23Vv323YA6cAtw5PkATD7zoiGLSgMSWaGbKryLJ2HTUmwBic6GfY3HGwTjslPDSvyhK4a9y+wqiGetNHJWljUuEmy3l4heM=,iv:8TO2MR48LCEaXC2R5IFvalPZ7qAwKbqLZDbz424kijg=,tag:f+f+LjegTExi4/rdWrWVVg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
