prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:Z3Es02zrznlgMKDXPw==,iv:xhKRUZ27pDj/pAUyijXyh4fb7pv//WvOfHwxReG3PGg=,tag:AqnrJ1dVhgi7Pz5pmxR6fQ==,type:str]
      value: ENC[AES256_GCM,data:FiVX7T5ieN3R0Ts4WMlSLBLGKs0QsgbLwiD/ydyrhhnLQlvn1E61WcjY9YntVQCrMhlHiFNSwQXNfPwtywUmohK3u3F/m2OpD3SAzp1pSmhGoqDgx4SyXI8AR93VVJd/ttj0Ahlz06ffeLcGpsGtUMVZm+/EQmB1njBbU4u6I04a0kPOQEbgrKk4zuhSFU15x8YBY9zjkrIQmsE256FBfhtPnXodPw8cbY26ESOskkxpZw==,iv:C+mmrkGID2smWyrsdiYzL65ags6cFWWrUITZEG8xqvU=,tag:YbNh2+kjJL1b6DBI4eIL5w==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:2GZKVQtiniQv5evDMmdrBbUrdR18ioGXAwyxdIcxzt/MMgcjaejMMlwY876sN6U0cVzyrtnf77R7V3RxTcaspw==,iv:KBkYczoK/k/ho99aAZ1qFj4xWGalnXog0YFwKLLcFAU=,tag:tNEbImtOrCva2x91A8qKuA==,type:str]
        password: ENC[AES256_GCM,data:1KMecxYfdo9YmEdJ2aOEJwI8WnLVkniUSnOJbeMdD9QxcUtYnliuPoXiRfrYkOkXhDnccON7+6s/8ZnvLhcPmg==,iv:1W0LV2lwvTicNlCc3rMF5KbyrJGet8dKMyaOfM/knKA=,tag:wr6oRWSgsAkf+TQlKZeS5w==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        HFSmHnxpjKCVdvLjqwD2EmZ4WZpKzb9lQ4bm1N6JArP9lx1zrLjeZx1EWl9QZM5S: ENC[AES256_GCM,data:57isdWP007zeXRCJ0ANiCsjxa8A0xk4Q/OFxU9BAywNDbh6wziweZ3FnjBV+jq6SBZBEJvm/3ejrn88N,iv:tIGFPRAxMWkHG/4aapo/ekO2cu6BuOQia5jvxX9tC14=,tag:Z1C73Y7DEqnd6N5hAJSQBA==,type:str]
prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:AxNkXjTKN34IXjWNTGxi/FU2JE6wlN6gF43GTDImF+iUKQI3TrnhTH/FDXisRROcQDDVEKRZNp1D/UpgIBCkKg==,iv:d4u9jKsNtxZ6/xCuUTCZ6rHzNf4g41Rs5uOrG0+TxuQ=,tag:bArsiQjcs9QNEEv6O0Lo+g==,type:str]
    password: ENC[AES256_GCM,data:bD9YmwxBhkqWcVRb+t07kCae6dHTJBNXTR4uM+8hi/U0f04yljjN+BLlIFOwwz6tjrE3wOv44qaY+FRq9Tq5cw==,iv:Hs/SJuZhqtgf9RdX2PRnkoWei/1/zGcPulMaQG2V6G0=,tag:ViXnJDRAFIjUIV4Oz4MPjQ==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:wg==,iv:EpXQLN0ZCFd8tUqvBs26K+HAoYykuoUyKe5kosj6iTM=,tag:XYo9JDh3jtJ5L4+JB6nTjg==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:s4PK9QbzTnw+nQ==,iv:Rx/Flz7XK+lm6fAh20xpRet3RHQ8kfWKm/UDpdIMbAA=,tag:CAsdmpoQsUL+2CzPDiY0tg==,type:str]
        orgId: ENC[AES256_GCM,data:HQ==,iv:ndFtZn7m1Y5YADffN4clRVk6n32ty2JY20nhKrpJl9c=,tag:aG3yK94IXhyCj7JnSGc69A==,type:int]
        type: ENC[AES256_GCM,data:5oRDLX8tGrbLjQ==,iv:kZA7JYN60U6GTXMcV7AoAa7pybCAwUujQltqa8+3QMo=,tag:DjOOD2wk2uHAcnCKH9oSjQ==,type:str]
        url: ENC[AES256_GCM,data:7+CmB33KsQTHDdA43p9De7xUoVLm5lSxEb3doQO59hE=,iv:M3NWSLj94vgWFUY/5NUbRDwpoDxc6YuFR1lyxl7ThUw=,tag:HfNrf/dEClz5P3AYDlHxnA==,type:str]
        access: ENC[AES256_GCM,data:52xpxDY=,iv:TFM1G3Hc55ArAPW+MMkutg/nfU6E0saBOlX9VCNP+tE=,tag:M7FD94Kr7EooLuJuAhbZCA==,type:str]
        isDefault: ENC[AES256_GCM,data:n+kFy0I=,iv:Ubb+u0JPExXarMW9sUAlHzyIN96Ej8g7fHlRslsG9fQ=,tag:Ob20FBsi7f1odUl9BAI3Iw==,type:bool]
        editable: ENC[AES256_GCM,data:jV9o2xE=,iv:arCJutrizVAroDJRZ2uGLE+/g92OHvP/tClcqWLbnSg=,tag:hFaOPq5wqnByEopHZzD54w==,type:bool]
        basicAuth: ENC[AES256_GCM,data:kIKycg==,iv:Nv3mHYHXJSHKlZwxubVRxA7GlQgK3aAh0Aey/hjTouQ=,tag:kKcNSz570az5DMjpusoROg==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:0nEK3/wiIYgtck559aAFKfBcsQjiq33mI7G98c/8tPWVK/VzTBzQrLp+Yf30Ji0IWz/vsqP7Gqun9gxyD+Vc/Q==,iv:PSeOEwji4brb/+MK8+wsquYZBTDf0jGVxo6SQSCPaY8=,tag:fqgef1q2WqK7IFE/1Kf5qA==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:2WJxJIvmmNWEz0+tNOS/8Ki7pQGAqQZVxo28tJKXgdNNDoFgRGaJYOjZsHiQU4VHck6o1gsepPLPNk3CjwOA1Q==,iv:iHvRHQMZbYYIt4bGjEDfS5vUfNcbJqBNuCyTUQykAHU=,tag:CRtYUxZhLrN7TTFRNO40ug==,type:str]
      - name: ENC[AES256_GCM,data:6brPZBg9JYL4eqAktOpC2wQ7NN+JCzcmPkHUJbQ5TQ==,iv:VMwOlw+KpE+66AFRg0UB/GTcpwsBABnq49t4erimiu4=,tag:A7VOMGQIx7C2fz9cTBnEpw==,type:str]
        type: ENC[AES256_GCM,data:6ME7gLPmjgdPSDzG9AQeWikAd4kLuOCXSYf1UF0WxQ==,iv:aiOIzylv1OmKYWKkO8slL/0Kf4KWVZYfjnIydUcnPiA=,tag:56EYWPM7zKTtId6oY9XIOA==,type:str]
        isDefault: ENC[AES256_GCM,data:a/m84EY=,iv:HbECg9V3jctbxHouZOxzxBsVErCnDnb4opsZ6+HuMck=,tag:GoCr4PROegKSbcQ2BM/aaQ==,type:bool]
        editable: ENC[AES256_GCM,data:cW8egA==,iv:OO7Nt/ghEy3Qlh9tbGBJKWB4CPp1IxnQqDxZzTZ33EA=,tag:aZzAbXFHtljZNTg6YbQFtg==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:m5AkzQ==,iv:O3msgfZZOANYFhIm9tAuLcT9CwPEu24T69zo/pxP88M=,tag:NsVbktLFCP1YSjfmAYFdJQ==,type:bool]
    username: ENC[AES256_GCM,data:eIEA7r6shyHxhNSu9E58+MQvaoNbOtwTKkRUdeNsKxO8exeaKneY5zdy8yXwJN83oeJkO6DJshAU6VeYIS4qBw==,iv:DS0cBWG6XImEEK3dBnHZxzJMk5EUziztNq0pe8B/eYQ=,tag:IGRUZozRdPsuZZe6/PSw/A==,type:str]
    password: ENC[AES256_GCM,data:aOcFP4ZzD3JOyt9oQ+G5HFrxL9SHSpzTFk3ZqSxXcovoqq+rZ4QsyK0B5rFbVwJ2wQCuA1cdFEKhpQMzCeIfWw==,iv:bxw6y+lX4Fi1hg9SsYiwDmog8+fo8coMQW2N6HhoqOk=,tag:oTLfDX/Wfpfigi0qJw3j8A==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:48Z'
    enc: CiUA4OM7eBr0iNwS9M+d/wMgmX3KLgHmM3usqkoXlyBO4zbxfeR+EkkAPHlbmSk9fnUURsjUeW0g7jvdGWZSx1VkNgcM9+x7iiFLsNAHiRzqMbPsm4GL1RFq9FinSEby5IfkiDBDttK+9l1rUrifNrwu
  lastmodified: '2026-05-01T14:40:48Z'
  mac: ENC[AES256_GCM,data:RKMFsFRUTw++M8xVFaZ8aOalKUzs6NiM7cBY/JVkP5sZwYFAxGk9nCXqZRZGTlWrA49hTyKURI0nhtd1H/9yLsPr84RS17DJk5T+J2WP9poHvofJ+pLVe2ZhfdHfVf+mjN5xYt3M0b6v9znCBUnAXzp/KpT4YxF1JdcOPQaOwfk=,iv:tzKQxLR41uwh64Fjf1+lx9AH5KSpjz6aKPb3LIXxQdc=,tag:EK0aX1vMukmgk04M+YOW/A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
