prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:CnmYMvnmWNP+RVkeJA==,iv:a+u2eT9Z2XKXyrXiJkXigkVTCLZR9ULn3+yYzqibr3c=,tag:qM4DNbde+NU3M6H98QbnCw==,type:str]
      value: ENC[AES256_GCM,data:PSy5vHZ+fbggrwnzA8A4oDSkYSznTQ/6WYbXt2rGXOkZVwZbJBYura8TZB9vQKdq7UoSh1MXIhhnMqmKn5eM10l93ZLVAHLAtDJAzFxcbOI0lxRklfB0F9iOvgzP1sv0a3lP9VDmakRr8STwFmq9EELfQ+tW6cUL9Yn7rTFimph+P6gtFw+gsxL7HS4meVmB/y7bH/5r7ZCPRiNkgMid03SVl1bn+ktNaAXIzqVbu4oMWg==,iv:Hv4pFWBQJLdI6zBlGAq2WKSYG95u+WEWieH4nl1Mlpo=,tag:5dPaPrpQu3NlNsjdNfYZpg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        HFSmHnxpjKCVdvLjqwD2EmZ4WZpKzb9lQ4bm1N6JArP9lx1zrLjeZx1EWl9QZM5S: ENC[AES256_GCM,data:FBsvroVGEY5UKLoi1S9QSXbxulgbq0Ka1Wr3pztolDfTMVs5wL3mKCYBkFYmIwfxoI7Ra5140PDo3D3l,iv:9rQxX9OfMelrgE0+BHEDTp6wvxzKsjF74zCy1thn4Sc=,tag:AVht7makpOIJUacaw2kXRA==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:BthQ+Q==,iv:KiJuqf038yzB6ydKKPnFnI46rgnJ2k6SzH69y5BK4u4=,tag:WJwZvJNiU1sF4VcIFjuPNQ==,type:bool]
    username: ENC[AES256_GCM,data:buxdDrnnkoUancP5wC4/YSATXryFd+Z8d2t4eGUPCiLCJng7yKueisvZQlrxCisSaOYhHfMdwPkaMo2btl/M/g==,iv:J0pPzFHQEQjMf7uB2EVPlN3ok184tSnZPms4czb+At0=,tag:6j4gSOOvs65neQ+CbbWk9w==,type:str]
    password: ENC[AES256_GCM,data:F/lyMozAnnusrZ/nLKAE1slRLjsTJZVYXQ0h+fnrp7Fxd59xIor8JxEVExGYZtXr8KYoixra6dxkiKod2HxIVQ==,iv:zYZHaw2ol65XMlwP1QB40peUO1XO02Oc80bunsI4Szg=,tag:xbYFkRUgRhQcG4F2VLCqFA==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:nh2BW8hyA3mIIEeyWoTW9Ee6SbbW0PKa8W6f3fDnSV55soREmzWSRyL5uX6w/3Zp/1ROOgfb9l+kMwbXKP3EIw==,iv:GFFJOmQebpuVu55QlxSMI9JO/azTV5D39Y8l7CS2X+M=,tag:VUneHjFCIctN8Fr4VAetjg==,type:str]
  password: ENC[AES256_GCM,data:htS29mLeb8kn5usNeeUuMhsfOz2QUvul9kSKgR1cskS+6kEvDnqaB7Y3wq43qPYY6+AxlMohATY/kysLIZvgrw==,iv:HxY93VB2ioP9wxpiS2vlok+ATtYnWD/+jBYwpVWEuug=,tag:pK/JsN9JNoFB4ajBDdONyw==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:22:06Z'
    enc: CiUA4OM7eIzGZMx529LW2+6b2AZYtj8UF86D1hAVsP1WA4kPab6nEkkAmy+ekkS/DO5TwhGzBFalpkc87CgVy4qmttfgYJSNiAzp9wkIOf+8q2HTb9VZZcpJUyK5N7IxkcUFqGJRw8zVGNwMdJGuj+7k
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:22:06Z'
  mac: ENC[AES256_GCM,data:wRdMcPNqr5PQeCvQuz1VhRf8fksXOepNdQidSYtBnjiOVVpQGjOSDjQcKnlBbItVCF7HjcrUKlKUuQoA+7CtxcHmCf4AgFi05pREO9+2XcZNRM0QGrW/10mrhe8GvmsaHHyPhYAuqL6PT4S1+l0bJVQhCPEQDAHnv22tGSSiEB0=,iv:YWlGOPSKYwH9ysTfihNWfSqaNz7ntRp8mFqX5HXuHpo=,tag:LiFgVw6YTQAEmsy2vKhSXw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
