prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:dBJ7ESEZ/IXAk/UEng==,iv:3cb5kLAzEj99BlcGgF1K03V9HiYBJARWjT/Iwm4T7jQ=,tag:R/L0pZwLVf9aG0fyM0tgDA==,type:str]
      value: ENC[AES256_GCM,data:efIEfNuSBqcmIiQO/UQJmpXkmDubUaaeUKQOP1nZLq91MmVK4mvrqxbpTIkySlIA3UvxhUBW4BzBdIv4qBdZdHKhAgK43wpkc6WmQqPK/PyHISVw45wKxgU5NfzI64CwG541MrzOQFIsC1AWlj74d7jQRZDh6byg5QCZ8XJPVaxOnX8rf4fJpGjsR2opD8ouGRV09+5E0AbKuxVKFnlADqK6WLaxrHn03jdxAYhJ6IIJxA==,iv:n4GcpvdFWIt0raDSC+7paQ8FDYm1nD47uVYNL1Lwd2E=,tag:cOgydnyeCw/iE99K99YavQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:gDXdjxkLr05EHcidTJrdXuOcHgSVqlzWEfaFuO7C3xkokprmx7FnjTbJgr56LNPndGnWNCgHlZF3T3b6kr4sEg==,iv:nYZTyPLcwT2XHmt4nNJQwX1OvEcd3KjOgPJuf9YPReI=,tag:EolbXPb3MpaFbVZ1xk1YNw==,type:str]
        password: ENC[AES256_GCM,data:2QrLh46OSxUWeNoirlps3Ahqkz/2XEC4K1INGenK3Ny9xDp9A8xREHQah1wTzBift/CQrJi4QWoJMKzRf/4x/w==,iv:fwY8nHCUKe2CXuH9IW32yJvpETTNP2V36kCmEFx95h4=,tag:PZrbsyI8nLwuWEUmgNELkw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        HFSmHnxpjKCVdvLjqwD2EmZ4WZpKzb9lQ4bm1N6JArP9lx1zrLjeZx1EWl9QZM5S: ENC[AES256_GCM,data:Er6QjAnDcOBiBWYuAB2mWryVAMdYRvOGuDWbJ+YXCixMLz1yWTe8lRidembTD8tW9wbINGYIK+cp7uXg,iv:ZWn8JWapOb+Kwem1KZzx7ffQDWbSYqgzcACiUv0UOik=,tag:b8fCRSBd4uGmHp5+Gv41qw==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:8A==,iv:HVoic+5RETd7e68Jp+N7VHxx/udQvbldiC2/ro2A+iM=,tag:1jP5M2QBczgUaAJMkEaHIw==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:aLtHmDjTMrJxaA==,iv:U4HqLms5aHTQHfRWBDlU2dcOmaoosLTVjcRH8bNnSZg=,tag:UH+XfG/tbs1JkVfR2U6SbQ==,type:str]
        orgId: ENC[AES256_GCM,data:0g==,iv:vPJgnTG64pkyX8tIARpJ79RCEtuqYIrE0quJx3nzHig=,tag:FIJ8PVI4aJD0vhkxgaVVfA==,type:int]
        type: ENC[AES256_GCM,data:cS4Y4e8Gzch08A==,iv://mubS2rp+h0CvVtdG+kmzpf6VycMj+Wlv0ugvBHuXE=,tag:Rg8DmrKvsGkKCeXpYc8VSw==,type:str]
        url: ENC[AES256_GCM,data:c0pyFQGh5dvH0yPJtBCxQKyJuCTUKRglkPy9IqUPNMA=,iv:X1+ykgOfDac2/G44d3Z+s+vP2cVc0czMRs+Ix47EFGU=,tag:fyft0keqmnHyNGNntEZyUw==,type:str]
        access: ENC[AES256_GCM,data:HLPIYXc=,iv:zQ7eQAXK7LXWsoxzQN8aEoXvsaReCXlXbqYUqmBnIwI=,tag:LbGxAgLwchT0FzAogkTUYA==,type:str]
        isDefault: ENC[AES256_GCM,data:gUGfbn0=,iv:DMslK2RQovFfLEn87bBL2EA4IKDgvFiAeBVzErSmDXA=,tag:UYX8v7RLWhfRW652J6q5Ww==,type:bool]
        editable: ENC[AES256_GCM,data:1RC2j04=,iv:gAX/4+DDmUzF3C5vQLt9c4nus7gG9q7GyqEyh6woHW0=,tag:yz5C0R8vyGuAZXbM+Pg47Q==,type:bool]
        basicAuth: ENC[AES256_GCM,data:AqWxzQ==,iv:uXinjlc0zX0SK90+lGxGWROVS2/CcUkC9IbFchOdkio=,tag:ok3gZFqpAlmEppIkom5LcA==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:zPJfWqvkcwrFBj4dYFBV+KqaLyHJ0FGHTWX99+vGFG1+b6h17E3TGesOOaFNpvkF3KxrH+HLFAfj/jGjaKo/QA==,iv:sLKp3/X0s8aBwhMcHNbSjjkHNEU/cpS2bsSTBSmrCdE=,tag:rxp5vnvO/aB8AQjggE84zA==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:+ly2ezsXJWkCInp2aPbu1WUTudndEIkXCtwQ90gVGEe25kWY7YyzGumek5poJhISGdp72qUhpq6UrR4WAWPryw==,iv:7AdJm+A4FC5kRT9tbPH7HHMCIk2EJI3a0chJ6gRRz0A=,tag:Hy4MTq3enNOGkpLSxW+jWg==,type:str]
      - name: ENC[AES256_GCM,data:kS4QF/TEyZcnC2oJKbG60D2zRK2Q0BPDifHqdaNlVw==,iv:E/8/Y7OqL7QwqBGn97M5IcJNe5+TUfA3kmbe3l/aqCY=,tag:6jeN+s01SwfJdsaFZ1SPug==,type:str]
        type: ENC[AES256_GCM,data:+uT4LovtFZ8excBeAmKKnJNpYLNGugNLBT3689GzdQ==,iv:H8nYPvBRrOL8M0fC+Sw8BKlZ31FSx+q6vbXWVLw/mS4=,tag:oUMwOcq+YS1TL9DlYyda3Q==,type:str]
        isDefault: ENC[AES256_GCM,data:6m08Pus=,iv:CPmIELp0BLElKiaY64F8rANLGYh3OApprufcHrjkEoc=,tag:4C8UkbhWqSG4MPIZW2BpYw==,type:bool]
        editable: ENC[AES256_GCM,data:uw3t1w==,iv:MTYDwKvIzocgdil0tqFhzhrjw5OZ0WD4SItctSjQRZY=,tag:Av6Ima2DPGXdhW3JqotiAQ==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:3odCMw==,iv:8gq95s6qpgSwZlBDwpzgEc9/rGjS7iTgJZIs8K3VZRc=,tag:97QvN7LNK61K3BfjMa78zA==,type:bool]
    username: ENC[AES256_GCM,data:kJY6xGlvzLPU8ve/DzR8uOiKdEkww6CbpnDePfu1dMT8zwVBL6BWcKwl0wMfzw9OSOIeHyNsZdOajM2JqVQWHQ==,iv:kC22tLGe8m+QKbL97pxdDfhbQhmoQBN5CW+kiDlP7Ow=,tag:BSOyLjS9nFLNEcg+MzluCw==,type:str]
    password: ENC[AES256_GCM,data:hwycEzGb4xTNZCzfPrxIJpGcoGJAMxdH3Hgc8m3Q617eSrtMh5ig9FWRUv/7kgfaLLjGAsPW+1EW2TB2pwCszA==,iv:iRZjRZ3SX7sJTIYSNxqXjkZHWC9RYZDtbV29RBa9/oM=,tag:o0Nvy064s0P8sBEpB3jd0A==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:Q7rGpo/cUX7qjDBxWybgYu27dl3PU/duv/+N+rYqa5kSnPgn264f1MDRdyO4oYo5j8eexFTG99jnLeVRmuH1ag==,iv:kNqYx1Un5/pLOBfgnR17wRdwoTgHoyCDoPRvbXfKbuA=,tag:u6P7ODXQGTUvr3xXGRa0+Q==,type:str]
  password: ENC[AES256_GCM,data:sWCs3OXDpk4xhfTLK6X/tkvSwJZxTo+WSob1kjMVR3gykwRRl/ucsu+JGY7hwA6hw2yPI0fMdg5O+ZZMYpRYxw==,iv:B1MnRkG6rf8puNCsHah38ZDfMPTpIkKGV9PKQ2WlCFI=,tag:+adbLPYCgY+FcI9CQo9oVQ==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:27Z'
    enc: CiUA4OM7eMflzIcyJcmRG1JlcHzEnv7INiivoGyqbXqHpi+5zCd8EkkAmy+ekv0LbSLxvqURUAzxqcnuS16d59Ms9T0BTQ6pe7++ChL+rvgoukoYxd3cthKOIJsE2A+c49BwWFUCTk0tqguWHloUklVZ
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:11:28Z'
  mac: ENC[AES256_GCM,data:WF2OjE+xQifrIuWh0FmDJ9aPh7PRP2+qi5Qs2IH5gXcZVMlZMABVo7Irp+GR7qRqKybdSWQG7b4Qpc2Z32qty2PQI+83/Vm2zxlRfW/nAd21y++sfp8Z5Y/AjctcSwqbwrEfByFMz9O6zI4Sk1300TSNk9Eo2NB+9M3VBhWFbd4=,iv:G5QEFF4wWiEk2BiqXFgyw0l07Eru6IuQzSB36iky/e4=,tag:MTjalaScPiDH7GhoBYu09w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
