prometheusIngressAuthSecret:
  enabled: true

cluster-autoscaler:
  enabled: true
  autoDiscovery:
    clusterName: opensci
  awsRegion: us-west-2

prometheus:
  server:
    ingress:
      enabled: true
      hosts:
      - prometheus.opensci.2i2c.cloud
      tls:
      - secretName: prometheus-tls
        hosts:
        - prometheus.opensci.2i2c.cloud
grafana:
  grafana.ini:
    server:
      root_url: https://grafana.opensci.2i2c.cloud/
  auth.github:
    enabled: true
    allowed_organizations: 2i2c-org
  ingress:
    hosts:
    - grafana.opensci.2i2c.cloud
    tls:
    - secretName: grafana-tls
      hosts:
      - grafana.opensci.2i2c.cloud

nginx-ingress:
  enabled: true
  controller:
    ingressClass:
      # Claim the `nginx` ingress class
      create: true

ingress-nginx:
  controller:
    # Turn off this controller
    replicaCount: 0
    # Let go of the `nginx` ingress class
    ingressClassResource:
      enabled: false

clusterEntrypoint:
  targetController: nginx-ingress

calico:
  enabled: true

# FIXME: remove this once eksctl is fixed
nvidiaDevicePlugin:
  aws:
    enabled: true
