prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:Ho6US4N797ZMqLFLPlA7UOHJmD7lqCNcrPvMMMOCFOTGKanWN/nVAtqo+vRsuc+TgniuAm6gqykaEqgFGqiUInZbQRakfZneT84Aogr06S/Az+4GLy2rAJWGh76UsCCsqxvKup9/qMYA/LhEBJfEmA1WEjispI3+gULt22zGFSJqzlwPss8A5m6gGF0zskkIXH2in2S5/2frt9Vo,iv:7ITBW+oDxFuY9OuVzy6aYNhvaSxUA5NNiuEsDg/zD1I=,tag:U7OaPe5AmM2nL/9Cl/VAaA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:yPpVeRVehVL0Zlh/6Rt1FQVJRjJ2xpzp6HWBW9SjSKqkzoqpsRWvLXRPuwz0zTT/0rTvo+TsvgpLZEa5/JB00A==,iv:sgcwfKGDx4NeGKd14DHkCDS4NwAls2RrdstXjKO2LNM=,tag:1ydIG2qlxvNNDzNfDqp87g==,type:str]
    password: ENC[AES256_GCM,data:71H8aK6nWBty88oWvQFAaGJRuVXTkfDTFyf8Wtmg7iXqGtR4E2wCr2+Y7XnwAPraDm5ql3vxT58hsWW9J0MHTw==,iv:LyKgthCnmopZEWBA1F765qfNdn9eI7pwmidr2EbSAoU=,tag:hcqib17F9qBpyYygHvu8Ag==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:2A==,iv:muodd6fEGny0vEGbgNjqLvQaZgQnx/BBk2fz/kFfOuU=,tag:D6+lbXZvleIjmahRYeDILw==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:DeJfvJqOcCnhjw==,iv:yiTue0XwIQZULVVUFBbZxFz89qpvlDNjgXiUBH9H2qE=,tag:weNAOVAjfRLnBg3rl19AGA==,type:str]
        orgId: ENC[AES256_GCM,data:WQ==,iv:UVEbYehEWi70M467WpbW7s3DoFl04wvh4xr1EaZggFk=,tag:PaZ8JVKYrDiBFGEbELgQIw==,type:int]
        type: ENC[AES256_GCM,data:DqsVMHZiQqUyfA==,iv:XSM+gBruBhdDrAB87QX/2rRl71FnL+eUSPW/ageu9kc=,tag:Xq2yWgjMqFcNv6TDmCDGfA==,type:str]
        url: ENC[AES256_GCM,data:/SfLy+zlkQJoxk0LlasTCo1ESPdF7fuwoFE1txh1bpA=,iv:Z02JJVbBFz3WuoJrlvZLdC1qG+TpNDqYoiBtRj1oCWg=,tag:E51hxAAizFZNm9qzT3nvfQ==,type:str]
        access: ENC[AES256_GCM,data:G+Lba00=,iv:0xoffRT1f5WJWBfiguCBhV32NKaPZrMws7/x5HayYt4=,tag:8litKYbvl4zu+daz2WJG4g==,type:str]
        isDefault: ENC[AES256_GCM,data:Jdd/JuA=,iv:/1QtY0D5hIfqkTdkv2D3VJ4NNL89RuVCwlDYSauVuR0=,tag:DUtKVKJl4NqhlDbVstQCsA==,type:bool]
        editable: ENC[AES256_GCM,data:kntnXIk=,iv:6N18j+WfEs2KCNyVhpx8AkcP8jPz0CQLyQGOKwA/TIM=,tag:7ddI6zlBsQnJhLXK3ecLnA==,type:bool]
        basicAuth: ENC[AES256_GCM,data:ZbX8Zw==,iv:q3c1ZG4N9qsfKK1aW5gRx04XMDfGWZmf+hyXgLU4890=,tag:/q0nEPGNh68s6FScK8JWew==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:qWL7Ozk1UMzouosd6pHkjstjIv0LYqaBmv01f1T9qvFQLSuolH6geiM1NX3z0H18seLbVt+17eO//MtlEEFEJA==,iv:h5UrNvPsOYyMpRgesGi5qO7LEO4GE4Hd+aNNz6WZCmI=,tag:B1GATSYbwb6vAHwaBP5uHw==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:e4BkgPm+avgXuj9Vi1HUZyYRNjXjnpdxxGEJwALhQj8vICI9E+K+0yNYFzNvdTyyPCSBwslgC1eMDW5wj6aHzw==,iv:rnwdt2+5vP2HRGCzCM8D4KURPjS0E/mcsbGzBqrKc9Q=,tag:saZ2rfcbcDN6fYl+iAlj+A==,type:str]
      - name: ENC[AES256_GCM,data:i69UNwnWomKfaTlZe7ERWfb5hf8375eLSZeCAJ6LbA==,iv:15I3bpjbw899Uc3+MmcMTe4K/xAwsjoqpOpdyf2/IEw=,tag:9ULFX2bJl17IHJZcQD9Ntg==,type:str]
        type: ENC[AES256_GCM,data:URSWNbbSjLbfGLo8Fy6QbYBq+898t5z+6j67/BpsPg==,iv:uFyE0Ty1XA7Z5SBuBC0t8CPW/pLn6ARUxFS7vDm41TE=,tag:L21W4W0VuU0uZprrPkq3cw==,type:str]
        isDefault: ENC[AES256_GCM,data:QJK2Dk4=,iv:dk1m7bFRUiCVt6PaE+6A02bMgXD6bFDsOwuBfc097Zw=,tag:A+WfgHcMKqH2Sn4eD3r4EA==,type:bool]
        editable: ENC[AES256_GCM,data:YKCr8A==,iv:YyC+1gHUfOaVPwAUDYEY12hsbiMJyCFYrDAdU5cvdbA=,tag:7JrUdw4L6KdfqtWpcdMrtg==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:FDlJbD25LTZCmHC1BA==,iv:N52hS6oDcLohLmBKM2qm5+2xBM9MOd7gQ5KYGj4jhK4=,tag:X3QYQDCHbGUqcFd9Au2tKg==,type:str]
      value: ENC[AES256_GCM,data:Ru76OHXVZ/5+QJfZ+ji9K61/eLd3Vcl16nqxFvWP/88+z+9TzHaVyyivNVmPfSkNixsi9EUykAoG2XBOKj0IgFyxM4+sXZDkqs6llDtFJFWYzUcA1xPM8Kss96HtLGZIaK8gP40IMpRafvBLPDLOEJbxWPkGQlgbAO79vy41julBVzIl8K/qRey9+rpKBJjtvQD3jV9dP4Z2KvlK5N40cB8g4zT3v4UCIdG5ZF4cN/k5mg==,iv:E+PXqFTq7GXMcW5ZbrD8ZkHE39hqvPQYpNrfnSQWEUs=,tag:c8f5Jk7oVBQ9dmuJptII8w==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:ft6wMvBvKFNRMQOH5JB+vxvYjK9AfmCrTOOn4p6ygn0ydlWYLxIAKKAQ+L6eef5fAuJnzlMbgDF4cXhlHS6wrw==,iv:mB3EVKUuLCXMN0kKlL5ocE/BM0In1ogsDRmxrw9I5uw=,tag:i0pdkwjrJVHSNiPQNhFh0Q==,type:str]
        password: ENC[AES256_GCM,data:IuS2TqBB+p7f84MPs8BJkCCXRE3fkMVuaVnC1+tgoedNyurKgSZdyxfN61VkUjWUAqsG8LcUaBQrqzGGO1tdjg==,iv:GvNp6lOFwxHJiRwmiAwlVaCJSHPNWOIgRnnIwOp8m8o=,tag:9h8l6XmqfcaaM3QmOFLYrw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        f1ODYMS2Ep9Jt9vlJjao5BnkX02rlTsW4JfQ1h14gFTLZbuESOuPOW5Qbo0N0KyU: ENC[AES256_GCM,data:BfsJfHTX5yJ8N/CMdt1C7duYUNgM0GIFp6yIvJFkHKT2VKd+nck9Mu8ycUGaEl/6+y/cY5K59+jDmRq8,iv:HMA8Y9WyVVNKY9AjLxetRX1Rop1OnugQR9xkgrA+g6c=,tag:4MtR4s/10gdoSCSTIYb7GQ==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:wjcq0w==,iv:ZgKZx/xo+iSzM/PycuIf0IrKVu55tqryeofgl5WkKUY=,tag:IPu3LHH2dRfXYC2My60MBA==,type:bool]
    username: ENC[AES256_GCM,data:7saU9AJ6z+5osuz3nGMv1dHJKO2pxgl5iHN7qVlL1ghf3lLb0/2lvI5/RrBSEqQsckn35VK5Zm78paWNqLV5Jg==,iv:AFS4+d/WnRePldD80KfiH9scMRV0LjxVhZGdKHkxtPo=,tag:aK13v2VqhftTPINeDANz7w==,type:str]
    password: ENC[AES256_GCM,data:tVkxk2dRGjac1qq8uLKWzK++yBcT963vj71URm7511NjeJazqaOUYJHKfgRu17vG92cM4R2RtlKOJ4eoSP1dTg==,iv:URU0O5m1/vujT2YbQ0sgKvTSjLFpQQYbtexb5IZKpqk=,tag:Z2/wI+9yVZUgan43hZVgQA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:51Z'
    enc: CiUA4OM7eGBVaigaNY4WcJ3nohiSXIYL22Gm3dAD7THgDNfBgxTrEkkAPHlbmQWVqVf9BIxR/ErctHtLejWx90JgsuLUXl5bbOrvECwuAkPBE3MAO+caVaG9aX8FEYptTluT7k8HmtFAMeO//OpwukJw
  lastmodified: '2026-05-01T14:40:52Z'
  mac: ENC[AES256_GCM,data:tOhvI9qK9HAYPyll/VcceYYPjbelUJZaceccuwd6mvgwzSSyCdTS3QPrGQ2rFSGRcNOu+O/C/QOqhK0G6f6KdR8P30kRW6lVUz9ruoMEiDDAYB2cy5FUPes9/I3WRUBnwvribkuEWAidHTE4f1FzhQc/sHHCleGg9IAJesdgr5c=,iv:AfsewJYjMaL6xMnvpGABiaAqAuZlnN226dZK/M/umgY=,tag:Ld+BwL8pMdolJdaoSaHdWA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
