grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:yQ==,iv:+4PPs5bhKr/Ujw6UDbrBLqAAqPi+8VVLQhMUBGASkLw=,tag:JfiMQymUZ26BslYCK0bIFw==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:M/k332UW8e/GzA==,iv:/b0p3ZH8l4YYvH1FImptSUB62vLG0CgMnko5ZV/s3bM=,tag:vAE8Ht5xBpQSc63BMX+ubQ==,type:str]
        orgId: ENC[AES256_GCM,data:jA==,iv:QHuV7Z9vXsChZ/r6ahfN9ba43YaZTAD1tcG1eUKmEV8=,tag:wv+OH3TbfIbDUlq8gJIJRw==,type:int]
        type: ENC[AES256_GCM,data:hrrCey4k1lcf+g==,iv:3xRqCcOn6EcqubknO31karoGdX2mW+JwbCU/jaaxce4=,tag:dyLJrR4e+By935g+7PxyZA==,type:str]
        url: ENC[AES256_GCM,data:4fWd+7wog0XuTLOwG/doSYhEDNBcxxYGQbjIoGciWG4=,iv:HfEUmJ4FU0zw8a+0FOtIv2H/l4NzYx+uvcHEtsjIqNQ=,tag:K2EhpnuylNSSPSEX9rpk9w==,type:str]
        access: ENC[AES256_GCM,data:UjP2Duo=,iv:zxM2/+lL7Hr2cfzp3xh5mCM27YR4lGSQih2cbvYR6GI=,tag:YHJD/P8u0x41I+hC1iSH6A==,type:str]
        isDefault: ENC[AES256_GCM,data:IpTugkA=,iv:FsKcSPjickx/5hqIh/5CToiuz0M414Kh1AgJ/E6Fc0g=,tag:wkIpVE5UjFFFUqwCL7Jrgw==,type:bool]
        editable: ENC[AES256_GCM,data:ONGeUF8=,iv:ILOavIZmqblBLLfL4I2SRi20pg2i1RCcQK6W8J4nLJg=,tag:4cDTsRNH83fLhO+KX7dlDQ==,type:bool]
        basicAuth: ENC[AES256_GCM,data:Al2jag==,iv:3QKNX6jc2AwyQ2BmWniORLoirjsblLxe7H39697+0yU=,tag:f5IK2TT92+OC2BwkrNoM1A==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:l0jopLvn4/NKP+MWuVOEf7v1iRalce7dU5bbyzXofkeiI6WNKtqrTFxHfZpRL6hgnRpHdLYzbhB1LRM+HZWnCg==,iv:qWGT38aUG6E0VYqzkcf40qJPbhaDjXzWJ8CNUXNIVoM=,tag:qG+OfgS5DUv4xChflFIYhg==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:qVNGt5G23oA6SjkDIWNBF9AuHsx6kSDuyae/ifTp0GVW4vbxNFUNUGdWf+0OQYQZ/tVfa0NZ7V0SQZ3tMOUgVA==,iv:ReU0esVwuC0AEgLPMFev32Y3qtMrS2+yOBSjejnhmA0=,tag:eUztnWKe2bT0MO6vhyPMIg==,type:str]
      - name: ENC[AES256_GCM,data:G2JnwnyWp9wtNCKI8vPTgAMeO4IXo1lqb0mNOdRSBQ==,iv:EXTC6SSSd5M5iXM20neIjGnkaoneWWQUK0EbM5dYi2o=,tag:yCoZkFOywTvtk2kyRCim8A==,type:str]
        type: ENC[AES256_GCM,data:IWN8K5mPdoByuOJRjUqqIgVgn9yZcJVcJlpgAMhI7g==,iv:lV6UJYyn6jNRMX5Ml7waLtmOT4bS9oL6plohwtH3fSc=,tag:Zo6tj1BHHpwyZjSk8sFRHQ==,type:str]
        isDefault: ENC[AES256_GCM,data:enF0IfM=,iv:ko3EgZ3WMriGk9OY9VmjTBxV7OWybA5sHQzZpjo81vs=,tag:FNXBU9oM1wA8SLKVLRKv2A==,type:bool]
        editable: ENC[AES256_GCM,data:eOfT+g==,iv:pBXUs/RKEFutolergVC+ERmNrT3A7cd2jdvJRnb7t94=,tag:UhY/1DffXfOP3L2hak3hgg==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:jXPhA5RE7ZcHLCEDcg==,iv:06AdrAuUJiocX0PMo33AMUffAF2SfYb5mDibheXOmzM=,tag:6oh585xlQ4dUQxSxChoaEA==,type:str]
      value: ENC[AES256_GCM,data:gYNddIu7ALRFfyQvBal1aybYFCTfvCG8QtarOJZRh94dO3llLfpmdN7TXHF9SDqoF/bijLooRYVkYRY0znjNQumHKpT/FY/ay/ZyZxfwzBablBm2h4gnRJU4VkIGPnNW8NkWp3li3q1gTq/FK56zhhEcoeiJ/jZFWDrU6zVXIDFperdaukPrBE1OwWYEMZJ7QdbJNjd7SfqpogUksprWpGyb/jziShxVsCAdj5jj69Q7Ig==,iv:Brma3eOPN5yHwPFM9EquMNt3fTsEVFOeLpH7n2t+jNE=,tag:WfSm1X/RN0mA0uoD90Cbiw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:xxgzwj/VEh295q7z7ss/J8is4sHc/javiukSTbbBgYU42wFw0IZFsIyRmY+9q35K05fjepSOPHNC2BT9y+M17Q==,iv:f2V4XuSPVrwat4tb6YyCL3KWqOk7+CBXn0KN8qXIPFw=,tag:SGV+ZrwlvIt8t6MrGFdYCQ==,type:str]
        password: ENC[AES256_GCM,data:oGDyHecCSaCvp7yCCUehnGTqQx6YCuQDm+Lkj9tTUlfsr3DxVlNxAsvbuFunxC0Wn0f2drU0sIY6lQUwfvNx1A==,iv:/BGdwJeyPo9R9g6IXmEdS8QLrhe8/E2DSsUnVaGst0M=,tag:xeUDbElVDSWvYKkJXAHkLg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        f1ODYMS2Ep9Jt9vlJjao5BnkX02rlTsW4JfQ1h14gFTLZbuESOuPOW5Qbo0N0KyU: ENC[AES256_GCM,data:R2yThNo77e6FTEiEeGCG+FMKNzTVmT9dNzlz4pi8mXxPVa4KCAKinP42nWJ4cKABp81sQxw3tWS+Wmvd,iv:jq9SWaeUO1juviphnmqSSD4bGqCPVSB8M3EvuYmwpGs=,tag:EURbxJGrQNqBV0RuuiErGA==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:1NVzqg==,iv:dwLMSipLNRteqLcUE0/fJAZwTxNgYgpprSVakQvQtMw=,tag:JG3YoZJG98ZlLPAi4iz2Nw==,type:bool]
    username: ENC[AES256_GCM,data:unhjAyT6J2y5QLqnhBQ59idWb6DLY4e0ltcHLD2MtzHHfuwuMivuRvgYnG7IbWhkia/tN7PWSjvkJStSDzxZfQ==,iv:bs6bOJxdQrkdI3VcGooGxgn6aIrKcZ5Yo1R7JaUjwEQ=,tag:M1ueeVMmlbSrL7lUVeb6Vg==,type:str]
    password: ENC[AES256_GCM,data:9mUZLy4A0hIoJiLllh/RrNM7ByUAZbYn2ruRZrjODvu1CgbbLzZYrriuRiD2r4t1NkOsc3j1V0zooGHntjJEqQ==,iv:TTqtFXOPyTkXVE2Hvb3S1RwpR31ew0lxmXLt50K40o4=,tag:6TiKOFtD1Rj7SnbfPKMTiA==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:kIjENpyv00U9rLqh7s9NfDl61cTahBcHaq5Wep5EI6c4lvoPjM67eCrkbKs0W87VA61CyA4ptL8iQY3oYNrKtA==,iv:kAPdR0eskX+mblOHk7WS/kd1MntwuqC6mvKvrDvwcZE=,tag:pPtJL20LvD+zvBP+KVzv+g==,type:str]
  password: ENC[AES256_GCM,data:X6dtcWCPEBnFkqnimvaeQfqcn3ktvxOJHxz2JiF4O+7f6rHwQaMcMUFyWq2kFWe08fnubhkjWcCkKjKm6dR3CQ==,iv:fB5s1sR40DuNY4C1nUoT4g1OzpRwC+NeFq+re42ieXI=,tag:jOQxg5gScUemhjk9MTNiuA==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:32Z'
    enc: CiUA4OM7eNnfIHJTMfOaJ5HM88KJ9kQwsm1MdsXefo3GLICDwC4wEkgAmy+ekoR4e+uFatIfYOHPclhKfk/0Dqf8I8tUMoW2u/Tw0wg/fKRHFvg5FNbR2EEQJNCXbGWmK2WbS2BANXvqrg82/h4nhc4=
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:11:33Z'
  mac: ENC[AES256_GCM,data:Wdm2oZo9jQIIMauCkYqtU+DVYBpv/PXk2COvRGfAk/SvEaUnZ924cVgv4QUKHt2XHYk+ZhXcHP3cR1lfzSZEUzOxWHeSp5lhHc/myApuiCaU7TorM7Kld36z8nI2nlM1/aLt8tloRxfrB7LefiENYUyjqANt/oreHU7cab1Ub/s=,iv:9QuHaGK0nGkXO2uG09V+55k7FDxNXXY7UODdYNxgUu4=,tag:qYtxZ0qgoelxhL+RAbIang==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
