jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:XyslfuEKcMbgFP/LpXuw2kKv2cU=,iv:JjNVgaa4ZvkXSHY4AfAbbrGZ3Zc5NA2HdNxC3BEMJcw=,tag:VDf4Cj2sO5edk2GZU+k7EQ==,type:str]
        client_secret: ENC[AES256_GCM,data:sbofonFyrJYs5bhvOCk1xGosuDG72LbYUt1AIPqTl1Utlt9GY/DziQ==,iv:8BxM3Bd/3Z2OsczdKWrca8m+sLYD83hLsNy+ZMCFmNM=,tag:MRkA1N4cpDL/RHeBlditCw==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:zZ2LdSU+7ya2aAdcaepcLVzJ0KOEwnpoVe9FzEvji5EEub2lQ14fcrWAjHZTs9wrcgeeLjkzoqKmg50pfd/WhS43N5xe2fU+FXvhMn+Yhsy2CzNdxEA=,iv:eF8et7iMvbOZOTzoKwChWxfHBGykE3q8NN4gsP3Ko/Y=,tag:3sfOVxirJcRJYiq5Ite2ag==,type:str]
        stringData: ENC[AES256_GCM,data:4khQRJHLgcJ+fodG49oMuZXCdaPzabAaF6MYW41vUWrEtYuVxUkz4piM9C3jvbLsHsb7AGfS8RE1sRD7Mj+zYgUyTSE1x4QUfy0N1GSD8vTnYarebjmTWKyc2Asj/4B0weBxoWEcKu8gr5Y2fa2qKHd6SFoGxxhPKBMPJQIgQJeKZ2uRQl8ZdCoO+yrrT/T2/A6skm/RFkjPIu8yhM25CG6JUaA5C3AuA0RRs0Pae+uveycUtNVbqKSHapKeW6hX6yTqHD1rVkEYxO6w0/h1LKlNTymT/4ONwVxd6TL9W3Sp7qHxjnxtnMgJp1gG9VJXZ6nqi+vtswLVeul/IS8DNhOKAcbsuuCHisi5f9oZsMH42dPqFJJSgfuq6aT0WmqCgaF/cR6HMQqR3a8QgRNMhi0l14WLGtNTSy55HewPntI7UlibNW6Hc10RkChkxVR7ZwgoCTBf3x+ABQpu256kwGcj6Cvk1w4IIGgB2PLaHiE3DUuw/FeiuMrBSMjiPWPb2ztPDNMEp5rUJ69dHPm9m/RVVnRJ43iuZQRKKOduiplPxcQbCCKoRGUWfAImI6DWz1PKaah6TxOzx+YdddR/g/LY4nFZ83SVHVb5rIS4tg7gwEQg/ZCFrgKuKGMLG6pKw+re6QCT0TtNdBpTkQ==,iv:uD7B3cOQQyC/w3PQ/PiB9O3Ak4lyx5oK4+9FyBk7oUo=,tag:zowUqifX6vW6je068SuUQw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:17:08Z'
    enc: CiUA4OM7eJVE0AkwiCS7sVSfzCbUsj5j1n277XQfi39sNKCrCdFiEkkAmy+ekmNnL5bzsDucBYXzxWmXf4wfW4fh5Cz+0scA1GXR6fNKMoFVlu2SPrQk/OpoQdcCxVwla+ecc/h3h4yLPQtEOXLE9twG
  lastmodified: '2026-07-29T19:17:09Z'
  mac: ENC[AES256_GCM,data:uKid+K/EpefbyLVWmLI0hBSKj9JqmR3NgYyJc/0+/yoCMdNDbAW1HfZoUaRFJaV1lUCdPgJf1QMtsZUtnEGELLMY+Yw7UzuWTm69AOjv/P1bEfRDh1gAF0KpjY4LMPFT/cGSvAfs8+8R+eEli7F/+VFnEJyoNUPLKoIs5Tu4eJE=,iv:xBpuoVdLWDIak7EuiX+mRVKKzkavU74kSPgUDAMk0W0=,tag:7aqL7z6t9g+eHoyXDuZGKg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
