jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:qxcD4hyEAPjN9RiyvLH71bAN+AIOUD+CxICocOLi+5HZIMUWna33lIQt6xXPUynrpyBOqugsAYZCRt3ajUc+Zcg=,iv:f8TFyKP4PY89nL/QWxkRz5LVMSddZUflQvAJkWoUuSg=,tag:PH6gbZb3BuHYW3MhBwW9Lw==,type:str]
jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:SR9+MCjHTDkZDxwW/MGiUg1NycI=,iv:OuI0UyBv6L/jI7ORBrMF4K3jR42ufRn3FmhEhwlyOwM=,tag:WYC4un5gyqTbKLHgRge+kA==,type:str]
        client_secret: ENC[AES256_GCM,data:u3s1Z3f3nV79+rjkzN7Fg3Qmam9oYbmwaiEFyTT9iEHtQLdQYx06jQ==,iv:bG6hklPwTlrhK3cC8P5PjWHlHg4/t9tlqRNZ06NL/oE=,tag:kaxudSw9U0tIEoGxegfFKQ==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-10-08T12:42:42Z'
    enc: CiUA4OM7eJWOTLPA1oEjvgKn1NIZ2AfP3ol3mGHqS91nhiitib+QEkkAsHDEl0+GkOX7dkne6ff/KPirBDonFv4iu+Og9plYjX+/+RGKmigJu5ZElE6B1yiZQqxuOXYqvUrck/PRl4qtNXDEEJMuywi+
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-10-08T12:42:42Z'
  mac: ENC[AES256_GCM,data:ZhhfKh9lgytUIEiuWS3cJVqooVjR/yWZ7WHAEdNg51oDtLxZtHaTlmsv0xMnTl178AwLbsHOp4dBeE4r6l0YrGSCvbXd6aA+PX/EiE2ngtit3imBtmnZjs4yme7ZAevccUZheMn4YIJUgzEcVQxtQlc1stLVe4Y4wrEW+v1szwA=,iv:wW7EKacZJ1t5V8g7A1KohKQV+OaJ1abOlX36p8zy9jU=,tag:yhdH+AfU0A6qD6+X0XACCg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
