jupyterhub:
  hub:
    config:
      SharedPasswordAuthenticator:
        user_password: ENC[AES256_GCM,data:/mKfDzGnUHuSB/MqS3Ph,iv:RbyFsF4CVgLuAlsATlrPP/4vpP0OlpwlU4j/eyN0CvE=,tag:IrRD8s6flLQnpyrovxjRoQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2025-04-11T09:58:17Z'
    enc: CiUA4OM7eFlVc72nV+TuQ5lymnGxKd59TY5jUXNmbdvNP6F1cP3sEkkAWOWv8N3LmcXJNED84UAFnxpcUKcNe7/39QWFmn/Rn7GrFgzKyMVV/MR6g2jBm2jpCu8lu5tm5sh+TGOdxkUNzOhHnKuAr7C7
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-04-27T20:30:52Z'
  mac: ENC[AES256_GCM,data:VMZZMlzoLbk+RPpE8PnlxJ4SzibFxWhLLq2E8wihvQ9CXt0SLsrOoiFVpVGPoFOdDOIOuI4hdK3MyQoaJUN4erPWUBAzs1KK5cF5mXYrtALwK136m53VRIX/U3HrAbpFfHXR+vqNCQTdLOxKYjFLHXHaXzjPzTZErxio4MEnmq4=,iv:Aogkz9pwRsLgvvbRHCfsGZWTj1XeGxQ/NNuMLOpJeHM=,tag:Vp+k8vxuOLwc3lo1gXhbKg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
