{{- if .Values.scratchDisk.enabled }}
apiVersion: storage.k8s.io/v1
kind: VolumeAttributesClass
metadata:
  name: scratch-disk
driverName: {{ .Values.scratchDisk.driverName }}
parameters:
  {{ .Values.scratchDisk.parameters | toYaml | nindent 2}}
{{- end}}