name: Comment GitHub Actions link on a merged PR

on:
  push:
    branches:
    - main
    paths:
      #################### Copied from deploy-hubs workflow ###############
      # Include changes to the deployer script's folder
    - src/**
    - helm-charts/**
    - config/clusters/**
      # Checking that a hub is online should not trigger a deployment
    - '!src/deployer/health_check_tests/**'
      # We can ignore dev commands
    - '!src/deployer/dev/commands/**'
       # Exclude the template configuration files
    - '!config/clusters/templates/**'
       ########### Additional includes ##########
    - .github/actions/setup-deploy/**
    - .github/workflows/comment-test-link-merged-pr.yaml
      #####################################################################

jobs:
  comment-actions-links:
    runs-on: ubuntu-latest
    permissions:
      # Grant GITHUB_TOKEN permissions to read a list of workflows for the repo
      # and to comment on Pull Requests
      actions: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v7

    - name: Provide comment to track deployment progress
      uses: ./.github/actions/monitor-deployment-notice
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
