name: PD triggered health-check
on:
  repository_dispatch:
    types: [health-check]
    outputs:

jobs:
  run-health-check:
    runs-on: ubuntu-latest
    steps:
    - name: Get the incident details
      id: details
      shell: python
      env:
        TITLE: ${{ github.event.client_payload.title }}
      run: |
        import os

        # example title: "At least two servers failed to start in the last 30m 2i2c staging 3 (aws immediate action needed)"
        title = os.getenv("TITLE")
        cluster = title.split()[-7]
        hub = title.split()[-6]
        failures = title.split()[-5]
        provider = title.split()[-4][1:]

        output_file = os.getenv("GITHUB_OUTPUT")
        print(cluster, hub, provider, failures)

        with open(output_file, "a") as f:
          f.write(f"cluster={cluster}\n")
          f.write(f"hub={hub}\n")
          f.write(f"failures={failures}\n")
          f.write(f"provider={provider}")
    - uses: actions/checkout@v6
      with:
        submodules: true
    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Save pip's install cache on job completion
      uses: actions/cache@v5
      with:
        path: ~/.cache/pip
        key: ${{ github.run_id }}

    - name: Install deployer script's Python dependencies
      run: |
        pip install --editable .
        go install github.com/google/go-jsonnet/cmd/jsonnet@v0.20.0

    - name: Setup deploy for ${{ steps.details.outputs.cluster }} cluster
      uses: ./.github/actions/setup-deploy
      with:
        provider: ${{ steps.details.outputs.provider }}
        GCP_KMS_DECRYPTOR_KEY: ${{ secrets.GCP_KMS_DECRYPTOR_KEY }}

    - name: Run health check against ${{ steps.details.outputs.cluster }} ${{ steps.details.outputs.hub }}
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: |
          deployer run-hub-health-check ${{ steps.details.outputs.cluster }} ${{ steps.details.outputs.hub }}
