name: PD triggered health-check
on:
  repository_dispatch:
    types: [health-check]
    outputs:

jobs:
  run-health-check:
    runs-on: ubuntu-latest
    steps:
    - name: Get the incident details
      id: details
      shell: python
      env:
        TITLE: ${{ github.event.client_payload.title }}
      run: |
        import os

        # example title: "[FIRING:1] At least two servers failed to start in the last 30m cluster=2i2c-aws-us hub=staging (provider=aws immediate action needed)"
        title_splits = os.getenv("TITLE").split()
        cluster = next(x for x in title_splits if "cluster=" in x)
        hub = next(x for x in title_splits if "hub=" in x)
        provider = next(x for x in title_splits if "provider=" in x)[1:]

        output_file = os.getenv("GITHUB_OUTPUT")
        print(cluster, hub, provider)

        with open(output_file, "a") as f:
          f.write(f"{cluster}\n")
          f.write(f"{hub}\n")
          f.write(f"{provider}")
    - uses: actions/checkout@v6
      with:
        submodules: true
    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Save pip's install cache on job completion
      uses: actions/cache@v5
      with:
        path: ~/.cache/pip
        key: ${{ github.run_id }}

    - name: Install deployer script's Python dependencies
      run: |
        pip install --editable .
        go install github.com/google/go-jsonnet/cmd/jsonnet@v0.20.0

    - name: Setup deploy for ${{ steps.details.outputs.cluster }} cluster
      uses: ./.github/actions/setup-deploy
      with:
        provider: ${{ steps.details.outputs.provider }}
        GCP_KMS_DECRYPTOR_KEY: ${{ secrets.GCP_KMS_DECRYPTOR_KEY }}

    - name: Run health check against ${{ steps.details.outputs.cluster }} ${{ steps.details.outputs.hub }}
      uses: nick-fields/retry@v3
      continue-on-error: true
      id: health-check
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: |
          deployer run-hub-health-check ${{ steps.details.outputs.cluster }} ${{ steps.details.outputs.hub }}

    - name: Leave a note to the incident
      env:
        ID: ${{ github.event.client_payload.id }}
        PD_TOKEN: ${{ secrets.PD_TOKEN }}
      run: |
        echo $status
        curl --request POST \
          --url https://api.pagerduty.com/incidents/$ID/notes \
          --header "Accept: application/json" \
          --header "Authorization: Token token=$PD_TOKEN" \
          --header "Content-Type: application/json" \
          --header "From: " \
          --data '{
          "note": {
            "content": "The health checks status was: ${{ job.status }}"
          }
        }'

    - name: Resolve the incident if successful run
      if: steps.health_check.outcome == "success"
      env:
        ID: ${{ github.event.client_payload.id }}
        PD_TOKEN: ${{ secrets.PD_TOKEN }}
      run: |
        curl --request PUT \
          --url https://api.pagerduty.com/incidents/$ID \
          --header "Accept: application/json" \
          --header "Authorization: Token token=$PD_TOKEN" \
          --header "Content-Type: application/json" \
          --header "From: " \
          --data '{
          "incident": {
            "type": "incident_reference",
            "status": "resolved"
          }
        }'
