name: 'Recurrent Debt: Incident Resolution Review'
on:
  workflow_dispatch:
  schedule:
  - cron: 0 4 * * 1

jobs:
  compute-week:
    uses: ./.github/workflows/is-this-sprint-week.yaml

  create-issue:
    if: ${{ needs.compute-week.outputs.valid_week == 'True' }}
    needs: compute-week
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: actions/checkout@v6
    - name: Get Deadline
      id: get_deadline
      run: |
        echo "deadline=$(date -d '+14 days' +'%B %d')" >> $GITHUB_ENV
        echo "deadline_as_iso_date=$(date -d '+14 days' +"%Y-%m-%d")" >> $GITHUB_ENV
    - name: Setup recurrent issue for incident reporting
      uses: ./.github/actions/setup-recurrent-issues
      with:
        title: Debt - review past outage resolution and actions
        assignee: yuvipanda,agoose77,GeorgianaElena
        body: |
          ### Context

          Each sprint, the Team Lead is scheduled to review the resolution and action items of the outages that have happened **between September 1st 2025 and February 10th 2026** until we have paid out all debt.

          ### What we need to do
          - [ ] review the resolution and the action items of a PD postmortem marked as ["Reviewed" in PD postmortems](https://2i2c-org.pagerduty.com/postmortems)
          - [ ] let the team know either in this issue, or the #post-outage-actions Slack channel and ask any clarifying questions

          ### Definition of Done
          - [ ] @yuvipanda has provided feedback to at least one PD postmortem that was in `Reviewed` state
          - [ ] @georgianaelena or @agoose77 has addressed feedback and published the report reviewed by Yuvi

        fields: Status,Estimate,End date
        GH_TOKEN: ${{ secrets.PROJECT_BOARD_PAT_TOKEN }}
        values: Up Next,2,${{ env.deadline_as_iso_date }}
