# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
name: Test docs

on:
  pull_request:
    paths:
    - docs/**
    - '**/test-docs.yaml'
  push:
    paths:
    - docs/**
    - '**/test-docs.yaml'
    branches-ignore:
    - dependabot/**
    - pre-commit-ci-update-config
  workflow_dispatch:

jobs:
  test-docs:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v7
      with:
        python-version: '3.13'
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
      with:
        node-version: 24

    - name: Install deps
      run: pip install deployer -r docs/requirements.txt

    - name: Generate hub tables
      run: python -m helper_programs.hub_info_table
      working-directory: docs

      # linkcheck is done separately from this in doc-links.yml, scheduled to
      # run every day and open/update an issue
    - name: Build docs
      run: jupyter book build --site
