name: Run tests on the deployer code

on:
  push:
    branches:
    - main
    paths:
    - deployer/**
    tags:
    - '**'
  pull_request:
    branches:
    - main
    paths:
    - deployer/**
  workflow_dispatch:

jobs:
  test-deployer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install --editable . --group test
      working-directory: deployer
    - name: Run tests
      run: python -m pytest -vvv --color=yes
      working-directory: deployer
