prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:XzZ5DqIv5ZoAfgiirw==,iv:cm3TGGD60sg/pONntZBl8DcaFlwrA/mk1znkEV1Bc7k=,tag:qA+XZ/U7MqtoMHLgziNq8A==,type:str]
      value: ENC[AES256_GCM,data:GAO6uM2FyhXFnxsUUb3DARRHdcJGvTHLomzRRreeOmQFMua4Dop32dnb9UNp0K3NxOiP1dwa3QTp+D+F2Zsiylk46+w9pa9Kam92AmaiAh4DiP2vWKQbtGIMReSoKmZM4rICA09LvrTR4T3iyFhkZ8fwUqaqHOFhFf5nFE8O7md3D6iE1P4xKzrnY1oth48Efe3noLgbmPb1+ZXAAuDTspBBAJQbEBuFPBh7i0tKsmO1Qg==,iv:kNgyXVPJa/viXcPAYJ1+zAgufjcdB+dHrjobUDY/Qvw=,tag:g+Ho9uaKN3kefUyRWprXEQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        nujsn2Khn099xNWfnILHcIKwR53lYDtMiojwCbKR54t91KqNmJQoi5YQW56sKHf1: ENC[AES256_GCM,data:qVcjZkArfVFDaozm6pZXemFMu5GYCxVVoknGqdPdcKLjpjY5nFklKpzf1VVwuZ7DaUTpLACt6ZnlJ/vu,iv:PFuYgC1/TflaJ5Yo1z5CIS3aMK655ebPthWB/hromeI=,tag:PuE7RjyL0h5W8w9DuR8NIg==,type:str]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:hlIaCg==,iv:xEOoSq35mMvb+ysCDPFMAvrLql04/WYsMupT4qLixK4=,tag:ODrhYYA/k5b02PutUotUEw==,type:bool]
    username: ENC[AES256_GCM,data:/qH62lSxs5eID1/gKQNkizSTsUiWdbKk4VoWCcRXcqPtuqaLxeogJarE34q6FsUWAVPrR1BvmgjQkBp1Q8P6XA==,iv:wzHr/voPeiw+V/uE7LcXRWvyUzo4jXx0B8l6D+U7w/E=,tag:74r8/lYpPR5lR/0reYmLIw==,type:str]
    password: ENC[AES256_GCM,data:w/gJezLhbZmAdOFDsEAyvYbh91UlF+jNwo4qge7FzROOaqW5sV1TyLzjdYV2TN8QUSEXB62BKtXLhpElmWYEzA==,iv:W/EcfGLQw+U16jeaqCwE+UUz+yI6eg2MejkMQLQGeg4=,tag:4tWIGJqjR4lwqAyoH9hZTA==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:zTjBhuFnoRE2uwV+5lKH+1a4O7Zhz1el/GwxEhaijPZP+6XJvPQM0ps5O+FmKZJ3mVAXavbt4FhLfP9YOwP5dg==,iv:huQPnYS2gyAnNzmb6AbnBJY/NAEOzKwjFusISPjhgYU=,tag:/489jYG6vfExw9fIyzAiBQ==,type:str]
  password: ENC[AES256_GCM,data:AH7oFM/JWlsiOvt4cRVzoyZKQ5eeWpRLk33juVAwm92L3tTFzNKQVyNu8afaoXKfnORDAb9EBmi5pyFsWqw4Yg==,iv:NwvIdVbDTQ05Wo22Q6o2vqyoW43cE7abFJMXyS/DR5s=,tag:Iy7OAWeRgqgi6fMCnHoCHw==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-21T10:21:57Z'
    enc: CiUA4OM7eEudhAZfDK6bJ+QbHzGpcTiqheL+KLplEAQzYmBqX9sCEkkAmy+ekp2OBafe21BtlvN/50OG1BlV75aDUWvT7Dh2WdLVz4sh+SfU6IVQdEJBx3BhzJc0ytz5X+5ck809F20w1cndaWt6x/Oi
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-21T10:21:58Z'
  mac: ENC[AES256_GCM,data:t5dXCHf1N7osb4q4vRfBZLZUBy1QDuwfz0IboQ+YfRGJ5Sp813g7FrWhrrqVz16eI8ylqMKBwi6RbjM0AMEHIvSfZJEzxWmAWSM5uPOiSFkLnuQfH6jZESmL0/yySsOFKvPxNukFlzTfI02jKHEMR3I03w1yt9z37gLMySuSdjA=,iv:9T1PwmBfmcfyZM5+boWA0MY9wA4PEJl44IPJNDNa168=,tag:ki7u0ILxMZFNL/MyP/y0HA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
