jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:g/JYI8QtNBBsQj5rhGmWXRSkSn7G6v1iVpIX6JRK+2d0/VxL2rm9KXXbP/yOwh6AyWin,iv:ogbLQt6b9oDyDkAUeHN413brfJ7/tKnaYHIpMeDWMdI=,tag:YtkyZJn8GWAFYpHDYFPIrQ==,type:str]
        client_secret: ENC[AES256_GCM,data:VMdhuQCCMziJYP9Sr2yTEoAP+w0GpH7jCzBPok6VzYgaNT7gKwi61PnVEy92PnnIDa7jpiuXbSdgRtDpvP52CvMap3Z4rLXvVJoexBDRh9hHoOeO0XI=,iv:MBZutMysqxaG03Rc5YgsVyNk53Ay1ucmeE9IMsnb5RE=,tag:dcKNJOekEA06uc/ZpFUnPA==,type:str]
jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:ml6mvdpdht5wYj03cscvd3G/xTrnEJQSYokRYRZk5qD+Ln+amYt+2woarz1KZ88WiEI+p/agVGWxOYxtdPyI1U6WtWyLQfJjcKqJUlCYs0k07JsrJkPMfdMLD6SdRq03+lp9ZVvpsf+No1aMfieSVptusLuhPdjk2H0LwFcVrw==,iv:8PGMdO9XJyfnSr9lX6886z3ULlCDXwoGysT3N+qrLys=,tag:NTeZd/pA8SrAath47WkYRQ==,type:str]
sops:
  gcp_kms:
    - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
      created_at: "2026-06-09T22:05:09Z"
      enc: CiUA4OM7eP74aUfuZF7QAXoE/zIX2i9Brvp58k5Ga6RyNUiE3p5WEkkAmy+ekhZeUaE0rs/J8C+xsPuuvIEvOmxbzXTbaLdhA0Jgu0X0U00Le2RFKlRGDoCm/2CHcCSwypOLj/3NMeQczWiywir6+2NX
  lastmodified: "2026-06-09T22:05:09Z"
  mac: ENC[AES256_GCM,data:Htj9VpNI3N6dLgWPFZQjqLGePeOc2qwpxgeI6GX/agDfhxTGXzFTFBqtCe+0VHaZq6rgVD0Vfd3PfrYwRC5RpgyEyyu6O4DGvXZHUBnAbJiTI9NgrWNK7BUYAlG7CnIJgnZYhjpr0JYTfFPlIfJTBfKzuDQw0yduYod9QrAe/to=,iv:pHiPt2hy8YEbov6yvb6uoqLCJ8P+dsOtymxyMiuem9I=,tag:uTNYY1L3SIYFfzYax+Qj6Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
