jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:g/JYI8QtNBBsQj5rhGmWXRSkSn7G6v1iVpIX6JRK+2d0/VxL2rm9KXXbP/yOwh6AyWin,iv:ogbLQt6b9oDyDkAUeHN413brfJ7/tKnaYHIpMeDWMdI=,tag:YtkyZJn8GWAFYpHDYFPIrQ==,type:str]
        client_secret: ENC[AES256_GCM,data:VMdhuQCCMziJYP9Sr2yTEoAP+w0GpH7jCzBPok6VzYgaNT7gKwi61PnVEy92PnnIDa7jpiuXbSdgRtDpvP52CvMap3Z4rLXvVJoexBDRh9hHoOeO0XI=,iv:MBZutMysqxaG03Rc5YgsVyNk53Ay1ucmeE9IMsnb5RE=,tag:dcKNJOekEA06uc/ZpFUnPA==,type:str]
jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:isDYeIvJ0T1Pqbop/s6kl19qRnl6NKIzAcdxCY4S5fu7loktKhmwpSLpIIdJocHvMyh17Ake,iv:FHkHZjoO5wxaE+N+U4jvWz9v0nKz6GgGASlIbGbfR+o=,tag:8S74tpJ9sajFISskwVj9fg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-06-09T22:05:09Z'
    enc: CiUA4OM7eP74aUfuZF7QAXoE/zIX2i9Brvp58k5Ga6RyNUiE3p5WEkkAmy+ekhZeUaE0rs/J8C+xsPuuvIEvOmxbzXTbaLdhA0Jgu0X0U00Le2RFKlRGDoCm/2CHcCSwypOLj/3NMeQczWiywir6+2NX
  lastmodified: '2026-06-23T09:48:02Z'
  mac: ENC[AES256_GCM,data:dqhKH7YWBgUMnOrOVaRcTwLHn5PAiw18TYqnvfATbTuWrz+bFemnW+9x2iwUjybA3botDIOkvL0VigMYLhiliEE0a9+K0H21tRImFo6BFopm+5n+kjEsNco+xK/3BmtsrXqXNAhmuROj4YH+ITkqmjIIQaqcgXmFeY6DHQZIiz0=,iv:kk5rW6TcVksUJwIu+FEzOCElc1EKUIRXbP3w5mdsRAw=,tag:TTokoX6Dk7QYRxIgrHzcyQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
