prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:6y0bRFhE/vz5LwZDZQ==,iv:0CRgT4RSEJdupbNJte9pOQfaYIbPEomI6PWUWdcuPnY=,tag:juy6x9MftsEbLvj/cfrwow==,type:str]
      value: ENC[AES256_GCM,data:hctzrANVkYAviwX6EFl/8SyHI75fC3HuAutgoFqqc9xTMRqpmKlYovdRyRJx1SsUzqWGCjEK4W07V3sLIerGZxTiAsV6Zw9vjd1tfIKAAN7izrdmbkJ8hB936+lQo6RAKIXNoTzs/9UKtlkmulvdlBT80+2w/Tgb/wmfLqckNvQcGQ7NC5QZ2q46Z5zx0mRdD2X5jkTntXgPTjrqittzmKfktB/PXhQ8MzKFqjsmW3VRqw==,iv:Gql1iPDtvsiRIY8oxWI9eBXtlPi4Y8DBRkd4cuk9M0I=,tag:YKa9GFZ/S32eSQhYUhII1A==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:bqzBlBK17CS+9xESNMlwWN2VBSBeg0IqqpaTTWJ+VET4B+BaRbL8uR08i2dzEFuEeDPlvZylwNNev3vR9YrS0Q==,iv:ODAdtYEvFuPBhzO9P5b+RtiNMqIepTNarG9HgLUpz40=,tag:Mz3WmYIrAjQlwaYSOllJAw==,type:str]
        password: ENC[AES256_GCM,data:zwK1absCjeS00DVJ29PAQJUyFsU1h5dnjgLV8bCH6K1I/EOpIhHVt12WbcdjoytpYcbcB5I/i2PJWvuh/mH2lA==,iv:j/AImNfgkfbY+n5XuzqRsCsTqVPkzLee5qcr4hAYAzE=,tag:ZqpTuSBRfZ5bzHUpUJpcQQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        nujsn2Khn099xNWfnILHcIKwR53lYDtMiojwCbKR54t91KqNmJQoi5YQW56sKHf1: ENC[AES256_GCM,data:GxyMmcfDAIxCPQbjCrWqN18XG3XJ5oBiIVPuFF1L5i6UgvozRgJZ4Jj+456K/6Jygw9tj36w9wdNPwGN,iv:MWjgyLNPeL11Uq82xRpxZ6h5v80ZJ9RwZckS47jB4EI=,tag:UlRxnAKC1vjtIVeWsq9wMw==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:DQ==,iv:LnD72H7F4KzPLXPT4wd2eCzj+icLGDLyvhKG6qf2hIc=,tag:FxFxBM1E6c43+5zjDg4TlQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:sIIBZ1Mp5ij6cg==,iv:S7M4mK0MWny5yas8+06ZgxJAiyqI9P+HdE5fS3aZ9HE=,tag:2+G5giFyqbXGZ9CjZbaVUg==,type:str]
        orgId: ENC[AES256_GCM,data:9g==,iv:A5zBJOXKV2IY8KQYijNITBmV9dDyKtgz0Jg90zUykpY=,tag:U1HcVdj6qY8MV1hymFABrQ==,type:int]
        type: ENC[AES256_GCM,data:ddd2KqrCz7sc2w==,iv:pnBqlPriI0XN6XsPda+ew0BtVpHtXdHUNu1SjwhfKNI=,tag:ScwxweCQIQrOtfOE8f8wfA==,type:str]
        url: ENC[AES256_GCM,data:s8sOwePKnypnmhLwfVjeVXuhtNbSuaRdWMmxj6HzJUs=,iv:BsWZJzu+zYurZRbHCh32hPtbzrpRG33lOqqRhs5pbCI=,tag:OL9s6jvyq8+yISWSBeHRZQ==,type:str]
        access: ENC[AES256_GCM,data:ifI1IZc=,iv:zcjRIx8bhYUBnmAe5QAoOL8wfmShC0V5ZX62vSQXpIU=,tag:SES3teqBXSYsqBLpyutpRA==,type:str]
        isDefault: ENC[AES256_GCM,data:7fhTz8Q=,iv:4zyRvbR1URA+kDw7nlptxovE3YlXwARBbhgmOorS5e0=,tag:6pHC0gglTwPytWlHwoDw0Q==,type:bool]
        editable: ENC[AES256_GCM,data:t2+LmYA=,iv:z2SQNce6CBSZfoBz5VEWOz0g2EM9j+le0ToGY/DwCu0=,tag:XzeuUs8beTqqh+o3BsJ+cA==,type:bool]
        basicAuth: ENC[AES256_GCM,data:YuIGXQ==,iv:RgvcctCLtHbf67K9v42bWhmt3DTfXjqgAe8tHPh0YqQ=,tag:h8oOZ6pTsQZr9mJLym7upg==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:Hr7yv8BN3xBio8Wawycq81JFgD3P+PmT/Edvrw+N1y/+bRkWobLnIzhOfifx0BHrNueGGPffToRrlkjSNFMdUg==,iv:4T6upb4so5nrXnXLG3gy890zINUOUVqOVchsOd5rxCs=,tag:M2wiUueR8GJT3oNnNY3TmA==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:vrHDqtV7MKsHovxtqb0paswtoNl1ido+jnrOyZQsct+rqZtEe4cXLub1mxIv8GQ9vHwZO9qk0y+HId2Mk1JM8w==,iv:p8iDOavZvO3ZMAJkwTFk0RnBC1JHdf+JGJcutdwFJH4=,tag:rLM3tpPbm/iGlXxcPScBwg==,type:str]
      - name: ENC[AES256_GCM,data:R83K9Xcj5BYCIGGfi694evUXaddTmxcDfj2lhsNrfA==,iv:8HsLWms4Nij5MaXQDA2hVtFW3OwtH2B9YvQKdT5h7og=,tag:v/mTTfdhPf6dFSUTWjSgLw==,type:str]
        type: ENC[AES256_GCM,data:BbI8LddV9D03tm3RMX3iYQg/BoekxPa5LQYlEqgbDQ==,iv:HYrMU92OxQXHvYsfpDC4OSjzVQ7NmLCadEg54qYA8dI=,tag:d3L9MlD+jK0OMPCdYs5SCw==,type:str]
        isDefault: ENC[AES256_GCM,data:UeMPcTY=,iv:7mJAei80hMEsuHtED9k5eUmcCEquQq1ZpKaJ840LmG8=,tag:79wyqWAbDA2HiHAyef+oBA==,type:bool]
        editable: ENC[AES256_GCM,data:OVrrdg==,iv:MQ1VqbSafFq3ENjnvoMzfzNX/kuJaGKc0XofG904QVM=,tag:H7QhocQnjoPdqfk3c1YpzA==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:nS/GvA==,iv:niHLDkEKAbQDV0YLGVj5WEsB+m6bY4bVbKny0KIo+8I=,tag:rdR187ipR4GR5BakvAdEPw==,type:bool]
    username: ENC[AES256_GCM,data:h2gwz/qkNVKf0OZfK2Ccps/OKMBoEYL5gV9G99CeaErCN7av/zoH2ilvis61Ba0SgFJ8Mr6q55Ao3S8K0+Lodg==,iv:JbSq38DV4wjoqap7eA0j/NZcuyfY/MJfpzbTC1HNMow=,tag:iT8HNMakD/SohbjL+bwNBg==,type:str]
    password: ENC[AES256_GCM,data:isXmXCxMFHe7QbAPiXpCcUNg4uM7CAXtstgygQx7CcEhOOljVvzNTLiMW1+KvVcJA58/ve1DbHB4yBIwrngdtA==,iv:WCG9gbaYaQCyjDspUjv5Td3b+rFs/FkKevKU4Z/0jgw=,tag:EE9kez1JyA2Lt7GDJNdPHA==,type:str]
prometheusAuthSecret:
  username: ENC[AES256_GCM,data:cYjb+3iTUcpfXeL7H41FDCZbdlad3pLziLJxC12zqR+zO4iD+C7NXnPhmBdV0WlxUWZXW53IirlZg3fYYch+cA==,iv:U3RmWS8/pP0Hpd9f6/UxWmFuR/PQuJ0MErPDFrmBYSg=,tag:yei7igvBunyqmYZAwQ6eEw==,type:str]
  password: ENC[AES256_GCM,data:u7egkWCLOeRf84pJ3MMiobqr/D/RcbMdXWU3AZzhskpA7+pZwMjyHO1gTYNTGM82GeQoe0gYjOWclQuV3ZjGIw==,iv:/Xfvqxyu0PQnqO3Cl+eqB47gq+3QzTqYUiCr7nocXDs=,tag:O9nIieIgyETgw1Ksjco18w==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-05-20T10:11:18Z'
    enc: CiUA4OM7eDMyq4AuHBGzVX6A405M3ABt7eCNzxFV3MkbL7p8DLWJEkkAmy+ekt664uJGJJ5xnbzkiRvJUdjyvU7Wl7o6UN6TNywoQsZxycfyDbEiMXh/XZzfg5lzWi79IjcDCcuvtGPGlNWHHQDu2HmH
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-05-20T10:11:19Z'
  mac: ENC[AES256_GCM,data:mfzJuqCNrlTYja0vQ+y6816uzScjaNrs4wh168AohlBVfKLop0cU1VaYc35xTvZqRzx42/c9k70At0b9easQ0aY2VMk+bHXDTRy4q/8KStLmbR5KJgMMgsIjtxt270p7YtS4zF8W4ndDA705KYA6EYKEqKA3vA8WNbclLq8BkHI=,iv:SEBiCtklc8iyYyMySvwXIfiv2Z5EcbuiMzf7gSJt2Ms=,tag:rvEBBw0WfQ5QHQe7DA0X+Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
