jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:g/JYI8QtNBBsQj5rhGmWXRSkSn7G6v1iVpIX6JRK+2d0/VxL2rm9KXXbP/yOwh6AyWin,iv:ogbLQt6b9oDyDkAUeHN413brfJ7/tKnaYHIpMeDWMdI=,tag:YtkyZJn8GWAFYpHDYFPIrQ==,type:str]
        client_secret: ENC[AES256_GCM,data:VMdhuQCCMziJYP9Sr2yTEoAP+w0GpH7jCzBPok6VzYgaNT7gKwi61PnVEy92PnnIDa7jpiuXbSdgRtDpvP52CvMap3Z4rLXvVJoexBDRh9hHoOeO0XI=,iv:MBZutMysqxaG03Rc5YgsVyNk53Ay1ucmeE9IMsnb5RE=,tag:dcKNJOekEA06uc/ZpFUnPA==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-06-09T22:05:09Z'
    enc: CiUA4OM7eP74aUfuZF7QAXoE/zIX2i9Brvp58k5Ga6RyNUiE3p5WEkkAmy+ekhZeUaE0rs/J8C+xsPuuvIEvOmxbzXTbaLdhA0Jgu0X0U00Le2RFKlRGDoCm/2CHcCSwypOLj/3NMeQczWiywir6+2NX
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-10-08T11:44:46Z'
  mac: ENC[AES256_GCM,data:R/cJE9yI7E/x7tvZpCOselLdQhIsH0t2kdw8KLGHo/y/Q+7OPIDck2dIWy19G42tPdVlzmcvBzSoZPP1bo6CtuXn/aeIDiDu48PbuUWWR7jXWxgDCSKwTRwSHHIl/jaG+1ZvFVy3kvYj8SQ3xBIqq+l+xJsIUHlB8Bsn0cL5O7I=,iv:YZLiSAdOL3qmFymLYvndU0QPJfot87+ifJABuXx8zbs=,tag:SHpvdksZqMfOm2jY+h2Tkg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
