jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:jMtCfboNrzZHpb3DotxKesg242GKkPjlNCJ5jO47u9UryxErN9ekdArklq5z8hHSc2iA,iv:VsrUeCrlCXSKmSPMK+1n8LOOJkfEubIH8xo7eaCwjUw=,tag:MAGxuoAe99XFW+ZBSUm5ZQ==,type:str]
        client_secret: ENC[AES256_GCM,data:bPw3/FiLmYPx7mcoL2HbSB/FumgHWLn4u5+LIoMcgnc82++H3pKX+ErtgQQhx+mpzSKYNwBF8wOeS59CZYeYtnt16Wy3lvoBw9WmlEdOl8OJJqX4HBE=,iv:Y+i/zNC+OrRk7eL6HzcGJCp/1DbcYe8yPFUsXa3WikY=,tag:TiYmuxJSxmHDZw4pNhsQwA==,type:str]
    extraFiles:
      usage_quota_config_secret:
        mountPath: ENC[AES256_GCM,data:HQ1gN368GFiVRrusZxj4t611J/96rO+rlpBh+euR8zO+bPH5RMcYLoptGyvOxD2WVkzhJQsR/najVDR8+flDblY2tp5ufpiXlDx+t/5rmAzNbQNn90M=,iv:nKhLPZZtZiPKpUDlPUOJEbTPlrUGu3kvGlEH30lxNmw=,tag:MYpDIRCAA1dZDbYGdoV/bg==,type:str]
        stringData: ENC[AES256_GCM,data:UGT7cxGPnprx3kD7OJLcCdExXZe7j9CvL1dcIjIww+p9GSllY3Lena7lu1aujTWsRL9Cickn/k6AJ+d3pAk1eVKoqFXuU31v6XZVjZl5AjZWsC93jGdrKCnNxArs1nOdHWwqP0utIaFMYt3eS5ddXpjuWJv6uNomEw4VvXrbaXVa1nahphAb1PmyO5qIcsNhCQRM4fkEG/60q9mEw4Dl+vFr37FMfzqNxJg9/M/o3BtwL///QcJGv6e6Uz39A9GT2YYOe7GxldvuA4yMWBLlTTbqGiGs7FRuMGlQ7jJbwrhyRWGVUlgJNIwJo9ePf68+spDW8CLc5oHmcHZwDVWBPr5Y6i5Gabi3/LrsGlec97eI/zc3ughA/kIPl9+rjR6vY6V8vBvso19OkivKTZPtU+OY5k8zGMWFOMxrmUXqN+6jSNAkP3UGYDa4Wg8y8bF64FNFcwiBRFgHNI9TNgzZhCk01E5lks/sChDf4699TUcorlH0U23wQ6g2/CrSDE/AJNtslB4VNw5vdX1IO2/j00CoyGXnESlp6e+rWSIYdXeh8AkEvI8KyqhA+IVb+h3Bh96Habn0LKbVRuCKTZGf9OEcaAARH7M5yURdEdhH6p67RwDdnUWJG3FrWqATcxE70LYVGWU2cuHPAdby2Q==,iv:PaEdZJzuqW9dpInkS7l/DGBMBuWsc+PoWXjFTJE8284=,tag:9NiDE49F4CYBUqhlEyLqyw==,type:str]
jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:C17LoXI0o+C8DLy4+Rj7DgTctFtp+YJdNZslxBfP+N36iG3q8ObVwLNZSA1QBgGAsOBbqatfdg5loxGOK65oaH8JZuRVGLj4mu7cn2JL4UCs/agyqJtWqa483cE=,iv:2DRd1FXgkhcmDHIdYrJLQkSRL+lxWBdsQjRtDZVgD2I=,tag:XzR3ph4ma2VGzKiT4XFrag==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-07-29T19:16:47Z'
    enc: CiUA4OM7eFp00NA2WAwcJuAjwUYhTnWy44qxfeh4FSO5aly+9PVDEkkAmy+ekp06ligELm9NoLpTbX04yUN++nPdIYgkhmkQeeZcnS26LDl8hmjb5MJgNXpLgETn51jS8+pYFK5WUA0+inztH+nwlXKQ
  lastmodified: '2026-07-29T19:16:47Z'
  mac: ENC[AES256_GCM,data:gDV21zlRbo9OLA3m1z+KRI9nx9D/7IOUsvObnhiwUpm6qr7PXUdMIsWwTVYUaHC+PTY3QeEiQpsmXLFnGP6VfE95IKZnzM3/n5MuRPypOqTTA/+6Ca8RJI1fJDuMseElx1CBRHLQhlPh/v65QSIqjoCRepMQIj46pRuKDRwb83k=,iv:ul5TXfVV25McpFhGS2wU8jk8xkdVIguahMV5yZMmicg=,tag:/FpNTYIq/bUSsTmtIf0c4A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
