jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:awec+hcrpQMdjfQu7TkURNiUN1F1Z23WnrQctzzifcKijQwJGHpVvyxMf1b07RixHhQe,iv:+FkfwtV9en6lBZsmyI8iF835hrN0RUgokgG2M7rzb48=,tag:69/7cQmfJYW3ikJGSQXwXA==,type:str]
        client_secret: ENC[AES256_GCM,data:EaZxIAIdyTnaGzp1YfXs1Fq5iBiux7Hq2T5foRtE2iw9i9sYLI9lNKcaeUGLwrmJkyNkeFWFY+c1dirMeagLLBAcjGnfZzbMa/6b/4CApaml/HpZiR8=,iv:JJVQRoimqZTYKS9ICbecCCfkIzvSwAqBFtcvCjVguK8=,tag:1COcP/zqXwA+EULvTgMmBw==,type:str]
jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:5zqw58zeERVx2VSc7485LRgQMegdsgpYdi0dBleFUY7FJH/EQO8zV5Gq+dFiAu6nFcceVWMBrMRf7KEsSkMnMvwQOiUQdd3ugDUDUN1iITFX,iv:0k91elQTBvBsdbFUvlHkH2oiRgJBvGXvN9E8FxQy/yc=,tag:dAIbGWEDccYaN7SBiMhx7Q==,type:str]
sops:
  gcp_kms:
  - created_at: '2026-10-08T12:42:41Z'
    enc: CiUA4OM7eHUmVQug/KSTxI+Oxriv5dwqlJZ7EuyJVSVZM9az0tbEEkgAsHDElxz10Xl2ibmkT1mwvv7EccAa5wQcIWBOM6BzxgNMjMk4uAbdZexrlvQrDpKyO0v3WbKMKYMKV6euDOGcZg/epkzee+E=
    resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
  lastmodified: '2026-10-08T12:42:41Z'
  mac: ENC[AES256_GCM,data:kRaO0RmX8Mudi/H+rjVyRKeSkVUDe9Z/vGWzZiT1AkcGaVNOH06KRbUTPW2PUDpuz9IHOiidNeifaSAS2MFz13nzVE/6IVik/oeQg0V/yiLLb7Q8VydaLlUUI8JZGzE6gDZVuV+/2rChvxxAPABtM3ZXRyDjR4fIXoUWC7iKrdI=,iv:Sz8LA9OcM2IQis0xybOX7ZjsahmLgrCKtrOIc9u+OAA=,tag:riAHXfaAbdyu57vR+GxJ8g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
