prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:kc3MQGFjBK8hbtfXRcZvxSGBGGY1i5l4vVC0pAFYvpbwRkzvvDVtfOs8XxZ2mK97BDyRem5o7gIbvtRAcED5eFdjtprcrv1pteIoYsXviEbw6dR1aOkr67KqRu5LZGUflKPk5b4oMjLKApFUq8MDgMgGadUQqlXUuyP1RhEJjrKsL9KuhJA20+yG7ljJVaWaSeDzEFRqdCYEClNz,iv:kVt9YLxnxxI9G1TzQOUh/31g902xdj7pUz+esNLtpyk=,tag:Wxdys1k28J0GMH6NkHxb/Q==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:HGAJzm0fekA75JIMQ2iSZMwuu857GZMvVkXsosmNSHiXcz5K8bSBbDngdS/Ky5iz1ti0v6zWpBPpPgNyZbi7aQ==,iv:qdP6YP4gWTZ3kP/iq8lOc0QmFj27nJwYsZ+pEvmypjw=,tag:m9lxX8lKYNA++limiNexZQ==,type:str]
    password: ENC[AES256_GCM,data:V1M/DcX+CbgK3BWHh/vetbfpYWVi3qlXRCipPX/BgieY2Tot5baK8h4A3ZfAvrjUml4p89ZAsi9vm3anDXBxEg==,iv:IcIYFeCK7tKHxuTTJwf4KFh1Jpkm9m+32AJt/Sf9uJ4=,tag:xCR1bxDFyOX0FKNT2OYgdg==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:RhsJU22kxUBSbqYkOg==,iv:VED413WbNrx3p1vmGKU9SlCGR4Oms37YLF1b4oRvEJU=,tag:IIoaJWRQyPWCY5ysnzEZGA==,type:str]
      value: ENC[AES256_GCM,data:1yuXrHMoocjxmov3j9xLBQXORmu8GIcG/+fO9ZefsASFgIdzR1xi14fb+5Zu4XdluQMS46a72t6a/izFvs6Evc7S8rkdzfDi/eEmJarATCeR79WD/yV726FvhOGZif+k3N/AgCbhZSixWuskqQVPdh+8rM85bbbDDy1nHWoMgPuHDRLs3J/WC2IfyHIt+dVVz4GhcNQYSO7SaMNOQ3INXmU2H6jIIxp/8QPx+cTyZuY+gQ==,iv:0vXq1jDMOfUxGg0sC+nu8FRyh0jBDiDrF0RZlhzeZM4=,tag:NjHS6MZLkcGZt6JANjD+Wg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:/SUfpC7NMy+GepR+f3Zixh1F2Qir47DMpK/yL+I5uSoBOE0fG+J6PRsLrc+dymRBcgJ/+vNysSTGPVSR2XACXA==,iv:kQekiP5u4reWvKlDbOCV9Wx/2cR+FopowqsnV5f1m8A=,tag:4/yLq4Norgu5fkEfIIO5vA==,type:str]
        password: ENC[AES256_GCM,data:N5u4G0GuK4lMm5Wl/zdt86f/vcWmtNV77zPc908IV9VPgbBmXA7nsiSXcZUDsWruKcIqMkMlQOz0cl0zcUiSfA==,iv:68nkazTDV11RXp+fY3VEsbEwDAJeK3lrXnQ4793aGVo=,tag:dT2tNjQpZ5u+XYGPb7hYog==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        nujsn2Khn099xNWfnILHcIKwR53lYDtMiojwCbKR54t91KqNmJQoi5YQW56sKHf1: ENC[AES256_GCM,data:UYFT6vtpyfNjWaW2zowMijLur2tKCkeV20bT0PlkMLP8qJvmDV6OW+nAM0Hu/iRyIarEG3cDz8w/fMZy,iv:namo+2BH+7cAULhh4a6zTsJqhPgKyVRpZKWnlW9in3w=,tag:NV4uP2EHy9/b40I8LDf0iA==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:kQ==,iv:X1bq1ZU41TLLx4nXcVDqoMDNuHMLXI8IsRb9tBvYHdE=,tag:zTADqXf2zwNX8DFzWliGjw==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:O3NCSSIa7upoBw==,iv:IbOB6ACKPVJYToRdhpn1orSb6zI3Xdr5yhkAcS+ftrI=,tag:baQ1iu9K7jdBdSxOAa7E/A==,type:str]
        orgId: ENC[AES256_GCM,data:5g==,iv:QKeqRpl4/X6TjQhuVhz82gU228AqeuOkEVFsJ+Fcrf8=,tag:t/h9vn+SJ7mAAIB79KH5wA==,type:int]
        type: ENC[AES256_GCM,data:tRi43adrbiBrPA==,iv:6BFBIjM9Vlk+f+4tKg5fYvBohhagpqEF/VY28UkpSWk=,tag:AMszG9+A3UCW8Xwa1cnnbg==,type:str]
        url: ENC[AES256_GCM,data:BMj6Wk6MZXXyE6OBdY4j14JiB5SKNvMdEU+KpibvBhQ=,iv:nqUf5LKw7lCxpE5NLuy/6t1pI4cHIaEROLVs70x/tN4=,tag:2TQz1xJe3HpxzP/cFSnvmQ==,type:str]
        access: ENC[AES256_GCM,data:L07eYLo=,iv:eTscyMXvLAcshOtzikDi+YppOJznHcP0M1LIE+nOKGI=,tag:VqPrqkH44LfEFOvu6RWWFQ==,type:str]
        isDefault: ENC[AES256_GCM,data:fYJfJAk=,iv:HW4bxyOgJMzBIC8JiEsuGexrTc9aHawDQDugNHhYyg8=,tag:W3tms0pgvffaXrOgyW8gmw==,type:bool]
        editable: ENC[AES256_GCM,data:hnIEtzk=,iv:g9NYejT6cDo2dwtl21ji5WYHsPe6vkXKGkOEI2Ye5Ow=,tag:GuAb4rdMusy6BJugVPC7lQ==,type:bool]
        basicAuth: ENC[AES256_GCM,data:SBgr7Q==,iv:u1QUQzLML532CH+Hxl/g8H1tmOdVZ80b2U3KBQuLDto=,tag:Kv//btP/pXsSCqeSVw3evw==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:br7fYHEgWUE3N3CvhXdxjmdns/e/TuGoQsaMAO7yj4yLNT1+rLJWHfb3w4uga4tsJ3QPPnOxH64veXvm4xHdvA==,iv:5rDRJULHEZ4OW4wDtwGKoSCHd+78CVox0jSV57ik67g=,tag:a0KCFTB3VbGsa/FxoLtJ2g==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:54NpxejTjcyePcnlR9zP+wQ29Hq0+5ukyAS/iAq9L6drfBZRICO0nhzSM4hU8fOr0QDlL3nor+04N/4pNP8Cqg==,iv:CgNPEicwTZX0mixO1Q8qn7zU/+S1nPj5CkhH0XWVrGE=,tag:B9oVoKscKaxK/E+urHeaTA==,type:str]
      - name: ENC[AES256_GCM,data:HtO5hGVO4hm3GjO6vlf/VfvrmdWpEOyhMVj86sTr0w==,iv:+XBpBge6lrvB6a2dtJE3j5JPCxbgOWHOUyz/awWqCv4=,tag:CFkEM5QXXTsBxaT5RCiJ8w==,type:str]
        type: ENC[AES256_GCM,data:Be8r0tgpJABHv1xnU9kZ1O1+DI2hlcuxk3LsTeh/5A==,iv:Rat+IuaRXYxv2uR1W+/QAMih9D7st03J1VsQwU4d7kE=,tag:JQtJUnZvng8shAtRP/8rdQ==,type:str]
        isDefault: ENC[AES256_GCM,data:TKI6zSo=,iv:KrdJ3Zdv9RWEbHAt9EV5RPbv2WO0LdhLwHUo2quj2h0=,tag:9reaoFex6C/CO2pCuU4fAA==,type:bool]
        editable: ENC[AES256_GCM,data:dYJH5w==,iv:DAqXED5xlmunMBR7Kr78vqGGXuTuSsonrwDJ/NTzfPA=,tag:eIKacB552849HyT2OQWM3Q==,type:bool]
jupyterhub-cost-monitoring:
  prometheusAuth:
    enabled: ENC[AES256_GCM,data:IUn03g==,iv:D6UH3rBRofqz8gZ8a6oRHh1sUBWCxsrBLv2tPMh4PBY=,tag:XI4hXDd/JGDqb3cEo5TZlg==,type:bool]
    username: ENC[AES256_GCM,data:+8Pn0EQm30I0AcEyhn7xPfT09hgEXf1bqAdl+307282grI13yctq96dupx56q9lK6dUoGNFndZ+kBdBKqNpZGA==,iv:TdDpRDsmmLprdA0AOwUJwyFM7LiQU3QT9925s9tCW1M=,tag:qAqf7Fzq9Li9M6IhlnHl/g==,type:str]
    password: ENC[AES256_GCM,data:TKheuSDJdpyvzj7vu1zN9N876QdHyk8CPph2RB0p5Qwwzmsn4izPromGisiZVDk4vRd0DU9P4Tujba1IP3TTGA==,iv:fZ4U5ex2YdNKEjtI/RiKagUZjxXqZziOPm8bFI+UGx4=,tag:72cf6gc2tducrpJgGhDazg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-05-01T14:40:42Z'
    enc: CiUA4OM7eKPr1RprHvOkFakQNDpri99V1IhFwWquwxhEa2sK2pWzEkkAPHlbme4VrBPLX4DsSkrmW2dYeoOdck6jUYu952RZYZ/xOIkT7ByuShgnqhkvC+9UA5j7zQscZ+YGWz54cPNtxNgYSLBR5gXG
  lastmodified: '2026-05-01T14:40:42Z'
  mac: ENC[AES256_GCM,data:GqmPG1I5ECD6ak78Xa5+FW9FrSu2iNCl1pGPJ14yUEdXBrg2x57E2sFR/QJAMdSoxca7hdO74lzYM6z5792B+JWYn91LDcPcONYXOyQA36Jsynm/PxAcyL659PWIE7tE0WVreWr9SVNZS12khVeyYu2CXp9uNwYXH5BUFIc5jJ0=,iv:xogAICBjLZFPa4Y2I1vFFgypKwEH6jYL8tOru98kkzE=,tag:JLIAQRKzCAGHjVfDstL4WQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
