jupyterhub:
  singleuser:
    profileList:
    - display_name: Python
      description: Start a Python server with JupyterLab and scientific Python stack
      default: true
      kubespawner_override:
          # From https://github.com/SaiUCM/example-inherit-from-community-image
        image: quay.io/cirt_ucm/jupyter-scipy-xarray:1e26b42ad87b
            # Launch into JupyterLab after the user logs in
        default_url: /lab
      profile_options: &profile_options
        requests: &profile_options_resource_allocation
          display_name: Resource Allocation
          choices:
            mem_954_mb:
              default: true
              display_name: ~954 MB RAM, ~0.1 CPUs
              description: Up to ~8 CPUs when available
              kubespawner_override:
                mem_guarantee: 999856524
                mem_limit: 999856524
                cpu_guarantee: 0.1176765625
                cpu_limit: 7.5313
                node_selector:
                  node.kubernetes.io/instance-type: r5.2xlarge
            mem_2_gb:
              display_name: ~2 GB RAM, ~0.2 CPUs
              description: Up to ~8 CPUs when available
              kubespawner_override:
                mem_guarantee: 1999713049
                mem_limit: 1999713049
                cpu_guarantee: 0.235353125
                cpu_limit: 7.5313
                node_selector:
                  node.kubernetes.io/instance-type: r5.2xlarge
    - display_name: R
      description: Start a R server with tidyverse & Geospatial tools
      kubespawner_override:
          # From https://github.com/2i2c-org/rocker-with-nbgitpuller
        image: quay.io/2i2c/rocker-with-nbgitpuller:3edc87d73e3d
        default_url: /lab
            # Ensures container working dir is homedir
            # https://github.com/2i2c-org/infrastructure/issues/2559
        working_dir: /home/rstudio
      profile_options: *profile_options
    - display_name: Custom Image
      description: Bring your own image to test
      kubespawner_override: {}
      profile_options:
        requests: *profile_options_resource_allocation
        image:
          display_name: Docker Image
          unlisted_choice:
            enabled: true
            display_name: Custom image
            validation_regex: ^.+:.+$
            validation_message: Must be a publicly available docker image, of form <image-name>:<tag>
            kubespawner_override:
              image: '{value}'
          choices: {}
jupyterhub-home-nfs:
  eks:
    volumeId: vol-09923c5867cea492a
  quotaEnforcer:
    config:
      QuotaManager:
        hard_quota: 5 # in GiB
nfs:
  pv:
    serverIP: 10.100.147.181
